### ISSUE TITLE
Option to add ticket's Cc: to an username, not just e-mail

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1003]
**Reported by Pepo on 3 Nov 40844512 16:53 UTC**
In the past, there was an option to add ticket commenter's username (actually, there was a free edit field) to Cc: option.

Since the Trac SW update, this option was gone, replaced by commenter's (previously publicly visible!! currently at least partially obscured) e-mail address with an optional checkbox to set and use it. If, then the reporter's username with a checkbox should be there instead.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1027

**Comment by ChristianBeer** [comment]
Not applicable anymore since we moved issues away from trac.
