### ISSUE TITLE
Info in systray status balloon isn't updated when manager is closed

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1006]
**Reported by zusel on 25 Dec 40881421 17:46 UTC**
The information about the work unit progress in the status balloon of BOINC icon is updated only while the manager is open. After it's closed, the last info will be shown.

Tested on Windows 7 x64.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1030

**Comment by ChristianBeer** [comment]
Needs to be investigated if this is still a problem.

**Comment by Ageless93** [comment]
Hmmm, testing it with BOINC 7.8.1. I see in my Windows 7 that the icon's balloon only shows:
"Computing is enabled. GPU computing is enabled. Network is enabled.", it does not show the progress of the task. Has it ever done that in BOINC 7?

**Comment by RichardHaselgrove** [comment]
I think WU progress indicators were removed by c95f0e1a915b2ff3c7e17ed016ec9d44f0c63647 (2010), in preparation for the introduction of Notices. Agree - close as ancient history.
