### ISSUE TITLE
No useable GPU found

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1011]
**Reported by nor on 15 Apr 40907231 20:00 UTC**
On ubuntu, meerkat with latest updates, NVIDIA ION GPU.
No GPU found, but when doing a 

"sudo /etc/init.d/boinc-client restart" 

GPU is found.

(Have another computer with a ATI Radeon/Ubuntu , and having the same issues there)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1035

**Comment by romw** [comment]
**Commented by SteveRC on 13 Jun 41041632 00:53 UTC**
Checkout info on Ubuntu bug report here:
https://bugs.launchpad.net/ubuntu/+source/boinc/+bug/587426

Would it not be possible for the Ubuntu/Debian/Boinc developers to all put their heads together and come up with a common install strategy to prevent things working differently depending on whose install scripts are used? - (and allow updates from Boinc website to code installed by Ubuntu Software Center?)

**Comment by ChristianBeer** [comment]
This is an issue with ATI/AMD GPUs where computing capability s only made available after logging into an X session.
