### ISSUE TITLE
boinc SEGVs if running on gluster/fuse filesystem

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1015]
**Reported by glynreade on 3 Jan 41041122 20:26 UTC**
I was having a problem running the boinc client on a CentOS 5.5 (64 bit) machine in that it would segfault while running the underlying application (observed with seti@home, einstein@home, lhc@home).  At first I thought it was the 32/64 bit issue discussed elsewhere, but it continued after all the appropriate 32 bit libraries were installed.

Eventually I tracked it down to keeping the boinc/project files on a glusterfs filesystem (see http://www.gluster.org/).  Note that glusterfs uses fuse.

Once I moved the boinc files to an ext3 filesystem, everything worked as expected.  Even if this is not fixed, it is worth describing in the linux installation notes.

I have seen other oddities with glusterfs (which is probably due
to its fuse nature), in particular programs that call setregid(2).

Linux 2.6.18-194.32.1.el5 #1 SMP Wed Jan 5 17:52:25 EST 2011

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1039

**Comment by ChristianBeer** [comment]
FUSE has evolved since this report. This might or might not be an issue still. If it is please open a new issue.
