### ISSUE TITLE
Spanish translation of "Main page" is wrong

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1018]
**Reported by teleyinex on 28 Jul 41085751 06:40 UTC**
The Spanish translation of the term "Main page" is wrong. Adjoining you can find the modified es.po files.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1042

**Comment by Pablohn26** [comment]
I do not know the component and the string teleyinex means, but this error is outdated and seems fixed.

**Comment by Pablohn26** [comment]
Could somebody tell me where is the string "Main page" located? I have been looking for it without success. I really want to close this issue but I cannot find the string on Transifex.

**Comment by ChristianBeer** [comment]
I think I remember that "Main page" was renamed to "Home". So this issue might have gone away over time.
