### ISSUE TITLE
does boinc really need execmem selinux privileges?

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1019]
**Reported by mjakubicek on 22 Sep 41137490 05:46 UTC**
Please have a look at https://bugzilla.redhat.com/show_bug.cgi?id=665453.

In short: boinc project already have the execmem privilege, now it looks like even boinc needs it, which seems to be a bug.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1043

**Comment by romw** [comment]
**Commented by davea on 25 May 41149903 12:00 UTC**
seems like an issue with the Red Hat installer, not w/ BOINC

**Comment by romw** [comment]
**Commented by Nicolas on 15 Sep 41150345 10:13 UTC**
It would be a problem with the Red Hat installer if the privilege was needed and it wasn't being granted. The question is if BOINC needs it.

"the boinc developers/packagers should explain why it needs this access or fix it so it does not"

**Comment by romw** [comment]
**Commented by mjakubicek on 3 Dec 41151243 13:20 UTC**
Nicolas, thanks, that's exactly the problem, so let me repeat it:

It is not a problem to grant the privileges for BOINC, but there seems to be no reason for BOINC (note: boinc client, NOT the boinc app) to have it.

**Comment by romw** [comment]
**Commented by mjakubicek on 23 Aug 41635841 10:13 UTC**
ping -- could somebody please explain? please refer to http://www.akkadia.org/drepper/selinux-mem.html for possible causes.

**Comment by romw** [comment]
**Commented by Nicolas on 15 Mar 41636471 13:20 UTC**
Do you still get the error? Can you get a backtrace from the system call that triggered the SELinux check?

**Comment by romw** [comment]
**Commented by davea on 23 Jun 41638452 09:20 UTC**
AFAIK, nothing in BOINC (manager, client, or applications)
uses PROT_EXEC anywhere, so they don't need the execmem privilege.

What exactly is the problem here?
Nothing in BOINC uses SELinux features.

**Comment by ChristianBeer** [comment]
Original bug was closed because of inactivity and EOL of the distribution.
