### ISSUE TITLE
Scheduler 5[pct] or 10[pct] of all WUs in queue before before finishing WUs from project

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1022]
**Reported by aspadistra on 16 May 41150897 11:33 UTC**
Scheduler allow project to compute up to  5% or 10% completion of all WUs in queue before before finishing WUs from that same project.

This wording is not perfect.

In essence, if I have 10 SIMAP or SETI units -- go up to 5% or 10% completion of all WU in the queue.

Once all WUs of a project are at say 5%, then complete a WU from that project.

Information obtained as a by-product of this scheduling practice : 

-- The scheduler obtains a very good idea on the ETA of a Work Unit.
-- Knowing the ETAs of most queued WUs allows for much more efficient scheduling.

Projects this is best suited for
-- SIMAP 
-- SETI 
-- Enigma 
-- QMC
-- Cosmology

Projects this is completely unsuited for
-- Climate simulations, any
-- Prime number searches, or long run maths WUs
-- Mostly these offenders are known and they have Due Dates very fare in the future ... mostly beyond 45 days.
-- I am not wed to 45 days, this is a guesstimate ... 30 or 15 days may be better numbers.

How should the 5% or 10% WU completion be turned on?
-- It should be up to the user to turn this on at the Client user interface.
-- The "Projects" tab is best suited for this.

How should the scheduling feature be be disabled?
-- It should be automatic based on when the WU is due.
-- WU due dates beyond 45 days, FORBID and INHIBIT.
-- There are more than 1 existing BOINC client parameter available to determine this. Some experimentation will be required.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1046

**Comment by Ageless93** [comment]
Is the scheduler ever perfect for all?

**Comment by lfield** [comment]
This suggestion is 8 years old. It doesn't really describe a problem that is being solved.
