### ISSUE TITLE
Add notice categories and user prefs

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1028]
**Reported by MarkJ on 20 May 41216886 05:20 UTC**
Add categories to notices.

Allow users to select what type of notices they are are interested in, so they can opt-out of certain categories.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1052

**Comment by lfield** [comment]
In the new GDPR world, opt-in and opt-out are important. However, I do not see that we have categories for notices.
