### ISSUE TITLE
GUI Discrepancies when Project Name is not set

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1029]
**Reported by JacobKlein on 19 Aug 41244560 17:20 UTC**
On Projects tab, if Project Name is not set, the "Web Sites" task should show Project URL.  Currently, the button just has no text, which appears broken, but when clicked, will go to the URL, and is functionally in tact.

On Statistics tab, if Project Name is not set, show Project URL, like Projects tab listing and Disk tab.  Currently, no text is shown, so the Project List and Graphs are missing labels, and it is impossible to identify which project's data is being viewed.

Note: This ticket is to correct the UI.
The project URLs that do not properly load a Project Name when attached via BAM! are:
http://isaac.ssl.berkeley.edu/alpha/
http://hydrogenathome.org/
... I will be reporting the failure to get Project name as a separate ticket.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1053

**Comment by romw** [comment]
**Commented by JacobKlein on 15 Oct 41332645 20:26 UTC**
This ticket is related to Ticket #659, except Ticket #1053 also mentions that the project's "Web sites" button needs to be fixed.

Hopefully someone can easily fix both tickets at the same time.

**Comment by romw** [comment]
**Commented by JacobKlein on 14 Sep 41333788 23:33 UTC**
2 more places where the UI is not correct is:[In Simple View, the tooltip when hovering mouse over the Project[[BR]([BR]]1))]2) In Simple View, left-clicking the Project

**Comment by ChristianBeer** [comment]
This seems to have been fixed in the meantime.
