### ISSUE TITLE
Suspended/Snoozed GPU tasks do not show correct Status details in Tasks tab

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1032]
**Reported by JacobKlein on 1 Jan 41244865 16:53 UTC**
Currently, if a GPU task is suspended or snoozed, it just says "Waiting to run".  This is not correct, because it is inconsistent with the statuses shown on suspended non-GPU-tasks. The following 3 examples all should be fixed.

1) If GPU task is suspended because of computing preference, it should say "Suspended - computer is in use", like suspended non-GPU-tasks do in that situation.

2) If GPU task is suspended because of "Suspend GPU" activity, it should say "Suspended - user request", like suspended non-GPU-tasks do in that situation.

3) If GPU task is suspended because of "Snooze", it should say "Suspended - user request", like suspended non-GPU-tasks do in that situation.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1056

**Comment by ChristianBeer** [comment]
Working in 7.6.33 must have been fixed in the past.
