### ISSUE TITLE
Windows 7 Screen Saver Install - Control Panel Personalization does not show Screen Saver set to BOINC

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1039]
**Reported by JacobKlein on 2 Oct 41245399 04:53 UTC**
On a Windows 7 Screen Saver Install, it appears the Personalization options are not properly being set.

Control Panel -> Appearance and Personalization -> Personalization[[BR]]... shows Screen Saver set to None (see first attachment).

If you then click the Screen Saver image or link, a Screen Saver Settings dialog comes up that shows the Screen Saver set to BOINC (see second attachment).

The actual functionality is working. By that, I mean that after install, if I let the screen saver kick in, it is the BOINC screen saver that runs.

But the installer needs to make sure that the Personalization screen shows that BOINC is the Screen Saver, instead of None.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1063

**Comment by Ageless93** [comment]
Is this still an issue with newer BOINC versions?

**Comment by Ageless93** [comment]
No answer, so closing for now. Assuming this is fixed.
