### ISSUE TITLE
all_projects_list.xml - New lines do not look correct after file is downloaded

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1041]
**Reported by JacobKlein on 6 Jun 41245552 02:13 UTC**
On a fresh install of 6.12.19, after the install but before the manager has run, I can right click the all_projects_list.xml file, and Open With Notepad, and the new lines look correct. It looks like an .xml file that is also human-readable.

However, if I click "Launch BOINC Manager", and let it launch, and it auto-opens the Attach wizard, and auto-downloads an updated all_projects_list.xml file... if I right click it, and Open With Notepad, the new lines are all messed up. I'm sure it's a proper .xml file still, but I can't read it, and want to.

If I open in Wordpad, I can read it. But I should be able to read it in Notepad too!

Could you please fix the Carriage Return (CR) and Line Feed (LF) combinations for this downloaded .xml file, so that it is readable in Notepad?

Attached are the various .xml files I tried to open.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1065

**Comment by ChristianBeer** [comment]
This is kind of expected behavior as the file comes from a Linux server. Since it is not meant for the user to look at I don't see the need to change CR to CRLF just for this fringe case.
