### ISSUE TITLE
When adding a project or account manager, the final step should not allow Cancel.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1044]
**Reported by JacobKlein on 27 Aug 41245708 06:40 UTC**
When adding a project, the final dialog says:[added[[BR]([BR]]Project)]This project has been successfully added.[Finish to close[[BR]([BR]]Click)]... yet Cancel is shown as an option, and when clicked, appears to be functionally identical to the Finish button.

When adding an account manager, the final dialog says:[using account manager[[BR]([BR]]Now)]You are now using this account manager.[Finish to close.[[BR]([BR]]Click)]... yet Cancel is shown as an option, and when clicked, appears to be functionally identical to the Finish button.

In both of these cases (where project is successfully added, or account manager is successfully set up), the final step should not allow Cancel.

It should either be greyed out, or better yet, the Cancel button should not be shown.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1068

**Comment by Ageless93** [comment]
Probably an easy enhancement, remove the cancel button on the final screen of the add-account-manager wizard.

**Comment by AenBleidd** [comment]
Please assign it to me. I'll fix this

**Comment by AenBleidd** [comment]
Fixed in #2195 2195
