### ISSUE TITLE
BOINC takes up to 10 seconds to begin suspending on cc_config.xml exclusive_app application; should be < 1 second every time.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1046]
**Reported by JacobKlein on 22 Aug 41245804 03:33 UTC**
In my testing, under normal BOINC loads on a fresh BOINC install on Windows 7 x64, it can take anywhere from 1 to 10 seconds after an exclusive application is launched, for BOINC to being suspending tasks.

This should be tightened to happen much more immediately. I expect tasks to suspend within a second, every time.

I actually rely on this feature for some of my games, and I've noticed that when my games load, they're competing for the processor until BOINC suspends the tasks. My games should be able to load faster.

Please make this respond quicker, hopefully within a second, each and every time.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1070

**Comment by ChristianBeer** [comment]
This might be fixed as I recall changes so that exclusive apps are checked every second. Needs to be tested.

**Comment by Ageless93** [comment]
No, it still takes several seconds before BOINC reacts. I think the polling
is done every 10 seconds, which in my opinion should be fine.


-- Jord van der Elst.

**Comment by lfield** [comment]
This request is 8 years old. I agree with @Ageless93 that 10s seems reasonable. We have to trade-off polling frequency and response.
