### ISSUE TITLE
When adding a project, failed username/password should not show Next, and should not place the failures on a stack.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1048]
**Reported by JacobKlein on 30 Mar 41246410 06:40 UTC**
When adding a project, if you do not use the correct email address or password, you get a dialog that says:[Failed.[[BR]([BR]]Login)]Check the email address and password, and try again.

The problem is that you are allowed to click Next.  You should not be allowed to click Next. You should be forced to click Back or Cancel or close the window.

As a side-effect, if you click Next, Try again, Fail, Next, try again, Fail... it places all of these failures on a stack, such that you can then click Back Back Back to see several failed login screens within the wizard.

Please do not allow "Next" on a failed login when adding a project.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1072

**Comment by ChristianBeer** [comment]
Needs to be checked if still present in current 7.6.33

**Comment by Ageless93** [comment]
Testing with BOINC 7.8.3
Trying to add Acoustics@Home
Using existing user
Filling in fake email and password
Answer: Login failed. Check the email address and password, and try again.
Buttons: <Back, Next> and Cancel

Clicking Next> gets me back to the login screen though. 
As does <Back. 

So this seems to be cosmetic, as both the back and next buttons bring you back to the login screen.

**Comment by AenBleidd** [comment]
@Ageless93 Please assign it to me, I'll fix this

**Comment by AenBleidd** [comment]
Fixed by #2196
