### ISSUE TITLE
After adding account manager, if user removes and readds account manager, projects become removable

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1052]
**Reported by JacobKlein on 12 Apr 41247733 10:40 UTC**
I added an account manager, BOINCstats BAM!, and it brought in my 15 projects that I have associated to the account manager.

The project properties, at this point, said "Added via account manager: yes", and none of the projects allowed the "Remove" button. So far, so good.

I then clicked "Stop using BOINCstats BAM!", and confirmed that I wanted to remove the account manager.

The project properties, at this point, said "Added via account manager: no", and all of the projects allowed the "Remove" button. So far, still so good, I guess.

I then re-added the account manager, BOINCstats BAM!.

The project properties, at this point, say "Added via account manager: no", and all of the projects allow the "Remove" button. This is not good.

Essentially, when an account manager is added or re-added, I believe it needs to better manage that "Remove" button.

I'm not sure if it's completely tied to the "Added via account manager" flag, but...[[BR]]If the sole purpose of the existing flag is to control the Remove button, then I recommend renaming the flag to "Managed by account manager", and then be sure to set it to "yes" anytime an account manager is added/!readded, even if the project was already in the BOINC projects list, thus making sure "Remove" is disallowed.

Hope this makes sense!

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1076

**Comment by ChristianBeer** [comment]
This is expected behavior as the Manager doesn't know if the account used for the existing project is the same as the AM wants to add. If this should be changed please open a new issue.
