### ISSUE TITLE
When adding an account manager, using a project URL does not halt gracefully.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1053]
**Reported by JacobKlein on 16 May 41247778 08:26 UTC**
Tools -> Add project or account manager... -> Use account manager -> Paste a project URL like http://isaac.ssl.berkeley.edu/alpha/ -> Next -> Agree to terms if applicable -> Identify account for the project -> Receive the following error:

Failed to add project[error has occured;[[BR]([BR]]An)]check the Event Log for details.[Finish to close.

Event log says:[[BR]([BR]]Click)]3/31/2011 !12:13:48 PM | | Fetching configuration file from !http://isaac.ssl.berkeley.edu/alpha/get_project_config.php [!12:13:56 PM | | Contacting account manager at !http://isaac.ssl.berkeley.edu/alpha/ [[BR]([BR]]3/31/2011)]3/31/2011 !12:13:57 PM | | error: file not found

Notices (on 6.12.19) also throws the error as a notice:[from BOINC[[BR]([BR]]Notice)]error: file not found

I propose this:

When the user is in "add account manager" mode, and first contact with the URL indicates that it is not capable of serving as an "account manager", the wizard should stop. It should not try to add it as a project. I should not have even gotten to terms of use page, or the Email address and password prompts.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1077

**Comment by romw** [comment]
**Commented by JacobKlein on 19 Feb 41247795 00:53 UTC**
Small correction: The error dialog actually says[[BR]]Failed to add account manager

Still, it should have halted earlier, and gracefully.

**Comment by Ageless93** [comment]
Just tested this with BOINC 7.8.1
In the communications window it shows that there was an error trying to add this account manager.
In the event log it shows:
17/08/2017 18:38:15 |  | Fetching configuration file from https://isaac.ssl.berkeley.edu/alpha/get_project_config.php
17/08/2017 18:38:17 |  | Project communication failed: attempting access to reference site
17/08/2017 18:38:20 |  | Internet access OK - project servers may be temporarily down.
