### ISSUE TITLE
BOINC Screen Saver does not respond properly when a GPUGrid.net task with Swan_Sync set to 0 saturates and starves either the primary GPU device or the CPU

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1057]
**Reported by JacobKlein on 20 Jan 41249078 10:13 UTC**
Rom and I have been doing some screensaver testing in Alpha testing, and  I believe I have come up with some reproducible bugs that should be  reported as tickets. As far as I know, these bugs exist on 6.10.58 and  the latest alphas.

This ticket is regarding the case where the Screen Saver is running, and the primary GPU device is running a GPU task. Essentially, the Screen Saver becomes delayed, starved for GPU cycles, and bad things can happen.

Among those bad things are:[Moving mouse/keyboard does not release the screensaver, and the user has to hit Ctrl+Alt+Del (in one case, even that did not respond, and I had to hard-boot ... but for the most part, if you just wait patiently, it will eventually respond)[[BR]([BR]]-)]- The Screen Saver sometimes makes the screen completely white for a few seconds, and may flicker between full-black and full-white.[Windows Event Viewer can sometimes show an "Application Hang" event (Interestingly enough, in addition to seeing hangs for the BOINC screen saver files boinc.scr, boincscr.exe, I've even seen an "Application Hang" event for the Windows 7 "Blank" screen saver, scrnsave.scr)[[BR]([BR]]-)]- While the screen saver is running, if you are able to see graphics, they may appear choppy or not moving or frozen.

I'm not sure how to fix this, but I am pretty sure the problem is a result of GPU tasks running.  For me, I only notice it when GPUGrid.net is running GPU tasks.  If I'm able to do more testing, I'll report back here.

One possible fix (that ROM thought up) might be to disable GPU processing on the primary display, whenever that primary display is in screen-saver mode (or maybe whenever any screen saver is running, since the Windows 7 "Blank" screen saver hung on me earlier).

For reference, my system is a Windows 7 x64 PC, Intel i7 965 eXtreme edition, quad-core with hyperthreading, so Windows sees 8 processors, BOINC sees 8 processors, I have 3 GPUs (1 Geforce GTX460 and 2 Geforce 9800 GTs), and I regularly run GPUGrid.net with the Swan_Sync system variable set to 0, which creates CPU processes to run alongside the GPU processing, and I have BOINC set up to use 63% (5 of 8) of my processors... so... BOINC is crunching 5 "cpu-only" tasks, and also 3 "gpu+cpu" tasks, which ends up fully saturating the entire PC. A mouthful.

Below is an exchange of emails regarding the issue.
# 

From: jacob_w_klein@msn.com[romw@romwnet.org; boinc_alpha@ssl.berkeley.edu[[BR]([BR]]To:)]Date: Thu, 31 Mar 2011 !17:30:56 -0500[Re: [boinc_alpha]([BR]]Subject:) 6.12.19 - Strange screensaver results

I just had another breakthrough, regarding the white-screen issue!  (Which may be entirely separate from Ctrl+Alt+Del issue.)[[[BR]([BR]])]On a test just now, when the screensaver was supposed to start, all I saw was a white screen and a busy cursor, for several seconds.[it may have flickered black, but then went back to white.[[BR]([BR]]Then,)] [and Keyboard were not responding, and so I hit Ctrl+Alt+Del, and that took several seconds (20-25?) to finally return me to the login.[[BR]([BR]]Mouse)] [best part of all this... is that it got logged (attached)! [[BR]([BR]]The)] [the juicy parts! [[BR]([BR]]Here's)]![17:14:55](03/31/11) Screen saver is executed[17:15:43]([BR]]![03/31/11) Threads and project selection happens (a whole 48 seconds late, and I'm betting I saw all white during the time!)[17:15:44]([BR]]![03/31/11) Docking project chosen.[17:15:55]([BR]]![03/31/11) Activity detected (me pressing keyboard? Looks like 11 seconds into the project's time slice)[17:15:55]([BR]]![03/31/11) - ![17:16:00](03/31/11) Tons of shutdown calls (shouldn't there only be one?)[and to top it off, the log didn't get flushed properly.[[BR]([BR]]...)] [see chaos. Let the fixing begin?[[BR]([BR]]I)] [smiling,[[BR]([BR]]Still)]Jacob
# 

From: jacob_w_klein@msn.com[romw@romwnet.org; boinc_alpha@ssl.berkeley.edu[[BR]([BR]]To:)]Subject: RE: [6.12.19 - Strange screensaver results[[BR](boinc_alpha])]Date: Thu, 31 Mar 2011 !17:56:03 -0500[The "white-out" apparently occurred while GPU tasks were running,  and while my CPU % settings was at 100, meaning: 8 cpu-only tasks,  alongside 3 cpu+gpu tasks[[BR]([BR]][[BR]]Note:)]... ie: overloaded even for my system.[thinking the "white-out" issue is a result of running GPU tasks alongside the screensaver.[[BR]([BR]][[BR]]I'm)][a thought regarding the shutdown:[[BR]([BR]]Here's)]Is it possible to boost the screensaver priority whenever things are being shutdown? (to ensure shutdown happens ASAP)[ at the time I hit Ctrl+Alt+Del, I'm sure I had 8 cpu processes at "Low"  priority, 3 cpu processes at "Below Normal" priority, and 3 GPUs that  were tied up.[[BR]([BR]]Because,)]I'm not sure what the screensaver priority was, but it should be at least "Normal" if not higher.[Jacob
# 

Date: Thu, 31 Mar 2011 !19:07:01 -0400[[BR]([BR]][[BR]]-)]From: romw@romwnet.org[jacob_w_klein@msn.com; boinc_alpha@ssl.berkeley.edu[[BR]([BR]]To:)]Subject: Re: [6.12.19 - Strange screensaver results[[BR](boinc_alpha])][priority is determined by Windows when the screensaver is[[BR]([BR]]Screensaver)]launched.[suspect the only way to "fix" this issue would be to shutdown the GPU[[BR]([BR]][[BR]]I)]app running on the primary display.  Then the screensaver and OpenGL[application from the project wouldn't be starved(waiting) for[[BR]([BR]]graphics)]GPU cycles.[[BR]][[BR]]----- Rom

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1081

**Comment by romw** [comment]
**Commented by JacobKlein on 9 Mar 41249092 11:06 UTC**
The Windows Event Viewer "Application Hang" events are Event ID 1002, Task Category (101), and I have events (hangs) listed for the following programs:[boinc.scr version 6.12.19.0[[BR]([BR]]-)]- boincscr.exe version 6.12.19.0[scrnsave.scr version 6.1.7600.16385[[BR]([BR]]-)]- minirosetta_graphics_1.92_windows_x86_64.exe version 0.0.0.0[[BR]]- charmm34_6.23_graphics_windows_x86_64 version 0.0.0.0

**Comment by romw** [comment]
**Commented by JacobKlein on 5 Sep 41253253 04:00 UTC**
Here are more testing results, reported on the Alpha email list:

> From: jacob_w_klein@msn.com[To: davea@ssl.berkeley.edu; boinc_alpha@ssl.berkeley.edu; romw@romwnet.org[[BR]([BR]]>)]> Date: Sat, 2 Apr 2011 !12:16:04 -0500[Subject: Re: [boinc_alpha]([BR]]>) 6.12.19 - Strange screensaver results[[[BR]([BR]]>)]> [Rom / David / List:[[BR]([BR]]>)]> [I've done some more testing regarding the screensaver slowness and hangs...[[BR]([BR]]>)]> and although I'm unable to conclude whether it is either GPU starvation or CPU starvation,[I do believe it has something to do with how GPUGrid.net uses the system variable "Swan_Sync" when set to "0".[[BR]([BR]]>)]> [Here are some tests I've done on my quad-core hyperthreaded (BOINC sees 8 CPUs) machine, with 3 GPUs:[[BR]([BR]]>)]> [When "Swan_Sync" is not set, and I have BOINC setup to use 100% of my processors:[[BR]([BR]]>)]> - BOINC uses 8 CPUs as Low priority processes[- GPUGrid.net uses all 3 GPUs[[BR]([BR]]>)]>  - GPUGrid.net also creates 3 "acemd..." Below Normal priority  processes, which consume very little CPU because "Swan_Sync" is not set.[- !ScreenSaver responsiveness seems very good.  Good when starting, good when executing, and good when releasing.[[BR]([BR]]>)]> [When "Swan_Sync" is set to "0", and I have BOINC setup to use 63% of my processors:[[BR]([BR]]>)]> [- BOINC uses 5 CPUs as Low priority processes[[BR]([BR]]>)]> - GPUGrid.net uses all 3 GPUs[- GPUGrid.net also creates 3 "acemd..." Below Normal priority [[BR]([BR]]>)]> processes, which consume as much CPU as they can because "Swan_Sync" is set to "0".[- !ScreenSaver responsiveness is poor.  Slow to start, choppy when executing, and slow to release, even sometimes hanging.[[BR]([BR]]>)]> [Do you think that maybe, when the screensaver runs[[BR]([BR]]>)]> ... having fully-active CPU processes at priority higher than "Low" can cause the screensaver to have problems?[ Again, I'm not sure if it's GPU starvation or CPU starvation, mainly  because I'm unsure of the effects of Swan_Sync on GPU utilization, but  either way it's not good.[[BR]([BR]]>)]> [Note:[[BR]([BR]]>)]> At GPUGrid.Net,  we are told to set "Swan_Sync" to "0" to make crunching faster for  modern GPUs, and to make tasks crash less for older GPUs.[I plan on keeping the setting set.[[BR]([BR]]>)]>  I am only playing with the setting, and running the BOINC Screensaver,  to help with testing - my normal setup is to run the "Blank"  screensaver.[[[BR]([BR]]>)]> Regards,[[BR]]> Jacob

**Comment by romw** [comment]
**Commented by JacobKlein on 1 Nov 41345674 10:13 UTC**
I have noticed that, when processing on the GPU with Swan_Sync set to 0, even the Windows Blank screensaver has trouble promptly responding, especially when Windows just entered screensaver mode. (ie: The screen goes blank, you wait 1-2 seconds, then move the mouse). I've seen 5-15 second delays in the response, and I've seen white-screens with the busy-cursor-animation.

So, I believe this issue does not only affect the Boinc Screensaver, it likely affects any screensaver.

**Comment by Ageless93** [comment]
Is this still an issue?

**Comment by AenBleidd** [comment]
Up

**Comment by ab1vl** [comment]
10-19-18 re: BOINC 7.14.2 

PC config:  Windows 10 Pro on a 12 physical core,/4 16GB logical core SuperMicro system with no GPU, 24 simultaneous tasks of various projects (other than GPU Grid) I occasionally see "waiting for memory" for a task status, but have not observed system hangs.   On lower performance systems (4 core AMD with 1 GPU as console port, 5 WUs total)  console response is normal  compared to 4 non GPU WUs running with no GPU WU.s  

 On 25 Nov 2016 ageless posted on SETI forum:  "No, there's no way to limit only GPU use. GPUs run 100% or 0%."  From that I deduce that while running at 100% CPU utilization while trying to manage multiple GPUs, with one or more GPUs set as monitor port(s), some response delay  is likely when viewing the console(s).  The narrative above seems to be based on a work load that equals or exceeds what the hardware can support.   In fact, the last comment by a submitter states:

"So, I believe this issue does not only affect the Boinc Screensaver, it likely affects any screensaver."

This seems an admission that BOINC software is not to blame for processing issues.  So I think we can close this one out but do suggest that we update the BOINC Docs/FAQ with some narrative about the role and best practice use of GPUs. I will take that action if someone familiar with that code can update me on its workings.

**Comment by JacobWKlein** [comment]
I'm okay with this being closed out. Though I must admit I haven't tested it since first reporting it, and I won't be able to immediately test it either.
