### ISSUE TITLE
Certain Windows 7 dialogs are significantly slower when BOINC is running

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1061]
**Reported by JacobKlein on 28 Jun 41259979 02:13 UTC**
I have noticed that certain Windows 7 dialogs are significantly slower when BOINC is running, versus when BOINC is not running, on my Windows 7 x64 machine.

1) Previous Versions dialog in Windows Explorer. Specifically, if you have several Restore Points and Shadow Copies of a file, in Windows Explorer, if you right click the file and select the Previous Versions tab, it can take 1.5 to 4 times as long to populate the list of Previous Versions, when BOINC is running. For my example, with BOINC suspended, the tab would take 4-6 seconds to load information, but with BOINC running, it would take 8-12 seconds if CPU-only tasks were running.

2) Opening the Action Center. When BOINC is running, it sometimes takes several seconds to open the Action Center or paint the screen after opening. If BOINC is suspended, it opens and paints immediately.

I suspect both of these issues are caused by Windows somehow running certain threads at a lower-than-normal priority, and then there are problems competing for CPU cycles when BOINC is running.

Other tasks/dialogs seem pretty snappy across the Operating System. These 2 just really stand out as BOINC performance hits, and I believe they should be looked into.

Feel free to contact me for any more information.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1085

**Comment by romw** [comment]
**Commented by Ageless on 13 Sep 41266576 10:13 UTC**
I've noticed a third as well, that being when you install any program, including an upgrade of BOINC, that the installer takes very long to break in on calculations. Snooze BOINC and the installer will immediately pop up and start work, but leave BOINC running and it'll be slow going. More than 30 seconds on average. Windows 7 - 64bit.

**Comment by romw** [comment]
**Commented by JacobKlein on 27 Feb 41324102 04:00 UTC**
I have confirmed that this issue not a result of anything GPU-processing-related. It's a problem that happens when the CPU is fully loaded.

**Comment by romw** [comment]
**Commented by JacobKlein on 16 Feb 41330650 09:20 UTC**
I have found another Windows 7 dialog that is slower.

When BOINC is running with the CPU fully loaded, the Windows 7 Power Options dialog takes longer-than-expected to open.

I hope something can be done (possibly in terms of processing priority?), so that these dialogs can feel snappy again.

**Comment by ChristianBeer** [comment]
BOINC already uses the lowest priority. The lack is probably from the OS scheduler struggling with a lot of processes at the same time.
