### ISSUE TITLE
Some BOINC Manager Computing Preferences need better sanitization

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1062]
**Reported by JacobKlein on 17 Nov 41267058 12:53 UTC**
Some BOINC Manager Computing Preferences need better sanitization
- "Idle minutes" preference input should not allow negative numbers
- "Hours" inputs should not allows entries like 13:239
- "% of the processors" should not allow negative numbers or numbers >100
- "% CPU Time" should not allow negative numbers or numbers >100
- "While processor usage is less than" should not allow negative numbers or numbers >100
- "Maximum download rate" should not allow negative numbers
- "Maximum upload rate" should not allow negative numbers

I don't like the idea of the program "assuming" it knows what I meant, so... if I type a negative number, it should not automatically treat it as positive. It should prevent me from saving the bad input.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1086

**Comment by ChristianBeer** [comment]
Some might be fixed already some might not. Needs to be checked.

**Comment by Ageless93** [comment]
With BOINC 7.8.1:
- Idle numbers cannot be negative numbers. Gives "Invalid input" and a red background in the input box. (FIXED)
- Hours input of 13:239 on daily schedule sets time to 16:59 and allows computation to start immediately. (FAIL)
- % of processors with -25% and 125% gives error window showing "Number must be between 0 and 100". (FIXED)
- % of CPU Time with -100 and 125% gives error window showing "Number must be between 0 and 100". (FIXED)
- non-BOINC CPU usage with -100 and 125% gives gives error window showing "Number must be between 1 and 100". (FIXED)
- Maximum download and upload rates with values of -100 gives error window with "Invalid number". (FIXED)

Which leaves the hours input, but I'll open a new issue for that one.
