### ISSUE TITLE
Download status is not correct when network suspended via activity and time of day

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1064]
**Reported by JacobKlein on 1 Jun 41267077 08:53 UTC**
If Network is suspended because of "Suspend Network" activity, it should say "Download suspended - user request", even if a time-of-day preference is set. 

Currently it says "Download suspended - time of day", which is inconsistent, because if you do the same tests with tasks and computing preferences, a task will correctly say "Suspended - user request".

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1088

**Comment by Ageless93** [comment]
BOINC 7.8.1
I've set a daily schedule for network, so it's suspended at the time of testing.
Checking the BOINC icon in the system tray it states: "Network is suspended - time of day"

I then went Activity->set Suspend Network Activity
Checking the BOINC icon in the system tray it now states "Network is suspended - user request"
