### ISSUE TITLE
Preferences - "On multiprocessors, use at most x processors" is not working as expected with "On multiprocessors, use at most x[pct] of the processors"

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1065]
**Reported by JacobKlein on 9 Dec 41267525 19:33 UTC**
I have tried to get the setting "On multiprocessors, use at most x processors" to actually do something, but I can't figure it out.

I'm thinking that the new setting "On multiprocessors, use at most x% of the processors" is being used by BOINC.

If that is true, then the first setting should be entirely removed from the Web Computing Preferences, to prevent further confusion.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1089

**Comment by romw** [comment]
**Commented by davea on 21 Sep 41267733 00:26 UTC**
I fixed "use at most X processors"; this was a bug in the client.  Will appear in 6.14, and possibly in the next 6.12.

**Comment by romw** [comment]
**Commented by Ageless on 16 Dec 41268120 04:53 UTC**
Replying to [JacobKlein](ticket:1089):
> I have tried to get the setting "On multiprocessors, use at most x processors" to actually do something, but I can't figure it out.

On web-preferences this is the old option for Pre-BOINC 6 clients, which are still used by various people on hardware and OSes that cannot use BOINC 6 at this time (think e.g. Domain Controllers). 

Perhaps that "On multiprocessors, use at most X processors." needs the addition "Used by BOINC 4 and 5 only." as it seems it's still a difficult preference ([referencing an Einstein thread showing this difficulty](http://einstein.phys.uwm.edu/forum_thread.php?id=8842)). 

Or just about everybody misses the "Enforced by version 6.1+" on the next preference.

**Comment by romw** [comment]
**Commented by JacobKlein on 13 Jul 41268234 16:26 UTC**
I'm confused. Is "use at most X processors" still a supported preference in current versions?

If it is supported in current versions, does it just work in tandem with "use a most X% processors" to find the maximum # of processors that satisfies both preferences?

If it is not supported in current versions, could the preferences page have that note, to say "Used by BOINC versions x only"?

**Comment by romw** [comment]
**Commented by davea on 15 Apr 41268404 00:00 UTC**
"Use at most X procs" is still supported.
A bug in the client kept it from working.

**Comment by romw** [comment]
**Commented by JacobKlein on 20 Apr 41325814 09:20 UTC**
This still is not working the way I expected, using 6.12.26.

The way I would expect it to work would be to use the maximum number of processors that still meets both of the 2 limiting preferences. Currently, the 2 preferences are still not working together to limit together, as can be seen in the 4th scenario below.

Also, currently, the Web can say "100%" when it really should say "---%", and the Manager can say "0%" when it really should say "100%".

Here are some useful scenarios (on a Win7 x64 6.12.26 machine that sees 8 processors), with expected outcomes, and Results:

Web Input: Use 0 processors, Use 0% processors[Web should say "--- processors" and "---% processors", Manager should say "100% processors", and client should use all processors[[BR]([BR]]Expected:)]Results: Web looks good, Manager says 0% but should say 100%, client used correct # processors

Web Input: Use 3 processors, Use 100% processors[Web should say "3 processors" and "---% processors", Manager should say "100% processors", and client should use 3 processors[[BR]([BR]]Expected:)]Results: Web says 100% but should say ---%, Manager says 0% but should say 100%, client used correct # processors

Web Input: Use 0 processors, Use 50% processors[Web should say "--- processors" and "50% processors", Manager should say "50% processors", and client should use 4 processors[[BR]([BR]]Expected:)]Results: Web looks good, Manager looks good, client used correct # processors

Web Input: Use 3 processors, Use 50% processors[Web should say "3 processors" and "50% processors", Manager should say "50% processors", and client should use 3 processors[[BR]([BR]]Expected:)]Results: Web looks good, Manager looks good, but client used 4 processors instead of 3.

Finally, why doesn't the Manager have UI to indicate the maximum # of processors? It seems like, if this is a supported setting, the Advanced Preferences should at least show the setting, right? Showing the preference may spin off into a new ticket. This current ticket is for getting the functionality correct.

**Comment by ChristianBeer** [comment]
The old setting was removed from Web and Manager and is ignored by current Clients.
