### ISSUE TITLE
In Simple View, after adding an Account Manager, the "Add Project" button should change to "Synchronize", as it would be if entering Simple View with an Account Manager already added

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1067]
**Reported by JacobKlein on 1 Jan 41286375 23:33 UTC**
In Simple View, after adding an Account Manager, the "Add Project" button should change to "Synchronize", as it would be if entering Simple View with an Account Manager already added

Another alternative might be to separate the "Synchronize" functionality into its own button in the Simple View.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1091

**Comment by Ageless93** [comment]
Simple view in BOINC 7.8 doesn't have the option to add the account manager anymore. That's solely available in Advanced view.
