### ISSUE TITLE
In Simple View, the Pause button should be called "Snooze" (for consistency, and because it does not stop network activity), and the tooltip should say "Temporarily stop work".

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1068]
**Reported by JacobKlein on 22 Oct 41286385 17:46 UTC**
It looks like the actual effect of using the "Pause" button on the simple UI, might be equivalent to using the "Snooze" option in the Tray.

If they are the same, the button should be re-labeled for consistency sake, and the tooltip should be adjusted. "Stops all activity" is not what Snooze does. "Temporarily stop work" sounds better to me.

Note: Don't forget to update translations.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1092

**Comment by Ageless93** [comment]
Is this still an issue? I cannot find a Pause button in Simple View, all options to pause are called Suspend.

**Comment by Ageless93** [comment]
No answer, so assuming this is fixed.
