### ISSUE TITLE
BOINC does not always launch a second graphics window when "Show graphics" is clicked on a project's second task (RNA World)

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1070]
**Reported by JacobKlein on 21 Oct 41291506 20:00 UTC**
I found this while testing graphics.

Scenario that works:[Have 2 or more RNA World tasks running[[BR]([BR]]-)]- Select them[Click "Show graphics"[[BR]([BR]]-)]- See the multiple Adobe Flash 9 windows properly open

Scenario that is broken:[Have 2 or more RNA World tasks running[[BR]([BR]]-)]- Select only one of them[Click "Show graphics"[[BR]([BR]]-)]- While those graphics are shown, select a different RNA World task[Click "Show graphics" for the different task[[BR]([BR]]-)]- The second graphics window does not appear, even though it should.

I know there are many problems with the way BOINC handles graphics and screensavers for RNA World, and it's possible that they're all related... but I figured I should report this as its minor bug.

Feel free to email me with any questions.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1094

**Comment by romw** [comment]
**Commented by JacobKlein on 19 Jul 41291508 09:46 UTC**
Just to be clear, I think the expected operation for the broken scenario is to see 2 separate "Adobe Flash Player 9" windows.

**Comment by romw** [comment]
**Commented by JacobKlein on 15 Mar 41328362 05:46 UTC**
Tickets #1080 and #1094 are probably related.

**Comment by ChristianBeer** [comment]
I would say this only happens with RNA World and is a problem of the Flash screensaver there. Would be interesting to know if someone could test this with YAFU@home and the HTML screensaver.

**Comment by AenBleidd** [comment]
Looks this is Project specific issue and it was never reported that any other Projects have the same issue.
Closing this as 'wontfix'
