### ISSUE TITLE
Notice tab not correctly displayed on dark theme

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1072]
**Reported by sandro tosi on 3 May 41315188 03:33 UTC**
Hi,
after checking http://boinc.berkeley.edu/trac/ticket/1003 resolution (and it's working great, at least for the main functionalities), I noticed that "Notices" is not correctly displayed on a dark theme, while it works fine in a light one.

Attaching 2 screenshots to show that.

Thanks,
Sandro

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1096

**Comment by ChristianBeer** [comment]
Adding original screenshots. The issue seems to be that the text color of the notice should be made aware of the selected Desktop theme.

![boinc-manager_6 12 22_dark](https://cloud.githubusercontent.com/assets/997210/24805507/543f2f0e-1bb2-11e7-94a1-2ced852958c9.png)

![boinc-manager_6 12 22_light](https://cloud.githubusercontent.com/assets/997210/24805506/543ec262-1bb2-11e7-9f0c-d26654f34c6d.png)

**Comment by ChristianBeer** [comment]
Another screenshot from a different ticket with actual notices:
![boinc-manager_6 13 10_dark](https://cloud.githubusercontent.com/assets/997210/24808210/31ee2df2-1bbb-11e7-9241-178d7c2c953a.png)

**Comment by CharlieFenton** [comment]
Since the Notices are displayed from HTML using wxWebView, I don't know if this is possible. And I believe the concept of themes exists only in MS Windows, not Mac (I don't know about Linux or other operating systems.)

**Comment by Ferroin** [comment]
Theming does exist on Linux and other UNIX derivatives (although it's a property of the graphics toolkit, not the desktop or the OS), it's just not as braindead as UWP theming (which is what WxWidgets appears to be keying off of here.  This looks pretty solidly to me like a bug in WxWidgets, not BOINC.

**Comment by ChristianBeer** [comment]
The Notices tab is essentially a HTML page that the Manager creates so we can add some CSS to that and convey the theme settings for background color and text color.

**Comment by davidpanderson** [comment]
On Win7, I switched to a white-on-black theme and the notices tab displayed correctly, white on black.  I tried to reverse this with CSS and it had no effect.

**Comment by ChristianBeer** [comment]
I selected "Breeze Dark" which is a white-on-black theme in KDE and the Manager was still black-on-white ignoring the change. Only the titlebar and border of the window was changed. Perhaps wxWidgets can't interact with some DM's on Linux or it needs some extra settings.

**Comment by Ferroin** [comment]
What Wx backend are you using on Linux?  I know for a fact that the WxGTK backend has issues like that when there isn't a GTK them set properly, and KDE may not be setting that right.

**Comment by ChristianBeer** [comment]
Yes, BOINC uses the GTK backend for wxWidgets.

**Comment by AenBleidd** [comment]
Closed in favor of #3115
