### ISSUE TITLE
systray - please make one click to close Manager into systray and another to reopen it

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1073]
**Reported by sandro tosi on 26 Mar 41315253 20:26 UTC**
Hi,
I noticed that when manager is minimized to the systray, a click on the tray icon re-opens it again.

It would be nice if a click on systray icon when manager is opened, would minimize it to systray.

Thanks,
Sandro

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1097

**Comment by romw** [comment]
**Commented by sandro.tosi on 26 Mar 41315289 00:00 UTC**
Ok, I overlooked the situation. My request change in: since now we have a working systray, it would be nice if we can minimize Manager to systray (instead of having it on the task bar) by clicking the systray icon. Another click on the icon when Manager is miminized, should make it reopen it.

**Comment by Ageless93** [comment]
Is this still an issue? I cannot reproduce it with 7.8.1 and Windows 7

**Comment by AenBleidd** [comment]
@Ageless93 This is reproducible.
Single click on systray icon does nothing.
Behavior proposed here is:
1 - When Manager is minimized, click on systray icon should open it.
2 - What Manager is open, click on systray icon should minimize it.
There are some applications with such behavior (e.g. TeamVIewer).

**Comment by CharlieFenton** [comment]
A;though a click on systray icon does not minimize the Manager if it is open, a single click on the Manager's main window does minimize it to the systray, so I feel this change us unnecessary. And wold it interfere with the ability to use the systray icon's menu?

Although I work primarily with macintosh and so am not as familiar with Windows applications as other people, the requested change seems to me to be hidden functionality, which is generally discouraged.

**Comment by CharlieFenton** [comment]
Correction: I meant to write:
... a single click on the close box of the Manager's main window does minimize it to the systray ...

**Comment by CharlieFenton** [comment]
Although a single click on the icon does nothing, a double click does open the Manager. The extra effort required to double click is negligible, so I feel that this, coupled with the ability to minimize the Manager with a single click on the close box, make the requested changes unnecessary. We have plenty of more pressing issues to spend our time on.

**Comment by Ageless93** [comment]
I also wonder if this isn't a function of Windows, as none of the icons in the system tray react to a single click. If I want to reopen my anti-virus, my Radeon settings, Speedfan, I need to all double click on the icons.

**Comment by AenBleidd** [comment]
Hello Jord,

No, this is not a function of Windows. You can implement any behavior on
any action with systray icon.
Also not so many applications have this function: in common case
application can be opened on doubleclick on systray icon. Other behaviors
are more rare.

Thanks

Best regards,
Vitalii Koshura

2017-08-18 13:44 GMT+03:00 Jord <notifications@github.com>:

**Comment by AenBleidd** [comment]
I don't see any real value in this functionality. Having BOINC Manager open, it's easier to click on 'Close' button to minimize the Manager to the systray, rather than going to the systray to do the same.
I have to admit that some of the applications really have this behavior, but it's not very common.
