### ISSUE TITLE
RPMLINT: binary-or-shlib-calls-gethostbyname

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1075]
**Reported by saigkill on 5 Jul 41325910 06:40 UTC**
libboinc6.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/libboinc.so.6.10.58[boinc-client.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/boinc-client[[BR]([BR]])] The binary calls gethostbyname(). Please port the code to use getaddrinfo().[[BR]]

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1099

**Comment by romw** [comment]
**Commented by Anton Torvalds on 1 Oct 41823142 12:00 UTC**
[http://www.synet.net/]

**Comment by ChristianBeer** [comment]
fixed in 0f4735352add8d8224cc4ccef195ec854a02eea3
