### ISSUE TITLE
Web Preferences - Clarify requirements and ranges

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1077]
**Reported by JacobKlein on 18 Aug 41326061 00:53 UTC**
Web Preference changes needed:[Some preferences should not be required[[BR]([BR]][[BR]]-)] -> "Switch between tasks every x minutes" (0 or blank could reset to 60)[-> "Disk: leave free at least x GB"[[BR]([BR]])][Required fields should indicate that they are required:[[BR]([BR]]-)] -> "'In use' means mouse/keyboard activity in last x minutes"[Fields with ranges should indicate the valid ranges (Percentages do not need to):[[BR]([BR]][[BR]]-)] -> "'In use' means mouse/keyboard activity in last x minutes"[-> "Suspend work if no mouse/keyboard activity in last x minutes"[[BR]([BR]])] -> "Switch between tasks every x minutes"[-> "On multiprocessors, use at most x processors"[[BR]([BR]])] -> "Disk: use at most x GB"[-> "Disk: leave free at least x GB"[[BR]([BR]])] -> "Tasks checkpoint to disk at most every x seconds"[-> "Computer is connected to the Internet about every x days"[[BR]([BR]])] -> "Maintain enough work for an additional x days"[-> "Maximum download rate: x Kbytes/sec"[[BR]([BR]])] -> "Maximum upload rate: x Kbytes/sec"[-> "Transfer at most x Mbytes every y days"[[BR]([BR]])][Some preferences need moved around[[BR]([BR]]-)] -> "Leave tasks in memory while suspended?" should be in the "Disk and memory usage" section

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1101

**Comment by ChristianBeer** [comment]
Most of this was taken care of in the big preference rearrangement by Jacob.
