### ISSUE TITLE
Preferences - Some supported Manager preferences are missing UI

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1078]
**Reported by JacobKlein on 5 Feb 41326154 04:26 UTC**
When testing Web Preferences, I noticed that there are 2 that are completely missing Manager UI.

The preferences are:["Suspend work if no mouse/keyboard activity in last x minutes"[[BR]([BR]]-)]- "On multiprocessors, use at most x processors"

I realize that the UI may have been intentionally removed, but if the  current versions of the Manager still "recognize" these Web Preferences and act on them, then there is an obligation to show them in the Manager Preferences dialog.

Please consider either adding UI elements, or removing support.  Currently, the Manager seems to have "hidden support" for them, and it's confusing for testers and users.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1102

**Comment by ChristianBeer** [comment]
This was fixed in the preferences overhaul.
