### ISSUE TITLE
Preferences - "Leave tasks in memory while suspended?", when unset, should remove previously-suspended tasks from memory

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1079]
**Reported by JacobKlein on 5 Jun 41326875 20:00 UTC**
I found this while testing a recent Alpha:

In my scenario, I had "Leave tasks in memory while suspended?" set to Yes for quite a while. Several hours later, after many scheduling periods, several tasks were suspended in memory, as expected.

However, when I changed the setting to No and suspended processing, only the tasks that had been processing during the change, were removed from memory. The previously-suspended tasks were still eating memory.

If possible, "Leave tasks in memory while suspended?", when unset, should remove previously-suspended tasks from memory.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1103

**Comment by Ageless93** [comment]
Is this still an issue?

**Comment by AenBleidd** [comment]
Up

**Comment by lfield** [comment]
I would say that as this is 7 years old it is not an issue.

**Comment by AenBleidd** [comment]
> I would say that as this is 7 years old it is not an issue.

I don't agree with this. It still an issue. When 'Leave non-GPU tasks in memory while suspended' is unchecked previously suspended tasks are left in memory. I think this is a useful feature but with low priority

**Comment by AenBleidd** [comment]
Sorry, my bad. Just verified this one more time. This is not an issue anymore
