### ISSUE TITLE
Memory Preference "Use at most x[pct]" should remove previously-suspended applications from memory if needed

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1080]
**Reported by JacobKlein on 17 May 41326966 10:13 UTC**
Found this on a machine with limited memory. It is a Windows 7 x86 laptop with 2GB.

My settings were: Use 50% memory when computer in use, Use 100% memory when computer is idle, Leave applications in memory

At one point, I got a task that took 1.5 GB of memory, and another that took 300 MB. So, if I wasn't using the laptop, BOINC was free to run them both, and it would pretty much take up all the memory.

However, when I started using the laptop, I noticed that memory was not being freed up for me. Both tasks stayed in memory, even though I had a preference that said Use 50% memory when computer is in use. This made the laptop very unusable.

Another thing I believe I noticed is that, if applications had been suspended to memory because they were cycled out by scheduling periods, BOINC would not remove them from memory to make room for running applications. This may be a feature to preserve work for tasks that didn't have a checkpoint recently, I'm not sure. It felt wrong though.

BOINC should count previously-suspended applications as part of the total memory %... and it should remove previously-suspended applications from memory if needed, to meet a % memory limitation.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1104

**Comment by romw** [comment]
**Commented by Pepo on 8 Sep 41327514 15:06 UTC**
Replying to [JacobKlein](ticket:1104):
> This may be a feature to preserve work for tasks that didn't have a checkpoint recently, I'm not sure. It felt wrong though.
You can make sure by comparing the task's CPU time with its "CPU time at last checkpoint". The threshold time is I believe 10 seconds.

**Comment by Ageless93** [comment]
Is this still an issue?

**Comment by AenBleidd** [comment]
Up

**Comment by lfield** [comment]
Testing with VB applications on LHC@home.  If I suspend (in memory) the task and reduce the available memory, the task will not start as it is waiting for memory. When exiting BOINC the tasks will suspend to disk. If the task is running and I reduce the the memory it aborts.  We could consider suspending to disk we are over the memory limit, similar to when BOINC exits. However, I consider the current situation preferable over aborting the tasks.

**Comment by davidpanderson** [comment]
If the available RAM is reduced, and a running job is using more than that amount,
it makes sense to abort it since it will never be able to run with that limit.

However, there are actually 2 RAM settings: one while in use, another while idle.
If the "while idle" setting accommodates the job, we shouldn't abort it even if
the "in use" setting doesn't accommodate it.
I'll look at this at some point.

**Comment by davidpanderson** [comment]
I looked at the code; it aborts the job only if its WSS is greater than both the in-use and idle memory limits.  So current behavior is probably OK.
