### ISSUE TITLE
Reorder and Chunk the Tools, Advanced, and Help menus

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1081]
**Reported by JacobKlein on 1 Jan 41331000 17:46 UTC**

This ticket is to enhance and improve the menus on the Advanced view. In some cases, if a separator or two was added, and things were slightly reordered, it would look a lot more organized. This would especially help the Advanced menu. Below is what I propose:

**Tools menu, when not using an Account Manager, should be:**
Add project or account manager...
(Separator)
Computing preferences
Display and network options...

**Tools menu, when using an Account Manager, should be:**
Synchronize with AM
Stop using AM
(Separator)
Add project...
(Separator)
Computing preferences
Display and network options...

**Advanced menu should be:**
Event Log...
(Separator)
Run CPU benchmarks
Do network communication
Read config file
Read local prefs file
(Separator)
Shut down connected client...
Select computer...
Launch another BOINC Manager

**Help menu should be:**
BOINC help
BOINC Manager help
BOINC website
(Separator)
About BOINC Manager...

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1105

**Comment by romw** [comment]
**Commented by drotos@a7169a2c-3604-0410-bc95-c702d8d87f7a on 27 Oct 43921901 20:20 UTC**
commit 31f0fee320678455d986ee5f1bf9a07f50c95208
Author: drotos <drotos@a7169a2c-3604-0410-bc95-c702d8d87f7a>
Date:   Thu Jan 4 09:53:15 2007 +0000

    fix #1105: change to running state immediatelly, don't wait for condor
    to start execution
    
    
    git-svn-id: svn+ssh://cvs.lpds.sztaki.hu/var/lib/svn/szdg/dcapi/trunk@994 a7169a2c-3604-0410-bc95-c702d8d87f7a

**Comment by romw** [comment]
**Commented by JacobKlein on 30 Dec 43922060 17:45 UTC**
I think that last comment may have been referring to some other ticket.

**Comment by Ageless93** [comment]
We have redone the whole of the Advanced view menu setup not too long ago (for BOINC 7.6 if I remember correctly). Jacob Klein helped out at that. So I'll close this issue.
