### ISSUE TITLE
job_log and computation errors

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1087]
**Reported by sunu on 17 Feb 41392551 16:53 UTC**
Currently jobs/tasks that end with computation errors aren't logged anywhere locally. job_log_<project>.txt file, logs only jobs that end successfully.

For monitoring purposes it would be nice to have a log of jobs/tasks with computation errors, either in a separate file or in the same job_log_<project>.txt file adding a new field with exit code.

This would also reduce web traffic and project database queries for those who troubleshoot or like to monitor their account very closely.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1111

**Comment by ChristianBeer** [comment]
The file format of job_log.txt should already support that.

**Comment by lfield** [comment]
I don't think that this is an issue.

**Comment by RichardHaselgrove** [comment]
I disagree. For those of us who like to report back to project administrators when problems occur with their tasks (a limited subset, admittedly), being able to locate errors by error number or exit code would be extremely useful. It would also help in educating users not to report errors such as 'output file absent' as if they were errors in themselves. Hide it behind a debug flag if you're afraid of frightening the punters.
