### ISSUE TITLE
Support the assistive technology service provider interface (AT-SPI).

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1088]
**Reported by krzyszp on 15 Sep 41403004 23:33 UTC**
Problem:

BOINC Manager doesn't cooperate with ORCA properly.Most of buttons and text fields are not work correct. I.e. in settings menu orca just read "text area, 50" without reading label field.

This problem is very difficult to omit for disabled people.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1112

**Comment by ChristianBeer** [comment]
This might be a wxWidgets issue but we should at least get this properly tested and see what we can do on our end.

**Comment by Ageless93** [comment]
The original issue was for BOINC 6.12.26. Aren't more up-to-date BOINC versions doing this differently?

**Comment by lfield** [comment]
I tried this on Ubuntu with 7.9.3 and the behavior was similar to Firefox.
