### ISSUE TITLE
EPERM upon slot creation not checked - Debian Bug #625280

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1090]
**Reported by steffen moeller on 19 Oct 41456307 05:20 UTC**
I'll ask for a confirmation with a later version.
You might anyway know where to look.
Thanks
Steffen

http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=625280

Package: boinc-client
Version: 6.10.58+dfsg-3
Severity: minor

Hi,

It appears that boinc doesn't correctly handle cases where EPERM is returned. 
At least when trying to create /var/lib/boinc-client/slots/$n if it gets an 
EPERM (and possibly other error codes) it keeps incrementing $n, trying to 
create a directory for every value of $n.

Not only this is useless, but it also leads to high CPU usage because of the, 
apparently endless, loop.
## Cheers,

Raphael Geissert - Debian Developer
www.debian.org - get.debian.net

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1114

**Comment by Ageless93** [comment]
Is this still an issue with BOINC 7 and Debian?

**Comment by AenBleidd** [comment]
Up

**Comment by davidpanderson** [comment]
It's not an infinite loop - only NCPUS*100

We could change boinc_mkdir() to distinguish specific/general errors,
but I'm not sure that's worth it.

**Comment by lfield** [comment]
I have just tested this by changing the ownership of the slot directory to root and got the message _exceeded limit of 200 slot directories_.

From the [code](https://github.com/BOINC/boinc/blob/master/client/app.cpp#L628)

>         // paranoia - don't allow unbounded slots

So the original issue (endless, loop/high CPU usage) has been addressed.
