### ISSUE TITLE
Create a mobile app for low-usage/multi-processor phones

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1096]
**Reported by say2joe on 6 Nov 41538839 04:26 UTC**
Perhaps it is time to consider utilizing mobile power (during lock screen) on under-utilized or high-performance devices. There are several phones / mobile devices being launched in 2011 (alone) which will be dual/multi-core. And, since mobile phones are always connected to data, the application could streamlined.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1121

**Comment by ChristianBeer** [comment]
We have an Android App now.
