### ISSUE TITLE
GPU tasks don't suspend on Mac OS X 10.6.8

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1099]
**Reported by Dagorath on 3 Sep 41585124 08:53 UTC**
BOINC 6.12.33 doesn't suspend GPU tasks on Mac OS X 10.6.8.  It does suspend CPU tasks properly so this doesn't appear to be a problem with keyboard/mouse usage detection.  It fails to suspend when the Suspend button is clicked and when user preferences specify no GPU usage when user is active.

Further details are in http://boinc.berkeley.edu/dev/forum_thread.php?id=6791

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1124

**Comment by ChristianBeer** [comment]
This is probably fixed in current 7.6.33 if not please open a new issue.
