### ISSUE TITLE
account_finish.php should help users to get help in forums

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1100]
**Reported by teleyinex on 1 Feb 41605958 01:20 UTC**
When a user creates an account in the project, the browser opens the following web page:

http://domain/project/account_finish.php

There are some users that do not find easily the Message Boards or Questions and Answers sections, so it would be nice to show a sentence with some information about it.

Adjoining is a patch with a sentence including links to the Message Boards and the Questions and Answers sections.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1125

**Comment by Ageless93** [comment]
With the newest BOINC forums, is it still possible to make an account via the website (other than on the BOINC Dev forums)? So is this still an issue?

**Comment by lfield** [comment]
After joining as a new user, my account page (home.php) is shown not account_finish.php.
