### ISSUE TITLE
PM: Error: Memory VFS already contains file *.xpm

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1101]
**Reported by toralf on 5 Mar 41606567 08:00 UTC**
Today I started the boincmgr 6.12.33 at my almost stable Gentoo and attached myself to the project orbit@home. I'm wondering whether these stdout/stderr are harmless or not:

tfoerste@n22 ~ $ boincmgr  08:02:04 PM: Error: Memory VFS already contains file 'webexternallink.xpm'! 08:02:04 PM: Error: Memory VFS already contains file 'nvidiaicon.xpm'! 08:02:04 PM: Error: Memory VFS already contains file 'atiicon.xpm'! 08:02:04 PM: Error: Memory VFS already contains file 'multicore.xpm'!

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1126

**Comment by romw** [comment]
**Commented by Yin Gang on 17 Nov 41783379 05:20 UTC**
The same issue also happened to me today when I'm adding OPTIMA@home to the client.

 * BOINC 6.12.34
 * Ubuntu 10.04 LTS x64
 * wxWidgets 2.8-0 (from synaptic)

**Comment by ChristianBeer** [comment]
Seems to be not an issue with current 7.6.33
