### ISSUE TITLE
[PATCH] Duplicate if in app_stats_mac.cpp

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1103]
**Reported by serval2412 on 11 Dec 41606843 07:06 UTC**
Hello,

I use cppcheck (last git version) to detect pbs.
cppcheck detected a duplicate if statement in the file app_stats_mac.

I tried to figure out what was done on this part and made corrections.
This patch should be reviewed to be sure.
Hope this helps.

Julien.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1128

**Comment by ChristianBeer** [comment]
Closing, as patch is most likely outdated.
