### ISSUE TITLE
boinc fix for building with libnotify >= 0.7

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1106]
**Reported by mjakubicek on 8 Apr 41635821 07:06 UTC**
There was an API change in libnotify 0.7 that prevents boinc building against that version, see here for details:

http://comments.gmane.org/gmane.linux.redhat.fedora.devel/141899

I'm attaching a very simple patch that works with libnotify >= 0.7, but you'll probably want a better solution that autodetects using AC_CHECK_FUNC (e.g. such as here: http://mail.gnome.org/archives/commits-list/2010-November/msg00182.html)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1131

**Comment by romw** [comment]
**Commented by mjakubicek on 27 Oct 41635831 11:06 UTC**
see also #1116, point 1, for a (maybe, I didn't test) better patch

**Comment by ChristianBeer** [comment]
Fixed in e17828b52ae9b2080529477476926145dc09a479
