### ISSUE TITLE
building and installing on linux leaves a wrong RPATH

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1116]
**Reported by viric on 22 Feb 41767983 13:20 UTC**
Looking at the RPATH with readelf, it shows the path of the building directory.

I'm building with "./configure --disable-server --prefix=somepath ; make install".

I've been looking for hours at what can that be, but I'm no libtool expert. I could not understand why that happened.

It looks to me like the libtool mode=install is not relinking with the proper prefix/lib.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1143

**Comment by romw** [comment]
**Commented by viric on 12 Jan 41767984 15:06 UTC**
Looking at the RPATH of any program installed into bin/, I meant.

**Comment by ChristianBeer** [comment]
probably fixed in #1798
