### ISSUE TITLE
Memory leaks in sample_bitwise_validator.cpp

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1119]
**Reported by tj2020 on 11 Feb 41803090 10:13 UTC**
In sched/sample_bitwise_validator.cpp we have;

```
intinit_result(RESULT&result,void*&data) {
```

```
...
```

```
FILE_CKSUM_LIST*fcl=newFILE_CKSUM_LIST;
```

```
....
```

```
retval=get_output_file_infos(result,files);
```

```
if(retval){
```

```
log_messages.printf(...);
```

```
returnretval;
```

```
}
```

```
...
```

```
data = (void*) fcl;
```

The function returns from the if (retval) block without freeing the allocated memory (or assigning fcl to the out parameter, data).

The same mistake is repeated inside the for loop few lines later.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1146

**Comment by ChristianBeer** [comment]
This is just an example file but nevertheless should not contain avoidable memory leaks.

**Comment by Ageless93** [comment]
Checking https://github.com/BOINC/boinc/blob/master/sched/sample_bitwise_validator.cpp I cannot find those issues anymore. So I'll be closing this one.
