### ISSUE TITLE
doesn't respect the "Additional work buffer" option

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1125]
**Reported by sandro tosi on 12 Dec 41863982 20:06 UTC**
Hello,
boinc-manager doesn't respect (since quite some time, sorry to report it only
now) anymore the "Additional work buffer" option. I've set it to '10' days, but
currently I only have the 3 WUs running right now, and nothing more. once one is
finished, then eventualyl others are downloaded, but just to fulfill the
immediate need of computation, no additional buffer is filled.

This is an important feature, in particular because several machines might not
have a constant connection, so being able to buffer some WUs is vital.

Cheers,
Sandro

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1152

**Comment by romw** [comment]
**Commented by Ageless on 16 Feb 41864332 11:45 UTC**
Run your client_state.xml file, global_prefs.xml file, global_prefs_override.xml file and cc_config.xml file through the [client simulator](http://boinc.berkeley.edu/dev/sim_web.php), try to reproduce your problem. 

Also, when reporting something, add information about:
- your computer.
- which projects you're attached to.
- which projects have work.

**Comment by ChristianBeer** [comment]
Should be fixed in current 7.6.33
