### ISSUE TITLE
More clever work fetch

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1127]
**Reported by saldsl on 31 Dec 41885479 04:33 UTC**
At the moment BOINC only takes account for % of time PC is on and % of BOINC is running to calculate how much work to fetch and when.
The process could be more clever, taking care of which days of week PC/BOINC is running and which not. For example, an office PC will stay on from Monday to Friday and off Saturday and Sunday, so BOINC should know that if today it's Friday for the next two days no work will be done.
Moreover, it can be implemented a sort of calendar where the user can insert, for example, holidays, to tell BOINC that for some day or some week the PC will remain off, so it should not download any more WUs. (currently the workaround I'm using it's suspend work fetch for projects with short deadlines)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1154

**Comment by ChristianBeer** [comment]
There is a paper that reports on research done if this is a good strategy. One might look this up and see if it can be implemented.

**Comment by lfield** [comment]
Most computers today at connected 24/7 so they can download new tasks when they need them. Having a buffer is useful in some circumstances but writing an adaptive algorithm to optimize the buffer size seems unnecessary.
