### ISSUE TITLE
Server build does not check for python

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1129]
**Reported by MattArsenault on 2 Oct 41913952 02:13 UTC**
Since python is required for the server tools, check that it is installed if building the server.
Additionally, while make_project is installed, it fails to run since boinc_path_config.py is not installed. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1156

**Comment by ChristianBeer** [comment]
python is a runtime dependency not a build time dependency. One could build server components on a system with no python. the actual project server needs python but since it is installed by default in all recent distributions there is no need for a check.
