### ISSUE TITLE
Server tools should be renamed

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1130]
**Reported by MattArsenault on 7 Mar 41914013 12:43 UTC**
The various server tools should be renamed, preferably to be prefixed with boinc_. Most importantly, start, status, stop and upgrade have extremely generic names.

This is most obviously problematic since /sbin/start exists in the new upstart init as used on Ubuntu, so once installed this conflicts with the real system start in the default PATH. This breaks lots of things.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1157

**Comment by romw** [comment]
**Commented by MattArsenault on 27 May 41914027 10:52 UTC**
These tools conflict with /sbin/status, /sbin/start, and /sbin/stop

**Comment by romw** [comment]
**Commented by Nicolas on 18 Jan 41914120 11:36 UTC**
Why is your $projectroot/bin in the $PATH anyway?

**Comment by romw** [comment]
**Commented by MattArsenault on 11 Apr 41914149 01:25 UTC**
Why would it not be? Having it installed in a separate world isn't really a reasonable requirement for any project.

**Comment by Ageless93** [comment]
Is this still an issue?

**Comment by lfield** [comment]
No. Currently everything is under the project directory.
