### ISSUE TITLE
Native systemd service file for boinc-client

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1138]
**Reported by johannbg on 31 Jul 41978688 21:20 UTC**
The attached file is a native systemd unit file for boinc-client and replaces the legacy sysv init script. 

It will work on any Linux platform that uses systemd as their init system.

To test this drop the attached file into /etc/systemd/system directory 

Run 

systemctl daemon-reload
systemctl start boinc-client.service
systemctl status boinc-client.service
systemctl stop boinc-client.service

To learn more about systemd see http://www.freedesktop.org/wiki/Software/systemd

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1165

**Comment by romw** [comment]
**Commented by johannbg on 29 Oct 42032578 11:54 UTC**
Is there any further information needed with regards to systemd and systemd units?

**Comment by ChristianBeer** [comment]
Debian ships a working systemd file.
