### ISSUE TITLE
7.0.11 unzip: tty operations not known to kfreebsd

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1145]
**Reported by smoe on 17 Feb 42092918 05:55 UTC**
7.0.11 does not build on Debian's BSD kernels, see
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=657750

Thanks

Steffen

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1172

**Comment by romw** [comment]
**Commented by steffen_moeller on 13 Jun 42097208 13:46 UTC**
In lack of a respective machine I contacted the kfreebsd mailing list. There, Robert Millan pointed out that the file zip/unzip/ttyio.c does not have _POSIX_VERSION defined, which keeps it from defining USE_POSIX_TERMIOS .  I am tempted to fix this with a mere "#include <unistd.h>" in ttyio.c, which would remove those problem. Though this should have been called through zip/unzip/unix/unxcfg.h.  The identification of the kFreeBSD system as a BSD system does not seem to work.

**Comment by ChristianBeer** [comment]
According to Debian bugtracker this was fixed on the Debian side.
