### ISSUE TITLE
Linux Debian nVidia GPU's aren't recognized in Boinc

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1148]
**Reported by fliteshare on 13 Apr 42111966 17:52 UTC**
Bug:  nVidia Tesla's don't show in Boinc but are known in Linux.

phenomenon: Boinc manager will display "NO GPU PRESENT" for GPU tasks.

cause: boinc-client comes online before the Tesla's are initialized. 
(my case Tesla's but might be other nVidia GPU's)

Solution: Patch /etc/init.d/boinc-client;
stop boinc-client
introduce a 30 second delay 
start boinc-client.
This gives Linux sufficient time to handshake the Tesla's.
(30 seconds is arbitrary but happened to work on my system)

Patched /etc/init.d/boinc-client script attached for your approval.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1175

**Comment by ChristianBeer** [comment]
Working in current 7.6.33.
