### ISSUE TITLE
Windows 7 Home Premium has no group management - no control by reg users

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1154]
**Reported by smoe on 22 Jul 42281657 04:04 UTC**
The typical presumed single user low budget (~ $700) machine over here comes with Windows 7 Home Premium ... which basically means ... Windows 7 minimal and with some likelihood represents the majority of Windows BOINC installations. That has no group management. Hence, there is no way for a regular user to control BOINC, which is configured to run for all users. Only the administrator can run it.

My suggestion is to have group management optional and just allow everyone to control BOINC who has the active Windows session ... on those machines that do not have group management. I do not recall that behaviour from BOINC 6.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1182

**Comment by romw** [comment]
**Commented by Ageless on 2 Apr 42282353 15:56 UTC**
Replying to [smoe](ticket:1182):
> I do not recall that behaviour from BOINC 6.

Which is weird, because in this sense nothing in the installer has changed between BOINC 6.10 and 7.0 (including 6.12). 

Although the Windows 7 Basic and Home versions may not have the group management policy editor, the administrator can still add users to the group, through the net localgroup command. See [this FAQ](http://boincfaq.mundayweb.com/index.php?language=1&view=492) on how to do that.

**Comment by romw** [comment]
**Commented by smoe on 12 Apr 42282389 01:36 UTC**
Replying to [Ageless](comment:1):
> Replying to [smoe](ticket:1182):
> > I do not recall that behaviour from BOINC 6.
> 
> Which is weird, because in this sense nothing in the installer has changed between BOINC 6.10 and 7.0 (including 6.12).
Strange. Fact is that when changing from Administrator (with full control) to the regular user the boinc client stops and the error message refering to the missing group entry pop up.

> Although the Windows 7 Basic and Home versions may not have the group management policy editor, the administrator can still add users to the group, through the net localgroup command. See [this FAQ](http://boincfaq.mundayweb.com/index.php?language=1&view=492) on how to do that. 

Wow, many thanks. This was helpful, indeed. Too bad the client did not point to that. While I was at it, my first attempts failed. I had to remove the quotes around the username. Then that went just fine. The remaining challenge now is to get the client started as a regular user. I'll send another comment if a reboot does not fix it.

**Comment by romw** [comment]
**Commented by smoe on 16 Mar 42282539 09:19 UTC**
Replying to [smoe](comment:2):
> Replying to [Ageless](comment:1):
> > Replying to [smoe](ticket:1182):
> > > I do not recall that behaviour from BOINC 6.
> > 
> > Which is weird, because in this sense nothing in the installer has changed between BOINC 6.10 and 7.0 (including 6.12).
> Strange. Fact is that when changing from Administrator (with full control) to the regular user the boinc client stops and the error message refering to the missing group entry pop up.
> 
> > Although the Windows 7 Basic and Home versions may not have the group management policy editor, the administrator can still add users to the group, through the net localgroup command. See [this FAQ](http://boincfaq.mundayweb.com/index.php?language=1&view=492) on how to do that. 
> 
> Wow, many thanks. This was helpful, indeed. Too bad the client did not point to that. While I was at it, my first attempts failed. I had to remove the quotes around the username. Then that went just fine. The remaining challenge now is to get the client started as a regular user. I'll send another comment if a reboot does not fix it.

Rebooted and logged in directly to the regular user. The reboot did not fix the issue with the error message, even though the user is still recognised to be assigend to boinc_users. The manager starts empty, invoking the connection to localhost says I'd not belong to boinc_users. And I already added to _admins and _projects, too. I am now helping myself by runing the BOINC manager as Administrator - did not come to me any earler. Had restarted BOINC manually in the meantime, no idea if this is any related to this "success" now. Starting with full provileges is not a good idea as many may agree.

Many thanks and regards,

Steffen

**Comment by romw** [comment]
**Commented by J Langley on 21 Jul 42288756 07:49 UTC**
I've experienced similar issues. [was running BOINC 6.12.34 as a service (with all users able to control BOINC), and upgraded to 7.0.25,  but no longer running as a service (though still with all users having the ability to control BOINC). When I logged in to my Administrator account, BOINC started and I could launch the GUI. But when I logged on to a standard user account BOINC did not appear to start properly (no tasks were started); when I launched the GUI and selected to attach to localhost I got the error message about not belonging to boinc_users.

I followed the suggestions above to manually add the standard user into the boinc_users group (surely the installer should have done this automatically for me?), but this did not resolve the problem.

I've uninstalled 7.0.25 and reinstalled 7.0.25 as a service again. Now everything is fine (all users can access the GUI and control BOINC), but sadly this prevents me from using my GPU or VirtualBox (for Test4Theory).

[[BR]([BR]]I)] This defect appears to be related to (or a duplicate of) ticket #1025.  [[BR]] Since ticket 1025 is flagged as a Blocker, I'm very surprised the 7.0 series has become the recommended client with this defect still in place.

I found this latest upgrade so frustrating that I registered for TRAC specifically to update this ticket.

**Comment by romw** [comment]
**Commented by smoe on 5 Jan 42343167 10:42 UTC**
It may sound a bit weird, but "start as Administrator" to me now means
 - log in as regular user
 - find the boinc-manager in the "Start" menu
 - right click on it and select "Run with Administrator privileges" or whatever the translation is

There is so much that I want the developers to work on that I would live with the current situtaion for now. My complaint is reduced to "Please do not start the boinc-manager at startup if the user then cannot open it and point your user to open it with full privileges as a workarond".

Cheers,

Steffen

**Comment by ChristianBeer** [comment]
Is this still an issue?

**Comment by Ageless93** [comment]
And asking again if this is still an issue? Can someone test this on Windows 10?

**Comment by Ageless93** [comment]
Closing due to no answer and no one testing.
