### ISSUE TITLE
cannot exit boincmgr by the tray icon

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1168]
**Reported by toralf on 24 Feb 42510299 19:56 UTC**
If I right-click under Gentoo Linux at the tray icon (KDE) and select "Exit" - then boincmgr doesn't really exits. The manager is still running.

It does only works, if I select the menu item of the manager widnow itself.
Here the program really finishes.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1196

**Comment by romw** [comment]
**Commented by Nicolas on 3 Dec 42804025 07:29 UTC**
I can reproduce this, running BOINC 7.0.27 on Debian Wheezy with KDE 4.8.4. It only happens when quitting the manager from the tray icon, ''not'' when using the File menu.

The window disappears. The tray icon ''seems'' to disappear, but in fact there's still an invisible (fully transparent) square taking up space in the tray, noticeable if I open another app with a tray icon. Opening the manager again shows a message box saying it's already running, and telling me to give a hostname and password to connect to a different client. This seems pretty confusing for end users.

The `boincmgr` process remains running, using no CPU. Attaching with `gdb` shows it's simply running the wxGTK event loop but not receiving any events (so the event-waiting function doesn't return).

**Comment by ChristianBeer** [comment]
I could reproduce this on Debian 9 (KDE). Closing via trayicon leaves several `boincmgr` processes running which prevents opening a new Manager instance.

**Comment by Ageless93** [comment]
Laurence, can you have your builders test for this bug?

**Comment by Germano0** [comment]
> I could reproduce this on Debian 9 (KDE). Closing via trayicon leaves several `boincmgr` processes running which prevents opening a new Manager instance.

That is what I experienced and documented in patch comment (point 1)
https://github.com/BOINC/boinc/issues/2604#issuecomment-445826926

**Comment by AenBleidd** [comment]
Fixed via #3052
