### ISSUE TITLE
Application crash boinc.exe 0xc0000374

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1180]
**Reported by schhcc tech on 2 Sep 42666945 05:06 UTC**
ZIP attachment contains windows seven: event-viewer(windows-logs(Application)) plus the ProgramData\boinc\std*.txt

I've uninstalled / installed; run chkdsk, run hardware diags

host pc is running Faronics Deep Freeze; the ProgramData files are not frozen. 

the boincmgr.exe is launched in the background using a separate account than the foreground logon account. this seup runs on 15 other units, none of witch exhibit the application crash event.   

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1208

**Comment by romw** [comment]
**Commented by Nicolas on 9 Oct 42667016 05:21 UTC**
Your attachment included your SETI@Home account key and other information that shouldn't be public. I have censored it out and re-uploaded the zip.

**Comment by romw** [comment]
**Commented by Nicolas on 29 Dec 42667037 23:41 UTC**
The .zip doesn't seem to have any useful information to track down the cause of the crash.

Rom: could you guide him to get a stack trace on Windows?

**Comment by ChristianBeer** [comment]
Most likely fixed as there were no more reports of the same issue.
