### ISSUE TITLE
cpu resources /scheduling

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1181]
**Reported by toralf on 12 Dec 42668769 05:00 UTC**
While playing with thinkfan (using CPU governor "ondemand") at my Gentoo Linux I'm wondering, whether an "interlaced" task scheduling would reduce the power consumption/fan noise at my ThinkPad without performance loss.
Meanin, what if for (as an example) a 4-core CPU system the following scheduling would be used for - say 60% CPU usage of 100% off all CPU's at a multi-core system - for 4 running tasks:
(1-4 means that the task is running at that time, . means pausing)
111111....111111....111111....111111....
.222222....222222....222222....222222...
..333333....333333....333333....333333..
...444444....444444....444444....444444.

?

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1209

**Comment by romw** [comment]
**Commented by davea on 26 Oct 42668856 22:06 UTC**
This effect could be achieved, I think, by limiting the # of processors used to 3 or less.  I should also point out that BOINC doesn't assign jobs to particular processors; it leaves that up to the operating system.

**Comment by romw** [comment]
**Commented by toralf on 1 Dec 42670524 19:46 UTC**
> This effect could be achieved, I think, by limiting the # of processors used to 3 or less
yep, but not so fine grained I think.

> it leaves that up to the operating system. 
good point, there are different strategies in the wild

At least here with current kernel 3.5.3 and a 4-core processor system it seems, that each core gets one task.

**Comment by ChristianBeer** [comment]
Needs #830

**Comment by lfield** [comment]
A Rom pointed out, this would be the same as switching one core off. As far as I understand energy consumption is not linear with CPU load. Reducing each core by 10% might be a better option but I don't think that this is currently possible. In any case the original suggestion of interlaced task scheduling will not be implemented.
