### ISSUE TITLE
Cppcheck full report

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1183]
**Reported by serval2412 on 21 Feb 42735874 06:05 UTC**
Hello,

I runned cppcheck (git updated version 2 days ago) on svn Boinc sources 2 days ago.
I attached the complete report.

There may be some false positives but I think it should help.

Julien 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1211

**Comment by ChristianBeer** [comment]
No need to comb through an old report.
