### ISSUE TITLE
no new task loaded if config values are set to 0

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1186]
**Reported by toralf on 18 Oct 42785466 14:21 UTC**
I set at version 7.0.35 both "minimum workload buffer" and "additional workload buffer" to zero at my 4-core CPU.
When a BOINC task finished (WCG with a computation error) - no new task were loaded - BOINC just continued with the remaining 3 tasks.

I set both values now to 0.01 - and a new task from WCG were loaded immediately.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1214

**Comment by ChristianBeer** [comment]
This might already be fixed, needs to be tested.

**Comment by Ageless93** [comment]
I've run BOINC 7.6 with zero and zero cache for a long time and always had around 4 tasks in cache. Running tasks solely on my GPU.

**Comment by RichardHaselgrove** [comment]
Even when running with zero cache, current clients fetch new work 3 minutes before remaining estimated time reaches zero - that enables 'just in time' workfetch and download.

The reporter mentions that a task crashed - that's always going to mess with runtime estimation. Furthermore, a task crash sets an RPC backoff (why?), so no work is fetched for well over a minute to replace the crashed task. The reporter hasn't mentioned any timescale for his observations.

I'd suggest the current behaviour is adequate, and can't be expected to handle crashes. Unless someone wants to explore the reason for the RPC deferment, I'd vote to close without further action.
