### ISSUE TITLE
user reputation

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1192]
**Reported by oeai on 18 May 42975778 23:13 UTC**
aLoha, i found that long-term issue in todo list
but i'd like to mention that this should be done asap, because with implementation of this more CPU power can be used for all projects, because with this reputation the results can be validated faster > rep can lower the size of validated file, so if you got no reputation then 70% of your file will be checked and with more wu's tested then this will be lowered, i hope you got this in mind when planning system, as well as results can be splitted between users with same rep and cpu time + cpu load, so they can work like together one will test another.
So the main idea that you don't need to validate whole file but you can take random pieces of it and with more rep amount of these pieces will be less and because of that more cpu powers can be pointed to the real processes and this is why it should be implemented.
also i found the issue of prioritizing and exchanging files, so i thought about it but as a leader of group inside project, so the groups can appear inside the project and people can prioritize jobs given for that group this can be users or meta group admins, so the project maintainers can pass some very needed data for more active group and in this group people can decide as well to get exact direction (i was thinking this for seti project, so the different clusters of stars can be splitted and people can choose which direction they will analyze)
maybe you have seen it already i've described it here 
http://setiathome.berkeley.edu/forum_thread.php?id=69850 and maybe you have thinked already about it before, so the reputation should be more prioritized i believe.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1220

**Comment by ChristianBeer** [comment]
The "reputation" was implemented and called error_rate which rpresents the trust a project can have in a host to produce valid results. With adaptive replication this can be used to increase throughput.

As to the prioritization of work this is also possible with assigning jobs to hosts, teams or users.

**Comment by davidpanderson** [comment]
Instead of error rate we now track # of consecutive validated results on a per (host, app version) basis
