### ISSUE TITLE
"Shut Down Connected Client" dialog doesn't work right

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1193]
**Reported by BarneyFifeFan on 28 Oct 43005335 05:53 UTC**
The check box in the "Shut Down Connected Client" dialog is supposed to prevent that dialog from opening again when the '''Advanced > Shut Down Connected Client'''menu option is selected. However, it does not work like it is supposed to: the dialog box keeps coming up.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1221

**Comment by ChristianBeer** [comment]
This dialog is mainly used on Windows and Mac so could someone please check if this is still broken?

**Comment by AenBleidd** [comment]
Tested on Windows 10:
Manager doesn't save option 'Do not show this dialog again'.
I'll take a look at it

**Comment by AenBleidd** [comment]
'Do not show this dialog again' is not implemented in this dialog.
@ChristianBeer, could you please assign this issue to me? I'll fix it in a couple of days.

**Comment by AenBleidd** [comment]
Fixed in #1869
