### ISSUE TITLE
Improper invocation of setup.py during build with configure --prefix leads to "ImportError: No module named boinc_path_config"

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1195]
**Reported by boinc of an eye on 26 Nov 43014171 17:56 UTC**

Many people have reported "ImportError: No module named boinc_path_config" when trying to set up the Boinc server software [[2](1]) [believe the problem is due to "make install" running this command:

`python setup.py install --prefix=/home/username/opt/boinc --root=`

Specifically, if you're compiling this in /home/username/src/boinc with a configure --prefix of /home/username/opt/boinc, these parameters cause the target to be created in /home/username/src/boinc/py/home/username/opt/boinc/lib/python2.7/site-packages.  This is clearly wrong!

A workaround is to run in the py/ subdirectory of the boinc source tree:

`python setup.py install --prefix=/home/username/opt/boinc`

The problem can be worked around by running the above command manually.  But it should really be fixed in the build scripts, so I'm filing this report.

I'm building from git commit 99eef6305535612137842ed9e5d5edc0057b1e8c on a new Ubuntu 12.10 server install in a Virtualbox VM using the following procedure:

```
./_autosetup
./configure --disable-client --disable-manager --prefix=$HOME/opt/boinc
make
make install
```

The "Version" field of this Trac ticket doesn't have 7.1.0 (the number in version.h) as an option, so it should be ignored.

[1](3].

I) http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=657036

[https://bugs.launchpad.net/ubuntu/+source/boinc/+bug/920554

[3](2]) http://article.gmane.org/gmane.comp.distributed.boinc.devel/1999/match=boinc_path_config

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1223

**Comment by lfield** [comment]
Could not reproduce with the latest code.
