### ISSUE TITLE
enable-wx-debug option for configure is not working

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1202]
**Reported by ChristianB on 11 Aug 43199070 03:22 UTC**
I tried to use the enable-wx-debug option in order to debug a manager problem I found out that`./configure --enable-wx-debug`was not working. I pinpointed the problem in a m4 script which generates the faulty code in configure. Attached is a patch that allows for proper use of --enable-wx-debug again.

Another thing I found is that ''clientgui/res/Makefile'' is not deleted when running `make distclean`. There seems to be a recursive call missing in ''clientgui/Makefile''. I don't know enough about makefiles to fix this too.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1230

**Comment by ChristianBeer** [comment]
@romw is there a way to recover the attachment of this trac ticket?

**Comment by romw** [comment]
@ChristianBeer I've re-enabled the Trac ticket system and put it in read-only mode.  You should be able to get the attachment now.

**Comment by ChristianBeer** [comment]
Thanks, I got it.

**Comment by ChristianBeer** [comment]
superseded by 530eb18
