### ISSUE TITLE
pausing boinc or GPU isnt permanent

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1204]
**Reported by Aculnay on 13 Mar 43221905 06:38 UTC**
When im starting to play a game that needs hight perfomance, i used to pause Boinc, so that the game runs fluently. But somehow Boinc decides to unpause after a random amount of time, and my game suddenly beginnst to lag like hell. So i have to close Boinc completely.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1232

**Comment by romw** [comment]
**Commented by ChristianB on 2 Sep 43223879 18:16 UTC**
Using the pause button in the taskbar does exactly that, pause the computation for some time (I think it's not random but haven't looked at the code). If you want to disable GPU processing completely you can either open the manager and disable GPU processing (and don't forget to turn it on again, that's why the pause is unpausing itself!) or add your game executable to the config file using the ''<exclusive_gpu_app>game.exe</exclusive_gpu_app>'' feature.

Extensive documentation about this can be found in the Userwiki: http://boinc.berkeley.edu/wiki/Client_configuration

If something is unclear please comment to this ticket and I try to help you.

**Comment by ChristianBeer** [comment]
I guess my original response fixed the problem.
