### ISSUE TITLE
More detailed CPU/GPU usage configuration

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1205]
**Reported by Aculnay on 3 Apr 43221917 07:54 UTC**
I think it would be great, if you could enhance the CPU/GPU usage configuration.
What i thought about is, that you can configure the usage for CPU/GPU while the pc is used and set alternative values for when the pc is not used.
For example: When the pc is used i would allow a CPU usage of 50% and no GPU usage.
But when the pc isnt used Boinc could use 100% of the CPU and also the GPU.
It would be also awesome if you could configure the GPU load.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1233

**Comment by ChristianBeer** [comment]
duplicate of #41
