### ISSUE TITLE
Simple View French Language Project Totals do not show correctly

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1207]
**Reported by JacobKlein on 29 Jan 43243541 07:05 UTC**
================================================================[jacob_w_klein@msn.com[[BR]([BR]]From:)]To: boinc_alpha@ssl.berkeley.edu[Sun, 24 Mar 2013 12:19:25 -0400[[BR]([BR]]Date:)]Subject: [Bug: Simple View French Language Project Totals[[BR](boinc_alpha])][was testing some translations for 7.0.58 x64, and noticed a problem when I switch to French.[[BR]([BR]]I)]Where it should show me the "Total work completed for project", I see strange values.[after the text that says "Travail termine ce projet: ", I see:[[BR]([BR]][[BR]]So,)][of the projects show a large negative number, followed by an e (so.... "-1008544220e" for example)[[BR]([BR]]Most)]Some projects show a large positive number, followed by an e (so... "2131403290e" for example)[some projects actually just show an e (literally, just "e")[[BR]([BR]]And)][I look at the Advanced view, on the Projets tab, for the column "Travail effectue", I see values that look correct.[[BR]([BR]]When)][the Simple View doing something wrong here?[[BR]([BR]]Is)][RE: [boinc_alpha]([BR]]Regards,[[BR]]Jacob[[BR]]================================================================[[BR]]Subject:) Bug: Simple View French Language Project Totals[Fri, 29 Mar 2013 11:03:02 -0400[[BR]([BR]]Date:)]From: romw@romwnet.org[jacob_w_klein@msn.com; boinc_alpha@ssl.berkeley.edu[[BR]([BR]]To:)][this also happen with 7.0.28?[[BR]([BR]]Does)][Rom[[BR]([BR]]-----)]================================================================[jacob_w_klein@msn.com[[BR]([BR]]From:)]To: romw@romwnet.org; boinc_alpha@ssl.berkeley.edu[RE: [boinc_alpha]([BR]]Subject:) Bug: Simple View French Language Project Totals[Fri, 29 Mar 2013 11:09:22 -0400[[BR]([BR]]Date:)][it happens to 7.0.28. Does that mean I should create a ticket?[[BR]([BR]]Yes,)]================================================================[RE: [boinc_alpha]([BR]]Subject:) Bug: Simple View French Language Project Totals[Fri, 29 Mar 2013 11:38:46 -0400[[BR]([BR]]Date:)]From: romw@romwnet.org[jacob_w_klein@msn.com; boinc_alpha@ssl.berkeley.edu[[BR]([BR]]To:)][go ahead.[[BR]([BR]]Yeah,)][Rom[[BR]([BR]][[BR]][[BR]]-----)]================================================================

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1235

**Comment by romw** [comment]
**Commented by costamagnagianfranco@yahoo.it on 13 Jun 43243566 03:18 UTC**
I cannot reproduce with italian locale

**Comment by romw** [comment]
**Commented by Ageless on 27 Jul 43243736 14:51 UTC**
I cannot reproduce with Dutch language.

**Comment by romw** [comment]
**Commented by mo.v on 9 Sep 43247452 07:47 UTC**
I have 6.12.34 in French. The project totals are correct in both places so the error must  have been introduced after this version. 

A new French translation must have been implemented after 6.12.34 where they say Travail effectu par (then username) and Travail effectu. These are both good translations. The new translations as reported by Jacob are both meaningless in French. 

I mention this in case the implementation of worse translations is somehow involved in the introduction of incorrect numerical values.

**Comment by romw** [comment]
**Commented by costamagnagianfranco@yahoo.it on 6 Dec 43254269 14:50 UTC**
I cannot change boinc locale on my pc...

is this normal?

I don't understand, this is the first time I cannot change it, I'm wondering a regression somewhere

**Comment by romw** [comment]
**Commented by mo.v on 6 Feb 43254280 04:32 UTC**
You have to exit from BOINC then restart it for the change to take effect. At least that's the case in 6.12.34.

**Comment by romw** [comment]
**Commented by costamagnagianfranco@yahoo.it on 10 Feb 43254312 13:54 UTC**
No way, I of course restarted it :)
this is when I start it up
05:10:40 PM: Error: Cannot set locale to 'it_IT'.

**Comment by romw** [comment]
**Commented by mo.v on 27 Jul 43254352 07:06 UTC**
Which BOINC version is that? Could you try a couple of other languages to see whether they can be changed? (Sorry I'm not doing this myself but 7.0.58 is incompatible with my main project, CPDN.) Spanish and Catalan should be there.

**Comment by romw** [comment]
**Commented by costamagnagianfranco@yahoo.it on 2 Mar 43254506 21:45 UTC**
tried with 6.x and 7.x in a clean quantal environment.

**Comment by ChristianBeer** [comment]
Fixed in latest dev version. Might have been fixed in a previous 7.4 or 7.6 release.
