### ISSUE TITLE
While BOINC is closed to tray, trying to launch from Start Screen or Taskbar shortcut does not restore from tray

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1209]
**Reported by JacobKlein on 27 May 43268658 11:26 UTC**
From: jacob_w_klein@msn.com[boinc_alpha@ssl.berkeley.edu[[BR]([BR]]To:)]Subject: While BOINC is closed to tray, trying to launch from Start Screen or Taskbar shortcut does not restore from tray[Sun, 7 Apr 2013 15:58:36 -0400[[BR]([BR]]Date:)][  I just noticed this behavior on my Windows 8 x64 machine, using 7.0.60 x64.[[BR]([BR]])][behavior:[[BR]([BR]]Expected)]If  BOINC has been closed to the system tray, if the user launches BOINC  Manager from either the Start Screen or a pinned Taskbar shortcut, the  already-running BOINC Manager should be restored from the tray.[behavior:[[BR]([BR]][[BR]]Actual)]Clicking the tile on the Start Screen does nothing.[ the pinned Taskbar shortcut makes the shortcut icon appear as if BOINC  is loading, but then after about 4 seconds, it reverts back to appear as  if it is not loaded.[[BR]([BR]]Clicking)][confirmed this behavior also occurs on 7.0.28, and so I'll create a ticket for it.[[BR]([BR]]I've)][[BR]]Regards,[[BR]]Jacob

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1237

**Comment by AenBleidd** [comment]
Tested on Windows 8.1 & WIndows 10 using BOINC 7.6.22. Seems it works now. Could someone check this also please?

**Comment by ChristianBeer** [comment]
Seems to work, no complaints received.
