### ISSUE TITLE
When switching Language, sometimes a "new notice" notification is generated, when there are no new notices

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1213]
**Reported by JacobKlein on 23 Jan 43273407 23:33 UTC**
When switching Language, sometimes a "new notice" notification is generated, when there are no new notices

It might be necessary to already have some notices within the Notices tab, before switching language.

But still, this shouldn't be happening, and appears to be bug.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1241

**Comment by romw** [comment]
**Commented by JacobKlein on 3 Nov 43273410 17:57 UTC**
Note: The notification appears after the user restarts the manager (to apply the new Language).

**Comment by romw** [comment]
**Commented by JacobKlein on 5 Jan 43273422 22:39 UTC**
Note: This happened on:[[BR]]Windows 8 x64, BOINC 7.0.60, attached to several projects, with 4 World Community Grid notices in the Notices tab.

**Comment by Ageless93** [comment]
We have had some Notices updates since that time. Is this still an issue?

**Comment by Ageless93** [comment]
Using BOINC 7.8.3 I have switched between Dutch and English ten times to and fro. 
Even tried changing the Notice interval from never to a week to always. 

On each start up I still have only one notice.

**Comment by AenBleidd** [comment]
Closing this for now as 'wontfix' since there was no any confirmation last 5 years that this is still an issue.
