### ISSUE TITLE
Upgrade install does not remember the "Allow all users on this computer to control BOINC" setting

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1214]
**Reported by JacobKlein on 24 Oct 43275084 13:58 UTC**
If I had the following checked when I installed the older version:[[BR]][x] Allow all users on this computer to control BOINC

... then, when I do an upgrade, the installer does not remember/use my previous setting.

I've confirmed this behavior on 7.0.27->7.0.28, and 7.0.28->7.0.62.

Rom said it's supposed to remember the setting, and that I should report it in Trac.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1242

**Comment by Ageless93** [comment]
Is this still an issue with BOINC 7.6 or 7.8?

**Comment by Ageless93** [comment]
Downgrade install BOINC 7.8.2 from 7.8.3
"Allow all users on this computer to control BOINC" is auto-selected. 
regedit shows HKEY_LOCAL_MACHINE\SOFTWARE\Space Sciences Laboratory, U.C. Berkeley\BOINC Setup\ENABLEUSEBYALLUSERS = 1

Upgrade install BOINC 7.8.3 from 7.8.2
"Allow all users on this computer to control BOINC" is auto-selected. 
regedit shows HKEY_LOCAL_MACHINE\SOFTWARE\Space Sciences Laboratory, U.C. Berkeley\BOINC Setup\ENABLEUSEBYALLUSERS = 1

Closing this issue as I cannot reproduce it with present version(s).
