### ISSUE TITLE
Installation makefile loftily wants to install stuff to /etc ... Nope!

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1227]
**Reported by Bluefin Tuna on 5 Nov 43381410 16:45 UTC**
Don't know how to solve this, but the installation makefile from the source distro thinks it has license to install to /etc.

DESTDIR in this case is unset (would anything else make sense? Looking at the code below, where DESTDIR is partially missing, no) and sysconfdir is "/etc".

```
install-exec-hook:
        chmod +x boinc-client
        $(INSTALL) -d $(DESTDIR)$(sysconfdir)/init.d
        $(INSTALL) -b $(srcdir)/boinc-client $(DESTDIR)$(sysconfdir)/init.d/boinc-client
        if [ -d /etc/sysconfig ] ; then \
          $(INSTALL) -d $(DESTDIR)$(sysconfdir)/sysconfig ; \
          $(INSTALL) $(srcdir)/boinc-client.conf $(DESTDIR)$(sysconfdir)/sysconfig/boinc-client ; \
        elif [ -d /etc/default ] ; then \
          $(INSTALL) -d $(DESTDIR)$(sysconfdir)/default ; \
          $(INSTALL) $(srcdir)/boinc-client.conf $(DESTDIR)$(sysconfdir)/default/boinc-client ; \
        else \
          $(INSTALL) -d $(DESTDIR)$(sysconfdir) ; \
          $(INSTALL) $(srcdir)/boinc-client.conf $(DESTDIR)$(sysconfdir)/boinc-client.conf ; \
        fi
```

The above is not even being run with root permission in my case (instead it is run by user 'boinc'), so simply fails and must be commented out.

Anyway, things are no longer handled that way in Fedora 17. Startup/shutdown operations are now done by via systemd, not init.

For example, httpd is started via a symlink 

/etc/systemd/system/multi-user.target.wants/httpd.service

pointing to

/usr/lib/systemd/system/httpd.service

Does the boinc client drop its privileges from root to some specified user? Not sure about that.

Anyway, this needs an overhaul.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1255

**Comment by romw** [comment]
**Commented by ChristianB on 3 Feb 43383620 17:12 UTC**
This seems to be the install script for Debian. Could you please cite the file you took this snippet from? As far as I know is the normal BOINC Installer (a bash script) creating a directory at the current working directory and does not install anything.

A little more information on your specific commands would be helpful.

**Comment by romw** [comment]
**Commented by Bluefin Tuna on 18 Feb 43385214 13:55 UTC**
Hi

Sorry about that - I didn't realize there might be several possibilities.

What I'm running here is the "Makefile" (generated from) the source repository. More precisely:

On a Fedora 17 installation:

   1. Grab the git repo
   2. ./_autosetup
   3. ./configure CXXFLAGS="-Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -fno-common" --disable-server --prefix=/home/boinc/boinc_${VERSION} 
   4. make (some errors occur but these are fixed quickly)
   5. make install

At point 5, the "client/scripts/Makefile" tries to install the startup/shutdown hooks to "/etc".

Well, one can work around easily of course, but it's still a weird thing to do.

Best regards,

-- David

**Comment by romw** [comment]
**Commented by ChristianB on 14 Mar 43385386 19:15 UTC**
I don't know if `make install` is supported anymore, I never used it to install the client. I change the Component to Clint - Build and see what davea thinks of this.

**Comment by romw** [comment]
**Commented by Bluefin Tuna on 7 Aug 44108859 07:40 UTC**
This can still be found in 7.2.9 in ```$BOINC_GIT_CLONE/client/scripts/Makefile```:

```
install-exec-hook:
        chmod +x boinc-client
        $(INSTALL) -d $(DESTDIR)$(sysconfdir)/init.d
        $(INSTALL) -b $(srcdir)/boinc-client $(DESTDIR)$(sysconfdir)/init.d/boinc-client
        if [ -d /etc/sysconfig ] ; then \
          $(INSTALL) -d $(DESTDIR)$(sysconfdir)/sysconfig ; \
          $(INSTALL) $(srcdir)/boinc-client.conf $(DESTDIR)$(sysconfdir)/sysconfig/boinc-client ; \
        elif [ -d /etc/default ] ; then \
          $(INSTALL) -d $(DESTDIR)$(sysconfdir)/default ; \
          $(INSTALL) $(srcdir)/boinc-client.conf $(DESTDIR)$(sysconfdir)/default/boinc-client ; \
        else \
          $(INSTALL) -d $(DESTDIR)$(sysconfdir) ; \
          $(INSTALL) $(srcdir)/boinc-client.conf $(DESTDIR)$(sysconfdir)/boinc-client.conf ; \
        fi
```

**Comment by Ageless93** [comment]
Is this still an issue?

**Comment by AenBleidd** [comment]
Was this fixed in d5ca3703290ffed3a92e0ad7fa89af896fed78bf ?

**Comment by smoe** [comment]
I just ran into it with current master.
```
if [ -d /usr/lib/systemd/system ] ; then \
        /usr/bin/install -c -d /usr/lib/systemd/system/ ; \
        /usr/bin/install -c -m 644 boinc-client.service /usr/lib/systemd/system/boinc-client.service ; \
elif [ -d /lib/systemd/system ] ; then \
        /usr/bin/install -c -d /lib/systemd/system/ ; \
        /usr/bin/install -c -m 644 boinc-client.service /lib/systemd/system/boinc-client.service ; \
fi
/usr/bin/install: cannot create regular file ‘/usr/lib/systemd/system/boinc-client.service’: Permission denied
make[4]: *** [Makefile:545: install-exec-hook] Error 1
```´
git log:
```
commit a3b91098da638a1fda28a3e717fd7a8463a5faa0 (HEAD -> master, origin/master, origin/HEAD)
Merge: 5e5847ac0a 0a62f0e9af
Author: Kevin Reed <22824141+TheAspens@users.noreply.github.com>
Date:   Mon Jul 1 08:43:35 2019 -0500

    Merge pull request #3198 from BOINC/dpa_amd

    scheduler: if plan class name contains "amd", assume it's AMD GPU

```

**Comment by AenBleidd** [comment]
I believe this is a different issue
