### ISSUE TITLE
Application Name and Version not Shown in Tasks View

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1285]
**Reported by knreed on 21 Jun 43566382 18:25 UTC**
The user friendly version of the application name for a given task is not being displayed on the tasks view. This is an important piece of information.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1313

**Comment by romw** [comment]
**Commented by JacobKlein on 3 Mar 43566487 12:38 UTC**
What do you mean?

On the Advanced View, if I go to the Tasks tab, within the grid is a column called "Application" that appears to show the friendly Application name, the version of the application, and also the plan (I think -- it says things like (cuda42) or (nci).

On the Simple View, within the Tasks combobox, the entries appear to be actually named by the friendly Application name.

Is it possible that you may have accidentally resized the "Application" column on the Advanced View grid? Its location is between the "Deadline" column and the "Name" column. Even if you did resize it to 0, if you move the mouse cursor to be as far right as possible near that resizing area between those columns, you should see a special resizing-cursor that will allow you to add size to the 0-size column.

Does that help at all? Or is your problem something else entirely? Or maybe are you referring to Android?

**Comment by romw** [comment]
**Commented by knreed on 13 Nov 43566500 22:28 UTC**
Please see my screen shot.  When I first installed (this version or one of the stock BOINC versions) the column was shown.  However, it has disappeared.  I will try restarting my computer and see what happens.

**Comment by romw** [comment]
**Commented by JacobKlein on 16 May 43566525 08:09 UTC**
Did you try seeing if it is a 0-size column that needs to be resized? I have attached a file that includes 4 images.

Images 1 and 2 show using the standard mouse cursor to resize an existing column.[[BR]]Images 3 and 4 show using the special "unhiding a colum" cursor to add size to a currently-hidden 0-size column.

Does this help you at all?

**Comment by romw** [comment]
**Commented by knreed on 8 Aug 43566569 14:28 UTC**
Ok - yes - it was a 0 width column.

Since I did not intentionally make it 0 width it is possible I did it accidentally. However, I would argue that 0 width columns are not a good practice. If the intention is that columns should be selectable, then there should be a dialogue that allows for the selection of columns shown (for example, right mouse click on the header/title row and choose what columns should show) and then make a 1 width min exist for columns so they don't vanish.

I will downgrade this to minor though since I believe it required user interaction to make it disappear.

**Comment by romw** [comment]
**Commented by JacobKlein on 3 May 43566629 02:56 UTC**
I'm glad that was the "problem".

I'm of the opinion there should be some way to hide a column. I'm not sure how much flexibility they have in the WxWidgets controls, so the current solution may be the only option, not sure.

But because setting a column this way is the intentional behavior currently, you might even consider changing this ticket from Defect to Enhancement.

**Comment by ChristianBeer** [comment]
There is a "Select columns..." menu option in 7.6.33 which was I believe added in the 7.6 series.
