### ISSUE TITLE
When overriding ignore on post, reload the page the post is on, not the whole thread.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1300]
**Reported by Ageless on 6 Jan 43681625 19:31 UTC**
With the present implementation of the ignore function, when I click the "Click here", the thread gets reloaded from post 1 and all the posts of the person on ignore become visible, not just the one post I wanted to see.
Now, with the new function of so many posts per page, and I want to see what this person wrote yet his post is on page 3, the thread reloads from post 1 as well. By the time I get back to page 3, where the post of interest is, it's hidden again.

Can the 'see this ignored post' function therefore get a page check, see what page the post is on and only reload that page, instead of the whole thread?[[br]]
And can the function of click here be only for that one post, not for all posts by the same person? 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1329

**Comment by Ageless93** [comment]
This has been fixed some time ago by David. It works as requested in Bootstrap.
