### ISSUE TITLE
Sometimes Images in Notices can crash BOINC Manager

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1304]
**Reported by JacobKlein on 4 Apr 43890241 17:25 UTC**
Below is an email, describing a situation where an image in a news feed from theSkyNet pogs ends up not being loaded correctly in the Notices tab, and the BOINC Manager crashes. I've also included some crash signatures, so hopefully when we get back to fixing this (for version 7.4 per Rom), it might be easier to find out what's going on. In the meantime, Rom is disabling downloading images in notices.

---

Subject: RE: [7.2.28 BOINC Manager hang up

Date: Wed, 20 Nov 2013 15:32:04 -0500[[BR](boinc_alpha])]From:[putting together a 7.2 build that disables downloading image files.

This issue will be fixed in 7.4.

----- Rom

'''From:''' Jacob Klein ![[BR]([BR]]To:[[BR]][[BR]]I'm)]'''Sent:''' Wednesday, November 20, 2013 3:28 PM[Richard Haselgrove; Rom Walton; [[BR]([BR]]'''To:''')]'''Cc:''' BOINC Alpha[RE: [boinc_alpha]([BR]]'''Subject:''') 7.2.28 BOINC Manager hang up

I am able to reproduce this crash, sometimes, I believe.[ added theSkyNet pogs, and their "image notice" looked okay. So then I  closed BOINC Manager (but left tasks running), then reopened BOINC,  and...[[BR]([BR]]I)][seems that 1 of the following 3 things happens:[[BR]([BR]]It)]- Sometimes it shows the notices without error (but won't show the image)[Sometimes it says "Fetching notices; please wait...", and after exactly 30 seconds, BOINC Manager disappears/crashes[[BR]([BR]]-)]-  Sometimes it'll partially load, with a message at the top that says  "One or more items failed to load from the Internet.", with a "Retry  Now" box, with the notices underneath showing all my notices except, for  the pogs one, it shows a broken-image-graphics where the image should  be.[my recent crashes, here are the 7.2.28 crash signatures from stderrgui.txt (Note, there are 3 distinct signatures here):[[BR]([BR]][[BR]]For)]Reason: Access Violation (0xc0000005) at address 0x00007FFE000E9CDF read attempt to address 0x00000000[Access Violation (0xc0000005) at address 0x00007FFE000E9CDF read attempt to address 0x00000000[[BR]([BR]]Reason:)]Reason: Access Violation (0xc0000005) at address 0x00007FFE09E9BB96 write attempt to address 0x00000024[Access Violation (0xc0000005) at address 0x00007FFE09E9BB96 write attempt to address 0x00000024[[BR]([BR]]Reason:)]Reason: Access Violation (0xc0000005) at address 0x00007FFE09E9BB96 write attempt to address 0x00000024[Access Violation (0xc0000005) at address 0x00007FFE09E9BB96 write attempt to address 0x00000024[[BR]([BR]]Reason:)]Reason: Access Violation (0xc0000005) at address 0x00007FFE09E9BB96 write attempt to address 0x00000024[Access Violation (0xc0000005) at address 0x00007FFE09E9BB96 write attempt to address 0x00000024[[BR]([BR]]Reason:)]Reason: Access Violation (0xc0000005) at address 0x00007FFE09E9BB96 write attempt to address 0x00000024[Access Violation (0xc0000005) at address 0x00007FFE00140A12 read attempt to address 0x00000090[[BR]([BR]]Reason:)][[BR]]Helpful at all?

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1333

**Comment by romw** [comment]
**Commented by JacobKlein on 8 Jan 43890246 14:10 UTC**
Note: There are some earlier emails, in the BOINC Alpha mailing list, which leads me to believe some other project also has images that are causing a problem (ie: It's not just theSkyNet pogs)

**Comment by romw** [comment]
**Commented by Ageless on 11 Jul 43890529 15:15 UTC**
Removing my own and others their email addresses. Spam bots do read here.

**Comment by romw** [comment]
**Commented by JacobKlein on 30 Mar 43890629 20:01 UTC**
Thanks, and sorry.

**Comment by romw** [comment]
**Commented by JacobKlein on 16 Oct 43893360 00:58 UTC**
Well, I presume 7.2.28.1 was the release where notices code was changed to not download images.

I retested 7.2.28.1, by subscribing to theSkyNet pogs, and selecting the Notices tab in Advanced view, and then restarting BOINC... over and over (10 times)

It did fail 1 of those times. It said "Fetching notices" for ~20-30 seconds, and then just closed. The stderrgui.txt file did have the following info regarding the crash:

Reason: Access Violation (0xc0000005) at address 0x00007FFE000E9CDF read attempt to address 0x00000000

Perhaps this is a separate bug? Maybe it's the same bug? I just knew I should report it.

**Comment by romw** [comment]
**Commented by JacobKlein on 27 May 43893799 02:20 UTC**
I tested 7.2.31 quite thoroughly. The disabling is now working entirely. For 30 reopens while on the Notices tab while attached to pogs, I never once saw the "Fetching notices... please wait..." message, and it loaded correctly each time. The pogs news post with the dynamic images/script showed 2 "broken image placeholder" images, but I think that was expected.

So, at least the disable is now working. Not sure if this defect should remain open until we can get images working again or not.

**Comment by ChristianBeer** [comment]
This was fixed in the 7.4 series.
