### ISSUE TITLE
BOINC screen saver flickers

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1309]
**Reported by Ageless on 9 May 44142316 02:47 UTC**
As has been reported through https://boinc.berkeley.edu/dev/forum_thread.php?id=8915 at first, when upgrading from an older BOINC version to 7.2.39 or when doing a clean install of 7.2.39, the screen saver will flicker. 

What we actually see is that the screen saver starts normally, then it'll start to switch between the Boincscr.exe and Boinc.scr screens in rapid fashion. 

Mostly noticed on Windows 7. Reports are that when going back to 7.2.33 or earlier, that the problem ceases immediately. 

I've found out that only the BOINC screen saver has to run, BOINC doesn't even need to run. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1338

**Comment by romw** [comment]
**Commented by Ageless on 31 Jan 44174058 03:45 UTC**
Threads with this problem:[[[br]([br]]
https://setiathome.berkeley.edu/forum_thread.php?id=74178)]
https://setiathome.berkeley.edu/forum_thread.php?id=74245 [[[br]([br]]
https://boinc.berkeley.edu/dev/forum_thread.php?id=8915)]

**Comment by ChristianBeer** [comment]
Is this reproducible with current 7.6.33?

**Comment by Ageless93** [comment]
I'll have to reinstall BOINC on the TV server to test that. In the mean time the system has had a new videocard and is streaming to a 4K LED TV, so would be interesting. Will be back on this.

**Comment by Ageless93** [comment]
Took me a while to get back, but can report that with BOINC 7.8.1 and my TV, I cannot reproduce this problem. Will close.
