### ISSUE TITLE
Change Notice notification icon to make it recognizable

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1314]
**Reported by Joachim on 22 Aug 44182133 23:56 UTC**
envelope icon is too generic. Asked WCG for a BOINC branded envelope icon

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1343

**Comment by Ageless93** [comment]
Is this still an issue?

**Comment by SETIguy** [comment]
If it has been fixed in the code, it has not been deployed on android.

**Comment by Ageless93** [comment]
Is it just for Android then, or for all platforms?

**Comment by Ageless93** [comment]
Ah never mind, just noticed the Android Manager label there. :)

**Comment by AenBleidd** [comment]
Fixed via #4006
