### ISSUE TITLE
Add preference: buffer size

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1317]
**Reported by Joachim on 16 Sep 44261019 17:52 UTC**
buffer size important to volunteers who infrequently connect to WiFi networks.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1346

**Comment by romw** [comment]
**Commented by Joachim on 23 Mar 44289244 20:11 UTC**
see preference <work_buf_additional_days>%f</work_buf_additional_days>

**Comment by Ageless93** [comment]
I'm not sure I follow the request. What's wanted here?

**Comment by AenBleidd** [comment]
Closing this because #2755 has more detailed and accurate description of the same feature request
