### ISSUE TITLE
Manual RPC

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1325]
**Reported by Joachim on 15 Sep 44351393 06:52 UTC**
Expose a field (advanced!) to the UI to let people write their own GUI RPCs. This feature is advanced, and should be hidden somewhere (menu in EventLog?).

Allows advanced users to use functionality of the BOINC client, that is not exposed to the (supposed to be self explanitory) Android Manager.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1354

**Comment by davidpanderson** [comment]
not clear.
