### ISSUE TITLE
Stationary device mode: enable by default on stationary devices

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1331]
**Reported by Joachim on 12 Sep 44461575 01:05 UTC**
Otherwise app start in benchmarking, until stationary device mode is enabled by user in preferences

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1360

**Comment by AenBleidd** [comment]
Is still still an issue? By default, benchmark is running on fresh install, after application update and then one timer per month. I believe these rules are good enough and no special case for Android should be done.
