### ISSUE TITLE
proxy issue on UI

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1333]
**Reported by Philip Lourandos on 4 Jun 44622500 23:22 UTC**
OS: windows 7 enterprise

I need to change my password due to security policies for Active Directory. I changed my password to: Qmv<OZ%Q
I updated the proxy settings via tools -> options -> HTTP Proxy.
I entered the full password above. I can see 8 masked characters in the text field. I press 'OK' and the dialog closes. I go back and I can only see 3 masked characters. The knock on effect my account was being locked out due to authentication failures by boinc.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1362

**Comment by Ageless93** [comment]
We have had some proxy fixes since this issue was brought forth. Is this still an issue on BOINC 7.6 or 7.8?

**Comment by AenBleidd** [comment]
Up

**Comment by RichardHaselgrove** [comment]
Proxy passwords are handled at https://github.com/BOINC/boinc/blob/master/lib/url.cpp#L63

The most recent patch on that file is ff7633a65def104b81a82b839f98fbe4b383f42f - much more recent than the bug report. Time for a re-test?

**Comment by ab1vl** [comment]
10-31-18; I'll need some guidance on how to properly test this. The original bug filing included interaction with Active Directory (presumably MS?) and I do not have the ability to set that up, if it is required.

**Comment by AenBleidd** [comment]
Looks like this was already fixed.
Since the testing of it is quite complex, I'm closing this because we haven't received any issue report about this during last several years.
