### ISSUE TITLE
bootstrap: group input fields into input-groups

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1334]
**Reported by ChristianB on 25 Oct 44757056 13:48 UTC**
input fields that belong together should be grouped.

see: http://getbootstrap.com/css/#forms

places to look at: forum.inc, team.inc, profile_menu.php, edit_user_info_form.php, forum_forum.php, forum_thread.php

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1363

**Comment by AenBleidd** [comment]
@ChristianBeer, @brevilo, @drshawnkwang, is it still an issue?

**Comment by brevilo** [comment]
@drshawnkwang and I haven't been involved in this.

**Comment by AenBleidd** [comment]
@davidpanderson, is it still an issue?

**Comment by davidpanderson** [comment]
I don't think so.  We use "form-group", which seems to do the same thing.
