### ISSUE TITLE
bootstrap: add pager and pagination divs

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1335]
**Reported by ChristianB on 21 Mar 44757061 12:54 UTC**
see: http://getbootstrap.com/components/#pagination

places to look at: result.inc, team.inc, forum_user_posts.php, profile_search_action.php, top_hosts.php, top_teams.php, top_users.php

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1364

**Comment by AenBleidd** [comment]
@ChristianBeer, @brevilo, @drshawnkwang, is it still an issue?

**Comment by brevilo** [comment]
@drshawnkwang and I haven't been involved in this.

**Comment by AenBleidd** [comment]
@davidpanderson, is it still an issue?

**Comment by davidpanderson** [comment]
It would be a slight improvement to have pagination buttons instead of the "Next 20" links.
But this is unimportant as far as I'm concerned.
