### ISSUE TITLE
bootstrap: group buttons that are in the same form

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1336]
**Reported by ChristianB on 22 Aug 44757064 08:51 UTC**
mainly for those ok, cancel buttons

see: http://getbootstrap.com/components/#btn-groups

place to look at: util.inc

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1365

**Comment by AenBleidd** [comment]
@ChristianBeer, @brevilo, @drshawnkwang, is it still an issue?

**Comment by brevilo** [comment]
@drshawnkwang and I haven't been involved in this.

**Comment by AenBleidd** [comment]
@davidpanderson, is it still an issue?

**Comment by davidpanderson** [comment]
Not as far as I'm concerned.
