### ISSUE TITLE
bootstrap: show_login_info.php needs to be overridable by the project

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1341]
**Reported by ChristianB on 11 Apr 44757079 00:43 UTC**
When using bootstrap and navigation bars the project may need to adjust the html structure and classes in this function.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1370

**Comment by AenBleidd** [comment]
@ChristianBeer, @brevilo, @drshawnkwang, is it still an issue?

**Comment by brevilo** [comment]
@drshawnkwang and I haven't been involved in this.

**Comment by AenBleidd** [comment]
@davidpanderson, is it still an issue?

**Comment by davidpanderson** [comment]
I guess not!
