### ISSUE TITLE
account for max_concurrent in work fetch

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1344]
**Reported by davea on 22 Sep 44922147 23:20 UTC**
Work fetch doesn't take max_concurrent into account, leading to idle devices in some situations.  Need to:
1) use max_concurrent in round-robin simulation
2) in work fetch, skip projects that are blocked on max_concurrent

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1373

**Comment by ChristianBeer** [comment]
@davidpanderson this is your area of expertise. Do you know if this is already implemented and if it affects other issues of the Work Fetch Policy tag?

**Comment by Ageless93** [comment]
@davidpanderson any updates?

**Comment by davidpanderson** [comment]
This was fixed in 81a880c74df (Mar 2019)
