### ISSUE TITLE
don't truncate email addr auto-fill in Android, and error-check the field

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1349]
**Reported by davea on 14 Oct 45034338 10:27 UTC**
It was reported that the auto-fill of email addr in the Android client truncated an address, and that this wasn't marked as an invalid addr.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1378

**Comment by AenBleidd** [comment]
Is this still an issue? Can't reproduce it now
