### ISSUE TITLE
boinccmd does not give correct error message when not authorized

### ISSUE THREAD

**Issue by BenjiWiebe** [BOINC/boinc#1359]
When 'boinccmd --quit' is called without being in the directory where gui_rpc_auth.cfg is located, it fails with 'Operation failed: Error -1', but it should print 'Operation failed: authentication error'  instead.

**Comment by BenjiWiebe** [comment]
Here is a patch to fix this issue:

diff --git a/lib/gui_rpc_client.cpp b/lib/gui_rpc_client.cpp
index a6c2a15..d2015ac 100644
--- a/lib/gui_rpc_client.cpp
+++ b/lib/gui_rpc_client.cpp
@@ -378,15 +378,17 @@ int RPC::parse_reply() {
     char buf[256], error_msg[256];
     int n;
     while (fin.fgets(buf, 256)) {
+        if (strstr(buf, "boinc_gui_rpc_reply>"))
+            continue;
         if (strstr(buf, "<success")) return 0;
         if (parse_int(buf, "<status>", n)) {
             return n;
         }
+        if (strstr(buf, "<unauthorized/>")) return ERR_AUTHENTICATOR;
         if (parse_str(buf, "<error>", error_msg, sizeof(error_msg))) {
             fprintf(stderr, "%s: GUI RPC error: %s\n",
                 time_to_string(dtime()), error_msg
             );
-            if (strstr(error_msg, "unauthorized")) return ERR_AUTHENTICATOR;
             if (strstr(error_msg, "Missing authenticator")) return ERR_AUTHENTICATOR;
             if (strstr(error_msg, "Missing URL")) return ERR_INVALID_URL;
             if (strstr(error_msg, "Already attached to project")) return ERR_ALREADY_ATTACHED;

**Comment by ChristianBeer** [comment]
Can you submit this as a pull request please? And leave it backwards compatible? An older client just might send the ```<error>unautorized</error>``` reply.
