### ISSUE TITLE
Battery Monitor: UX 

### ISSUE THREAD

**Issue by Wizardofoddz** [BOINC/boinc#1362]
Battery Monitor: Make the UX display battery information like this app: 
https://play.google.com/store/apps/details?id=com.gombosdev.ampere&hl=en 
Or just say its a battery conditioner

**Comment by AenBleidd** [comment]
Goal of BOINC application on Android to run calculation tasks on mobile device.
It is not supposed to show any battery information even despite that fact that it uses this information to control task run scheduling.
Closing this ticket as not an issue.
If you this that BOINC application should display this information feel free to reopen this ticket
