### ISSUE TITLE
Add visual warning that an input box's value has been put in wrong, and which box. 

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#1370]
Add a way for a faulty input in BOINC Manager preferences to show what was input wrong and where it was input wrong and what the correct input range is. 
From Rom: We could use the control's FOCUS_ENTER/FOCUS_LEAVE events to trigger warnings on content validation errors.

**Comment by AenBleidd** [comment]
I think this issue is currently fixed in a scope of another changes in 7.6.9 release version
