### ISSUE TITLE
[pre][/pre] containers in [code][/code] containers on BOINC forum code execute, instead of show the container codes

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#1381]
While teaching someone how to use all the tag containers, I added [pre] .. [/pre] in a code container ([code] .. [/code]) and found that it's executed inside the code container.

It shows as a code box, but then with  

```
<div class="pre">..</div>
```

in the post preview and in the post.
I expect that it shows [pre]..[/pre] in the code container.

Is someone able to fix this?

**Comment by ChristianBeer** [comment]
Is still happening with bootstrap?

**Comment by Ageless93** [comment]
Yep: https://boinc.berkeley.edu/dev/forum_thread.php?id=11565#77314

**Comment by ChristianBeer** [comment]
The interesting thing with your example is that [pre] gets translated to html but [url] not. This seems to be a problem with the bbcode2html parser which should ignore bbcode tags if they are inside [code] tags.

**Comment by Ageless93** [comment]
As
https://boinc.berkeley.edu/dev/forum_thread.php?id=11565&postid=77317#77317
shows, everything else works. Well, but for showing code tags within code
tags, then the end code tag doesn't work. ;-)

As an aside, I can execute <code> tags though, but not <url> tags.


-- Jord van der Elst.

**Comment by ChristianBeer** [comment]
Ok, the problem is [pre] inside [code] gets translated to html while it should stay bbcode. This needs to be fixed.

The [code] within [code] does not work by design of the parser. I believe it's not worth fixing that particular problem. A workaround would be to use [code] within [pre] which should have the same effect (if not it's a bug again).

**Comment by Ageless93** [comment]
Good idea. Hadn't thought of that. Yes, that works as normal, I did
[pre][code][color=red]Red text[/color][/code][/pre] which just shows the
middle, and shows it unexecuted.

That I can execute some HTML codes is because I have the administrator
title. I'd like to keep being able to do that as it sometimes helps
clearing up some code in a sentence, without having to use the cumbersome
code boxes.

By the way, previewing any post with code in it shows the code tags as
well, not executed, while it will show things like bold, strike through,
italics and underline in executed form. That to do with the same parser? Or
a separate issue I need to write a separate ticket for?


-- Jord van der Elst.

**Comment by ChristianBeer** [comment]
Ideally the same parser is used for preview and afterwards. I think that can be fixed together with the [code] tag issue.

**Comment by davidpanderson** [comment]
The same function (output_transform(), in text_transform.inc)
is used for preview and final version.
