### ISSUE TITLE
BOINC not working on Galaxy Neo Note

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1384]
Report from a user:
Device: Samsung Galaxy Neo Note
Android Kitkat 

Preferences are not being saved. 
Also am not able to add more than one project. 

Screenshot attached as proof. Let me know if more info is required. Please fix at the earliest. 

![image](https://cloud.githubusercontent.com/assets/985729/9556819/593dfcc4-4d8c-11e5-84c9-78474784fbbc.png)

**Comment by AenBleidd** [comment]
Description given in this ticket is very similar to #2211. Closing this in favor of more detailed ticket
