### ISSUE TITLE
Recommend 7.4/7.6 for Linux?

### ISSUE THREAD

**Issue by felixonmars** [BOINC/boinc#1387]
Currently the recommended version for Linux x86/x64 is still 7.2.42 on the website (https://boinc.berkeley.edu/download_all.php)

As I have been using the latest version (7.6) for quite some time without an issue, I would like to know if there is a plan for recommending 7.4/7.6 series for Linux?

On the other hand, as I am packaging boinc for Arch Linux, I would like to know if you would like us to push the latest version instead of the recommended one on that page. Thanks!

**Comment by felixonmars** [comment]
Just FYI that we are now providing the latest release `7.6.22` in the repositories, since this issue got not replies so far :(

**Comment by felixonmars** [comment]
Any updates on this issue? The recommendation still didn't change.

**Comment by ChristianBeer** [comment]
Oops, I thought we changed that. Considering the time since 7.6.33 was released and how long it is running without major problems on Debian and Ubuntu you can consider 7.6.33 to also be the recommended version on Linux. I'll need to prepare a file for download in order to change the official page.

**Comment by Ageless93** [comment]
Isn't the official stance that Linux versions are built by packet
maintainers and released through packet managers? This to minimize the
compatibility problems over the wide range of Linux distros, or problems
due to (missing) libraries on users systems?


-- Jord van der Elst.

**Comment by felixonmars** [comment]
We (package maintainers) are referring to the official recommended version, though. It is fine for me to provide only source distribution.

**Comment by ChristianBeer** [comment]
The system behind the download page is not made for source distribution only, so we have to provide a Linux installer although we say that it should not be used. On the todo list for tomorrow.

**Comment by felixonmars** [comment]
I see. Thanks a lot!

**Comment by davidpanderson** [comment]
Our policy is to release a Linux version that works on the latest Ubuntu at the time.
We don't try to support any other distros.
-- D

**Comment by Ageless93** [comment]
Any updates on this issue?

**Comment by Ageless93** [comment]
The BOINC client v7.8.3 is available for testing on Linux

For Debian/Ubuntu

sudo apt-add-repository ppa:costamagnagianfranco/boinc
sudo apt-get update
sudo apt-get install boinc-manager

For Fedora/RedHat/CentOS

sudo dnf config-manager --set-enable updates-testing
sudo dnf install boinc-manager

Test reports can be sent to the alpha testing project and bugs can be reported to the Fedora or Debian bug trackers respectively.

**Comment by lfield** [comment]
I would suggest we follow the same approach as HTCondor. On their [download](http://research.cs.wisc.edu/htcondor/downloads/) page it says:
> We recommend that you install HTCondor from a repository on Linux platforms. The tarballs are still available below if you need to be able to place the software in a custom location. 
The text links to the [instructions](http://research.cs.wisc.edu/htcondor/instructions/) page. I would be happy to write the instructions page if needed.

**Comment by AenBleidd** [comment]
As I see it is not an issue and can be closed.

CC: @RichardHaselgrove

**Comment by RichardHaselgrove** [comment]
Agreed - we are being far more proactive in updating the packages with recent releases.
