### ISSUE TITLE
BOINC has some projects not listed 

### ISSUE THREAD

**Issue by AlmightyAug** [BOINC/boinc#1390]
I have a few phones which run BOINC on android. Only some phones can show Citizen Science Grid but some of the other phones do not show Citizen Science Grid. The project listing has missed some projects. Please fix this issue. Android 5.0.1. Device: Samsung GT-i9505

**Comment by ChristianBeer** [comment]
The list of projects gets downloaded from boinc.berkeley.edu from time to time. Maybe the list got updated on some phones and not on others. Are you sure the version on each phone is the same?

**Comment by AlmightyAug** [comment]
It is the same version. but if you look in the pictures to compare, you will realise that some projects is missing on the 2 different phones.

![20150921_000128 1](https://cloud.githubusercontent.com/assets/12712386/9981618/9bb5be96-5ff4-11e5-89db-b374e9bb2e0e.jpg)
![20150921_000216 1](https://cloud.githubusercontent.com/assets/12712386/9981622/a5227a28-5ff4-11e5-99ea-76e29080ac46.jpg)
![20150921_000239 1](https://cloud.githubusercontent.com/assets/12712386/9981626/ad09d95c-5ff4-11e5-9b46-3c05bd8a9d73.jpg)
![20150921_000246 1](https://cloud.githubusercontent.com/assets/12712386/9981629/bde958e2-5ff4-11e5-93f7-518fdd774c71.jpg)

**Comment by AenBleidd** [comment]
@AlmightyAug, do you still have some devices that you use for BOINC and have described issue?

**Comment by AenBleidd** [comment]
Looks like this issue should be fixed in the upcoming release. Need to be verified
