### ISSUE TITLE
BOINC server VM comes with out-of-date remotes

### ISSUE THREAD

**Issue by tdelac** [BOINC/boinc#1391]
Looks like the vm shipped here:
https://boinc.berkeley.edu/trac/wiki/VmServer

Comes with the git repository referencing a location that does not exist anymore. Changing the remote to this github repository seems to have fixed it.

**Comment by ChristianBeer** [comment]
I will update the VM and fix this. A new version should be up next week.

**Comment by tdelac** [comment]
Thanks!

**Comment by ChristianBeer** [comment]
I uploaded and linked a new VM. See the link above.
