### ISSUE TITLE
Change [trac]#ticket[/trac] code in text_transform.inc to use github instead

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#1397]
Is it possible that someone changes the code in text_transform.inc for [trac]#ticket[/trac] to use [github]#ticket[/gitgub] instead? Possibly also useful for the [trac]changeset:N[/changeset] code. 

As far as I know, we can still use the [trac]wiki:??[/trac] code to point to stuff in the BOINC Wiki (e.g. http://boinc.berkeley.edu/trac/wiki/ProjectMain), although it would be nice if this code could point to the User Wiki (e.g. http://boinc.berkeley.edu/wiki/Main_Page) as well.

**Comment by RichardHaselgrove** [comment]
It would be good (but I don't know how feasible) if this could incorporate a lookup table, so that historical posts don't link a trac ticket number to an unrelated github issue number.
