### ISSUE TITLE
Windows 10 - doesn't autostart on boot

### ISSUE THREAD

**Issue by StevePLMarquis** [BOINC/boinc#1398]
BOINC manager will not autostart on boot, you have to fire it up manually then it's OK.

**Comment by ChristianBeer** [comment]
This needs to be verified.

**Comment by AenBleidd** [comment]
I did not see such error while working on Win10 (Anniversary update).

**Comment by StevePLMarquis** [comment]
This was resolved in subsequent updates.  I raised it in Oct 2015 !
