### ISSUE TITLE
Private message responses through email...

### ISSUE THREAD

**Issue by SETIguy** [BOINC/boinc#1399]
It would be nice for Moderators/Admins to be able to respond to a PM via email.  A crypographic hash tag in the response would be sufficient to provide the authentication of the source.

**Comment by RichardHaselgrove** [comment]
If they reply by PM, and email notification is enabled in your account preferences, you will receive an email containing the full text of the PM. I can't see what else might be needed.

**Comment by SETIguy** [comment]
I don't want to have to log into the SETI@home Web site on my phone in
order to reply to a pm.

For example I replying to this message on my phone in the mail client with
logging into github.

**Comment by SETIguy** [comment]
I guess there would need to be an sendmail/procmail/whatevermail filter that would parse the message and enter the message into the database.  I'd write it myself if I had the time.  I may even though I don't.

**Comment by AenBleidd** [comment]
While this looks like a good functionality, in reality it will create a log of issues and visual noise  (e.g. email signature and the replied message will be included into the post if not cleared by user), and the post above (https://github.com/BOINC/boinc/issues/1399#issuecomment-146371859) is the great example of that.

Closing this without any further actions.
