### ISSUE TITLE
Android 6.0

### ISSUE THREAD

**Issue by m-gregory-github** [BOINC/boinc#1408]
boinc 7.4.41 does not work on android 6.0.
each unit runs until it reaches 100% then just keeps running (the time used keeps increasing).
Therefore it never seems to upload.

I have tried uninstalling and reinstalling to no effect.

Also it seems my 17000 someodd credits have vanished.

**Comment by SETIguy** [comment]
Which project are you running on?  It could be a problem with their app's
stat keeping.

On Fri, Oct 16, 2015 at 12:35 PM, m-gregory-github <notifications@github.com

**Comment by m-gregory-github** [comment]
Hi,
Sorry I should have provided this before:

Runing on a Nexus 9 with World Community Grid.  Before the upgrade to 6 the
thing just cranked out results (I don't use it for anything else.)
Hope this helps and thanks

Mike

**Comment by m-gregory-github** [comment]
Hi,

Since my last replay:

I have deleted everything I could find re: boinc and reinstalled.  It seems
to be running now.  It still thinks my nexus is a different device.

Hope this helps in some way.

Mike

**Comment by Stiwi** [comment]
I think this is a problem of the World Community Grid app.

There are also a few posts on their forum:
http://www.worldcommunitygrid.org/forums/wcg/viewthread_thread,37915
https://secure.worldcommunitygrid.org/forums/wcg/viewthread_thread,37770

**Comment by brevilo** [comment]
FWIW, current `master` runs just fine on AOSP 6.0.1.
