### ISSUE TITLE
Task list items selection focus jumps

### ISSUE THREAD

**Issue by Viking69** [BOINC/boinc#1409]
My PC is Win 7 x64 and BOINC version 7.6.9.
I have started a message board thread too: http://boinc.berkeley.edu/dev/forum_thread.php?id=10562 Basically, if I have more than one task for a project, and I select any other task but the top most for that project, the focus jumps to the top most item for that project. This happens really quick. This prevents you from selecting any items in the commands list. This even happens if all projects are suspended.

**Comment by ChristianBeer** [comment]
According to fourm posts fixed in 7.6.18
