### ISSUE TITLE
Android client fails to get project list

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1411]
From boinc_projects:
We followed the wiki and built the app successfully.
But, once launched,logging in, it shows null projects with continue button.

In logcat, we see BOINC_GUI: UpdateProjectListAsyncTask: fails to retrieve
data.

**Comment by Ageless93** [comment]
Same issue as in #1384

**Comment by AenBleidd** [comment]
Closed as a duplicate of #1384
