### ISSUE TITLE
run while screensaver running

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1417]
(from boinc_android_testing):
I've grown rather fond of the Daydream screensaver in newer Android releases, but it has been eating into my BOINC credit, as I keep the "Pause computations while screen is on" setting enabled, to keep my device nice and snappy. However, I really don't need performance for Daydream mode, and it would be nice to see a setting that would allow computations while in Daydream mode, regardless of the current "Pause computations while screen is on" setting.

**Comment by AenBleidd** [comment]
Latest Android OSs have policies to limit background activity of applications (when they are not on foreground).
So running BOINC in background with screensaver of foreground is not reasonable.
Closing this as 'Won't fix'
