### ISSUE TITLE
Manager should verify network connectivity before launching the wizards.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#142]
**Reported by romw on 3 Apr 37330957 07:33 UTC**
- if network activity is suspended (either explicitly,
  or because of time-of-day settings) and the user tries
  to attach to a project or update a project,
  a dialog appears that says
  "To complete this operation BOINC needs to resume
  network activity - OK?"
  and if they click OK, the network mode is set to Always.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/142

**Comment by romw** [comment]
**Commented by romw on 22 Dec 37357055 10:13 UTC**
Bump to 6.0

**Comment by ChristianBeer** [comment]
The latest (7.6.33) behavior is that projects can be added regardless of network activity setting. If this is not the desired behavior please open a new issue.
