### ISSUE TITLE
When boinc gpu is paused and boinc is paused complete one context menu check is missing on Windows

### ISSUE THREAD

**Issue by informatorius** [BOINC/boinc#1423]
This is how it looks when GPU is snoozed.
![boincsnoozegpu](https://cloud.githubusercontent.com/assets/6989214/10863147/fe0916f8-7fc3-11e5-94a4-8db1204536e1.png)

When boinc is snoozed complete additionaly to gpu snooze then GPU context menu check is missing.
![boincsnoozegpu complete](https://cloud.githubusercontent.com/assets/6989214/10863139/b9ef79c6-7fc3-11e5-860f-d18a30fe9bd3.png)

When complete snooze check is removed then gpu snooze check is shown again.
This looks inconsistent to me.

**Comment by AenBleidd** [comment]
I suggest next scenario:
When "Snooze" is checked make "Snooze GPU" checked and disabled to avoid user enabling GPU only. I think it will be more understandable.

Rom Walton, David Anderson: What do you think?
I can fix this issue quite fast but I need your final decision.

Thanks

**Comment by ChristianBeer** [comment]
It sounds very reasonable to make it clear that "Snooze" also includes "Snooze GPU" in the way @AenBleidd described it. @romw what do you think?

**Comment by romw** [comment]
Sound fine to me.

**Comment by AenBleidd** [comment]
Fixed in https://github.com/BOINC/boinc/pull/1425

**Comment by informatorius** [comment]
Solved with Boinc 7.6.22
