### ISSUE TITLE
Is there a way to hide Boinc icon from Mac dock?

### ISSUE THREAD

**Issue by oleg-ilnytskyi** [BOINC/boinc#1424]

**Comment by CharlieFenton** [comment]
This is easy to do by adding the following to the info.plist file as explained in <http://apple.stackexchange.com/questions/68915/hide-a-running-app-from-dock>:

<key>LSUIElement</key>
<string>1</string>

Feel free to do this on your personal copy of BOINC Manager, but BOINC should _not_ be distributed with this change, as most people probably prefer to have it in their dock.

**Comment by oleg-ilnytskyi** [comment]
Thank you, it works. Would be great to have such option in preferences.

**Comment by ChristianBeer** [comment]
This should be in "Options" -> "Other Options..." on the Mac.

**Comment by CharlieFenton** [comment]
I believe it is not possible to prevent an application from appearing in the Dock as a user selectable runtime option.

**Comment by CharlieFenton** [comment]
@AenBleidd: Yes, I think it should be closed.

**Comment by trigger2k20** [comment]
As far I can see in Sonoma, the <key>LSUIElement</key> method is not possible anymore, therefore I would ask to go back to @ChristianBeer his suggestion "This should be in "Options" -> "Other Options..." on the Mac."
