### ISSUE TITLE
PC freezes 3 or 4 times a day, for 2 minutes, only when BOINC is launched

### ISSUE THREAD

**Issue by jeremythille** [BOINC/boinc#1428]
For weeks and weeks, I've been searching what damn application was making my PC freeze for 1 to 2 minutes, several times a day. Turns out when BOINC is not launched (not in the tray), these freezes never happen.

Symptoms : 
- Suddenly, all applications stop responding, at a random time of day
- Mouse cursor still responds perfectly, but that's the only thing that works
- Hard drive LED goes haywire
- After two minutes, the PC instantly recovers its speed and updates the display

System : 
- Windows 7 ultimate
- Core i7 4710MQ - 16 GB ram - SSD 512GB OCZ Octane - nVidia 880M

**Comment by AenBleidd** [comment]
This could be a problem with hard drive when some project writes a big amount of data (e.g. some project that uses Oracle Virtual Box from time to time saves snapshot (>200 MB).

**Comment by informatorius** [comment]
If Boinc project generats so much IO that even a SSD is stalled then maybe the project does something wrong. As experiment you could try to set IO priority for your projects to low using tool "Process Hacker" to see if this helps.

**Comment by ChristianBeer** [comment]
Could have been anything. If this still occurs please provide a log snippet around the time where this happens so we can see what BOINC does during the time.
