### ISSUE TITLE
Paused Boinc resumes unexpectedly

### ISSUE THREAD

**Issue by informatorius** [BOINC/boinc#1429]
I paused Boinc at 20:31:23 but at 21:31:23 boinc resumes unexpectedly.

04/11/2015 20:31:23 |  | Suspending computation - user request
04/11/2015 21:23:31 | Poem@Home | Sending scheduler request: To report completed tasks.
04/11/2015 21:23:31 | Poem@Home | Reporting 1 completed tasks
04/11/2015 21:23:31 | Poem@Home | Not requesting tasks: don't need (CPU: ; AMD/ATI GPU: job cache full)
04/11/2015 21:23:33 | Poem@Home | Scheduler request completed
04/11/2015 21:31:23 |  | Resuming computation

Boinc 7.6.9 x64 on Windows 7 with project poem@home

**Comment by davidpanderson** [comment]
"Snooze" lasts for 1 hour.

**Comment by informatorius** [comment]
How can I snooze Boinc until user resumes?

**Comment by ChristianBeer** [comment]
What you want is to "suspend" computation not "snooze". Snooze in general means stop that for 1 hour and resume automatically. Just like your alarm clock. To suspend until further notice from the user:
BOINC Manager Simple View - middle button at the bottom of the window says "Suspend" and "Resume" and means the whole computation
BOINC Manager Advanced View - Menu Activity -> Suspend - same place to resume

**Comment by informatorius** [comment]
So I wish a contextmenu entry similar to the snooze
1) Suspend
2) Suspend GPU

My usecase is e.g. watching a movie or playing a game longer than 1 hour.
My feature is I want to toggle suspend for GPU by tray icon context menu.
The described workaround with opening boinc manager, switching to Tasks tab, selecting all GPU projects and press suspend seams little inconvenient to me.

Can you reopen the issue?

**Comment by CharlieFenton** [comment]
On Nov 5, 2015, at 9:33 AM, informatorius <notifications@github.com> wrote:
> My usecase is e.g. watching a movie or playing a game longer than 1 hour.

You can accomplish what you want by setting BOINC computing preferences to "Suspend when computer is in use."

**Comment by davidpanderson** [comment]
In Advanced view, select "Suspend GPU" in the Activity menu.

**Comment by informatorius** [comment]
@CharlieFenton: But "suspend when computer is in use" will also suspend boinc when e.g. doing email?
@davidpanderson: It is the fastest way in Advanced View.
Still wish suspend in context menu

**Comment by informatorius** [comment]
I did "BOINC Manager Simple View" Suspend and still after 1 hour computation resumed unexpectedly.
