### ISSUE TITLE
Option to hide old application details.

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#1433]
On projects that switch through their applications a lot, the "Application details for host N" page is starting to become unclear. Is it possible that the old application details get an option to hide them, or at least fold them so they don't show and we can easier find the newer applications' details? 

e.g. my page for Seti shows:
SETI@home Enhanced 6.03 windows_intelx86
Number of tasks completed	1
Max tasks per day	101
Number of tasks today	0
Consecutive valid tasks	1
Average processing rate	16.18 GFLOPS
Average turnaround time	0.11 days

SETI@home v7 7.00 windows_intelx86
Number of tasks completed	126
Max tasks per day	238
Number of tasks today	0
Consecutive valid tasks	138
Average processing rate	24.37 GFLOPS
Average turnaround time	1.02 days

SETI@home Enhanced (anonymous platform, CPU)
Number of tasks completed	20651
Max tasks per day	196
Number of tasks today	0
Consecutive valid tasks	20
Average processing rate	42.44 GFLOPS
Average turnaround time	1.59 days

SETI@home Enhanced (anonymous platform, ATI GPU)
Number of tasks completed	1
Max tasks per day	297
Number of tasks today	0
Consecutive valid tasks	197
Average processing rate	246.64 GFLOPS
Average turnaround time	0.02 days

Astropulse v505 (anonymous platform, CPU)
Number of tasks completed	0
Max tasks per day	102
Number of tasks today	0
Consecutive valid tasks	2
Average turnaround time	0.00 days

Astropulse v505 (anonymous platform, ATI GPU)
Number of tasks completed	1
Max tasks per day	103
Number of tasks today	0
Consecutive valid tasks	3
Average processing rate	326.86 GFLOPS
Average turnaround time	0.81 days

SETI@home v7 (anonymous platform, CPU)
Number of tasks completed	2608
Max tasks per day	1764
Number of tasks today	0
Consecutive valid tasks	1731
Average processing rate	29.26 GFLOPS
Average turnaround time	1.48 days

SETI@home v7 (anonymous platform, ATI GPU)
Number of tasks completed	8059
Max tasks per day	1754
Number of tasks today	0
Consecutive valid tasks	5
Average processing rate	148.56 GFLOPS
Average turnaround time	5.99 days

AstroPulse v6 (anonymous platform, CPU)
Number of tasks completed	89
Max tasks per day	120
Number of tasks today	0
Consecutive valid tasks	22
Average processing rate	90.30 GFLOPS
Average turnaround time	1.72 days

AstroPulse v6 (anonymous platform, ATI GPU)
Number of tasks completed	56
Max tasks per day	176
Number of tasks today	0
Consecutive valid tasks	77
Average processing rate	760.07 GFLOPS
Average turnaround time	0.99 days

AstroPulse v7 (anonymous platform, ATI GPU)
Number of tasks completed	164
Max tasks per day	356
Number of tasks today	0
Consecutive valid tasks	301
Average processing rate	1,015.09 GFLOPS
Average turnaround time	3.98 days

**Comment by davidpanderson** [comment]
I removed the display of info for deprecated apps and app versions.

**Comment by RichardHaselgrove** [comment]
I would have preferred Jord's original request, but with the default setting reversed: initially show current applications only, but with an option to display previous application data as well.

**Comment by Ageless93** [comment]
I would have preferred my original request as well, because people are using the data of the older applications to compare if the newer applications are doing their work correctly. Removing the data is the easy way out, but not what I asked for.
