### ISSUE TITLE
Make BOINC website valid HTML

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#144]
**Reported by Simek on 5 Mar 37331721 12:26 UTC**
BOINC website have "''poor''" quality code. 

For example: (from index.php)[width=80% size=1>'''''[[BR]([BR]]
'''''<hr)]

In new web standards it should look like:[style="width: 80%; height: 1px" />'''''

The code need some improvements. If not XHTML improvements, it needs quotes (" ") in  tags values. 

Additionaly I suggest to use CSS files. Save them outside the php file and link to elements by "id" or "class" tags. 

I think that the XHTML standard of website is very important and it is the future of Internet.

'''P.S.'''
## I offer my help with working on this task. I made some XHTML 1.1 valid sites and I can spend some time (approximately 8h-10h per week) to make the code valid.

Edit by Nicolas: XHTML won't be used, we're staying with HTML4.01; see [comment:ticket:144:4 comment 4]([BR]]
'''''<hr).

Migrated-From: http://boinc.berkeley.edu/trac/ticket/144

**Comment by romw** [comment]
**Commented by Nicolas on 6 Dec 37332725 16:26 UTC**
XHTML? I'd be happy with valid HTML 4.01. Using the ''latest'' standards or not isn't really important, BOINC HTML pages aren't currently following '''ANY''' standard anyway! ,,(I do ''want'' them to be valid, I'm just saying they're not, under any standard),,

But definitely HTML 4.01 will do. Personally I don't see what XHTML can provide that HTML can't, other than being able to read it with a strict XML parser.

**Comment by romw** [comment]
**Commented by Simek on 11 Jan 37335121 08:26 UTC**
Nicolas I know that BOINC Website aren't currently following any standard and I think that this must be changed! HTML 4.01 isn't worse then XHTML, but making website validate take much time. When we choose HTML 4.01 after some period of time we shoud change it to new standard. Personally I think that making website now valid with new standard in future allow to save valuable time.

Sorry for my bad english ;)

P.S. I attached file to this ticked. It's a XHTML 1.1 test version of root/trunk/boinc/doc/download.php file. If some one can test this and tell me what is wrong, I will be grateful!

**Comment by romw** [comment]
**Commented by Rytis on 24 Feb 37335143 01:20 UTC**
We will not go for XHTML because it's unsupported by Internet Explorer. Yes, I know we can send XHTML as HTML, but that's just as bad as sending tag soup.

Since the web won't be able to correctly use XHTML for quite a long time (until 99% of people in the world use the browser that can handle it), the only logical thing is to use HTML 4.01.

Now, to making the pages valid. This is the hard part. I don't think that it's a high priority task. Even if you make the changes, I will have to review them before I check them in, and I don't really have time for that. However, I make (at least the parts of) the pages that I modify valid.

**Comment by romw** [comment]
**Commented by Nicolas on 14 Jul 37535580 08:53 UTC**
Title edited to reflect we won't use ''X''HTML

**Comment by romw** [comment]
**Commented by mtughan on 3 Apr 37758071 12:00 UTC**
Nicolas has offered his help, and so do I. He and I have worked on a site together, and we both are able to do valid (X)HTML.

**Comment by romw** [comment]
**Commented by Nicolas on 29 Oct 38261888 18:40 UTC**
Removing exclamation point from title; made it look more important than the rest on a ticket list...

**Comment by skybon** [comment]
Internet Explorer 9 (finally!) supports XHTML. Since it is the only supported version on oldest current Windows version (7) it would make sense to use it now.

**Comment by AenBleidd** [comment]
Is it still an issue?

**Comment by davidpanderson** [comment]
Not as far as I'm concerned.
