### ISSUE TITLE
Client stuck thinking VM extensions are disabled

### ISSUE THREAD

**Issue by marius311** [BOINC/boinc#1460]
In some cases, the client (tested on Win/7.6.22 and Linux/7.2.47) can get stuck thinking VM extensions are disabled. There may be more ways, but one way to reproduce is:
- Ensure VM extensions are off in your BIOS
- Attempt to request some jobs from a project which has VM jobs that need extensions (you'll rightly get none)
- Go turn VM extensions on in your BIOS
- Come back to BOINC and try to request jobs again, you'll still get none

This is actually pretty common. Since VM extensions are often off by default, people come in and try to run your jobs, they don't work, then they go and read the website and find out they need VM extensions, but they turn them on and it still doesn't work. 

The [workaround](http://www.cosmologyathome.org/faq.php#i-enabled-vt-xamd-v-but-jobs-say-scheduler-wait-please-upgrade-boinc) btw is the user has to edit the `client_config.xml` file and delete `<p_vm_extensions_disabled>` by hand.

**Comment by marius311** [comment]
Oops, my steps should have been,

* Ensure VM extensions are off in your BIOS
* Request some jobs from a project which has VM jobs, you'll get some but when you 
* Go turn VM extensions on in your BIOS
* Come back to BOINC and try to request jobs again, you'll no longer get any VM jobs

**Comment by marius311** [comment]
Since this was brought up again, let me clarify since I screwed up my explanation above. It actually goes like this,
* Ensure VM extensions are off in your BIOS
* Request jobs from a project which has VM jobs that need extensions
* You'll get one, it'll start running, vboxwrapper will detect you don't have extensions and fail. 
* BOINC now permanently marks your client as not having VM extensions, so you will no longer get any such jobs. 
* You can now re-enable extensions, but since you won't get any more VM jobs there's no way for the client to now that VM extensions are now enabled. 

Also a note about the workaround, its often been difficult for users to do this because in some cases that I haven't figured out exactly why, the BOINC client overwrites their changes to `client_config.xml`.

**Comment by JacobWKlein** [comment]
Does the <p_vm_extensions_disabled> settings get stored in "client_config.xml", or does it get stored in "client_state.xml" ?

**Comment by marius311** [comment]
Ah sorry, its `client_state.xml` yes.

**Comment by romw** [comment]
This issue will be resolved once https://github.com/BOINC/boinc/issues/1474 is implemented.

**Comment by Ageless93** [comment]
Seeing how this is a very active problem and we want our users (mostly novices in computer use) to have to manually edit files as little as possible (especially client_state.xml because of the dangers therein), may we have an option for this as soon as possible? 

I'm not sure what would be the easiest for this, a GUI option for something like "Reactivate VM", or an external app/script that does this (and other potential things, like fully uninstall BOINC).

**Comment by Rytiss** [comment]
I was just personally bit by this issue and spent a while digging up info on how to fix it.

I believe BOINC should reset host_info.p_vm_extensions_disabled flag on each BOINC client startup: that is really the only time when a user could fix the setting as it needs rebooting into BIOS. Sure, that means we would do a single run testing VM extensions on a reboot even if the user did not fix the issue, but considering vbox apps have gigantic amounts of failures anyway, I don't think it has a significant negative impact - but is way more user-friendly.
