### ISSUE TITLE
Configure process priority

### ISSUE THREAD

**Issue by MichaelFiedeldey** [BOINC/boinc#1463]
It would be nice to be be able to configure the process priority of the tasks, particularly the GPU tasks. I routinely have to increase the priority of the GPU tasks or the processor is not able to keep up with feeding the GPU and the GPU usage falls. After increasing the priority of the GPU tasks in the task manager (windows), the GPU usage goes back to near 100%.

**Comment by AenBleidd** [comment]
Hello Michael,

As I remember I made a pull request about similar feature and it should be
in release now: https://github.com/BOINC/boinc/pull/1394
Please try to add *process_priority_special* in *cc_config.xml *file.
Possible values are 0 (lowest priority, the default), 1 (below normal), 2
(normal), 3 (above normal), 4 (high) and 5 (real-time - not recommended).

Best regards,
Vitalii Koshura

2016-01-08 18:24 GMT+02:00 MichaelFiedeldey <notifications@github.com>:

**Comment by MichaelFiedeldey** [comment]
Thanks for pointing that out. Looks like there are both process_priority and process_priority_special options in there. That did exactly what I needed.
