### ISSUE TITLE
Host CPID Dupe [7.6.22]

### ISSUE THREAD

**Issue by Kati3e** [BOINC/boinc#1466]
So I run my own account manager, here: http://pool.gridcoin.co/ , and one of my user's just reported strange behavior relating to having 2 hosts. I looked into it, requesting the user to supply me with the acct_mrg_request.xml and acct_mrg_reply.xml files, just as I thought, they both have the same CPID, which is causing the issues. Both hosts have different host names, however they both are DESKTOP-[random string]. Both very different hardware setups. The same OS, Windows 10. I asked him if he had copied any files over to the other host and he said he hadn't. 

He reinstalled BOINC, yet still got the same CPID.

He tried adding a 3rd host, this one running Windows 7, it indeed got a different CPID.

Could this be an issue with Windows 10?

The documentation here: http://boinc.berkeley.edu/wiki/Cross-project_identification says..
"Each host generates an internal cross-project ID, which is the MD5 of the concatenation of its domain name, IP address, free disk space, and a timestamp."

So how is it possible for these 2 hosts to be given the same host CPID, when host names, free disk space and timestamps are different?

I checked with the project's server (Asteroids) to see what it was reporting in regards to these hosts.. one of the two hosts existed, but with an entirely different CPID. The other host was not present at all. (Tho I suppose this might be because the user stats haven't been updated yet for that project)

Also "Whenever a scheduler reply indicates that it has generated a new host record (e.g. because a bad RPC seqno suggests that this is a duplicate host) the client generates a new internal host CPID."

Does that mean it is possible for account mangers to request the client to get a new CPID? I did not see anything about that under https://boinc.berkeley.edu/trac/wiki/AccountManagement

Thank you.

**Comment by Kati3e** [comment]
Update: Moo Wrapper! is reporting the 2 hosts, each with different host IDs, yet the same CPID.

**Comment by jamofox** [comment]
im the one with this particular problem. i can provide more information if needed.

**Comment by davidpanderson** [comment]
I suspect the user copied client_state.xml (which contains the host CPID) from one computer to the other.  This doesn't work. You can clone BOINC by copying the data directory (including the account_* files) but don't copy client_state.xml.

I checked in a change to the server software that would deal with this particular case by comparing the CPU name, #CPUs, and OS vendor and name.  This is not a general fix since these can all be the same on different computers.

**Comment by Kati3e** [comment]
As per my OP, "I asked him if he had copied any files over to the other host and he said he hadn't.", also, "He reinstalled BOINC, yet still got the same CPID." (He had made sure to delete the data directory as well.)

I'd also like to point out that the projects themselves are still reporting the same CPID for both hosts to this day..:

<host>
    <id>415517</id>
    <create_time>1452611007</create_time>
    <rpc_seqno>146</rpc_seqno>
    <rpc_time>1452933893</rpc_time>
    <host_cpid>9a8dd1e762429da00002d93a8bb89721</host_cpid>
    <total_credit>20984</total_credit>
    <expavg_credit>1722.86260254612</expavg_credit>
    <expavg_time>1452933896.0751</expavg_time>
    <domain_name>DESKTOP-[CENSORED]</domain_name>
    <p_ncpus>2</p_ncpus>
    <p_vendor>GenuineIntel</p_vendor>
    <p_model>Intel(R) Core(TM)2 Duo CPU     T5750  @ 2.00GHz [Family 6 Model 15 Stepping 13]</p_model>
    <p_fpops>2141666666.66667</p_fpops>
    <p_iops>4810797625.82324</p_iops>
    <os_name>Microsoft Windows 10</os_name>
    <os_version>Core x64 Edition, (10.00.11082.00)</os_version>
    <m_nbytes>4293316608</m_nbytes>
    <d_free>70930923520</d_free>
    <d_total>119439097856</d_total>
    <venue/>
</host>
<host>
    <id>415560</id>
    <create_time>1452614607</create_time>
    <rpc_seqno>48</rpc_seqno>
    <rpc_time>1452932322</rpc_time>
    <host_cpid>9a8dd1e762429da00002d93a8bb89721</host_cpid>
    <total_credit>404442.8</total_credit>
    <expavg_credit>31388.0620409701</expavg_credit>
    <expavg_time>1452932385.60554</expavg_time>
    <domain_name>DESKTOP-[CENSORED]</domain_name>
    <p_ncpus>8</p_ncpus>
    <p_vendor>GenuineIntel</p_vendor>
    <p_model>Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz [Family 6 Model 60 Stepping 3]</p_model>
    <p_fpops>4581532967.28677</p_fpops>
    <p_iops>16190972794.5361</p_iops>
    <os_name>Microsoft Windows 10</os_name>
    <os_version>Professional x64 Edition, (10.00.11082.00)</os_version>
    <m_nbytes>8531210240</m_nbytes>
    <d_free>49505370112</d_free>
    <d_total>119007084544</d_total>
    <venue/>
</host>

And both of his clients are still reporting back the old CPIDs, "5513c5f6f4345a7d66c8200216508f8f", the acct_mgr_request.xml is not updating them at all...

**Comment by grctest** [comment]
Is this still an issue? How many users were affected by this @Kati3e ?

**Comment by piedar** [comment]
I had the same issue... One of my hosts got into a funky state with the project manager so I wanted to start fresh.  Turns out the `host_cpid` is [based on MAC address and working directory](https://github.com/BOINC/boinc/blob/73a7754e7fd1ae3b7bf337e8dd42a7a0b42cf3d2/client/hostinfo_network.cpp#L143) (which is usually a good thing because it keeps the cpid stable across installs).  Rather than mess around with MAC address, I did this

- stop boinc-client and delete its data/config
- start boinc-client to generate new data
- stop boinc-client
- edit `client_state.xml` and change one of the digits in the `host_cpid`
- start boinc-client
