### ISSUE TITLE
Boinc Manager Utility - Report Errors & Other

### ISSUE THREAD

**Issue by MrD2** [BOINC/boinc#1467]
Why not introduce a Button to send reports of errors to a project mail list?
This way it would be easier to report errors, or suspicions of errors in undergoing projects....

For example, right now i have a project running that should have been finished 2 days ago, but it is still in 3% and The current "Remaining Time to Completion" is 4696 hours <OUCHiii>, and it already processed for 145hours...

Now i don't know if its going as planed or if it broke, AND i'm too lazy to report to the projects by other means, so..... that's why..

XD

DGuerra

**Comment by ChristianBeer** [comment]
This sounds like a RNA World task. If it it is, than the long runtime is expected and you can read more about it on the project forums.

As for the button. I don't think that is a good idea. Every project has a different way to handle error reports plus the complication of stripping personal information from such error reports. If you are too lazy to report to the projects just abort problematic tasks.
