### ISSUE TITLE
Client softlocked after attempting to remove ATLAS@home

### ISSUE THREAD

**Issue by ElliottBelardo** [BOINC/boinc#1468]

**Comment by ChristianBeer** [comment]
Can you please add a description of the problem?

**Comment by ChristianBeer** [comment]
For example: What do you mean by "softlock"? How does it look like? Is it reproducible? What BOINC version do you have installed? What VirtualBox version do you have installed? How do you want to remove ATLAS? Via Manager or boinccmd?

**Comment by ElliottBelardo** [comment]
1. By softlock, I mean an unclosable window appears on top of the manager trying to remove ATLAS@home, but it takes forever to do so, making the BOINC manager unusable.
2. Look above.
3. Don't know.
4. Haven't checked.
5. Version 5.0.12 (this might be the reason why this is happening)
6. Using the manager.
