### ISSUE TITLE
AMs don't work with Android client

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1472]
(reported by a user)
Hi!  I've been using BOINC for a long time and have been using the Android app since it came out.  From the very beginning, there was an issue where if I attached an account manager such as BAM, the BOINC android client would fail to work.  Specifically, it would go blank and not download any tasks.  Ever.  If I attempted to manually attach a project at that point, it would crash the app.

The only solution has been to clear the app data and start fresh by manually attaching projects and not using the account manager.  Do you have any suggestions?  Thanks!

**Comment by brevilo** [comment]
@davidpanderson, what's your take on this? Is this a defect or an enhancement request?

**Comment by AenBleidd** [comment]
Verified with latest master code bf5f2fce31a6627fb31ba092bca5598021d1c008
Everything works fine.
Should be reverified after release.

**Comment by adamradocz** [comment]
Can we close this issue?
