### ISSUE TITLE
Insecure version check

### ISSUE THREAD

**Issue by funkydude** [BOINC/boinc#1475]
`client_version_check_url` is set to HTTP by default, this should be changed to HTTPS

https://github.com/BOINC/boinc/blob/b69b868e76e133d051be7e44f9352fbf6ccbf99d/lib/cc_config.cpp#L210

In addition, `client_download_url` should probably also be changed to HTTPS.

-------------------------------

This can also be fixed in the WCG build which fully supports HTTPS
https://github.com/BOINC/boinc/blob/edfa2bf428934ccfa17175465c5768f35b726c52/win_build/installerv2/redist/WCG/cc_config.xml#L6

**Comment by funkydude** [comment]
Hijacking this to also state that `network_test_url` should also be changed to HTTPS: https://github.com/BOINC/boinc/blob/b69b868e76e133d051be7e44f9352fbf6ccbf99d/lib/cc_config.cpp#L240
https://github.com/BOINC/boinc/blob/edfa2bf428934ccfa17175465c5768f35b726c52/win_build/installerv2/redist/WCG/cc_config.xml#L7

**Comment by romw** [comment]
Just switching to HTTPS will not mean that the check is secure.  A certificate thumbprint check would also have to be performed.

Once the certificate is updated (old one expires) then of course everything breaks until a new client version is deployed with the new thumbprint value.

It would probably be better to have a signed manifest file which could be signed with a custom x.509 certificate that has a 30-year lifespan, or something like that.  The public key could be embedded within the client and used to verify the manifest and executable signatures.

**Comment by ChristianBeer** [comment]
But switching to HTTPS would be a first step to prevent MITM Attacks. The Client checks the hostname in the certificate to make sure it communicates with the correct server.

A signed manifest would additionally prevent a malicious tampering on the serverside or the case that someone gets a certificate for boinc.berkeley.edu who is not authorized to get one.

**Comment by BryanQuigley** [comment]
Agreed, let's not block on perfect security, when currently it's all in easily modifiable plaintext.

**Comment by davidpanderson** [comment]
I changed those URLs to HTTPS;
protects against MIML attack but not BOINC server hack.

**Comment by davidpanderson** [comment]
Also changed WCG URLs, and the network test URL.
