### ISSUE TITLE
can't build boincmgr on Linux (Ubuntu 14.04 x64)

### ISSUE THREAD

**Issue by thirschbuechler** [BOINC/boinc#1479]
Hi,
I want to modify the interface of `boincmgr` (and hopefully make a pull req), but it seems i've only got the daemon (boinc) to build and install itself.

Been trying to build it on two different machines (Pc, Laptop): No luck.
Using i.e. `sudo make install |& tee ~/logmakeinstall.txt` i've tried to provide the cmdline output.

[logautosetup.txt](https://github.com/BOINC/boinc/files/107214/logautosetup.txt)
[logconfigure.txt](https://github.com/BOINC/boinc/files/107215/logconfigure.txt)
[logmake.txt](https://github.com/BOINC/boinc/files/107216/logmake.txt)
[logmakeinstall.txt](https://github.com/BOINC/boinc/files/107213/logmakeinstall.txt)

Then, i realized the culprit may be somewhere within `./configure`  (it stated it wouldn't build `boincmgr`without it), but even installing `libwxgtk2.8-dev libwxgtk2.8-dbg` didn't help.

**Comment by BryanQuigley** [comment]
If you're just going to make changes to the GUI, why not just run it from your build directory? (no make install needed)

.....git/boinc$ ./clientgui/boincmgr

**Comment by thirschbuechler** [comment]
My problem is that only boinc, boinc_client and boinccmd get compiled, not boincmgr!

Yes, `make install` may be unnecessary

**Comment by ChristianBeer** [comment]
From logconfigure.txt it seems that the Manager is not built but then you try to build all the pieces when you only want the Manager. You should run ```./configure --disable-server --disable-client``` and then ```make```. This should build everything in ./clientgui/

Before you do that however, you should install the correct wxWidgets version (3.0 for >7.4.0). There is also a list of Packages for Debian/Ubuntu in [SoftwarePrereqsUnix](http://boinc.berkeley.edu/trac/wiki/SoftwarePrereqsUnix)

**Comment by thirschbuechler** [comment]
Thanks, i missed that (got sidetracked in old wiki-pages / didn't look hard enough). Problem solved
