### ISSUE TITLE
Screen resolution

### ISSUE THREAD

**Issue by wirzroland** [BOINC/boinc#1486]
Boinc change the screen resolution after a certain time on 640px automatically.
A reset to the normal resolution is necessary.

**Comment by ChristianBeer** [comment]
Can you please provide which BOINC version and what operating system you have this issue with? To me it sounds like an issue with a Screensaver that kicks in after some time. So this can also be a graphics app related issue so It would be nice to know which projects you have attached on this host.

**Comment by wirzroland** [comment]
Windows 7 Prof.

 

No Screensaver is actif

 

Von: Christian Beer [mailto:notifications@github.com] 
Gesendet: Dienstag, 2. Februar 2016 15:47
An: BOINC/boinc
Cc: wirzroland
Betreff: Re: [boinc] Screen resolution (#1486)

 

Can you please provide which BOINC version and what operating system you have this issue with? To me it sounds like an issue with a Screensaver that kicks in after some time. So this can also be a graphics app related issue so It would be nice to know which projects you have attached on this host.

**Comment by ChristianBeer** [comment]
Please reopen with new information if this still occurs.
