### ISSUE TITLE
Oracle Virtual Machine problem with vLHC@home on Linux Mint 17.3 

### ISSUE THREAD

**Issue by ilkeryus** [BOINC/boinc#1488]
Hi,
I use VM 5.0.14 (the last version) on Linux Mint 17.3. VM runs without any problem with other virtual systems that I installed.  

  I installed BOINC Manager 7.2.42 (x86), the last recommended version for Linux. And added vLHC@Home. It run correctly,  downdloaded its own VM from server and its works. There was no problem. 

After I restarted my computer, BOINC displayed that message at works tab for vLHC: Please update/recompile VirtualBox Kernel drivers. 

I installed again VM 5.0.14 for many times.  vLHC runs correctly again for new works only. Unfinished works gone to garbage box, vLHC denied to complete them, what a big lost for my little netbook.  After a restart the same problem again, and agan, again. 

Why couldn't vLHC recognize VM version? Is there any thing I can do?
Thanks..

Aydin Alp, 
Turkey

**Comment by ChristianBeer** [comment]
Please try again with current 7.6.33 from you distribution repository.
