### ISSUE TITLE
Clients upload result files more than once

### ISSUE THREAD

**Issue by ChristianBeer** [BOINC/boinc#1489]
Some Clients are uploading result files more than once. Even after they reported the result as complete and it was validated. Those uploads I will call reuploads. This leads to data corruption on the project server as the BOINC server should make sure that result files that are validated should not change afterwards.

The initial fix to this was to make a result file readonly as soon as it is uploaded completely (be50103751667952b11793ffbadc354232e0b01d). This has triggered some other issues and there already was a discussion about the symptoms at ce00365f866e97ae48b1f41ba9608dff4c459ffe 

I'm currently investigating this and I'm in the process of gathering more data on those reuploads. The goal is to find the root cause for those reuploads especially those where in the reupload the Client reports a different filesize than in the first upload.

**Comment by funkydude** [comment]
If you're the same Christian as the one from Einstein@Home then this may be related. Just today I had issues with 1 specific task uploading, it just kept failing and backing off. During this process, other tasks were being downloaded, completed, and uploaded just fine.

I decided to go to the transfers section of BOINC and abort the transfers (there were 2 transfers listed). After doing so the task was marked "ready to report" as if it had already uploaded. Simply forcing the report (by updating the project in BOINC) removed the task as successful.

**Comment by ChristianBeer** [comment]
I modified the file upload handler to output a better parseable line with the information available. Here is the preliminary report over roughly 30h at EaH:
There where 1,069,972 file uploads of which:

- 90 had a md5 mismatch (reported by client vs. computed on server)
- 1,136 where reuploads (a read-only file was present on the server)
of those reuploads:
  - 40 changed in size and content
  - 4 did not change in size but in content

Looking at the md5 mismatches I tried to blame a specific client version or platform, but:
```
i686-pc-linux-gnu 5.8.16
powerpc-apple-darwin 5.8.15
windows_intelx86 5.8.15
windows_intelx86 5.8.16
windows_x86_64 7.0.28
windows_x86_64 7.4.42
windows_x86_64 7.6.22
windows_x86_64 7.6.9
x86_64-pc-linux-gnu 7.2.33
x86_64-pc-linux-gnu 7.2.42
x86_64-pc-linux-gnu 7.4.22
x86_64-pc-linux-gnu 7.4.23
x86_64-pc-linux-gnu 7.4.42
x86_64-pc-linux-gnu 7.6.6
```

The result files look fine and validate against non mismatches. But this makes it unclear if the md5 value send by the client can be trusted. I did not investigate further why md5 sums mismatch.

Looking at the bulk of the reuploads where the file didn't change indicates a communication problem with the Client. It does not receive the success message and tries to reupload again. The file upload handler should ignore the file (if md5 matches and can be trusted) and send a success to the Client. I didn't correlate the time the Client reported a result with the time of the upload yet. It would be interesting to find a Client that uploads a file after it was reported.

All 44 reuploads that changed content (and are not caused by resends) are originating from one user (in that timeframe), who as it seems, is copying the Client data directory from one computer to another and uploading result files for the same task from two different hosts. I can see that because the hostid is part of the result file and I have access to both versions of result files.

The objective of the file_upload_handler should be to prohibit result file tampering either intentional or unintentional. Since it is a feature of BOINC that a file is immutable once it is "in the system", the file_upload_handler should adhere to that too. For that it should report a permanent error to the Client in cases where there is a mismatch between the server file and the file send by the client.

Open questions now are:
What to do with the md5 mismatches?
How to react on a reupload that differs in content?

Some of the files that changed in size or content (not counted above) are due to the fact that we recently resend (unintentionally) some older work using the same workunitnames. This should in general not happen but is possible. If a Client uploads a result file long after the deadline when the result is already purged from the DB there is only an error in scheduler.log and the files have to wait for the antique_file_deleter to be run. This takes some time because the file is "new". When in the meantime the same workunitname is reused again and results are comming in there is a conflict between the read-only file on the server from the "old" Client and the file uploaded by the "new" Client. The file_upload_handler has no way to decide which file is "better" and decides to keep the "old" one.
I think that some of the problems with intentional or unintentional resends are solved when adding a random extension to the result file (as in master since Nov 20) which would result in new files created rather than existing files overwritten.

**Comment by ChristianBeer** [comment]
We ave a fixed file upload handler running on Einstein@Home running for some time. I'm going to push that upstream when I have time.

**Comment by lfield** [comment]
@ChristianBeer Did this fix ever make it upstream?

**Comment by AenBleidd** [comment]
Looks like this has been already fixed. At least, we have never received any additional information.
