### ISSUE TITLE
Team founder: Email privacy concern

### ISSUE THREAD

**Issue by grctest** [BOINC/boinc#1491]
Hey,

Over at the Gridcoin forums, we've been discussing the [team 'gridcoin' membership requirement](https://cryptocointalk.com/topic/44260-discussion-mandatory-team-gridcoin-membership-requirement/page-1), and one hot topic has been the centralized admin powers that each project's 'team founder' user has.

One specific issue is email privacy within the team; it's currently not possible to hide your email address from the 'team founder' user, but you can set it so that mass team emails are not sent to you. Cryptocurrency users tend to be very sensitive about privacy, and the exposure of their email addresses to individuals could be interpreted as a security/OPSEC threat.

I've identified the exact location in the server side code where emails are listed for the team founder:
https://github.com/BOINC/boinc/blob/edfa2bf428934ccfa17175465c5768f35b726c52/html/user/team_email_list.php#L49

How possible would it be to add to the "$show_email = ($user && is_team_founder($user, $team));" line, a check for an individual user's 'email privacy' setting? And if it's checked (potentially a new privacy setting, or the existing email privacy settings), return 'N/A' in place of an email?

I acknowledge that it may be difficult to get any/all project servers to update to include this change, but this issue could potentially hold Gridcoin back from opening up to all teams rather than just team 'Gridcoin' in the future.

Best regards,
GRCTEST.

**Comment by Kati3e** [comment]
I think this is a great idea. I see no reason why emails should be used as an identifying mark of a BOINC account. We have usernames, why do emails need to be public if the users don't want it to be?

The only reason I could really think of why a team founder would need/want emails of their members would be to.. send them emails. But what if users don't want emails from the team founders? An option to hide the email from team founders would quickly solve this.

BOINC should be a strong supporter of user privacy settings in all regards.

**Comment by SETIguy** [comment]
I was entirely unaware of the existence of this "feature".  BOINC should
provide the ability to provide a team wide email, but should not reveal
email addresses, even to team founders.

**Comment by davidpanderson** [comment]
In Project Preferences, there's a "no email" checkbox.
If this is checked, you won't get emails from the project,
and your email addr won't be shown to your team's founder.
The "join team" page says this.

**Comment by grctest** [comment]
Thanks for replying david.

Quickly checking yoyo@home I can only find the following email setting within the yoyo@home preferences page: https://i.imgur.com/VEvKA6W.jpg

I've set it to no email, but I'm still able to see my email address in the team_email_list.php page. Does it take a while for the change to propagate? It's also worth noting that no users email addresses in team gridcoin for yoyo@home (approx 405 users).

Are there other settings that I can investigate? If it's just a matter of setting the right profile settings, we can create a PSA for our community to increase privacy.

Cheers :)

**Comment by davidpanderson** [comment]
It's the checkbox in project prefs labeled:
"Is it OK for (project name) and your team (if any) to email you?"

I've verified that in the current BOINC code this works; if you uncheck this box, your email isn't shown.  It's likely that yoyo@home is using old server code in which this mechanism doesn't exist or doesn't work.  The files they need to update (if they don't want to update all the PHP code) are
inc/xml.inc, inc/team.inc, and user/team_email_list.php

**Comment by grctest** [comment]
It would be cool if it was two seperate checkboxes & "your team (if any) to email you" was unchecked by default.

That said, I will be creating an PSA (distributed via reddit/irc/forums) for our users to uncheck this setting to increase email privacy & will work with the other team founders to identify which projects are up to date - we'll attempt to reach out to any projects that have out-dated php pages.

Thanks for your time, David.

**Comment by grctest** [comment]
*BUMP*

As a team founder I've been tasked with contacting my entire team, but It's more difficult from a legal standing than initially perceived. Somewhat related to this topic, since many users may not know they're sharing their email with me (potentially resulting in emails being branded spam): https://groups.google.com/forum/#!topic/boinc-team-founders/sziGysV5Thk

Cheers

**Comment by davidpanderson** [comment]
I committed changes so that email addresses are not shown to team founders.

To allow team founders/admins to communicate with the team, I added a feature that lets them send a private message to the team.
