### ISSUE TITLE
Funding - Would the BOINC repo be open to a 'Tip for Commit' donation system?

### ISSUE THREAD

**Issue by grctest** [BOINC/boinc#1493]
Hey,

With the news last year that funding for BOINC Was ending, would BOINC devs/community be open to a 'Tip4Commit' style donation mechanism? I.e. Users donate x quantity of a cryptocurrency, and every dev commit unlocks a small portion of the donations.

Source project: https://tip4commit.com/

We could potentially port the above linked project to use Gridcoin & throw some foundation coins at the BOINC github project. But it would require prior consent of the BOINC devs before being worth implementing.

So what's the consensus on the idea?

Thanks for your time,
GRCTEST.

**Comment by PiiTan** [comment]
I definitely think this is a good idea. I have suggested about implementing this sometime last year. I'm guessing we need people to maintain the site?

**Comment by grctest** [comment]
We could possible get boinc added to tip4commit, and just exchange GRC -> BTC for donating to the repo. Wouldn't require us to maintain the site.

**Comment by grctest** [comment]
Rather than porting tip4commit, we could port peer4commit for better initial compatibility (gridcoin is closer to peercoin than bitcoin): https://github.com/grctest/peer4commit

Still requires the approval of the github repo admins - I should have proposed this idea to the BOINC community governance rather than creating an issue on the BOINC repo..

**Comment by ChristianBeer** [comment]
You should explain (to the BOINC Management Committee) how this works. Like who decides when a feature is implemented and which commits receive the funds raised. Does one need to register somewhere to get the funds? What if multiple persons are working on a feature?

**Comment by ChristianBeer** [comment]
Closing for now, please feel free to reopen if there is a more concrete proposal.
