### ISSUE TITLE
BOINC doesn't work on latest Fire OS

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1495]
(user email)
My kindle fire hdx tablet computer has been running boinc with no problem, but today it was upgraded to the latest version of fire OS. Now boinc no longer works, and it is not available in the amazon app store. Since I can only download apps from the amazon app store, I cannot run boinc.

**Comment by AenBleidd** [comment]
@davidpanderson, did you have permissions to update BOINC app [here](https://www.amazon.com/Space-Sciences-Laboratory-U-C-Berkeley/dp/B00DCCGLAG/ref=cm_cr_arp_d_product_top?ie=UTF8) ?
Looks like it was not updated as it was done for Google Play.
Maybe updating app on Amazon store will handle this issue (possibly no but anyway it requires update when next release will be ready)

**Comment by davidpanderson** [comment]
I am able to update the Amazon store version, but haven't done so recently.

**Comment by AenBleidd** [comment]
Should be re-verified after new release update on Amazon store

**Comment by AenBleidd** [comment]
Not an issue anymore on 7.16.16
