### ISSUE TITLE
Suggestion: improving forum posting and quoting 

### ISSUE THREAD

**Issue by AgentB1** [BOINC/boinc#1496]
When posting to the forums - currently there are three options (four if you include edit) when contributing to a thread.

A Reply does not read easy, it is not clear who you are replying to.

Quotes are often lazy used, and this is irksome - especially when reading on small displays.

Is it possible to
*1 add

>   [quote]In reply to: Agentb's message of 29 Feb 16 12:34:56UTC [/quote]

at the start of a reply or quoted message - The poster can of course edit this.

*2 replace the label on the current Quote button with "QuoteAll".

and

*3 An new "QuoteLast" button between Reply and QuoteAll buttons. 
This is like QuoteAll but instead only quotes only the remainder from last [/quote] found in the message being quoted.  

*4 A link to "Netiquette" somewhere obvious - possibly below Rules - where each forum can give their guidelines to good and bad posting.

**Comment by grctest** [comment]
Spoiler tags (to reduce walls of text) would be a pretty decent addition to the forums too.
