### ISSUE TITLE
squashing some vboxwrapper bugs

### ISSUE THREAD

**Issue by marius311** [BOINC/boinc#1501]
With a sample of about a quarter million VM jobs (vboxwrapper 26182), we're getting about 93% success rate. About 3% of those error are Docker related, below is my summary of the remaining types of errors I see. I've just gone through and found the lines in the stderr that seem indicative of the errors, its possible I've missed things / picked the wrong lines. 

![image](https://cloud.githubusercontent.com/assets/1510968/13446697/e4dc51c4-e015-11e5-8bc2-305b3e440804.png)

The biggest problem, labeled "lpt1" seems like an easy fix. The error output more exactly is this,

```
VM Trace Log:
...
[--vcpheight <height>]
[--vcprate <rate>]
[--vcpfps <fps>]
[--defaultfrontend default|<name>]
VBoxManage: error: Unknown option: --lpt1
```

Looks like some peoples' version of VBoxManage doesn't have this lpt1 command line option. Note I see a similar error for the `--draganddrop` option. Not sure what the function of these options are, maybe they can just be removed?

Beyond that, there's all the others little bugs which might be squashed. I'm less sure what's going on there. Let me know if you like to see more detailed examples of stderr's outs from those jobs, I'm happy to report back!

**Comment by romw** [comment]
Do you happen to have the version numbers handy for the lpt1 and invalid virtual CPU count issues?

**Comment by marius311** [comment]
Breakdown for the two:
![image](https://cloud.githubusercontent.com/assets/1510968/13457686/b322ed6a-e069-11e5-86dc-75cd4820fc66.png)

![image](https://cloud.githubusercontent.com/assets/1510968/13457672/9df099ba-e069-11e5-8714-2cb6e762591f.png)

**Comment by marius311** [comment]
@romw, re: the virtual CPU thing, I think its possible VBox (all versions) has a hard max of 32 CPUs? I can't find anything official written, but anecdotally its true. That is, no one one at C@H has succesfully run a job with >32 CPUs, and everyone that's tried more's error messages look like this: 
```
VBoxManage: error: Invalid virtual CPU count: 64 (must be in range [1, 32])
```
Do you happen to know anything this? I can fix it for us with `<max_threads>` in `plan_class.xml` I think, but perhaps this is affecting other projects and a `vboxwrapper`-wide fix would be in order?

**Comment by marius311** [comment]
Ok, according to https://www.virtualbox.org/manual/ch03.html#settings-processor there is indeed a max of 32.

**Comment by romw** [comment]
Alright, I'll tweak the wrapper to cap the CPU count at 32 and write a warning to stderr.  You should also cap it in plan_class.xml to avoid having the BOINC client reserve more than 32 processors for a given job.

**Comment by romw** [comment]
Both.  Vboxwrapper needs to be changed to handle older server versions.  It is better to allow the client to under provision the system and use a max of 32 processors than to abort the job.

**Comment by marius311** [comment]
Good point, makes sense to me.

**Comment by marius311** [comment]
Sorry, one more thing related to CPU counts. From my link above you'll see,

> You should not, however, configure virtual machines to use more CPU cores than you have available physically (real cores, no hyperthreads).

Does vboxwrapper/BOINC honor this? 

I just made the connection, but for at least [one user](http://www.cosmologyathome.org/forum_thread.php?id=7385) who I've been helping debug this seems to not be the case, i.e. his card is [this](http://ark.intel.com/products/81713/Intel-Xeon-Processor-E5-2690-v3-30M-Cache-2_60-GHz) (12 cores, 24 hyperthreads) but his jobs get 24 VBox CPUs. He ends up having the issue that the CPUs seem to not be fully utilized, and perhaps this is related.

**Comment by ChristianBeer** [comment]
AFAIK BOINC can not detect hyperthreading so it doesn't know that those 24 cpus it sees are hyperthreaded and vboxwrapper should only use 12. To solve this we would have to find a way for the Client to detect hyperthreading and report a second cpu second for this that can be used serverside or locally.

**Comment by marius311** [comment]
The number of CPUs assigned to a job gets picked server-side right, so it'd *have* to percolate up somehow? Or do I not understand the way it works?

**Comment by ChristianBeer** [comment]
On 12.04.2016 18:59, Marius Millea wrote:
>
> The number of CPUs assigned to a job gets picked server-side right, so
> it'd /have/ to percolate up somehow? Or do I not understand the way it
> works?
>

No the assignment happens on the client but if we have this information
(Hyperthreading on or not) the server scheduler should also know about
this to make better decisions.

**Comment by romw** [comment]
The number of CPUs assigned to a job is determined by the server.

However, the client does not report the difference between hyperthreaded cores vs. full cores.

----- Rom

**Comment by davidpanderson** [comment]
The BOINC client uses GetActiveProcessorCount() to get the # of CPUs:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd405485%28v=vs.85%29.aspx
This returns the # of "logical processors" (i.e. a HT CPU counts as 2).
I can't find an API for getting the # of physical processors.
-- David

**Comment by romw** [comment]
I found this:
http://www.lpjjl.net/pgm/fichiers/intelcountingprocessors.htm

**Comment by davidpanderson** [comment]
A work-around would be for VM-based apps to assume that Intel processors are hyperthreaded, and pass N/2 as the ncpus param to virtualbox.

**Comment by romw** [comment]
IIRC, it is only the high-end processors that have hyperthreading.

**Comment by davidpanderson** [comment]
My impression is that the majority, maybe 90%, are hyperthreaded:
http://science.opposingviews.com/intel-processors-hyper-threading-18298.html

**Comment by marius311** [comment]
I don't really know what boost is, but this looks promising? http://www.boost.org/doc/libs/1_56_0/doc/html/thread/thread_management.html#thread.thread_management.thread.physical_concurrency

**Comment by ChristianBeer** [comment]
Boost is a big pile of libraries that we don't want to use if we only need one function.
I found this SO question: [Programatically detect number of physical processors/cores or if hyper-threading is active on Windows, Mac and Linux](http://stackoverflow.com/questions/2901694/programatically-detect-number-of-physical-processors-cores-or-if-hyper-threading) especially this answer: http://stackoverflow.com/a/29761237 seems to show a cross platform solution.

What about a small test program that we can send to some powerusers to test on different CPU models and operating systems?

**Comment by marius311** [comment]
I'm happy distributing some test program to some of our users. 

I'll also mentioned there's probably some other subtleties, because I'm getting reports that in some cases it _does_ seem to be OK running Virtualbox with "num_logical_cores" CPUs instead of "num_physical_cores". I'm digging into it, but in any case, having the ability to detect the number of physical ones would certainly be needed.

**Comment by Ageless93** [comment]
Are these still an issue?

**Comment by marius311** [comment]
Some yes, others no. I'll close this for now, and maybe at some point individual issues can be opened for specific errors.
