### ISSUE TITLE
Ransom Malware Attack

### ISSUE THREAD

**Issue by farmer254** [BOINC/boinc#1506]
I downloaded the BOINC software and connected to SETI@home. Next day we found a ransom malware attacking one of our work stations and the server. Has anyone else recently had this experience?

**Comment by boonware** [comment]
There have been recent attacks against Linux Mint and the Transmission BitTorrent client whereby the official downloads were maliciously replaced with infected versions. I suggest you immediately (1) disable network access to the infected computer and others with potential infection, and (2) verify the checksum of the downloaded application.

**Comment by romw** [comment]
Where did you download BOINC from?  What OS are you running?

**Comment by KLiKzg** [comment]
Well, for sure it's not SETi@home app...been running it for years! ;)

Check something else...

**Comment by boonware** [comment]
Just to be clear, I was not suggesting that BOINC is infected. I was just offering some precautions in the event that it is.

**Comment by KLiKzg** [comment]
Only way that antivirus sees apps inside BOINC as a virus is a BitCoin apps...so not possible!

Especially not a SETi@home.

**Comment by boonware** [comment]
Wouldn't it be possible for an attacker to recompile the source with malicious additions, and replace the official downloads with this infected version? That is precisely what happened over at Linux Mint and Transmission, unfortunately :/

**Comment by ChristianBeer** [comment]
@farmer254 Can you please elaborate on what you mean with "Ransomware attacking our server and workstations"? It could just be an unlucky correlation. Attackers are scanning random IP sections for weak points all the time. What we also need to not speculate is where you downloaded the BOINC Client and what operating system you use. Was BOINC installed on all attacked machines?

**Comment by ChristianBeer** [comment]
There was no further explanation by the OP and no one else mentioned anything like this. Closing.
