### ISSUE TITLE
MGR: Ensure start page is in page stack when launching in auto-attach mode

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1510]
ISSUE:
Selecting cancel and selecting 'NO' causes the back button to become enabled when it shouldn't be.

STEPS TO REPRODUCE:
From initial volunteer report:
"I want to add a new project or use an account manager. But then I decide to close the new project window again and boinc asks me if I really would like to cancel. Well, boinc convinced me and I say, NO. I´d like to stay here."

**Comment by AenBleidd** [comment]
Fixed in Pull Request #1656
