### ISSUE TITLE
BOINC Manager tries to detach Einstein@home against my command

### ISSUE THREAD

**Issue by Ruuktak** [BOINC/boinc#1516]
With every reboot BOINC Manager updates the settings of E@h to a kind of "allow no new wu, detach after finishing all work" (in german (origin): "Keine neuen Aufgaben zulassen, Entfernen, sobald alle Aufgaben erledigt sind"). This was not my command or wish!

What can I do to avoid that unwanted detach? Why is BOINC Mgr that strange?

Thx for help, 

Sebastian

**Comment by ChristianBeer** [comment]
This message originates from BAM not the Client. I would like to refer you to the Thread at Einstein@home: https://einstein.phys.uwm.edu/forum_thread.php?id=12011

Currently I consider it normal behavior that an Account Manager detaches and reattaches when the master URL of a project changes. The current problem is that the master urls don't match between BAM and E@H (the first uses https, the project http) which leads to another message after the reattach that informs the user he is using the wrong master URL.
