### ISSUE TITLE
disconnected client

### ISSUE THREAD

**Issue by noobusinglinux** [BOINC/boinc#1518]
i came back from work today to see client was disconnected from the BOINC manager when i try to connect to the localhost hostname the window appears "communicating with..." then the client is disconnected again. i am willing to post again i have modified the event log to record more data but i cant find what file to upload please email me some instruction as to how to proceed
thankyou

**Comment by ChristianBeer** [comment]
It would help if you could say which version of BOINC, what Operating System and how you installed the BOINC Client (via download of via package manager).

On Linux the log files are usually in `/var/lib/boinc-client/` and are called stdoutdae.txt and stderrdae.txt

**Comment by noobusinglinux** [comment]
ok so its happening on windows vista and windows7 installations and it manager 7.6.22x86 wxwidgets version 3.0.1 both have the latest version of boinc as far as i know just a downloaded version

[stderrgui.txt](https://github.com/BOINC/boinc/files/201757/stderrgui.txt)

[stderrscrgfx.txt](https://github.com/BOINC/boinc/files/201758/stderrscrgfx.txt)

**Comment by ChristianBeer** [comment]
Since there is no other report and the stderrgui.txt is without context I would advise for a complete restart of the host and check if any updates where installed or need to be installed.
