### ISSUE TITLE
run_in_ops tasks failing if "./" included in cmd

### ISSUE THREAD

**Issue by marius311** [BOINC/boinc#1521]
I'm seeing that if I specify in `config.xml` e.g., 
```
<cmd>run_in_ops ./update_uotd.php</cmd>
```
I get an error message `/usr/bin/env: php: No such file or directory` on the log, but if instead I do
```
<cmd>run_in_ops update_uotd.php</cmd>
```
it works. This only applies to jobs run by cronjob, i.e. I can go in and run `./run_in_ops ./update_uotd.php` by hand just fine. Note the former is how the default `config.xml` is created. 

I can reproduce this on boinc-server-docker [56212c6](https://github.com/marius311/boinc-server-docker/tree/56212c6). Does anyone else see this?

**Comment by ChristianBeer** [comment]
This can be a bash/dash/sh/... specific problem. Maybe your cronjob user has a different shell configured. The `run_in_ops` script is very simple:
```
#! /bin/sh
cd ../html/ops; ./${*}
```

I don't check this specific case in the ServerVM but we use bash there and Ubuntu uses dash out-of-the box which gave problems in the past.

**Comment by marius311** [comment]
Thanks, Christian. I haven't totally figured it out yet, but I'm pretty sure it actually has to do with the environment in which I'm running `cron` being weird (which propagates to the tasks themselves). Anyway, not related to BOINC, so closing.

**Comment by ChristianBeer** [comment]
> I haven't totally figured it out yet, but I'm pretty sure it actually has to do with the environment in which I'm running cron being weird (which propagates to the tasks themselves).

Yes, the start script forks itself when starting tasks so it is important which user (including environment) runs the cronjob. You might also want to check the user/group settings for your project directory. In a multiuser environment you have to make sure that only the ´boinc´ user is able to use the start/stop scripts to enable and disable the project. There is a special config option for that.
