### ISSUE TITLE
Are these log errors normal for BOINC Android?

### ISSUE THREAD

**Issue by jdheeter** [BOINC/boinc#1523]
I just installed the BOINC android app in a clean x86 emulator and I see so much log spam, even when the app is not connected or doing anything, it keeps pushing out these messages like:
`04-08 17:42:18.669  3846  3846 W boinc   : type=1400 audit(0.0:6863): avc: denied { search } for name="397" dev="proc" ino=5027 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0 
`
Could someone explain to me what these messages mean? Is something wrong?

here is the full log from install to launch of the app:
https://gist.github.com/jdheeter/47e241bf936068cc2cde67612addc7bb

**Comment by ChristianBeer** [comment]
I guess those are expected. BOINC is enumerating processes and doesn't have enough permissions for those.

**Comment by AenBleidd** [comment]
It is designed behavior to scan running processes. These errors should not happen on real device.
As soon as this is happen on emulator I'm closing this for now.
If it's still an issue please feel free to reopen it.
