### ISSUE TITLE
Strange statistics graphs when client machine has temporary invalid date

### ISSUE THREAD

**Issue by mpoupe** [BOINC/boinc#1539]
I accidentally switched my machine local date to year 2018 (current + 2), I reverted it back after few minutes. Unfortunately some results were reported in this interval, which caused the stat graph look strange.
OS: win7 x64
Version: 7.6.22 x64
![boinc](https://cloud.githubusercontent.com/assets/5470905/14978219/8f8e3918-111a-11e6-9985-9e2f852f30df.png)

**Comment by Ageless93** [comment]
http://boincfaq.mundayweb.com/index.php?language=1&view=590 shows how to
fix that.


-- Jord van der Elst.

**Comment by mpoupe** [comment]
Ageless93: Thank you.
