### ISSUE TITLE
win7 shell restarts when closing boinc

### ISSUE THREAD

**Issue by stievie82** [BOINC/boinc#1541]
since about 4-6 weeks the win7 shell (explorer.exe) restarts when i close the boin manager. In the Windows eventlog is just a report of that (Event-ID 1002: The shell was unexpectedly restarted). After that a "system file check" (sfc /scannow) complains corruptet system files (that cant repaired in this session). After a reboot of the system and a new run of sfc the files are restored correctly (until the error above occuring again) - any idea ?
Attaching the cbs.log from sfc --

**Comment by stievie82** [comment]
try again cbs.log
[CBS.txt](https://github.com/BOINC/boinc/files/253540/CBS.txt)

**Comment by ChristianBeer** [comment]
Is this still happening with current 7.6.33?

**Comment by stievie82** [comment]
..no, running three machines here with 7.6.33 without any problem


Von: Christian Beer [mailto:notifications@github.com]
Gesendet: Mittwoch, 12. April 2017 09:49
An: BOINC/boinc
Cc: stievie82; Author
Betreff: Re: [BOINC/boinc] win7 shell restarts when closing boinc (#1541)


Is this still happening with current 7.6.33?

**Comment by AenBleidd** [comment]
Same behavior: have several PCs on Win7 running BOINC without any problems with shell
