### ISSUE TITLE
Boinc Manager causes memory leak in gnome-panel on Ubuntu 16.04

### ISSUE THREAD

**Issue by bswarm9568** [BOINC/boinc#1543]
On Ubuntu Gnome 16.04 using gnome-flashback session... There's a memory leak in gnome-panel anytime Boinc Manager is running. Memory use of gnome-panel starts out at 18.2MB and creeps up to 3GB after about 10 hours. If I exit boinc manager, the leak stops. Boinc Manager v7.6.31 (x64). The only project running is seti@home.

**Comment by ChristianBeer** [comment]
I'm experiencing similar issues on KDE with the krunner and plasmashell processes. I've also read reports for other applications (not BOINC related) that increase memory usage of system processes. I suspect there is a problem with wxWidgets or GTK. Are you using the Manager supplied by Ubuntu or did you download from berkeley? What's your wxWidgets version in Help -> About BOINC Manager.

**Comment by bswarm9568** [comment]
It's wxWidgets v3.0.2 and I'm using the boinc version from the regular Ubuntu repo. I know there was a memory leak problem in previous versions of gnome-panel if you used the weather applet, but I'm not using that. The memory leak is only when boinc manager is running, whether it's minimized or not. This was a clean install of 16.04, not an upgrade.

**Comment by ChristianBeer** [comment]
I couldn't find a solution to the weather applet bug. The gnome-panel is a taskbar and the BOINC Manager is interacting with it through wxWidgets. I'll try to reproduce this in a VM with default Ubuntu 16.04 and Gnome.

**Comment by ChristianBeer** [comment]
I couldn't repro this but I only did a short test. Can you please elaborate on how you measure the memory usage? I usually open htop and sort by MEM_RESIDENT. I'll let it run for some more time tomorrow and see if the memory usage increases over time.

**Comment by bswarm9568** [comment]
I use System Monitor to watch the gnome-panel process creep up .2 to .4 mb every 4-8 seconds. I started removing panel indicators trying to find the culprit, then tried closing all running apps. The one that stopped it was by exiting (not just closing) boinc manager. I've tested this many times over the last few days. For now I'm leaving boinc manager exited and started using conky to keep an eye on work units.

**Comment by ChristianBeer** [comment]
I couldn't reproduce this in a VM. The memory consumption of gnome-panel and boincmgr stayed the same for the whole day. There was also no other process that increased memory usage during that time. That doesn't mean there is not leak but a bit more elaborate testing is needed. Maybe someone has to run the manager through Valgrind and sift through the output. I could imagine that the taskbar integration is not optimal in some cases.

**Comment by bswarm9568** [comment]
OK. It's probably still an ongoing problem with the notification applet and/or gnome-panel. There are several bug reports for memory leaks, one said they weren't going to fix it. I've switched to a conky script to monitor boinc projects which looks cool and uses little resources for now. If no one else has a problem, consider it closed.
