### ISSUE TITLE
Does BOINC Manager 7.6.22 (x64) ignore suspend request?

### ISSUE THREAD

**Issue by PunyFlops** [BOINC/boinc#1546]
I am looking at 8 SETI@Home threads running from a BOINC Manager with a suspended SETI@Home task. 

Why is that?

**Comment by ChristianBeer** [comment]
This sounds like a problem with the Seti@Home application. Did you try in the forums there if they updated the app recently or if other users have the same problem?

**Comment by ChristianBeer** [comment]
Please reopen if this is not a Seti problem.
