### ISSUE TITLE
Android problems: display orientation, no project list

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1550]
I just installed it on a Odroid, which is not a phone.  It fires off rotated 90degrees.  I even tried to pickup the little gizmo and spin it.  No joy.  Is there someway for me to fix that?  It also stops and asks me what projects I want to run, it doesn't seem to provide a list.  I guess I need to run some sort of a configuration for it.  I've been running nativeboinc for several years, but suddenly it refused to connect.

**Comment by GITNE** [comment]
Yes, I have experienced exactly the same on Android TV like devices, like the [OUYA](https://www.ouya.tv). #1578 has fixed the issues you mention to some extent already, especially forcing portrait screen orientation on start up. Unfortunately, fixing this is not so easy because screen orientation processing has been also mixed into the code by previous authors.

But, I am on it. :wink: D-pad navigation is also another item on my list of pending fixes.

**Comment by GITNE** [comment]
> It fires off rotated 90 degrees. I even tried to pickup the little gizmo and spin it. No joy. Is there someway for me to fix that?

Unfortunately, not really. You know, all this mobile app stuff is supposed to be fool proof. :laughing: However, all these *smart* devices and *smart* apps are only as smart as their developers. Anyway, you can try looking into your Settings app for on option to force screen orientation (either globally or per app). Some device vendors add such an option to their flavor of Android.

> It also stops and asks me what projects I want to run, it doesn't seem to provide a list.

@davidpanderson have you tried "Clear data" on the BOINC app in the Settings app? This is something that worked sort of for me. On the first launch, or when no app data is stored, I get a complete list of attachable projects. However, once I have attached any project and then try to add other projects, I get an empty list too. :unamused: I will have to figure out what is going there.

I am happy that you can test on other stationary devices than e.g. the [OUYA](https://www.ouya.tv). The emulator is good but it does not mirror *real* *world* devices. So, what kind of input devices do you use with your ODROID? Mouse, keyboard, D-pad etc?

**Comment by ChristianBeer** [comment]
@GITNE this is most likely a request via mail or from Google Play Store. No easy way to contact the OP.

**Comment by AenBleidd** [comment]
This should be fixed in the next release
