### ISSUE TITLE
error 1073741205 (0xc000026b) - STATUS_DLL_INIT_FAILED_LOGOFF

### ISSUE THREAD

**Issue by WilliamStilte** [BOINC/boinc#1553]
Forwarding the issue from [SETI NC](https://setiathome.berkeley.edu/forum_thread.php?id=79695).

Basic problem is, that BOINC tries to start tasks while Windows wants to shut down. As per thread the results can be catastrophic (i.e. lots of killed tasks). A global mutex is being offered as possible solution in   [this post](https://setiathome.berkeley.edu/forum_thread.php?id=79695&postid=1792495#1792495)

With Microsoft moving to non-scheduled shutdowns in win10 this may become a large scale problem.

**Comment by JuhaSointusalo** [comment]
The client already has code to handle special exit codes. It's just missing STATUS_DLL_INIT_FAILED_LOGOFF .

https://github.com/BOINC/boinc/blob/master/client/app_control.cpp#L455

Oh and for those magic numbers there:

```
//
// MessageId: STATUS_CONTROL_C_EXIT
//
// MessageText:
//
// {Application Exit by CTRL+C}
// The application terminated as a result of a CTRL+C.
//
#define STATUS_CONTROL_C_EXIT            ((NTSTATUS)0xC000013AL)    // winnt

```
and

```
//
// MessageId: DBG_TERMINATE_PROCESS
//
// MessageText:
//
// Debugger terminated process.
//
#define DBG_TERMINATE_PROCESS            ((NTSTATUS)0x40010004L)    // winnt
```

**Comment by JuhaSointusalo** [comment]
As for detecting when the system is shutting down, there's a load of code in https://github.com/BOINC/boinc/blob/master/client/sysmon_win.cpp

**Comment by romw** [comment]
I'll add that functionality tonight.

**Comment by romw** [comment]
Has anybody attempted to run 7.6.33:
x86: http://boinc.berkeley.edu/dl/boinc_7.6.33_windows_intelx86.exe
x64: http://boinc.berkeley.edu/dl/boinc_7.6.33_windows_x86_64.exe

It has the code to detect this issue.

**Comment by JuhaSointusalo** [comment]
There's one report in the Seti thread that the client no longer trashes tasks when it receives 0xc000026b error code.

There still seems to be something not quite right with the way the client handles Windows shutdown or the way it shuts itself down. At least in that person's machine the client seems to just keep on going even though Windows is shutting down.

**Comment by romw** [comment]
Juha, would you open up a new bug on the shutdown issue?  I'm going to go ahead and close this one.
