### ISSUE TITLE
File locking doesn't work on Lustre

### ISSUE THREAD

**Issue by ibethune** [BOINC/boinc#1563]
If you run boinc on a Lustre filesystem under Linux (e.g. on a compute cluster), this causes problems since calls to FILE_LOCK::lock() mayfail, returning ERR_FCNTL.  This seems to occur if file locking has not been enabled (it's a fs-wide option at mount time), presumably because it has a performance overhead.  The root point of failure is that fcntl( , F_SETLK , ) returns ENOSYS (i.e. not implemented).

See https://groups.google.com/forum/#!topic/lustre-discuss-list/YJz_6DMBvJg for similar reports.

This bites BOINC in two places (at least that I saw).

* The core client uses a LOCKFILE to check no other clients are running at startup.  This can be worked-around by running with <allow_multiple_clients/> in the cc_config to bypass the check

* When boinc_init is called by an app, it also uses a LOCKFILE to check no other app is running in the current slot directory.  This fails, causing the app to back off indefinitely.  I could only work around this by commenting out that check in the source code, rebuilding the boinc_api library and relinking my app.

I'm not sure what alternative solutions exist (if any).  There is some suggestion in man open:

```
              Portable programs that want to perform atomic file locking
              using a lockfile, and need to avoid reliance on  NFS  sup-
              port for O_EXCL, can create a unique file on the same file
              system (e.g., incorporating hostname  and  PID),  and  use
              link(2)  to  make  a  link  to  the  lockfile.  If link(2)
              returns 0, the lock is successful.  Otherwise, use stat(2)
              on  the  unique  file  to  check  if  its  link  count has
              increased to 2, in which case the lock is also successful.
```

Any suggestions?

**Comment by davidpanderson** [comment]
I suggest that we have LOCK_FILE::lock() succeed if the flock returns ENOSYS; i.e. not do locking if it's disabled in the FS.

The problem with the workaround in the man page, seems to me, is that old locks aren't cleaned up automatically.

**Comment by davidpanderson** [comment]
I added this in b0b5edc

**Comment by ibethune** [comment]
Great, it's working nicely. Thanks!
