### ISSUE TITLE
Hard locks with GPU access on NVidia 1080

### ISSUE THREAD

**Issue by sej69** [BOINC/boinc#1566]
I've been having issues with my computer since I upgraded to the NVidia 1080 card a couple of weeks back.  While working with NVidia support I disabled the board display adapter (intel) and I got another crash after coming back to my computer.  I was assuming it was because I have a 4k tv as my main monitor and it was powering off the device causing the computer to reload the drivers when the TV was powered back on.  It was always a hard lock so there were no error messages in the event viewer.  However after disabling the intel adapter I got an error in the event viewer at the next crash (as well as a memory dump)  The error that showed up is:

Faulting application name: setiathome_8.12_windows_intelx86__opencl_nvidia_sah.exe, version: 0.0.0.0, time stamp: 0x56fec898
Faulting module name: igdrcl32.dll, version: 20.19.15.4444, time stamp: 0x571a9017
Exception code: 0xc0000005
Fault offset: 0x000680bd
Faulting process ID: 0x10d4
Faulting application start time: 0x01d1d08b6d27fdb1
Faulting application path: C:\ProgramData\BOINC\projects\setiathome.berkeley.edu\setiathome_8.12_windows_intelx86__opencl_nvidia_sah.exe
Faulting module path: C:\WINDOWS\SYSTEM32\igdrcl32.dll
Report ID: 207062ac-b925-4a09-97b7-bacc60f8f69c
Faulting package full name: 
Faulting package-relative application ID: 

This error shows up 10+ times right before the crash.

I did notice that I was running 7.6.9 for boinc so I did update that as well to 7.6.22.  But for now, I'm leaving the GPU disabled so I can see if this really is the issue.  Also, I tried to create an account in the seti forum page but there's an error when you click on create accounts regarding captcha.

**Comment by sej69** [comment]
I've let my computer power down the monitors twice now since I disabled the GPU and the lockups went away.

**Comment by ChristianBeer** [comment]
This may be related to the latest Driver from Nvidia. Here is a similar report on the seti forum: http://setiathome.berkeley.edu/forum_thread.php?id=79753#1794724
Also you don't need an extra account for the seti forums. You can use the same account you use for crunching.
I'm closing this issue since it is project application related. If you still can't write in the seti forums you can comment here again.
