### ISSUE TITLE
Migrate to Gradle for build to enable Android Studio development

### ISSUE THREAD

**Issue by brierjon** [BOINC/boinc#1570]
As mentioned in #1439 the BOINC for Android code still is configured for Eclipse which has limited support. Android Studio is where primary development for Android tools and resources are focused. 

This issue is created to track and discuss the migration to Android Studio from Eclipse. 

The main task requires migrating the build to Gradle which an export from eclipse and verification of the conversion to gradle for building is the largest barrier to converting from Eclipse to Android Studio.

Resources:
1. Migrating to gradle for building: https://developer.android.com/studio/build/index.html
2. Migrate from Eclipse to Android Studio: https://developer.android.com/studio/intro/migrate.html

Note: Eclipse support for Android Development tools ended Nov 2, 2016 - https://android-developers.blogspot.com/2016/11/support-ended-for-eclipse-android.html

**Comment by brevilo** [comment]
@brierjon I presume this one could be closed now?

**Comment by brierjon** [comment]
Yes, gradle build support and structure is present. Closing.

**Comment by brevilo** [comment]
Thanks
