### ISSUE TITLE
VBox proposal: specify boot order

### ISSUE THREAD

**Issue by marius311** [BOINC/boinc#1573]
Currently the boot order that vboxwrapper sets up is 1) disk 2) dvd. I'm in a situation where I'd like to boot from an ISO but also use `enable_cache_disk`. Currently this is impossible since, if the cache disk is formatted, the VM will try to boot from it and hang since there's no boot sector (or whatever its called). 

I'd like to propose adding an option to `vbox_job.xml` called `boot_device` which will be either `disk` or `dvd` to specify which goes in the first boot slot. The default will be `disk` so as not to break backwards compatibility. I'm happy to code this up myself and submit a PR, I just want to get feedback if there is any first.

**Comment by ChristianBeer** [comment]
This is a very good use-case. This could additionally be a command line option to vboxwrapper so it is a little bit more flexible.
