### ISSUE TITLE
Connecting with old  account manager credentials instead of new account

### ISSUE THREAD

**Issue by jdheeter** [BOINC/boinc#1580]
This is an odd issue. I found one other person with the same problem and no solution.
https://setiathome.berkeley.edu/forum_thread.php?id=72036 

I have an install of BOINC in the default location with one account manager. On the same computer I have a second copy of BOINC that I interact with via command line. I use -dir command for alternative data directory.

 When using the second BOINC install(command line only) I issue boinccmd.exe -Join_acct_mgr with my correct credentials. BOINC connects to the account manager BAM using the credentials that I use in the other version of BOINC(in default install location).  I thought they must be interfering, so I uninstalled the default BOINC and totally wiped the data dir for second copy.  I also deleted data in %appdata% and %programdata%

With a clean slate I tried to attach my second copy of BOINC to the account manager again. To my surprise, BOINC connected to BAM using the same wrong credentials. I can not find these credentials saved anywhere on my computer, I looked in the registry as well.

Any tips or pointers as to what could be causing this? Could there be some issue with BAM seeing my CPID and assuming incorrect account?

**Comment by ChristianBeer** [comment]
Please specify your Operating system and the BOINC versions involved.

**Comment by jdheeter** [comment]
Window 10 
BOINC 7.6.22

**Comment by ChristianBeer** [comment]
If you have two copies of boinc installed you need to specify a different port number for the second installation. You also need to tell boinccmd to use this other port when communicating with the second installation. Here is a rather old how-to for this: [How To: run multiple BIONC clients on one machine - not an app_info method](http://www.xtremesystems.org/forums/showthread.php?283512-How-To-run-multiple-BIONC-clients-on-one-machine-not-an-app_info-method) but it should still work.

I also think you cannot "install" the second copy. You need to install the regular way and then copy the BOINC directories for the second installation.

**Comment by jdheeter** [comment]
I was able to
