### ISSUE TITLE
Reuse Accounts in other Apps

### ISSUE THREAD

**Issue by MTRNord** [BOINC/boinc#1586]
I want to make an App with that the Users have to submit data to the Server (harware project and they submit data that will be processed with boinc). I would love to be able to just use the DB and let my user use their boinc Project accounts, but I don't see any Documentation how the hashing of the Passwords work. Is there any Documention I am missing? I tried to reverse engineer the code for it but couldn't figure out what will be hashed and how. (But at least I think that it is only an md5 hash, am I right?)

**Comment by ChristianBeer** [comment]
I'll give you a hint: [html/user/edit_passwd_action.php#L47](https://github.com/BOINC/boinc/blob/4ff667a8881df599ab12d5c64fa7be56b2522f83/html/user/edit_passwd_action.php#L47)
Which software are you trying to use with BOINC?. There is already a Wordpress bridge that allows authentication in Wordpress via the BOINC DB and there is a Drupal module that does the same.

**Comment by MTRNord** [comment]
it will be an custom app/api for using in an android app built on ionic framework/cardova
