### ISSUE TITLE
allow users to enable/disable proxy autodetection

### ISSUE THREAD

**Issue by JuhaSointusalo** [BOINC/boinc#1588]
Some users have set up their systems to normally use a proxy but BOINC doesn't need to or shouldn't use the proxy. Currently on Windows, if the user has not set a proxy then BOINC will try to autodetect one.

BOINC should have an option to enable or disable proxy autodetection. It should be enabled by default to increase the chances of BOINC working automagically even in the presence of a proxy.

http://boinc.berkeley.edu/dev/forum_thread.php?id=11117

**Comment by ChristianBeer** [comment]
For whoever wants to tackle this feature request: Please include a checkbox in the proxy settings of the Manager too. Not only a cc_config.xml option.

**Comment by ChristianBeer** [comment]
I totally missed commit 51257b9f61b32dcce59b9453c987fc7a73c2af39 which implements this as a cc_config.xml option. Now we just need a checkbox in the manager.

**Comment by JuhaSointusalo** [comment]
Sorry @davidpanderson but I'm not happy with 51257b9. So far all the proxy options have taken effect right after changing them. You implemented the new option in a way that changing it requires client restart to take effect. I don't find that acceptable.

Also, I would like if you stopped giving new options and variables a "negative" name. Negative names just lead to double negative logic operations and parsing those tend to require more mental effort than "positive" logic.

Also, I have a sneaking suspicion that you didn't test the code... or for that matter, even compile it on Windows:

`    if (!cc_config.no_autodetect) {`



> Now we just need a checkbox in the manager.

The checkbox needs to go in both the Options dialog and Add project/AM wizard. The wizard already has [some code](https://github.com/BOINC/boinc/blob/master/clientgui/ProxyPage.cpp#L91) for the checkbox.

To save everybody's time I'll pre-emptively object using the code in the wizard as is. The name of the control and its placing suggests that only HTTP proxies can be autodetected but that is [not true](https://github.com/BOINC/boinc/blob/51257b9f61b32dcce59b9453c987fc7a73c2af39/client/sysmon_win.cpp#L359).

The checkbox should probably have a tooltip saying autodetection is currently supported only on Windows.

**Comment by davidpanderson** [comment]
I fixed the error.
Not sure it's worth polishing this feature; only 1 user requested it AFAIK.

**Comment by AenBleidd** [comment]
There were no additional requests on this last 6 years.
Usual user scenario is to use system proxy when it's configured, and this works fine with BOINC.
Closing this as 'wontfix'

**Comment by Ghost-chu** [comment]
I'm using Clash(Proxy Software) to bypass GFW, however for some reason BOINC also use that proxy and it consume my proxy traffic and sometimes it won't connect to server (because proxy unstable for sometimes), I tried to let BOINC bypass the system proxy configuration but no luck.
