### ISSUE TITLE
Remove or modify existing translation?

### ISSUE THREAD

**Issue by GITNE** [BOINC/boinc#1595]
Hello guys!

I am working on a fix to the [```plurals```](https://developer.android.com/guide/topics/resources/string-resource.html#Plurals) issue of the [```notice_notification_single_header```](https://github.com/BOINC/boinc/blob/master/android/BOINC/res/values/strings.xml#L375) and [```notice_notification_multiple_header```](https://github.com/BOINC/boinc/blob/master/android/BOINC/res/values/strings.xml#L376) string resources. Now, I am wondering what would be better to do; to remove these or to just modify them to mimic the current (in some languages incorrect) implementation in languages I cannot provide proper translation for myself? Removing could notify or alert language coordinators because Transifex would lower its translation progress indicator. Language coordinators would then need to review the new or missing string resources. Whereas just modify the string resources to mimic the current implementation might not cause Transifex to send notification or alert messages to language coordinators. However, language coordinators may not always respond quickly enough or not at all, so that if the resource string is removed BOINC users of unsupported languages would be presented with the default (English) strings.

So, how should I proceed?

**Comment by ChristianBeer** [comment]
Can you please give an example on what gets changed? I.e. how would the English strings look before and after your proposed changes?

What was done in the past is to change the English source string, compile a new template file for Transifex and inform the translators via a Transifex news item and the boinc_loc mailinglist that something big has changed with some instructions what to do.

**Comment by GITNE** [comment]
@ChristianBeer Thank you for your timely response.

> Can you please give an example on what gets changed? I.e. how would the English strings look before and after your proposed changes?

No need for an example. It is a question about workflow. But, if really want to know, it is not a big change.

As you have suggested about past proceedings, it is probably best to remove the affected string resources in other languages and inform translators. I am going post a pull request with individual commits pertaining to languages I can handle and those I cannot, so you will be able to see what changed.

**Comment by ChristianBeer** [comment]
Why do you want to tackle each language separately? All that needs changing is the English source string. This needs to be fed into Transifex where it will be added to every language and then automatically committed back into source as soon as a translator translates the new string.

So the workflow is:

1. change the template file here on github (@romw should know which file is for Android)
2. Transifex will pick up the change and change languages accordingly
3. tell translators that new strings are available and they should translate them
4. Transifex will commit the translations back to github

**Comment by GITNE** [comment]
> change the template file here on github (@romw should know which file is for Android)

This is very impractical from a developer's perspective because he has to reach out to resources that are not managed directly in his local project. Additionally, it breaks the concept of a manageable project. Transifex should work the other way round. It should pull the project from Github and load any resources (and changes) automatically before a translator can work on it. The translator should also be able to resolve merges in Transifex.

**Comment by romw** [comment]
@GITNE The bridge handles receiving notifications from GitHub and Transifex when changes are made to the GitHub repo or Transifex project.  As a general rule I stay out of the loop as much as possible.

When changes are made to boinc/locale/templates/* or boinc/android/BOINC/res/values/strings.xml GitHub notifies the bridge, the bridge then in turn downloads the changes and updates the Transifex project.  Updates to the Transifex project then cause emails to be sent out.  As the localizers update the files and reach 100%, Transifex notifies the bridge and the bridge takes the changes and commits them to the GitHub repo.

Details can be found here: https://github.com/BOINC/txgh

**Comment by GITNE** [comment]
@ChristianBeer @romw Okay, I got it now. Thanks!
