### ISSUE TITLE
Option for disabling system tray icon for BOINC Manager

### ISSUE THREAD

**Issue by fturco** [BOINC/boinc#1600]
It would be cool if there was a way to disable the system tray icon for BOINC Manager. I use the GNOME desktop environment on a Parabola GNU/Linux-libre distribution and I find system tray icons rather annoying. With workspaces I would rather move the BOINC Manager window in a dedicated workspace and forget about it.

I tried BOINC Manager version 7.6.33.

Please also see [this](https://boinc.berkeley.edu/dev/forum_thread.php?id=11129) discussion on the BOINC forums.

**Comment by AenBleidd** [comment]
FIxed via #3052
