### ISSUE TITLE
Better icon for BOINC Manager under GNOME

### ISSUE THREAD

**Issue by fturco** [BOINC/boinc#1603]
Under GNOME the BOINC Manager icon looks pretty bad:

http://i.imgur.com/0gZ8Fa4.jpg

I suspect `/usr/share/pixmaps/boinc.png` is being used, which is only 48x48 pixels in resolution. A better icon is needed, either higher resolution PNG or SVG.

BOINC 7.6.33-1. GNOME 3.20.2. Parabola GNU/Linux-libre.

**Comment by ChristianBeer** [comment]
Those images are distributed via the package of your distribution. There are better logos available here: http://boinc.berkeley.edu/logo.php
Your should file a bug against the BOINC package of your distribution to include a better version. Since BOINC is blacklisted in Parabola I don't know how to fix that. From what repository are you installing?

**Comment by fturco** [comment]
Even though my distro is Parabola I decided to install BOINC nevertheless by taking the package from Arch Linux repositories. So I guess we could file a bug on the Arch Linux tracker.

**Comment by fturco** [comment]
I migrated from Parabola to Gentoo but I have the same problem with BOINC, so I filed the following bug report: https://bugs.gentoo.org/show_bug.cgi?id=593362

**Comment by Ageless93** [comment]
Hi Francesco,

I've converted the 32x32 pixel icon into a 64x64 and 128x128 pixel icon and
then edited to take the weird conversion pixels out.
Saved as 8bit and 32bit. If you want them in any other format, just say so
and I'll make/convert them.

You can forward them to the package maintainer, no need to add workload for
them. :)

Cheers,


-- Jord van der Elst.

**Comment by Ageless93** [comment]
Ah oops, forgot edit the yellow. Fixed now. :)


-- Jord van der Elst.

**Comment by Ageless93** [comment]
And once more for completeness. :)


-- Jord van der Elst.

**Comment by fturco** [comment]
@Ageless93: I'm sorry but where can i download your icon for testing?

**Comment by Ageless93** [comment]
Ah, best not use them. David pointed out a big flaw in them. ;-)
Better to use the official ones. (I knew they were somewhere...)

http://boinc.berkeley.edu/logo.php
If you need the BMPs or TIFs translated to PNG, I can do that.


-- Jord van der Elst.

**Comment by fturco** [comment]
Sven Eden almost completely fixed the problem in Gentoo. The only remaining glitch is [this](https://bugs.gentoo.org/show_bug.cgi?id=599910). I guess I can close this bug here.
