### ISSUE TITLE
The remote job status is not provided when  min_mod_time is specified. 

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#1609]
The boinc_gahp requests can be seen in the GridmanagerLog.

BOINC_QUERY_BATCHES 4 0 9 condor#boinc-submitter.cern.ch#Sixtrack#1470046242 condor#boinc-submitter.cern.ch#Sixtrack#1470049845 condor#boinc-submitter.cern.ch#Sixtrack#1470746903 condor#boinc-submitter.cern.ch#Sixtrack#1470042521 condor#boinc-submitter.cern.ch#Sixtrack#1470049582 condor#boinc-submitter.cern.ch#Sixtrack#1470126076 condor#boinc-submitter.cern.ch#Sixtrack#1470519953 condor#boinc-submitter.cern.ch#Sixtrack#1470049378 condor#boinc-submitter.cern.ch#Sixtrack#1470089006

And we do get the following response which seems correct.

08/09/16 16:37:17 [157885] GAHP[157887] -> '4' 'NULL' '1470753439.291700' '1' 'condor#boinc-submitter.cern.ch#Sixtrack#1470046242#18.0' 'ERROR' '1' 'condor#boinc-submitter.cern.ch#Sixtrack#1470049845#21.0' 'ERROR' '1' 'condor#boinc-submitter.cern.ch#Sixtrack#1470746903#27.0' 'IN_PROGRESS' '1' 'condor#boinc-submitter.cern.ch#Sixtrack#1470042521#17.0' 'ERROR' '1' 'condor#boinc-submitter.cern.ch#Sixtrack#1470049582#20.0' 'ERROR' '1' 'condor#boinc-submitter.cern.ch#Sixtrack#1470126076#23.0' 'ERROR' '1' 'condor#boinc-submitter.cern.ch#Sixtrack#1470519953#26.0' 'IN_PROGRESS' '1' 'condor#boinc-submitter.cern.ch#Sixtrack#1470049378#19.0' 'ERROR' '1' 'condor#boinc-submitter.cern.ch#Sixtrack#1470089006#22.0' 'ERROR'

However after the first call, the subsequent ones  include a timestamp where before there was 0.

08/09/16 19:32:27 [158462] GAHP[158465] <- 'BOINC_QUERY_BATCHES 14 1470763888.431700 9 condor#boinc-submitter.cern.ch#Sixtrack#1470046242 condor#boinc-submitter.cern.ch#Sixtrack#1470049845 condor#boinc-submitter.cern.ch#Sixtrack#1470746903 condor#boinc-submitter.cern.ch#Sixtrack#1470042521 condor#boinc-submitter.cern.ch#Sixtrack#1470049582 condor#boinc-submitter.cern.ch#Sixtrack#1470126076 condor#boinc-submitter.cern.ch#Sixtrack#1470519953 condor#boinc-submitter.cern.ch#Sixtrack#1470049378 condor#boinc-submitter.cern.ch#Sixtrack#1470089006'

And the following is returned.

08/09/16 16:39:18 [157885] GAHP[157887] -> '14' 'NULL' '1470753559.707100' '0' '0' '0' '0' '0' '0' '0' '0' '0'

The difference in the XML submitted is:

```
<min_mod_time>0.000000</min_mod_time>
<min_mod_time>1470763888.431700</min_mod_time>
```

And the returned XML respectively are:

```
<?xml version="1.0" encoding="ISO-8859-1" ?>
<query_batch2>
<server_time>1470764185.2719</server_time>
   <batch_size>1</batch_size>
    <job>
<job_name>condor#boinc-submitter.cern.ch#Sixtrack#1470042521#17.0</job_name>
        <status>ERROR</status>
    </job>
   <batch_size>1</batch_size>
    <job>
<job_name>condor#boinc-submitter.cern.ch#Sixtrack#1470046242#18.0</job_name>
        <status>ERROR</status>
    </job>
   <batch_size>1</batch_size>
    <job>
<job_name>condor#boinc-submitter.cern.ch#Sixtrack#1470049378#19.0</job_name>
        <status>ERROR</status>
    </job>
   <batch_size>1</batch_size>
    <job>
<job_name>condor#boinc-submitter.cern.ch#Sixtrack#1470049582#20.0</job_name>
        <status>ERROR</status>
    </job>
   <batch_size>1</batch_size>
    <job>
<job_name>condor#boinc-submitter.cern.ch#Sixtrack#1470049845#21.0</job_name>
        <status>ERROR</status>
    </job>
   <batch_size>1</batch_size>
    <job>
<job_name>condor#boinc-submitter.cern.ch#Sixtrack#1470089006#22.0</job_name>
        <status>ERROR</status>
    </job>
   <batch_size>1</batch_size>
    <job>
<job_name>condor#boinc-submitter.cern.ch#Sixtrack#1470126076#23.0</job_name>
        <status>ERROR</status>
    </job>
   <batch_size>1</batch_size>
    <job>
<job_name>condor#boinc-submitter.cern.ch#Sixtrack#1470169805#24.0</job_name>
        <status>DONE</status>
    </job>
   <batch_size>1</batch_size>
    <job>
<job_name>condor#boinc-submitter.cern.ch#Sixtrack#1470314864#25.0</job_name>
        <status>DONE</status>
    </job>
   <batch_size>1</batch_size>
    <job>
<job_name>condor#boinc-submitter.cern.ch#Sixtrack#1470519953#26.0</job_name>
        <status>IN_PROGRESS</status>
    </job>
</query_batch2>
```

and

```
<?xml version="1.0" encoding="ISO-8859-1" ?>
<query_batch2>
<server_time>1470764518.9648</server_time>
   <batch_size>0</batch_size>
   <batch_size>0</batch_size>
   <batch_size>0</batch_size>
   <batch_size>0</batch_size>
   <batch_size>0</batch_size>
   <batch_size>0</batch_size>
   <batch_size>0</batch_size>
   <batch_size>0</batch_size>
   <batch_size>0</batch_size>
</query_batch2>
```

**Comment by davidpanderson** [comment]
This is the correct behavior (see my email)
