### ISSUE TITLE
boinc_gahp is not returning a job status classad

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#1610]
From looking at the[ specifications of other gahps](https://research.cs.wisc.edu/htcondor/gahp/), it seems that the result should have the following syntax.

<reqid> <SP> <result-code> <SP> <error-string> <SP> <result-classad> <CRLF>

It looks like the result from the boinc_gaph does not provide a job status classad.

$GahpVersion: 1.0 Aug  9 2016 BOINC\ GAHP $
BOINC_SELECT_PROJECT http://lhcathomedev.cern.ch/vLHCathome-dev/ xxxxxxxxxxx
S
BOINC_QUERY_BATCHES 5 0 1 condor#boinc-submitter.cern.ch#Sixtrack#1470782967
S
RESULTS
S 1
5 NULL 1470816845.222300 1 condor#boinc-submitter.cern.ch#Sixtrack#1470782967#28.0 IN_PROGRESS

My guess is that it should provide the following class add.

[\ ClusterId\ =\ 28;\ ProcId\ =\ 0;\ JobStatus\ =\ 2;\ ]

**Comment by davidpanderson** [comment]
I don't understand.  The BOINC GAHP (like the other variants) returns a simple job status indicator (in progress/done/error in our case), not a Class Ad.
