### ISSUE TITLE
client rendering OS X unusable

### ISSUE THREAD

**Issue by MrVulcan** [BOINC/boinc#1611]
I can't use the BOINC client anymore, because whenever I run it, my computer becomes unresponsive. To resolve the problem, I have to shut the computer down by holding the Power button, start it back up and then (force) quit the BOINC client before OS X becomes unresponsive.

Is something wrong in the client, or in the settings? Can I do anything to resolve this myself?

**Comment by CharlieFenton** [comment]
Your Mac may be crashing (kernel panic) due to overheating, usually by the GPU. Search "BOINC overheating Mac" (without the quotation marks) on Google for some possible solutions.

Also, make sure you have "suspend when computer is in use" set and "Leave tasks in memory when suspended" off in your BOINC computing preferences.

Cheers,
--Charlie

**Comment by MrVulcan** [comment]
I'll do that search, but I do have a question:

How will I make sure "suspend when computer is in use" is set and "Leave tasks in memory when suspended" is off, if my Mac Pro becomes unresponsive almost the moment I activate the BOINC Manager?

I ended up removing the BOINC Manager and deleting the data directory. When I reinstalled the BOINC Manager again all was well.

Regards,

Bert


> Op 11 aug. 2016, om 02:44 heeft CharlieFenton <notifications@github.com> het volgende geschreven:
> 
> Your Mac may be crashing (kernel panic) due to overheating, usually by the GPU. Search "BOINC overheating Mac" (without the quotation marks) on Google for some possible solutions.
> 
> Also, make sure you have "suspend when computer is in use" set and "Leave tasks in memory when suspended" off in your BOINC computing preferences.
> 
> Cheers,
> --Charlie
>
