### ISSUE TITLE
exclusive apps for GPU doesn't work

### ISSUE THREAD

**Issue by TheSisa** [BOINC/boinc#1612]
Hey there,

I just wanted to set up an exclusive app (a game) in BOINC, so I get higher FPS in the game. Unfortunately, it doesn't work. I checked the name of the process of the game twice, I checked the config file, it is all there. I've restarted BOINC manager, even my computer. The exclusiveness for GPU still doesn't work. I've got nVidia GTX 970 and the 7.6.22 version of BOINC manager.

Thank ya mates,
looking forward to a solution.

**Comment by ChristianBeer** [comment]
Can you give me an example of the filename? I also presume you are using the Windows BOINC Manager?

**Comment by Ageless93** [comment]
Make sure that Activity in BOINC Manager's advanced view is set to "Run
based on preferences", for when it's set to "Run Always" it will ignore any
run-based preferences set, including this one.


-- Jord van der Elst.

**Comment by TheSisa** [comment]
Ah, I overlooked this option, that was it. Thank you guys, it works now :). I have just one more question. Can I somehow (it can be other program, not BOINC manager) set an option for automatic clocking the GPU? When I play games, I usually overclock my GPU a bit (using MSI Afterburner), but it makes some noise, so I don't wanna have it overclocked, when "just" BOINC manager is running, but I have to do it manually. Is this process automatable?

Thank you again
