### ISSUE TITLE
BOINC stops processing on Fire 5th gen tablet

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1625]
(from a user):
For some reason BOINC stops crunching tasks in the Amazon Fire 7" 5th Gen tablet. It seems that the tablet drops the Wifi connection and that is when BOINC stops crunching. What happens is that the task timers stops, and there are no progress for any tasks. The solution is to turn off the Wifi and turn it on again, and the tasks will continue crunching, but after a few hours, the problem starts again. This issue only happens in the Fire tablet as my other Android phones and tablets runs BOINC perfectly. I did a factory reset and it is only running BOINC but the problem still persist.

I am running BOINC 7.4.53

**Comment by AenBleidd** [comment]
Not an issue anymore on 7.16.16
