### ISSUE TITLE
BOINC causes "device is not removable and cannot be ejected or unplugged."

### ISSUE THREAD

**Issue by jmngpt** [BOINC/boinc#1630]
I have a Nvidia Geforce 930M on my laptop, and installed the latest Windows BOINC Manager version and attached Rosetta and GPUGrid.

Now, whenever BOINC Manager starts, I get an error saying that "Device Nvidia Geforce 930M is not removable and cannot be ejected".

After that, my GPU is no longer recognized in Device Manager (it gets moved from the Display Adapters section to the Other Devices section).

This only happens if/when I start BOINC, and before any tasks start processing, both with older Nvidia drivers (two versions ago) and with the latest drivers. If I login and do not start BOINC, this does not happen.

Is there any fix for this?

**Comment by ChristianBeer** [comment]
This was discussed on the BOINC dev forums some time ago and the problem was identified as a buggy driver or Windows Update. Something outside of BOINCs control. If you still have this issue with latest updates please reopen.

**Comment by jmngpt** [comment]
The problem manifested itself with three different driver versions, hard to understand how this is caused by "buggy drivers"...
