### ISSUE TITLE
Port XML routines to libxml++

### ISSUE THREAD

**Issue by vorot93** [BOINC/boinc#1633]
BOINC uses XML format throughout its operation on every level from shared memory to HTTP server communication.

Right now the XML code is organized in the following way:
* Output: XML is hand-formed by the programmer and printed into FILE* or the MFILE/MIOFILE wrapper. (e.g. `fprintf(stream, "<tag>data</tag>\n");`)
* Input: BOINC implements `XML_PARSER` that contains logic for parsing XML buffers.

**This presents the following challenges:**
**XML correctness**:
Well-formedness of resulting documents is hit-and-miss when it comes to BOINC XML routines. Complaints from users about that are not exactly a rarity on this bug tracker.

**Presentation matters**
Abscence of proper data structure (DOM), while not a bug, presents challenges regarding extensibility. Programmer should never care about *XML* format, just about the *data* input/output (e.g. an `std::map` that will be passed to XML document factory).

*A fix for this will pave the way to quick JSON migration but that is outside the scope of this proposal.*

**Code bloat and unmaintainability**
* Every XML routine currently does its own check for well-formedness, instead of once, globally, and on load. For example, documents with unclosed nodes must be thrown out the window *immediately* because they are garbage, not structured information.
* Strings must be escaped/unsecaped manually `xml_escape` / `xml_unescape`. Failure to do so will go undetected and poison resulting output / data variable.
* XML_PARSER forces you to write imperative, *variable sharing* code (`XML_PARSER::parse_*`). Akin to real world *needle-sharing* this coding paradigm is extremely dangerous as it may lead to data corruption or hide obvious bugs (e.g. required data is absent but the code moves on and uses leftover data of unrelated instruction from shared variable).
* It is simply outside BOINC's scope and leads to extra code that could be omitted.

---------------------------------

In light of these I propose a port to [libxml++](https://developer.gnome.org/libxml++/stable/).

**What is libxml++?**

* C++ wrapper for *[libxml2](http://xmlsoft.org/)*, well known XML manipulation library, present on *every* Linux installation and in many Windows applications.
* Developed by [GNOME project](https://gnome.org), yet cross-platform.
* Presents an class-based, RAII-oriented XML API, features rich capabilities for XML manipulation.

**Boons of the port**
* No more XML correctness complaints, libxml2 is industry proven to output proper XML data.
* New XML routines will navigate **DOM** instead of floating in the sea of characters.
* Single point of data entry/exit. All XML data will be parsed on stream read / file load. Classes down the deserialization line will receive DOM.
* Clean, declarative and functional DOM-to-class deserialization code.

**Challenges of the port**
* The port will bump C++ version requirement to **C++11**.
* The port can only be divided into big chunks. While classes do serialization/deserialization themselves, big structures like `CC_CONFIG` call output/parsing routines of other objects. Such spider webs will have to be converted *at once and together*.
* Care has to be taken when using libxml++'s routines because **they may throw**. BOINC does not use exceptions therefore these must be caught on sight and converted to error numbers.
* While it is possible to parse/encode XML in different encodings with libxml++, the default is **UTF-8**. For the best results we should stick with it.
* Compiling and linking against libxml++ is easy on Linux but may require effort on OS X and Windows.

---------------------------------

My rewrite of XML routines is currently underway. Unfortunately, BOINC does not have its .clang-format and therefore my code is reformatted making diffs polluted. #1622 must be resolved before a rewrite this magnitude is merged.

Refs #1617, #1622

**Comment by davidpanderson** [comment]
I don't think a rewrite of the XML code would be advantageous.  The existing code has been stable for years, and AFAIK there are no XML-related problems in any of the APIs.  I'd prefer to focus on functional improvements.

**Comment by grctest** [comment]
@davidpanderson Would it not also solve this XML-related problem which affects ~1350 users within the Gridcoin pool? https://github.com/BOINC/boinc/issues/1470

In fact, within #1470 you stated that the only way to fix #1470 would be to add a real XML parser: https://github.com/BOINC/boinc/issues/1470#issuecomment-173858009

**Comment by skybon** [comment]
@davidpanderson except issues with XML conformance pop up now and then.

**Comment by brevilo** [comment]
Apart from the important reasons already stated above, adding the possibility to validate any XML (by using libxml) **is** a functional improvement that can't be rated high enough, given the load of broken XML floating around in the BOINCsphere...

**Comment by ChristianBeer** [comment]
@skybon I'm currently investigating how to integrate a libxml++ DOM parser into our scheduler. The goal is to validate incoming XML against a DTD on a small scale. I think this is a good way to see how to integrate libxml into the larger BOINC code one step at a time.

**Comment by davidpanderson** [comment]
That's something we'd need to discuss as a group.

**Comment by skybon** [comment]
@ChristianBeer I have stage 1 of port complete (IPC + writing routines for lib classes). It is as little a step as it gets.

@davidpanderson I strongly suggest to use [Gitter](https://gitter.im) for it. It retains history and provides GitHub integration.

**Comment by ChristianBeer** [comment]
@davidpanderson Yes, definitely. I just wanted to get a feeling how to use libxml++ for this simple task. In the end it was just a few lines of extra code to parse the global preferences directly in the scheduler and get a valid/invalid answer. It would now detect invalid XML like the missing </venue> tag we see right now. But it would also detect other things too. The parsing into the data structures is still happening the old way. While reading the reference doc and examples I also found out that libxml++ allows validation using an XML Schema (XSD) definition which is easier than DTD.

@skybon I don't want to discourage you but the last time I checked you had one massive commit with a diff that github could barely show. This is very bad to review if that should be merged.

**Comment by brevilo** [comment]
> I also found out that libxml++ allows validation using an XML Schema (XSD) definition 

The way to go

**Comment by skybon** [comment]
@ChristianBeer I am currently plucking out unrelated style fixes. Afterwards I will split the changes and start submitting isolated pull requests.

**Comment by JuhaSointusalo** [comment]
Some challenges not mentioned before. (Maybe they are too obvious but I want them mentioned anyway.)

Backward compatibility.

The new code needs to be able to handle any XML the current code produces, even if that XML isn't well-formed like the one used in app IPC. And vice versa. The new code needs to produce XML that the old code can read.

Forward compatibility.

This matters at least for global preferences. The new code needs to store and send forward all preferences, not only the preferences it understands.

As for things already mentioned.

> The port can only be divided into big chunks. While classes do serialization/deserialization themselves, big structures like CC_CONFIG call output/parsing routines of other objects. Such spider webs will have to be converted at once and together.

I would very much like you to re-consider this. Once you get to the big ones like CLIENT_STATE, SCHEDULER_REQUEST or SCHEDULER_REPLY you'd need to do all of them at the same time plus a few GUI RPCs and maybe something else too. That's too much to review in just one commit.

A much better approach would be one class per commit. The glue code between old and new code doesn't need to pretty or even working, it's just temporary code. As long as the end result works it doesn't matter what the code temporarily looks like.

> The port will bump C++ version requirement to C++11.

This seems to have been overlooked, probably because it wasn't there originally. So far there has not been any agreement on switching BOINC to C++11. While I agree that using C++11 makes the code more readable, especially the parsing code, you should make sure there is a compatible compiler available for all supported platforms.

About the validation. How the new code should react when it encounters bad XML? Taking the global prefs with missing end tag as an example. Right now projects have such bad XML in their databases. When a project's server is updated to the new code and there's a request that requires handling the bad XML should the server throw it's hands up in the air and refuse to continue or should it notify the user and continue processing the request as best it can?

Right now BOINC seems to be coded with just keep on going mentality and I think it tolerates problems reasonably well. I would like to see that kept. I don't think being very strict would be helpful and I think being very strict would break BOINC for set it and forget people.

**Comment by skybon** [comment]
@JuhaSointusalo 
> The glue code between old and new code doesn't need to pretty or even working, it's just temporary code.

Correct me if I'm wrong but the usual VCS policy is *no broken commits*. If so then:
> A much better approach would be one class per commit.

Unfortunately it does not work that way. **You just cannot mix model (DOM) and representation (plain text)**. DOM is decoded/encoded in *entry/exit points* and the classes receive/output *DOM data structures*. Therefore each XML hierarchy must be converted at once.
> How the new code should react when it encounters bad XML? Taking the global prefs with missing end tag as an example.

**Data with missing end tag is not XML**, end of story. It will be (at least by default) rejected on sight with exception thrown by any industry-quality DOM parser. We are talking about structured data hence an error like this must never be skipped for receiver's sake.

**Comment by davidpanderson** [comment]
If it's not broken, don't fix it.

**Comment by brevilo** [comment]
Kaizen.

**Comment by JuhaSointusalo** [comment]
> If it's not broken, don't fix it.

It's not thoroughly broken but it's not working perfectly either.

> Correct me if I'm wrong but the usual VCS policy is no broken commits.

Shrug. Not breaking the build is more important when you are pushing individual commits but when you are pushing a number of commits I think what matters are the commits as a whole.

I forgot to ask earlier. What kind of diagnostic libxml++ gives when you try to parse invalid XML? Does it give some kind of human readable explanation like "missing tag X"? Useful messages makes it easier to help people in forums or even enable people help themselves.

**Comment by ChristianBeer** [comment]
> I forgot to ask earlier. What kind of diagnostic libxml++ gives when you try to parse invalid XML? Does it give some kind of human readable explanation like "missing tag X"? Useful messages makes it easier to help people in forums or even enable people help themselves.

It throws an exception which contains some error messages. Here is what it looks like with the missing closing venue tag:
```
[prefs] Parser error
[prefs] Line 89, column 22 (fatal): Opening and ending tag mismatch: venue line 62 and global_preferences
[prefs] Line 90, column 1 (fatal): Premature end of data in tag global_preferences line 1
```
libxml has a strange error format with 2 lines per error but I already have code to transform this to the one line format BOINC uses (shown above).

**Comment by ChristianBeer** [comment]
Another example that the XML parsing is broken would be [lib/parse.cpp#L330](https://github.com/BOINC/boinc/blob/2715c5b8a7acb6be3de7b7494d13d9f851319433/lib/parse.cpp#L330). Adding attributes to the `<venue>` tag breaks venue specific preferences. This would not have happened with a proper XML parser.

**Comment by vorot93** [comment]
Closing in favour of https://github.com/boinc-next/boinc-client/issues/2

**Comment by grctest** [comment]
@vorot93 Why fork instead of merge into the main BOINC repo?

Would be sensible to keep this issue open since it's still unresolved in this repo.

**Comment by AenBleidd** [comment]
@grctest As I understand he just offended.

**Comment by vorot93** [comment]
@grctest 
There is no way that this goes mainline any time soon.

Libxml++ port is just too big and (apart from breakage potential of itself) likely will not work w/ MSVS build chain, Therefore we have to fix up Autotools toolchain for MinGW or Cygwin and throw away MSVS. And *this* will *never* be approved by Berkeley.

Today we have this impasse and the fact that C++ dev here has gone stale and PRs get no review for months. It can only be resolved by a fork.

Hey, on the bright side, since Git allows easy cherry picking, we won't break Berkeley and will share commits. Maybe one day the port will get mainlined. But for now, time to go separate ways.

**Comment by grctest** [comment]
@vorot93 If you feel there is a problem that is going unresolved you could publicly approach the BOINC project governance regarding the matter: https://boinc.berkeley.edu/trac/wiki/ProjectGovernance

Will current/new BOINC projects have to support either boinc or boinc-next? Or is it backwards compatible?

**Comment by vorot93** [comment]
@grctest boinc-next client will be backwards compatible (or it's all for naught). In any case, I don't think that discussing the fork is appropriate in this thread.
