### ISSUE TITLE
MacOS Sierra not telling BOINC client about idleness?

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#1651]
Can someone test whether BOINC 7.6.33 works correctly with the new Macintosh OS X Sierra, and test that it follows the idle settings correctly? We have had a report in on the forums (https://boinc.berkeley.edu/dev/forum_thread.php?id=11207) that it doesn't do so, and the lead developer's system is too old to run Sierra, so he cannot test.

**Comment by nadavfima** [comment]
@Ageless93 yup, this build fixed it for me...
