### ISSUE TITLE
BOINC can no longer find GPU after latest Windows 10 update

### ISSUE THREAD

**Issue by milesrf** [BOINC/boinc#1652]
Tonight, I shut down BOINC long enough to install the latest 64-bit Windows 10 update.  After the Windows restart, I restarted BOINC - but it was no longer able to find my GT440 graphics board.  Status of all the GPU tasks now starts with GPU missing, GPU suspended.

Note - the model of motherboard in this computer is known for being unable to boot with an Nvidia-based graphics board more recent than the GEFORCE 500 generation.

**Comment by ChristianBeer** [comment]
This is most likely related to Microsoft pushing a non-OpenCL driver on top of the installed original Nvidia driver. You may need to reinstall the driver supplied by Nvidia to get access to CUDA and OpenCL again.

**Comment by ChristianBeer** [comment]
Was this resolved in the meantime?

**Comment by Toby-Broom** [comment]
I can confirm Christians comments with my computer
