### ISSUE TITLE
Android no new works

### ISSUE THREAD

**Issue by ezzo24** [BOINC/boinc#1659]
I have a Samsung galaxy s6.
Boinc worked well since 4 months ago, when started to say "no new works".
No way to download new tasks.
All ok with other devices.

Also see http://setiathome.berkeley.edu/forum_thread.php?id=79857&postid=1800335#1800335

Seems to be a bug of new application version.

**Comment by AenBleidd** [comment]
Seems to be a known issue: #1597

**Comment by ezzo24** [comment]
My cpu was correctly detected and worked fine for many months.
New application version does not work.
Why don't they fix it ?

**Comment by ChristianBeer** [comment]
The BOINC project currently does not have an Android developer who is able to investigate and fix this issue.

**Comment by brevilo** [comment]
FYI, I can't reproduce that error using a build based on 6e8c453 (current master).

Tested:
* AOSP 6.0.1 (M4B30Z on `hammerhead`)

**Comment by ezzo24** [comment]
works again

**Comment by brevilo** [comment]
Yeah! Thanks for the feedback.
