### ISSUE TITLE
boinc_copy() returns 0 if fread() fails

### ISSUE THREAD

**Issue by ibethune** [BOINC/boinc#1661]
I spotted a problem where zero-sized (or truncated) output files are returned to the PrimeGrid server.  The final task before calling boinc_finish() of our LLR wrapper code is to boinc_copy() a file into the project directory from the slot directory.

I think there is a hole in the logic of boinc_copy, where if the fread() fails (in my case due to a system interrupt EINTR, but presumably other cases could also occur), it will return 0 but boinc_copy takes this to signify and end-of-file and returns 0.  The file is not (completely) copied and the caller has no way of taking corrective action e.g. back-off and try again, or at least print an error message

I think a better solution than

```
n = fread(buf, 1, sizeof(buf), src);
if (n <= 0) break;
```

is something like:
```
n = fread(buf, 1, sizeof(buf), src);
if (n <= 0) {
   // Either end of file or an error occurred
   if (!feof(src)) retval = ERR_FREAD; // return an error to the caller
   break;
}

This seems to be a fairly rare occurrance, I hit the problem 5 times out of ~1500 tasks, so I'm currently waiting for it to happen again (running with the above fix + some debugging output).  Will update the ticket when that happens.

**Comment by AenBleidd** [comment]
I think you should make a Pull Request to let your changes be integrated in a proper way.

**Comment by davidpanderson** [comment]
I committed the change; thanks.
