### ISSUE TITLE
VirtualBox GPU

### ISSUE THREAD

**Issue by MTRNord** [BOINC/boinc#1667]
Is GPU processing with Virtualbox possible or are there limitations that don't allow to compute on GPU? Reason is: I want to compute OpenCV (py as language) with Boinc. OpenCV uses huge amount of power so it would be nice to do evreything that has the GPU support by OpenCV get calculated on the GPU and not CPU. 

TL;DR:
Can I use VBox with GPU (for OpenCV calculation) or do I need to write myself another wrapper (or something other)?

**Comment by AenBleidd** [comment]
As far as I know this is a limitation of VirtualBox: https://www.virtualbox.org/manual/ch09.html#pcipassthrough
