### ISSUE TITLE
Please retry transfer when transient HTTP error will happen

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#1673]
I have problem downloading some files for World Community Grid, I see following entry in log:

2016-10-11 08:19:28 | World Community Grid | Temporarily failed download of wcgrid_oet1_vina_7.19_windows_x86_64: transient HTTP error

After such failure BOINC removes file from download list, and WU is marked as "download failed" and reported back to server. Please change this, transient means that this is a temporary issue which may be resolved soon. I propose to start retrying transfers like for timeout. Additionally you can add limit maximum number of attempts download, and fail transfer if this count will be exceeded.

**Comment by AenBleidd** [comment]
I think this is a bad idea: you have time limit to calculate the task. This time limit starts at the moment when server send to the client a notification about new task available. If we use the same rules of attempts to retry the download as we have now for uploading there will be a possibility that this task will be not finished in time. 
And such kind of 'temporary issue' may not be resolved during long time as we can see on some projects.

**Comment by sirzooro** [comment]
Yes, sometimes this can take too long. But in this case I suspect that server is overloaded so second or third attempt should be successful. Yesterday I had the same problem with WCG OpenZika app, today it was downloaded successfully.  So there should be some total limit how long BOINC can retry - I think one day (24h) is reasonable.

**Comment by AenBleidd** [comment]
I think fixed time is not very good (what if we will have some small tasks for 1 day only?).
I suggest 10% of time slot to retry download.

**Comment by ChristianBeer** [comment]
What version are you talking about? Looking at the current implementation it is already considered transient. See: https://github.com/BOINC/boinc/blob/master/client/pers_file_xfer.cpp#L276
So there must be something else wrong why the task is aborted. What is the actual HTTP error?

Looking a bit further I can see that the time until a transient error is considered permanent is already configurable: https://github.com/BOINC/boinc/blob/master/client/pers_file_xfer.cpp#L329 through the "--file_xfer_giveup_period" commandline argument. The default is 90 days.

**Comment by AenBleidd** [comment]
As far as I know BOINC tries to re-upload files only. I've never saw it trying to re-download them.

**Comment by sirzooro** [comment]
I am using BOINC 7.6.22 (x64) for Windows.

I do not know which HTTP error was sent, it is not logged by default. I would have to play a bit with WCG to reproduce this and get more logs.

I am not sure if I remember correctly, but this may be another scenario - download started but was not completed successfully (server closed connection or something like this). Could you check how this scenario is handled in code?

**Comment by ChristianBeer** [comment]
The message itself states that it is a temporary error. I only encountered HTTP 404 errors which are considered permanent and print a different message. Following the code that produces the OP's message leads directly to a transient error and a retry of the download not an abortion of the task. A link to the task on the WCG page would also be nice as there might be extra information in the stderr output.

**Comment by sirzooro** [comment]
Is it possible to get link to task from WCG which is publicly accessible? I tried to copy one, but had to login when I tried to open it from other browser.

Following error details were sent to WCG server:

```xml
<core_client_version>7.6.22</core_client_version>
<![CDATA[
<message>
app_version download error: couldn't get input files:
<file_xfer_error>
<file_name>wcgrid_oet1_vina_7.19_windows_x86_64</file_name>
<error_code>-120 (RSA key check failed for file)</error_code>
<error_message>signature verification failed</error_message>
</file_xfer_error>

</message>
]]>
```

**Comment by ChristianBeer** [comment]
That error means that the download succeeded but the signature from the project did not match. This happens sometimes and can have multiple reasons. If you see this error regularly you should check stability of your Internet connection or if your firewall modifies data that is downloaded.

**Comment by sirzooro** [comment]
This must be something related to WCG, I did not have such issues in the past.

So looks that BOINC downloaded file, tried to verify its signature but it failed, then logged this as transient HTTP error and marked WUs as failed because of download problem. I wonder how this work - should BOINC try to re-download file, or log some non-transient error?

**Comment by ChristianBeer** [comment]
I don't think it happened that way. Most likely there was a transient error (that was logged) but later the download was successful and the signature verification failed (which was not logged). What also could have happened is that signature verification was done on the incomplete file but I don't see any evidence for that in the code. BOINC logged a permanent error just not to the user but to the project.

**Comment by ChristianBeer** [comment]
If you encounter this again please try to set `file_xfer_debug` as a log flag and add the output here.
