### ISSUE TITLE
Please make <url> tag in <exclude_gpu> optional

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#1688]
BOINC allows to exclude GPU for some projects in cc_config.xml using `<exclude_gpu>` tag. When someone wants to exclude some GPU completely, he has to repeat this tag for every project with GPU apps because child `<url>` tag is required. Please make it optional or allow to use some special value there (e.g. `*`) to tell BOINC that given GPU is not available for all projects.

**Comment by RichardHaselgrove** [comment]
This facility is already available through the 'ignore' device option.

**Comment by Ageless93** [comment]
Added a line in the client_configuration documentation pointing out that
for all project GPU use excluding, the <ignore_*_dev> options can be used.


-- Jord van der Elst.

**Comment by ChristianBeer** [comment]
For future reference: [client_configuration](https://boinc.berkeley.edu/wiki/client_configuration#Options) (search for `ignore_`)

**Comment by sirzooro** [comment]
Thanks, I found <exclude_gpu> some time ago and assumed there are no other tags for this.

BTW, I suspect that in the future one more <ignore> tag will be needed for Odroid XU4's Mali-T628 GPU :)
