### ISSUE TITLE
Feature request: 'Apply' button on Event Log options dialog.

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#1689]
'Apply' would configure and activate the new set of choices (as 'OK' does now), but leave the dialog open for reuse. This would enhance usability during debugging:
- When you want to study the output from one of the verbose options, but not leave it running continuously.
- When you're not quite sure which option would be most useful, and want to try alternatives.
- If you activate the dialog with Ctrl+Shift+F while viewing the Event Log window (which works - nice touch), the default positioning obscures the very thing you want to concentrate on. Leaving it open would allow you to park it on a different part of the screen while you work.

**Comment by AenBleidd** [comment]
Fixed in PR #1715

**Comment by RichardHaselgrove** [comment]
Many thanks to AenBleidd for that. Tested in a private build, and works a treat.

**Comment by ChristianBeer** [comment]
Is the button in the right order on Windows? Would be a shame if we have a different ordering as the user expects.

**Comment by RichardHaselgrove** [comment]
'Apply' buttons are rare in user applications in Windows, but are common in the operating system dialogs known as 'property sheets'. I think the order (OK, Defaults, Cancel, Apply) conforms to the guidance in https://msdn.microsoft.com/en-us/library/windows/desktop/bb774538(v=vs.85).aspx

The only thing missing is that the 'Apply' button would normally be disabled when the dialog is first opened, and only become active when one of the checkboxes is toggled - but that would be a lot of extra work to implement, and IMHO hardly worth it.

**Comment by AenBleidd** [comment]
@ChristianBeer, Yes, this is the default button order in Windows.
@RichardHaselgrove, it would be not so easy to implement such behavior of 'Apply' button. I think this is not a critical issue.

**Comment by RichardHaselgrove** [comment]
"not a critical issue": Agreed

**Comment by JuhaSointusalo** [comment]
Something like this in the constructor:

```
btnApply->Disable();
Bind(wxEVT_CHECKBOX, [btnApply] (wxCommandEvent&) {
    btnApply->Enable();
});
```

Converting it to pre C++11 if left as an exercise for the reader.

**Comment by AenBleidd** [comment]
@JuhaSointusalo, thank you for the advice. I've made a new commit.
@RichardHaselgrove, please check the new behavior.
@davidpanderson, please review this.

**Comment by RichardHaselgrove** [comment]
Just got back in, so only a very quick test - but seems to be working perfectly. Thanks to all who contributed.

**Comment by AenBleidd** [comment]
New PR #1718 opened with proper name instead of #1715

**Comment by RichardHaselgrove** [comment]
Tested Windows builds - both 32bit and 64bit - from #1718 source files. All OK.

**Comment by AenBleidd** [comment]
@RichardHaselgrove Thank you! I really appreciate your help :+1:

**Comment by RichardHaselgrove** [comment]
I should be the one thanking you - it was my request in the first place! Deploying the new build around my other machines has also confirmed that #1711 is working too.

I think that this thread has been a good example of the community development model in action. All we have to do now is to invent a community deployment model to finish the job.

**Comment by RichardHaselgrove** [comment]
Thanks David. I think we're done here.

**Comment by AenBleidd** [comment]
@RichardHaselgrove I think you close this too early because this PR was not integrated into any release.

**Comment by RichardHaselgrove** [comment]
I think public build availability and release management are issues worthy of discussion, but are a wider subject than this single (welcome) enhancement. If anything comes to my attention specifically related to the operation of the diagnostic log flag selection dialog, I'll happily open it again - github has provided me with a button for that purpose.
