### ISSUE TITLE
Cannot change priority for application

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#1698]
I am trying to run cgminer from BitcoinUtopia project on non-idle priority, because now it times-out during detection of my USB miner. This project uses BOINC wrapper, so I tried to add `<priority>3</priority>` to job.xml file. Unfortunately this did not help, `ps -u boinc -l` shows that both wrapper and cgminer are still on the lowest priority like other tasks. I am not sure if this is some bug or wrapper used by BU does not support this tag (wrapper file is named wrapper_26014_x86_64-pc-linux-gnu).

I also found that it is not possible to modify priority for apps which uses BOINC library to talk directly to BOINC Client, there are no similar tag for use in app_config.xml and app_info.xml. It would be good to add one, sometimes it may be needed.

I use BOINC 7,7,0 on Linux CentOS 7.

**Comment by AenBleidd** [comment]
Hello.
This is related to the issue #1128 fixed in PR #1394. As far as I know this fix was merged into master but was not released yet.
Maybe @davidpanderson or @romw can share some details about this.

**Comment by JuhaSointusalo** [comment]
@sirzooro Are you running the client at idle priority?

On Unixes normal users can only lower the priority of the programs they run. Only root can increase priority of programs. When programs are started they inherit their priority from their parent process.

If the client is running at idle priority then all the science apps it starts will run at idle priority too.

**Comment by sirzooro** [comment]
@JuhaSointusalo yes, I run on idle priority, and on boinc user account. This explains why wrapper could not increase priority. It would be good if it could check if priority change succeeded and print some warning to stderr if it failed.

@AenBleidd thanks for these links. I checked them and found that adding `<process_priority_special>3</process_priority_special>` fixed my issue. However this is still a workaround, it increases priority for all GPU apps what may be not desirable sometimes. So it would be nice to have dedicated tags in app_config.xml and app_info.xml.

I missed the `<process_priority_special>` tag when reading the Client configuration page - it is described together <process_priority>`. What do you think about describing them separately, or adding new line between tag names instead of comma? That would help if someone scans text quickly.
