### ISSUE TITLE
Unable to build ARM client

### ISSUE THREAD

**Issue by denravonska** [BOINC/boinc#1702]
I'm trying to build the ARM Android client from master but get the following error:

```
cd android
./build_boinc_arm.sh

...
make[2]: Leaving directory '/home/marco/dev/boinc/lib'
Making all in client
make[2]: Entering directory '/home/marco/dev/boinc/client'
  CXX      libwhetneon_a-whetstone.o
In file included from cpu_benchmark.h:37:0,
                 from whetstone.cpp:37:
/home/marco/androidarm-tc/lib/gcc/arm-linux-androideabi/4.9.x/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
  ^
Makefile:810: recipe for target 'libwhetneon_a-whetstone.o' failed
make[2]: *** [libwhetneon_a-whetstone.o] Error 1
```

I can see that some work on this was done in 7b2ca9e787a204f2a57f390bc7249bb7f9997fea but it seems to clash.

**Comment by denravonska** [comment]
I did what the compiler suggested which is to change -mfpu=vfpv3-d16 to -mfpu=neon. It worked for me on my device but the test scope was very limited.

**Comment by davidpanderson** [comment]
I can't help fix this, but I can tell you the idea: when we started Android, devices were about 50/50 between VFP and Neon for floating-point support.  We wanted the floating-point benchmark (whetstone) to use whichever was present.  So we needed the client to included versions of the benchmarks compiled for both types of device.  We did this by compiling the code into different C++ namespaces.

**Comment by ChristianBeer** [comment]
I tracked it down to 19223fd86881c98e9d7b24932e177f232becdc10 where Rom added the flags. It turns out he missed the flag to switch the correct floating-point support for the benchmark. Instead of doing what the compiler says just add `-DANDROID_VFP` to lines 25 and 25 and 26 in  android/build_boinc_arm.sh

This will build you a VFP enabled client. If you want to have a NEON enabled Client you need to add `-DANDROID_NEON` and change to `-mfpu=neon` on the same lines. VFP is more general although all newer ARM CPUs (that are powerful enough for BOINC) do have NEON which seems to be faster.

@denravonska Can you please test the changes I described and create a pull request for them if you can build the android client this way?

**Comment by denravonska** [comment]
I'll give it a go and submit a PR if it works.

**Comment by denravonska** [comment]
It seems that regardless of how you setup the build flags, client/Makefile will always build whetstone.cpp for NEON which requires the FPU flag. If all newer ARMs do have NEON, should we switch to it permanently by changing the FPU flag in build_boinc_arm.sh?

**Comment by Ferroin** [comment]
I will comment that I know of no new phones that don't have NEON, but there are still plenty of ARMv{4,5,6} systems being designed (the're getting rarer these days, but they do still exist), and there are a few very popular ARM boards that don't have NEON (dropping VFP support would for example pretty much nuke support for first and second generation Raspberry Pi's).

**Comment by ChristianBeer** [comment]
>It seems that regardless of how you setup the build flags, client/Makefile will always build whetstone.cpp for NEON which requires the FPU flag. If all newer ARMs do have NEON, should we switch to it permanently by changing the FPU flag in build_boinc_arm.sh?

Because the [client/Makefile](https://github.com/BOINC/boinc/blob/master/client/Makefile.am#L117) is building both versions at the same time it is setting `-mfpu` too. So we end up with conflicting declarations. So we can't specify `-mfpu` in android/build_boinc_arm.sh or remove it before building boinc (so it is still in effect for the toolchain). Maybe this should be added as an argument to the script. 

I haven't investigated other implications that arise from using a toolchain that is specifically built for VFP aor NEON and how this affects building science applications. The link that Rom gave states that this now tailors the toolchain to ARMv7a which is in general not what we may want.

**Comment by davidpanderson** [comment]
To repeat: we want to build whetstone.cpp twice: once with -DANDROID_NEON (and appropriate compile flags) and once with -DANDROID_VFP (and appropriate compile flags).  This will put in different C++ namespaces, so no conflicts.  See the start of whetstone.cpp

**Comment by davidpanderson** [comment]
Science apps can be built for NEON and VFP separately; the scheduler will send the appropriate one.  But for the BOINC client we need to have both.

**Comment by denravonska** [comment]
Ok, I think I know what's going on here. The automake file [tries](https://github.com/BOINC/boinc/blob/master/client/Makefile.am#L117) to append the correct build flag for each target. However, since the user's CFLAGS always overrides the automake CFLAGS, what ends up in the final makefile is something like

> $(CPPFLAGS) $(libwhetneon_a_CXXFLAGS) $(CXXFLAGS)

which causes the FPU selection from build_boinc_arm.sh (vfpv3-d16) to always be the selected one, regardless of what Makefile.am wants. Maybe someone who is more proficient with autotools can say what the proper solution here would be.

**Comment by ChristianBeer** [comment]
Maybe we can reduce the changes to `android/build_boinc_arm.sh`. Let's try something like this:
```
diff --git a/android/build_boinc_arm.sh b/android/build_boinc_arm.sh
index 3ef310a..f98d368 100755
--- a/android/build_boinc_arm.sh
+++ b/android/build_boinc_arm.sh
@@ -32,6 +32,8 @@ export PKG_CONFIG_SYSROOT_DIR=$TCSYSROOT
 ./build_androidtc_arm.sh

 if [ -n "$COMPILEBOINC" ]; then
+export CFLAGS="--sysroot=$TCSYSROOT -DANDROID -DDECLARE_TIMEZONE -Wall -I$TCINCLUDES/include -O3 -fomit-frame-pointer -fPIE -march=armv7-a"
+export CXXFLAGS="--sysroot=$TCSYSROOT -DANDROID -Wall -I$TCINCLUDES/include -funroll-loops -fexceptions -O3 -fomit-frame-pointer -fPIE -march=armv7-a"
 echo "==================building BOINC from $BOINC=========================="
 cd $BOINC
 if [ -n "$MAKECLEAN" ]; then
```
This will reset build flags to not include the problematic flags when building BOINC but it builds the toolchain with those options. So the toolchain is built for VFP but the Client should still be build for VFP and NEON. I'm just making guesses here so you should somehow test the Client that comes out of this. It's possible it segfaults during the benchmark or something along those lines.

**Comment by denravonska** [comment]
I  can build and test it but I don't think I have a non-NEON device. Can it be tested in the Android emulator perhaps?

**Comment by brevilo** [comment]
Looking into this...

**Comment by brevilo** [comment]
Dropping the explicit VFP option works fine for me. Both whetstones are built and all runs smoothly on a 4.4.2 vpf/neon device. I'm also not sure how to test this as we don't have any non-neon arm device around and I don't think that the virtual device manager can distinguish between the two.

*Anyhow, I'm going to submit a PR for this soon as I'm already preparing a larger update for those build scripts to make them more usable.*

**Comment by brevilo** [comment]
@ChristianBeer 
> The link that Rom gave states that this now tailors the toolchain to ARMv7a which is in general not what we may want.

Why not? ARMv7a is the lowest common denominator supporting VFP and NEON.

**Comment by ChristianBeer** [comment]
Building the Android Client for ARMv7a means it won't run on older ARM cpus. Also considering that PIE is also required nowadays it makes no sense to build for older hardware or Android prior to 4.1.

**Comment by brevilo** [comment]
Agreed.

**Comment by brevilo** [comment]
Fixed
