### ISSUE TITLE
Use Bootstrap for CSS

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1704]
The BOINC web code (html/inc, html/user) currently uses a mixture of Bootstrap classes (btn, text-muted, etc.) and BOINC-specific classes (about 50 of them).  The BOINC CSS files (main.css, white.css) contain definitions of both groups of classes.

I propose using only Bootstrap classes and eliminating main.css and white.css. 
Benefits:
- project web sites will be "responsive" (i.e. work well on small displays)
- projects can use Bootstrap "themes" to get custom color schemes etc.
- web sites will have a more "modern" appearance.
Disadvantages:
- projects that have developed their own CSS (e.g. gpugrid) will have to change it.

Choice of Bootstrap: there are many alternative CSS frameworks but since Bootstrap is widely used, and we're already using many of its classes, I think it's the best choice.

**Comment by ChristianBeer** [comment]
I already started the work to transform the public web UI to an (now) older bootstrap version. These are the issues I created at the time to remind me later what needs to be done.
#1334, #1335, #1336, #1337, #1338, #1339, #1340, #1341, #1342 

The main challenge at the time was to still provide the old look-and-feel and make bootstrap optional. If this is not the case anymore, it's easier for someone to pick up where I left off. It's still a lot of restructuring of code left to achieve the separation of logic and design that such a framework requires.

I can also provide the bootstrap implementation for RNA World where bootstrap is already integrated in everything but the forums.

Oh and as a final note: please make the use of Bootstrap CDN optional and not mandatory.

**Comment by davidpanderson** [comment]
Thanks; I'll look at those issues.

My plan is to change the code to use only (a fairly small set of) Bootstrap classes.  This doesn't mandate using Bootstrap CSS files; one could write one's own CSS for them, as you did for .btn etc.

**Comment by ChristianBeer** [comment]
But if you don't include the bootstrap CSS you won't get the benefits listed above. I only added support for .btn and others in main.css because of the backwards compatibility. The RNA World implementation doesn't include main.css or white.css but only the bootstrap CSS (served locally) and the CSS files that are required by the theme (which I copied from a public repository).

**Comment by grctest** [comment]
I fully support this change, I use bootstrap pretty much everywhere.

I tried to implement bootstrap on [project rain](https://github.com/grctest/project-rain-site), but it only worked on the index page - any linked page dropped bootstrap.

**Comment by davidpanderson** [comment]
I revised the BOINC web code (PHP) to use Bootstrap CSS
rather than our own ad-hoc CSS (main.css, white.css).
This is on Github in a branch named "bootstrap".
You can try it out on your project,
and see it in action on the BOINC message boards.

    The revised code uses exclusively Bootstrap classes.
    Pages with multiple columns (such as the sample home page) use Bootstrap grids to be "responsive" (i.e. to show a single column on small displays).
    I added support for a navbar with drop-down menus.  This can be fixed or not.
    You can use the standard Bootstrap CSS (black on white) or one of the many "themes" (google "bootstrap free theme"; there are many sources).  If you have your own custom CSS (based on white.css) you can still use it, though it may need tweaking.

To use the new code:

    Check out the "bootstrap" branch
    In tools/, do upgrade --web_only project
    In PROJECT/html/user, copy sample_bootstrap.min.css to bootstrap.min.css; similarly with bootstrap.min.js and jquery.min.js
    If you want to use a theme, put it in PROJECT/html/user/bootstrap.min.css
    In PROJECT/html/project, edit your project_banner() to use the navbar if you want.  Use boinc/html/project.sample/project.inc as a basis.

There are some rough edges - for example, in dark-background themes, <select> options don't display correctly.  (Anyone know how to fix this?).
Please send me comments/feedback.
I plan to merge this to master when it's stable.

-- David

**Comment by ChristianBeer** [comment]
Kudos for using a feature branch to stabilize the new feature before putting it into master. I definitely will give this a try soon.

**Comment by davidpanderson** [comment]
I'm proud of myself for learning how to make branches!

**Comment by davidpanderson** [comment]
I looked at #1335 etc.; most of them are done.  Not the stuff about grouping form items.  Does this matter?  Forms look and work OK.

**Comment by ChristianBeer** [comment]
Grouping form items allows for nicer visual effects. See: http://getbootstrap.com/components/#input-groups and http://getbootstrap.com/components/#btn-groups for examples. At least the input elements should be grouped (e.g. the `http://` before the URL text fields). I'm not so sure about grouping the buttons anymore.

**Comment by ChristianBeer** [comment]
Another point I just remembered. Did you check the [migration guide](http://getbootstrap.com/migration/) to migrate from 2.x to 3? My initial implementation was aimed at 2.7 so some of those old class names might still linger around and cause difficulties.

**Comment by ChristianBeer** [comment]
Bootstrap was implemented and is now in master. There are some issues left open.
