### ISSUE TITLE
Building and installing “BOINC Manager 7.7.0”

### ISSUE THREAD

**Issue by elfring** [BOINC/boinc#1714]
I [cloned the current Git repository](https://boinc.berkeley.edu/trac/wiki/SourceCodeGit#CloningtheGitrepository "Cloning the Git repository") on my openSUSE Tumbleweed system a moment ago. It seems that the software configuration and the corresponding build succeeded then.

```
elfring@Sonne:~/Projekte/Bau/BOINC> ~/Projekte/BOINC/lokal/configure --disable-server --disable-fcgi --enable-dynamic-client-linkage --enable-optimize --prefix=/usr/local/BOINC-ab_20161119 && make -j4
…
--- Configuring BOINC 7.7.0 (Release) ---
--- Build Components: (client manager libraries) ---
…
```

The software installation worked also to some degree. Now I wonder why the subdirectory “bin” does not contain the program files which I would usually expect from the display of the content from a package like “boinc-manager 7.6.32-1.5” here. :confused:

I would appreciate your advices for a solution.

**Comment by elfring** [comment]
I have looked at the software situation in more detail once more. I noticed then that the make variable “`CLIENTGUI_SUBDIRS`” was commented out. This happened because [a condition “`ENABLE_MANAGER`” was not met](https://github.com/BOINC/boinc/blob/0c08a4ef92d1b0c58d593221f26289451978aaf5/configure.ac#L1070 "Specification for a condition"). This result is connected with a previous call of the macro “`BOINC_OPTIONS_WXWIDGETS`”.

Now I would like to suggest the introduction of the following error message instead of deactivating a software component for a desired build variant.

```diff
diff --git a/m4/boinc_wxwidgets.m4 b/m4/boinc_wxwidgets.m4
index f5a64a1..ead1c46 100644
--- a/m4/boinc_wxwidgets.m4
+++ b/m4/boinc_wxwidgets.m4
@@ -9,7 +9,9 @@ AC_DEFUN([BOINC_OPTIONS_WXWIDGETS],[
      [])
 
    AM_OPTIONS_WXCONFIG
-     AM_PATH_WXCONFIG($1, [_ac_cv_have_wxwidgets=yes], [_ac_cv_have_wxwidgets=no])
+     AM_PATH_WXCONFIG($1,
+                      [_ac_cv_have_wxwidgets=yes],
+                      [AC_MSG_ERROR([Please choose appropriate build system settings for the wxWidgets library.])])
    AC_CACHE_CHECK([if wxWidgets works],[ac_cv_have_wxwidgets],
     [ac_cv_have_wxwidgets="${_ac_cv_have_wxwidgets}"])
    AC_CACHE_SAVE
```


I would have not overlooked an information like the following in the long configuration log output yesterday.

```
…
checking for wxWidgets version >= 3.0.0... no (version 2.8.12 is not new enough)
…
```


🔮 Are there any more configuration checks to reconsider in a similar way?

**Comment by ChristianBeer** [comment]
Please submit a Pull Request with your fix so this can be checked with Travis CI. It looks sound but the build system is fragile.

**Comment by Ageless93** [comment]
No such PR was ever made.

**Comment by ChristianBeer** [comment]
This also regularly bothers me so I tested this and send in a PR.
