### ISSUE TITLE
BOINC runs tasks with wrong priority which leads a lot failure on deadline

### ISSUE THREAD

**Issue by hailzhang** [BOINC/boinc#1717]
As you can see in the screenshot, sometimes BOINC jumps to run tasks whose has longer deadline but leave closer ones waiting, the problem is that it still tries to run those tasks whose already failed on deadline, which wasted a lot resources. 

![screen shot 2016-11-22 at 09 39 39](https://cloud.githubusercontent.com/assets/1251142/20516725/2d1876a4-b098-11e6-8e6d-9e65ae7860a1.png)

**Comment by ChristianBeer** [comment]
This is kind of expected as there can be a project defined period where late results are still accepted and validated. The Client does not know about this and still tries to run the tasks. The log message says something like "You may consider aborting this task".
