### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [BOINC/boinc#1721]
[An extra null pointer check is not needed in functions](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for null before free p?") like the following.
- [MFILE](https://github.com/BOINC/boinc/blob/a44f7ad49d47bdc66647e34bb678ba672fe1289f/lib/mfile.cpp#L45 "Destructor for MFILE")
- [SCHEDULER_REPLY](https://github.com/BOINC/boinc/blob/5c36ce25daae8532f44d81e9f4c5527bde5e0e51/client/scheduler_op.cpp#L566 "Destructor for SCHEDULER_REPLY")
- [STARFIELD::build_stars](https://github.com/BOINC/boinc/blob/365ca7960f751a501fc195670abd0acfc160f8d3/api/gutil.cpp#L466 "STARFIELD::build_stars function")

**Comment by ChristianBeer** [comment]
Can you please create a Pull request with your proposed solution and the reasoning why you've done so? I frankly don't see a reason to remove the checks because at least for `MFILE` we allocate memory in the constructor why shouldn't we free in the destructor? The other cases are similar.

**Comment by elfring** [comment]
How do you think about to [avoid redundant checks](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?")?

**Comment by ChristianBeer** [comment]
Ok, now I understand what you mean. Although the SO users say it is not strictly required if you use a standard compliant library it also creates no performance problems. If you can guarantee that no one will ever try to build BOINC with a non standards compliant C library I'm fine with removing the checks. Since you can't do that and they don't harm us now, I don't see a reason to remove them and potentially create a problem in the future.

**Comment by davidpanderson** [comment]
Let's not worry about this.  A bigger concern is making the client behave deterministically (e.g. log an error message, wait 2 seconds for the GUI to get it, then exit) on a memory alloc failure.  This could be an issue on Android.

**Comment by elfring** [comment]
* How do you think about cooperation with configuration checks like [the macro call "`AC_FUNC_MALLOC`"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Particular-Functions.html#index-AC_005fFUNC_005fMALLOC-453 "Description for AC_FUNC_MALLOC") in your build specification?
* Would you like to [reuse wrapper functions](https://stackoverflow.com/questions/262439/create-a-wrapper-function-for-malloc-and-free-in-c "Create a wrapper function for malloc and free in C") under specific circumstances?
* Can the use of smart pointers help also a bit more in the affected source files?

**Comment by ChristianBeer** [comment]
If you find a place where you think any of this would be beneficial please open a Pull Request and state why it is beneficial, someone will then decide if it goes into the repository or not.

As to your questions: I don't know and I won't research this right now maybe you can answer your own questions in a new issue and state why it would be beneficial for us to use certain macros or where to use smart pointers. Just asking question about what we think about a random feature is not the right way to start a discussion IMHO.
