### ISSUE TITLE
Checking conditions for a message display by BOINC manager

### ISSUE THREAD

**Issue by elfring** [BOINC/boinc#1723]
I have looked at [the implementation of the member function “CBOINCBaseFrame::OnAlert”](https://github.com/BOINC/boinc/blob/e6607a63402a2b4ce2d88588efa2c011ffae9b86/clientgui/BOINCBaseFrame.cpp#L244 "Update candidate: CBOINCBaseFrame::OnAlert()") once more.

1. A condition could be written a bit shorter there: `if (IsShown() && !(event.m_notification_only && pTaskbar->IsBalloonsSupported())) {`
2. I wonder about the check "`!IsShown()`" there. How should this statement ever fit when the opposite condition was checked before?

**Comment by ChristianBeer** [comment]
This seems to be a copy&paste leftover. One needs to find out what the intended purpose of the function is and adjust the whole function accordingly.

Although your version of the condition is a bit shorter it is not so clear on the first glance what it does. I rather like the current one where it is more clear.

**Comment by AenBleidd** [comment]
Any code suggestions should be sent via PRs. Closing this as 'wontfix'
