### ISSUE TITLE
Add PVS-Studio Static Code Analyzer

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#1726]
Hello.

PVS-Studio is free for open-source projects now: http://www.viva64.com/en/b/0457/
I think it will be very helpful do add a source code check by this utility.

**Comment by ChristianBeer** [comment]
We already use [Coverity Scan](https://scan.coverity.com/projects/boinc-boinc?tab=overview) as a static code analyzer from time to time. Also the way PVS-Studio is free might not be suitable for BOINC. According to there license we must add a comment to each cpp file in this repository promoting the tool. Basically they ask us to place an add in the source code. I'm not willing to support this unless the tool has some major advantages over Coverity.

I read the article why they do it the way they do it and I support that in general but I don't think it's appropriate for BOINC.
