### ISSUE TITLE
<dont_use_vbox> does not work

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#1729]
I have added `<dont_use_vbox>1</dont_use_vbox>` to my cc_config.xml and reloaded it. I checked log and found line "Config: don't use VirtualBox", so tag was recognized as expected. Unfortunately it was not respected - when I enabled work fetching for LHC@home, BOINC downloaded few vbox WUs (namely LHCb Simulation) and started them. I also checked sched_request_lhcathome.cern.ch_lhcathome.xml file and found `<virtualbox_version>5.1.6</virtualbox_version>` tag, so it looks that vbox version is reported to server as usual.

I tried to restart BOINC Client but it did not help, LHC tasks were started after BOINC Client came up.

BOINC 7.6.22 (x64)
Windows 10 Pro x64
VBox 5.1.6

Update: one of other projects complained about disk space, so I went to Options and increased limit. I also changed list of allowed apps on LHC page. After doing this I enabled getching new WUs from LHC, and this time BOINC stopped reporting to LHC that I have vbox - in logs I noticed message from server "VirtualBox is not installed". Strange.

**Comment by ChristianBeer** [comment]
If you set the option in cc_config.xml you need to restart the Client to clear the VirtualBox version. A simple reload of cc_config.xml does not suffice. The tag only controls sending the VirtualBox Version to the server. If you already have a VM task it is going to run.

**Comment by sirzooro** [comment]
Ahh, I see. Could you update the [Client configuration](https://boinc.berkeley.edu/wiki/Client_configuration) page? Now it describes this tags as "If set, don't run VirtualBox jobs + New in 7.5", so I thought that this functionality is broken.

**Comment by ChristianBeer** [comment]
@Ageless93 Can you please update the wiki? Add something like "Needs a Client restart. Does not cancel already downloaded tasks."

**Comment by Ageless93** [comment]
Done, and in other places as well.


-- Jord van der Elst.
