### ISSUE TITLE
Stop Boinc/GPU on active process

### ISSUE THREAD

**Issue by Goersch** [BOINC/boinc#1738]
Hello,

would it be possible to get options to deactivate the CPU/GPU calculation if a process is active (not if an executable is active)? The difference between what is available and what I need is:
- Today I have to select an executable within a directory. If the executable has been started, the calculation stopps -fine
- I would like to select a process (like I can do in the task manager). If this process is active, the calculation stopps.

Why do I ask for it? There were always some special processes (usually games) in the past for which I would have needed it. Now it is XBox on Windows. I have no access to the directory and I would like Boinc to stop using the GPU automatically if Xbox is running - but I can't.

Thanks!
Georg

**Comment by ChristianBeer** [comment]
You can already achieve that. If you know the name of the executable that you can't access, you can manually add this to your cc_config.xml as a separate `<exclusive_app>filename.exe</exclusive_app>` or `<exclusive_gpu_app>important.exe</exclusive_gpu_app>` BOINC will compare the name given with the current processlist and if it finds a process with this name it will act accordingly.

See: [Client_configuration](https://boinc.berkeley.edu/wiki/Client_configuration#Options) for where to find this file and how to set the options.

**Comment by Goersch** [comment]
Hello Christian,
I know the process name but not the name of the executable and the task manager also does not give a helpful executable name when showing the options. So a logic which also checks for process names would be helpful.
Georg

**Comment by ChristianBeer** [comment]
The process name should be the same as the executable name. What BOINC does is check if the configured name in cc_config.xml is part of a process name in the list of active processes.

**Comment by Goersch** [comment]
"should be the same" is not equal to "is the same" :) And in the OS I know the process name can be different from the executable name.

> What BOINC does is check if the configured name in cc_config.xml is part of a process name in the list of active processes.
Unfortunatelly this is not how it works. It looks like boinc compares with the executable name; not with the process name.

I added
<exclusive_app>notepad.exe</exclusive_app> 
to my config file and boinc stopped all calculations after starting notepad.

I changed to
<exclusive_app>notepad</exclusive_app> 
and boinc did not stop any calculation after starting notepad.

So if boinc would look at the process name it would work - but it doesn't.

**Comment by JuhaSointusalo** [comment]
Earlier you said you have no access to the Xbox directory. Why? If you can
run Xbox stuff then shouldn't you have some kind of access there?

Could you give more concrete example of what you have to deal with.
Screenshots would be nice.

When you look at the process in Task Manager's Process tab have you tried
right clicking the process and selecting either Go to details or Properties?

**Comment by Ageless93** [comment]
Wmccds.exe is the process name that will show up when you have an XBox
connected to your PC (e.g. for use with the Windows media center)
Mcrdsvc.exe is the process that will show up when you stream media from
your PC to your XBox.
It's possible that the application that runs XBox related applications is
called plainly XBoxApps.exe (on Windows 10).


-- Jord van der Elst.

**Comment by Goersch** [comment]
@JuhaSointusalo 

> Earlier you said you have no access to the Xbox directory. Why? 
The directory is called "C:\Program Files\WindowsApps". It is not accessible. I might change the "owner" (which is now "TrustedInstaller") for this directory so that my user is able to access it; but I'm not sure if this will have a bad impact on all my games. I'm even not sure if windows allows me to do it.

Unfortunately, the screenshots are in German. Anyway, in the property screenshot you can see the directory and the executable name: "Microsoft.XboxApp_24.24.20004.0_x64__8wekyb3d8bbwe". I added this to the cc_config.xml as well - without success. Boinc does not stop any calculation.

![example](https://cloud.githubusercontent.com/assets/24088528/21533285/5a0a14fa-cd59-11e6-8db8-bea3cad21a1d.PNG)

**Comment by Ageless93** [comment]
The process name is C:\Program
Files\WindowsApps\Microsoft.XboxApp_24.24.20004.0_x64__8wekyb3d8bbwe\XBoxApps.exe,
or just XBoxApp.exe

Which, translated to cc_config.xml is just:
<cc_config>
  <log_flags>
  </log_flags>
    <options>
        <exclusive_app>xboxapp.exe</exclusive_app>
        <exclusive_gpu_app>xboxapp.exe</exclusive_app>
    </options>
</cc_config>

Referencing:
https://answers.microsoft.com/en-us/windows/forum/games_windows_10/win10-xbox-app-file-path/0e05f05c-1f65-4b71-b8c1-7ac7e32f7d56

-- Jord van der Elst.

**Comment by Goersch** [comment]
:) Thanks - now it works.

But I still think it might be a good idea to implement a logic to compare against process names as well.

Shouldn't be that big change:
- add "processName" to PROCINFO in procinfo.h
- in procinfo_xxx.cpp: copy pProcesses->ProcessName to  p.processName
- a logic in app.cpp to compare processName with cc_config.exclusive_apps. So no new option/parameter necessary

**Comment by Ageless93** [comment]
Good that it works, even though I noticed a typo in my cc_config.xml
example. A broken missing tag:
<cc_config>
  <log_flags>
  </log_flags>
    <options>
        <exclusive_app>xboxapp.exe</exclusive_app>
        <exclusive_gpu_app>xboxapp.exe</exclusive_app>
    </options>
</cc_config>

Needs to be

<cc_config>
  <log_flags>
  </log_flags>
    <options>
        <exclusive_app>xboxapp.exe</exclusive_app>
        <exclusive_gpu_app>xboxapp.exe</exclusive_gpu_app>
    </options>
</cc_config>

:)


-- Jord van der Elst.
