### ISSUE TITLE
Strange run times at pogs.

### ISSUE THREAD

**Issue by adrianxw** [BOINC/boinc#1740]
Some tasks at the pogs project have strange run times. The work unit I crunched was done by another as usual, my run time is shown as 6:47, my wingman as 2:09, however, the start and end times for the wu are recorded as:

> My machine    05:07:18 to 07:22:03
> My wingman  01:04:17 to 05:23:31

Unfortunately, the task itself has disappeared from my task list, so I cannot provide a link. The people at pogs are aware I've raised the issue here.
I was asked to post this in here, so I have done.

**Comment by ChristianBeer** [comment]
I did a [first analysis](http://lists.ssl.berkeley.edu/pipermail/boinc_dev/2016-December/022401.html) when the results where still there.

TL;DR: I need some more data by the project on the extend of the problem to understand what is happening.

**Comment by adrianxw** [comment]
I've asked the POGS people to look in.

**Comment by ChristianBeer** [comment]
Project didn't respond.
