### ISSUE TITLE
Boinc 7.6.33 can not be install/update on Windows 10 

### ISSUE THREAD

**Issue by EtoKobato** [BOINC/boinc#1744]
- Using: **boinc_7.6.33_windows_x86_64.exe**.(https://boinc.berkeley.edu/dl/boinc_7.6.33_windows_x86_64.exe)
- On: Windows 10.0.14393.

1. In the installation progress, insatller said that **BOINC.msi** is **not valid** package.
2. Manual set msi package make nosense.
3. Press cancel button cause **Error 1706**.

**Comment by AenBleidd** [comment]
I installed BOINC on previous (before anniversary update)  version of windows 10. All is correct. Tomorrow will check on 10.0.14393.

**Comment by ChristianBeer** [comment]
This is a known problem for all Windows versions. Please see [Issue installing boinc_7.6.33_windows](http://boinc.berkeley.edu/dev/forum_thread.php?id=11357) for links how to resolve this.
