### ISSUE TITLE
BOINC BSODs on Win10 at 7.6.33

### ISSUE THREAD

**Issue by erickmgriffin** [BOINC/boinc#1753]
Seeing a BSOD which I thought was being caused by MilkyWay GPU s/w I now think is a BOINC issue. I have several Win10 minidumps of the issue (I hope), or whatever windows takes when it goes blue. The reason why I think its GPU is I have that set only to run when I am away from the computer and when screensaver is running, that's when it always happens.  I confirmed its nothing MilkyWay is doing specifically by disabling that project and installing a new project that uses GPU and same BSOD occurred.

CPU = AMD FX-8370 Eight-Core Processor, 4013 MHz, 4 Kern, 8 logische Prozessors
Mem = 16GB
Graphics = GeForce GTX 1080
Driver = Nvidia 376.33
OS = Microsoft Windows 10 Pro, 10.0.14393 Build 14393

Boinc = 7.6.33 (x64), wxWidgets = 3.0.1

Not sure if you get informed by Microsoft on issues related to your product or not. Please advise what you need next.  I have MS DMP files if you know how to look at those, I could zip them up and attach here.

**Comment by erickmgriffin** [comment]
Additional info from one of the dumps:
```
Microsoft (R) Windows Debugger Version 10.0.14321.1024 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Windows\Minidump\121716-15109-01.dmp]
Mini Kernel Dump File: Only registers and stack trace are available

Symbol search path is: srv*
Executable search path is: 
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ntkrnlmp.exe - 
Windows 10 Kernel Version 14393 MP (8 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Built by: 14393.576.amd64fre.rs1_release_inmarket.161208-2252
Machine Name:
Kernel base = 0xfffff802`9507c000 PsLoadedModuleList = 0xfffff802`95381060
Debug session time: Sat Dec 17 07:47:07.200 2016 (UTC - 5:00)
System Uptime: 0 days 1:05:36.922
Loading Kernel Symbols
.

Press ctrl-c (cdb, kd, ntsd) or ctrl-break (windbg) to abort symbol loads that take too long.
Run !sym noisy before .reload to track down problems loading symbols.

..............................................................
................................................................
................................................................
............
Loading User Symbols
Loading unloaded module list
........
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

Use !analyze -v to get detailed debugging information.

BugCheck 19, {d, ffffab86458bbc90, c58374bc473c3785, 968374bc473c3785}
```

**Comment by erickmgriffin** [comment]
and a more recent one:
```
Microsoft (R) Windows Debugger Version 10.0.14321.1024 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Windows\Minidump\010117-14328-01.dmp]
Mini Kernel Dump File: Only registers and stack trace are available

Symbol search path is: srv*
Executable search path is: 
Windows 10 Kernel Version 14393 MP (8 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Built by: 14393.576.amd64fre.rs1_release_inmarket.161208-2252
Machine Name:
Kernel base = 0xfffff801`c687f000 PsLoadedModuleList = 0xfffff801`c6b84060
Debug session time: Sat Dec 31 20:12:34.270 2016 (UTC - 5:00)
System Uptime: 0 days 10:22:06.991
Loading Kernel Symbols
.

Press ctrl-c (cdb, kd, ntsd) or ctrl-break (windbg) to abort symbol loads that take too long.
Run !sym noisy before .reload to track down problems loading symbols.

..............................................................
................................................................
................................................................
.................
Loading User Symbols
Loading unloaded module list
............
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

Use !analyze -v to get detailed debugging information.

BugCheck F7, {670120851010, e70774f6eb4a, ffff18f88b0914b5, 0}
```

**Comment by AenBleidd** [comment]
Hello Erick,

Could you please attach one of the dumps somewhere? I'll try to look into
it on next week.

Thanks

Best regards,
Vitalii Koshura

2017-01-08 1:44 GMT+02:00 Erick Griffin <notifications@github.com>:

**Comment by erickmgriffin** [comment]
Here is the latest kernel minidumps from January, again it could be an NVIDIA driver problem since I cannot find any common thread or issue between the dump myself.  Good luck.

[January_Kernel_Minidump.zip](https://github.com/BOINC/boinc/files/692244/January_Kernel_Minidump.zip)

**Comment by CharlieFenton** [comment]
Random system crashes when running BOINC can sometimes be caused by the GPU overheating.

Cheers,
--Charlie

**Comment by erickmgriffin** [comment]
@CharlieFenton  no its not that, I have had the Tweaker UI up at times and the GPU never gets close to overheating.  Additionally, this is a dual boot machine and when Linux Ubuntu 16.04 is running boinc using MilkyWay and the GPU, I experience no crashes, ever.

**Comment by erickmgriffin** [comment]
My next test today is re-installing BOINC and disabling GPU use.

**Comment by erickmgriffin** [comment]
I am closing this issue.  I have finally tracked down this issue to a flaky Corsair Vengeance stick of memory.  After 8 hours of memtest86 it finally threw the errors that were causing serious issues with Win10, but no so much on Linux.  In any case, I have swapped the bad memory out, retested everything, re-enabled GPU and everything appears stable for the last day or so.
