### ISSUE TITLE
why load too big tasks ?

### ISSUE THREAD

**Issue by jokjami** [BOINC/boinc#1766]
BOINC loaded today 24 january 2017 two tasks
name          time    deadline
milkeway    17 d    5 february 2017
milkeway    11 d    5 february 2017
these tasks cannot be computed before deadline

**Comment by Ageless93** [comment]
How do you want BOINC to know beforehand that tasks have an impossible
deadline?
Best report this at the project the tasks are from. Although it being
Milkyway, it's very possible these are GPU tasks or multithreaded CPU
tasks, or even singlethreaded CPU tasks that run quite a bit faster than
the initial estimate. No one knows until you let BOINC actually run them.




-- Jord van der Elst.
