### ISSUE TITLE
Broken scheduler reply for one of my hosts at Enigma@Home

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#1772]
One of my host attached to Enigma@Home stopped downloading new tasks. In log I found following error:
```
73581	Enigma@Home	2017-01-27 19:32:07	[error] Can't parse file info in scheduler reply: unexpected XML tag or syntax	
73582	Enigma@Home	2017-01-27 19:32:07	[error] No close tag in scheduler reply	
```

I checked sched_reply_www.enigmaathome.net.xml file and found that it is broken. First the `<md5_cksum>` tag was closed using `</url>`
```
<no_delete/>
    <name>00trigr.naval</name>
    <url>http://www.enigmaathome.net/download/00trigr.naval</url>
    <md5_cksum>58319aa039c5a60947547eatrigr.naval</url>
</file_info>
```
Then this part when something really bad happened:
```
<file_info>
<no_delete/>
    <name>00trigr.naval</name>
    <url>http://www.enigmaathome.net/download/00trigr.naval</url>
    <md5_cksum>58319aa039c5a60947547eatrigr.naval</url>
    <md5_cksum>58319aa039c5a609
</file_info>
<file_i_cksum>
    <nbyt
    <name>00bigr.naval</name>
    <url>http://www.enigmaathome.net/download/00bigr.naval</url>
    <md5_cksum>66ac16de94f07d23d719b5346284872d</md5_cksum>
    <nbytes>6152</nbytes>
</file_info>
```
And last thing, not encoded `&`sign:
```
<rss_feed>
<url>http://www.enigmaathome.net/notices.php?userid=137931&auth=[removed]</url>
<poll_interval>86400</poll_interval>
</rss_feed>
```

This particular host has buffer set to 3 days, E@H limited this to about 18 hours of work per CPU. When I found that something does not work here, this host had completed all tasks and was idle so it persisted for long time.

Edit: I have reported this at [E@H forum](http://www.enigmaathome.net/forum_thread.php?id=824#4248). Please take a look on this.

I have saved copy of broken scheduler reply file. I can attach it here if you want.

**Comment by ChristianBeer** [comment]
This looks like a Enigma@Home problem. To troubleshoot this in the original BOINC code I would need to know the commit from which the Enigma@Home scheduler was built and if there are any modifications.

**Comment by ChristianBeer** [comment]
The linked thread on Enigma@Home shows that more users have this problem with specific workunits. If the Enigma@Home admin wants to fix this he/she best contact the BOINC developers through the boinc_dev mailing list.
