### ISSUE TITLE
BOINC+VirtualBox bundle installer should warn that it will temporarily disconnect the host from network

### ISSUE THREAD

**Issue by JuhaSointusalo** [BOINC/boinc#1781]
VirtualBox' own installer has the following warning:

> Warning:
> 
> Network Interfaces
> 
> Installing the Oracle VM VirtualBox 5.0.32 Networking feature will reset your network connection and temporarily disconnect you from the network.
> 
> Proceed with installation now?

The bundle installer should have a similar warning so that people installing BOINC can decide if this is a good time for the network reset.

**Comment by Toby-Broom** [comment]
On the LHC project you don't need the BOINC networking components for it to work so I just dissable these options at installaion.  I don't know if other projects are the same but it could be possiable to just change the launch options for the installer.

**Comment by AenBleidd** [comment]
It is planned that the next release of BOINC will have WSL+Docker support, and thus VBox won't be a recommended part of the installation anymore.
There will still be a support of VBox tasks (if WSL is disabled/not detected), but there will be not bundled installation anymore.
