### ISSUE TITLE
Server status page inconsistency

### ISSUE THREAD

**Issue by marius311** [BOINC/boinc#1788]
Minor bug, but the server status page says "Runtime of last 100 tasks in hours" but if you look at the query:

https://github.com/BOINC/boinc/blob/479cbb61544ab6ce482349cdc74c860086309354/html/user/server_status.php#L390

its looking at all tasks, not just the last 100.

**Comment by AenBleidd** [comment]
@lfield, could you please verify if this is still an issue?

**Comment by lfield** [comment]
This still seems valid. IIUC, the stats are for the past 24 hours and not the last 100 tasks. A simple update of the test would be sufficient. @davidpanderson can you confirm? I am happy to do the PR.
