### ISSUE TITLE
Pagination Require For Per App Statistics

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#1809]
The top participants and top teams pages use pagination to only show 20 entries per page at a time. When the per app view is used, there is no pagination and all entries are displayed on a single page. This results in the page failing where there are a large number of entries.

**Comment by ChristianBeer** [comment]
I was confused for a bit what page you meant but then I found: https://github.com/BOINC/boinc/blob/master/html/user/per_app_list.php which has no paging on it.

**Comment by davidpanderson** [comment]
Fixed.

**Comment by lfield** [comment]
How was it fixed? Why was this pull request not considered or even commented upon?

https://github.com/BOINC/boinc/pull/1805
