### ISSUE TITLE
New upload directory requried for remote submission

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#1816]
The download directory should not be used for staging input files when using remote submission. At least a subdirectory should be used on the Web server so that write access can be limited. Ideally, an external storage solution such as Ceph could be used and the volunteers would download the input file directly from there. This would avoid data throughput on the Web server.

**Comment by davidpanderson** [comment]
Couple of comments:
- the remote file management system doesn't let job submitters overwrite existing files; they can only create new files.
- The remote job submission has an option (the "remote" file type) that lets you put files on any server.

**Comment by AenBleidd** [comment]
After the internal discussion with David, it was decided to not continue with that, since the implementation of the remote submission is secure enough.
