### ISSUE TITLE
"setitimer" in boinc_api.cpp may cause random seg faults on Android ARM

### ISSUE THREAD

**Issue by davidekim** [BOINC/boinc#1850]
As a workaround for our Rosetta@home scientific application we avoid the "setitimer" call in the start_worker_signals function - instead of periodically calling the signal handler, we call it when necessary using pthread_kill from the timer thread (mainly for suspend and exit). GETRUSAGE_IN_TIMER_THREAD is also defined.

**Comment by brevilo** [comment]
On 12.04.17 23:10 , David Anderson wrote (on boinc_projects):
> If you have Android apps: it turned out that the Android API was
> crashing often
> on Android versions <= 4.
> I think we have a handle on fixing this; I'll let you know in a couple
> of days.

Is this related to this issue?

**Comment by davidekim** [comment]
I think so.  But the issue also affected 5 and 6 versions, and possibly 7.

**Comment by brevilo** [comment]
What to do with this issue after the latest off-channel email exchange? Is a fix still pending or can it be closed?

**Comment by davidekim** [comment]
I think it can be closed now.
