### ISSUE TITLE
Quoting adds white lines, making a quote after text removes a white line

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#1852]
With the new bootstrap code implemented in the forum code, when quoting, one has to write their answer directly after the closing quote tag, as the quote box gives an extra white line. When quoting someone and starting the text on the next line, two white lines are added. 

Further, when posting a new quote immediately after a bit of text, that quote is squashed directly against the previous text. 

I have made a new thread at Seti (as that is using the newest code, which the BOINC forums don't even yet have) that shows the problems: https://setiathome.berkeley.edu/forum_thread.php?id=81261

**Comment by davidpanderson** [comment]
Either I don't understand this or it's been fixed already.

**Comment by AenBleidd** [comment]
Closing this as 'works for me' until there will be more detailed explanation of the issue if it still exists.

**Comment by RichardHaselgrove** [comment]
I can give you an exact description if you want, but most of us have adapted to the new design over the seven years since it was adopted without notice or explanation. The remaining problem now is the projects still using the old design, where you have to remember to type your own eol character.
