### ISSUE TITLE
Manager Notices Tab fails under mac OS 10.12.4

### ISSUE THREAD

**Issue by CharlieFenton** [BOINC/boinc#1856]
Several users have posted to the BOINC forums about a serious problem with the BOINC Manager's Notices tab in Advanced View after updating from Mac OS 10.12.3 to OS 10.12.4. When they click on the tab, it immediately opens a web browser which says it is unable to open the page, and they do not see the notices in the Manager. They all say this was working under OS 10.12.3. The thread is at https://boinc.berkeley.edu/dev/forum_thread.php?id=11540. 

The Notices code uses wzWidgets wxWebView::SetPage() API to display the notices, and on the Mac wxWebView uses the WebKit Framework. I learned that the update to OS 10.12.4 also updates the Safari web browser to version 10.1, and simultaneously updates the WebKit Framework (on which Safari is based.) 

Three of the posters have supplied the list of projects they are running.  All three are running LHC@home, einstein@home and pogs, and two are running ATLAS@home. I am unable to reproduce this because my Mac is too old to run OS 10.12.4, but one poster wrote that the URL the browser attempts to open is http:/// while another says it is http://localhost.

**Comment by brevilo** [comment]
Fixed by 96be5aca48073ad37b809461d161955fd83695d6

**Comment by ChristianBeer** [comment]
Fixed in 7.6.34 (only contains the Mac hotfix)
