### ISSUE TITLE
Computing Preferences window is too big under 1366*768 resolution

### ISSUE THREAD

**Issue by truboxl** [BOINC/boinc#1872]
![screenshot from 2017-04-18 21-00-33](https://cloud.githubusercontent.com/assets/12658589/25131992/84be3a50-247a-11e7-9ff6-4e38b80f59e1.png)

Fedora 25 Workstation
GNOME 3
BOINC version 7.6.22
wxWidgets version 3.0.2

I don't understand why recent BOINC Managers keep growing the size of that window

**Comment by AenBleidd** [comment]
Looks like some problems with Gnome 3 themes. 
I see no problems on Windows with default text size.
Do you use normal font size?

**Comment by TruboXL** [comment]
![screenshot from 2017-04-18 21-22-38](https://cloud.githubusercontent.com/assets/12658589/25132761/2d65851c-247d-11e7-851f-8b93f2885559.png)

These are the normal defaults on Fedora I guess...
