### ISSUE TITLE
Manager 7.7.2 Pre-release doesn't start automatically on Windows 10

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#1876]
Hi,

At Windows startup the Boinc manager sometimes doesn't start automatically, although the client is running in the background. If it starts, then automatically shows the Add Project window, like if I hadn't any current project. If I close it, everything is fine.

My environment:
Windows 10 Home x64 version 1607

<img width="946" alt="boinc-startup-bug-v7 7 2pre" src="https://cloud.githubusercontent.com/assets/16503773/25233966/857a8d40-25d8-11e7-8d95-4fa3819196a9.PNG">

**Comment by AenBleidd** [comment]
I have never see such issue on Windows 10.
@adamradocz
Where your BOINC is installed?
Is it installed as a service?
Does client run task apps even if Manager shows 'Add Project' window?

**Comment by adamradocz** [comment]
My BOINC is installed normally in Program Files and not as a service. Yes, if I check the task manager, the tasks are running, so it's manager issue and not client.

**Comment by Overtonesinger** [comment]
@adamradocz , Thanks for pinpointing this out as a clearly Manager-issue. It is fixable now! How to assign this to myself? :O

**Comment by AenBleidd** [comment]
@Overtonesinger You can not do this whether you have no write access: https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/

**Comment by ChristianBeer** [comment]
Thanks for the link. I was also looking for a way to assign issues to people without write access which should be possible. The doc suggests to use a team with read access to the repository so a user with write access can assign people from the read-only team to issues. That would suffice for now.

**Comment by Overtonesinger** [comment]
My new PC with Ryzen 7 1800X, Asus STRIX GAMING NV. GTX 1070, 16 GB RAM... is finally at home!
Ready to test and fix issues on weekend, Yeeeeeeeah!
Writing it to my calendar right _NOW_.

**Comment by Overtonesinger** [comment]
Issue **confirmed**! It happens on my Ryzen 1800X machine in Win10 at least once in every 10 starts of windows.
(And I have also seen at least once: the "Add Project Empty List" issue _after logging into Win10_.)

**Comment by AenBleidd** [comment]
I caught this only once on Win10 with BOINC Manager 7.6.33 and some old version of BOINC client on Raspberry PI. And this was not at start of Win10. It appears after some connection issues. Previously when I got connection errors I just saw the message which asked be whether I want to reconnect or not.
Do not know the way to reproduce this on regular basis.

**Comment by Overtonesinger** [comment]
Errata, it happens in cca **50% of cases** lately. (as the PC is full of software and startup becomes more consistent and predictable).
![boinc-on-startup-win10-creators-update](https://cloud.githubusercontent.com/assets/7014638/26282305/6b181e00-3e0f-11e7-9739-cc40d9f13e1d.png)

**Comment by seaquake** [comment]
I have the same problem on 3 computer too. :P 

Thanks for support

**Comment by seaquake** [comment]
This issue happens in 7.8.0 64bit too

**Comment by TruboXL** [comment]
Windows 7 Pro x64
BOINC 7.8.0

Got the same behaviour as with Windows 10,
reboot and then BOINC may show blank new project window...

Also notice it took a longer time to open up some Preferences window as it is communicating with BOINC Client, so race condition?

**Comment by Ageless93** [comment]
Is this still an issue with BOINC 7.8.1?

**Comment by seaquake** [comment]
Hi, sorry at the moment I'm in vacation without any computer. I will let you know asap. Thanks anyway for the support

**Comment by adamradocz** [comment]
It seems working to me.
