### ISSUE TITLE
AppVeyor for Windows build

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#1881]
Add support of AppVeyor https://www.appveyor.com/ for native windows builds using Visual Studio.

**Comment by AenBleidd** [comment]
I'm working on it now.

**Comment by ChristianBeer** [comment]
It seems this is a similar service as Travis CI just for Windows. I scanned through the terms of service and the only problematic thing I saw was that they require a special license for the code while the code is on their platform. See section 10 of https://www.appveyor.com/terms-of-service/ 

I don't see this as a big problem and I'm not sure if this counts as relicensing as they don't want the right to redistribute under a different license. But I would like to have the backing of the PMC before creating an account there. Can you write a short pitch to https://groups.google.com/forum/#!forum/boinc_admin to get the ball rolling?

**Comment by AenBleidd** [comment]
@ChristianBeer Thank you for your review. As I understand this section means that you give AppVeyor rights to build your code but for the build session only.
Yes, I will post message on this forum.

**Comment by AenBleidd** [comment]
Pull request #1886 created.
Please merge it after if will be decided to add AppVeyor support only.
Also I've added build with VS 2013 only (both 'vanilla' and 'ibm' projects) because VS 2010 Express Edition doesn't have needed headers which are used in BOINC. Also command line build with devenv 2010 very painful (we can not use msbuild because of some environment variables which are used in devenv but can not be used in msbuild.
Also I've added builds for Debug Win32 mode only because every build run ~10 minutes and builds can not run simultaneously with free account (all possible modes will require 8 build and this will takes approximately 80 minutes which is not good from my POV). In any case I've added this modes and comment them so if it will be decided to include some mode combinations this could be done very easily.

**Comment by AenBleidd** [comment]
The corresponding question is posted here: https://groups.google.com/forum/#!topic/boinc_admin/l00GLi3FaGc

**Comment by AenBleidd** [comment]
Ok. After 3 weeks on Google Groups this post has 5 messages and 9 views (at least 3 views are mine). Seems no one really read it. So what about this issue and corresponding pull request? Should I improve or fix smth?

**Comment by Ageless93** [comment]
Don't we have AppVeyor support now? Is this issue (and its PR) still needed?

**Comment by AenBleidd** [comment]
Yes, we have. This can be closed now.

Best regards,
Vitalii

Sent via Android

24 окт. 2017 г. 20:33 пользователь "Jord van der Elst" <
notifications@github.com> написал:

**Comment by Ageless93** [comment]
Closing as requested.
