### ISSUE TITLE
Duplicate accounts.

### ISSUE THREAD

**Issue by adrianxw** [BOINC/boinc#1885]
At two projects, that I am aware of, I have two accounts.

2) adrianxw 0 0.00 Denmark
3) adrianxw [Founder] 0 0.00

 and

7) adrianxw 268,033 0.43 Denmark
18) adrianxw [Founder] 0 0.00

As you can see, one is as the founder of our team and presumably created at the project initialisation, the other, created by me when I found the project and started to crunch it. This applies too both projects.

The accounts both have the same e-mail address, which I have checked and have not spelt wrongly. The accounts have, unsurprisingly, different ID numbers, but I have noticed a link between them, in that when I click Project -> Account of the Founder account, it calls the second accounts "Account" page. I am attatched to many projects, but have only noticed this happening this year, so possibly a recently introduced effect/problem.

I was asked by Ageless to post this here.

<edit>
As an aside, in the second project I quote above, it says in the editor 7 and 18, after submitting it, it says 7 and 8.
</edit>

**Comment by ChristianBeer** [comment]
Can you please state which projects are affected? We need to contact them to get to know which version of the servercode they use. A link to the profiles would also be nice so I can see when the accounts were created.

Could you also please provide a link to your team at BOINC wide teams?

**Comment by adrianxw** [comment]
The project where I am 2 and 3 is Acoustics@Home.

http://www.acousticsathome.ru/boinc/team_members.php?teamid=256&offset=0&sort_by=expavg_credit

http://www.acousticsathome.ru/boinc/show_user.php?userid=363
http://www.acousticsathome.ru/boinc/show_user.php?userid=2358

The project where I am 7 and 18 is Universe@Home.   *** NOTE: 18 not 8 ***

http://universeathome.pl/universe/team_members.php?teamid=240&offset=0&sort_by=expavg_credit

http://universeathome.pl/universe/show_user.php?userid=241
http://universeathome.pl/universe/show_user.php?userid=22564

Our team is BOINC@Denmark, I am not sure what you want from your last sentence. If that is insufficient, please can you be more specific with what you want, and where you want it from. I'm happy to do the leg work.

**Comment by ChristianBeer** [comment]
This is the BWT team: http://boinc.berkeley.edu/teams/team_display.php?teamid=340
The founder account (lower userid) is created with the email that is registered with the BWT account. This email is different than the email you used to create the second account later on.

I checked the emails. The account on BWT is using an "@get2net.dk" email and the second account is most likely using "@adrianxw.dk" (at least this is what your EaH account uses). The founder account is automatically created when the team import from BWT is run and you should have received an email about that. The second account was most likely created by yourself.

The easiest way would be to transfer foundership to your new user and rename the old one or just ignore it.

**Comment by adrianxw** [comment]
If the BWT is still using my old get2net.dk account, which I haven't used for years, then it will need changing. I doubt the get2net.dk address still exists, so if a mail was sent there to tell me, it would not have arrived. The link you put there takes me to a page, but that does not show my e-mail or, therefore, allow me to change it.

I haven't used that address for a very long time, it is somewhat suprising that this has only surfaced recently.

**Comment by adrianxw** [comment]
I tried...

 ----- The following addresses had permanent fatal errors -----
<adrian.worley@get2net.dk>

**Comment by ChristianBeer** [comment]
If you remember the password that you most likely used for this account you can try to login to BWT (using the old email address) and change the email: http://boinc.berkeley.edu/teams/login_form.php?next_url=home.php

Please also see the notes on the BWT homepage: http://boinc.berkeley.edu/teams/

If you can't login to BWT because you can't remember the password, please contact David Anderson directly. He is able to change the email so you can get a new password.

I'm closing this issue as it is not a software bug, please post follow up questions in your BOINC forum thread http://boinc.berkeley.edu/dev/forum_thread.php?id=11583
