### ISSUE TITLE
Help - Old PC

### ISSUE THREAD

**Issue by josepotatos** [BOINC/boinc#1888]
Hello everybody I am new and I have something to ask    PS: I am spanish
I have a old pc with celeron 2 GHZ 1 Core 1 gb RAM running boinc but is only running 1 task
Is there a way to run more than one task having only 1 core? The processor is old but is was so expensive 8 years ago :P

**Comment by AenBleidd** [comment]
@josepotatos Do you want to run more than 1 task simultaneously? Than this has no sense because it is more efficient to run only one task because it will be calculated faster. If you want to run more than 1 project than you can add them and let BOINC do the rest. Is it acceptable for you?

**Comment by josepotatos** [comment]
Idk so why I have like20 proyects and only running 1 task and the other says waitting to execute
https://jpst.it/YBSQ Pls watch this images and told me what is happening and how can I run more than one task 

PS: I am spanish

**Comment by adamradocz** [comment]
@josepotatos, One task can occupies one or more cores, but two task can't occupy one core, because it's not efficient. If you want to participate in more than one project, the BOINC automatically switch between the project every 60 minutes.

If you switch to advanced view, you can see more details about the projects and tasks.

**Comment by josepotatos** [comment]
Thank you and another question if boinc is at 100% why can I use xp very well,search internet...etc
I have stop computing while the pc is in use in false

**Comment by AenBleidd** [comment]
Because BOINC run tasks with low priority (you can check this in Task Manager)

**Comment by josepotatos** [comment]
The page is a mess
 Where can I find the task manager?

**Comment by AenBleidd** [comment]
Press Ctrl+Alt+Delete :)

**Comment by josepotatos** [comment]
there are 7 process the only one that is in hight(default) is called taskmgr.exe 
the others are ctfmon,boincmgr,boinccmgr,boinctray,boinc,explorer.exe,wscntfy,wuauclt
And the use of CPU is in 100%  always I think is a problem of drivers idk

**Comment by adamradocz** [comment]
The CPU usage always will be 100%, because the BOINC use the unused resources of your system. For example if your browser use 20% CPU, than the BOINC will use the rest 80%.

**Comment by josepotatos** [comment]
No no I am saying that the monitor says that I am using the 100% of CPU and I can perfectly manage office things :/ 
If I have use 100% of the CPU do I have to set it in the task manager too cuz there are a lot of boinc process

**Comment by AenBleidd** [comment]
@josepotatos BOINC have several processes to manager its work + 1 process (in your case) to run task. This task runs in low priority which means that if some other application with higher priority will require more time to execute OS will give this time to it. Other details you can read here: https://en.wikipedia.org/wiki/Computer_multitasking
It's the basics of modern computers

**Comment by AenBleidd** [comment]
@josepotatos Did you receive all answers you want? If yes - please close this issue. Further it's better to ask such question on forum: http://boinc.berkeley.edu/dev/forum_index.php

**Comment by ChristianBeer** [comment]
I think everything was answered. If you have follow up questions please ask in the forum.
