### ISSUE TITLE
Android Vagrant doesn't work

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#1896]
Hi,

I followed the steps to install the Vagrant environment, but I got an error message and it doesn't work.
I installed the VirtualBox and Vagrant in advance.
Am I missed something?

<img width="960" alt="boinc-vagrant" src="https://cloud.githubusercontent.com/assets/16503773/25626105/5c25d9b8-2f56-11e7-8852-06ba2447a9c4.PNG">
<img width="401" alt="boinc-vagrant-vm-1" src="https://cloud.githubusercontent.com/assets/16503773/25626314/1141a8fe-2f57-11e7-958e-7b67e6fb66a4.PNG">
<img width="401" alt="boinc-vagrant-vm-2" src="https://cloud.githubusercontent.com/assets/16503773/25626315/11450aee-2f57-11e7-885c-2143277e4315.PNG">

**Comment by ChristianBeer** [comment]
The error indicates that Android Studio was not properly installed which by itself could have issued an error message higher up in the cmd output. Your should check there. If you can't find anything please try again by deleting the unfinished VM using ` vagrant destroy` and then rebuilding it from scratch using `vagrant up`. This will keep the Ubuntu base VM but download the packages and Android dependencies again.

**Comment by adamradocz** [comment]
Thanks, no it works.

**Comment by ChristianBeer** [comment]
What did you do? A simple restart was not sufficient as I can see in the updated screenshots.

**Comment by adamradocz** [comment]
I used `vagrant destroy` and then `vagrant up`.
