### ISSUE TITLE
stderr output from VirtualBox is not saved when task is aborted

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#1906]
Recently I had VirtualBox task which was running for very long time. After aborting it and sending it back to server I wanted to check if there was something interesting logged to stderr, but there was only "aborted by user" message. Other successful tasks had many lines of stderr output logged, so this one also should have something more. Please retrieve stderr output from VM and send it to server in such case, it will help project developers with fixing bugs in their apps.

**Comment by ChristianBeer** [comment]
All aborted tasks behave this way. There is an option that can be set by projects to also retrieve output files if present but I don't think the stderr is part of that.

**Comment by RichardHaselgrove** [comment]
Actually, I think this was fixed (for standard tasks) by 0355298b0deac03a5f42ddb211ac055c44d130b7 - unless there's a separate issue for VBox?

**Comment by AenBleidd** [comment]
Looks like this was already fixed, so I'm closing this ticket as 'wontfix'.
If this is still an issue - please reopen.
