### ISSUE TITLE
Backup project feature

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#1908]
Hi,

I'd like a backup project feature which means, the backup project only gets WU, if the main project(s) for some reason can't send enough WU to use all of my resources.
For example:
- If the main project's server down.
- If the main project doesn't have WU for my GPU, but the backup project has.

**Comment by davidpanderson** [comment]
You can do this by giving the backup project zero resource share.

**Comment by adamradocz** [comment]
Thanks, it wasn't obvious for me, and unfortunately it's not obvious for other people as well.
For example, the WCG is going to shutdown for 2 days and some people are talking about setting up a 2nd BOINC for the same PC to get more WUs for that period, or adding an extra backup project.

**Comment by adamradocz** [comment]
The problem with this, if I suspend the main project's tasks individually in the "Tasks" panel, then the backup project automatically start to download new WUs, even though that's not what I want, because I suspended the tasks intentionally.

**Comment by Overtonesinger** [comment]
OK. Sounds *Good*!

        If the project in the BOINC MANAGER would have a *new property* called
"Resource Status"  ... and it was set to the value with this meaning: *BACKUP
PROJECT*
*   - then it would be also  very EASY to implement *the  scheduler
situations  WHEN it shall NOT react by downloading new work from the
project (or at least not immediatelly...  for EXAMPLE ONLY WHEN we forget
the manually suspended task there for  say 2 hours and thus an idle core is
sitting there for some time......*  )*


2017-05-06 20:31 GMT+02:00 Adam Radocz <notifications@github.com>:

**Comment by AenBleidd** [comment]
Maybe it would be better to let user dynamically change resource share?
Because what if I'd want to have to 'backup; projects or to set the option
to use 50% of resources to 1 project and rest 50% resources to other ~10
projects?
I think dynamic share change will be better in this case.

Best regards,
Vitalii Koshura

2017-05-06 22:20 GMT+03:00 Filip Rydlo <notifications@github.com>:

**Comment by Overtonesinger** [comment]
**Too complicated** for the ordinary users (who **NEVER ever** were developing any SW app nor did they DO any kind of IT Support).

But I _personally_ LOVE your idea of having a **second** "resource-share" number for each project... which would be **ACTIVATED ONLY IF** the project was **marked** by a checkbox saying **"This is a backup-project"**.

**Comment by adamradocz** [comment]
@Overtonesinger I like your idea, this is what I'd prefer, and it's easily understandable.

**Comment by davidpanderson** [comment]
I think the current solution works fine.  If you want to suspend the main project without getting backup projects, just suspend all computing.
