### ISSUE TITLE
BOINC Notices Not Displaying

### ISSUE THREAD

**Issue by chuckcoleman** [BOINC/boinc#1925]
Version 7.6.33, wxWidgets 3.0.0, macOS 10.12.4, 10.12.5.

The manager tells me that new notices are available.  When I click on the notices tab, it is blank. Instead, an empty web browser window opens.

**Comment by Ageless93** [comment]
Already fixed in BOINC 7.6.34 for the Mac available from https://boinc.berkeley.edu/download.php

**Comment by chuckcoleman** [comment]
This bug is probably why I didn't know about the new version. :-(
