### ISSUE TITLE
Do not allow moderators and administrators to be filtered by the user

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#1926]
At the moment it is possible for a user to put everyone else that he doesn't like on ignore, this includes moderators and administrators. When a user is on ignore his posts are filtered and he cannot private message me. I feel that moderators and administrators need always have the ability to PM the user to be able to ask them to tone down when needed. On phpBB boards it's not possible to put moderators and administrators on ignore. I think we should adopt that. 

phpBB's https://github.com/phpbb/phpbb/blob/c571d99c0f4108ec9136b601c9a57b4878597470/phpBB/includes/ucp/ucp_zebra.php lines 162 and further shows how it is done for them. Can this be adapted for BOINC?

**Comment by Aurum420** [comment]
Obnoxious moderators at SETI are the most important reason to be able to block moderators.
If an administrator needs blocking then their whole project should be avoided. I agree no blocking for administrators.
