### ISSUE TITLE
Add Project on startup

### ISSUE THREAD

**Issue by seaquake** [BOINC/boinc#1930]
Hi,
with the latest beta 7.7.2 for win64 every time the computer is restarted boinc is loaded with the "Add Project" window open, and it don't start to elaborate since the user close it.
I have try it on 3 several computers and it made all the same (just on the startup of the computer, not if you close and reopen it).
Thanks for support.
Seaquake

**Comment by adamradocz** [comment]
This looks like the same or very similar issue as #1876

**Comment by seaquake** [comment]
oh yes, sorry! i have search add project and startup and nothing come out 🗡 
i close this for duplicate ;)
