### ISSUE TITLE
Old version of VirtualBox on the Downloads for Windows page

### ISSUE THREAD

**Issue by nikolasgianna** [BOINC/boinc#1934]
The version of VirtualBox currently downloaded from the Downloads for Windows page alongside BOINC is 5.0.18.
The current version of VirtualBox for Windows is 5.1.22. Given the fact that versions prior to 5.1.0 are not actively maintained the version offered should be updated.

**Comment by Ageless93** [comment]
BOINC 7.8.3 comes with VBox 5.1.26
