### ISSUE TITLE
CPU and GPU temperature limit

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#1955]
Hi,

I'd love a feature which sets a CPU and GPU temperature limit.
I've an older laptop and sometimes turn off because of the overheating.

**Comment by adamradocz** [comment]
Sorry, I just found the #1378 and #1379.

**Comment by AenBleidd** [comment]
Hello @adamradocz,
Which OS do you use?
I have similar problem on one of my Windows notebook so I created a solution which works for me.
If you're using Windows too mail me directly and I'll share my solution with you, maybe it will help you.
