### ISSUE TITLE
On laptop with switchable graphics only onboard GPU is used, discrete GPU is not identified or used

### ISSUE THREAD

**Issue by anishmworld** [BOINC/boinc#1957]
I use BOINC on a Lenovo G50-80 with AMD Radeon M330, Windows 10 64-bit. However, I found that during computation the discrete GPU is not used at all. Only the Intel HD Graphics GPU is used. As a side effect of this, the CPU overheats and turns off the computer if GPU computing is enabled. The Intel GPU was not designed to sustain prolonged full loads.
Improve GPU detection on mobile platforms so that more computation can be done efficiently

**Comment by adamradocz** [comment]
> The Intel GPU was not designed to sustain prolonged full loads.
It's a brave statement :)! I use my Intel GPU at full load whenever my laptop is on and everything is fine.

**Comment by anishmworld** [comment]
Revised statement: .... In India, in the middle of summer without air
conditioning. 😂

**Comment by JuhaSointusalo** [comment]
Do you have computing parts of AMD GPU drivers installed?
Does clinfo list the M330? ([Download here](http://boinc.berkeley.edu/dl/clinfo.zip) if it didn't come with drivers.)
Does GPU-Z say the M330 has OpenCL available?
Just so that you know, GPU drivers that are available from Windows Update often lack computing parts. You may need to download the drivers from AMD's site.

If you do have the full driver installed then:
If your system has an option to "Run with graphics processor" or similar in Explorer is there any difference if you select the M330?

**Comment by anishmworld** [comment]
yes. The full driver is installed with OpenCL. There is no option to "Run with graphics processor" or similar, it is managed dynamically by the software, though I can manually specify apps to run on integrated or discrete GPU if I want to, except some like browsers which are locked on the integrated GPU.

**Comment by Ageless93** [comment]
Not enough information. 

Can you please post the first 30 or so lines from the start log (from Event Log, in BOINC Manager press CTRL+SHIFT+E) showing all detection an more? 
At the project of choice, did you select in the project preferences to use the AMD (ATI) GPU? Here you can also select not to use the Intel GPU. 
```
 Use CPU
 Use ATI GPU
 Use NVIDIA GPU
 Use Intel GPU
```

**Comment by JuhaSointusalo** [comment]
>
> yes. The full driver is installed with OpenCL.
>
I would still like to see what clinfo and GPU-Z has to say.

> There is no option to "Run with graphics processor" or similar, it is
> managed dynamically by the software, though I can manually specify apps to
> run on integrated or discrete GPU if I want to
>
Could you then manually specify BOINC client to run on the discrete GPU and
post Event Log messages?

**Comment by anishmworld** [comment]
I'm on the road till 7th July. Will get back to you after that. Bear with
me a bit

**Comment by AenBleidd** [comment]
@anishmworld, please provide additional information mentioned above some if you still have this issue. Thanks
