### ISSUE TITLE
Checking for new version doesn't work in development version

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#1959]
Hi,

I've boinc 7.7.2 development version, and the updater doesn't find the new 7.8.0 development version, even if I click manually on the "Check for new BOINC version" button.

**Comment by AenBleidd** [comment]
Hello Adam,

I'll try to look at it but I'm in a business trip right now so
unfortunately I'll be unavailable two next weeks.
It would be great if someone can take a look at this issue.

Thanks

Best regards,
Vitalii Koshura

2017-07-03 9:32 GMT-04:00 Adam Radocz <notifications@github.com>:

**Comment by JuhaSointusalo** [comment]
The client checks versions from
https://boinc.berkeley.edu/download_all.php?xml=1 and that page is not yet
updated to include 7.8.

**Comment by ChristianBeer** [comment]
The question is: should it work? We would need to put some extra logic into the client so it recognizes itself as a dev version and then adjusts the version check URL by adding a `&dev=1`.

**Comment by davidpanderson** [comment]
Let's stick with the status quo: "check for new versions" only reports release versions
