### ISSUE TITLE
GPU detection failed. error code 512

### ISSUE THREAD

**Issue by AnkS4** [BOINC/boinc#1972]
I'm running Manjaro with boinc 7.6.33.
I'm getting an error :
_boinc GPU detection failed.
error code 512 GPU not found._

I currently have all possible drivers installed including: bumblebee, cuda, opencl-nvidia, mesa, lib32-mesa, lib32-glibc, lib32-glib2, lib32-pango, lib32-libxi, lib32-mesa, lib32-libjpeg6-turbo, lib32-libxmu and linux411-nvidia
I've also tried: https://wiki.archlinux.org/index.php/BOINC#GPU_missing

**Comment by ChristianBeer** [comment]
What type of NVidia GPU do you have installed? Are the Manjaro cuda packages providing the needed libraries? In particular BOINC looks for `libnvidia-ml.so.1` (or `libnvidia-ml.so`) and `libcuda.so`.

You could activate the `coproc_debug` logflag and try again. The gpu detection process also writes it's own logfiles (`stdoutgpudetect` and `stderrgpudetect`) although I don't know where they are stored on Manjaro.

**Comment by AnkS4** [comment]
NVIDIA GF108M [GeForce GT 540M]

```
$ locate libnvidia-ml.so.1
/usr/lib/libnvidia-ml.so.1
/usr/lib32/libnvidia-ml.so.1
```
```
$ locate libnvidia-ml.so
/opt/cuda/lib64/stubs/libnvidia-ml.so
/usr/lib/libnvidia-ml.so
/usr/lib/libnvidia-ml.so.1
/usr/lib/libnvidia-ml.so.375.66
/usr/lib32/libnvidia-ml.so
/usr/lib32/libnvidia-ml.so.1
/usr/lib32/libnvidia-ml.so.375.66
```
```
$ locate libcuda.so
/opt/cuda/lib64/stubs/libcuda.so
/usr/lib/libcuda.so
/usr/lib/libcuda.so.1
/usr/lib/libcuda.so.375.66
/usr/lib32/libcuda.so
/usr/lib32/libcuda.so.1
/usr/lib32/libcuda.so.375.66
/usr/share/man/man7/libcuda.so.7.gz
```
coproc_debug activation returning:
**[coproc] read_coproc_info_file() returned error -108**

**Comment by ChristianBeer** [comment]
The file `read_coproc_info_file()` tries to open and fails is named `coproc_info.xml` and should be created in the data directory `/var/lib/boinc-client` (on Debian). Please check if this file is created, it might be in a different directory or not created at all as your first post suggests that the GPU detection process which creates this file fails.

**Comment by AnkS4** [comment]
coproc_info.xml

**Comment by AnkS4** [comment]
coproc_info.xml
   ```
 <coprocs>
<warning>NVIDIA drivers present but no GPUs found</warning>
<warning>ATI: libaticalrt.so: cannot open shared object file: No such file or directory</warning>
<warning>clGetPlatformIDs() failed to return any OpenCL platforms</warning>
    </coprocs>

```

**Comment by AnkS4** [comment]
/var/lib/boinc/stderrgpudetect.txt
`
`

/var/lib/boinc/stdoutgpudetect.txt
`
07-Jul-2017 17:44:32 [---] cc_config.xml not found - using defaults
07-Jul-2017 17:47:14 [---] cc_config.xml not found - using defaults
07-Jul-2017 19:04:54 [---] cc_config.xml not found - using defaults
07-Jul-2017 21:35:19 [---] cc_config.xml not found - using defaults
`

**Comment by ChristianBeer** [comment]
Is `coproc_info.xml` located in `/var/lib/boinc/` and what are the permissions?

The message inside the file suggests that a call to `cuInit()` failed which to me looks like an issue with the cuda driver/library. Unfortunately there is no output of the return code. You might want to try to compile some cuda examples and see if they work.

**Comment by AnkS4** [comment]
Yes, -rw-r--r--

**Comment by JuhaSointusalo** [comment]
How are you starting the client?

**Comment by AnkS4** [comment]
**$ boinc**

**Comment by JuhaSointusalo** [comment]
Ok. Include path in the command line.

**Comment by JuhaSointusalo** [comment]
BTW. Unless you want to use the current directory as BOINC's data directory
add "--dir /path/to/datadir" to the command line.

**Comment by AnkS4** [comment]
```
$ boinc --dir /var/lib/boinc/
15-Jul-2017 00:51:35 [---] cc_config.xml not found - using defaults
15-Jul-2017 00:51:45 Another instance of BOINC is running.
$ systemctl status boinc.service
● boinc.service - BOINC Daemon
   Loaded: loaded (/usr/lib/systemd/system/boinc.service; disabled; vendor prese
   Active: inactive (dead)
```

**Comment by AnkS4** [comment]
Starting with
`$ sudo boinc --dir /var/lib/boinc/`
But, giving same errors

**Comment by JuhaSointusalo** [comment]
When you installed the boinc package it installed BOINC as a service which
starts automatically at boot time. While you can run multiple clients at
the same time they can't share the same data directory. (Though usually
multiple clients is something you don't want.) If you don't want BOINC to
run as service you need to disable it. systemctl disable boinc.service may
work.

As for GPU detection, the client needs to be started so that the path to
the client is included: /usr/bin/boinc .

If you'd like to have BOINC run as a service and have it detect GPUs you
may need to restart it after you have logged in to the computer. When BOINC
is installed as a service it often manages to start well before GPU drivers
are loaded and causes the GPU detection to fail. You can edit the X/Wayland
init scripts to restart BOINC automatically. I don't which file that would
be in Manjaro so that's something you'll have to figure out yourself.

**Comment by AnkS4** [comment]
```
$ boinc --dir /usr/bin/boinc
chdir: Not a directory
```

**Comment by JuhaSointusalo** [comment]
Uh, no. Like this:

/usr/bin/boinc --dir /path/to/datadir

**Comment by AnkS4** [comment]
It has same result:
`$ /usr/bin/boinc --dir /var/lib/boinc/
15-Jul-2017 23:14:12 [---] cc_config.xml not found - using defaults
15-Jul-2017 23:14:22 Another instance of BOINC is running.`

**Comment by JuhaSointusalo** [comment]
The problem that made you open this ticket, GPU detection failing when
starting BOINC client from command line, is worked around by starting the
client using full path to the executable.

To sort out the rest of the problems, you need to tell what is it that you
want to do. I can't read your mind so I'm really going to need you to
explain what is it that you want to do.

Do you want the client to run as service so that it runs even when nobody
is logged in?
Do you want the client to be started automatically when the system boots up?
Do you have some specialized scenario where you really need to run more
than one copy of the client simultaneously?

**Comment by AnkS4** [comment]
I just want GPU to work on boinc projects.

**Comment by JuhaSointusalo** [comment]
The Arch Wiki page you linked to instructs to add boinc to video group:

sudo gpasswd -a boinc video

Then it suggests restarting the service:

sudo systemctl restart boinc.service

Lets try those first. If it still isn't working make sure coproc_debug is
enabled, restart the service and from BOINC's Event Log post everything
from start to "Initialization complete".

**Comment by ChristianBeer** [comment]
Manually starting boinc does not work because the package creates a boinc user account and the data directory and all files are owned by this user. Unless you added your normal user to the boinc group you don't have permissions to modify files in the datadirectory.

To achieve your goal you need to restart the service so that the correct useraccount is used to start boinc. That would explain the fopen error that the client, started with the wrong useraccount, can't read `coproc_info.xml`.

I would suggest to purge the `boinc-client` package from your computer. Make sure the `/var/lib/boinc` directory is gone and reinstall `boinc-client`. Add one project and see if you GPU is recognized. If not please post the content of `/var/lib/boinc/coproc_info.xml` again, in addition to the Event Log portion Juha suggested. Please always use `sudo systemctl stop boinc.service` and `sudo systemctl start boinc.service` (or manjaro equivalent) to control the Client. Do not start `boinc` directly as root or your own user.

**Comment by AnkS4** [comment]
Reinstalled boinc & tried restarting boinc.service:

```
$ boinccmd --join_acct_mgr https://www.grcpool.com user pwd
Operation failed: authentication error
$ sudo systemctl restart boinc.service
$ boinccmd --join_acct_mgr https://www.grcpool.com user pwd 
can't connect to local host
$ systemctl status boinc
● boinc.service - BOINC Daemon
   Loaded: loaded (/usr/lib/systemd/system/boinc.service; enabled; vendor preset
   Active: active (running) since Mon 2017-07-17 23:09:40 IST; 1min 21s ago
 Main PID: 2750 (boinc_client)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/boinc.service
           └─2750 /usr/bin/boinc_client --dir /var/lib/boinc --redirectio
```

If boincmgr started by:
```
$boincmgr
'Unable to connect to the core client' in the the status
```
Already added boinc to video group:
```
$ groups boinc
video boinc
```

Current user is also in boinc group:
```
$ id -Gn $whoami
anks disk lp wheel bumblebee network video optical storage scanner power autologin boinc docker
```

**Comment by AnkS4** [comment]
```
$ boinccmd --get_state
======== Projects ========

======== Applications ========

======== Application versions ========

======== Workunits ========

======== Tasks ========

======== Time stats ========
  now: 1500314025.152206
  on_frac: 0.978554
  connected_frac: -1.000000
  cpu_and_network_available_frac: 0.999988
  active_frac: 0.999988
  gpu_active_frac: 0.999988
  client_start_time: Mon Jul 17 23:09:40 2017

  previous_uptime: 166.692709
  session_active_duration: 830.724026
  session_gpu_active_duration: 830.724026
  total_start_time: Mon Jul 17 17:55:19 2017

  total_duration: 950.946242
  total_active_duration: 940.780239
  total_gpu_active_duration: 940.780239
```

**Comment by AnkS4** [comment]
* Simple stateful firewall: inactive
```
$ systemctl status iptables.service
● iptables.service - Packet Filtering Framework
   Loaded: loaded (/usr/lib/systemd/system/iptables.service; disabled; vendor pr
   Active: inactive (dead)
```

* Uncomplicated Firewall: inactive
 ```
#ufw status
Status: inactive
```

**Comment by AnkS4** [comment]
```
$ boinccmd --passwd 23d2e54b008650b84157abc6a4ed57fc --read_cc_config
retval 0
```

Able to open boincmgr with blank gui_rpc_auth.cfg.
But, getting failed to add project

**Comment by AnkS4** [comment]
Event Log:
```
Tue 18 Jul 2017 12:01:56 AM IST |  | cc_config.xml not found - using defaults
Tue 18 Jul 2017 12:02:07 AM IST |  | Starting BOINC client version 7.6.33 for x86_64-pc-linux-gnu
Tue 18 Jul 2017 12:02:07 AM IST |  | log flags: file_xfer, sched_ops, task
Tue 18 Jul 2017 12:02:07 AM IST |  | Libraries: libcurl/7.54.1 OpenSSL/1.1.0f zlib/1.2.11 libpsl/0.17.0 (+libicu/59.1) libssh2/1.8.0 nghttp2/1.23.1
Tue 18 Jul 2017 12:02:07 AM IST |  | Data directory: /var/lib/boinc
Tue 18 Jul 2017 12:02:07 AM IST |  | No usable GPUs found
Tue 18 Jul 2017 12:02:07 AM IST |  | Host name: xps
Tue 18 Jul 2017 12:02:07 AM IST |  | Processor: 4 GenuineIntel Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz [Family 6 Model 42 Stepping 7]
Tue 18 Jul 2017 12:02:07 AM IST |  | Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
Tue 18 Jul 2017 12:02:07 AM IST |  | OS: Linux: 4.11.10-1-MANJARO
Tue 18 Jul 2017 12:02:07 AM IST |  | Memory: 3.76 GB physical, 8.27 GB virtual
Tue 18 Jul 2017 12:02:07 AM IST |  | Disk: 908.63 GB total, 201.01 GB free
Tue 18 Jul 2017 12:02:07 AM IST |  | Local time is UTC +5 hours
Tue 18 Jul 2017 12:02:07 AM IST |  | No general preferences found - using defaults
Tue 18 Jul 2017 12:02:07 AM IST |  | Preferences:
Tue 18 Jul 2017 12:02:07 AM IST |  | max memory usage when active: 1924.78MB
Tue 18 Jul 2017 12:02:07 AM IST |  | max memory usage when idle: 3464.60MB
Tue 18 Jul 2017 12:02:07 AM IST |  | max disk usage: 200.91GB
Tue 18 Jul 2017 12:02:07 AM IST |  | don't use GPU while active
Tue 18 Jul 2017 12:02:07 AM IST |  | suspend work if non-BOINC CPU load exceeds 25%
Tue 18 Jul 2017 12:02:07 AM IST |  | (to change preferences, visit a project web site or select Preferences in the Manager)
Tue 18 Jul 2017 12:02:07 AM IST |  | gui_rpc_auth.cfg is empty - no GUI RPC password protection
Tue 18 Jul 2017 12:02:07 AM IST |  | This computer is not attached to any projects
Tue 18 Jul 2017 12:02:07 AM IST |  | Visit http://boinc.berkeley.edu for instructions
Tue 18 Jul 2017 12:02:28 AM IST |  | Re-reading cc_config.xml
Tue 18 Jul 2017 12:02:28 AM IST |  | cc_config.xml not found - using defaults
Tue 18 Jul 2017 12:02:28 AM IST |  | log flags: file_xfer, sched_ops, task
Tue 18 Jul 2017 12:04:10 AM IST |  | Fetching configuration file from https://www.grcpool.com/get_project_config.php

```

**Comment by AnkS4** [comment]
After enabling coproc_debug & restarting boinc.service:
`Tue 18 Jul 2017 12:10:04 AM IST |  | Starting BOINC client version 7.6.33 for x86_64-pc-linux-gnu
Tue 18 Jul 2017 12:10:04 AM IST |  | log flags: file_xfer, sched_ops, task, coproc_debug
Tue 18 Jul 2017 12:10:04 AM IST |  | Libraries: libcurl/7.54.1 OpenSSL/1.1.0f zlib/1.2.11 libpsl/0.17.0 (+libicu/59.1) libssh2/1.8.0 nghttp2/1.23.1
Tue 18 Jul 2017 12:10:04 AM IST |  | Data directory: /var/lib/boinc
Tue 18 Jul 2017 12:10:04 AM IST |  | [coproc] launching child process at /usr/bin/boinc_client
Tue 18 Jul 2017 12:10:04 AM IST |  | [coproc] relative to directory /
Tue 18 Jul 2017 12:10:04 AM IST |  | [coproc] with data directory /var/lib/boinc
Tue 18 Jul 2017 12:10:04 AM IST |  | [coproc] NVIDIA drivers present but no GPUs found
Tue 18 Jul 2017 12:10:04 AM IST |  | [coproc] ATI: libaticalrt.so: cannot open shared object file: No such file or directory
Tue 18 Jul 2017 12:10:04 AM IST |  | [coproc] clGetPlatformIDs() failed to return any OpenCL platforms
Tue 18 Jul 2017 12:10:04 AM IST |  | No usable GPUs found
Tue 18 Jul 2017 12:10:04 AM IST |  | Host name: xps
Tue 18 Jul 2017 12:10:04 AM IST |  | Processor: 4 GenuineIntel Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz [Family 6 Model 42 Stepping 7]
Tue 18 Jul 2017 12:10:04 AM IST |  | Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
Tue 18 Jul 2017 12:10:04 AM IST |  | OS: Linux: 4.11.10-1-MANJARO
Tue 18 Jul 2017 12:10:04 AM IST |  | Memory: 3.76 GB physical, 8.27 GB virtual
Tue 18 Jul 2017 12:10:04 AM IST |  | Disk: 908.63 GB total, 200.84 GB free
Tue 18 Jul 2017 12:10:04 AM IST |  | Local time is UTC +5 hours
Tue 18 Jul 2017 12:10:04 AM IST |  | No general preferences found - using defaults
Tue 18 Jul 2017 12:10:04 AM IST |  | Preferences:
Tue 18 Jul 2017 12:10:04 AM IST |  | max memory usage when active: 1924.78MB
Tue 18 Jul 2017 12:10:04 AM IST |  | max memory usage when idle: 3464.60MB
Tue 18 Jul 2017 12:10:04 AM IST |  | max disk usage: 200.74GB
Tue 18 Jul 2017 12:10:04 AM IST |  | don't use GPU while active
Tue 18 Jul 2017 12:10:04 AM IST |  | suspend work if non-BOINC CPU load exceeds 25%
Tue 18 Jul 2017 12:10:04 AM IST |  | (to change preferences, visit a project web site or select Preferences in the Manager)
Tue 18 Jul 2017 12:10:04 AM IST |  | gui_rpc_auth.cfg is empty - no GUI RPC password protection
Tue 18 Jul 2017 12:10:04 AM IST |  | This computer is not attached to any projects
Tue 18 Jul 2017 12:10:04 AM IST |  | Visit http://boinc.berkeley.edu for instructions
Tue 18 Jul 2017 12:10:49 AM IST |  | Fetching configuration file from https://www.grcpool.com/get_project_config.php
`

**Comment by ChristianBeer** [comment]
Please read the manual pages for `boinccmd` and `boincmgr`. It is important that those two tools are started in the data directory. In your case you need to do a `cd /var/lib/boinc` before executing commands. You also need to have read access to `gui_rpc_auth.cfg` (if it contains a password) this is usually achieved by adding your normal user to the `boinc` group.

The interesting line from your log is `NVIDIA drivers present but no GPUs found` which means that the driver has no CUDA capability. This is not a BOINC problem but one with the Nvidia driver provided by Manjaro. I found instructions to build the samples that come with the package: https://wiki.archlinux.org/index.php/GPGPU#Development You should try those first and see if they work. Of interest to use would be the output of the `deviceQuery` tool.

**Comment by AnkS4** [comment]
```
$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 30
-> unknown error
Result = FAIL
```

**Comment by AnkS4** [comment]
```
$ optirun ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GT 540M"
  CUDA Driver Version / Runtime Version          8.0 / 8.0
  CUDA Capability Major/Minor version number:    2.1
  Total amount of global memory:                 1985 MBytes (2081619968 bytes)
  ( 2) Multiprocessors, ( 48) CUDA Cores/MP:     96 CUDA Cores
  GPU Max Clock rate:                            1344 MHz (1.34 GHz)
  Memory Clock rate:                             900 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 131072 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65535), 3D=(2048, 2048, 2048)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 32768
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (65535, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = GeForce GT 540M
Result = PASS
```

**Comment by AnkS4** [comment]
But, optirun with boinc not working:
```
$ optirun boinc
18-Jul-2017 14:06:00 [---] cc_config.xml not found - using defaults
18-Jul-2017 14:06:35 [---] Starting BOINC client version 7.6.33 for x86_64-pc-linux-gnu
18-Jul-2017 14:06:35 [---] log flags: file_xfer, sched_ops, task
18-Jul-2017 14:06:35 [---] Libraries: libcurl/7.54.1 OpenSSL/1.1.0f zlib/1.2.11 libpsl/0.17.0 (+libicu/59.1) libssh2/1.8.0 nghttp2/1.23.1
18-Jul-2017 14:06:35 [---] Data directory: /home/anks
execv: No such file or directory
18-Jul-2017 14:06:35 [---] GPU detection failed. error code 512
18-Jul-2017 14:06:35 [---] No usable GPUs found
18-Jul-2017 14:06:35 [---] Creating new client state file
18-Jul-2017 14:06:35 [---] Host name: xps
18-Jul-2017 14:06:35 [---] Processor: 4 GenuineIntel Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz [Family 6 Model 42 Stepping 7]
18-Jul-2017 14:06:35 [---] Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
18-Jul-2017 14:06:35 [---] OS: Linux: 4.11.10-1-MANJARO
18-Jul-2017 14:06:35 [---] Memory: 3.76 GB physical, 8.27 GB virtual
18-Jul-2017 14:06:35 [---] Disk: 908.63 GB total, 197.79 GB free
18-Jul-2017 14:06:35 [---] Local time is UTC +5 hours
18-Jul-2017 14:06:35 [---] No general preferences found - using defaults
18-Jul-2017 14:06:35 [---] Preferences:
18-Jul-2017 14:06:35 [---]    max memory usage when active: 1924.78MB
18-Jul-2017 14:06:35 [---]    max memory usage when idle: 3464.60MB
18-Jul-2017 14:06:35 [---]    max disk usage: 197.69GB
18-Jul-2017 14:06:35 [---]    don't use GPU while active
18-Jul-2017 14:06:35 [---]    suspend work if non-BOINC CPU load exceeds 25%
18-Jul-2017 14:06:35 [---]    (to change preferences, visit a project web site or select Preferences in the Manager)
```

**Comment by ChristianBeer** [comment]
I also have an `optirun` setup and it didn't work at first. I also had other problems with optirun so I waited for a new version in Debian and sometime in the stretch testing it started to work. I don't remember the exact steps but at one time I needed to specify the ID of the discrete GPU like this `BusID "PCI:01:00:0"` in the bumblebee xorg conf. But I don't need that now and BOINC detects the GPU"
```
Thu 27 Jul 2017 08:26:09 AM CEST |  | Starting BOINC client version 7.6.33 for x86_64-pc-linux-gnu
Thu 27 Jul 2017 08:26:09 AM CEST |  | log flags: file_xfer, sched_ops, task
Thu 27 Jul 2017 08:26:09 AM CEST |  | Libraries: libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Thu 27 Jul 2017 08:26:09 AM CEST |  | Data directory: /var/lib/boinc-client
Thu 27 Jul 2017 08:26:10 AM CEST |  | CUDA: NVIDIA GPU 0: GeForce 940M (driver version 375.66, CUDA version 8.0, compute capability 5.0, 982MB, 964MB available, 863 GFLOPS peak)
Thu 27 Jul 2017 08:26:10 AM CEST |  | OpenCL: NVIDIA GPU 0: GeForce 940M (driver version 375.66, device version OpenCL 1.2 CUDA, 982MB, 964MB available, 863 GFLOPS peak)
```

**Comment by AnkS4** [comment]
Finally, optirun worked.
It may have been a kernel problem.
```
28-Jul-2017 23:22:39 [---] Starting BOINC client version 7.6.33 for x86_64-pc-linux-gnu
28-Jul-2017 23:22:39 [---] log flags: file_xfer, sched_ops, task, coproc_debug
28-Jul-2017 23:22:39 [---] Libraries: libcurl/7.54.1 OpenSSL/1.1.0f zlib/1.2.11 libpsl/0.17.0 (+libicu/59.1) libssh2/1.8.0 nghttp2/1.23.1
28-Jul-2017 23:22:39 [---] Data directory: /var/lib/boinc
28-Jul-2017 23:22:39 [---] [coproc] launching child process at /usr/bin/boinc_client
28-Jul-2017 23:22:39 [---] [coproc] relative to directory /
28-Jul-2017 23:22:39 [---] [coproc] with data directory /var/lib/boinc
28-Jul-2017 23:22:40 [---] CUDA: NVIDIA GPU 0: GeForce GT 540M (driver version 375.66, CUDA version 8.0, compute capability 2.1, 1985MB, 1969MB available, 258 GFLOPS peak)
28-Jul-2017 23:22:40 [---] OpenCL: NVIDIA GPU 0: GeForce GT 540M (driver version 375.66, device version OpenCL 1.1 CUDA, 1985MB, 1969MB available, 258 GFLOPS peak)
28-Jul-2017 23:22:40 [---] [coproc] NVIDIA library reports 1 GPU
28-Jul-2017 23:22:40 [---] [coproc] ATI: libaticalrt.so: cannot open shared object file: No such file or directory
28-Jul-2017 23:22:40 [---] Host name: xps
28-Jul-2017 23:22:40 [---] Processor: 4 GenuineIntel Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz [Family 6 Model 42 Stepping 7]
28-Jul-2017 23:22:40 [---] Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
28-Jul-2017 23:22:40 [---] OS: Linux: 4.12.3-1-MANJARO
28-Jul-2017 23:22:40 [---] Memory: 3.76 GB physical, 8.27 GB virtual
28-Jul-2017 23:22:40 [---] Disk: 908.63 GB total, 237.58 GB free
28-Jul-2017 23:22:40 [---] Local time is UTC +5 hours
28-Jul-2017 23:22:40 [---] No general preferences found - using defaults
28-Jul-2017 23:22:40 [---] Preferences:
28-Jul-2017 23:22:40 [---]    max memory usage when active: 1924.68MB
28-Jul-2017 23:22:40 [---]    max memory usage when idle: 3464.43MB
28-Jul-2017 23:22:40 [---]    max disk usage: 237.48GB
28-Jul-2017 23:22:40 [---]    don't use GPU while active
28-Jul-2017 23:22:40 [---]    suspend work if non-BOINC CPU load exceeds 25%
28-Jul-2017 23:22:40 [---]    (to change preferences, visit a project web site or select Preferences in the Manager)
28-Jul-2017 23:22:40 [---] gui_rpc_auth.cfg is empty - no GUI RPC password protection
28-Jul-2017 23:22:40 [---] This computer is not attached to any projects
28-Jul-2017 23:22:40 [---] Visit http://boinc.berkeley.edu for instructions
28-Jul-2017 23:22:40 Initialization completed
28-Jul-2017 23:22:40 [---] Suspending computation - on batteries

```
