### ISSUE TITLE
Mining cryptocurrencies for project founding

### ISSUE THREAD

**Issue by qwert95** [BOINC/boinc#1975]
Hi everyone.
I post here instead of continuing [this](https://boinc.berkeley.edu/dev/forum_thread.php?id=11727) topic on BOINC's forum.
My idea is to make project's owners to be able to send some work units with the only purpose to mine cryptocurrencies in order to self-found the project. Like pooled mining but for charity.
As I said in my original post, I have no idea if it's affordable for any project to trade cpu time with cryptocurrencies and I have no idea about how much cpu time translates in how many cryptocoins. I barely tried mining/using cryptovalues, so you're called to judge and discuss this, because I clearly have not a solid idea of what I'm talking about.

As Ageless was pointing out on the forum, CPU mining is less efficient than GPU mining.
In my opinion being efficient is something you must care about only when you are trying to make a profit from something, not when essentially you are donating, but I understand "less efficient" in this case can mean "A LOT less efficient" so we are probably talking about exclusively-gpu work units.

I'm not an experienced dev so I probably won't have the chance to help much more, but I felt like this could be game changer for projects that don't have a big/constant flow of money, so I wanted to share my idea. Now I'll leave you smart people judge :)

**Comment by ChristianBeer** [comment]
Mining cryotocurrencies is just another application a project can deploy. There is no special change needed by BOINC. In other words: this is already possible and some projects already do this.
