### ISSUE TITLE
NCI and non-NCI apps on same project

### ISSUE THREAD

**Issue by krzyszp** [BOINC/boinc#1988]
I have this problem mentioned previously but now it is more important
and I really need to solve it.

Basically, I'm trying to put both: CPU intensive and non-intensive apps
on same project but I found that if you do this, all apps in Manager are
visible as CPU intensive and non-NCI work units takes one thread for
each of it.

The problem can be easily reproduced by installing server with default
values and adding example_app and sleeper to same project - I had
created project with --test_app then added sleeper as second application
for test purposes. Obviously sleeper is marked as NCI in Ops.

I strongly suspect that problem is not in server itself but in Manager.

**Comment by AenBleidd** [comment]
I believe this is fixed in scope with #5385.
Closing this for now as 'Fixed'.
