### ISSUE TITLE
Android custom build app doesn't install

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#1989]
Hi,

I build the Android Boinc without any modification and when I try to install it to my phone it doesn't install and I get the "App not installed." error message. I uninstalled the previous version of Boinc but it didn't help.

Unknown sources is allowed.
I have a Xiaomi Redmi Note 2 and Linage OS Android 6.0.1.
I also triad the same package on a LeEco Le 2 Linage OS Android 7.1 and got the same result.

![screenshot_20170722-114538](https://user-images.githubusercontent.com/16503773/28490214-a696fae6-6ed4-11e7-9bb6-f43543757b2f.png)

**Comment by brevilo** [comment]
While we don't support custom builds it would be interesting to know which codebase (commit SHA1) you used for it.

**Comment by adamradocz** [comment]
I downloaded the master codebase that day, when I posted the issue. I tried the vagrant environment and windows environment as well. I've deleted my development environment so I can't check the logcat records.

**Comment by brevilo** [comment]
Ok, thanks. My latest builds of `master` (using the Vagrant env) are a few months old (~April) but at that time they built and worked OK on AOSP 5.1.1, AOSP 6.0.1 and OxygenOS 7.1.1.

Could you please try 981b0409d3? If that doesn't work either then it's likely to be problem at your end. If it does work you could `git-bisect` to find the commit that broke the build in `master`.

**Comment by adamradocz** [comment]
The 981b040 gives the following error:
`Error:(31, 0) Invalid release tag encountered: vboxwrapper/26198. Expression: (1 == match.size())
<a href="openFile:/home/vagrant/StudioProjects/boinc/android/BOINC/app/build.gradle">Open File</a>`

The 4700280 gets the same App not installed error message.

**Comment by brevilo** [comment]
Ok, the first one can be explained but the second one indicates there's something wrong on your build system or you might be picking the wrong apk (architecture). Run a logcat while installing the app. It should tell you why.

**Comment by adamradocz** [comment]
The logcat doesn't show any useful unfortunately:

`--------- beginning of main
gralloc_unregister_buffer:1440: ID=373781 ref=0
gralloc_register_buffer:1325: hnd=0x7f8f489300 ID=373783 fd=37 ref=1
gralloc_unregister_buffer:1440: ID=373783 ref=0
gralloc_unregister_buffer:1440: ID=373777 ref=0
gralloc_unregister_buffer:1440: ID=373779 ref=0
gralloc_unregister_buffer:1440: ID=373780 ref=0
gralloc_register_buffer:1325: hnd=0x7f8f489760 ID=373842 fd=29 ref=1
gralloc_register_buffer:1325: hnd=0x7f8f489c60 ID=373844 fd=36 ref=1
gralloc_register_buffer:1325: hnd=0x7f8f4896c0 ID=373859 fd=39 ref=1
gralloc_register_buffer:1325: hnd=0x7f8f48a700 ID=373860 fd=42 ref=1
gralloc_unregister_buffer:1440: ID=373844 ref=0
gralloc_unregister_buffer:1440: ID=373842 ref=0
gralloc_unregister_buffer:1440: ID=373860 ref=0
gralloc_unregister_buffer:1440: ID=373859 ref=0
gralloc_register_buffer:1325: hnd=0x7f8f4896c0 ID=374556 fd=25 ref=1
gralloc_register_buffer:1325: hnd=0x7f8f48a020 ID=374573 fd=36 ref=1
gralloc_register_buffer:1325: hnd=0x7f8f488220 ID=374574 fd=39 ref=1
gralloc_register_buffer:1325: hnd=0x7f8f489800 ID=374575 fd=42 ref=1
gralloc_unregister_buffer:1440: ID=374573 ref=0
gralloc_register_buffer:1325: hnd=0x7f8f48a020 ID=374576 fd=41 ref=1
gralloc_register_buffer:1325: hnd=0x7f8f489b20 ID=374577 fd=45 ref=1
`
