### ISSUE TITLE
Change default server name from boincserver.com to 127.0.0.1 ?

### ISSUE THREAD

**Issue by grctest** [BOINC/boinc#1990]
Hey,

Would it be possible to change the default servername from boincserver.com to 127.0.0.1? When set as boincserver.com it breaks the formatting of the default website view until changed. If set to 127.0.0.1 it would work fine. The domain has also been registered recently so it links offsite.

Best regards,
CM.

**Comment by marius311** [comment]
Hey, the choice of boincserver.com as the default URL is actually [boinc-server-docker](https://github.com/marius311/boinc-server-docker) specific, I'm going to open an Issue there to discuss.

**Comment by grctest** [comment]
Cool, good to know. Closed.
