### ISSUE TITLE
[Android] Hard to read texts from drop down menu

### ISSUE THREAD

**Issue by truboxl** [BOINC/boinc#2001]
While not exactly unreadable now on your screen, but I do think blue background with black texts don't work well on phone screen...

The situation is more noticeable if you use old Androids that still uses physical Menu key (replaced by Overview key in recent Androids), and the menu popups from below.

Please position the drop down menu below the panel so that the Menu button can be seen...

![screenshot_20170707-124045](https://user-images.githubusercontent.com/12658589/28827431-2571de02-7700-11e7-83b3-ea494ea78779.png)

**Comment by brevilo** [comment]
Yep, this really needs fixing as it compromises usability (it's not just a cosmetic issue).

**Comment by AenBleidd** [comment]
I believe problem with menu location is ot topical nowadays since there is no default Android menu button.
If I'm wrong an it is still an issue please open new ticket.
Issue with background menu color will be fixed in pull request mentioned below.
