### ISSUE TITLE
(Windows) GPU detection fails when started from command line

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#2029]
Previous reference https://lists.ssl.berkeley.edu/pipermail/boinc_alpha/2017-July/021908.html

If the client is started from the Windows command line with

prompt>boinc --detach_console

GPU detection fails, and any previous coproc_info.xml file is deleted.

Starting the client with

prompt>boinc.exe --detach_console

allows GPUs to be detected and used as normal.

Changing the commandLine used in

https://github.com/BOINC/boinc/blob/master/client/main.cpp#L488

to use an explicit .exe extension also solves the problem - as was found by the author of https://github.com/BOINC/boinc/blob/master/client/gpu_detect.cpp#L640 (though I prefer the idea of passing the command line here too, rather than hard-coding the executable name)

Tests reconfirmed with code as at the v7.8.1 tag.

**Comment by Ageless93** [comment]
Is PR #2036 a fix for this problem? (https://github.com/BOINC/boinc/pull/2036)

**Comment by Ageless93** [comment]
Seeing how PR#2036 was added to Master, I updated my local repository and built a new client and manager from Master. Then ran those from the command line, with `boinc --detach_console`, and got this:

```
20-Aug-2017 00:21:39 [---] Starting BOINC client version 7.8.3 for windows_x86_64 (DEBUG)
20-Aug-2017 00:21:39 [---] This a development version of BOINC and may not function properly
20-Aug-2017 00:21:39 [---] log flags: file_xfer, sched_ops, task, benchmark_debug, checkpoint_debug
20-Aug-2017 00:21:39 [---] log flags: cpu_sched, file_xfer_debug, sched_op_debug, task_debug
20-Aug-2017 00:21:39 [---] Libraries: libcurl/7.42.1 OpenSSL/1.0.2a zlib/1.2.8
20-Aug-2017 00:21:39 [---] Data directory: M:\ProgramData\BOINC
20-Aug-2017 00:21:39 [---] Running under account Ageless
20-Aug-2017 00:21:39 [---] Project for statistics_abcathome.com.xml not found - ignoring
20-Aug-2017 00:21:39 [---] Project for statistics_albert.phys.uwm.edu.xml not found - ignoring
20-Aug-2017 00:21:39 [---] Project for statistics_aqua.dwavesys.com.xml not found - ignoring
20-Aug-2017 00:21:39 [---] Project for statistics_convector.fsv.cvut.cz.xml not found - ignoring
20-Aug-2017 00:21:39 [---] Project for statistics_dnahome.cs.rpi.edu_dna.xml not found - ignoring
20-Aug-2017 00:21:39 [---] Project for statistics_www.chess960athome.org_alpha.xml not found - ignoring
20-Aug-2017 00:21:39 [---] No usable GPUs found
20-Aug-2017 00:21:39 [SETI@home] Found app_info.xml; using anonymous platform
20-Aug-2017 00:21:39 [---] app version refers to missing GPU type ATI
20-Aug-2017 00:21:39 [---] app version refers to missing GPU type ATI
20-Aug-2017 00:21:39 [---] app version refers to missing GPU type ATI
20-Aug-2017 00:21:39 [---] app version refers to missing GPU type ATI
20-Aug-2017 00:21:39 [---] app version refers to missing GPU type ATI
20-Aug-2017 00:21:39 [---] app version refers to missing GPU type ATI
20-Aug-2017 00:21:39 [---] app version refers to missing GPU type ATI
```

**Comment by RichardHaselgrove** [comment]
Oops - still broken in v7.9.0

**Comment by RichardHaselgrove** [comment]
Retested for confirmation with v7.12.1: solution working correctly. Closing / complete
