### ISSUE TITLE
Email lists are documented in two locations

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2040]
Email lists are documented in two locations https://boinc.berkeley.edu/trac/wiki/EmailLists and https://boinc.berkeley.edu/email_lists.php.  They contain some different information and google indexes them both.

This issue proposes changing https://boinc.berkeley.edu/email_lists.php to send a 301 redirect to https://boinc.berkeley.edu/trac/wiki/EmailLists to resolve this issue.

**Comment by davidpanderson** [comment]
Done.  The PHP page was ancient; where are there links to it?

**Comment by TheAspens** [comment]
Google was what pointed me to the link.  A 301 redirect will result in google updating its search index once it queries it again.

**Comment by TheAspens** [comment]
The fix that was implemented sends a 302 redirect so google will not update its search index.  I'm trying to push a branch that contains a fix that will send a 301 redirect but I'm having an issue - if someone could let me know what I'm doing wrong I would appreciate it:

`[knreed@oc7811586721 boinc]$ git push --set-upstream origin redirect_email_lists
Username for 'https://github.com': theaspens0@gmail.com
Password for 'https://theaspens0@gmail.com@github.com': 
remote: Permission to BOINC/boinc.git denied to TheAspens.
fatal: unable to access 'https://github.com/BOINC/boinc/': The requested URL returned error: 403
[knreed@oc7811586721 boinc]$ git status
# On branch redirect_email_lists
nothing to commit, working directory clean
`

**Comment by davidpanderson** [comment]
I did the 301 in the apache config file

**Comment by TheAspens** [comment]
Ah - ok.  Tx.
