### ISSUE TITLE
Daily schedules not checking hours input

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2044]
Going to Options->Computing preferences->Daily schedules, I fill in at the top option "Compute only between 13:239 and 18:555, then click OK.

The window closes, BOINC starts calculations. 
Reopening the Options->Computing preferences window, the Daily schedules value are set to 16:59 and 21:18 

The values should be checked for correct hour times (00:00 to 23:59)

**Comment by AenBleidd** [comment]
@Ageless93, I'll take a look at it too

**Comment by AenBleidd** [comment]
Fixed in #2083
