### ISSUE TITLE
Show language options in actual language, not all in English (only)

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2061]
This is a request to make the Options->Other options->Language drop down menu show the optional languages in those languages instead of all in English. Or show them in dual language. For example Deutsch (German), Nederlands (Dutch) , Français (French) etc. 

For consistency this is also needed at the web sites.

**Comment by ChristianBeer** [comment]
We already have this for the website as I just checked on boinc and Seti@Home. We just need it in the Manager.

**Comment by davidpanderson** [comment]
Also, the manager should show only languages for which translations actually exist.

**Comment by adamradocz** [comment]
Flag for each language also would be nice.

**Comment by AenBleidd** [comment]
I think flag is unnecessary.

Best regards,
Vitalii Koshura

2017-09-03 10:13 GMT+03:00 Adam Radocz <notifications@github.com>:

**Comment by BrianNixon** [comment]
PR #5176 ready for review & test.

> show them in dual language

Done, using the same format as the Web sites: _NativeName_ (_EnglishName_)
Note that the names are supplied by wxWidgets, so are outside BOINC’s control.

> show only languages for which translations actually exist

Done

> Flag for each language

Languages don’t have flags. Countries have flags. The many-to-many mapping between the two is not readily resolved in a drop-down list…

**Comment by BrianNixon** [comment]
> PR #5176 ready for review & test

Disregard that; see discussion in the PR
