### ISSUE TITLE
Change "Use ATI GPU" on project preferences to "Use AMD GPU"

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2063]
In 2006 AMD bought ATI. 
Since 2010, AMD has ceased using ATI as a brand. 
So can we please follow and change the "Use ATI GPU" in the project preferences to "Use AMD GPU"?

**Comment by SebastianoPistore** [comment]
It's TRUE! I had never thought about it, but it did not matter that everyone knows it.

Radeon/FirePro = ATI/AMD

A user who does not know what to select can look at the box on his graphics card and do not find the word "ATI", but only "AMD".

**Comment by AenBleidd** [comment]
@davidpanderson, I believe it is a ticket that could be fixed very easily, am I right?

**Comment by homersimpsons** [comment]
Hi, should all locale files be updated too, or will this be done by transifex ?
Should every ATI string be replaced by AMD or just "Use ATI GPU" (there are some like "Faking an ATI GPU", "No ATI library found.", "CAL: ATI GPU %d: %s") ?
Should code occurrences be replaced, as for example `have_ati` ?

**Comment by ChristianBeer** [comment]
The locale files are updated separately. Most important are the user facing strings (text occurring inside `_()` or `tra()` functions). Please don't change code occurrences.

**Comment by JuhaSointusalo** [comment]
"ATI" was changed to "AMD" in task list and details and in ops section in #2844.

"ATI" is practically ungreppable. There's way too many false hits so it's not possible to tell if there are more changes needed. So I'm leaving this open for now. If some "ATI" strings remained future reports must point to the exact location of the string.

**Comment by AenBleidd** [comment]
Looks like it is fixed so I'm closing it now
