### ISSUE TITLE
Change authorization text for translations

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2067]
At the moment one of the translations for BOINC-Manager.pot in Transifex says:
> You currently are not authorized to manage %s.⏎⏎To run %s as this user, please:⏎- reinstall %s answering "Yes" to the question about non-administrative users⏎ or⏎- contact your administrator to add you to the 'boinc_master' user group.

This is incorrect because the Windows installer doesn't have a "Yes" to that question, or even that question. Instead in the Windows installer one can checkmark "Allow all users on this computer to control BOINC" (see https://boinc.mundayweb.com/wiki/index.php?title=File:Install7-4-advanced.png), which is quite different from what's said in the text. 

The above happens in https://github.com/BOINC/boinc/blob/f83c2527db0be7c111ccdb042e0ba512648ecb0d/clientgui/BOINCGUIApp.cpp#L311

**Comment by Ageless93** [comment]
Going through the source code, I find another of these.
In https://github.com/BOINC/boinc/blob/f83c2527db0be7c111ccdb042e0ba512648ecb0d/sched/handle_request.cpp#L1149 it says "Unable to send work to Vista with BOINC installed in protected mode.  Please reinstall BOINC and uncheck 'Protected application execution'"

The Protected application execution part has been Service Install for all of BOINC 7. 
Also, the check only happens for Windows Vista? Not 7, 8, 8.1, or 10?

**Comment by CharlieFenton** [comment]
This string is included only in the Mac build and is used only by the Mac:
"You currently are not authorized to manage %s.⏎⏎To run %s as this user, please:⏎- reinstall %s answering "Yes" to the question about non-administrative users⏎ or⏎- contact your administrator to add you to the 'boinc_master' user group."

The string included in the Windows build is:
"You currently are not authorized to manage the client.\nPlease contact your administrator to add you to the 'boinc_users' local user group."

**Comment by Ageless93** [comment]
Ah, okay. That difference doesn't show in Transifex. 
And of course I should've seen that in the source code, a couple of lines above it. It does say there it's for the Mac. Sorry. :)

I'll close this one and move the other one to its own issue.
