### ISSUE TITLE
The server should support the Linux FHS

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#2069]
In order for the BOINC server to be packaged correctly for Linux distributions, it should support the files being located according to the [Filesystem Hierarchy Standard.](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). At the moment many commands fail as there are hard-coded assumptions regarding where file are located.

**Comment by lfield** [comment]
Here is a first attempt to package the BOINC server for CentOS 7.

http://cern.ch/lfield/boinc-server-0.0.0-0.el7.cern.x86_64.rpm

**Comment by ChristianBeer** [comment]
One physical server can host several BOINC projects (through virtual hosts or aliases) and each project can have different code versions. An example would be a low budget research institution (like Rechenkraft.net) that hosts the production project and the beta project on the same server.

How would such a scenario be addressed when switching to FHS?

**Comment by lfield** [comment]
How many projects operates this way, how many like LHC@home only deploy one project per server and where should we place the priorities? Packaging to help deployment in data centres does not have to break the project directory concept if deploying directly from source.  In any case it should be possible to support multiple projects per server using different configuration but the same code base.

**Comment by Ferroin** [comment]
The differing versions of the software part is easy, many package managers can already handle that type of thing (it's kind of mandatory for handling of Python, PERL, and many other programing languages).  Most of them require a different name for each high-level version (See for example how Debian and it's derivatives handle Python), but some have ways to handle this without separate naming (See the concept of package 'slots' used by Gentoo for an example of that).

Personally, I'd suggest at least making things such that locations aren't hard-coded.  That would probably cover about 90% of what would be needed from BOINC itself, and most of the rest could easily be handled by the package managers.

**Comment by AgentB1** [comment]
Could some examples of commands which fail, be listed?  

Also, which file locations do not comply with FHS?

**Comment by lfield** [comment]
As it is not yet packaged, none of the file locations comply with FHS. The main issue is that project directory concept does not work with the FHS.  Here is an example of a command that fails. 

```
[root@boinc-server-test ~]# /usr/libexec/boinc-server/tools/update_versions 

PHP Warning:  chdir(): No such file or directory (errno 2) in /usr/libexec/boinc-server/tools/update_versions on line 31

Warning: chdir(): No such file or directory (errno 2) in /usr/libexec/boinc-server/tools/update_versions on line 31
PHP Warning:  require_once(boinc_db.inc): failed to open stream: No such file or directory in /usr/libexec/boinc-server/tools/update_versions on line 32

Warning: require_once(boinc_db.inc): failed to open stream: No such file or directory in /usr/libexec/boinc-server/tools/update_versions on line 32
PHP Fatal error:  require_once(): Failed opening required 'boinc_db.inc' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/libexec/boinc-server/tools/update_versions on line 32

Fatal error: require_once(): Failed opening required 'boinc_db.inc' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/libexec/boinc-server/tools/update_versions on line 32
```

**Comment by lfield** [comment]
I am closing this issue as there are currently no plans to package the server code.
