### ISSUE TITLE
Windows10: While snoozed tray icon still shows BOINC works

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#2077]
OS: Windows 10 x64 Version 1607
BOINC version: 7.6.33 x64

When click 'Snooze' in pop-up menu on tray icon BOINC pauses but icon doesn't change its condition.

![p70828-165109 1](https://user-images.githubusercontent.com/3234209/29779108-3c560b50-8c1a-11e7-8ae1-61d33d74b151.jpg)

Couldn't reproduce this behavoir on another PC with the same version of Windows and BOINC.

**Comment by gopherit** [comment]
OS:  Windows 10 Pro x64 Version 1709
BOINC version:  7.8.3 x64

Cannot reproduce behavior.  Tray icon properly changes icon when right-clicking and snoozing CPU.

**Comment by AenBleidd** [comment]
Looks like this never happens again (at least in my case). So since I'm the only one who caught this once on one particular PC, I'm closing this issue.
