### ISSUE TITLE
Move BOINC website into its own repository

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2084]
The code for the BOINC website (https://boinc.berkeley.edu/) is stored in this repository.  It would make sense to refactor this code into a separate repository as it is a separate concern.

This would mean creating a repository at https://github.com/BOINC/boinc_site and moving the code from this repository under boinc/doc to that new repository (preserving history).

I am looking at the files that are included from the files under boinc/doc in order to see what other files need to be included in the move.

**Comment by AenBleidd** [comment]
Hello Kevin,
What is the reason to split repositories?
There was many discussions about this in mail threads.
Thanks

Best regards,
Vitalii Koshura

2017-08-31 18:10 GMT+03:00 Kevin Reed <notifications@github.com>:

**Comment by TheAspens** [comment]
Can you point me to the discussion on that?  I scanned the archives for boinc_project, boinc_dev and boinc_alpha and didn't see it (but I've been known miss things directly in front of me, so that doesn't mean much).

To be clear, this is not the BOINC website code (i.e. for a project), but rather the code for the BOINC website (i.e. https://boinc.berkeley.edu/).  The BOINC website is mostly independent of the code used to setup a BOINC project and thus splitting those logically different code bases makes sense (for example, the maintainers for it are different for it vs the maintainers for the rest of the BOINC software).

This will let development of the two things proceed independently and simplify things such as reviewing commit history and pull requests (for example).

**Comment by AenBleidd** [comment]
Hello Kevin,

I'll find and forward it for you. Unfortunately I can't do this from my
phone.
As for the development and maintainers, there is no such intensive
development. As you can see we have very small amount of pull requests and
most of them are open for several months. So commits are not really mixed
and any necessary information can be found easily.

P.S. Linux kernel is significantly bigger but it still has all stuff in one
repo and this works perfectly.

Best regards,
Vitalii

Sent via Android

31 авг. 2017 г. 8:53 PM пользователь "Kevin Reed" <notifications@github.com>
написал:

**Comment by AenBleidd** [comment]
@TheAspens Similar issue: #1551

**Comment by davidpanderson** [comment]
The proposal is to move the contents of /doc to a new repo - nothing else.  The contents of /doc affect only the BOINC web site, boinc.berkeley.edu.

This will mean that changes to the BOINC web site are separated from the software development process.  E.g. releasing a new client version doesn't go through the branch/pull request/review protocol.

**Comment by ChristianBeer** [comment]
Most of the questions are already answered. This split off should only include files located under `doc/`. There are dependencies to files in `html/inc` using hardcoded paths (https://github.com/BOINC/boinc/blob/master/doc/index.php#L18) but that is easily solved on the server that hosts the boinc website.

My approach would be:
- extract all commits that affect `doc/` and add them to a new repository `BOINC/boinc-site` to retain history (if possible)
- delete `doc/` from the `BOINC/boinc` repository
- clone the new `BOINC/boinc-site` repository alongside (not inside) `BOINC/boinc` on the server
- update `BOINC/boinc` repository on the server (`doc` will be deleted)
- symlink `doc/` directory to clone of `BOINC/boinc-site` (apache config might forbid that but there are options to allow it if the symlink has the correct ownership)
- now both clones can be updated/modified independently from each other
- if we identify files or functions in `BOINC/boinc` that are specific to `BOINC/boinc-site` we can still move them afterwards by going through the proper procedure

I know this could also be handled via git submodules but I consciously want to avoid that as it is an advanced git feature and wrong usage can mess up repositories badly.

The goal is as David already said to decouple changes that are needed to fix or change the BOINC website (which don't need to go through a review process) from all other changes in the BOINC repository (Client/Manager/Server/API/Apps) which need to go through a review process soon.

**Comment by grctest** [comment]
I raised the need to split the BOINC repo into many repos in the '[For the betterment of BOINC thread](https://boinc.berkeley.edu/dev/forum_thread.php?id=11736&postid=79781)':

>Modularity - The BOINC github repo is huge, if you're just wanting to setup a BOINC web server you don't need the majority of the repo's contents. If it was possible to be split into seperate repos (client, server, mobile, etc) it might be easier for users to find the files required for modification (customizing web server) or to contribute towards development (A dev forked out of frustration: https://github.com/volunode/volunode https://github.com/BOINC/boinc/issues/1633#issuecomment-252813358)

I think it's a good idea to seperate the repo where possible, for simplicity sake. Issues can be moved using: https://github-issue-mover.appspot.com/

**Comment by AenBleidd** [comment]
I think splitting the repo into many repos is redundant: several parts of
the repo must be in consistency with each other.
https://github.com/volunode/volunode is the example of such redundancy: it
is too hard to build whole application package of the exact version.
Modules that are linked with each other (physically and logically) must be
in one repo.

Best regards,
Vitalii Koshura

2017-09-04 1:00 GMT+03:00 CM <notifications@github.com>:

**Comment by ChristianBeer** [comment]
Splitting of the repo into Client/Manager/Server/Library/API indeed requires that each separate part has a proper version number so that you can establish dependencies between them and keep them working.  In some cases the linking between the components is too tight and needs to be lessened before splitting of the repo. Another obstacle is that existing dependencies and contracts between components (APIs) are not documented but need to be to ensure sustainability in the future.

But this is not part of this issue. As a kind of first step we want to split of the BOINC website which by itself uses some parts of the BOINC server code but none of the BOINC server code uses files in `doc/` which makes it an easy candidate to test how to split of parts of the main repository.

**Comment by TheAspens** [comment]
@AenBleidd - for the narrow question of splitting the BOINC website into its own repository.  Are you ok if this issue moves forward?

**Comment by AenBleidd** [comment]
Yes, I'm OK.

Best regards,
Vitalii

Sent via Android

8 сент. 2017 г. 18:09 пользователь "Kevin Reed" <notifications@github.com>
написал:

**Comment by AenBleidd** [comment]
@TheAspens, @tristanolive, @drshawnkwang, @ChristianBeer, @davidpanderson 
Gyus, I'm just curious, while we are moving website to separate repo, maybe it would be also an option to move 'drupal' to separate repo too? What do you think?
Thanks

**Comment by drshawnkwang** [comment]
The drupal code depends on the boinc code in html/inc in the same way that other parts (client, manager, server, etc.) do. Which isn't to say it couldn't be done. IMO the work wouldn't justify the result.

If there is every a long-term push to separating the code into separate repositories (**if** it can even be done as @ChristianBeer writes) then that would be the time to split off the drupal/ codebase.

**Comment by AenBleidd** [comment]
@drshawnkwang, thank you for clarification. I didn't know about this dependency.
In this case there is no reason to split it.

Thanks

**Comment by TheAspens** [comment]
Code has been merged, closing issue.
