### ISSUE TITLE
Need to be able to show reported tasks sorted by task name and date/time on Seti website

### ISSUE THREAD

**Issue by KeithMyers** [BOINC/boinc#2085]
Need to be able to show reported tasks sorted by name in ascending order along with date/time on Seti website instead of just by either date/time OR ascending order on the Tasks page.  Would make it much easier to find a suspect task so the stderr.txt output could be examined.

**Comment by RichardHaselgrove** [comment]
The current SETI task list uses the generic BOINC HTML schema. From that, an individual suspect task can be found using the task search box (remembering to include the task replication number: if that is unknown, the workunit name with _0 or _1 will always find a task in the same workunit, until purged).

At the moment, displaying task names automatically selects 'sort by name': displaying tasks IDs automatically selects 'sort by date sent'. With the search box available, sorting no longer needs to be linked to 'find a task': I would prefer this issue to be addressed by implementing generalised 'sort asc/desc by column' for all columns, as is common for list GUIs.

**Comment by KeithMyers** [comment]
Even that method would be preferable to what is current.
