### ISSUE TITLE
Configure proxy settings at install time via command line options

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#21]
**Reported by Ageless on 17 Nov 37294705 08:00 UTC**
version 4.27

Posted by: boinc 
Date: 10:14 PM 04-04-2005
would like the ability to set proxy settings during installation from the command line using .msi installation methods

Posted by: rob 
Date: 6:09 AM 04-05-2005
That might be nice... Rom? 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/21

**Comment by romw** [comment]
**Commented by romw on 2 Nov 39159105 04:26 UTC**
Punting setup bugs to 6.10.

**Comment by romw** [comment]
**Commented by romw on 22 Jun 40859071 06:13 UTC**
Setup bugs are being punted to a future release.  This work item should be completed with the new open source installer.

**Comment by AenBleidd** [comment]
This feature makes sense only when doing installation of the software on a pull of devices.
However, usually when doing that, this is done not manually but using some administrative tools (e.g. using Active Directory Group Policy).
If the installation is still done manually - then it makes more sense to prepare cc_config.xml file with all the settings that should be set by default, and put it into the BOINC Data directory after the installation. In this way not only proxy, but any settings could be configured.

Thus closing this as "won't fix".
