### ISSUE TITLE
Curl shows garbage in request headers

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2101]
When you set http_debug you sometimes get stuff like

08-Sep-2017 14:41:27 [---] [http] [ID#0] Sent header to server:
Accept-Language: en_GB
08-Sep-2017 14:41:27 [---] [http] [ID#0] Sent header to server:
08-Sep-2017 14:41:27 [---] [http] [ID#0] Sent header to server: $0I A
08-Sep-2017 14:41:27 [---] [http] [ID#0] Received header from server:
HTTP/1.1 302 Found

(or some other garbage text instead of $0I A).

I'm not sure whether the garbage text is actually being sent in the header - can someone check this?

**Comment by Ageless93** [comment]
I don't think it does. 
I've just made a wireshark capture of a scheduler & download contact at Seti, because over there the BLC tasks show _Sent header to server: the galaxy). This is not yet the full data set, which lives at Penn State, it's some test on-target/off-target observations that we're checking out_ consistently when using http_debug

But I cannot find this being sent in the Wireshark capture.

**Comment by davidpanderson** [comment]
Maybe a bug in curl.   Seems to be harmless.

**Comment by RichardHaselgrove** [comment]
Checking <http_debug> for a faulty server, I saw episodes of the same thing. The attached log file is a single scheduler contact with SETI@Home - comprising a sched request/reply pair plus 48 file downloads. You can see that the first few lines of the sched_reply file are duplicated as text into the [http] log, and later on 3 (I think) of the 48 data files are similarly displayed. These are copies of the contents of the files, not redirects: the sched_reply was parsed correctly by BOINC and acted on, and I have no reason to believe the data files were damaged.

This particular log was recorded after a deliberate downgrade to v7.6.33 (to test how long the problem has existed): I have a similar (but slightly longer) log recorded under v7.8.3. Both tests performed under Windows 7/64

[BOINC http debug contents.zip](https://github.com/BOINC/boinc/files/1616152/BOINC.http.debug.contents.zip)
