### ISSUE TITLE
Bug: client library: inconsistent terminology for intel_gpu

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#2103]
Previous reference: https://lists.ssl.berkeley.edu/pipermail/boinc_alpha/2017-August/022023.html

This problem was reported during alpha testing for the 7.8 branch. Charlie Fenton identified a probable cause, but it was never transferred into bug-tracking. The problem has been re-reported as an ongoing bug in v7.8.2

**Comment by RichardHaselgrove** [comment]
Actually, it seems to be worse than Charlie thought. There are two separate cc_config.xml handlers:

CC_CONFIG::parse_options_client in \client\log_flags.cpp
CC_CONFIG::parse_options in \lib\cc_config.cpp

Both routines say that they should be kept in sync with each other, but they haven't been. ignore_intel_gpu_dev vs. ignore_intel_dev is merely one symptom.

I've confirmed Cliff Harding's report: when ignore_intel_dev is placed manually into cc_config.xml, it works. But when cc_config.xml is updated via the GUI 'Event log options' dialog, the intel_dev line is removed. I'm about to test updating the library file (only: three occurrences) and seeing if a new build fixes it.

**Comment by RichardHaselgrove** [comment]
Yes, confirmed: changing the library file fixes Cliff's reported problem - the 'ignore' line is re-written correctly. But I'd recommend that an experienced developer re-checks the synchronisation between the two files.

**Comment by RichardHaselgrove** [comment]
Commit fa0eb5d should be good to go, but I failed to make a proper pull request.

**Comment by AenBleidd** [comment]
@RichardHaselgrove,
I guess you need to create a separate branch and make cherry-pick with the
necessary commit.

Thanks

Best regards,
Vitalii Koshura

2017-09-11 17:43 GMT+03:00 RichardHaselgrove <notifications@github.com>:

**Comment by RichardHaselgrove** [comment]
Thanks - that seems to have worked.

**Comment by RichardHaselgrove** [comment]
Issue fixed in both master and v7.8.3
