### ISSUE TITLE
Boinc 7.8.2 VirtualBox tasks are not visible in VirtualBox Manager when BOINC started from installer

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#2107]
I attached a project http://uspex-at-home.ru/prediction/
It has VirtualBox tasks only.
Application used in this project is a little buggy so when some error occurs and task is aborted VirtualBox machine still running. So before updating to 7.8.2 i used BOINC 7.6.33 and I stopped and killed abandoned VirtualBox machines by myself.
But now all launched VirtualBox tasks are not shown in VirtualBox Manager (5.1.26). I didn't reinstall it before or after updating to 7.8.2.
This issue reproduces both on Windows 7 and Windows 8.1.
As you can see from the screenshot there are at least 2 VirtualBox machines work but I have only one VIrtualBox task. So one of the VIrtualBox machines are abandoned but I can't stop it and remove because they are not visible in VirtualBox Manager (on the screenshot you can see only my machines which are stopped).
![default](https://user-images.githubusercontent.com/3234209/30253473-af383a66-968e-11e7-813b-6f8a68cbe3b7.PNG)

**Comment by AenBleidd** [comment]
Another symptom:
VirtualMachine task is running but VirtualBox Manager shows this machine as Powered Off

![untitled](https://user-images.githubusercontent.com/3234209/30272747-afb0a4a4-96fe-11e7-88b0-2748e893160a.png)

**Comment by JuhaSointusalo** [comment]
Could you check that you are running everything under the same user
account? BOINC installer has (or had) a bug that if you started BOINC from
the installer it would run under admin account.

**Comment by AenBleidd** [comment]
Yes, they are both run from the same account:
![untitled](https://user-images.githubusercontent.com/3234209/30276933-1160d772-970f-11e7-942f-e64e3a3be95e.png)

**Comment by AenBleidd** [comment]
Looks like OS restart helped. I'll keep this ticket open for some days to watch on it.

**Comment by AenBleidd** [comment]
Both OS restart and BOINC restart help.
@JuhaSointusalo you were right, it is some error when running BOINC from installer.

**Comment by AenBleidd** [comment]
Closed as a duplicate of #992
