### ISSUE TITLE
BOINC 7.8.2: Error while calculating free disc space

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#2114]
Hello.

I faces several time the same issue that task is aborted because of disc space.
But there are more than enough disc space and this option is turned off in preferences.
![default](https://user-images.githubusercontent.com/3234209/30350917-7bd06fb0-9821-11e7-8d96-a33c5fdda3ac.png)

**Comment by RichardHaselgrove** [comment]
I think you're misreading the log. The 100 MB is not likely to be the global disk requirement, but the limit for this individual task set by the project. Look at the < rsc_disk_bound > value in the < workunit > section of the task specification.

I've been discussing similar errors with Juha on the alpha mail list - https://lists.ssl.berkeley.edu/pipermail/boinc_alpha/2017-September/022120.html. He thinks that applying eaf200e to your client build should cure it (the problem is actually BOINC re-using a slot directory which hasn't been cleaned properly). I was waiting until I had time to build a client with that bugfix and test before opening an issue.

Alternatively, it could be a project error, if they are sending out tasks which require 948 MB but setting a 100 MB limit.

**Comment by AenBleidd** [comment]
This error happens with several projects not this particular one. And all
these projects have no such error before 7.8.2 so it's definitely the
problem with client.

Best regards,
Vitalii

Sent via Android

13 сент. 2017 г. 12:29 пользователь "RichardHaselgrove" <
notifications@github.com> написал:

**Comment by AenBleidd** [comment]
It looks like a critical issue for me.
Does anyone else faced it?

**Comment by AenBleidd** [comment]
@RichardHaselgrove 
I can provide any necessary information.
What do you need exactly?

Thanks

**Comment by RichardHaselgrove** [comment]
You probably need to look at:

1) the < workunit > specification for the tasks which are failing
2) the total list of file sizes in the slot directory where the task is scheduled to run - either the files specified for this job, or files left over from the previous job run in that slot.

Got to go out now, can investigate further this evening.

**Comment by AenBleidd** [comment]
The problem is that this doesn't happen instantly. So I should catch the
moment when this will happen next time.

Best regards,
Vitalii Koshura

2017-09-13 16:13 GMT+03:00 RichardHaselgrove <notifications@github.com>:

**Comment by ChristianBeer** [comment]
This looks like the project misconfigured the tasks. The log output is about the disk usage limit per task that BOINC checks not the overall disk usage limit.

**Comment by AenBleidd** [comment]
@ChristianBeer, Yes, but the problem is that this issue never happen on
7.6.33 and now appears from time to time on 7.8.2 with different projects
(e.g. SETI@home, Gerasim@home, World Community Grid, Rosetta@home). maybe
with some other also but I can't remember all of them. I am completely sure
that all this projects didn't change their configuration in one moment.

Best regards,
Vitalii Koshura

2017-09-13 18:00 GMT+03:00 Christian Beer <notifications@github.com>:

**Comment by JuhaSointusalo** [comment]
Could you enable `<cpu_sched>` and `<slot_debug>`? `<cpu_sched>` makes the logs much easier to understand and `<slot_debug>` tells if you are seeing the bug that eaf200e fixes.

With the bug fixed what you'll see is something like this:
```
11-Sep-2017 18:23:20 [---] [slot] cleaning out slots/0: handle_exited_app()
11-Sep-2017 18:23:20 [---] [slot] removed file slots/0/boinc_finish_called
11-Sep-2017 18:23:20 [---] [slot] removed file slots/0/boinc_task_state.xml
11-Sep-2017 18:23:20 [---] [slot] removed file slots/0/cudart32_50_35.dll
11-Sep-2017 18:23:20 [---] [slot] removed file slots/0/cufft32_50_35.dll
11-Sep-2017 18:23:20 [---] [slot] failed to remove file slots/0/foo.txt: Error 32
11-Sep-2017 18:23:20 [---] [slot] removed file slots/0/init_data.xml
...
11-Sep-2017 18:23:20 [---] [slot] removed file slots/0/work_unit.sah
11-Sep-2017 18:23:20 [SETI@home] Computation for task blc05_2bit_guppi_57903_48301_HIP9480_0006.25352.409.23.46.100.vlar_1 finished
11-Sep-2017 18:23:20 [---] [slot] cleaning out slots/0: get_free_slot()
11-Sep-2017 18:23:20 [---] [slot] failed to remove file slots/0/foo.txt: Error 32
11-Sep-2017 18:23:20 [SETI@home] [slot] failed to clean out dir: unlink() failed
11-Sep-2017 18:23:20 [---] [slot] cleaning out slots/4: get_free_slot()
11-Sep-2017 18:23:20 [SETI@home] [slot] assigning slot 4 to 20au08ag.22581.10706.7.34.106_1
11-Sep-2017 18:23:20 [---] [slot] removed file slots/4/init_data.xml
11-Sep-2017 18:23:20 [SETI@home] setup_file: projects/setiathome.berkeley.edu/setiathome_8.00_windows_intelx86__cuda50.exe (input)
11-Sep-2017 18:23:20 [SETI@home] [slot] linked ./../projects/setiathome.berkeley.edu/setiathome_8.00_windows_intelx86__cuda50.exe to slots/4/setiathome_8.00_windows_intelx86__cuda50.exe
11-Sep-2017 18:23:20 [SETI@home] setup_file: projects/setiathome.berkeley.edu/cudart32_50_35.dll (input)
11-Sep-2017 18:23:20 [SETI@home] [slot] linked ../../projects/setiathome.berkeley.edu/cudart32_50_35.dll to slots/4/cudart32_50_35.dll
...
11-Sep-2017 18:23:20 [SETI@home] setup_file: projects/setiathome.berkeley.edu/20au08ag.22581.10706.7.34.106_1_r989697716_0 (output)
11-Sep-2017 18:23:20 [SETI@home] [slot] linked ../../projects/setiathome.berkeley.edu/20au08ag.22581.10706.7.34.106_1_r989697716_0 to slots/4/result.sah
11-Sep-2017 18:23:20 [---] [slot] removed file slots/4/boinc_temporary_exit
11-Sep-2017 18:23:20 [SETI@home] Starting task 20au08ag.22581.10706.7.34.106_1
11-Sep-2017 18:23:20 [SETI@home] [cpu_sched] Starting task 20au08ag.22581.10706.7.34.106_1 using setiathome_v8 version 800 (cuda50) in slot 4
```
`foo.txt` was a test file locked by an external program.

I don't have logs that shows the bug but you'll know when you see it. With the bug present the client doesn't try to remove leftover files or that failing doesn't try to use another slot. The client will also tell it's *re*starting a brand new task.

**Comment by JuhaSointusalo** [comment]
Have to say, I'm rapidly beginning to see the value of opening not only a PR to fix things but also opening an accompanying issue to document what is being fixed. :)

**Comment by AenBleidd** [comment]
I think I know why this issue appears.
I have a project (prediction) that has an error: when task is terminated VM
continue to run. I do not know why this situation doesn't handled by
vboxwrapper. So maybe because of running VM and files that are in use
client has no possibility to clean slot directory.
I think that vboxwrapper should handle such situations and kill VMs

Best regards,
Vitalii Koshura

2017-09-13 18:56 GMT+03:00 Juha Sointusalo <notifications@github.com>:

**Comment by RichardHaselgrove** [comment]
That sounds like a plausible explanation. In that case, Juha's patch should force BOINC to use a new (empty) slot directory for the next task, which will allow it to run. This could mean that your computer builds up a large number of orphaned VMs, which won't be good. You should either persuade prediction to clean up its own VMs, or wrapper to forcibly kill them as you suggest.

**Comment by AenBleidd** [comment]
There are no big number of orphaned VMs (max 2) because I kill them from
time to time. But it looks like that client tries to clean slot for the
next task, this operation fails, task aborted, and then it tries to apply
next task to the same 'dirty' slot.

Best regards,
Vitalii Koshura

2017-09-13 20:43 GMT+03:00 RichardHaselgrove <notifications@github.com>:

**Comment by RichardHaselgrove** [comment]
Again, that (re-using a dirty slot) is what I'd expect from the code in the current release branch.

Using the code in master - i.e. the *next* release branch - will result in the multiplying slot directories: at least, that's the current design intention. So the app problem needs to be solved for the future.

**Comment by AenBleidd** [comment]
Agreed.
Separate question: why vboxwrapper doesn't kill VM when task is failed? I
think this situation should be handled by BOINC because the client should
work silently and with minimum user interaction, as I see it.

Best regards,
Vitalii Koshura

2017-09-13 21:47 GMT+03:00 RichardHaselgrove <notifications@github.com>:

**Comment by JuhaSointusalo** [comment]
In the screenshots in #2107 I'm not seeing vboxwrapper process anywhere and the VM names don't resemble those that vboxwrapper creates. Is this project using wrapper of their own or a modified BOINC's vboxwrapper or something else?

**Comment by AenBleidd** [comment]
![default](https://user-images.githubusercontent.com/3234209/30396681-1ce74f70-98d3-11e7-992e-f03d4faf66b9.PNG)
Those processes are here. And the VM name is normal (selected one, other are mine personal VMs)
![default](https://user-images.githubusercontent.com/3234209/30396740-4c4736fe-98d3-11e7-821e-706fd9399798.png)

**Comment by JuhaSointusalo** [comment]
Yeah. BOINC's VM wrapper is called something like `vboxwrapper_26198ab5_windows_x86_64.exe`. This is LHC's tweaked version and has `ab5` added.

vboxwrapper names the VMs something like `boinc_1121cd21863db6d`.

You also have `wrapper_26016_windows_x86_64.exe` which looks like BOINC's non-VM wrapper.

The client has some code that's supposed to kill process tree when the main process ends but it may need co-operation from the wrapper. The client might not know which processes it should kill if the wrapper doesn't tell it.

**Comment by AenBleidd** [comment]
@JuhaSointusalo, thank you for explanation. It's clear for me now. I'll
send a request to the project developers.

Best regards,
Vitalii Koshura

2017-09-13 22:50 GMT+03:00 Juha Sointusalo <notifications@github.com>:

**Comment by AenBleidd** [comment]
New log with debug flags checked:

[stdoutdae.txt](https://github.com/BOINC/boinc/files/1301024/stdoutdae.txt)

**Comment by JuhaSointusalo** [comment]
Yup, reusing slots without cleaning them.

```
13-Sep-2017 23:26:06 [prediction] Aborting task vmvasp_79_341_ud16607_0: exceeded elapsed time limit 54122.17 (600000000.00G/11086.03G)
13-Sep-2017 23:26:08 [prediction] [slot] output file slots/5/output.vdi missing, not copying
13-Sep-2017 23:26:08 [---] [slot] cleaning out slots/5: handle_exited_app()
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/boinc_lockfile
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/config.cmd
13-Sep-2017 23:26:08 [---] [slot] failed to remove file slots/5/deb_port1871322585.vdi: Error 32
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/init_data.xml
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/job.xml
13-Sep-2017 23:26:08 [---] [slot] failed to remove file slots/5/mainimage1871322585.vdi: Error 32
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/stderr.txt
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/stdout
13-Sep-2017 23:26:08 [---] [slot] failed to remove file slots/5/USPEX_1871322585/Logs/VBox.log: Error 32
13-Sep-2017 23:26:08 [---] [slot] failed to remove file slots/5/USPEX_1871322585/Logs/VBoxHardening.log: Error 32
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/USPEX_1871322585/Snapshots/2017-09-13T20-21-36-519969200Z.sav
13-Sep-2017 23:26:08 [---] [slot] failed to remove file slots/5/USPEX_1871322585/Snapshots/{25fa844f-b5ac-48ac-b38f-1339135cbb60}.vdi: Error 32
13-Sep-2017 23:26:08 [---] [slot] failed to remove file slots/5/USPEX_1871322585/Snapshots/{407ebc9a-5d4b-4dde-9db2-3f739b903f68}.vdi: Error 32
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/USPEX_1871322585/USPEX_1871322585.vbox
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/USPEX_1871322585/USPEX_1871322585.vbox-prev
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/vm-producer.cmd
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/wrapper_26016_windows_x86_64_1.16.exe
13-Sep-2017 23:26:08 [---] [cpu_sched_debug] Request CPU reschedule: application exited
13-Sep-2017 23:26:08 [prediction] Computation for task vmvasp_79_341_ud16607_0 finished
13-Sep-2017 23:26:08 [prediction] Output file vmvasp_79_341_ud16607_0_r375888279_0 for task vmvasp_79_341_ud16607_0 absent
13-Sep-2017 23:26:08 [odlk] [slot] assigning slot 5 to odlkmin_15714_1505128772.930927_0
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/init_data.xml
13-Sep-2017 23:26:08 [odlk] setup_file: projects/boinc.progger.info_odlk/odlkmin_1.0_windows_x86_64.exe (input)
13-Sep-2017 23:26:08 [odlk] [slot] linked ../../projects/boinc.progger.info_odlk/odlkmin_1.0_windows_x86_64.exe to slots/5/odlkmin_1.0_windows_x86_64.exe
13-Sep-2017 23:26:08 [odlk] setup_file: projects/boinc.progger.info_odlk/input_odlkmin_17_0002346_00002.txt (input)
13-Sep-2017 23:26:08 [odlk] setup_file: projects/boinc.progger.info_odlk/odlkmin_15714_1505128772.930927_0_r873239954_0 (output)
13-Sep-2017 23:26:08 [odlk] [slot] linked ../../projects/boinc.progger.info_odlk/odlkmin_15714_1505128772.930927_0_r873239954_0 to slots/5/output.txt
13-Sep-2017 23:26:08 [---] [slot] removed file slots/5/boinc_temporary_exit
13-Sep-2017 23:26:08 [odlk] [cpu_sched] Restarting task odlkmin_15714_1505128772.930927_0 using odlkmin version 100 in slot 5
13-Sep-2017 23:26:08 [---] [cpu_sched_debug] enforce_run_list: end
13-Sep-2017 23:26:09 [odlk] Aborting task odlkmin_15714_1505128772.930927_0: exceeded disk limit: 1114.01MB > 100.00MB
13-Sep-2017 23:26:11 [---] [slot] cleaning out slots/5: handle_exited_app()
13-Sep-2017 23:26:11 [---] [slot] removed file slots/5/boinc_lockfile
13-Sep-2017 23:26:11 [---] [slot] failed to remove file slots/5/deb_port1871322585.vdi: Error 32
13-Sep-2017 23:26:11 [---] [slot] removed file slots/5/init_data.xml
13-Sep-2017 23:26:11 [---] [slot] removed file slots/5/input.txt
13-Sep-2017 23:26:11 [---] [slot] failed to remove file slots/5/mainimage1871322585.vdi: Error 32
13-Sep-2017 23:26:11 [---] [slot] removed file slots/5/odlkmin_1.0_windows_x86_64.exe
13-Sep-2017 23:26:11 [---] [slot] removed file slots/5/output.txt
13-Sep-2017 23:26:11 [---] [slot] removed file slots/5/stderr.txt
13-Sep-2017 23:26:11 [---] [slot] failed to remove file slots/5/USPEX_1871322585/Logs/VBox.log: Error 32
13-Sep-2017 23:26:11 [---] [slot] failed to remove file slots/5/USPEX_1871322585/Logs/VBoxHardening.log: Error 32
13-Sep-2017 23:26:11 [---] [slot] failed to remove file slots/5/USPEX_1871322585/Snapshots/{25fa844f-b5ac-48ac-b38f-1339135cbb60}.vdi: Error 32
13-Sep-2017 23:26:11 [---] [slot] failed to remove file slots/5/USPEX_1871322585/Snapshots/{407ebc9a-5d4b-4dde-9db2-3f739b903f68}.vdi: Error 32
13-Sep-2017 23:26:11 [---] [cpu_sched_debug] Request CPU reschedule: application exited
13-Sep-2017 23:26:11 [odlk] Computation for task odlkmin_15714_1505128772.930927_0 finished

```

**Comment by ChristianBeer** [comment]
Juha can you check if a build from master fixes the problem? Or a release build with eaf200e applied.

**Comment by JuhaSointusalo** [comment]
@AenBleidd I think @ChristianBeer's request was for you.

**Comment by AenBleidd** [comment]
@JuhaSointusalo, @ChristianBeer Ok, I'll check this

**Comment by AenBleidd** [comment]
I checked this with 7.8.3.
Works as expected so I close this ticket.
