### ISSUE TITLE
boinc-client tasks fail with segmentation violation

### ISSUE THREAD

**Issue by jpds** [BOINC/boinc#2120]
Hello,

I run boinc-client within some Docker containers in a cluster of Kubernetes hosts, using the `laurentmalvert/docker-boinc` image. This image seems to be based on boinc version 7.4.23.

I noticed that on a Debian stretch `4.12.0-0.bpo.1-amd64` kernel host, boinc tasks are failing with:

```
<core_client_version>7.4.23</core_client_version>
<![CDATA[
<message>
process got signal 11
</message>
<stderr_txt>
SIGSEGV: segmentation violation

</stderr_txt>
]]>
```

Interestingly, the same Docker image is working fine on `4.9.0-3-amd64` host.

This is happening for me on both the SETI and World Community Grid projects.

**Comment by jpds** [comment]
I also found this thread: https://boinc.berkeley.edu/dev/forum_thread.php?id=11392 which has the following post:

```
You are most probably running Debian Stretch and recently updated to the 4.8 Kernel series. This kernel disabled a feature (for security reasons) that is used by some applications. You should post in the project forums maybe you just need to select a different application which does not use this feature.
```

**Comment by jpds** [comment]
Noticed that while the tasks are failing, boinc itself seems fine:

```
13-Sep-2017 00:40:58 [World Community Grid] Sending scheduler request: To report completed tasks.
13-Sep-2017 00:40:58 [World Community Grid] Reporting 6 completed tasks
13-Sep-2017 00:40:58 [World Community Grid] Requesting new tasks for CPU
13-Sep-2017 00:41:01 [World Community Grid] Scheduler request completed: got 6 new tasks
13-Sep-2017 00:41:03 [World Community Grid] Started download of MCM1_0136220_7092_MCM1_0136220_7092.txt
13-Sep-2017 00:41:03 [World Community Grid] Started download of ff9c6255a991c4f4309e9885f5d211e2.job
13-Sep-2017 00:41:06 [World Community Grid] Finished download of MCM1_0136220_7092_MCM1_0136220_7092.txt
13-Sep-2017 00:41:06 [World Community Grid] Finished download of ff9c6255a991c4f4309e9885f5d211e2.job
13-Sep-2017 00:41:06 [World Community Grid] Started download of 47c0db0d4c684a48fe81e71dae8f68a8.zip
13-Sep-2017 00:41:06 [World Community Grid] Started download of b62aeea23f600a298158dbc6e981f613.pdbqt
13-Sep-2017 00:41:08 [World Community Grid] Finished download of 47c0db0d4c684a48fe81e71dae8f68a8.zip
13-Sep-2017 00:41:08 [World Community Grid] Finished download of b62aeea23f600a298158dbc6e981f613.pdbqt
13-Sep-2017 00:41:08 [World Community Grid] Started download of zika.x3ufa_Saur_SplApr_PInhib_A.pdbqt
13-Sep-2017 00:41:08 [World Community Grid] Started download of b4bd13b253dfbcfd7bfc5814fd34066d.job
13-Sep-2017 00:41:11 [World Community Grid] Finished download of zika.x3ufa_Saur_SplApr_PInhib_A.pdbqt
13-Sep-2017 00:41:11 [World Community Grid] Finished download of b4bd13b253dfbcfd7bfc5814fd34066d.job
13-Sep-2017 00:41:11 [World Community Grid] Started download of 4bf616df538ce5025e9381ca5a1bcb3a.zip
13-Sep-2017 00:41:11 [World Community Grid] Started download of 094706af384ec19f4b0fee37d334aa3e.job
13-Sep-2017 00:41:13 [World Community Grid] Finished download of 4bf616df538ce5025e9381ca5a1bcb3a.zip
13-Sep-2017 00:41:13 [World Community Grid] Finished download of 094706af384ec19f4b0fee37d334aa3e.job
13-Sep-2017 00:41:13 [World Community Grid] Started download of 39f4fa7dafcb42853190ae8f02877f58.zip
13-Sep-2017 00:41:13 [World Community Grid] Started download of MCM1_0136220_8163_MCM1_0136220_8163.txt
13-Sep-2017 00:41:15 [World Community Grid] Finished download of 39f4fa7dafcb42853190ae8f02877f58.zip
13-Sep-2017 00:41:15 [World Community Grid] Finished download of MCM1_0136220_8163_MCM1_0136220_8163.txt
13-Sep-2017 00:41:15 [World Community Grid] Started download of d93f747a95963da6015d5779e133a07b.job
13-Sep-2017 00:41:15 [World Community Grid] Started download of 20aeac0966ee5d29aacc3cc21b31bda9.zip
13-Sep-2017 00:41:17 [World Community Grid] Finished download of d93f747a95963da6015d5779e133a07b.job
13-Sep-2017 00:41:17 [World Community Grid] Finished download of 20aeac0966ee5d29aacc3cc21b31bda9.zip
13-Sep-2017 00:41:17 [World Community Grid] Started download of 9a3f21a2a16f5265d50d4c5c44e8ea2c.pdbqt
13-Sep-2017 00:41:19 [World Community Grid] Finished download of 9a3f21a2a16f5265d50d4c5c44e8ea2c.pdbqt
```

I also see this in the host dmesg:

```
[11853.778586] wcgrid_zika_7.0[28432] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7fffb66baef8 ax:ffffffffff600000 si:0 di:7fffb66baf10
[12009.710147] wcgrid_fahv_vin[28799] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7ffd521b2a28 ax:ffffffffff600000 si:0 di:7ffd521b2a40
[12012.751861] wcgrid_fahv_vin[28806] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7ffd207b4928 ax:ffffffffff600000 si:0 di:7ffd207b4940
[12015.795266] wcgrid_mcm1_7.3[28812] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7ffe38c91e88 ax:ffffffffff600000 si:0 di:7ffe38c91ea0
[12015.796976] wcgrid_oet1_vin[28813] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7fffc9d34d78 ax:ffffffffff600000 si:0 di:7fffc9d34d90
[12015.804983] wcgrid_mcm1_7.3[28814] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7ffed294a958 ax:ffffffffff600000 si:0 di:7ffed294a970
[12017.831349] wcgrid_zika_7.0[28821] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7fff2f1baf18 ax:ffffffffff600000 si:0 di:7fff2f1baf30
```

**Comment by jpds** [comment]
Related:

- https://einsteinathome.org/content/vsyscall-now-disabled-latest-linux-distros
- https://lists.debian.org/debian-kernel/2017/01/msg00022.html

**Comment by jpds** [comment]
Found these on another compute node's `dmesg`:

```
[12170.726325] boinc[14151] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffe78630818 ax:ffffffffff600400 si:0 di:0
[12173.076521] boinc[14204] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffcbbd88ae8 ax:ffffffffff600400 si:0 di:0
[12188.321254] boinc[14318] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffd96145668 ax:ffffffffff600400 si:0 di:0
[12223.639865] boinc[14677] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffeeaab3728 ax:ffffffffff600400 si:0 di:0
[12226.405345] boinc[14757] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffd1e378f88 ax:ffffffffff600400 si:0 di:0
[12245.316363] boinc[14881] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffdde009798 ax:ffffffffff600400 si:0 di:0
[12272.338645] boinc[15046] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffe239bcc88 ax:ffffffffff600400 si:0 di:0
[12324.247067] boinc[15334] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffceb70e158 ax:ffffffffff600400 si:0 di:0
[12717.107365] setiathome_8.00[17379] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7ffe44bc18c8 ax:ffffffffff600000 si:0 di:7ffe44bc18e0
[13003.517345] setiathome_8.00[18616] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7ffcfdc17388 ax:ffffffffff600000 si:0 di:7ffcfdc173a0
[13004.538547] setiathome_8.00[18620] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7ffdd8a61dd8 ax:ffffffffff600000 si:0 di:7ffdd8a61df0
```

**Comment by ChristianBeer** [comment]
Your analysis is correct for kernel 4.11 and newer you need to set the kernel option `vsyscall=emulate` in order to run applications compiled with older glibc.

**Comment by AenBleidd** [comment]
As far as I understand, this is not an issue and could be closed

**Comment by AenBleidd** [comment]
@ChristianBeer, @RichardHaselgrove, could you please handle this ticket?

**Comment by RichardHaselgrove** [comment]
Sorry, not me. I don't have the necessary Linux knowledge.

**Comment by jpds** [comment]
I don't think this should be closed - if tasks are failing, the client should log those and let admins know rather than silently fail.

**Comment by RichardHaselgrove** [comment]
Well, according to the opening post, the clients are reporting failures with "process got signal 11". Admittedly, that's a generic error, rather than specific advice to the project to re-compile the application with "the kernel option vsyscall=emulate". Since WCG is named, perhaps @TheAspens or one of his colleagues could comment if signal 11 is still a problem for any of their applications?

**Comment by jpds** [comment]
@RichardHaselgrove Sorry, I forgot to clarify in the original post that that's what I saw in the web UI for those projects, not on the worker hosts themselves.

**Comment by RichardHaselgrove** [comment]
In general, I'm in favour of a general policy of logging error numbers in the Event Log when tasks fail, but only a tiny minority of volunteers would know how to handle those, and to use them to distinguish between a client error (which might require maintenance of the machine under their control) and an application error (which requires attention by the project which supplied the application). In this case, when the signal 11 is visible on the web portal, it can also be retrieved from the database by the project administrators - they were the ones who needed to understand and act on it.

In addition to this discussion, notification was also sent to all projects via the mailing list:

https://lists.ssl.berkeley.edu/mailman/private/boinc_projects/2016-November/011929.html
https://lists.ssl.berkeley.edu/mailman/private/boinc_projects/2017-January/012007.html

(fortunately the problem arose while we were keeping archives). The thread title, "new Debian kernel 4.8 leads to segfaults in science apps", should have caught the eye - though the second reference says "The change introduced with 4.8 was reverted again in version 4.8.15-1 of linux-image-4.8.0-2-amd64.", so this should not be a continuing problem.

**Comment by TheAspens** [comment]
Signal 11 is not an ongoing issue on our projects.  Note that signal 11 is a segmentation fault and can have many different causes.  Recompiling the app with the kernel option you mentioned may work in the one case you saw, but it is a specific case and should not be seen as a general solution.  Signal 11 should still be passed back to the project in the stderr output for their analysis.

**Comment by Ferroin** [comment]
@TheAspens  If it's x86 or x86_64 Linux though, it's statistically speaking probably a lack of vsyscall support.  Yes, segfaults can be caused by many different things, _but_ most of those things are very unlikely for apps provided by big projects.

It absolutely should be passed back to the project though regardless.  Maybe if they see enough errors from this they'll finally get around to rebuilding without a need for vsyscalls (BOINC is literally one of the last big users of vsyscalls on Linux).

**Comment by AenBleidd** [comment]
So what is the decision about this ticket? Should smth be done or it could just be closed?

**Comment by TheAspens** [comment]
From a project operators perspective, we get the signal 11 message on the server side and so we are able to conduct analysis and study what clients are generating the signal.  So we have what we need to investigate.  I would say that this can be closed.

**Comment by paulmenzel** [comment]
I am still seeing this with Debian bullseye/stable with Linux 5.10.92-2 and *boinc-client* 7.16.16+dfsg-1.

```
[Sun Mar 13 01:53:32 2022] warn_bad_vsyscall: 32 callbacks suppressed
[Sun Mar 13 01:53:32 2022] camb_2.16_x86_6[265153] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7ffd9da8f718 ax:ffffffffff600000 si:0 di:7ffd9da8f730
[Sun Mar 13 01:53:32 2022] camb_2.16_x86_6[265153] vsyscall read attempt denied -- look up the vsyscall kernel parameter if you need a workaround ip:569228 cs:33 sp:7ffd9da8eaf0 ax:0 si:1 di:7fed40
[Sun Mar 13 01:53:32 2022] camb_2.16_x86_6[265153] vsyscall read attempt denied -- look up the vsyscall kernel parameter if you need a workaround ip:569228 cs:33 sp:7ffd9da8deb0 ax:0 si:1 di:7fed40
[Sun Mar 13 01:53:32 2022] camb_2.16_x86_6[265153] vsyscall read attempt denied -- look up the vsyscall kernel parameter if you need a workaround ip:569228 cs:33 sp:7ffd9da8d270 ax:0 si:1 di:7fed40
[Sun Mar 13 01:53:32 2022] camb_2.16_x86_6[265153] vsyscall read attempt denied -- look up the vsyscall kernel parameter if you need a workaround ip:569228 cs:33 sp:7ffd9da8c630 ax:0 si:1 di:7fed40
[Sun Mar 13 01:53:32 2022] camb_2.16_x86_6[265153] vsyscall read attempt denied -- look up the vsyscall kernel parameter if you need a workaround ip:569228 cs:33 sp:7ffd9da8b9f0 ax:0 si:1 di:7fed40
[Sun Mar 13 01:53:32 2022] camb_2.16_x86_6[265153] vsyscall read attempt denied -- look up the vsyscall kernel parameter if you need a workaround ip:569228 cs:33 sp:7ffd9da8adb0 ax:0 si:1 di:7fed40
[Sun Mar 13 01:53:32 2022] camb_2.16_x86_6[265153] vsyscall read attempt denied -- look up the vsyscall kernel parameter if you need a workaround ip:569228 cs:33 sp:7ffd9da8a170 ax:0 si:1 di:7fed40
[Sun Mar 13 01:53:32 2022] camb_2.16_x86_6[265153] vsyscall read attempt denied -- look up the vsyscall kernel parameter if you need a workaround ip:569228 cs:33 sp:7ffd9da89530 ax:0 si:1 di:7fed40
[Sun Mar 13 01:53:32 2022] camb_2.16_x86_6[265153] vsyscall read attempt denied -- look up the vsyscall kernel parameter if you need a workaround ip:569228 cs:33 sp:7ffd9da888f0 ax:0 si:1 di:7fed40
```

**Comment by Ferroin** [comment]
@paulmenzel Lacking vsyscall support. Short term, booting with the kernel parameter `vsyscall=emulate` should fix it (though it also marginally reduces the security of the system). Long term, complain to the project that they should be building with a new enough glibc that it does not need vsyscall support (I _think_ 2.13 is the minimum to avoid this issue, but I do not recall for certain).

**Comment by paulmenzel** [comment]
> Long term, complain to the project that they should be building with a new enough glibc that it does not need vsyscall support (I
> think 2.13 is the minimum to avoid this issue, but I do not recall for certain).

Hmm, it’s *libc* 2.31-13+deb11u2, so that shouldn’t be it.

    $ ldd /var/lib/boinc-client/projects/einstein.phys.uwm.edu/hsgamma_FGRP5_1.08_x86_64-pc-linux-gnu__FGRPSSE
            linux-vdso.so.1 (0x00007fff5692b000)
            libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe2bf5f3000)
            libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe2bf4af000)
            libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe2bf2ea000)
            /lib64/ld-linux-x86-64.so.2 (0x00007fe2bf620000)

**Comment by Ferroin** [comment]
@paulmenzel That’s a different application than the one the kernel was reporting in your post above, `camb_*` is Cosmology@Home, not Einstein@Home.

**Comment by paulmenzel** [comment]
Thank you.

    $ sudo ldd /var/lib/boinc-client/projects/www.cosmologyathome.org/camb_2.16_x86_64-pc-linux-gnu
            not a dynamic executable

So it’s a statically linked binary. But it’s not part of the Debian package *boinc-client* 7.16.16+dfsg-1.

    $ sudo ls -l /var/lib/boinc-client/projects/www.cosmologyathome.org/camb_2.16_x86_64-pc-linux-gnu
    -rwxr-xr-x. 1 boinc boinc 3969193 Jun 17  2017 /var/lib/boinc-client/projects/www.cosmologyathome.org/camb_2.16_x86_64-pc-linux-gnu
    $ sudo md5sum /var/lib/boinc-client/projects/www.cosmologyathome.org/camb_2.16_x86_64-pc-linux-gnu
    4f7b672d6719a03be7a1aeacbbd438e5  /var/lib/boinc-client/projects/www.cosmologyathome.org/camb_2.16_x86_64-pc-linux-gnu

So from 2017. Any idea, where that comes from and how to update it?

**Comment by Ferroin** [comment]
It’s the downloaded application binary from the project itself. There’s not really much you _can_ do to update it short of complaining upstream about it on the Cosmology@Home forums. They would have to rebuild it themselves, at which point BOINC would (probably) download and run the newer version.

**Comment by paulmenzel** [comment]
Thank you. I created https://github.com/marius311/cosmohome/issues/24.
