### ISSUE TITLE
Support for Windows 10 on ARM CPUs

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#2136]
Recently I have read that MS is working on Windows 10 for ARM, which most probably will launch in last quarter this year:
[Microsoft's Windows 10 ARM-twist comes closer with first demonstration](https://www.theregister.co.uk/2017/05/12/microsofts_windows_10_armtwist_comes_closer_with_first_demonstration/)
[Windows 10 on ARM still on track for Q4 2017, but not all OEMs will make it](https://mspoweruser.com/windows-10-arm-still-track-q4-2017-not-oems-will-make/)

Sooner or later someone will try to run BOINC on it, so some changes in BOINC will be required to support it. This Windows version will run 64-bit ARM CPUs, so new platform string will be required. It will also have x86 emulator (32-bit), so windows-x86 should be reported as an alternative platform. SSE instructions most probably also will be supported, so BOINC Client will have to run some helper x86 module to execute x86 CPUID instruction, and somehow report results to server. This probably will require update to client-server protocol too, mixing x86 CPU capabilities with ARM ones is not a good idea.

**Comment by Ferroin** [comment]
[Windows 10 IoT Core](https://developer.microsoft.com/en-us/windows/iot) may be of some interest, as it should give some idea what the API's will look like for ARM.

**Comment by cristipurdel** [comment]
https://en.wikipedia.org/wiki/List_of_Qualcomm_Snapdragon_systems-on-chip#SQ1
2.1TFLOPS for a fan-less design is definitely something to consider
