### ISSUE TITLE
Linux Manager: bug/workround no longer needed?

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#2147]
Commit 6479868b7c4c2efa87ff69d9e0910d43d2c33df7 introduced a workround for a wxWidget bug at wxWidget v3.0 / BOINC v7.4

Although that commit introduces the workround into the v7.4 release branch, the same code is still present in master. It has been asserted in testing that the workround is no longer needed, and itself now introduces unwanted side-effects.

**Comment by RichardHaselgrove** [comment]
The 'unwanted side-effects' mentioned above are still causing problems for a significant cohort of users.

Specifically, if the user:

* is running a Linux version of BOINC Manager
* is viewing the Tasks pane in advanced view
* has sufficient tasks visible to over-fill the list area (invoking scrolling)
* performs a server RPC which changes the number of visible rows (reporting or receiving new tasks)

then the display jumps from whatever scrolling position the user chose and displays the final rows only.

Could this be reviewed alongside the work which @ChristianBeer is currently doing to prepare for wxWidgets 3.1?

**Comment by ChristianBeer** [comment]
I've tested the described behavior with a local built using wxWidgets 3.1. The workaround is still required to handle the initial problem but it seems the side-effect described by Richard  are gone now. So for the next Client Release we should update wxWidgets to also be in sync with the Mac Client.

**Comment by RichardHaselgrove** [comment]
We have a user at SETI@Home (Oddbjornik) who has built a personal Manager from #3050 and wxWidgets 3.1 - he'll report results as we along in https://setiathome.berkeley.edu/forum_thread.php?id=84013. He has refined my description of the jumping problem with:

> I think the bug only rears its head when a work request 1) causes the number of tasks in the manager to be reduced, but still 2) returns _some_ work. 

He has also commented on another matter:

> In other news, this manager still wastes much cpu when minimized, because the pFrame-IsShown() call still returns true when the program is minimized.

**Comment by RichardHaselgrove** [comment]
@ChristianBeer: Oddbjornik reports that he has again observed the jumping bug, this time with the wxWidgets 3.1 build. Please refer to my comments in https://setiathome.berkeley.edu/forum_thread.php?id=84013&postid=1985590#1985590.

**Comment by RichardHaselgrove** [comment]
The problem complained of is "drew blank lines at the top and failed to draw the bottom items." The only time this is a problem is when all items in the list could have fitted in the viewport.

EnsureVisible scrolls the viewport so that a particular line is visible - in this case, the last line. The only time we need to do that is

`if (m_pListPane->GetItemCount() <= m_pListPane->GetCountPerPage()) {`

It works in Windows: I'll ask the Linux testers to try it.
