### ISSUE TITLE
CTRL+A shortcut doesn't work

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2155]
The CTRL+A shortcut doesn't work on the Projects and Tasks tab. Assuming also this is the case on the Transfers tab.
The CTRL+Left Click and the SHIFT+UP/DOWN/HOME/END shortcuts are working.

**Comment by RichardHaselgrove** [comment]
#MeToo - had to help a user where this would have been useful. Wherever the focus happens to be on the tab controls, CTRL+A convention implies 'select all lines in list'.
