### ISSUE TITLE
Suspend when specific window is opened

### ISSUE THREAD

**Issue by hugo4715** [BOINC/boinc#2160]
Hello

I think it would be useful if we could suspend the computations when a specific window is opened, for example in order to suspend when games are running.

Thanks

**Comment by AenBleidd** [comment]
Hello @hugo4715 ,

There is already a feature called 'Exclusive applications'.
Please read details here: http://boinc.berkeley.edu/wiki/Advanced_view#BOINC_Manager_Menus

If you have any questions please feel free to contact me and I try to help.

**Comment by hugo4715** [comment]
Oh thanks
