### ISSUE TITLE
Streamline register/install process

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2163]
The current register/install process has several problems:
- it involves many clicks
- it requires the user to remember the name of the project and find it in a long list.
- most of the GUI is in the Manager, which is clunky, hard to maintain/extend, and not visually integrated with web interfaces.
- it requires going through the BOINC web site
- it doesn't easily support "login with Facebook".

I'd like to support the following streamlined process for joining a project or account manager X:
- the user fills out a form to create an account on X (possibly w/ OAuth credentials)
- the user clicks a "download" link on X and runs the resulting installer
... and that's it.  The client is installed and attached to the account.

To attach a device to an existing account, the user would log in to X on the device, and click the download link.

We want to do this in a way that prohibits scams; for example:
- user sees a link saying "run SETI@home" (or some other known project)
- user downloads installer and sees "signed by UC Berkeley"
- but actually client is attached to hacker project

A basic idea is that download from X triggers the creation of a "login token": a random string with a corresponding DB entry containing the user ID and timestamp.  To attach to the account, the client does a "lookup login token" RPC, which returns the weak account key and user name.  The token is valid for a bounded amount of time, like an hour.

There are a few approaches to passing the login token to the client.

1) Using "Web sockets".  The web site would connect to the client (with repeated tries) and would then do an RPC passing the token.

Possible problems:
- wouldn't work if the user left the web site
- Web socket feature seems insecure and might be removed in future browsers.

2) Using cookies.  Download is done via "concierge" script on BOINC web site.  Project URL and account token are passed to script, which passes them to the user host as a set of cookies.  On startup, the client looks for these cookies.

Problems:
- Locating/getting cookies is problematic and soon impossible

3) Using download filename.  Download is done via "concierge" script, which downloads the installer using a filename that encodes the project ID and login token.

Possible problems:
- Some anti-virus software may be triggered by unknown filenames.

**Proposal**

Let's focus on the filename approach for now.

The client already has a list of "vetted" projects and account managers.  For security, let's restrict automated attach to these.

Pieces we'll need:

- An RPC to the BOINC web site that passes the web agent string, and that returns a list of recommended versions (with and without vbox) for that platform.
- Add "login token" table to BOINC DB, with PHP interface
- Add sample download page to BOINC PHP code
- Add "lookup_login_token" web RPC
- Change concierge.php to pass login token and project code (3 chars)
- Change the Win and Mac installers to write the name of the install file to a well-known file (say, "installer_filename.txt") in the data directory; remove other stuff involving filename

Client startup:
* if attached to any projects or AM, delete installer_filename.txt; done.
*  look for the installer_filename.txt.  If present:
   * parse it
   * lookup project ID, get URL
   * do a lookup_account_token RPC to the project, get weak auth
   * attach to project

It's been suggested that, on the initial run, the Manager should show a Welcome dialog saying "you're attached to project X as user Y - OK?", and the client shouldn't attach to the project until the user clicks OK.  I don't think this is needed.

**Comment by CharlieFenton** [comment]
I thought Rom already implemented approach 3, at least for MS Windows. This is what he wrote in an email titled "boinc_alpha] BOINC 7.6.33 released for Windows":

**Comment by romw** [comment]
Just for reference, cookieless installs using the stock installer are documented here:
http://boinc.berkeley.edu/trac/wiki/SimpleAttach#CookielessInstalls

**Comment by davidpanderson** [comment]
The proposal extends that by using account tokens, working for account managers, restricting to vetted projects, and moving the filename parsing from installer to client.

**Comment by davidpanderson** [comment]
If no comments, I'll start working on this, e.g. the DB table for signup tokens and RPC

**Comment by AenBleidd** [comment]
@davidpanderson, isn't this already implemented?

**Comment by davidpanderson** [comment]
yup
