### ISSUE TITLE
Cannot change process priority on Android.

### ISSUE THREAD

**Issue by fxzjshm** [BOINC/boinc#2201]
I am using MIUI, where I discovered that 8 computing processes only share 1 slowest core, with other 7 cores idle. However, just one normal process can use up 1 fast core.  
So could you please add a property to configure the process priority?

**Comment by JuhaSointusalo** [comment]
How many and which cores are used on Android is discussed in #2549. I'm keeping this issue open in case #2549 gets resolved in some way other than bumping process priority.

**Comment by fxzjshm** [comment]
Thats great,thanks!

**Comment by AenBleidd** [comment]
Manual thread/process binding to the particular CPU core is not a good behavior, since the kernel might want to stop some cores to prevent CPU overheat, thus breaking the binding.
CLosing this as "Won't fix" for now
