### ISSUE TITLE
Use GPU always - causes overheat with dual GPU laptop

### ISSUE THREAD

**Issue by Iwork4beer** [BOINC/boinc#2214]
I have one GPU integrated in Intel CPU, and additional GeForce card. I cannot leave BOINC unatended, as when I leve option "Use GPU always" enabled, and there will be two tasks, one using Intel GPU, and one using NVIDIA GPU... BOINC will run both of them. This causes overheat of my laptop.

I have to disable GPU computing overnight and oversee it during the day, which slows it down and wastes my time.

The solution is simple, if I had more specified choice like "Use GPU 1 always" - or 2, or whatever, depending on the detected number of GPU's installed, that would sort it out.

I'm starting to built two multi GPU machines and would happily use this feature on them as well.

**Comment by SETIguy** [comment]
Perhaps realated to #1379?

**Comment by Iwork4beer** [comment]
Yes, it is related. But most of the modern non-gaming laptops share one heatsink between CPU(APU) and GPU, so even if we would have this overheat protection it would just cause tasks to stop every 15 minutes. My laptop is fully able to keep the temperatures reasonable when I'm using one of the GPU's. If I will be able to choose just one, overheat will never occure.

**Comment by Iwork4beer** [comment]
Maybe I wasn't clear enough. 

I see that BOINC detected correctly both of my GPU's. The problem is that, I cannot limit the software to use just one of them at the time. You can put usage limits at the CPU, but not GPU. 

So what I'm asking for is a solution to pick the particular GPU (or GPU's) to be used by the BOINC from the list of the GPU's currently installed in the system.

**Comment by JuhaSointusalo** [comment]
You can already do that by going to each project you have joined and de-selecting in project preferences to use "Vendor X GPU" or using `<exclude_gpu>` in `cc_config.xml`.

Or you can prevent BOINC from using any particular GPU at all by setting `<ignore_X_dev>` in `cc_config.xml`.

Or you can use `<no_gpus>` in `cc_config.xml` to use no GPUs at all.

See [Client configuration](http://boinc.berkeley.edu/wiki/Client_configuration) for details.

**Comment by Iwork4beer** [comment]
Fair enough, but I want to use them both... just not at the same time. Some tasks in SETI@home are using IntelGPU and some NVIDIA GPU, BOINC runs them both. I have to suspend all tasks from one type, by hand, them resume them. But if in the meantime some of the other tasks will be downloaded... well. 

Only solution so far is a complete lack of GPU processing during the night time, which is a schame.

Changing config files every 3-5 tasks would be a pain too.

**Comment by JuhaSointusalo** [comment]
So what you want is to have something equivalent to the cc_config.xml options made available in GUI and so that they are applied at runtime without needing BOINC restart?

I'm assuming you don't want to stick with one of the GPUs because you play games or whatever on the discrete GPU and at those times you'd like the integrated GPU to process tasks?

**Comment by Iwork4beer** [comment]
Yes, I'd like to be able to do it whenever it suits me with a few clicks.

When I'm using my laptop for work I need only integrated Intel GPU, it is responsible for showing the image on my screen and additional monitor. I can then use NVIDIA for BOINC and I can't even feel it. When I'm away shopping, sleeping etc. I'd like to use Intel GPU for the rest of the tasks.

**Comment by AenBleidd** [comment]
Closing this now if favor of #1459 with more general approach described.
