### ISSUE TITLE
Can't start boinc from unpacked archive

### ISSUE THREAD

**Issue by ghost** [BOINC/boinc#2216]
Dear developers,

I'm running a Fedora 26 Workstation installation and the following error occured:
I downloaded `boinc_7.2.42_x86_64-pc-linux-gnu.sh` , ran it the `boinc_7.2.42_x86_64-pc-linux-gnu.sh` script and tried to run it on a Fedora 26 Workstation installation by `~/BOINC/run_manager`. The boinc manager however doesn't start but gives me instead the following error message:

```
$ ~/BOINC/run_manager
./boincmgr: Symbol `_ZTV12wxBufferedDC' has different size in shared object, consider re-linking
./boincmgr: Symbol `_ZTV10wxClientDC' has different size in shared object, consider re-linking
./boincmgr: Symbol `_ZTV10wxMemoryDC' has different size in shared object, consider re-linking
./boincmgr: Symbol `_ZTV9wxPaintDC' has different size in shared object, consider re-linking
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

I would guess that this error is connected to a compiler as probably Fedora uses a compiler that is to probably too tew for the boinc package. For which packages do I have to look to find the cause of the error?

Regards,

Jakob

**Comment by AenBleidd** [comment]
Should this issue just be closed and the corresponding file just deleted from http://boinc.berkeley.edu/download.php ? In any case it is out-dated.

**Comment by AenBleidd** [comment]
Since this issue belongs to outdated version of BOINC and there are better ways to instal it on *nix OSs with package manager, I'm closing this ticket.
