### ISSUE TITLE
Mac AMD Compute Engines report negative memory

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2226]
It's been reported that AMD Compute Engines are reporting negative memory in BOINC 7.8.2 and 7.8.3, resulting in lost work in some projects because their scheduler rounds up these to have no memory at all (0MB). 

I've found examples of this happening at Seti@Home.
AMD Radeon Pro 580 Compute Engine (0MB) (https://setiathome.berkeley.edu/show_host_detail.php?hostid=6873866)
AMD Radeon Pro 575 Compute Engine (0MB) (https://setiathome.berkeley.edu/show_host_detail.php?hostid=8322862)
AMD Radeon HD - FirePro D500 Compute Engine (-1024MB) (https://setiathome.berkeley.edu/show_host_detail.php?hostid=7303945)

The AMD Radeon Pro 580 Compute Engine has 8GB memory
The AMD Radeon Pro 575 Compute Engine has 4GB memory
The AMD Radeon HD - FirePro D500 Compute Engine has 768MB memory

These can also report very large amounts of total memory, for example 
AMD Radeon Pro 555 Compute Engine (driver version 1.2 (Sep 29 2017 18:59:39), device version OpenCL 1.2, **17592186042368MB**, -2048MB available, 821 GFLOPS peak)
(that's 16 Zettabytes)

**Comment by CharlieFenton** [comment]
Handled in PR #2227 and #2228.

**Comment by CharlieFenton** [comment]
fixed in PR #2227 and #2228.
