### ISSUE TITLE
get_versions.php needs to be part of the default project make_project

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2235]
The script get_versions.php that was added to support the new download page should be part of the make project script and added as a every 6 hour job to fetch the latest version.

**Comment by TheAspens** [comment]
This should be implement as part of PR #2207

**Comment by TheAspens** [comment]
Based on the proposed standard for reviews and merges (https://github.com/BOINC/boinc-policy/blob/knr-code-reviews/Expectations_of_Code_Review.md) , this does not need to be implemented in PR #2207 .

**Comment by davidpanderson** [comment]
This needs to be done only for vetted projects, so it shouldn't be part of make_project

**Comment by TheAspens** [comment]
After more thinking I think with the way the download page is currently being used I think you are right.  I'm closing this issue.
