### ISSUE TITLE
Use constant "INSTALLER_FILENAME_FILENAME" in new autologin code

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2236]
The code developed in branch dpa_autologin_client_setupwin and in pull request #2222 didn't use the constant because it was defined in pull request #2207 (branch dpa_autologin_client).

PR#2222 was merged to master and then merged into dpa_autologin_client in order to get the code in a single place.  The constant can now be implemented in branch dpa_autologin_client as part of PR #2207.

**Comment by davidpanderson** [comment]
I changed the name to account_data.txt
We need to combine this stuff into a single branch, or into master

**Comment by TheAspens** [comment]
This was resolved in issue #2207 so I'm closing it.  Thanks for fixing.
