### ISSUE TITLE
website:  get_versions.php puts header message into versions.xml

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2237]
When running the ops tool get_versions.php, the resulting versions.xml file a notice message in the file.

```
root@boincserver:~/project/html/ops# head ../user/versions.xml 

Notice: Undefined index: HTTP_USER_AGENT in /mydisks/a/users/boincadm/boinc-site/download_all.php on line 27
<?xml version="1.0" encoding="ISO-8859-1" ?>
<versions>
<version>
    <platform>Windows 64-bit</platform>
    <dbplatform>windows_x86_64</dbplatform>
    <description>Recommended version</description>

```

**Comment by TheAspens** [comment]
After looking at this further, this is an issue with the BOINC website download_all.php generating the NOTICE when the HTTP_USER_AGENT is not set.

I've opened pull request https://github.com/BOINC/boinc-site/pull/2 with one suggestion that might resolve this.

**Comment by RichardHaselgrove** [comment]
Reviewing for v7.10 release, it looks as if this has been handled in the boinc-site PR: in which case this issue can be closed (unless required to remind us to test?)

**Comment by TheAspens** [comment]
Yes - this was resolved on BOINC site.  Closing ticket.
