### ISSUE TITLE
Manager: Can we remove autoattach_in_progress

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2239]
In the later part of pull request #2207 code was added to not handle GUI RPCS until after the processing of the account deteails file was complete within the core client.

I believe that this implementation eliminates the need for the function autoattach_in_progress in the file clientgui/MainDocument.cpp.

If that is correct, then that function can be removed.  This has the benefit of eliminating reading of local files by the manager.

**Comment by davidpanderson** [comment]
Charlie added some changes to GUI RPC timeout that require this function.

**Comment by davidpanderson** [comment]
However, you're correct that it doesn't need to be called before opening the attach wizard in the no-projects case.  I removed these.

**Comment by TheAspens** [comment]
Ok - at the time I opened it, it wasn't needed but since the code has evolved it is needed.  I'm going to close this now since it has been resolved.
