### ISSUE TITLE
client: Re-enable GUI RPCs if no response from project to auto-attach RPC 

### ISSUE THREAD

**Issue by CharlieFenton** [BOINC/boinc#2240]
Regarding commit f052077 _Client: don't handle GUI RPCs until account token lookup RPC is finished_, what happens if the RPC never receives a reply? Will the Manager hang forever, or is there proper timeout handling to enable GUI RPCs and to open the Attach Wizard?
(Reference PR #2207

**Comment by davidpanderson** [comment]
Curl times out HTTP transactions.
But in general they either succeed or fail immediately.
