### ISSUE TITLE
Auto-attach: client must get latest all_projects.xml list

### ISSUE THREAD

**Issue by CharlieFenton** [BOINC/boinc#2242]
Reference: #2207 

When installing over an existing client, the mac installer does not replace the existing _all_projects_list.xml_ file, because the one already in the BOINC Data directory may be newer than the one in the installer, and the file will get updated at some point. This won't be a concern as long as the auto-attach is only used with virgin BOINC installations. But although the server web site says not to use the buttons if you already have BOINC installed, you can't count on people to follow the directions.

One possible way to solve this would be for the client to download the latest _all_projects_list.xml_ as the first step in handling an auto-attach token. 

However, as explained in issue #2241, during testing the client must use a special version of _all_projects_list.xml_ which includes the test project.

**Comment by TheAspens** [comment]
Charlie - if I understand, this issue would come into play in the following situation:

1) A project is launched that is assigned a project_id and is added to the all_projects_list.xml
2) However, the version of the all_projects_list.xml does not contain the project yet

Thus this new project would not be able to use the auto-attach mechanism until a new version of the client was released that contains an updated version of the all_projects_list.xml.

Would it be correct to say that this could be resolved any of:

- Cause the client to initiate a fetch of the latest version of the all_projects_list.xml before attempting to process an auto-attach?
- Cause the client to initiate a fetch of the latest version of the all_projects_list.xml if the project id of used in the auto-attach file is not found?
- Other options?

Let me know if this is addressing the question you are raising.

Note that in ticket #2241 (if I summarized it correctly and if everyone agrees with that approach) the issue of replacing the all_projects_list.xml file will be changed to not do that before a production release of the 7.10 client.

**Comment by CharlieFenton** [comment]
> Would it be correct to say that this could be resolved any of:
> 
> Cause the client to initiate a fetch of the latest version of the all_projects_list.xml before attempting to process an auto-attach?

Yes

> Cause the client to initiate a fetch of the latest version of the all_projects_list.xml if the project id of used in the auto-attach file is not found?

This would wok, but It would be better to always do this before attempting to process an auto-attach. 

It would be better yet to always do this after any install that changes the version number, so that the project list shown in the Attach Wizard is complete in case the user then wants to manually add another project that recently came available. 

>Note that in ticket #2241 (if I summarized it correctly and if everyone agrees with that approach) the issue of replacing the all_projects_list.xml file will be changed to not do that before a production release of the 7.10 client.

A I wrote in my latest comment in that issue, I disagree with that approach.

**Comment by TheAspens** [comment]
> This would wok, but It would be better to always do this before attempting to process an auto-attach.
> 
> It would be better yet to always do this after any install that changes the version number, so that the project list shown in the Attach Wizard is complete in case the user then wants to manually add another project that recently came available.

David mentioned via email 

> One slight rough edge is that the lookup-token RPC takes long enough
> that the "communicating with client" warning pops up for a second or two.

If we also have to make another RPC to fetch the all projects list this will increase this time.  Are we ok with that additional delay for the initial connect?

Or would you consider this:
1. If version number of client changes, fetch new all_projects_list.xml before allowing manager RPCs
2. If project id from auto-attach not found in file, fetch new all_projects_list.xml before allowing manager RPCs

The only advantage of my alternative is a slightly faster time to allowing the manager RPCs.  If you and David don't think that is worth it, I'm ok with that.

**Comment by CharlieFenton** [comment]
> David mentioned via email
> 
> One slight rough edge is that the lookup-token RPC takes long enough
> that the "communicating with client" warning pops up for a second or two.

As you (@TheAspens) had requested earlier, these discussions should be done within the PRs and issues, not in private emails, so there is record of them in one place. I had wondered if this wold be a problem but was waiting for testing so as not to raise a non-issue.

> If we also have to make another RPC to fetch the all projects list this will increase this time. Are we ok with that additional delay for the initial connect?

That is an example of the reason this needs to be added to the code before testing: to ensure that our testing locates unintended consequences. 

> If version number of client changes, fetch new all_projects_list.xml before allowing manager RPCs

That is OK if the project ID is already in the _all_projects_list.xml_ file found in the user's BOINC Data (if one existed before the install.) Remember that the installer must not overwrite an existing _all_projects_list.xml_ file, which may be newer than the one in the installer.

> If project id from auto-attach not found in file, fetch new all_projects_list.xml before allowing manager RPCs

That is too late. It must be done before starting the auto-fetch.

> The only advantage of my alternative is a slightly faster time to allowing the manager RPCs. If you and David don't think that is worth it, I'm ok with that.

The problem is that it is taking too long to allow the manager RPCs. Since the client has not responded to the manager in a timely manner, the  "communicating with client" warning is dips;aged. So neither of these will make zany difference. I think the only solution is to have find a way for the manager to know why there is a delay and have it display a different message, such as "communicating with server." We may need a special RPC for that, and allow only that and perhaps certain other necessary RPCs while waiting for the auto-attach to complete.

Frankly, I am not surprised that the auto-attach feature is turning out to be considerably more complicated than originally anticipated.

**Comment by TheAspens** [comment]
> David mentioned via email
> 
> > One slight rough edge is that the lookup-token RPC takes long enough
> > that the "communicating with client" warning pops up for a second or two.
> 
> As you (@TheAspens) had requested earlier, these discussions should be done within the PRs and issues, not in private emails, so there is record of them in one place. 

I agree.  David sent that email to both you and me and I had to add it to this thread for everyone to have context.

**Comment by TheAspens** [comment]
@davidpanderson - can you please comment on Charlie's thoughts above?

**Comment by CharlieFenton** [comment]
> It would be better yet to always do this after any install that changes the version number, so that the project list shown in the Attach Wizard is complete in case the user then wants to manually add another project that recently came available.

After studying the client code, I found that this is already implemented in the current release.

>Cause the client to initiate a fetch of the latest version of the all_projects_list.xml if the project id of used in the auto-attach file is not found?

After a discussion with @davidpanderson, we agreed that he will implement this in the dpa_autologin_client branch.

**Comment by AenBleidd** [comment]
Is it still an issue?

**Comment by davidpanderson** [comment]
I don't think so.  Charlie?

**Comment by CharlieFenton** [comment]
I believe it should no longer be an issue if @davidpanderson has already implemented this:
>> Cause the client to initiate a fetch of the latest version of the all_projects_list.xml if the project id of used in the auto-attach file is not found?

> After a discussion with @davidpanderson, we agreed that he will implement this in the dpa_autologin_client branch.

**Comment by AenBleidd** [comment]
According to the comments above I'm closing this ticket as Fixed
