### ISSUE TITLE
GIT Master now contains bad all_projects_list.xml file

### ISSUE THREAD

**Issue by CharlieFenton** [BOINC/boinc#2247]
The premature merge of the dpa_autologin_client branch into master overwrote the file `win_build/installerv2/redist/all_projects_list.xml` with a test version which includes the _BOINC Test_ project. That project should not be included in production builds.

**Comment by CharlieFenton** [comment]
Reference PR #2207

**Comment by JuhaSointusalo** [comment]
Stepping on release manager's toes for a bit. `all_projects_list.xml` still needs to be updated/corrected. The current version includes Onboard account manager under a test URL.

**Comment by davidpanderson** [comment]
fixed in #2351

**Comment by CharlieFenton** [comment]
Since I've already built and uploaded the version 7.9.1 installer for the Mac, that installer still has the version that was at _win_build/installerv2/redist/all_projects_list.xml_ on Feb 12 at 12:01am in the 7.9.1 tag. My next build will have the new one, but **ONLY** if it is copied / cherry-picked to the _client/client_release 7/7.10_ branch **first**. If we need this done before the first round of alpha testing, that means we need to change the version number to 7.9.2 **after** _win_build/installerv2/redist/all_projects_list.xml_ has been updated in the _client/client_release 7/7.10_ branch, so I can build and upload a new release.

**Comment by RichardHaselgrove** [comment]
Noted. See my review of #2351 - this will have to wait for further checks tonight or tomorrow.

**Comment by AenBleidd** [comment]
Wasn't this already fixed?

**Comment by AenBleidd** [comment]
I think this ticket is one that can be fixed with no problems. It is open for 10 month without any progress on it

**Comment by AenBleidd** [comment]
@RichardHaselgrove, thank you. Just wanted to clean backlog from old and stale stuff.

**Comment by RichardHaselgrove** [comment]
New general issue created: the specific problem discussed here is historic and can be closed.
