### ISSUE TITLE
Add systemd unit 

### ISSUE THREAD

**Issue by BryanQuigley** [BOINC/boinc#2255]
Both Fedora[1] and Debian/Ubuntu [2] install their own systemd unit.  It would likely be better to standardize on one.

I'm currently testing one on Ubuntu based on the modified Fedora one:
[Unit]
Description=Berkeley Open Infrastructure Network Computing Client
Documentation=man:boinc(1)
After=network-online.target

[Service]
Type=simple
Nice=19
User=boinc
WorkingDirectory=/var/lib/boinc-client
ExecStart=/usr/bin/boinc
ExecStop=/usr/bin/boinccmd --quit
ExecReload=/usr/bin/boinccmd --read_cc_config
ExecStopPost=/bin/rm -f /var/lib/boinc-client/lockfile
IOSchedulingClass=idle

[Install]
WantedBy=multi-user.target

Looks like this should live in client/scripts.  TODO handle the various differences between Fedora and Debian.  Different lockfiles and boinc client names...

[1] http://pkgs.fedoraproject.org/cgit/rpms/boinc-client.git/tree/boinc-client-systemd
[2] https://packages.debian.org/sid/amd64/boinc-client/filelist

**Comment by vaneldik** [comment]
Hi Brian, it would be great if you could add a line

EnvironmentFile=/etc/sysconfig/boinc-client

in the "[Service]" part. This would allow users to define environment variables again.

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1517456 (opened yesterday)

**Comment by BryanQuigley** [comment]
@vaneldik had to modify it to not require the file exist (and added the two other possible Environment Files).

**Comment by photonxp** [comment]
Default systemd service file for boinc on Ubuntu, pasted here for reference:
1. Make sure the directory for "--dir" exists with proper permission
2. No **ExeStop**, refer to content above.

> [Unit]
> Description=Berkeley Open Infrastructure Network Computing Client
> After=network.target
> 
> [Service]
> Nice=10
> User=boinc
> PermissionsStartOnly=yes
> ExecStartPre=/usr/bin/touch /var/log/boinc.log /var/log/boincerr.log
> ExecStartPre=/bin/chown boinc:boinc /var/log/boinc.log /var/log/boincerr.log
> #ExecStart=/usr/bin/boinc --dir /var/lib/boinc-client
> ExecStart=/bin/sh -c '/usr/bin/boinc --dir /var/lib/boinc-client >/var/log/boinc.log 2>/var/log/boincerr.log'
> ExecReload=/usr/bin/boinccmd --read_cc_config
> ExecStopPost=/bin/rm -f /var/lib/boinc-client/lockfile
> IOSchedulingClass=idle
> 
> [Install]
> WantedBy=multi-user.target

**Comment by Germano0** [comment]
@BryanQuigley why nice has been setted to 10 instead of 19?
https://github.com/BOINC/boinc/blob/master/client/scripts/boinc-client.service.in#L9

**Comment by BryanQuigley** [comment]
I can't figure out where this message is in - in Github, so hopefully
this goes to the right place.

Conversation on why we went with nice=10 is
https://github.com/BOINC/boinc/pull/2260#issuecomment-360619802
