### ISSUE TITLE
BOINC Android freezes on splash screen

### ISSUE THREAD

**Issue by Kongpha** [BOINC/boinc#2258]
I suspended a computering then resume again. While app resuming tasks. I closed a app. Moment later, I opened app again and it freezes on BOINC logo.

I need to reinstall a app to it works normally and my tasks and projects were removed.

**Comment by Ageless93** [comment]
Would be nice to know some more information:
* Android version?
* BOINC version?
* Where did you download it from if not the Google Play Store?
* Which project(s) added and running?

**Comment by Kongpha** [comment]
Sorry for the slow reply.

Android version : Android 7.0 Nougat
BOINC version : before 7.4.53
Where did you download it from if not the Google Play Store? : I was downloaded it from Play store
Which project(s) added and running?
 : 
- Rosetta@home
- SETI@home
- Universe@home
- Asteroids@home
- yoyo@home
- Acoustics@home

**Comment by Kongpha** [comment]
However i had deleted BOINC's data, and it works perfectly now. But all credits where are come from my mobile had gone. But it isn't big problem because i had connected to BOINCstats(BAM!) And it saves my all credits well now.
