### ISSUE TITLE
Provide SHA256 of stat files

### ISSUE THREAD

**Issue by denravonska** [BOINC/boinc#2259]
When generating stat files, would it also be possible to provide a `.sha256` for each file, containing the hash of the file in question? This can be used to determine the authenticity of the file and to ensure that it has not been tampered with along the way.

**Comment by AenBleidd** [comment]
This was requested by GridCoin developers, but they have implemented their solution without this requirements years ago. And there is no other real reason to have this feature implemented.
That is why I'm closing this without any further actions.
