### ISSUE TITLE
Out of Memory when trying to display all tasks on project website

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#2277]
When I am trying to display all my tasks at RakeSearch project, I get following error:

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 77 bytes) in .../html/inc/db_conn.inc on line 125 

I checked in BOINC code and this page uses LIMIT directive in SQL query to load 20 records from DB at once, so it is surprising that 128MB was not enough. In the past it worked correctly, when my completed tasks list was much shorter.

I asked about this at project's forum and got reply that "This memory allocation error has been happening on quite a few projects for quite a few years". So this is some legacy bug. Link: [http://rake.boincfast.ru/rakesearch/forum_thread.php?id=46](http://rake.boincfast.ru/rakesearch/forum_thread.php?id=46)

Note: if you have problem with debugging this, you can try installing [Xdebug](https://xdebug.org/). As I recall, it dumps lots of useful data when error happens in PHP script.

**Comment by davidpanderson** [comment]
What PHP page does this happen on?

**Comment by sirzooro** [comment]
I get this error when I try opening http://rake.boincfast.ru/rakesearch/results.php?userid=47

**Comment by progger** [comment]
Reason here: https://github.com/BOINC/boinc/blob/406fe15121c3d615e9f994a32fc0a44f4a13f07a/html/inc/result.inc#L762-L775
We get an array of all the results and count them according to the conditions. If you have many results, the script requires a lot of memory for this array. I do not see an easy way to fix this. It may be necessary to write a large query that returns all counts, it can be a return enumerator, so as not to create an array, there may be something else.

**Comment by davidpanderson** [comment]
The query returns only those results belonging to that user.
How many of these are there?
Are you running db_purge?

**Comment by progger** [comment]
This is not my server, but as I see, db_purge is not running. Ok, I will recommend that they run it.

> How many of these are there?

I think that about 200k

**Comment by sirzooro** [comment]
You can also consider using stored procedure in PL/pgSQL, which would compute all of this and return results as a record set.

**Comment by progger** [comment]
state_num($result) has a lot of logic - it's not simple.

**Comment by sirzooro** [comment]
> state_num($result) has a lot of logic - it's not simple.
By executing SQL with grouping you would get quite small result set (below 1k records), so it would need a lot less memory. state_num() could do with data whatever it wants, it only should start taking into account record count returned by query.

**Comment by progger** [comment]
> Edit: SQL query with grouping also should do the trick:

I did not think about this option. I tested it on my server, and it seems to work:
```
    $results = BoincResult::enum_fields(
        "appid, server_state, outcome, validate_state, count(*) AS cnt",
        $where_clause." group by appid, server_state, outcome, validate_state", null
    );
    foreach ($results as $r) {
        $cnt = $r->cnt;    
        if (array_key_exists($r->appid, $app_count)) {
            $app_count[$r->appid] += $cnt;
        }
        $app_count[0] += $cnt;
        if (!$info->appid || ($r->appid == $info->appid)) {
            $state_count[state_num($r)] += $cnt;
            $state_count[0] += $cnt;
        }
    }
```

**Comment by sirzooro** [comment]
Good! So please prepare a pull request with this fix :)
