### ISSUE TITLE
build issue in app_ipc.h

### ISSUE THREAD

**Issue by ColumPaget** [BOINC/boinc#2279]
Hi,

when trying to build boinc I had a compile failure in lib/app_ipc.h. The cause was that the APP_INIT_DATA object is defined at line 140 as:

struct APP_INIT_DATA
{

yet it contains constructor/destructor functions. My compiler (gcc 6.3.0) balked at this. Changing the defintion to:

class APP_INIT_DATA
{
public:

solved this issue.

Colum

**Comment by davidpanderson** [comment]
Structs can have constructors/destructors AFAIK; see https://stackoverflow.com/questions/1127396/struct-constructor-in-c
... and BOINC has dozens of structs that do, not just APP_INIT_DATA.

Can you post the error message your were getting?

**Comment by AenBleidd** [comment]
Is this still an issue?

**Comment by AenBleidd** [comment]
I was not successful trying to reproduce this with gcc 6.4.0. Assuming that this is the latest minor version of the same major release I see no issues with current master branch.
I close this issue.
Please feel free to reopen it if it still reproducible.
