### ISSUE TITLE
Feature Request:  Ability for Manager to manage multiple computers at the same time

### ISSUE THREAD

**Issue by gopherit** [BOINC/boinc#2283]
Currently if we want to manage multiple clients, we have to connect to them individually and switch back and forth.  It would be ideal if we could manage multiple clients at once.

**Idea 1:  Horizontal Row of Tabs**
- Add another row with tabs, similar to a web browser.
-- Existing Row (Menu Bar):  File View Activity Options Tools Help
-- New Row (Client Tabs):  localhost Computer01 Computer02
-- Existing Row (Tabs):  Notices Projects Tasks Transfers Statistics Disk
- If many, many clients are connected than can fit on the screen, the tabs could scroll (like with Excel) or use an overflow menu (like with Firefox).

**Idea 2:  Vertical Column**
- Each client device could be its own button on the left hand side of the window.

Ideas 1 and 2 are similar in behavior to many Remote Desktop managers and organizers.  Some RDP managers have a red/green color scheme in the tabs to show whether or not there is an active connection to the remote computer, allowing us to right-click and Connect or Disconnect.  Additionally, we can create a list of bookmarks in the left hand of the window and connect to them manually.  We can organize many clients in folders and subfolders; e.g. "Location 1" folder has Computer01, Computer 02, Computer03 and "Location 2" folder, etc.

**Idea 3:  Combine Ideas 1 and 2.  Make bookmarks on left side of window and row of tabs across the top.**

Example with Remote Desktop Organizer:

![image](https://user-images.githubusercontent.com/25557897/34466879-540b54e6-eeb0-11e7-8401-b0c22f312532.png)

I realize this feature request is a major effort, but we can always dream big.  :)

**Comment by AenBleidd** [comment]
Clone of #1759

Best regards,
Vitalii

Sent via Android

1 янв. 2018 г. 3:30 PM пользователь "gopherit" <notifications@github.com>
написал:

**Comment by gopherit** [comment]
Apologies!  I didn't immediately find it.
