### ISSUE TITLE
Use hypens instead of underscores for command line options

### ISSUE THREAD

**Issue by chrstphrchvz** [BOINC/boinc#2291]
Would it be possible for any BOINC program's command line options with multiple words to use hyphens ("dashes") instead of underscores? Those seem to be the more popular and easier to type approach. E.g.:
```
boinccmd --get-project-status
```
instead of
```
boinccmd --get_project_status
```
And for compatibility, would it be possible to accept either way (i.e. documentation uses hyphens, but programs support both)?

**Comment by AenBleidd** [comment]
I don't see a big value in this change.
So I close this without any further actions.
