### ISSUE TITLE
boinccmd: add option for synchronizing account manager

### ISSUE THREAD

**Issue by chrstphrchvz** [BOINC/boinc#2292]
Currently, there is no option in `boinccmd` specifically for requesting the client to synchronize with an account manager. [As discussed on the forum](https://boinc.berkeley.edu/dev/forum_thread.php?id=11954), there is the workaround of using `--quit_acct_mgr` then joining again: `--join_acct_mgr [URL username password]`. Could an option e.g. `--sync_acct_mgr` be added for this purpose?

**Comment by davidpanderson** [comment]
I added this; will appear in 7.10 client release.
