### ISSUE TITLE
Manager feature request: set daily schedule for CPU usage limits

### ISSUE THREAD

**Issue by mchelen** [BOINC/boinc#2296]
I would like to be able to set CPU usage on a daily schedule like:
9am-5pm = 25%
5pm-9am = 100%

It doesn't seem like there is any way to do this with the current BOINC Manager.

**Comment by Ageless93** [comment]
Long time request, no time set for when it will be added, if ever. Original issue #41. Please continue in that issue, add your request to it.

**Comment by TheAspens** [comment]
If there is a developer/contributor who is interested in developing this feature, I would encourage them to propose the changes in issue #41 along with how the UI would work on both the website and the client and then see if anyone objects to the implementation.  I think that the older comments in issue #41 should be reconsidered if there is someone be willing to do the implementation and if the implementation was able to hide the complexity of this complexity from novice users.

**Comment by TheAspens** [comment]
This is a duplicate of #41 

(adding this to get github to link the two issues)
