### ISSUE TITLE
Remove GPL Code from BOINC

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2304]
Commit https://github.com/BOINC/boinc/commit/73a95378f54964b118f84352c6cdd72b6915b124 added GPL code that was intended to be enable the monitoring of CPU temperature as a way to better throttle cpu usage and keep fan speeds low.  

However, this work was not fully implemented.  Additionally, it incorporates code that is licensed under the GPL that cannot be used in BOINC.

As a result, this commit needs to be reversed and the code removed.

**Comment by RichardHaselgrove** [comment]
@CharlieFenton 
With the 'critical' flag, this looks like a showstopper for v7.10, which David wants me to start on. Could you review and advise, please, and action if you agree?

**Comment by CharlieFenton** [comment]
Kevin, David and I have already discussed this and I agree. The code added by my commit 73a9537 in April 2010 can be safely removed and should be removed for the reasons given.

**Comment by JuhaSointusalo** [comment]
Closing. The code was removed in #2305.
