### ISSUE TITLE
macOS: menu is hidden behind non-BOINC full screen apps

### ISSUE THREAD

**Issue by chrstphrchvz** [BOINC/boinc#2315]
Using 7.8.6 on macOS 10.13.3. Clicking the BOINC menu bar icon causes the menu to appear only either on a desktop space (i.e. not focused on a full screen app) or when focused on a BOINC full screen window. The menu **does not** appear for third-party full screen apps' windows, although the menu is "there"--I can interact with it using the keyboard. This leads me to believe the menu is hidden/obscured by whichever window I have open, and BOINC is failing to force the menu to appear in front of another apps' window. 

Menu for ordinary desktop (does not get obscured by other apps):
![screen shot 2018-01-23 at 5 16 47 pm](https://user-images.githubusercontent.com/7941193/35306058-a3195962-0061-11e8-9f8c-b8ea91f8ef4f.png)

Menu for BOINC full screen (expected result):
![screen shot 2018-01-23 at 5 17 06 pm](https://user-images.githubusercontent.com/7941193/35306060-a6586488-0061-11e8-9dd2-73d50d603b25.png)

Menu for third-party app full screen window:
![screen shot 2018-01-23 at 5 17 43 pm](https://user-images.githubusercontent.com/7941193/35306071-af622f00-0061-11e8-9435-91d3c2cf22d9.png)

**Comment by CharlieFenton** [comment]
The relevant code is in the wxWidgets library. All current versions of wxWidgets implement the status bar menu using APIs which have been deprecated since OS 10.10. When they update this code, it should hopefully fix this issue. Meanwhile, a simple workaround is to control-click on the BOINC Manager's Dock icon, which produces the same menu.

**Comment by chrstphrchvz** [comment]
Thanks for the insight. Is wxWidgets already aware of this issue/do they have a ticket for this (if not, I can try opening one)?

**Comment by CharlieFenton** [comment]
I no longer see this problem with BOINC version 7.9.3 which uses a newer version of wxWidgets. You can get it [here](https://boinc.berkeley.edu/dl/boinc_7.9.3_macOSX_x86_64.zip), Please let me know if this fixes it for you.

**Comment by chrstphrchvz** [comment]
@CharlieFenton thanks, it is fixed in 7.9.3.
