### ISSUE TITLE
Separate filter lists for fora and PM's

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#233]
**Reported by Fuzzy Hollynoodles on 9 Dec 37426704 00:00 UTC**
Separate filter lists for users on the boards and for Personal Messages wanted.

Then people can filter certain other people from sending them PM's while their posts still can be read on the fora.

Thank you.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/234

**Comment by romw** [comment]
**Commented by Fuzzy Hollynoodles on 21 May 37428159 20:26 UTC**
Replying to [KSMarksPsych](comment:1):

How come this ticket has been set to priority: '''Trivial'''?

As a moderator on two of the boards where this feature has been implemented on, I can't have anybody filtered as I need to see what they are posting. 

Having received an abusive PM from one of the moderators on the BOINC board, you own board, I need this function implemented very soon, specially when the very same person is posting abusive/spamming posts to me on the boards at the same time.

A little biased, are we?

**Comment by romw** [comment]
**Commented by anonymous on 11 Oct 37429284 12:26 UTC**
KSMarksPsycho is biased?  Talk about trivial.  We already know this!

**Comment by romw** [comment]
**Commented by romw on 27 Aug 37431031 22:13 UTC**
At this time I see no reason to adjust the priority level of this bug, based on the current priorities of the project.

I'll change the assignment of this bug to David so he can make the final call.

As far as I'm concerned KSMarksPsych made the right call based on current priorities.

**Comment by romw** [comment]
**Commented by davea on 12 Sep 37431041 21:46 UTC**
Probably not worth doing unless more people request it

**Comment by romw** [comment]
**Commented by Fuzzy Hollynoodles on 22 May 37431161 04:26 UTC**
Replying to [davea](comment:5):
> Probably not worth doing unless more people request it

I'm sorry, David, but I strongly disagree with you. Do you give ticket no. 235 and 236 higher priority than this? Even ticket no 233 which is about spam has been given the priority as critical.

Of course it's embarrassing to you that your own moderator is abusing the system, so you should make up for this by giving this a higher priority, I think.


Thank you.

**Comment by romw** [comment]
**Commented by Ageless on 14 Feb 37431546 00:26 UTC**
Ticket #235 is Minor.
Ticket #236 is Minor. 
They are both set by Rytis himself, the person who programs these things. 

Ticket #233 got set to Critical by the original poster, at the original time he posted it. 

If you leave your ticket with only a complaint, we as moderators on Trac set your ticket to the correct component you complain about, (so it goes to the correct developer) and the priority it is set at according to the list we have set with the developers.

**Comment by Ageless93** [comment]
User hasn't been active on the forums, or as moderator since about 9 years. Closing this issue.
