### ISSUE TITLE
Review BOINC wrt the EU General Data Protection Regulation (GDPR)

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#2332]
Internally at CERN we are reviewing all services including BOINC. This issue will be used to report our findings related to BOINC and to discuss with organisations doing the same.

**Comment by Ageless93** [comment]
Leaving a link to the thing here, do read with a lot of free time and a lawyer present: http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=PL

**Comment by brevilo** [comment]
Closing this in favor of #2413 which now includes an already longer discussion.
