### ISSUE TITLE
Information about app version with id = 1 is not updated

### ISSUE THREAD

**Issue by progger** [BOINC/boinc#2333]
In validator log: missing app_version_id (1)
The reason in a strange check:
https://github.com/BOINC/boinc/blob/5c36ce25daae8532f44d81e9f4c5527bde5e0e51/sched/credit.cpp#L527-L540
This is a very old code, and perhaps this check is not relevant. As a result, information about app version with id = 1 is not updated.

**Comment by davidpanderson** [comment]
Thanks!  I did a PR with a fix.
