### ISSUE TITLE
[Error] Could not open directory '/dev/input/mice'

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2335]
Hi,

I got the following error on a headless Ubuntu Server 17.10.1. I installed the `boinc-client` package with the apt.
```
dir_open: Could not open directory '/dev/input/mice' from '/var/lib/boinc-client'.
```
I tried installing the `xorg` and the `xserver-xorg-legacy` packages, but didn't help.

**Comment by adamradocz** [comment]
If I add `--device=/dev/input/mice:/dev/input/mice` flag when run the docker, than everything is fine.

**Comment by adamradocz** [comment]
I reopen the issue, because the problem didn't go away.

**Comment by TheAspens** [comment]
Is that a error log message or does it prevent the client from running?

**Comment by adamradocz** [comment]
The client is running perfectly, it's in the error log.

**Comment by HelterBelter** [comment]
Same here, Raspian Stretch on headless Raspberry Pi Zero
---------------
tail -f /var/log/boincerr.log :
dir_open: Could not open directory '/dev/input/mice' from '/var/lib/boinc-client'.
dir_open: Could not open directory '/dev/input/mice' from '/var/lib/boinc-client'.
....
---------------
New error(line) ~ every second (estimated)
The errors start several minutes (seems for me it's ~ 7min) after starting the client (e.g. after a 'service boinc-client restart')

**Comment by lfield** [comment]
Please could you try with version 7.8.3

**Comment by adamradocz** [comment]
I use version 7.8.3

**Comment by lfield** [comment]
@LocutusOfBorg (Debian packager) For Fedora we are patching the code to disabled the idle detection. Are you doing the same? 
https://src.fedoraproject.org/rpms/boinc-client/blob/master/f/disabled_idle_detection.patch

**Comment by vincent-guesnard** [comment]
We encounter the same "bug" on Debian Stretch (Boinc v7.6.33)

**Comment by LocutusOfBorg** [comment]
@lfield I only read it now, but meh, looks like this code is not getting removed!

**Comment by JuhaSointusalo** [comment]
@LocutusOfBorg What do you mean?

**Comment by LocutusOfBorg** [comment]
I'm now applying https://github.com/BOINC/boinc/pull/2463/commits/0e16d026ce50fdadee8d3629bbdd95b5a5298416 on top of 7.10.3 release

**Comment by lfield** [comment]
@LocutusOfBorg The PR was actually merged. It was accidentally closed first but this issue was not updated when the PR was reopened and merged. See #2463
