### ISSUE TITLE
reference .desktop file

### ISSUE THREAD

**Issue by JuhaSointusalo** [BOINC/boinc#2339]
Different Linux distros have different ideas of what should be in .desktop file (the file behind the entry in start menu) for Manager. All the different versions could be upstreamed so that there is one reference file.

The most important part of the file is using `Path` to set working directory to BOINC's data directory so that Manager can find `gui_rpc_auth.cfg`. It would be nice if translation of the file was integrated with the rest of the BOINC translation system.

[Arch Linux](https://git.archlinux.org/svntogit/community.git/tree/trunk/boinc.desktop?h=packages/boinc)
[Debian](https://anonscm.debian.org/cgit/pkg-boinc/boinc.git/tree/debian/boinc-manager.desktop)
[Fedora](https://src.fedoraproject.org/rpms/boinc-client/blob/master/f/boinc-manager.desktop)
[Mageia](http://sophie.zarb.org/rpms/a43a82667e3b928558f576b6007cfc5b/files/3)
[Suse](https://build.opensuse.org/package/view_file/network/boinc-client/boinc-gui.desktop?expand=1)

**Comment by BryanQuigley** [comment]
I don't seem to need to set path - will have to test more cases.  Having trouble building boinc atm, but will try to integrate in future.

Currently testing with:
[Desktop Entry]
Version=1.0
Type=Application
Name=BOINC Manager
Exec=boincmgr
Icon=boincmgr
Terminal=false
Keywords=computation;science;
Categories=System;Monitor;GTK;
GenericName=BOINC monitor and control utility
GenericName[cs]=Monitorovací a ovládací nástroj pro BOINC
GenericName[de]=BOINC Überwachungs- und Kontrollprogramm
GenericName[pt]=Monitorização BOINC e utilitário de controlo
GenericName[pt_BR]=Utilitário de controle e monitoramento do BOINC
Comment=Configure or monitor a BOINC core client
Comment[cs]=Monitoruje a nastavuje klienta BOINC
Comment[de]=BOINC Basis Client konfigurieren oder überwachen
Comment[pt]=Configurar ou monitorizar o cliente básico do BOINC
Comment[pt_BR]=Configure ou monitore o cliente básico do BOINC

**Comment by JuhaSointusalo** [comment]
Unless you have empty GUI RPC password (Debian/Ubuntu style) or have linked `gui_rpc_auth.cfg` to your home directory (IIRC, openSUSE style) then I'm pretty sure you need to set `Path`.

**Comment by KeithMyers** [comment]
I am having issues with Ubuntu 18.04 LTS and Boinc Manager and client.  The manager doesn't have the Add to favorites right-click menu which would allow the app to dock like normal Linux apps.  This was never an issue with 16.04 and Unity desktop manager.  So the way the app is handled under Gnome desktop has changed.  I tried to create the .desktop file using your linked example.  Set the path to the BOINC folder on the Desktop.  That allowed me to dock to the app.  But when executed only the Manager window opens and does not start the client.

So can you tell me what I haven't done to get the Manager to start the client as it usually does?

**Comment by JuhaSointusalo** [comment]
@KeithMyers 

This issue is about adding a .desktop file to BOINC repository so that every distro don't have to come up with their own file, each differing a little bit from others. Your problem seems to more about general troubleshooting and it's best handled in forums. Please ask moderators there to move your posts to a new thread dedicated to your problem.

**Comment by KeithMyers** [comment]
I don't understand your post.  Which moderators?  I have been asking everywhere for help solving this issue.  This bug was referenced by Ageless as the likeliest place to get some response.

**Comment by truboxl** [comment]
This can be a blocker to https://github.com/BOINC/boinc/issues/2485 when creating [Flatpak](https://docs.flatpak.org/en/latest/conventions.html#desktop-files) and [AppImages](https://docs.appimage.org/reference/appdir.html#general-description) ...and maybe Snaps

**Comment by BryanQuigley** [comment]
Looking more into this and getting a proper install of it.. the image files in clientgui/res/templates/icons/Final Design .. would need to be reorganized similar to how was done in Debian.

See Icon section in https://salsa.debian.org/pkg-boinc-team/boinc/-/blob/master/debian/README.source

Any issues with reorganizing that area?

**Comment by BryanQuigley** [comment]
does anyone have an icon variant in SVG format? I can only find the whole logo in SVG. It would just make sense to include that - and we can generate the pngs/etc from it too.

**Comment by AenBleidd** [comment]
We have it in XML format (SVG packed in XML): https://github.com/BOINC/boinc/blob/master/android/BOINC/app/src/main/res/drawable/ic_boinc.xml

**Comment by BryanQuigley** [comment]
Thank you @AenBleidd !   Incorporated based on that version for the updated PR.

I think starting with an SVG and a 64x64 png is good enough.
