### ISSUE TITLE
Outbox for private messages

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#234]
**Reported by Rytis on 21 Jan 37428298 00:00 UTC**
Implement outbox where sent private messages would be stored.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/235

**Comment by romw** [comment]
**Commented by Ageless on 17 Sep 37882300 19:33 UTC**
Reassigning to David.

**Comment by AenBleidd** [comment]
Closing as subticket of #1963
