### ISSUE TITLE
Config: "Don't contact ref site" blocks "Get Project List"

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#2352]
With the increasing emphasis on having an up-to-date 'all_projects_list.xml' file (especially for autologin), is there any remaining justification for preventing the download of a new file when cc_config.dont_contact_ref_site is set?

https://github.com/BOINC/boinc/blob/master/client/acct_setup.cpp#L254

**Comment by TheAspens** [comment]
Yes.  The usage that I have seen for that flag is set when large users do mass deployments like WCG has worked with various corporations and other entities to do.  There security groups don't want the client talking to anything but the WCG project servers they have set it up to communicate with.  They also generally do not allow the people at the workstations to control the client either.

We could argue that the parameter is named poorly, but the use case above requires that these additional requests that the client makes continue to be disallowed.

**Comment by RichardHaselgrove** [comment]
OK. I've used the flag (for many years) to avoid being rude and pestering Google - I have better ways to diagnose the health of my personal internet connection. I obviously don't think like a large, secure, corporation!
