### ISSUE TITLE
Advanced view -> View menu has options indented

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2356]
In English, and therefore in all the translations, the Advanced view -> View menu has all the key combos after Notices one or more pixels indented. I've made a screen shot and added a straight line to it that shows it:
![still indented](https://user-images.githubusercontent.com/10869587/36342052-be2c37b0-13f8-11e8-8b0c-d5e23bf776cd.png)

It's not an optical illusion.

**Comment by AenBleidd** [comment]
There is no spaces in source file. Looks like this is a wxWidgets issue because of non-momspaced font.

![image](https://user-images.githubusercontent.com/3234209/36346137-77f733aa-1441-11e8-992f-08477950156b.png)

**Comment by Ageless93** [comment]
Yes, the last time I reported this via boinc_alpha for a 7.8 version, someone answered that they didn't see it in their Mac version either. I don't know how long it is already there, only started to notice it since I do the Dutch translations and those were off by two or three pixels. Also don't know if this is under Windows 7 x64 only, or also under any of the other flavours of Windows.

**Comment by AenBleidd** [comment]
I can see this behavior on Win8.1 also:
![image](https://user-images.githubusercontent.com/3234209/36359384-60951a50-1523-11e8-8ea3-8721d0636921.png)
Can't check on linux right now but really looks like wxWidgets Windows issue

**Comment by RichardHaselgrove** [comment]
As AenBleidd's code shows, the two chunks of text on each menu line are separated by a \t special character. I suspect that this means 'right justify the rest of the string':

![bm view menu](https://user-images.githubusercontent.com/14886436/36536844-4bfe37ac-17c6-11e8-8e90-369c62f8ed18.png)

The trouble is that some of the characters, notably P and S, are narrower in this font than N and D.

NNNNNNNNNN
PPPPPPPPPP
SSSSSSSSSS
DDDDDDDDDD

**Comment by AenBleidd** [comment]
There is nothing that could be done on our side (unless maybe just using the monotype font that I strongly don't want to) so I'm closing this ticket as 'wontfix'.
