### ISSUE TITLE
Windows Installer License Agreement

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2357]
In the blurb on the Windows Installer license agreement:

""This is free software. It is distributed under the terms of the GNU Lesser General Public License as published by the Free Software Foundation (http://www.fsf.org/). The source code may be obtained from the BOINC web site (http://boinc.berkeley.edu/)."
a) URLs should be HTTPS.
b) source code isn't available from the BOINC website, but from Github.

**Comment by RichardHaselgrove** [comment]
I have a slight worry about the source code link. This change is technically accurate, but if you visit the BOINC site first, you see front page links not only to the source code, but also to the Wiki instructions for using it and participating in the project. If you visit Github first, there isn't a corresponding back-link to the Wiki - just a bare link (minimal explanation) back to the link you're proposing to remove.

We should certainly back-port the fsf links to v7.10, irrespective of what we finally decide about our own sources and documentation.

**Comment by Ageless93** [comment]
The front page here (https://github.com/BOINC/boinc at the bottom) does show a link back to the BOINC web site, but for completeness, it'll probably need a link to the Compile Client page (https://boinc.berkeley.edu/trac/wiki/CompileClient). 

In any case, the blurb isn't correct in saying that the source code is at the BOINC website. So either the blurb should say that the source code is here and give a link to the compile client page, or it should say that links to the source code and how to build BOINC are available from the BOINC website.
