### ISSUE TITLE
Update "wiki/Installing_BOINC"

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2359]
The [https://boinc.berkeley.edu/wiki/Installing_BOINC](https://boinc.berkeley.edu/wiki/Installing_BOINC) webpage is outdated. 

- The Ubuntu ISO image is no longer available.
- In the "Build from source" section the "Building the BOINC Client Software (from the Unofficial BOINC wiki)" link no longer available.

**Comment by davidpanderson** [comment]
Thanks: I fixed the links.

**Comment by adamradocz** [comment]
Should I close the issue?
