### ISSUE TITLE
Update the general linux build

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2360]
On the [https://boinc.berkeley.edu/download_all.php](https://boinc.berkeley.edu/download_all.php) webpage, the latest general linux build is 4 years old. On a Debian or Red Hat based disto is not a problem, but on any other linux distro is a bummer.

**Comment by davidpanderson** [comment]
We need to find someone to do the general Linux build.

**Comment by lfield** [comment]
You can extract the tar file from an rpm with the rpm2cpio command. The question is would that be suitable?

**Comment by JuhaSointusalo** [comment]
> You can extract the tar file from an rpm with the rpm2cpio command. The question is would that be suitable?

Debian and Red Hat based distros used to have slightly different names for OpenSSL library files. I don't know if that is still the case. If it is then a general build would have to have at least some of it statically linked.

**Comment by lfield** [comment]
I have attempted to do a general Linux build on my Fedora 26 machine. 
http://cern.ch/lfield/boinc-7.9.2.tgz

`./_autosetup
./configure   --disable-silent-rules  --enable-client-release   --disable-server   --disable-fcgi   --enable-unicode   --with-wx-config=/usr/bin/wx-config-3.0   --with-ssl   --with-x   STRIP=:   DOCBOOK2X_MAN=/usr/bin/db2x_docbook2man   "CXXFLAGS=$(pkg-config gtk+-x11-3.0 --cflags --libs) -DNDEBUG"
make
make install -p DESTDIR=/home/fedora/target
cd /home/fedora/target/
tar -zcf ../boinc-7.9.2.tgz *
`
Comments more than welcome

**Comment by TheAspens** [comment]
Laurence, the older instructions that were previously used for building it are available at https://boinc.berkeley.edu/trac/wiki/CompileClient

I tried to use your version on Debiian 7 - Wheezy and got:

```
knreed@cirrus:~/BOINC/usr/local/bin$ ldd boinc_client 
./boinc_client: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./boinc_client)
./boinc_client: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./boinc_client)
./boinc_client: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./boinc_client)
./boinc_client: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./boinc_client)
```

And on Red Hat Desktop 7 
```
[knreed@oc7811586721 bin]$ ldd boinc_client 
./boinc_client: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./boinc_client)
./boinc_client: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./boinc_client)
./boinc_client: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./boinc_client)
```


The version that I build on my Red Hat Desktop 7 gave me
```
[knreed@oc7811586721 bin]$ ldd boinc_client 
./boinc_client: /usr/lib64/libstdc++.so.6: version `GLIBC_2.15' not found (required by ./boinc_client)
./boinc_client: /usr/lib64/libstdc++.so.6: version `GLIBC_2.14' not found (required by ./boinc_client)
```
so I have some work to do as well.

I/we should probably start with just using the existing virtual machines that were used previously.  https://boinc.berkeley.edu/trac/wiki/VmCompatibility which I will try soon.

**Comment by AenBleidd** [comment]
Should this issue just be closed? In any case this file is out-dated and there are more easy and common used ways to install BOINC?

**Comment by AenBleidd** [comment]
I'm closing this ticket in favor of package manager installations of BOINC for specific *nix OS.
If someone thinks that general linux installations should be updated feel free to reopen this ticket,
