### ISSUE TITLE
BOINC User Manual Wiki: when using https, CSS breaks on pages

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2368]
When switching from its default http (1) to https (2) on pages of the BOINC User Wiki, this breaks CSS and everything looks bad. 

I had a conversation with David about this in January 2017, and the decision then was not to fix this but to deal with it later. Later in 2018 major browsers will start showing http pages as not secure, so I suppose it's time to deal with it now, before that happens. (3)

[1] http://boinc.berkeley.edu/wiki/Installing_BOINC_on_Ubuntu
[2] https://boinc.berkeley.edu/wiki/Installing_BOINC_on_Ubuntu
[3] https://www.techspot.com/news/73202-chrome-start-marking-http-not-secure.html

**Comment by AenBleidd** [comment]
Currently both pages [1] and [2] looks similar so I suppose it was fixed some time ago.
