### ISSUE TITLE
Forums not secure due to mixed content

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2369]
A lot of the BOINC forum threads are not secure, due to images in the thread or in people's signatures and other links being loaded via http instead of https. Browsers will then show that this link isn't secure, even though the forums do use https. 

For example: https://boinc.berkeley.edu/dev/forum_thread.php?id=11763
This shows for my browser (Firefox):
![not-secure 3](https://user-images.githubusercontent.com/10869587/36482519-df5ca8d4-1713-11e8-9f6d-bd7bb19f098e.png)
![not-secure 2](https://user-images.githubusercontent.com/10869587/36482518-df5b6e6a-1713-11e8-9d02-944a51b16b32.png)

**Comment by AenBleidd** [comment]
Not sure this is smth that we could/should fix.
I'm not a Firefox user but I've never see this on Chrome
Closing this as 'wontfix'
