### ISSUE TITLE
7.9.2, copyright 2003-2017

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2372]
The Help->About BOINC Manager window still says Copyright 2003-2017. It's 2018. 
Should be adapted in DlgAbout.cpp, line 192.

**Comment by JuhaSointusalo** [comment]
And program file properties, and installer properties, and Android GUI, and and and...

Should the branded installers be updated even if there is no plan to release branded installers?

Did you know that if you search the entire BOINC codebase for lines containing the word "copyright" you get 3120 hits? I think we need a bit shorter list of files to update.

**Comment by Ageless93** [comment]
Those are all in the leading blurb in .the C++ files, probably others as well. A lot of them (344) have copyright (C) 2008. There are a lot of differing copyright dates all around the source code. However, the one I pointed out is in the compiled BOINC Manager About window, the one people will see. That one needs to be adapted to the present year.

**Comment by JuhaSointusalo** [comment]
>
> Those are all in the leading blurb in .the C++ files
>
Most of them yes. Since there were other files to update too how would one
find them? Oh that's easy, simply grep the codebase for 'copyright'. Ok,
not that easy...

**Comment by AenBleidd** [comment]
As I know, the common practice is to change year in copyright header when
you touch that particular file only.
It is now so hard to update all files but do we really need to do this?

Best regards,
Vitalii Koshura

2018-02-23 16:29 GMT+02:00 Juha Sointusalo <notifications@github.com>:

**Comment by JuhaSointusalo** [comment]
With other files I mean Windows resource files *.rc, InstallShield files
*.ism, that Java file whichever it it. Plus any other file that needs
updating. I don't mean the copyright/license blurb at the top of source
files.

Since there isn't a list of files to update that I know of, the best I can
come up with is to search the codebase for keywords like 'copyright',
'(c)', or year numbers and then go through the results, compile that list
and write it down somewhere.

**Comment by AenBleidd** [comment]
Make sense. Thanks

Best regards,
Vitalii Koshura

2018-02-23 16:45 GMT+02:00 Juha Sointusalo <notifications@github.com>:

**Comment by RichardHaselgrove** [comment]
> ...and write it down somewhere?

Just over 2,500 instances of "Copyright (c)" at tag client_release_7-9-2 attached

[Copyright_strings.zip](https://github.com/BOINC/boinc/files/1759046/Copyright_strings.zip)

**Comment by AenBleidd** [comment]
@RichardHaselgrove, I made pull request #2378 
Please verify whether it contains all necessary changes.
Thanks
