### ISSUE TITLE
Make About BOINC Manager copyright year increase automatically

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2380]
Since we collectively forget each year to increase the copyright on BOINC Manager's About window, how about having it increase automatically? Is that a possibility, have it read it from the computer's clock or something? That way we don't need to redo translations on it every year either.  

Super trivial issue, until it's January again and someone's about to release 7.14...

**Comment by truboxl** [comment]
Maybe make a pull request bot that when Jan 1 of every new year hits, will create a PR that changes the date of all the files... 🤣

**Comment by Vulpine05** [comment]
Sounds simple enough.  I would think when a release version is published, the year would be "locked in" to the code, similar to how we have (or are going to) lock in the wxWidgets version when a release is published?

In other words, if this was implemented and if five years from now someone builds the source code of a release published today, the copyright year should say 2022, not 2027.

**Comment by IRainman** [comment]
The macro __DATE__ and __TIME__ is available, ;) we can simplify use date line for copyright, after cut only last 4 symbols from string.

**Comment by CharlieFenton** [comment]
> The macro __DATE__ and __TIME__ is available, ;) we can simplify use date line for copyright, after cut only last 4 symbols from string.

Does that show the date of the last edit (which is what we want) or does it always show the current date?

**Comment by CharlieFenton** [comment]
According to [this](https://www.cprogramming.com/reference/preprocessor/__DATE__.html) website:
> __DATE__ is a preprocessor macro that expands to current date (at compile time) in the form mmm dd yyyy (e.g. "Jan 14 2012"), as a string. The __DATE__ macro can be used to provide information about the particular moment a binary was built.

Since we have the copyright in *.h files as well as *.cpp, would this change the dates of the included files even though the have not been edited / changed?

**Comment by AenBleidd** [comment]
@CharlieFenton, this is for `About` window only and has nothing to do with the copyrights in the headers of source files
