### ISSUE TITLE
Client: VBox detection fails on Windows 8.1

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#2383]
From user report at http://boinc.berkeley.edu/dev/forum_thread.php?id=8649&postid=84964

User is running Windows 8.1 (64 bit), which reports the operating system to be

`OS: Microsoft Windows 8.1: Core x64 Edition, (06.03.9600.00)`

This platform fails the 64-bit detection test at https://github.com/BOINC/boinc/blob/master/client/client_state.cpp#L262, resulting in the (false) Event Log message "Can't detect VirtualBox because this is a 32-bit version of BOINC".

Edit - I can't find the primary_platform string stored anywhere in the user data folders, so I can't ask the reporting user to look it up and tell us what his is.

**Comment by JuhaSointusalo** [comment]
The code in question is
```
#if defined (_WIN32) && !defined(_WIN64)
        if (!strcmp(get_primary_platform(), "windows_x86_64")) {
            msg_printf(NULL, MSG_USER_ALERT,
                "Can't detect VirtualBox because this is a 32-bit version of BOINC; to fix, please install a 64-bit version."
            );
        }
#endif
```
The message is included only in Windows 32-bit builds. Either the user installed 32-bit version or something went wrong in the build process.

The startup message

`27-Feb-2018 17:04:03 [---] Starting BOINC client version 7.9.2 for windows_x86_64`

is misleading in this case. It tells what the client detected, not how it was built.

**Comment by RichardHaselgrove** [comment]
User has confirmed that a 32-bit version was running, although he had thought he had downloaded the 64-bit installer. We can probably close this, unless anyone wants to comment on the startup message?

Perhaps split it into two:
Starting 32-bit BOINC client... (build version)
Running in 64-bit environment... (operating system)

**Comment by JuhaSointusalo** [comment]
I was thinking about that. It's a bit more complicated than 32/64-bit.

Linux client with Wine for running Windows programs:
```
Starting BOINC client version 7.9.2 for x86_64-pc-linux-gnu
Platforms: x86_64-pc-linux-gnu, i686-pc-linux-gnu, windows_x86_64, windows_intelx86
```
Or FreeBSD client with Linux and Windows emulation.

**Comment by RichardHaselgrove** [comment]
Let's transfer the discussion to #2386
