### ISSUE TITLE
How to recognize the bit-depth of the client.?

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2386]
In all these years I believed that when BOINC stated in the event log "Starting BOINC client version 7.9.2 for windows_x86_64" that the windows_x86_64 part meant that the client was 64 bit, running on Windows. But through a comment by Juha it appears this is not the way. It shows what operating system it has detected, in the above case Windows 64 bit, but not necessarily that the client is 64 bit. 

When installing the 32 bit client on a 64 bit Windows, it will start with "Starting BOINC client version 7.9.2 for windows_x86_64", while it will only report "windows_intex86" when installed on a 32 bit Windows.

Now then, where can we find information about the bit-depth of the client? 
In BOINC Manager's About window it says via Version: N.N.N (x86) or N.N.N (x64)
However, when one cannot start BOINC Manager for some reason and one has to check via the command line with boinc.exe --version, the 32 bit version will report N.N.N windows_intelx86, while the 64 bit version will report N.N.N windows_x86_64. Here the windows_* indicate the bit-depth of the client, not that of the operating system. That is confusing, to me anyway.

So I am putting this discussion down, with questions. For user-friendliness, and for ease of mind of us oldies: 

1. Should we continue to have the client start by saying what OS it detected, even when that same detection is later on in the log written with the full name of the OS itself? 
I.e. _OS: Microsoft Windows 7: Ultimate x64 Edition, Service Pack 1, (06.01.7601.00)_
2. Or should the client start with information for the user what client he installed, with the same information as it is shown on the installer he used? 
I.e. _"Starting BOINC client version 7.9.2, 32-bit (x86) for Windows"_, _"Starting BOINC client version 7.9.2, 64-bit (x86_64) for Windows"_ 
3. Or is there a third option we can use? 

In any case, if 1. then IMO the command line version reporting is incorrect. That should be N.N.N intelx86/x86_64, not including the windows_ part.

**Comment by davidpanderson** [comment]
The current behavior is wrong; I'll fix it.

**Comment by Ageless93** [comment]
Thanks! :+1: 
But what are you going to fix? The event log message or the command line message? :)

**Comment by davidpanderson** [comment]
I fixed the event log message.
I didn't change the output of boinc --version.

On Fri, Mar 2, 2018 at 12:49 AM, RichardHaselgrove <notifications@github.com
