### ISSUE TITLE
Can't detect VirtualBox because this is a 32-bit version of BOINC; to fix, please install a 64-bit version.

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2389]
_Can't detect VirtualBox because this is a 32-bit version of BOINC; to fix, please install a 64-bit version._ is an error message in BOINC that one encounters when one has tried to install a 32bit version of BOINC + 32bit Vbox on a 64bit OS. 

As I found out through installing boinc_7.9.2_windows_intelx86_vbox.exe on my Windows 7 x64, a 32bit version of VBox will not even install on a 64bit OS. It is silently dropped. No warning messages, no errors during the installation. For the untrained eye the installation was done perfectly. Things were unpacked, the VBox installer closed without errors, the BOINC installer started without problems. 

Perusing through Windows Event Viewer, Windows Logs->Application, I found mostly informational messages and one error: 

```
Information: Beginning a Windows Installer transaction: C:\Users\Ageless\AppData\Local\Temp\{2A0AADE7-93C3-4409-8E38-FE0CA571F879}\{99360D9A-6C66-4E9E-B1DA-CFBECEBD9678}\VirtualBox-5.2.6-r120293-MultiArch_x86.msi. Client Process Id: 5980.
Error: Product: Oracle VM VirtualBox 5.2.6 -- This application only runs on 32-bit Windows systems. Please install the 64-bit version of Oracle VM VirtualBox 5.2.6!
Information: Product: Oracle VM VirtualBox 5.2.6 -- Installation failed.
Information: Windows Installer installed the product. Product Name: Oracle VM VirtualBox 5.2.6. Product Version: 5.2.6. Product Language: 1033. Manufacturer: Oracle Corporation. Installation success or error status: 1603.
Information: Ending a Windows Installer transaction: C:\Users\Ageless\AppData\Local\Temp\{2A0AADE7-93C3-4409-8E38-FE0CA571F879}\{99360D9A-6C66-4E9E-B1DA-CFBECEBD9678}
\VirtualBox-5.2.6-r120293-MultiArch_x86.msi. Client Process Id: 5980.
```
Starting BOINC after this failed VBox installation yields the error _Can't detect VirtualBox because this is a 32-bit version of BOINC; to fix, please install a 64-bit version._. 

The message implies that VirtualBox is installed, but just cannot be found. It hasn't been installed. 
It also implies that by installing a 64bit version of BOINC, the 32bit version of VBox will work... which it still won't. So the message needs to include that VirtualBox didn't install correctly and that for everything to work, a 64bit version of VBox is needed on a 64bit OS. 

Whether BOINC is 32bit or 64bit here, I don't think matters. 32bit BOINC can run 64bit applications on a 64bit system/OS, so why wouldn't it be able to work with a 64bit VBox? (I am not testing that scenario out.)
Calling this critical and not a blocker, because in essence, BOINC runs fine. It just won't work with VBox in this scenario. 
I'll be putting the error logging of the installer in a separate issue.

**Comment by AenBleidd** [comment]
Since we do not support x86 platforms anymore (latest BOINC installers are x64 only) I see no reason to support use case and fix this ticket.
Closing it as 'won't fix'.
