### ISSUE TITLE
Check return codes everywhere

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#239]
**Reported by elfring on 5 Jan 37430807 07:33 UTC**
Some checks for return codes are missing.

Examples:[you like to add more error handling for return values from "[http://opengroup.org/onlinepubs/009695399/functions/malloc.html malloc]([BR]]
Would)" like in the function "[read_ppm_file](source:/trunk/boinc/api/gutil.C@10130#L574)" and from "[fwrite](http://opengroup.org/onlinepubs/009695399/functions/fwrite.html)" in the function  "[copy_stream](source:/trunk/boinc/lib/parse.C@12151#L136)"?

Migrated-From: http://boinc.berkeley.edu/trac/ticket/240

**Comment by romw** [comment]
**Commented by davea on 9 Apr 37524427 12:53 UTC**
I added a few.  Not feasible to do them all right now.

**Comment by romw** [comment]
**Commented by elfring on 9 Nov 37682454 17:46 UTC**
I suggest to avoid unchecked function calls.[you like to detect every error situation as early as possible?

There are still some ignored error codes from functions like [source:/trunk/boinc/api/gutil.C@10130#L583 fread]([BR]]
Would).[the way: Is it a bug that there is no [http://en.wikipedia.org/wiki/Switch_statement#Examples break]([BR]]
(By) instruction at the end of "case '3':"? Is the fall-through really intended?)

**Comment by romw** [comment]
**Commented by Nicolas on 11 Mar 37682605 03:33 UTC**
Fall-throughs on switch blocks should always be noticed with a `//fallthrough` comment in place of the `break;`.

Also, it's clear it's not feasible to check error codes on every function call. That's why [handling](WikiPedia:Exception) were invented. BOINC should really start using them...

**Comment by romw** [comment]
**Commented by Nicolas on 30 Jul 37682619 18:40 UTC**
Oops, the link on my previous comment is broken. I meant: That's why[exceptions](WikiPedia:Exception_handling) were invented.

**Comment by romw** [comment]
**Commented by elfring on 23 Nov 37692934 08:53 UTC**
Each return value should be checked to see if an exception object should be thrown. Are there any situations where the reaction "[exit(errno)](http://opengroup.org/onlinepubs/009695399/functions/exit.html)" or "[abort()](http://opengroup.org/onlinepubs/009695399/functions/abort.html)" would be more appropriate?

Would you like to reduce the efforts for [error code checking](http://cexcept.sourceforge.net/) by an [exception class hierarchy](http://dietmar-kuehl.de/mirror/c++-faq/exceptions.html#faq-17.1)?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by ChristianBeer** [comment]
This applies to the complete BOINC codebase. There are static code analysis tools that we use that flag unhandled return values. Its the job of each developer to fix them.

**Comment by elfring** [comment]
How many effects can be seen from the mentioned source code analysis tools on corresponding software evolution?

**Comment by ChristianBeer** [comment]
Fixing code smells is more like a standing item that should be covered in a code of conduct or how to contribute guide. I already fixed a lot of issues found by https://scan.coverity.com and each committer gets an email from https://scrutinizer-ci.com/g/BOINC/boinc/ if there is a critical problem with his/her code so it can be fixed.

References to codefiles in this issue are broken because of the trac to github conversion. Feel free to open a new issue about concrete code or just a general policy discussion. I personally would prefer to receive pull requests for issues still listed in the https://scan.coverity.com report (account needed to view defects).

**Comment by elfring** [comment]
Did the mentioned source code analysis tools find update candidates like the following?
- [fread](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fread.html "Binary input") ⇒ [copy_stream](https://github.com/BOINC/boinc/blob/ca80cac75af668dcea9aff29ded70abdff70c573/lib/parse.cpp#L136)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [GetCurrentUserSID](https://github.com/BOINC/boinc/blob/5c36ce25daae8532f44d81e9f4c5527bde5e0e51/clientsetup/win/utils.cpp#L32)

There are also further software design approaches to consider, aren't there?

**Comment by ChristianBeer** [comment]
I can't follow you. If there is a problem with how return codes are handled please open a new issue or pull request stating the problem and a proposed solution.

If you want to start a discussion about the BOINC software development process please post to the boinc_dev mailing list.

**Comment by elfring** [comment]
I dared to point remaining open issues out.
* Would you like to fix each questionable implementation detail manually?
* How do you think about to achieve better results by higher level software development tools (besides automatic source code analysis)?
