### ISSUE TITLE
Windows + VirtualBox installer, when errors encountered, or some part didn't install, show that to the user

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2390]
Referencing #2389.
When installing VirtualBox from the combined installer with BOINC, and any errors are encountered through which VirtualBox isn't installed, the user isn't told about this. 

I think we need a screen at the end of the installer, prior to the screen or perhaps even on the screen where BOINC Manager can be started, what the outcome was of the installers, if all parts have been installed correctly. 

Is this an option in the presently used installer technology?

**Comment by AenBleidd** [comment]
There will be no VBox bundled version of the BOINC installer: it is planed that the next release will include WSL+Docker support. VBox tasks will still be supported if the WSL is disabled/not supported.
