### ISSUE TITLE
No hardware resource selected in project preferences, on initialization BOINC gets work anyway

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2391]
Prior to using a test version of BOINC with auto-attach, I set Seti@Home to not use the CPU or any of the GPUs via Seti's project preferences. In the account_setiathome.berkeley.edu.xml file this shows as:
```
<no_cpu>1</no_cpu>
<no_ati>1</no_ati>
<no_cuda>1</no_cuda>
<no_intel_gpu>1</no_intel_gpu>
```

When BOINC next started on its first initialization run, it asked for 1 task for my AMD GPU. 
Later, after lots of uninstalling & reinstalling the client multiple times, and switching between 32bit and 64bit clients, one of the initialized work requests was for 518400.00 seconds for the AMD GPU. 

All this time my project preferences were still the same as above, do not use any hardware resource. 
What the event log also shows, after every scheduler contact is _Your current settings do not allow tasks from this project.  To fix this, you can change Project Preferences on the project's web site._ It showed this after the scheduler contact that gave it the 518400 seconds worth of work. And since that initialization BOINC will hold true to the preferences set, it won't ask for work because no resources checked. 

Just never on the first request. Code added through https://github.com/BOINC/boinc/commit/71c7e7a74b82e49b2da73869442e13bf06cb73c3 says:
 - client/scheduler/web: add per-project preferences for whether to accept CPU, NVIDIA and ATI jobs.
    These prefs are shown only where relevant: e.g., only for processor types for which the project has app versions, and if it has versions for only one type, no pref is shown.

    These prefs affect both client and scheduler. The client won't ask for work for a device blocked by prefs,
    and the scheduler won't send it.

    This replaces earlier optional project-specific prefs for "no CPU jobs" and "no GPU jobs". (However, these prefs continue to be honored on the server side).

Can we make BOINC read and use the project preferences if they are already available in the account_*.xml file, even when it's in init mode? And can the scheduler be made more intelligent that when the user has set his preferences up like this, that no work is sent, even when work is asked?

**Comment by AenBleidd** [comment]
This is a very rare edge case, and in a normal workflow this should not ever happen.
Thus there is no reason to put efforts to fix that.
Closing this for now without my further actions.
