### ISSUE TITLE
Upload server: reject incoming files if backing storage can't accept them

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#2411]
In most cases, BOINC upload servers which fail, fill up, are undergoing maintenance, or are unreachable, reject uploads immediately - either during http header negotiation, or via an http timeout.

But in some cases, the upload server accepts the entire file - which can be 100 MB or more - and only then responds with a failure message. This means that the entire file has to be retried at a later stage, and for individuals with metered connections, or for users in countries where metering is customary, costs may become higher than they budgeted for.

My understanding is that the problem arises when the BOINC upload server acts as a gateway to a separate background data storage facility. If the storage facility is rejecting transfers ('Disk quota exceeded' in a current case), the BOINC server should reject offered uploads at the header negotiation stage to avoid wasted bandwidth and expense.

Source reference: http://boinc.berkeley.edu/dev/forum_thread.php?id=12349

**Comment by JacobWKlein** [comment]
I would appreciate something to mitigate this problem. I'm not on a metered connection, but I've got 4 PCs all uploading results over and over, and my local network gets badly congested when the upload pipe is saturated - sometimes hard to use webpages even.

I hope the change gets implemented to avoid the upload altogether, if the backing store is incapable of accepting.

Thanks,
Jacob Klein

**Comment by ChristianBeer** [comment]
This is not a server problem. The upload_handler understands two requests:

1. get_file_size: The client asks about the size of the file. This request also checks if there is enough space for new files and reports an error if there isn't. This is used to restart an upload at the point where the previous upload failed for example.
2. file_upload: The client sends some meta information about the file which is immediately followed by the data of the file. Even if the server can't write the data to disk it has to consume the data (it has to be transfered) because the server can't send the client a response while the client is still sending data to the server.

Ideally the client should first ask the server about the file size and then send the data. If for some reason the upload handler thinks there is enough space in step 1 it can still fail in step 2 because in reality there isn't enough space. Maybe we should make a more prominent note for projects to monitor the upload server disk capacity. This is a critical metric for every project.

**Comment by RichardHaselgrove** [comment]
The full error reported today at CPDN was
```
Error reported by file upload server: can't write file (name): Disk quota exceeded
```
Looking back through my own logs, I found these - all from LHC, around December/January.

```
Error reported by file upload server: can't open file (name): No space left on device
Error reported by file upload server: Server is out of disk space
Error reported by file upload server: (name) locked by file_upload_handler PID=-1
```
At this distance, I can't remember whether the LHC errors were reported at the beginning or the end of the transfer, and I have a fast upload line so the log timings hardly help.

Both of these projects rely on shared external data stores managed by Oxford University and CERN, respectively. My understanding was that the 'Error reported...' from an external device was different from internal space checks, but I'll defer to anyone with more specific knowledge than me.

**Comment by RichardHaselgrove** [comment]
@ChristianBeer:

This problem has been discussed (at least) twice in BOINC's history:

http://boinc.berkeley.edu/trac/ticket/133
http://boinc.berkeley.edu/trac/ticket/139

The first of those resulted in the fix you've described (c0c6cf779d7d31744336075232c92e99fdd2be87) - which isn't working for CPDN and LHC. That's why I feel that the problem arises when backing storage fails, not when the actual upload server has a local problem.

**Comment by ChristianBeer** [comment]
The upload server might not be able to detect if the storage is accessible. It depends on how the storage is connected to the upload server. Currently it should work with local storage and NFS connected storage. I know that WCG also uses network storage for uploads but I don't know if they modified the upload handler to accommodate for that. In the end this is setup specific and each project affected needs to provide some more information on what failed and possibly how a better detection should look like for this use case.

**Comment by RichardHaselgrove** [comment]
Adding another data point: Einstein@Home is (21 November 2018) accepting the full content of upload files to the upload server, but then responding with

504 Gateway Time-out

and backing off the upload for further retries at a later date.

**Comment by AenBleidd** [comment]
While the idea is good in general, there is no clear and easy way to implement such a functionality.
Also, nowadays there are almost nobody who is still on the metered connection, so there is no real reason trying to implement some complex solution.
