### ISSUE TITLE
[Linux] Provide option to use regular socket (maybe in /run?) instead of abstract socket

### ISSUE THREAD

**Issue by chiraag-nataraj** [BOINC/boinc#2434]
Given that abstract sockets are extremely hard to deal with when it comes to sandboxing (it's not always possible or desirable to set up a new network namespace), could there be a preference to switch to using a regular unix socket instead for boincmgr?

**Comment by JuhaSointusalo** [comment]
What do you mean with abstract socket?

If you are thinking of communication between client and Manager then client and boinccmd can already use Unix sockets. Start the client with `--gui_rpc_unix_domain` and use `--unix_domain` with boinccmd. Looks like Unix socket support has not been implemented in Manager.

**Comment by chiraag-nataraj** [comment]
Yeah, I'm thinking of the communication between client and manager. Ah, didn't see that (it's not in the manpages for boinc yet?). I guess I'd like to see Unix socket support in Manager :slightly_smiling_face:

**Comment by JuhaSointusalo** [comment]
> it's not in the manpages for boinc yet?

`--help` tends to be more up-to-date.

**Comment by chiraag-nataraj** [comment]
Actually, hold on. If I understand correctly, `--gui_rpc_unix_domain` is talking about using a socket instead of binding to a port. What I'm talking about is the abstract socket that boincmgr creates when it launches. So for example, try the following:
1. Run `sudo ss -xap | grep '@'`, which will show you the currently bound abstract sockets.
2. Launch `boincmgr`
3. Re-run `sudo ss -xap | grep '@'`, which should show a new abstract socket (in my case, it shows up as `@/tmp/user/1000/dbus-<something>`) which is owned by `boincmgr`.

**Comment by davidpanderson** [comment]
I don't think the manager explicitly creates a socket when it launches.

It's possible that the WxWidgets "wxMutex" class, which the manager uses,
is implemented using sockets on some platforms.

**Comment by chiraag-nataraj** [comment]
Hmmm, okay. It seems to be something related to dbus based on the name of the socket, but it doesn't look like the manager is actually spawning a dbus daemon (for example). I will do an `strace` on it and try to figure out what exactly is creating the socket.

**Comment by chiraag-nataraj** [comment]
Okay, so after running `strace`, I find these lines:
```
boincmgr.3576:bind(7, {sa_family=AF_UNIX, sun_path=@"/tmp/user/1000/dbus-Rx3NdT4A"}, 31) = 0
boincmgr.3576:getsockname(16, {sa_family=AF_UNIX, sun_path=@"/tmp/user/1000/dbus-Rx3NdT4A"}, [128->31]) = 0
```
`3576` is the main `boincmgr` process (not something it spawns, like `WebKitWebProcess`, for example). There is also some short-lived process (`3677` in my case) which connects to the socket. I've attached the `strace` output for both the main process and `3677`.
[boincmgr.3576.txt](https://github.com/BOINC/boinc/files/1864419/boincmgr.3576.txt)
[boincmgr.3677.txt](https://github.com/BOINC/boinc/files/1864420/boincmgr.3677.txt)

**Comment by JuhaSointusalo** [comment]
Try running Manager under debugger and set breakpoint on `bind` or `connect` or any relevant function. Then get a stack trace. It's hard to tell from strace output what the Manager was doing.

Anyways, Manager doesn't use D-Bus directly and wxWidgets doesn't either. It could be GTK+ or WebKit. I don't think we have much control over those.

**Comment by chiraag-nataraj** [comment]
>Anyways, Manager doesn't use D-Bus directly and wxWidgets doesn't either. It could be GTK+ or WebKit. I don't think we have much control over those.

Interestingly enough, these calls seem to be originating from wxWebViewWebKit - it apparently wants to set up a WebExtension server(!!!)

**Comment by chiraag-nataraj** [comment]
Alright I will be closing this - I guess there isn't much to be done at this end :'(
