### ISSUE TITLE
[Manager] Auto-reconnect to remote client without user prompt

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#2440]
- Add new option 'Ask user to reconnect to remote client'
- Option should be checked by default to save old behavior on application upgrade
- When option is off show prompt to user

**Comment by davidpanderson** [comment]
I don't understand this.  What is the problem and solution?

**Comment by RichardHaselgrove** [comment]
If you use BOINC Manager to monitor a remote computer, and the remote client restarts - maybe a power failure, maybe you saw something remotely that needs attention locally - the local manager loses connection and needs manual intervention before re-connecting.

This would allow auto-recovery, aka persistent connection.

**Comment by davidpanderson** [comment]
This potentially applies to the local case too, right?

How about a title like "Reconnect if client fails"?

**Comment by AenBleidd** [comment]
> This potentially applies to the local case too, right?

No, this doesn't apply to the local case because there is the code at clientgui/BOINCBaseFrame.cpp:544
to restart client and reconnect to it automatically if there is such need.

In case of remote client it always prompt user that can be annoying.

> How about a title like "Reconnect if client fails"?

From my POV this title is confusing because if client fails in case of local client Manager will try to reconnect automatically and in case of remote client it will prompt user asking whether to reconnect or not.
