### ISSUE TITLE
client download error Permanent HTTP error

### ISSUE THREAD

**Issue by JohnSuuAries** [BOINC/boinc#2442]
hello

when the client try to download application and inputs files. i got 

Permanent HTTP error

so i check the server and i find there is no application under the PROJECT/download/ . i also check the log. i find client send a request   http://xxxx.com/download/APP_NAME. just copy the application from PRJECT/apps/APP_NAME/VERSION/x86_app_darwin/APP_NAME to PROJECT/download/ APP_NAME and it's working fine.

sorry...im not good at english .....

i want to know is this a bug??
if client always access http://xxxx.com/download/APP_NAME. how can i deal with the architecture? like linux windows mac ....

can somebody help me.

thanks.

**Comment by JohnSuuAries** [comment]
is the server. i find this:

<file_info>
    <name>test</name>
    <url>http://server.xxxxs.com/xxxx/download/test</url>
    <executable/>
    <file_signature>
ccc8948fb1b199cad84767c1a9be1b1fa791b8c1387a92ca70de0d7363918144
608c9296570adb1af266812ac5588211f42b66b5e60024b5099716e0e39ef356
5c01dbcc26ab5510e67cff3de90668425f5ecf112f6c17808d3d0e57d48a349d
d2f429cc9e17a3c127a9bd9f38fd72ce3645af2dedd8ce106e708ffb70f9e937
.
    </file_signature>
    <nbytes>404360</nbytes>
</file_info>
<app_version>
    <app_name>test</app_name>
    <version_num>100</version_num>
    <api_version>7.11.0</api_version>
<file_ref>
    <file_name>test</file_name>
    <main_program/>
</file_ref>
</app_version>


at this line 

  <url>http://server.xxxxs.com/xxxx/download/test</url>


it is some mistake?

**Comment by AenBleidd** [comment]
Not sure this is smth relevant anymore.
Closing it as 'wontfix'.
If this is still an issue - please reopen.
