### ISSUE TITLE
[Client GUI] Add Project wizard doesn't populate all fields

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#2444]
This with v7.9.3 under Windows 7/64. When the 'Attach project' wizard is first opened, the fields for Research area, Organisation, and Web site are blank.

![wizard initial load](https://user-images.githubusercontent.com/14886436/38204316-679c3dea-369a-11e8-9d52-3256ce27bba2.png)

After viewing other projects, or changing the category filter, the missing fields are fully populated.

![wizard reselect](https://user-images.githubusercontent.com/14886436/38204358-92924670-369a-11e8-999b-5799ca3292f7.png)

**Comment by AenBleidd** [comment]
I'll take a look at it today.

**Comment by AenBleidd** [comment]
I found the issue:

When showing info about every project we truncate these strings to fit the window but when Wizard is launched it is not created fully and has zero size, so the length of the text become zero too.

I'll try to find some solution next days (hopefully today but who knows)
