### ISSUE TITLE
Remove code related to browser cookies from manager

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2454]
At one point we experimented with auto-attach features using web browser cookies.  We abandoned this because the way that browsers store cookies changes all the time and is undocumented.

Remove this code (e.g. browser.cpp) from the manager, and remove related stuff from GUI RPCs and the client.

**Comment by CharlieFenton** [comment]
Does GridRepublic no longer use this method?

**Comment by davidpanderson** [comment]
If they are it doesn't work anymore, at least on Chrome.

**Comment by CharlieFenton** [comment]
@davidpanderson Did Matt Blumberg ever respond to your email of June 29 where you wrote:
> Is anyone (WCG?  Gridrepublic? Charity Engine?) using this feature

If not, I suggest asking him again before removing this code. 

> it doesn't work anymore, at least on Chrome.

I don't have Chrome, so I can't test it here. You might want to ak Matt Blumberg about that, too.

**Comment by AenBleidd** [comment]
Fixed via #3954
