### ISSUE TITLE
No automatic benchmarks upon CPU switch

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2456]
Yesterday I've been busy switching from CPU on my main system, one that also runs BOINC every now and then. I switched from an i5-2500K to an i5-3470 on the same motherboard, with the same Windows, with a whole lot of trouble (all neatly registered on the BOINC forums :)). 

So just prior to switching the CPU, I was at:
```
03-Apr-2018 21:57:29 [---] Host name: i5-2500K
03-Apr-2018 21:57:29 [---] Processor: 4 GenuineIntel  Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz [Family 6 Model 42 Stepping 7]
03-Apr-2018 21:57:29 [---] Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss htt tm pni ssse3 cx16 sse4_1 sse4_2 popcnt aes syscall lm avx vmx tm2 pbe
```
After switching the CPU, I was at:
```
07-Apr-2018 01:08:37 [---] Host name: i5-2500K
07-Apr-2018 01:08:37 [---] Processor: 4 GenuineIntel  Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz [Family 6 Model 58 Stepping 9]
07-Apr-2018 01:08:37 [---] Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss htt tm pni ssse3 cx16 sse4_1 sse4_2 popcnt aes f16c rdrandsyscall nx lm avx vmx smx tm2 pbe fsgsbase smep
```
You can see that the system name is still the same, I had not thought of changing it yet. 
However, I noticed this morning that BOINC had not done a new benchmark for the new CPU. We do new benchmarks when BOINC changes, so why don't we do them when the actual hardware it benchmarks changes?

**Comment by CharlieFenton** [comment]
That would be nice, but I think you would agree that having the processor change in the same computer is pretty rare. I would propose that anyone knowledgeable enough to change their motherboard is knowledgeable enough to select _Run CPU benchmarks_ from BOINC Manager's _Tools_ menu. ;=)

**Comment by Ageless93** [comment]
How about people who move their BOINC directory over from one system to the next? Then there's no automated benchmark either. The automated benchmark only happens on first install, or when BOINC itself changes.

**Comment by sirzooro** [comment]
This may also happen in cloud environment, when VM with BOINC will be moved between nodes.

**Comment by sunk818** [comment]
So the workaround is to rerun the benchmark.

VM moving between nodes wouldn't require a benchmark unless you're on a shared vps or given undedicated cores. In that case, I wouldn't run boinc on there anyway.

These are all rare edge situations where you can handle it manually. Dont you want programmers to fix bugs and make new features?

**Comment by TheAspens** [comment]
> How about people who move their BOINC directory over from one system to the next? Then there's no automated benchmark either. The automated benchmark only happens on first install, or when BOINC itself changes.

I would argue that this is unsupported.  Some research applications can generate bad results (or at least results that won't validate) if run on a different cpu half way through the computation (do to differences in floating point operations for example).

**Comment by TheAspens** [comment]
However, I would agree that this is something that could be changed and that you have correctly set its priority as "trivial" as it is much lower priority than other bugs out there.

**Comment by AenBleidd** [comment]
I don't believe CPU switch is smth that happens too often so I don't believe it worth time to fix this issue.
Closing it as 'wontfix' for now.
