### ISSUE TITLE
Contacting BOINC server will crash client in libeay32.dll

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2470]
Reported in two separate threads at the BOINC forums. 
In both cases the crash happens when using an Intel Pentium CPU N4200, on Windows 10, with BOINC 7.8.3, but also with earlier versions. 
Juha checked and thinks this may be a problem with this specific CPU and the version of OpenSSL we use in present BOINC and that it may need updating. 

Workaround is to set <no_info_fetch> in cc_config.xml, or use it as command line attribute, or to install the 32bit client. 

Error message:
>Faulting application name: boinc.exe, version: 7.8.3.0, time stamp: 0x59d3f202
>Faulting module name: LIBEAY32.dll, version: 1.0.2.7, time stamp: 0x56d5fc8e
>Exception code: 0xc0000005
>Fault offset: 0x00000000000e6543
>Faulting process id: 0x824
>Faulting application start time: 0x01d3d32c4b8e41e1
>Faulting application path: C:\Program Files\BOINC\boinc.exe
>Faulting module path: C:\Program Files\BOINC\LIBEAY32.dll
>Report Id: 00636b25-2b84-41af-9d92-9d0b0c5e47ed

[Thread 1](https://boinc.berkeley.edu/dev/forum_thread.php?id=12383)
[Thread 2](https://boinc.berkeley.edu/dev/forum_thread.php?id=11870)

**Comment by JuhaSointusalo** [comment]
> Is it time to consider updating our distro?

Yes. I am wary of updating it for 7.10 though. We know it doesn't work with
the most recent low-power CPUs from Intel but with the version being so old
who knows what could break if it's updated now.

**Comment by TheAspens** [comment]
7.10 should have been feature frozen for awhile now.  We are now at 7.10.2 which means it is a release candidate and unless there is a new (i.e. not present in 7.8.3) and serious (i.e causes serious negative user experience or prevents the system from working) bug, then we should ship 7.10 and start working on 7.12.

There will **always** be another bug that needs fixing.  If you stop and wait for them all, the release will never go out.  

We are much better off testing and releasing in a 2 -3 week cycle and getting a release out every 2-3 months then we are spending 4-5 months in a release cycle and only getting 1 or 2 releases out each year.

@RichardHaselgrove - Please draw a line in the sand, lets get 7.10 out and start working on 7.12.

**Comment by Ageless93** [comment]
We do probably best by adding a warning about this in the news report and Wiki pages of the recommended release client, that people who use a low powered Intel CPU either wait until 7.12 comes along, or that they temporarily switch to the 32bit client - which doesn't seem to have any problems.

**Comment by RichardHaselgrove** [comment]
I agree. I've called this a release candidate, and I think it should stay that way. But we shouldn't shy away from what appears to be a crashing bug on certain CPUs - we need to follow it up. IFF 1.0.2o turns out to be a drop-in replacement for 1.0.2g, we can do an interim re-release from the same branch later - but we'll need to recruit reliable testers with the right hardware first. But I suspect we'd need some code tweaks and a lot more testing as well.

**Comment by RichardHaselgrove** [comment]
Ah - I've found https://www.openssl.org/news/newslog.html

1.0.2g actually dates from 01-Mar-2016 - another vendor which doesn't update their copyright notices (which is where I got 2005 from).

I've had a cursory look through the security advisories linked from the newslog, and I can't see anything directly related to our problem - though a few crashing bugs are mentioned. Some bedtime reading there for when the dust has settled.

**Comment by RichardHaselgrove** [comment]
I've downloaded the sources for v1.0.2o, but they don't appear to supply any pre-built libraries.

The BOINC dependency package for VS2013 only contains an even older version - 1.0.2a from May 2015 - and pre-built copies of this are presented in the BOINC win_build release directory for builders to use.

Unless anybody beats me to it, I'll try to build 1.0.2o (of both libeay32.dll and ssleay32.dll - they seem to belong together) and see if they work. I may be some time...

If we do manage to resolve the crashing problem with a newer version, we should remember to update the dependency packages too.

**Comment by AenBleidd** [comment]
@RichardHaselgrove, please keep in memory that VS2013 prebuilt packages that contains on win_build directory will crash on WinXP

**Comment by moisesmcardona** [comment]
Just had this very same issue with an Intel Atom E3940.

My solution was to download this: https://indy.fulgan.com/SSL/openssl-1.0.2s-x64_86-win64.zip

Then I replaced the BOINC libeay32.dll with the one in the downloaded zip. It's working now.

**Comment by Ageless93** [comment]
Two more systems with this problem, with BOINC 7.14.2
https://boinc.berkeley.edu/forum_thread.php?id=13270 -> an Asus PN40 Mini PC with Intel Celeron N4000 CPU
https://setiathome.berkeley.edu/forum_thread.php?id=84923#2022742 -> Microsoft Surface laptop 3 with Intel Core i7-1065G7 CPU

**Comment by letswinnie** [comment]
Have the same issue with BOINC 7.14.2 and 7.16.3 on Celeron N3450 and Core i7-1065G7.
Solution provided by @moisespr123  works.

**Comment by davidpanderson** [comment]
I'll build the next Windows client with 1.0.2s.

**Comment by Ageless93** [comment]
Another host with a similar sort CPU with this problem:
https://setiathome.berkeley.edu/forum_thread.php?id=84998, Intel Core i5-1035G1

For quick help, is it possible someone builds a new libeay32.dll and ssleay32.dll and puts those in a zip file in https://boinc.berkeley.edu/dl/?C=M;O=D so I can at least help people with a 64bit Windows/64bit BOINC get back to work, without having to tell them to install a 32bit BOINC?

**Comment by RichardHaselgrove** [comment]
Just taken delivery of a new mini-PC with Celeron(R) CPU J3455 (Goldmont based "Apollo Lake" - very similar to Goldmont Plus based "Gemini Lake" N4000 range).

I can confirm all previous reports:
BOINC for x64 installs but crashes when fetching all_projects_list
BOINC for x86 installs and runs
BOINC for x86 displays warnings about needs 64-bit version to detect VBox (not installed anyway)
BOINC for x64 installs **and runs** with openssl 1.0.2s download suggested by @moisespr123 

Ready to test v7.16.4

**Comment by RichardHaselgrove** [comment]
Confirmed v7.16.4 x64 installs and runs correctly on the Celeron.

14 watts running 4x SSE cores, no iGPU (Einstein) - for the person who was asking yesterday.

**Comment by AenBleidd** [comment]
@RichardHaselgrove, do you still have that Celeron hardware? Are you able to reproduce this with the latest client built on 'master'?
https://github.com/BOINC/boinc/actions/workflows/windows.yml?query=branch%3Amaster+is%3Asuccess

**Comment by RichardHaselgrove** [comment]
Yes - I have it and you're looking at the screenshots from it for #4546.

It's running the build you linked 8 days ago. Since that test, I've built a complete suite from master for @hucker75 on it. So it can handle VS2019, but I don't really want to throw VBox at it as well.

But with recent builds distributed with openssl 1.0.2s, the 64-bit client runs without crashing. What else is there to test?

**Comment by hucker75** [comment]
I confirm 6 different computers are running that build here with no problems.  Let me know if you want me to try to caused a crash :-)

**Comment by AenBleidd** [comment]
Thank you both for the testing. No need to do any testing with VBox since it's not related to this particular issue with OpenSSL.
