### ISSUE TITLE
Error in db/schema.sql

### ISSUE THREAD

**Issue by MrLeau** [BOINC/boinc#2479]
The default value for the create_time column of the token table causes an error when creating a new project.
According to mysql (5.7) documentation you can't put functions for default value except for current_timestamp. Mysql 5.7 is most up to date version for Ubuntu 16.04.

See https://dev.mysql.com/doc/refman/5.7/en/data-type-defaults.html
https://github.com/BOINC/boinc/issues/new

create table token (
    token                   varchar(255)    not null,
    userid                  integer         not null,
    type                    char            not null,
    **create_time             integer         not null default unix_timestamp(),**
    expire_time             integer,
    primary key (token),
    index token_userid (userid)
) engine=InnoDB;

**Comment by AenBleidd** [comment]
Necessary fix is on the go in PR #2474
