### ISSUE TITLE
Copyright sign unreadable

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2493]
Just built BOINC 7.10.1 for Windows, and find that the copyright sign on the Details box of the properties of boinc.exe and boincmgr.exe is unreadable. This may have been going on for some time already, because I didn't copy the new boinctray.exe over to my BOINC Program directory --which held the officially installed BOINC 7.9.3 files-- and there it shows like that as well. 

![boincmgr_copyright](https://user-images.githubusercontent.com/10869587/39442737-8d4af86e-4cb2-11e8-8c79-2446bad6448a.png)
![copywhat_](https://user-images.githubusercontent.com/10869587/39442738-8d6a4818-4cb2-11e8-9281-76770c68b226.png)

This is on a Windows 7 SP1 x64 system (almost fully updated). I have an older 7.6.20 Manager where the copyright sign shows correctly:
![7 6 20-correct](https://user-images.githubusercontent.com/10869587/39442914-2449ce2a-4cb3-11e8-9ed6-0712e6b5be79.png)

The sign is Alt+0169 on Arial

**Comment by RichardHaselgrove** [comment]
BOINC v7.8.3 shows it correctly, too.

![boinc copyright dteails 7-8-3](https://user-images.githubusercontent.com/14886436/39443502-bb0bad58-4cac-11e8-8369-e131b3b20436.png)

**Comment by AenBleidd** [comment]
This was broken with my commit. I'll fix it in an hour

Best regards,
Vitalii Koshura

2018-04-30 21:29 GMT+03:00 RichardHaselgrove <notifications@github.com>:

**Comment by AenBleidd** [comment]
Fix provided, Sorry for this

**Comment by Ageless93** [comment]
The only thing I see in all these is that we go from "� 2003-2018 University of California" to "� 2003-2018 University of California", which as far as it looks to me are the same. But perhaps that's my local font.

**Comment by RichardHaselgrove** [comment]
I think that's (very bad) font/non-ascii handling by github. I had to resort to a hex editor to see what was really going on inside the files.
