### ISSUE TITLE
Recent merges have broken master - and could have been prevented

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2499]
Two recent pull requests #2445 and #2453  have broken master.

These could have prevented if the testing automation from https://github.com/TheAspens/boinc-server-test had been run against the pull requests prior to merging.

Is someone able to set things up so that runs as part of the automated testing when pull requests are opened and updated?

(note - I'm willing to move that over to the BOINC organization if we think that is appropriate)

**Comment by AenBleidd** [comment]
Hello @TheAspens,
I think it's possible. If it's not an urgent question I can take a look at it later this month

**Comment by ChristianBeer** [comment]
We can setup a new travis job on linux that is docker enabled (https://docs.travis-ci.com/user/docker/) and run tests there. We already have `gradle` installed in the Trusty CI environment. There is no ansible that I can see but it should be available to install.

So here is what I would propose:
- Add a new `BOINC_TYPE=test` to our build matrix (Note this is the same name as in #2457 on purpose)
- Add `ansible` to the `before_install` `apt-get install` command (I don't think it matters that the other types don't need it)
- figure out a way for the docker container to use the code being under test right now (already cloned in the VM) and not the master branch as is stated on the Readme

The last thing has several parts. One is to copy the ansible playbooks from Kevins repository to BOINC/boinc and adapt them to work with the current working directory. The other part is to make changes to https://github.com/marius311/boinc-server-docker for it to not clone the code again but somehow use the existing working directory.

**Comment by TheAspens** [comment]
@marius311 - do you have any thoughts about how I could pass into your code a directory to use for the boinc source as an option rather than using the source the way you do now?

**Comment by marius311** [comment]
The Dockerfile currently builds whatever it finds in the boinc directory (https://github.com/marius311/boinc-server-docker/blob/16c8b3ee62e2c58b09130658ffa665989d88cf62/images/makeproject/Dockerfile#L28-L29) This is by default the boinc submodule that comes with the repo, but you could always checkout the repo without that submodule, then put/link whatever folder you link there?

**Comment by TheAspens** [comment]
Ok - I'll see if I can do that.  I'll let you know what I find.

**Comment by AenBleidd** [comment]
Wasn't this fixed by #2667 ?

**Comment by TheAspens** [comment]
Yup.  Hooray!
