### ISSUE TITLE
Migrate commit email service to webhook

### ISSUE THREAD

**Issue by ChristianBeer** [BOINC/boinc#2502]
Github is deprecating the service that sends an email every time a push happens on a repository. See: https://developer.github.com/changes/2018-04-25-github-services-deprecation/

Currently this is used for BOINC/boinc to send an email to the `boinc_cvs@ssl.berkeley.edu` email list.

As of now there is no alternative service available that we can switch to. We have to implement our own webhook receiver and send the email ourselves. I briefly looked into existing implementations and the most promising seem to be: https://gist.github.com/gka/4627519 and https://github.com/jbelien/php-github-webhook (which is a more refined version of the first).

The general idea about this is to provide a new repository (e.g. BOINC/boinc-webhooks) that has everything setup correctly and can be easily deployed on a machine that is already accessible via a URL. The URL itself (and a shared secret) must not be made public but needs to be configured in the BOINC/boinc repository by someone with admin permissions (Committers don't have those!). This server must be able to send one email per push (json payload to the URL specified, see: https://developer.github.com/v3/activity/events/types/#pushevent) to the mailing list above so the traffic for the server is minimal and distribution is handled by the google group. This way it is relatively easy to switch the webhook receiver from one server to another.

The deprecation happens in late 2018 and perhaps until then a better solution pops up.

**Comment by TheAspens** [comment]
@ChristianBeer - what are common uses of the emails sent to boinc_cvs?  I've known the email list exists and at one point I subscribed, but it generated so much noise, I unsubscribed.

**Comment by CharlieFenton** [comment]
I feel the same as @TheAspens and unsubscribed from that list when I inadvertently was resubscribed by the shift to Google Groups. 

@ChristianBeer Before going through the effort, I suggest sending email to that list to see if anyone feels it is worth keeping.

**Comment by ChristianBeer** [comment]
I already send an email. So far two people responded and one wants to keep the service. I'm going to wait two more weeks so everybody subscribed to the list had a chance to read it. I don't have access to the subscription list so I don't know how many people are still subscribed.

**Comment by ChristianBeer** [comment]
I didn't hear back from others. I'm not going to implement the webhook because of that (sorry @brevilo). If one wants to get the mails and sets up his/her private webhook receiver I can add the URL and token to the configuration.

**Comment by brevilo** [comment]
Oh well, ignorance is bliss 😏

**Comment by ChristianBeer** [comment]
Quick note about this issue: github has implemented a new way to send those commit emails as part of repository level notifcations. This was automatically migrated on Feb 1 and is working.
