### ISSUE TITLE
EU-GDPR - Right to Erasure - Account Managers

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2507]
In issue #2447 there is a discussion about the interaction between account managers and projects with regards to the right to erasure.  The discussion starts here:  https://github.com/BOINC/boinc/issues/2447#issuecomment-383603716

I am creating this ticket to seperate the discussion and planning for this part of the issue sperate from the rest of the implementation.

There are two proposals provide in the discussion (with comments on both so please review the other ticket before before commenting here).

From Kevin Reed:

> 
> - Account managers should monitor the new user_deleted.xml that will be exported in the stats - this will list users deleted on a project in the past 60 days. See https://boinc.berkeley.edu/trac/wiki/RightToErasure#DataExports and https://boinc.berkeley.edu/trac/wiki/RightToErasure#FinalRemoval
> - Account managers need to be able to invoke the delete operation on a project. A new am_delete_account RPC is needed that would align with the other RPC's defined here: https://boinc.berkeley.edu/trac/wiki/WebRpc
> - In order to secure the delete web rpc, projects will have a list of trusted Web RPC users (i.e. https://boincstats.com/, https://scienceunited.org/, https://www.gridrepublic.org/)
> - TheWeb RPC's (need to decide which) will be updated to include a section that contains:
> ```
> <signature>
>        <signer>https://boincstats.com/</signer>
>        <hash>1234afd123asdf1234asdf134asdf.....</hash>
> </signature>
> 
> ```
> 
> - The Web RPC users will provide a public key at a standard location like /public.key (i.e https://boincstats.com/public.key
> - The Web RPC user will use their private key to sign the message and send the signature with the request
> - The RPC will verify that the signer is a trusted signer and will then obtain the public key (either from local cache or from the remote server - but if the signature fails, it needs to refetch the public key to allow the signer to update their key) and then verify that the signature matches the content.
> - Only after that processing is complete and successful will it perform the actions of the RPC.

From Eric Korpela:

> I don't think that the account manager needs to be able to run the project
> delete without intervention.  The account manager should redirect the user
> to the project delete function.  Then the delete would propagate back to
> the project manager in the next stats export.

In addition to resolving the design and approach, someone needs to take on the implementation.

**Comment by brevilo** [comment]
I'm trying to determine the state of GDPR in BOINC: how about this issue? #2447 got merged so, technically it should be resolved. What's keeping us from closing the issue itself? The inclusion in the server release 1.0?

Thanks

**Comment by darkdragon-001** [comment]
Any news?

**Comment by darkdragon-001** [comment]
> If the user would like to remove their data, they need to go directly to every project and every Account Manager they use and ask to be removed. I strongly object something need to be done automatically here.

Would be great if this askin gprocess would be more formalized - both for users as well as account managers. If there was a button for the user to request deletion, this should trigger a deletion request for the account manager, who then has a delete button to process the deletion. Currently, the account manager needs to perform a bunch of manual actions.
