### ISSUE TITLE
limit web RPCs to specific sources

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2526]
AM -> project RPCs like create_account can be abused by spammers who,
for whatever reason, create millions of bogus accounts.

I propose that projects be able to have a list of acceptable sources of these RPCs
(e.g. a list of vetted AMs).
Each AM would have a PKE key pair.
RPC requests would include something encrypted with the private key.
Simplest thing would be to include the Unix time, both clear and encrypted.

**Comment by JuhaSointusalo** [comment]
Duplicate of #2308
