### ISSUE TITLE
Naming Client/Web inconsistent, example "Work done"/"Credit".

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#253]
**Reported by Rattledagger on 24 Sep 37444263 14:13 UTC**
In January 2006, after BBC/CPDN did some usability test, it was decided to change the names on Result, Credit and so on. While the Client/Manager-part was changed to use the new names, the Web-part is still lagging-behind using the outdated names.

See "terminology change", boinc_dev, 18.01.2006.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/260

**Comment by ChristianBeer** [comment]
I think this is now done. If there are some user visible instances of "Result" and "Workunit" left please open an issue or a pull request.
