### ISSUE TITLE
Microsoft buying Github

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2548]
As per [A bright future for GitHub](https://blog.github.com/2018-06-04-github-microsoft/)

> 
"I am very excited to announce that Microsoft is acquiring GitHub and expect the agreement to close by the end of the year. While it will still take a few months to finalize, we wanted to share the news as soon as we were able."

**Comment by AenBleidd** [comment]
So what? As I understand this doesn't mean that all code on github now is licenced to Microsoft

**Comment by Ageless93** [comment]
I posted it as news so everyone could reach their own conclusions, and decide if they want to stay under the umbrella or not. 
As for your comment, perhaps not now, but maybe in  a future. You never know. [Keep an eye on your EULA/CoC](https://www.theregister.co.uk/2018/03/28/microsoft_services_agreement_bars_offensive_language/).

**Comment by AenBleidd** [comment]
This could happen anyday even without acquiring. In any case, let's watch
the situation. Linux cire mirror still in github ;)

Best regards,
Vitalii

Sent via Android

ср, 6 июня 2018, 10:55 Jord van der Elst <notifications@github.com>:

**Comment by JuhaSointusalo** [comment]
Nobody in the BOINC community has demanded that we leave GitHub, there has not been any interest in discussing the matter or anything else really. I think this ticket has served it's purpose, whatever it is, and I'm closing it.
