### ISSUE TITLE
Boinc 7.4.53 stops auto-updating new tasks on Android 7.1.2

### ISSUE THREAD

**Issue by zthomasz** [BOINC/boinc#2562]
I'm running BOINC 7.4.53 on an Odroid XU4 with Android 7.1.2. The only project is Rosetta@Home. It performs well for a while, but after a few hours BOINC gives error messages about Computation Errors and Waiting for tasks. 

When I go to Preferences, select Projects, then Rosetta, and click on "Update" it will download new Tasks and begin crunching them.  It performs well for a few hours, but then stops again so I have to repeat the Update procedure.

Thanks!

**Comment by adamradocz** [comment]
I had similat but not exactly the same problems with v7.4.53.
Since v7.14.1 everything is fine. Can we close this issue?
