### ISSUE TITLE
[Bug] New project can't be added if the login failed.

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2563]
If I mistype a password while I'm trying to add a new project, I can't add it anymore, because the "Next" button is disabled, when I go back and try to correct it. The only solution is to close the window and start  the process again.

<img width="444" alt="login failed 1" src="https://user-images.githubusercontent.com/16503773/41506195-952fcfc8-7219-11e8-9ed6-0f6f0da7d41f.PNG">

<img width="444" alt="login failed 2" src="https://user-images.githubusercontent.com/16503773/41506197-979749ee-7219-11e8-9529-39d404802b53.PNG">

**Comment by AenBleidd** [comment]
I think this was fixed in #2537

**Comment by adamradocz** [comment]
Sorry.

**Comment by AenBleidd** [comment]
@adamradocz, it's ok. Actually, this was never documented as an issue and was fixed after the 7.10.2 release so this fix was not really visible.
