### ISSUE TITLE
text not translatable because wrong format

### ISSUE THREAD

**Issue by ChristianBeer** [BOINC/boinc#2573]
https://github.com/BOINC/boinc/blob/96ec30db31a50ba9bc623a2fdb10f42d97f62fa0/html/user/delete_account_confirm.php#L85

@TheAspens You can't use concatenation with global variables inside the `tra()` function. You need to specify the variable as an argument and insert a placeholder `%1`.

**Comment by TheAspens** [comment]
My apologies - I'll get to this in the next 2-3 days.
