### ISSUE TITLE
update GeoIP files

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2574]
https://dev.maxmind.com/geoip/geoip2/geolite2/

The files in BOINC show Serbia and Montenegro as 1 country; no longer the case.

**Comment by Ageless93** [comment]
Same region, "Republic of Macedonia" renamed itself to "Republic of North Macedonia". See https://en.wikipedia.org/wiki/Macedonia_naming_dispute for more on that.

**Comment by Rytiss** [comment]
Maxmind has deprecated GeoIP Legacy. The code is [still available](https://github.com/maxmind/geoip-api-php/blob/master/src/geoip.inc), but the databases [are not](https://support.maxmind.com/geolite-legacy-discontinuation-notice/), so we should upgrade to [GeoLite2](https://dev.maxmind.com/geoip/geoip2/geolite2/).

**Comment by davidpanderson** [comment]
GeoLite2 requires PHP 8.1, which many projects don't have.
I don't think this is worth worrying about.
