### ISSUE TITLE
[GUI] 'Add project' wizard: distinguish 'web' and 'attach' urls

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#2579]
The latest online update to all_projects_list.xml contains distinct urls:
```
        <url>http://www.cpdn.org/cpdnboinc/</url>
        <web_url>http://climateprediction.net/</web_url>
```
(and likewise for Einstein@Home). This is a good move - it resolves problems I encountered with 7.10 - but it needs placing in the repository for @CharlieFenton and others to use. And the attach wizard needs updating to display it: this is from a fresh checkout/build from master today, with the new file in place.

![attach-wizard](https://user-images.githubusercontent.com/14886436/41988145-25138492-7a33-11e8-99d6-cfe09e60691e.png)

Attaching a reconciliation of the various versions of all_projects_list as at 27 June 2018 (Excel speadsheet)

[Comparison of All_Projects_List versions.zip](https://github.com/BOINC/boinc/files/2142201/Comparison.of.All_Projects_List.versions.zip)

**Comment by drshawnkwang** [comment]
Just my unenlightened opinion: I don't think #2580 is related, but I could be wrong.

**Comment by davidpanderson** [comment]
CPDN's PHP site could redirect to the Wordpress site for non-BOINC user
agents.
Then they'd just need one URL

**Comment by RichardHaselgrove** [comment]
But the non-attach BOINC functions (stats, help desk) still need to be on the designated BOINC server.

**Comment by RichardHaselgrove** [comment]
PIcking up a comment from #2438, and extending the (overdue?) review of the 'Attach project' wizard.

1) intel_gpu not tested for
2) other GPU tests search for "[cuda", "[ati" (i.e. keyword at start of plan class string). SETI is not detected as ATI/AMD capable, because its plan classes start "[opencl". Test needs generalising.
3) it would be user-friendly to add tooltips to the icons: it requires one line of code per icon, such as

`m_pProjectDetailsSupportedPlatformWindowsCtrl->SetToolTip(_("Windows"));`

**Comment by adamradocz** [comment]
@RichardHaselgrove I'd suggest to increase the icons size at least to 36 or 48 pixel wide. Is it possible. Currently this size is barely see-able and not so informative.

**Comment by RichardHaselgrove** [comment]
We have another conference call tomorrow: perhaps we can ask again for some documentation. A search for "web_url" in this repository finds only my opening remark for this issue, so the current all_projects_list hasn't yet been committed.

Attaching an xsd schema (renamed as txt to allow uploading), generated from the live file as a basis for documentation.
[all_projects_list.txt](https://github.com/BOINC/boinc/files/2270064/all_projects_list.txt)

**Comment by RichardHaselgrove** [comment]
I think I'm getting there...

![new attach icons](https://user-images.githubusercontent.com/14886436/43912771-2033945a-9bfb-11e8-9f87-c24f1db0ce23.png)

**Comment by RichardHaselgrove** [comment]
Implementation completed in #2643. Closing.
