### ISSUE TITLE
Ctrl-Tab to switch between views

### ISSUE THREAD

**Issue by jeffythedragonslayer** [BOINC/boinc#2584]
It would be nice if the Ctrl-Tab shortcut could be used to quickly switch between different views (Notices, Projects, Tasks, etc.) like switching between tabs in Firefox or Chrome.  (And Ctrl-Shift-Tab to cycle through them backwards.)  This shortcut doesn't appear to do anything in Boinc Manager at the moment.

**Comment by CharlieFenton** [comment]
Which operating system are you using? It already does this on MS Windows. On all platforms, you should be able to use the keyboard shortcuts in BOINC Manager's _View_ menu.

**Comment by jeffythedragonslayer** [comment]
This is Fedora 28

**Comment by chrstphrchvz** [comment]
This issue also applies to macOS, and there is already a [wxWidgets bug](https://trac.wxwidgets.org/ticket/17064) for why it doesn't work on macOS. I have not found a similar wxWidgets bug for why it doesn't work on Linux, though.

**Comment by AenBleidd** [comment]
Closing in favor of more detailed #3359
