### ISSUE TITLE
curl/curl.h

### ISSUE THREAD

**Issue by ritua2** [BOINC/boinc#2600]
The "curl.h" file is being included in lib/remote_submit.cpp. However, we do not see this file in the "curl" directory. Is this file not required anymore?

Thanks,
Ritu

**Comment by JuhaSointusalo** [comment]
`curl.h` comes from libcurl development files. On debians the package you want is `libcurl4-openssl-dev` and on redhats `curl-devel`.

**Comment by JuhaSointusalo** [comment]
To avoid any potential misunderstandings. You don't need to copy `curl.h` to BOINC source tree. `configure` should find it after you have installed the development package (which means you need to re-run `configure` after installing the package).

`curl` directory's purpose is to hold the certificate bundle that's used in Windows and Mac clients.

**Comment by ritua2** [comment]
Thanks a lot Juha! That is very helpful!


Best Regards,

Ritu


________________________________

**Comment by Uplinger** [comment]
This issue appears to be closed, why is it still open?

Thanks,
-Keith
