### ISSUE TITLE
[Docker] Tester wanted with AMD GPU

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2617]
Hi,

Unfortunately I don't have AMD GPU, so I can't test the AMD specific Dockerized version of Boinc.

 It would be a huge help, if anyone could help with the testing.

Here are the instructions: https://github.com/BOINC/boinc-client-docker

**Comment by ab1vl** [comment]
Adam,

I have an AMD Athlon 64/x2 5600+ with GeForce GT-220 PCIe.  It's running BOINC 7.12.1 on win7/64 and the GPU is showing up in the Event Log as running WUs, tho only rated at 1.2. 

RSVP if interested and I will install Lubuntu 18.04 and try your package.

chuck

**Comment by adamradocz** [comment]
I need someone with AMD GPU, not CPU. But thanks anyway.

**Comment by gridranger** [comment]
Hi!

Maybe I could help. I have a Radeon x9 270 OC with 2GB RAM.
I have installed a Ubuntu 18.04 LTS on my PC next to my Win 10. Docker has been installed, BOINC client image has been built, and I could connect to it from the manager.

I am ready for the user stories to try :)

**Comment by gridranger** [comment]
What happened:

* I realized that I build client instead of client:amd so I built client:amd
* ROCm was installed (side note: BOINC Manager GUI broke somehow during this step, but it still could be run as root; running it as myself results a GTK error in the log: `(boincmgr:7281): Gtk-CRITICAL **: 13:57:29.932: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar`
* Boinc Manager was attached to the new client
* log says: "No usable GPUs found"
* googled found and run: "sudo apt install mesa-opencl-icd" (it was for 16.04 originally)
* container stopped, removed, a new one started
* Boinc Manager was restarted, reattached
* log says: "No usable GPUs found"

**Comment by gridranger** [comment]
Still alive and trying to get results, but unfortunately with Ubuntu 16.04 I stuck in a login screen loop after installing the AMD drivers. I will report back later.

**Comment by davclark** [comment]
While I am not currently involved with the BOINC project, I'm interested in support of AMD GPUs. I have a working install of ROCm on Ubuntu 16.04 with an 8GB RX 580. @gridranger I recall getting a login loop by following some instructions from some crypto-mining software (I figured they'd have good instructions on getting good performance for GPU compute). You might try editing your GRUB kernel parameters and see if you can flip anything there... I forget what the specific parameter was, though.

I actually have the card listed for sale right now... but if the ecosystem turns the corner maybe I'll hang onto it :)

Relatedly, I built a couple of GPU machines for the [D-Lab](https://dlab.berkeley.edu) while I was there, the larger of which is somewhat collaboratively managed between BIDS, D-Lab and Research Computing. That might be a nice community to work with on testing this system and driving usage outside of the typical / traditional players.

It's too early for us yet, but I could also see putting something together in my current employer's platform ([Gigantum](https://gigantum.com)) that would make use of BOINC. It's a neat project - glad I stumbled onto it!

Anyway, I'll try to monitor here if you'd like me to run something on my personal RX 580 machine, but if you want more responsiveness, I'm also davclark on twitter.

**Comment by davidpanderson** [comment]
It would be great if BIDS and/or Research Computing learned about or used BOINC.  I'd be happy to meet with them to discuss this.

**Comment by gridranger** [comment]
In the past week I tried to make ROCm work with a wide range of Ubuntu releases with different kernel versions and different amd driver versions. Also tinkered around with Grub settings. rocminfo just gives the same idiot error message (hsa api call failure at line 900...).
My best guess is that my card is unsupported. It was stated nowhere but if amdgpu-pro is required for ROCm to function properly, than my card is useless due lack of support.

**Comment by adamradocz** [comment]
I think the amdgpu-pro and ROCm have a lots of commonality.

**Comment by gridranger** [comment]
I found official explanation why did I experience the issue:
https://github.com/RadeonOpenCompute/ROCm/issues/519#issuecomment-418469084
Southern Islands GPUs like mine (R9 270) are unsupported by ROCm.

Is there a possible way to get the desired test result without ROCm?
