### ISSUE TITLE
[AppVeyor]: Fix config to run more CIs

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#2620]
Next configuration should run on AppVeyor CI:
- Debug x64 (already exist)
- Debug Win32
- Release x64
- Relese Win32

This is necessary to avoid such issues as #2619 

To add these configurations I plan to switch from using existing git repository with prebuilt binaries for VS2013 and switch to using storage proposed by @TheAspens.
So at first I plan to collect zip archives with prebuild binaries from git repository to new location and then start working on this ticket

**Comment by ChristianBeer** [comment]
We should also tell AppVeyor about our build artifacts. Mainly `boinc.exe`, `boinccmd.exe` and `boincmgr.exe`. This will make them available for testers shortly after the pull request was made.

**Comment by RichardHaselgrove** [comment]
Yes please. We're wasting valuable pre-package testing time this way, resulting in the visible WSL config error in v7.12.1

**Comment by AenBleidd** [comment]
@TheAspens, all I need is time. Unfortunately, I'm overloaded on my work now. Hopefully, I'll have more time starting from Autumn

**Comment by TheAspens** [comment]
No worries - thanks for all that you contribute!
