### ISSUE TITLE
Multi GPUs treated as one.

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2633]
My laptop has an Intel and an NVIDIA GPU. If a project supports both of them, like Einstein@home of SETI@home, I get WUs for both of them. Until this point everything works correctly.
But, if I suspend one of the platforms WU manually, the other platform won't get new WUs, even when the current WU is done. The correct workflow should be, that the another platform gets new WUs continuously even-tho.

If I resume the suspended WU, then all the platforms get new WUs again.

**Comment by davidpanderson** [comment]
This isn't related to GPUs.  The client's current work fetch policy is to not fetch work from a project if any of its WUs are suspended.

**Comment by adamradocz** [comment]
I'd assume not to download any WU if I use the "No new tasks" button on the Projects tab. IMO the current behavior is a little bit confusing.

**Comment by AenBleidd** [comment]
I think current behavior is obvious and pretty clear. I suggest to close this as "Not an issue".
