### ISSUE TITLE
VBoxWrapper performance is worse - Poll function in PR 1946, likely

### ISSUE THREAD

**Issue by JacobWKlein** [BOINC/boinc#2636]
Here is a screenshot of the negative performance impact I noticed, comparing 26200 vs 26197. It might be attributed to the poll function changes in PR 1946. Not sure, but I assume it is, based on timing.
[https://github.com/BOINC/boinc/pull/1946](https://github.com/BOINC/boinc/pull/1946)

To summarize the screenshot:
- BOINC was crunching 4 RNA Tasks for 5450 minutes CPU Time. All using COM, based on Logs. Using VirtualBox v5.1.38.
- vboxwrapper 26200 used 40.2 additional minutes CPU Time, for a running task, during that time.
- vboxwrapper 26197 used 1.2 additional minutes CPU Time, for a running task, during that time.
- So, performance of 26200 is 33 times worse.

Could we investigate if this can be improved or reverted?
Thanks,
Jacob Klein

![boinc vboxwrapper 26200 vs 26197](https://user-images.githubusercontent.com/13267799/43719339-6f29d210-995b-11e8-998d-719c45fb7551.png)

**Comment by JacobWKlein** [comment]
Originally noted here:
[https://github.com/BOINC/boinc/pull/1946#issuecomment-409065809](https://github.com/BOINC/boinc/pull/1946#issuecomment-409065809)

**Comment by JacobWKlein** [comment]
nikolasgianna said:

Since the COM interface is being used and the only change is the poll function, a simple test would be to build the vboxwrapper using the original poll function instead of the one which reads virtualbox's logs. That way, all other things equal, the poll function would definitely be at fault of using too much CPU time.

**Comment by Germano0** [comment]
@JacobWKlein does this happen even with lastest updates?

**Comment by JacobWKlein** [comment]
It is highly likely that it does. However, my RNA World project is no-longer using 26197 for tasks, and I no-longer have any more 26197 long-runners in progress.

I specifically reported the issue, at the time I saw it, because I knew it would be hard to test.

The issue likely still exists. Do you have steps to easily re-test it?

**Comment by Germano0** [comment]
> Do you have steps for an end user to easily re-test it?

No, I asked you because I still have to start studying the situation from the scratch
