### ISSUE TITLE
(Windows) GPU detection fails when started from command line (take 2)

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#2657]
Previous references: issue #2029 , PR #2036.

A year ago we tackled an issue where GPU detection failed if the client was started from the command line with "boinc", rather than "boinc.exe"

The problem has been re-reported for BOINC v7.10.2 and v7.12.1, but this time when the invocation is from a batch file or from BoincTasks, if the correct working directory is not used. Compare these screenshots (from Process Explorer)

![boinc client 2 - v7 8 3](https://user-images.githubusercontent.com/14886436/44597799-c4b08280-a7c8-11e8-8060-1a99776fca5b.png)
![boinc client 2 - v7 12 1](https://user-images.githubusercontent.com/14886436/44597800-c4b08280-a7c8-11e8-88bb-60807162e7bf.png)

After all the multiple restarts to detach from the command window and do the GPU detection, the final running client instance was still started with the full path on the command line (D:\BOINC\... on my machine). By contrast, v7.12.1 starts with the now hard-wired "boinc.exe", but no path.

I think commit 7930686128709433b29741a034dd890c27a616f1 just moved the problem around a bit, without fully fixing it. We need both the path and the .exe

**Comment by JuhaSointusalo** [comment]
Closing. The issue was fixed in #2713 and the problems in that PR were fixed in #2748.
