### ISSUE TITLE
Mac screensaver app can not be built on Travis CI

### ISSUE THREAD

**Issue by ChristianBeer** [BOINC/boinc#2662]
The Xcode ss_app target can not be built on Travis CI because of missing symbols. The error message seems to point to freetype or FTGL or some other missing static library. Since this is not release critical (it only happens on the Travis OSX VM) I just disabled the target but it would be nice if someone can investigate and fix it.

```
Undefined symbols for architecture x86_64:
  "_png_error", referenced from:
      _read_data_from_FT_Stream in libfreetype.a(sfnt.o)
  "_png_create_info_struct", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_set_read_fn", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_read_info", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_set_palette_to_rgb", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_get_error_ptr", referenced from:
      _error_callback in libfreetype.a(sfnt.o)
      _read_data_from_FT_Stream in libfreetype.a(sfnt.o)
  "_png_create_read_struct", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_set_longjmp_fn", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
      _error_callback in libfreetype.a(sfnt.o)
  "_png_set_tRNS_to_alpha", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_set_expand_gray_1_2_4_to_8", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_set_strip_16", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_read_image", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_set_packing", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_set_gray_to_rgb", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_set_interlace_handling", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_read_update_info", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_read_end", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_get_io_ptr", referenced from:
      _read_data_from_FT_Stream in libfreetype.a(sfnt.o)
  "_png_get_valid", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_get_IHDR", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_set_read_user_transform_fn", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_set_filler", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
  "_png_destroy_read_struct", referenced from:
      _Load_SBit_Png in libfreetype.a(sfnt.o)
```

**Comment by JuhaSointusalo** [comment]
Isn't this the same issue as with libidn? Freetype configure finds libpng from the VM but it's not a static one. Try adding `--without-png`.

**Comment by ChristianBeer** [comment]
I don't remember but I think I tried that when we first encountered the problem some time ago. But I didn't have the detailed log output then. It looks like this could work. I'm not sure if I should piggy-back this on #2659 too. I'll test this together with some other changes I have in mind for optimizing the buildcache on Travis.

**Comment by brevilo** [comment]
I just came across this one myself after upgrading freetype > 2.3.5. I can confirm that adding `--without-png` to freetype's `configure` statement fixes the issue.

**Comment by AenBleidd** [comment]
@brevilo, could you please provide a pr for this?

**Comment by brevilo** [comment]
Nope, this about Travis and I don't know what files are involved.

**Comment by AenBleidd** [comment]
All Travis related scripts are (or mentioned) here: https://github.com/BOINC/boinc/blob/master/.travis.yml

**Comment by brevilo** [comment]
Following those references I ended up [here](https://github.com/BOINC/boinc/blob/master/mac_build/buildfreetype.sh#L143) and `--without-png` is already included there. As Christian [said](https://github.com/BOINC/boinc/issues/2662#issuecomment-416055772), he already tried.
