### ISSUE TITLE
Server Version

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#2688]
A mechanism is required to publish the server version.

**Comment by lfield** [comment]
Are there any suggestions on how to do this?

**Comment by marius311** [comment]
If I remember right, at the workshop it was suggested to put it in the get_project_config.xml ? I'm in favor of that idea. 

One thing I'd request is that it be easy for boinc-server-docker to append something to the published version to include that the server is running in boinc-server-docker, in a way that the admin doesn't have to do anything.

**Comment by lfield** [comment]
This is fine. We can also show it in the footer. The question is what is the source for this information? Where does the php pick it up from and how does it get there. Also does the drupal also need updating?

**Comment by lfield** [comment]
Does this work with the zip download?

**Comment by brevilo** [comment]
Erm, nope, but that should be discouraged anyway, right? I mean how are admins supposed to run controlled updates of such instances?

**Comment by brevilo** [comment]
Also, may I ask why publishing the server version is wanted in the first place? Projects might not want to do that due to security (by obscurity) concerns.

**Comment by lfield** [comment]
At least the Fedora build uses the zip file. Publishing the server version is useful. The security risks are limited. Most security is provided by the OS, the details of which are not published.

**Comment by brevilo** [comment]
Not sure I can agree to that. Compromised BOINC server components (by their nature) endanger the sensitive BOINC database content, and that's way easier if you know what server version you are about to attack. You might even go as far as arguing that this in violation of Art. 32 GDPR. This is of course debatable, but I think we should therefore at least have that discussion. One way or another, this feature must be made optional (via **opt-in**) and thus nothing must ever depend on the version being available.

**Comment by ChristianBeer** [comment]
With SVN the revision was put into a file at checkout which was accessible to apache and shown on the server status page. Something like this can be done with the server version (not the git sha1) and it is up to the project to enable this or not. This file could be part of the zip archive. For projects that use a local fork of the BOINC repo the SHA1 hash is more meaningful though. They could publish this SHA1 but since the local fork is private nobody but the project admins know what version is really running (assuming they put their local changes in the same repo).

Publicly showing the exact SHA1 that is running is not advisable as that makes it easy for attackers to see if this specific version has a vulnerability without interacting with the project.

I also want to stress that no other tool should rely on this version number and expect certain features or behaviors. There are better ways for service discovery these days.

**Comment by lfield** [comment]
I understand the principle but in practice there is a limited number of large projects, so it wouldn't take long for an attacker to try them all. Also new versions come with new features so by mapping features to a releases makes it easy to deduce the version. For a serious vulnerability a quick workaround would be implemented as we could not afford to wait for a release and this would not change the version.

**Comment by lfield** [comment]
An item to discuss at the next phone call?

**Comment by RichardHaselgrove** [comment]
From the message board / help desk point of view, it's extremely helpful to be able to view the current state of a server's code, and tailor advice / bug reports accordingly. In SVN days, the revision number even of php include files could be seen in the source code of each web page (the bare tags are still there, but unpopulated with revision data). There were occasions when a project updated server components, but failed to update their web pages to reflect, for example, updated task status reports. We could diagnose that remotely.

**Comment by brevilo** [comment]
> Publicly showing the exact SHA1 that is running is not advisable as that makes it easy for attackers to see if this specific version has a vulnerability without interacting with the project.

That's the same for an arbitrary version number as long you intend to use meaningful version numbers which have to be mapped to git tags 😉

**Comment by drshawnkwang** [comment]
Apache [hides the version number with a configuration option](https://www.tecmint.com/hide-apache-web-server-version-information/). A similar option could be added to `config.xml` to publish/unpublish whatever version of BOINC server a project is running.

**Comment by tristanolive** [comment]
There are also some similar concepts in project.inc, e.g. define("RPC_DEBUG", false); That could be a place to define SERVER_SIGNATURE, and then use "if" or "if (defined(...))" to show the signature, if the project opts in.

**Comment by tristanolive** [comment]
Also, how about the server_status page as a home for this string? That would keep Drupal out of it. :)
