### ISSUE TITLE
power detection not working on Android 8?

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2692]
(user email):

I really like your BOINC app.
But, since I updated my Moto Z to Android Oreo (8.0.0) the computation stopped and the app displays a message requesting to connect the power outlet, even when it's already connected (phone 100% recharged).
Should I reinstall it, or clean cached and storage data?

**Comment by Ageless93** [comment]
See the comment done by @brevilo in #2467

**Comment by brevilo** [comment]
Keep in mind that current bug reports are usually based on the play store version of our app. That one's severely outdated and potentially buggy. I for one can't reproduce that problem on Android 8.0.0 and BOINC acts as expected: stops computing when unplugged and restarts when plugged in again.

That said, the focus needs to be on getting the BOINC 7.14 released and build/release a new play store version based on that. At that point **all** existing Android bug reports need to be revisted and I hope we can immediately close tons of them.

**Comment by AenBleidd** [comment]
> At that point all existing Android bug reports need to be revisted and I hope we can immediately close tons of them.

I'm afraid, this will not happen because we still have the same codebase. Just upgrade minimum and/or recommended Android API version will not solve this.
But who knows....

**Comment by brevilo** [comment]
Let's wait and see. I'm rather confident because I can't reproduce most bug reports we received but maybe it's just because I use an Android flavor that relatively close to AOSP.

**Comment by AenBleidd** [comment]
Closing as a duplicate of #2467
