### ISSUE TITLE
boinccas.dll needs to be rebuilt for auto-attach to work

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2711]
The version of boinccas.dll in git is out of date and will create the auto_attach as installer_filename.txt instead of as login_token.txt. 

The core client looks for login_token.txt so if the current version of boinccas.dll that is in git is used, auto attach will not work on windows.

**Comment by davidpanderson** [comment]
Done, but these binary files don't really belong in the repo.
They're built by the VS solution, and should be automatically placed in the
installerv2/redist/x directory
