### ISSUE TITLE
Custom host name setting for android devices

### ISSUE THREAD

**Issue by gridranger** [BOINC/boinc#2721]
It would be great if there was a setting in the android client to set the device's host name. (Like there was one in the old unofficial NativeBOINC app.)

My devices got names like android_3002ca71 or android_183c46bd. Setting device name on the smartphone affects only Bluetooth and WiFi host names but not the string that BOINC client uses to identify the host.

What is even worse that the android_XXXXXXXX-type name changes after certain OS updates were received or a new ROM was flashed on the device.

It may seem to be a nice to have or purely cosmetic feature only but if you have multiple androids set up for BOINC, it could be hard to tell them apart by those ID's. A custom name would be extremely useful for that case.

PS: I tried to check for similar requests and found none. Please excuse me, if this request was discussed earlier.

**Comment by cristipurdel** [comment]
> What is even worse that the android_XXXXXXXX-type name changes after certain OS updates were received or a new ROM was flashed on the device.

Or when you reinstall the boinc app (almost sure about this)

**Comment by say4n** [comment]
Does the change of name on Android propagate to say Science United’s device listing too?
