### ISSUE TITLE
BOINC on Guix

### ISSUE THREAD

**Issue by leungbk** [BOINC/boinc#2722]
It would be nice if BOINC were available as a Guix package (https://www.gnu.org/software/guix/).

**Comment by KenSharp** [comment]
Aren't there enough package managers?

**Comment by leungbk** [comment]
>The recommended way to install the BOINC client on Linux is to use the package management system of your Linux distribution. If the BOINC client does not exist for your distribution, please open an issue in github.

**Comment by lfield** [comment]
This would require someone familiar with Guix to provide the package.
