### ISSUE TITLE
[Android] Add "Store at least X days of work" preference

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2755]
On Android the "Store at least X days of work" and the "Store up to an additional X days of work" preferences would be nice.

**Comment by AenBleidd** [comment]
Isn't it the same as #1317 but more accurate description?

**Comment by Ageless93** [comment]
I'd be hesitant with this option as it can still require a lot of free space on the device, that they don't all have. Depending on what project app your run, task sizes can be 300KB but also over 1GB in storage. Perhaps it's better to leave it to the client in this case, as it'll store a bit more than the amount of active cores you have by default.

**Comment by adamradocz** [comment]
@Ageless93 it could be under the advanced option, just like any other advanced feature.

**Comment by adamradocz** [comment]
> What's the difference between the "Store at least X days of work" and the "Store up to an additional X days of work"

I found an answer on [https://boinc.berkeley.edu/wiki/Preferences](https://boinc.berkeley.edu/wiki/Preferences)
