### ISSUE TITLE
Simple View Project name blank when friendly name unavailable

### ISSUE THREAD

**Issue by JacobWKlein** [BOINC/boinc#2757]
Simple View Project name blank when friendly name unavailable

When a Project doesn't yet have a "friendly name", Simple View shows it as blank. This is confusing.
Can we please show the URL in this case, like we do in the Advanced View?
See screenshots.

In my case:
- The Project is Climate@Home
- It was attached from Account Manager BOINCstats/BAM!
- Its URL is: https://climateathome.info/climateathome/

![20181011 boinc simple view project name blank - simple view](https://user-images.githubusercontent.com/13267799/46837213-68a6bb00-cd82-11e8-9267-09a6474c1935.png)

![20181011 boinc simple view project name blank - advanced view](https://user-images.githubusercontent.com/13267799/46837219-6c3a4200-cd82-11e8-87f7-6260eb58c71c.png)

**Comment by davidpanderson** [comment]
Fixed in #2758.  I couldn't fix the other one.

**Comment by AenBleidd** [comment]
Linked PR is merged. Closing this issue as fixed

**Comment by JacobWKlein** [comment]
I ran a test of this one today, using my one attached project that doesn't have a name.
Its URL is: https://boinc.drugdiscoveryathome.com/

BOINC 7.14.2 Simple View: Incorrectly showed the project as blank, in the combobox of projects.
BOINC 7.16.3 Simple View: Correctly showed the project as "https://boinc.drugdiscoveryathome.com/" within the list, alongside showing all the other projects too.

So, I think the changes works - Thanks!
