### ISSUE TITLE
Server Side Redirects Not Working As Expected In The Client

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#2764]
Both downloads and uploads should support server side redirect status codes. Currently downloads fail with the following:

> Project communication failed: attempting access to reference site

and uploads with:

> -224 (permanent HTTP error)

**Comment by JuhaSointusalo** [comment]
Do you mean HTTP 3xx redirect codes?

Do you have more detailed logs about these with <http_debug> enabled? Around here www.google.com (aka network test URL) is redirected to www.google.fi and previously the client has not had trouble following that redirect. It would be surprising if the client handled redirects differently when downloading or testing network connection.

As for uploads, I think a few projects have used or tried to use redirected uploads (HTTP -> HTTPS or something like that) and found out that some firewalls don't like that and cut the connection.

**Comment by lfield** [comment]
Yes, I see [this](https://github.com/BOINC/boinc/blob/master/client/http_curl.cpp#L580) in the code. I configured an Apache server with some redirects for an input file and the upload handler respectively. 

> Redirect permanent /test http://lfield.web.cern.ch/lfield/six.zip
> Redirect permanent /redirect http://lhcathome-test.cern.ch/lhcathome-dev_cgi/file_upload_handler

The redirects work when I go to the URLs in a browser. However, the client gives the following error when downloading the input file. 

> Temporarily failed download of jf_4d9d2e1b0b29eda4547047af85fcb676: transient HTTP error

**Comment by lfield** [comment]
Using the <http_debug> option I can see it is following the http->https redirection.

**Comment by lfield** [comment]
I tried a different approach using our URL redirector for Ceph. The given URL is:

> http://data-bridge.cern.ch/myfed/cms-output/six.zip

This is redirect to :

> http://vc-cms-output.s3.cern.ch/six.zip?AWSAccessKeyId=SGIUA6XJY6N885VJ33EY&Signature=NccHJq%2BLHaQXCD5G5Ha1ZAnP1xo%3D&Expires=1539688729

However this fails with the following: [download.log](https://github.com/BOINC/boinc/files/2482362/download.log)

**Comment by lfield** [comment]
Have updated the title

**Comment by ffurano** [comment]
Hi Laurence,

 the presigned URL in the log is correct, and works if pasted on a browser. I'd doublecheck with Dan,
maybe the Ceph backend is rejecting that kind of clients.

Fabrizio

**Comment by lfield** [comment]
I can confirm that the CEPH server is rejecting the request. It works fine from a browser/wget but not the BOINC client. Still investigating.

**Comment by lfield** [comment]
The issue is the [setting of the content type](https://github.com/BOINC/boinc/blob/master/client/http_curl.cpp#L607) for the request. It breaks the signature as it assumes that there is no content type. I have rebuilt the client with this commented out and everything works fine. What is the reason this is in the code?

**Comment by lfield** [comment]
The issues has been resolved.
