### ISSUE TITLE
Updater doesn't recognize minor version changes

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2772]
The Boinc 7.14.0 doesn't recognize the 7.14.2 as a new version.

**Comment by AenBleidd** [comment]
It should. Are you sure that your have updated get_current_version.xml and it contains description about 7.14.2 release? Please also remember that this file is updated by BOINC every two weeks by default.

**Comment by adamradocz** [comment]
I updated manually after all, so I can't confirm it.
