### ISSUE TITLE
Improve the efficiency/scalabilty of submit_rpc_handler.php

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#2791]
When submitting 30K jobs, the submit_rpc_handler.php exceeded the default memory limit of 128M on line [230](https://github.com/BOINC/boinc/blob/master/html/user/submit_rpc_handler.php#L230). The XML file is only 8.7MB in size.

**Comment by lfield** [comment]
As an aside using create work and passing command line arguments does not seem like a good idea to me. At least on our target machine the maximum number of arguments is O(2M).

**Comment by davidpanderson** [comment]
It doesn't use command line arguments.

**Comment by lfield** [comment]
It uses the command line in the function _submit_jobs_

https://github.com/BOINC/boinc/blob/master/html/user/submit_rpc_handler.php#L204
https://github.com/BOINC/boinc/blob/master/html/user/submit_rpc_handler.php#L211
https://github.com/BOINC/boinc/blob/master/html/user/submit_rpc_handler.php#L248
https://github.com/BOINC/boinc/blob/master/html/user/submit_rpc_handler.php#L278

In any case this would be a big change. This issue is about the memory efficiency of handling a large submission.

**Comment by davidpanderson** [comment]
Per-job parameters are not passed to create_work on the command line;
they're passed via stdin.

**Comment by davidpanderson** [comment]
After the initial report I increased the script's mem limit to 4GB.
Did that solve the problem?
