### ISSUE TITLE
Batches Failing To Be Retired

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#2793]
The python function `retire_batch(req)` seems not to work as expected. It looks like the code tries to update the column [state](https://github.com/BOINC/boinc/blob/master/html/inc/submit_util.inc#L146) but the actual column name is [project_state](https://github.com/BOINC/boinc/blob/master/db/schema.sql#L344). This also would affect `abort_batch` and `expire_batch`. If my understanding is correct I can provide a PR with the fix.

**Comment by AenBleidd** [comment]
Fixed in #2794
