### ISSUE TITLE
User web: private message system (bug)

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#2795]
Bug report from BOINC message board:

> On SetiBeta a user changed his name to include a comma. Now other users can't send him a PM. The system supplies his user number and in parenthesis his user name. The system reads the comma in his user name as a delimiter for the next user name and fails.

[Message 88737](https://boinc.berkeley.edu/forum_thread.php?id=12699&postid=88737#88737)

**Comment by JuhaSointusalo** [comment]
Duplicate of #572
