### ISSUE TITLE
Check for new BOINC update

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#28]
**Reported by KSMarksPsych on 13 Apr 37296509 21:20 UTC**
Posted by: elst93
Date: 8:12 PM 05-11-2005
Would it be possible to add a check for update in the Manager's Help menu?

Many applications have this feature these days. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/28

**Comment by romw** [comment]
**Commented by Ageless on 9 Feb 38016773 12:53 UTC**
Added in 5.8 as an automatic function.

**Comment by romw** [comment]
**Commented by Ageless on 7 Sep 38550783 00:26 UTC**
Could there be some kind of indicator for this in the GUI, not just in the message stream, where it will get lost or ignored? Perhaps with the icon in the tray changing colors, the way Windows Update does? 

Or could the new 6.4 or above versions auto-update themselves? [[br]]
Possibly download the new version when there's an internet connection and flag it available for install upon the next restart of BOINC, not unlike Firefox and Adobe Acrobat Reader do? Or is this still considered a security risk?

**Comment by romw** [comment]
**Commented by Eric Myers on 17 Jul 38561377 17:20 UTC**
This feature needs careful thought about the user controls, and it HAS to be under user control for a wide range of use cases.

Some people won't want auto-update.  They need an easy way to turn it off.

Some people only want auto-update -- set it and forget it.   They need an easy way to turn it on.

Some people will want to do updates manually, but they will appreciate an easy GUI interface, for that -- easier than the initial download and install.   They will want some kind of indication that there is a new update (not just in the message stream), and/or a way they can take an action to check for new updates (or verify that they are up to date).

As already mentioned, this exists for other software in the form of Windows Update, FireFox and Acrobat.  Add Apple Software Update to the list.  We need to design the interface so that it works well  (Apple and Firefox do, IMHO, Acrobat does not).  Windows Update is widely familiar so perhaps worth emulating, at least in general?

There has to be user control over this functionality or the people who don't like however it's done will be annoyed.

**Comment by romw** [comment]
**Commented by Nicolas on 14 Dec 38647846 23:06 UTC**
Something worth emulating from Windows Updates is the configuration options:
 * Download and install automatically.
 * Download and notify, but ask before installing.
 * Notify, but ask before downloading or installing.
 * Disable updates.

**Comment by romw** [comment]
**Commented by romw on 25 Jan 38648356 00:53 UTC**
We currently have a design doc on [AutoUpdate](wiki:AutoUpdate).

It hasn't been fully implemented as yet.

**Comment by adamradocz** [comment]
Is there any news about this issue? It would be nice to have.

**Comment by ChristianBeer** [comment]
This is still in the design stage. I'm not aware of anyone working on it. And with the current shortage of manpower it doesn't seem likely this can be done for the next release. This feature has a lot of security implications that need to be addressed.

**Comment by AenBleidd** [comment]
@ChristianBeer Are there some docs about this feature? I see existing code in client to check new updates (and it seems that it's working now) so I can do smth with this case (at least a notification about the new version in GUI).

**Comment by ChristianBeer** [comment]
There is the [AutoUpdate](http://boinc.berkeley.edu/trac/wiki/AutoUpdate) stuff which was not implemented and got deprecated 6 years ago.

The other thing is the version check that is already there. You can use this to design a GUI notification. But please think this through and propose your changes before actually doing them. Especially since you need to introduce a new GUI-RPC between Client and Manager. You can do all this in a new issue as this one is rather old and odd to properly read.

**Comment by AenBleidd** [comment]
@ChristianBeer Thank you. I'll see what I can do here and I'll open a new issue with my propositions.

**Comment by Ageless93** [comment]
Just in case you didn't see yet, the AutoUpdate code is in the source code:
https://github.com/BOINC/boinc/blob/master/client/auto_update.h
and https://github.com/BOINC/boinc/blob/master/client/auto_update.cpp

It is just not used in building the client.


-- Jord van der Elst.

**Comment by davidpanderson** [comment]
This code turned out way more complex and brittle than I planned.  I didn't fully test it.

There must be external frameworks for auto-update, maybe part of Installshield.  If so we should use that instead.

Also, there were security concerns: how to prevent hackers from using the auto-update feature to distribute malware.  The existing code doesn't address this, which is a deal-breaker.

**Comment by AenBleidd** [comment]
@davidpanderson Why we can't just check for the new version using link in cc_config (already implemented) and then just show the notification to the user and link to the download page?
I agree, that auto-update feature is too dangerous but notification about new version is safer: it is up to user's choice whether to download the new version from the given link or not.

**Comment by Ageless93** [comment]
Isn't that what
https://github.com/BOINC/boinc/blob/master/client/current_version.cpp is
already doing, though?


-- Jord van der Elst.

**Comment by ChristianBeer** [comment]
My personal opinion is that BOINC doesn't need an auto-update feature. The security measures that need to be taken into consideration and that need to be maintained properly is not worth the gain.

As to InstallShield I also don't see a bright future for this tool with BOINC. It's proprietary software that should not be used together with Open Source software. And it causes lot of problems on Windows from time to time where users need to run a fixing tool or edit registry settings. It's possible this is a general Windows problem but switching to a more open framework would be more future proof.

Also keep in mind this thread does now cover two issues. One is the auto-update feature, the other is the visual notification in the Manager when a new version is available. While I think the first one should be removed from the source code I hope someone will pick up on the second one and implement this to the Manager.

**Comment by davidpanderson** [comment]
The manager shows a "notice" when there's a new client version available, with a link to the download page.  This should be adequate.

**Comment by ChristianBeer** [comment]
This "notice" may not be what users expect nowadays. Granted I'm not the normal user but I would find it nice to have a menu option in the manager to query for updates myself.
@Ageless93 since you originally requested this feature do you find the current implementation enough or should @AenBleidd follow up on the original requirement?

**Comment by AenBleidd** [comment]
@Ageless93 I saw this code, thanks.

**Comment by Ageless93** [comment]
On Tue, Jan 10, 2017 at 12:02 AM, Christian Beer <notifications@github.com>
wrote:

> @Ageless93 <https://github.com/Ageless93> since you originally requested
> this feature do you find the current implementation enough or should
> @AenBleidd <https://github.com/AenBleidd> follow up on the original
> requirement?
>
> I think I originally put it as a ticket into SVN because a lot of people
at the time were asking for it in the forums.
After that we must've moved it from SVN to Trac, and eventually again moved
it to Github. Just saying that me asking this thing is a bit diluted. :-)

I don't think I ever really needed the option myself. If asked, I feel the
same about is as you do: a security risk. Added to that, there are enough
things that auto-update without an option to opt-out (Windows 10 comes to
mind), so I don't think we need it.

But perhaps we need to poll the users?

-- Jord van der Elst.

**Comment by ChristianBeer** [comment]
The original request was not about AutoUpdate. The discussion got sidetracked later in the original trac ticket. The original request was:

> Would it be possible to add a check for update in the Manager's Help menu?
> Many applications have this feature these days.

And the questions now is: Does the current implementation with a Notice in the Manager fulfill this request or do the users want to have an additional way to check for updates?

To further sidetrack this:  I find the idea of a user poll about what features should be implemented next into Client and Manager very intriguing. But before we do that we maybe should have a better overview of possible features (I know there is a list in the forums) and feasibility of implementation. This would be a nice way to steer further development of Client and Manager to what volunteers want.

**Comment by AenBleidd** [comment]
Opened new issue #1768.
