### ISSUE TITLE
Always have to add localhost manually in computer after world community grid install

### ISSUE THREAD

**Issue by xixou2** [BOINC/boinc#2808]
Hi,
I always have to add localhost manually in computer menu of Boinc after world community grid was installed and uninstalled.
Everytime Boinc is started, otherwhise it does not auto start the tasks.
Win 10 as of Today 2018_11_09
Boinc manager 7.14.2 x64

Uninstalling an re-installing boinc manager does not help,
even with deleting the programdata/boinc folder after uninstall.

**Comment by AenBleidd** [comment]
@xixou2, could you please check whether this option is checked?
![image](https://user-images.githubusercontent.com/3234209/48273572-3df66380-e40f-11e8-98bd-a6f8f10c9556.png)
Also could you please verify do you have the same issue with BOINC unbranded setup it could be downloaded from here: https://boinc.berkeley.edu/download.php)?

**Comment by xixou2** [comment]
Hi AenBleidd,
run the client was not ticked, indeed, I guess world community grid turn that off, you should let them know not to do that.
Now this is fine, thanks again.

**Comment by AenBleidd** [comment]
@TheAspens, could you please take a look at this? Looks like some configuration issue with the branded installer

**Comment by AenBleidd** [comment]
Was not able to reproduce this on fresh installed Windows 10 x64 with the installer `wcg_7.14.2_windows_intelx86__22_568195_f26e94dc.exe`
