### ISSUE TITLE
[Website] Update the BOINC source code page

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2812]
On the [BOINC source code page ](https://boinc.berkeley.edu/trac/wiki/SourceCodeGit#Windowsbuilddependencies) the URL in the example `git clone http://boinc.berkeley.edu/git/boinc_depends_win_vs2010.git` should be updated to `https://boinc.berkeley.edu/git/boinc_depends_win_vs2013.git`.

On the standard HTTP the cloning is not working, plus the newest repository should be used.

Other:
On the [Source code structure overview section](https://boinc.berkeley.edu/trac/wiki/SourceCodeGit#Sourcecodestructureoverview) the `m4` folder has a `(Why!)` note. Shouldn't we do with it something?

**Comment by CharlieFenton** [comment]
> On the BOINC source code page the URL in the example git clone http://boinc.berkeley.edu/git/boinc_depends_win_vs2010.git should be updated to https://boinc.berkeley.edu/git/boinc_depends_win_vs2013.git.

I don't think it matters, since the context makes it clear that you should substitute the version of Visual Studio you are using in the command. But I have no objection to the change you suggest

**Comment by cwallbaum** [comment]
Please be careful!

About two months ago I tried to compile BOINC (7.12.x) with Microsoft Visual Studio 2013 Community-Edition and I have to say: Compiling works, but the builds are buggy! I'm not sure about the causes, but I guess that the msvcrt120 libs are the reason for:
- tray app/icon problems (in 9 of 10 cases boincmgr is not added to the systray)
- boincmgr doesn't always start or correctly closes a client instance if there is not already an instance running
- there are a few projects that cannot be added by the "project assistant" (the one that boincmgr runs at the first start; for example WCG: A connection to the project server(s) cannot be established -> adding failed)
- a few other problems...

I think that there is a reason why the official BOINC is still build with Visual Studio 2010?!

I got a license of VS2010 to run some tests and yes, these builds are working!

Best wishes

walli
