### ISSUE TITLE
Update the community profile on GitHub

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2819]
I propose to update the [community profile](https://github.com/BOINC/boinc/community).

1. The Contributor Covenant Code of Conduct template suggested by GitHub is similar that the BOINC uses but more detailed but still simple. I propose to use that template.
2. Contributing guidelines would make easier for new people how can they contribute.
3. IMO standardizing the issues with issue templates would make our work a little bit easier, by showing people step-by-step instructions on how to give a clear issue description. I propose 3 templates, Bug report, Feature request, and Other issues. [GitHub's temples](https://github.com/BOINC/boinc/issues/templates/edit) could be the base for each template.
4. I think we could also benefit a Pull request template too.

Any thoughts on this?

**Comment by AenBleidd** [comment]
@adamradocz, fell free to create PR with changes you think are good
