### ISSUE TITLE
Move the Trac/Wiki to Github

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2820]
I think moving the development related [trac/wiki](https://boinc.berkeley.edu/trac/wiki) from the website to the GitHub could have a few benefits.

1. More people could edit the documents if necessary.
2. The development related stuff like source and its documentation would be in one place.

Any thoughts on this?

**Comment by AenBleidd** [comment]
This will require significant efforts to rewrite from one markdown style to another. As far as I know there is no autoconverter to do this.
The idea is good bu it requires someone who is willing to do this

**Comment by CharlieFenton** [comment]
There are links to the trac/wiki pages in several places, perhaps many, including the ReadMe file we distribute with the Macintosh BOINC installer. Someone would need to find them all and update them, or change the existing pages to forward to the new ones.

**Comment by lfield** [comment]
I support the idea of moving the documentation to github. Documentation can be updated in parallel with the code. A PR should contain the new feature and the supporting documentation change. A quick google turned up the [Pandoc](https://pandoc.org/) tool. Someone will need to volunteer to coordinate this effort but others can contribute. It is a task that does not require knowledge of the code base.

**Comment by adamradocz** [comment]
I don't have permission to edit the Wiki. If I get permission I will slowly copy the pages.

**Comment by AenBleidd** [comment]
The interesting this is that in the footer of wiki you can find next:
![image](https://user-images.githubusercontent.com/3234209/48625547-42df8800-e9b8-11e8-81b4-8b7f8c66b651.png)
But this address gives 404 error

**Comment by AenBleidd** [comment]
@davidpanderson, could you please give persmissions to @adamradocz?

**Comment by AenBleidd** [comment]
While I have no time for significant development, I started to work on this ticket.

**Comment by lfield** [comment]
I believe @TheAspens was working on a plan for this. We probably need to do it in a structured way.

**Comment by AenBleidd** [comment]
In any case, existing wiki should be converted to Markdown format. And I plan to do this while I have no possibility to develop anything. If these could be then used - it's fine. If no - it's also fine :)

**Comment by lfield** [comment]
I would hope that it is used but think we could do with a little guidance from @TheAspens. As mentioned previously am happy to contribute to this effort where I can.

**Comment by AenBleidd** [comment]
I agree with you, but meanwhile some work could be done, even if then it should be redone (I hope not completely), or fixed, it would be easier not to start with the empty page.
My branch with existing and future changes for reference:
https://github.com/AenBleidd/boinc/blob/2820_move_wiki/wiki/WikiStart.md

**Comment by TheAspens** [comment]
I apologize for the vastly late proposal.  Here are my thoughts about organization.  Please edit/comment and lets discuss at the next contributor call.  This is intended to be a starting point for how to organize not a final version. 
 https://docs.google.com/document/d/1UvaYyLzZSRsZTiK0wywDsT36dg14TpVS63O8KtMopCU/edit?usp=sharing

**Comment by AenBleidd** [comment]
I like this idea, thank you, @TheAspens.
I do not know whether I could be on that call, but I definitely like the way it goes

**Comment by davidpanderson** [comment]
There are lots of tools for converting trac wiki to markdown.
Below is one I found.  It gets the trac pages from the sqlite DB;
I can send this DB to anyone if they want.

Anyway, this doesn't do everything correctly.
I fixed a couple of things but there are more.
Someone who understands regular expressions can do this
in a straightforward way; I don't have time right now unfortunately.

#!/usr/bin/python
# vim:set fileencoding=utf-8 sw=2 ai:

# downloaded from https://gist.github.com/tcchau/4628317
# ... which is a fork from https://gist.github.com/sgk/1286682

import sqlite3
import datetime
import re
# additional imports --ah
import os
import sys

SQL = '''
  select
      name, version, time, author, text
    from
      wiki w
    where
      version = (select max(version) from wiki where name = w.name)
'''

# Modified expression to generate a file for every version (overwriting previous version) --ah
SQLgit = '''
  select
      name, version, time, author, text, comment
    from
      wiki w
    order by time
'''

# exclude wiki pages starting with.... --ah
excludepages = [ "Trac" ]

# Add function to try to preserve author information in git --ah
def gitauthor(author):
  if author == "foo@bar":
    return " --author \"Foo Bar <" + author + ">\" "
  # add more here if you want to preserve author information for edits...
  elif author == "trac":
    return " --author \"trac <" + author + "@example.com>\" "
  else:
    print "WARNING: unknown author: " + author
    return ""

# helper functions from https://gist.github.com/gazpachoking/9540849

def convert_wiki_link(link):
  if link.startswith('wiki:'):
    link = link[5:]
  return link.strip("'").replace('/', '-')


def sub_full_wiki_link(m):
  return '[%s](%s)' % (m.group(2), convert_wiki_link(m.group(1)))


def sub_simple_wiki_link(m):
  return '[[%s]]' % convert_wiki_link(m.group(1))


def sub_fenced_block(m):
  if m.group(1) == 'html':
    return '\n%s\n' % m.group(2)
  elif m.group(1):
    return '```%s\n%s\n```' % (m.group(1), m.group(2))
  return '```\n%s\n```' % m.group(2)


def sub_table(m):
  lines = []
  for group in m.group(0).strip().split('\n'):
    lines.append(' | '.join(group.strip().split('||')).strip())
  width = len(m.group(1).strip().split('||')) - 2
  lines.insert(1, '| %s |' % ' | '.join('---' for x in range(width)))
  return '\n%s\n' % '\n'.join(lines)

# use alternative SQL if using git to preserve history of changes --ah
if "--git" in sys.argv:
  SQL = SQLgit

conn = sqlite3.connect('../trac.db')
result = conn.execute(SQL)
for row in result:
  #print(row)
  name = row[0]
  version = row[1]
  time = row[2]
  author = row[3]
  text = row[4]
  #comment = row[5]
  comment=''

  # add possibility to exclude certain pages. --ah

  if name.startswith(tuple(excludepages)):
    print "Skipping " + name + " (version " + str(version) + ")"
    continue

  text = re.sub('\r\n', '\n', text)
  text = re.sub(r'{{{(.*?)}}}', r'`\1`', text)
  # below 2 line from https://gist.github.com/gazpachoking/9540849
  text = re.sub(r'(?sm){{{\n(?:#!([a-z]+)\n)?(.*?)\n}}}', sub_fenced_block, text)
  text = re.sub(r'(?m)^(\|\|[^\n]+\|\| *\n?)+$', sub_table, text)

  def indent4(m):
    return '\n    ' + m.group(1).replace('\n', '\n    ')
  text = re.sub(r'(?sm){{{\n(.*?)\n}}}', indent4, text)
  # Modified lines below to allow sloppy trailing spaces --ah
  text = re.sub(r'(?m)^====\s+(.*?)\s+====$', r'#### \1', text)
  text = re.sub(r'(?m)^====\s+(.*?)\s+====\s\#(.*?)$', r'### \1 <a name="\2"></a>', text)
  text = re.sub(r'(?m)^===\s+(.*?)\s+===$', r'### \1', text)
  text = re.sub(r'(?m)^===\s+(.*?)\s+===\s\#(.*?)$', r'### \1 <a name="\2"></a>', text)
  text = re.sub(r'(?m)^==\s+(.*?)\s+==$', r'## \1', text)
  text = re.sub(r'(?m)^==\s+(.*?)\s+==\s\#(.*?)$', r'### \1 <a name="\2"></a>', text)
  text = re.sub(r'(?m)^=\s+(.*?)\s+=$', r'# \1', text)
  text = re.sub(r'(?m)^=\s+(.*?)\s+=\s\#(.*?)$', r'### \1 <a name="\2"></a>', text)
  text = re.sub(r'^       * ', r'****', text)
  text = re.sub(r'^     * ', r'***', text)
  text = re.sub(r'^   * ', r'**', text)
  text = re.sub(r'^ * ', r'*', text)
  text = re.sub(r'^ \d+. ', r'1.', text)

  a = []
  for line in text.split('\n'):
    if not line.startswith('    '):
      #line = re.sub(r'\[(https?://[^\s\[\]]+)\s([^\[\]]+)\]', r'[\2](\1)', line)
      #line = re.sub(r'\[(wiki:[^\s\[\]]+)\s([^\[\]]+)\]', r'[\2](/\1/)', line)
      #line = re.sub(r'\!(([A-Z][a-z0-9]+){2,})', r'\1', line)
      #line = re.sub(r'\'\'\'(.*?)\'\'\'', r'*\1*', line)
      #line = re.sub(r'\'\'(.*?)\'\'', r'_\1_', line)
      # --- above original replaced with parts from https://gist.github.com/gazpachoking/9540849
      line = re.sub(r'(?<!\[)\[([^\s\[\]]+?)\]', sub_simple_wiki_link, line)
      line = re.sub(r'\[([a-z]+?://[^\s\[\]]+)\s([^\[\]]+)\]', r'[\2](\1)', line)
      line = re.sub(r'\[(wiki:?[^\s\[\]]+)\s([^\[\]]+)\]', sub_full_wiki_link, line)
      line = re.sub(r'\!(([A-Z][a-z0-9]+){2,})', r'\1', line)
      line = re.sub(r'\'\'\'(.*?)\'\'\'', r'*\1*', line)
      line = re.sub(r'\'\'(.*?)\'\'', r'_\1_', line)
    a.append(line)
  text = '\n'.join(a)

  # Modification to create directory path when needed. --ah
  if "/" in name:
    try:
      os.makedirs(os.path.dirname(name))
    except:
      pass


  fp = file('%s.md' % name, 'w')
  fp.write(text.encode('utf-8'))
  fp.close()

  # commit newly created/overwritten file to preserve history. --ah
  if comment != "":
   comment = "\n\n%s" %comment
  if "--git" in sys.argv:
    os.system("git add .; git commit --quiet " + gitauthor(author) + " --date=\"" + datetime.datetime.fromtimestamp(time/1000000).strftime('%Y/%m/%d %H:%M:%S') + "\" -avm \"Import " + name + ", version " + str(version) + str(comment) + "\"")

**Comment by jring-o** [comment]
I've got a decent start a pretty good grasp of the tasks needed to finish. Reach out to me on Slack if you want to help.

https://github.com/jring-o/BOINCWiki/wiki

**Comment by davidpanderson** [comment]
Scripts that convert trac wiki to md.
I tried a couple of these and they worked mostly but not entirely
(e.g. they didn't do links correctly)

https://github.com/HeinrichHartmann/trac2md/blob/master/trac2md.lua
(in Lua)

https://gist.github.com/cvogt/8283260
(in Ruby)

https://scodoc.org/git/jmplace/DocScoDoc/src/branch/master/tools/trac2md.py

https://git.hactrn.net/sra/trac-wiki-to-markdown/src/9830a562f93005599e09964bcea79c901fb94bb4/trac2md.py

https://gist.github.com/kskmori/3bcd68fa022e635105af285274161dbb

**Comment by AenBleidd** [comment]
Trac/wiki has been converted.
It's now available here: https://github.com/BOINC/boinc/wiki
