### ISSUE TITLE
Move proposed developments from trac/wiki to GitHub as Issues

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2822]
For better project management the still valid [proposed developments on track/wiki](https://boinc.berkeley.edu/trac/wiki/DevProjects) should be moved to GitHub as issues.

Any thoughts on this?

**Comment by lfield** [comment]
This is a duplicate of #2820. But agree that this should be moved to CONTRIBUTING.md and reference the [BOINC policies](https://github.com/BOINC/boinc-policy).

**Comment by adamradocz** [comment]
I think similar but slightly different. The #2820 only a Wiki -> Wiki migration, but this issue propose to create issues all the proposed development projects and simply delete them from the wiki.

**Comment by AenBleidd** [comment]
All major ideas were already published on GitHub as issues.
