### ISSUE TITLE
PHP warning when running DB dump

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#2825]
Warning: Invalid argument supplied for foreach() in /boincdata/boinc/project/lhcathome-dev/html/ops/export_credit_by_app.php on line 37

**Comment by davidpanderson** [comment]
This feature requires defining $sub_projects in your project.inc:
https://boinc.berkeley.edu/trac/wiki/PerAppCredit

**Comment by lfield** [comment]
$sub_projects is defined but using var_dump before the foreach in export_credit_by_app.php  shows that it is set to  _null_

**Comment by davidpanderson** [comment]
I'm not seeing this on my test project.
export_credit_by_app.php includes inc/util_ops.inc, which includes project/project.inc
