### ISSUE TITLE
BOINC refuses to add exclusive application it can't execute, like Windows UWP apps

### ISSUE THREAD

**Issue by GreenReaper** [BOINC/boinc#2826]
On Windows 10, UWP apps such as the Xbox app (which may be impacted, particularly by GPU execution) cannot be added as exclusive applications because BOINC does not recognize them as executable:

> 'XboxApp.exe' is not an executable application.

This is even though the apps _can_ be executed, and indeed may be running, as that user or another.

Here is [a screenshot of the advanced security settings for this executable](https://www.dropbox.com/s/tufitql9gjwm2fd/UWPSecurity.png?dl=0).
(I wasn't able to upload it to the issue - "Something went really wrong".)

As you can see it provides a condition to executablilty:
> WIN://SYSAPPID Contains "MICOSOFT.XBOXAPP_..."

This is an AppContainer [package moniker](https://books.google.co.uk/books?id=y83LDgAAQBAJ&pg=PT981&lpg=PT981&dq=%22SYSAPPID%22+appcontainer&source=bl&ots=kHarMBMpkw&sig=3pUMUMJWS7nHgVcOosJY1rX5MLc&hl=en&sa=X&ved=2ahUKEwiD54PvptbeAhVTT8AKHawMDoUQ6AEwAnoECAUQAQ#v=onepage&q=%22SYSAPPID%22%20appcontainer&f=false) attached to the impersonation security token upon app execution.

The issue is that BOINC is checking for the ability to open for executability by the BOINC process:
https://github.com/BOINC/boinc/blob/f14d96d2be2e5a290177f7b5391b0802fbd3756c/clientgui/DlgExclusiveApps.cpp#L331

In practice this file _can_ be opened as executable, even by the user, but only when actually executing the app. Indeed it seems that this problem is already known (to an extent) based on a line just a little further down:
https://github.com/BOINC/boinc/blob/f14d96d2be2e5a290177f7b5391b0802fbd3756c/clientgui/DlgExclusiveApps.cpp#L360

---

I therefore suggest that executability not be tested - after all, you might want to disable BOINC when applications are running which the user in question cannot execute, even as an app, if it interferes with them.

At the end of the day, BOINC needs a list of filenames to processes it can see running. If if it gets a validly-_formatted_ filename (not necessarily an existing file), as `fn.IsOk()` [implies](http://proton-ce.sourceforge.net/rc/wxwidgets/docs/html/wx/wx_wxfilename.html#wxfilenameisok), should that not be enough?

---

I'm not sure it should even test (e.g. `fn.FileExists()`) whether the file can be _accessed_ by the current user, since that is not a requirement for it being a running process on the computer - though I don't know if you can still see the filename in the process list in that case.

In this light a file picker might not be the ideal option, but it'd be possible to remove `wxFD_FILE_MUST_EXIST` which would allow users to enter filenames that aren't visible to them:
https://github.com/BOINC/boinc/blob/f14d96d2be2e5a290177f7b5391b0802fbd3756c/clientgui/DlgExclusiveApps.cpp#L311
This would also save time when the user knows the filename they want to enter, but not its location.

**Comment by Ferroin** [comment]
I'm inclined to agree, the requirement that exclusive apps be executable by the BOINC process seems entirely bogus to me, especially because it's reasonably certain to not be the case for certain types of application when running BOINC as a service.

**Comment by AenBleidd** [comment]
Fixed via #2843
