### ISSUE TITLE
Make statistics tab scrollable sideways when sizing Boinc Manager by hand.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#284]
**Reported by Ageless on 2 Feb 37466233 02:40 UTC**
Please make it possible that the statistics tab is scrollable sideways when sizing BOINC Manager's window by hand. Now all text based tabs are scrollable to the right, but for the Statistics tab and the Disk tab. The pie charts in the Disk tab resize in a normal way, but the Statistics become a jumbled mass of illegibility. 

See attachment on BOINC 5.10.7

Migrated-From: http://boinc.berkeley.edu/trac/ticket/292

**Comment by ChristianBeer** [comment]
The current version 7.6.33 (Linux) doesn't scroll left-right for both tabs.

**Comment by Ageless93** [comment]
I'm retracting this issue. Resizing the manager keeps the Statistics legible in all sizes.
