### ISSUE TITLE
Android not running jobs?

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2855]
User email:

Can't see any tasks, although the phone is warm. Galaxy S8 ATT with current updates.

GUI Messages

11-29 16:35:36.682 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:35:36.274 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:35:35.538 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:53.664 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:52.656 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:52.120 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:49.657 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:48.689 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:47.685 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:46.679 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:45.683 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:44.662 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:43.651 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:42.668 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.
11-29 16:34:41.683 W/BOINC_GUI(26150): TasksActivity: Could not load data, clientStatus not initialized.

**Comment by AenBleidd** [comment]
Application just should be closed (and removed from running applications) and then restarted again. I have similar issues starting after last release.

**Comment by AenBleidd** [comment]
Seems very similar to #2467
Closing for now as a duplicate
