### ISSUE TITLE
GDPR preference page improvements

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#2856]
**Describe the bug**
User feedback from testing GDPR

**Steps To Reproduce**
Visit the project preferences page. 

**Expected behavior**

Agreeing to the terms and conditions should be formulated as a question.
Links to the terms-of-use/data protection should be placed on the prefs page.
Force a logoff (+ show a warning) when the box is unchecked.

**Additional context**

**Comment by drshawnkwang** [comment]
I'm guessing you see this because you enabled "Privacy Prefs" in the manage consent_type Ops page for consent type `ENROLL`?

I think my intent was this consent type was not meant to be part of the privacy prefs. And while it is the intent of the framework to allow users to withdraw their consent to this enrollment consent type, functionally there is no method of doing so.

**Comment by nilsjh** [comment]
The links to terms of use should also be linked to the project_preferences page. (e.g. prefs.php)

**Comment by nilsjh** [comment]
![terms-of-use](https://user-images.githubusercontent.com/45591105/50228238-c02b5d80-03a7-11e9-94ef-2fbb02296bc4.png)

**Comment by drshawnkwang** [comment]
> However, when the consent type STATSEXPORT is enabled, the screen the user gets to upon registration does not propose validation of consent to export statistcs.

Each consent type, such as ENROLL or STATSEXPORT must be handled independently of one another. The 'agree to terms-of-use' page you see during Web enrollment only sets the user's agreement to the ENROLL consent type. All other types, e.g., STATSEXPORT, must be handled elsewhere, each one a separate question with a separate checkbox.

**Comment by nilsjh** [comment]
Fine, but as the concept of user consent is new to BOINC, it would make sense to ask for consent both for STATSEXPORT and ENROLL and the same time, with 2 tickboxes on the same screen.  This would be easier for existing volunteers, so that they are made aware of the changes as soon as they login.

**Comment by AenBleidd** [comment]
I strongly believe the current implementation is good enough and don't require any additional improvements. Closing this as 'not needed'.
