### ISSUE TITLE
signup.php doesn't show terms of use

### ISSUE THREAD

**Issue by JuhaSointusalo** [BOINC/boinc#2869]
**Describe the bug**
I have set up test project with terms of use and enabled `<enable_login_mustagree_termsofuse>`. If I click the green _Join $PROJECT_ button, fill in account details and click the _Join_ button I am told I need to go back to the previous page and agree to the terms of use. But the page doesn't show TOU.

**Steps To Reproduce**
1. `run make_project --test_app blaah blaah`
2. enable GDPR compliance setting per the [wiki page](https://boinc.berkeley.edu/trac/wiki/GdprCompliance)
3. open project web page in browser
4. click  the green _Join $PROJECT_ button
5. fill in the form, notice that there are no terms shown and click green _Join_ button

**Expected behavior**
The page shows terms of use so that I can accept them.

**Additional context**
The big green button on the front page takes to `signup.php`. The _Sign Up_ link in upper right corner takes to `create_account_form.php`. Having two pages for signing up is probably a bug in itself. And looking around there is also `join.php`.

**Comment by JuhaSointusalo** [comment]
At LHC@athome-dev you have the _Sign Up_ link at the upper right corner which takes you to the `create_account_form.php`. You also have the big greyish Join _LHCathome-dev_ button which takes you to the `join.php` page. The `join.php` page tells you to create an account with Manager so that's not a problem.

At LHC@home main you have the same _Sign Up_ link. The big greyish _Join LHC@home_ button instead takes you to `signup.php` page. I think web sign up should stop working from the big button at the main project once you have updated the project and enabled the consent stuff.

From the comments in code `signup.php` is for vetted projects and supports auto-attach and `join.php` is for others. I went looking for documentation about auto-attach and found [SimpleAttach](https://boinc.berkeley.edu/trac/wiki/SimpleAttach). That page lists yet another sign up page, `register.php`. `register.php` does display terms of use and seems to work fine but I think the wiki page is outdated and `register.php` is deprecated and `signup.php` should be used instead of it.

**Comment by nilsjh** [comment]
Thanks. We should also show the terms of use in "prefs.php" when users want to edit their project preferences.  Right now, it mentions "General project terms-of-use", but there is no link from the text.

**Comment by AenBleidd** [comment]
@lfield, is this still the issue?

**Comment by lfield** [comment]
I can't find a way to navigate to `signup.php` from the LHC@home website. `join.php` or `create_account_form.php` is used. Will close this issue.
