### ISSUE TITLE
Built with -ffast-math option in gcc/g++, boinc client doesn't recognize beignet (intel gpu) library on Linux

### ISSUE THREAD

**Issue by ghost** [BOINC/boinc#2910]
**Describe the bug**
I am building boinc client from git master tree on Fedora 29 linux.
Building boinc client by configuring 'CFLAGS="-O4 -mavx2 -funroll-loops -fforce-addr -ffast-math" CXXFLAGS=$CFLAGS ./configure --disable-server --disable-manager', boinc client doesn't recognize intel gpu, though it detects nvidia gpu (my machine has both).  If -ffast-math is removed, boinc client works for both intel and nvidia.   Here I use "-O4 -mavx2", but they don't matter.  With only "-O3", it happens.  -O4 directs more aggressive optimization.   -mavx2 is just for my cpu (Haswell).
Funnily, usage of -ffast-math is introduced in boinc wiki https://boinc.berkeley.edu/wiki/Compiling_the_core_client.

**Steps To Reproduce**
1. Just configure with 'CFLAGS="-O4 -mavx2 -funroll-loops -fforce-addr -ffast-math" CXXFLAGS=$CFLAGS ./configure --disable-server --disable-manager' under boinc directory.
2. make and install boinc and launch.

**Expected behavior**
Intel integrated gpu must be detected and used by boinc client.

**Screenshots**
![boinc-intel-missing](https://user-images.githubusercontent.com/28835810/49983410-f0d55680-ffa5-11e8-8476-40fb30c04388.png)

**System Information (please complete the following information):**
 - OS:  Linux Fedora 29 x86_64
 - BOINC Version: master branch (7.15.0)

**Additional context**
This happens with boinc 7.14.2 also.

**Comment by AenBleidd** [comment]
@maverick6664 
Looks like it is internal driver issue:
https://unix.stackexchange.com/questions/414656/darktable-doesnt-recognize-intel-graphics-620s-opencl-beignet-in-fedora-27/419590
Also described here:
https://www.freedesktop.org/wiki/Software/Beignet/
Could you please try this:

> "Beignet: self-test failed" and 15-30 unit tests fail on 4th Generation (Haswell) hardware. On Haswell, shared local memory (__local) does not work at all on Linux <= 4.0, and requires the i915.enable_ppgtt=2 [boot parameter](https://wiki.ubuntu.com/Kernel/KernelBootParameters) on Linux 4.1.
> 
> This is fixed in Linux 4.2; older versions can be fixed with [this patch](https://01.org/zh/beignet/downloads/linux-kernel-patch-hsw-support).
> 
> If you do not need __local, you can override the self-test with
> 
> export OCL_IGNORE_SELF_TEST=1
> 
> but using __local after this may silently give wrong results.

**Comment by truboxl** [comment]
Beignet is deprecated.

**Comment by AenBleidd** [comment]
Could you please mention a proof of it, please?

**Comment by truboxl** [comment]
>Beignet vs. NEO
>Starting in Q1’2018, Beignet has been deprecated in favor of NEO OpenCL driver (https://01.org/compute-runtime).
>We encourage the existing Beignet community members to explore the new driver stack and provide feedback.
>Beignet remains our recommended solution for legacy HW platforms (e.g. Ivybridge, Sandybridge, Haswell).

https://01.org/beignet

**Comment by AenBleidd** [comment]
Since Beignet is deprecated for 4 years already, I see no reason to fix this issue.
Closing as 'wontfix'
