### ISSUE TITLE
support VBox 6.x

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2915]
Check whether vboxwrapper works with VBox 6.X
(with both COM and vbox_manage interfaces).
If not, fix it.

**Comment by JacobWKlein** [comment]
I wrote this in an email on 4/17/2019:

>  On 4/16/2019, Oracle released VirtualBox v6.0.6.
>
>This version includes a fix for a "last snapshot restore" issue, where earlier v6.0.x versions had the restore hanging at 97%, which I considered a blocking issue. Fixed now. Details here:
https://www.virtualbox.org/ticket/18212
>
>Could we please proceed to get a VBoxWrapper application update that supports this version of VirtualBox?
>
>It looks like progress could be tracked here in the open BOINC ticket:
>https://github.com/BOINC/boinc/issues/2915
>
>Let me know when I can help test it, please.
>
>Thanks,
>Jacob Klein

**Comment by JacobWKlein** [comment]
Any progress on this? I'd like to see an updated VBoxWrapper, so VM projects can finally deploy the version that supports VirtualBox v6!  Progress?

**Comment by davidpanderson** [comment]
Do we know that vboxwrapper doesn't work with VBox v6?

Also, does v6 have the ability to lower the process priority of a VM instance?

**Comment by marius311** [comment]
> Do we know that vboxwrapper doesn't work with VBox v6?

I've not had the time to test myself but lots of reports of errors with VBox 6 from Cosmology@Home, e.g. https://www.cosmologyathome.org/forum_thread.php?id=7563

**Comment by JacobWKlein** [comment]
I'm pretty sure it needs an update to use the COM interface, right? Else it may successfully fall back to VBoxManage, but I haven't tested it, as I thought we were getting an update.

**Comment by davidpanderson** [comment]
Yes.  Rom just told me how to update the COM interface.  I'll try to do this shortly.

**Comment by JacobWKlein** [comment]
You did it last time, too, I think. It took 3 tries, if I recall ;) I won't be able to test any new version until Sunday at the earliest.

**Comment by lfield** [comment]
LHC@home is using the VBoxManage interface for Windows so is [running fine ](https://lhcathome.cern.ch/lhcathome/forum_thread.php?id=4905)without this change.  It looks like the [process priority](https://www.virtualbox.org/ticket/13500) issue has still not been fixed.

**Comment by davidpanderson** [comment]
I made new versions (26201) of the Windows vboxwrapper:
https://boinc.berkeley.edu/trac/wiki/VboxApps#Premadevboxwrapperexecutables

**Comment by AenBleidd** [comment]
@davidpanderson, will you commit your changes via pull request? As far as I remember @romw made new release on github for every release of vboxwrapper also (e.g. https://github.com/BOINC/boinc/tree/vboxwrapper/26200 )

**Comment by JacobWKlein** [comment]
@davidpanderson Just to make sure, isn't there some like .tlb file or something that was used to create the executable, such that the .tlb will need to be included in our source code somewhere?

Also ... yikes, it's been a long time since I've had to test this stuff out (with custom app_config stuff), but I'm going to start doing that now, and will chime back in with results when I have them. It may take a few days.

**Comment by JacobWKlein** [comment]
@davidpanderson I found 2 problems, likely related. I feel like you missed something that you've missed before, that should be on some checklist or something for the future. Add it to that list? Details are below. Let me know when to test a new "Release 2" please.

=================
Problem 1:

26200 app_info, stderr.txt correctly has 1 line:
2019-05-12 15:32:56 (13260): vboxwrapper (7.9.26200): starting

26201 app_info, stderr.txt incorrectly has 2 lines:
2019-05-12 15:53:16 (7052): Detected: vboxwrapper 26200
2019-05-12 15:53:16 (7052): Detected: BOINC client v7.14.2

I was expecting this 1 line:
2019-05-12 15:33:16 (13260): vboxwrapper (7.15.26201): starting

=================

Problem 2:
The file details of the .exe file erroneously say:
File version: 7.15.26200.0

I was expecting:
File version: 7.15.26201.0

=================

**Comment by davidpanderson** [comment]
I forgot to update the version # in a couple of places.
I made a new version (26202) with these fixed.
See
https://boinc.berkeley.edu/trac/wiki/VboxApps#Premadevboxwrapperexecutables

The vboxwrapper version # is now independent of the client version.
There shouldn't be anything like 7.15.26202.
I'm still seeing this in the file details of the .exe.
I can't figure out where this info comes from.

**Comment by JacobWKlein** [comment]
Okay. I'll test 26202 in the upcoming days and report results here. Let me know if you spin another version for me to test.

**Comment by JacobWKlein** [comment]
David,
When I go to the link you mentioned, it is still serving 26201 despite saying 26202 on screen. Can you fix that please, and let me know when to re-test?

**Comment by JacobWKlein** [comment]
Testing looks good on starting, snapshotting, and resuming from snapshot, for RNA World. See attached. I'll need to wait a little bit to test against LHC VMs (I use that project to test "new" VM creation)... as it appears their DB is currently down. Will chime in later with those results.

Also, don't forget to fix those hyperlinks please :) Thank you.
[RNA World - 26202 app_info - VirtualBox 5.2.txt](https://github.com/BOINC/boinc/files/3177875/RNA.World.-.26202.app_info.-.VirtualBox.5.2.txt)
[RNA World - 26202 app_info - VirtualBox 6.0.txt](https://github.com/BOINC/boinc/files/3177876/RNA.World.-.26202.app_info.-.VirtualBox.6.0.txt)

**Comment by JacobWKlein** [comment]
I'm picking up the LHC testing today.

**Comment by JacobWKlein** [comment]
@davidpanderson I think I found significant problems in my testing today. Did you test 26202 yet?

I'm betting you'll be able to repro the problems, if you do -- I'll even give you an LHC app_info to make it easy - Just get one of their VM tasks, close BOINC, place the app_info.xml + exe + pdb into their project folder, and find the problems.

[app_info - LHC - CMS+Theory+ATLAS - 26202 vboxwrappers.zip](https://github.com/BOINC/boinc/files/3194214/app_info.-.LHC.-.CMS%2BTheory%2BATLAS.-.26202.vboxwrappers.zip)

It seems like the COM interface gets stuck once the VM is started, and then doesn't communicate with the VM anymore. This results in the following 3 behaviors I noticed, for both RNA World and LHC (CMS/Theory/ATLAS). I'm also including a sample of the stderr.txt files.

1) When I suspend computation using Activity > Suspend, the VM does not suspend, and the VM erroneously keeps running.
2) When I exit BOINC, the app does not gracefully stop the VM. Instead, the BOINC processes are killed by heartbeat timeout, and the VM erroneously keeps running.
3) While a task is running, I expected the "Show VM Console" button to show, but it did not show up.

Note: When you have the LHC app_info placed in their Project folder, you will not be able to get new work. It results in "Scheduler request failed: HTTP internal server error", and I am tracking it as a separate issue here:
https://lhcathome.cern.ch/lhcathome/forum_thread.php?id=5034




[stderr - LHC Atlas - 26202 app_info - VirtualBox 5.2.txt](https://github.com/BOINC/boinc/files/3194202/stderr.-.LHC.Atlas.-.26202.app_info.-.VirtualBox.5.2.txt)
[stderr - LHC Atlas - 26202 app_info - VirtualBox 6.0.txt](https://github.com/BOINC/boinc/files/3194203/stderr.-.LHC.Atlas.-.26202.app_info.-.VirtualBox.6.0.txt)
[stderr - LHC Atlas - Project vboxwrapper - VirtualBox 5.2.txt](https://github.com/BOINC/boinc/files/3194204/stderr.-.LHC.Atlas.-.Project.vboxwrapper.-.VirtualBox.5.2.txt)
[stderr - LHC Atlas - Project vboxwrapper - VirtualBox 6.0.txt](https://github.com/BOINC/boinc/files/3194205/stderr.-.LHC.Atlas.-.Project.vboxwrapper.-.VirtualBox.6.0.txt)
[stderr - LHC CMS - 26202 app_info - VirtualBox 5.2.txt](https://github.com/BOINC/boinc/files/3194206/stderr.-.LHC.CMS.-.26202.app_info.-.VirtualBox.5.2.txt)
[stderr - LHC CMS - 26202 app_info - VirtualBox 6.0.txt](https://github.com/BOINC/boinc/files/3194207/stderr.-.LHC.CMS.-.26202.app_info.-.VirtualBox.6.0.txt)
[stderr - LHC CMS - Project vboxwrapper - VirtualBox 5.2.txt](https://github.com/BOINC/boinc/files/3194208/stderr.-.LHC.CMS.-.Project.vboxwrapper.-.VirtualBox.5.2.txt)
[stderr - LHC CMS - Project vboxwrapper - VirtualBox 6.0.txt](https://github.com/BOINC/boinc/files/3194209/stderr.-.LHC.CMS.-.Project.vboxwrapper.-.VirtualBox.6.0.txt)
[stderr - LHC Theory - 26202 app_info - VirtualBox 5.2.txt](https://github.com/BOINC/boinc/files/3194210/stderr.-.LHC.Theory.-.26202.app_info.-.VirtualBox.5.2.txt)
[stderr - LHC Theory - 26202 app_info - VirtualBox 6.0.txt](https://github.com/BOINC/boinc/files/3194211/stderr.-.LHC.Theory.-.26202.app_info.-.VirtualBox.6.0.txt)
[stderr - LHC Theory - Project vboxwrapper - VirtualBox 5.2.txt](https://github.com/BOINC/boinc/files/3194212/stderr.-.LHC.Theory.-.Project.vboxwrapper.-.VirtualBox.5.2.txt)
[stderr - LHC Theory - Project vboxwrapper - VirtualBox 6.0.txt](https://github.com/BOINC/boinc/files/3194213/stderr.-.LHC.Theory.-.Project.vboxwrapper.-.VirtualBox.6.0.txt)

**Comment by JacobWKlein** [comment]
Crystal Pellet reported success on Windows 7 here:
https://lhcathome.cern.ch/lhcathome/forum_thread.php?id=5034&postid=38894

I plan on redoing my testing using a release OS version instead of Insider version, and using a release version of VirtualBox instead of a Testbuild. Perhaps I'm hitting on a beta bug.
