### ISSUE TITLE
Dark themes on Linux are broken with BOINC Manager

### ISSUE THREAD

**Issue by mmstick** [BOINC/boinc#2919]
**OS:** Pop!_OS 18.04 & 18.10 w/ Pop Dark

```
# apt-cache policy boinc-manager
boinc-manager:
  Installed: 7.12.0+dfsg-1
  Candidate: 7.12.0+dfsg-1
  Version table:
 *** 7.12.0+dfsg-1 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

This has been an issue since the original BOINC Manager client. Finally decided to check for an issue report. Surprised to find no reference to this issue here. As you can see, it would seem that BOINC Manager has some hard-coded theming, which themes everything but the text.

![screenshot from 2018-12-21 13-29-56](https://user-images.githubusercontent.com/4143535/50363253-1c1cf000-0528-11e9-825d-a7684e7df88e.png)

**Comment by AenBleidd** [comment]
Closed in favor of #3115
