### ISSUE TITLE
How can I get tasks via api?

### ISSUE THREAD

**Issue by apocello2008** [BOINC/boinc#2928]
Hello!  I want to develop boinc client based on Zephir lang. How can i get the tasks via api? (socket, HTTP, etc..)
For example, for project: Einstein@Home

Thanks for answers!

**Comment by AenBleidd** [comment]
Hello @apocello2008,
I think https://boinc.berkeley.edu/trac/wiki/GuiRpc will help you

**Comment by AenBleidd** [comment]
As soon as there is no additional questions during last 6 months I believe this could be closed.
