### ISSUE TITLE
Configuring/Moving the Data Directory from UI or Config file

### ISSUE THREAD

**Issue by SanjayArora** [BOINC/boinc#2929]
**Describe the problem**
Many people including myself are now using smaller SSDs to boot the OS & larger Hard Drives for home partitions. Usually SSDs are just enough for the OS. That is so in my case with about 15GB left over, which is absolutely required for SSD to function at optimum speeds. I moved my data directory manually under Ubuntu Bionic, redirected the symlink /var/lib/boinc to the new data directory manually. But due to some reason the boinc install does not get the data & Boinc-Manager crashes without showing an error. Boinc however, works perfectly if launched from the new home directory in terminal. Spent over an hour to find the error then gave up. 

**Describe the solution you'd like**
1. Data Directory should be GUI changeable or at least be changed in config file. I know at least one person who stopped running boinc due to same issue as mine....no space in OS SSD.
2. Boinc-Manager should not crash without showing errors.

**Additional context**

**Comment by AenBleidd** [comment]
@SanjayArora, 
please try to use next solutions:
- http://alpheratz.net/how-to-move-boinc-data-directory-linux/
- https://boinc.berkeley.edu/dev/forum_thread.php?id=8037

**Comment by AenBleidd** [comment]
Closed in favor of #4104
