### ISSUE TITLE
github link

### ISSUE THREAD

**Issue by cristipurdel** [BOINC/boinc#2937]
**Describe the problem**
Add github link in boinc directly

**Describe the solution you'd like**
Add an entry/shortcut under the "Help" option to link directly to 
https://github.com/BOINC/boinc/issues

**Additional context**
It will increase the chance of bug issues reporting here directly and not in the forums
I also did not know that boinc was on github until recently :P

**Comment by brevilo** [comment]
@cristipurdel the Android-related part of this is [done](https://github.com/BOINC/boinc/pull/2939) and the desktop Manager is close to follow suit...

**Comment by davidpanderson** [comment]
To repeat: I don't think there should be github links in either android or desktop clients.

**Comment by RichardHaselgrove** [comment]
Actioned via #2939 (Android) and #2941 (desktop). Closing.
