### ISSUE TITLE
[Android] Collapase menu button is replaced with Back button

### ISSUE THREAD

**Issue by truboxl** [BOINC/boinc#2940]
**Describe the bug**
Top left menu button is replaced with a back button that is from Event log
Is this intentional?

**Steps To Reproduce**
1. Use the beta
2. Immediately see the behaviour

**Expected behavior**
"Hamburger" or collapse menu button should be still there...

**Screenshots**
The beta 7.14
![img](https://user-images.githubusercontent.com/16503773/50486561-dc0fae80-09fa-11e9-8d20-b571ddf9de39.png)

7.4.53
![screenshot_20181228-100737](https://user-images.githubusercontent.com/12658589/50500163-60f5d900-0a8a-11e9-96a2-dc9b81a41339.png)
![screenshot_20181228-100748](https://user-images.githubusercontent.com/12658589/50500138-3e63c000-0a8a-11e9-8d8b-569fd463cee5.png)

**System Information (please complete the following information):**
 - OS: Android 8.1

**Comment by adamradocz** [comment]
I think the 'back' icon is the expected behavior, but the 'hamburger' icon.
If you think about it, you are going back from the menu, to the opened page.
