### ISSUE TITLE
Android BoincTasks continuous integration

### ISSUE THREAD

**Issue by cristipurdel** [BOINC/boinc#2942]
**Describe the problem**
Quick overview of important hardware info in notification bar, in order to support current/future BoincTasks features. This should be disabled by default, but could be enabled under advanced preferences 

**Describe the solution you'd like**
When I pull down the boinc notification, I would like to see following info:
1. CPU % = BOINC CPU %, see nativeboinc implementation under BoincTasks, this should help also with debugging https://github.com/BOINC/boinc/issues/2549 
2. Battery temp, it is already seen in event log, but not clearly visible
3. CPU temp, better to have smth similar to CPU-Z, first entry set as default. CPU monitor is not so accurate, on some devices.
4. CPU avg freq, from what I've read, google might try to limit access to hw data, but it would be nice to have, when running on octa/deca cores to see what the load level is, see also CPU monitor

**Additional context**
All the 4 setting should be written in the data folder, so BT could read them.
See implementation of nativeBOINC for CPU%

**Comment by AenBleidd** [comment]
The goal of BOINC is to run tasks when phone is not used (most common case). If you want to monitor hardware information please use appropriate software.
Regarding BoincTasks, if they want some kind of integration with BOINC software that is not provided now, it is recommended to contact via `boinc_dev(at)ssl(dot)berkeley(dot)edu` or create a corresponding ticket here on GitHub.
Closing this ticket for now
