### ISSUE TITLE
[Website] Wrong insturction on "Controlling BOINC remotely" page

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2945]
**Describe the bug**
At the bottom of the page it says the client data is stored in `/var/lib/boinc-client`, but in version 7.10.2 it has changed to client data is stored in `/var/lib/boinc`

**Steps To Reproduce**
1. Navigate to [https://boinc.berkeley.edu/wiki/Controlling_BOINC_remotely](https://boinc.berkeley.edu/wiki/Controlling_BOINC_remotely)
2. Scroll down to "BOINC data directory" section

**Comment by RichardHaselgrove** [comment]
Verified change made in 344ddabeb4e0b453ab7c3be8d5d1d5e478de2561

Amended Wiki accordingly. Can close if no objection to change.
