### ISSUE TITLE
'In use' setting does not respect inputs from Steam streaming

### ISSUE THREAD

**Issue by Holek** [BOINC/boinc#2955]
**Describe the bug**
When a computer (in this case, Windows, but I would assume it's the same for other desktop platforms) has BOINC set up to "Run based on preferences" and preferences are set to "Suspend when computer is in use", using SteamLink (either [hardware](https://store.steampowered.com/app/353380/Steam_Link/) or [Android app](https://play.google.com/store/apps/details?id=com.valvesoftware.steamlink&hl=en)) or [Steam streaming](https://store.steampowered.com/streaming/) doesn't respect inputs made via this method.

Due to that, while running Steam games BOINC decides to start its work (due to inactivity rule).

**Steps To Reproduce**
1. Set "Run based on preferences"
2. Set "Suspend when computer is in use"
3. Set 'In use' last minutes to 2.
4. Start streaming from Steam and start any game.
5. Wait 2 minutes.
6. Ran game jitters and stutters, because BOINC starts work.

**Expected behavior**
I expect BOINC to honour 'Suspend when computer is in use' setting, even if inputs are made through streaming platforms.

**System Information (please complete the following information):**
 - OS: Windows 10
 - BOINC Version: 7.14.2 (x64)

**Additional context**
Connecting via Google Remote Desktop or VNC does not produce this behaviour.

**Comment by adamradocz** [comment]
Add Steam as exclusive app.

**Comment by AenBleidd** [comment]
Client works as expected.
Feature request to support full-screen applications is described here: #2301

**Comment by Holek** [comment]
Just for other people who might stumble upon this issue, setting `C:\Program Files (x86)\Steam\bin\steam_monitor.exe` as an exclusive app in BOINC manager does the trick.

`steam_monitor.exe` handles SteamLink connections and runs only when Steam is in streaming mode.
