### ISSUE TITLE
db_dump seg faults if STATSEXPORT is not enabled

### ISSUE THREAD

**Issue by drivere** [BOINC/boinc#2958]
**Describe the bug**
db_dump crashes with a seg fault if STATSEXPORT is not enabled.  This results in stats not being exported.

**Steps To Reproduce**
With STATSEXPORT disabled, from the project bin directory, run db_dump:
./db_dump -d 4 -dump_spec ../db_dump_spec.xml

**Expected behavior**
If STATSEXPORT is disabled, I would expect db_dump to work like it used to before the latest GDPR code was added.

**System Information**
 - OS: Linux Ubuntu 4.15.0-42
 - BOINC Version: 7.15.0  (server version 1.0.0)

**Additional context**
Here is the output of db_dump if STATSEXPORT is disabled (in case its useful):
_2
     2019-01-11 10:07:35.5384  db_dump starting
     2019-01-11 10:07:35.5403  Starting
     query: SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
     query: select count(*) from user WHERE total_credit > 0 AND authenticator NOT LIKE 'deleted%'
     query: select sum(total_credit) from user WHERE total_credit > 0 AND authenticator NOT LIKE 'deleted%'
     query: select * from consent_type where shortname = 'STATSEXPORT'
     query: select * from user WHERE total_credit > 0 AND authenticator NOT LIKE 'deleted%'_

**Comment by drivere** [comment]
The seg fault is now happening again, even with STATSEXPORT enabled.  I assume there is a problem in one of my tables that surfaced again after a user enabled the stats export.

So this issue should be put on hold until I gather more information.

**Comment by drivere** [comment]
Yes, I can do that.  It will be a couple days before I find the time, but I will post back here with the info.

**Comment by ChristianBeer** [comment]
This issues was introduced with #2906 specifically commit ff91f05aa65e27ec09d029fbd1f0eeaf7e1271bb on Dec 17 2018 so they are not part of a server release. The last server release (1.0.3) was on Dec 10 2018. I'm going to create a PR as a hotfix for this issue so it can be merged into master fast.
