### ISSUE TITLE
Cloud support

### ISSUE THREAD

**Issue by cristipurdel** [BOINC/boinc#2959]
**Describe the problem**
In the cloud, hosted here or smth similar (see BoincTasks approach), should centralize all data from boinc devices for various uses:
- Device summary reports (csv format, per device columns with runtime, aborted tasks see #2957) send to email (used as username), e.g. weekly, could bypass #1699 
- Managing projects and issuing commands for all devices, similar to boincstats or BoincTasks

**Describe the solution you'd like**
similar to boincstats or BoincTasks

**Additional context**

**Comment by AenBleidd** [comment]
> Managing projects and issuing commands for all devices, similar to boincstats or BoincTasks

Already described in #1759
