### ISSUE TITLE
Fine tune task search

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2972]
The current task search option on Seti apparently only allows for the complete correct name of the task to be searched, it does not allow booleans asterisk (*) and question mark (?) anywhere in the text. Or any booleans for that matter. 

Is it possible that these are added?

**Comment by AenBleidd** [comment]
Not sure this is smth that is really needed. Closing it as 'wontfix'.
If this is smth that is still requested - please reopen this ticket.
