### ISSUE TITLE
Cross-project certificate page is broken

### ISSUE THREAD

**Issue by sergeyklay** [BOINC/boinc#2975]
**Describe the bug**
Cross-project certificate page is broken.

**Steps To Reproduce**
1. Login to BOINC
2. Open account page: https://boinc.thesonntags.com/collatz/home.php
3. Click "Certificate -> Cross-project": https://boinc.thesonntags.com/collatz/cert_all.php

**Expected behavior**
A page with valid Certificate.

**Actual behavior**
A lot of PHP warning and notices. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1256298/51585405-e92c9a00-1ee1-11e9-8859-d72cbac9e2f0.png)

---

Refs: https://github.com/BOINC/boinc/issues/2690, gridcoin-community/Gridcoin-Research#92

**Comment by jdrews417** [comment]
The API on the netsoft server is IP Address restricted (due to abuse that made it look like a ddos on the server). If your project server isn't on the list of allowed sites, you should contact James Drews.

**Comment by sergeyklay** [comment]
@jdrews417 Yes, most likely you're right. But I'm not a maintainer. I afraid I don't not know all required credentials for the https://boinc.thesonntags.com site. This just my bug report.

**Comment by sergeyklay** [comment]
The issue has been fixed by James Drews.

**Comment by ballen4705** [comment]
James wrote the following to me: "The site (RPC) got address restricted a few years ago due to abuse that made it look like a ddos attack. I've added this person's server to the allowed list."
