### ISSUE TITLE
Incorrect peak FLOPS for AMD GPU

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2988]
The OpenCL GPU detection for a particular AMD GPU reports 43 ExaFLOPS - about 10,000X too big.
(this is 7.10.2, but same in 7.14.2)

22-Dec-2018 12:28:23 [---] cc_config.xml not found - using defaults
22-Dec-2018 12:28:23 [---] Starting BOINC client version 7.10.2 for windows_x86_64
22-Dec-2018 12:28:24 [---] OpenCL: AMD/ATI GPU 0: AMD Radeon(TM) Vega 8 Graphics (driver version 2580.6 (PAL,HSAIL), device version OpenCL 2.0 AMD-APP (2580.6), 6567MB, 6567MB available, 43980464 GFLOPS peak)

**Comment by adamradocz** [comment]
Maybe driver issue? The Intel OpenCL driver shows me different result too, then the Beignet driver,

**Comment by RichardHaselgrove** [comment]
Whatever the cause, we probably need to update [lib/coproc.cpp](https://github.com/BOINC/boinc/blob/4f6e52f1cbac1e776b9ea0b6853b3e3e156a342b/lib/coproc.cpp#L840) for AMD/ATI, as we did last year for NVidia in #2707

**Comment by davidpanderson** [comment]
Addendum from user:

Update: On a hunch, I set the underclocked GPU back to auto (400-1100MHz).  The spurious peak GFLOPS issue went away. 02/02/2019 15:28:02 \|  \| OpenCL: AMD/ATI GPU 0: AMD Radeon(TM) Vega 8 Graphics (driver version 2766.5 (PAL,HSAIL), device version OpenCL 2.0 AMD-APP (2766.5), 6567MB, 6567MB available, 1127 GFLOPS peak)On underclocking it again, this time to a slightly different nominal speed, we get the old issue back:02/02/2019 15:57:59 \|  \| OpenCL: AMD/ATI GPU 0: AMD Radeon(TM) Vega 8 Graphics (driver version 2766.5 (PAL,HSAIL), device version OpenCL 2.0 AMD-APP (2766.5), 6567MB, 6567MB available, 43980464 GFLOPS peak)CPUZ seems to report the correct GPU speed in each case.

**Comment by JuhaSointusalo** [comment]
Workarounded in #3001.

**Comment by JuhaSointusalo** [comment]
Eeh, worked around...
