### ISSUE TITLE
Android: 64-bit client needed by Aug 2019

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2998]
(email from Google; I'm not sure if this applies to apps as well as the BOINC client)

Get your apps ready for the 64-bit requirement by August 1, 2019

Hello Google Play Developer, In our latest blog post, we detailed the requirement that apps using native code must provide a 64-bit version in addition to the 32-bit version by August 1, 2019. As you may know, 64-bit CPUs deliver faster, richer experiences, and we appreciate your support in ensuring our users have the best experience possible on the Android platform. Action required. If you haven't yet, we encourage you to begin work for the 64-bit requirement as soon as possible. Many apps are written entirely in non-native code (e.g. the Java programming language or Kotlin) and will not need code changes. Please note that we are not making changes to our policy on 32-bit support. Google Play will continue to deliver apps with 32-bit native code to 32-bit devices. The requirement means that those apps will need to have a 64-bit version as well. To help you make the transition, we've prepared documentation on how to check whether your app already supports 64-bit and how to become 64-bit compliant. We're also providing a high-level timeline below. Starting August 1, 2019: All new apps and app updates are required to provide 64-bit versions of any 32-bit native code they provide. Extension: Google Play will continue to accept 32-bit only updates to existing games that use Unity 5.6 or older until August 2021. Starting August 1, 2021: Google Play will stop serving apps without 64-bit versions on 64-bit capable devices, meaning they will no longer be available in the Play Store on those devices. This will include games built with Unity 5.6 or older. The requirement does not apply to: APKs or app bundles explicitly targeting Wear OS or Android TV, which are form factors that do not currently support 64-bit code. APKs or app bundles that Google Play won't install on Android 9 Pie or later (support for 64-bit does not need to extend to APKs that are only on Android 8 Oreo and below). If you have any questions, you can find additional information about adding 64-bit support here. The Google Play Team © 2019 Google LLC 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA. Email preferences: You have received this mandatory email service announcement to update you about important changes to your Google Play Developer account.

**Comment by BAAKILI1987** [comment]
what i will do to change this 32bit to 64 bit in adobe air  !! is the latest version of SDK compiler enought to resolt a problem
thanks

**Comment by AenBleidd** [comment]
According to this [article](https://developer.android.com/distribute/best-practices/develop/64-bit) we already have 64-bit application. However, even for 64-bit devices we are showing projects that support only 32-bit executables. And here could be an issue. I do not know exactly but it could happen that new devices will not run 32-bit executables at all. In this case we should remove support of 32-bit projects for 64-bit devices.

**Comment by AenBleidd** [comment]
No action is required. Until August 2021 we are completely fine. After August 2021 only 64-bit application could run on new Android phones. Until then projects should update their apps to support 64-bit. I send notification to corresponding projects.
