### ISSUE TITLE
Scheduler URL prepended by two "http://" strings

### ISSUE THREAD

**Issue by ritua2** [BOINC/boinc#3004]
Greetings,

Not sure if this is a bug or our set-up error, but the scheduler.txt file was showing two "http://" in the URL - a friendly user pointed this out:

"
```
<!-- <scheduler>http://http://boinc.tacc.utexas.edu/boincserver_cgi/cgi</scheduler> -->
<link rel="boinc_scheduler" href="http://boinc.tacc.utexas.edu/boincserver_cgi/cgi">
```
"

->

"
```
<!-- <scheduler>http://http://boinc.tacc.utexas.edu/boincserver_cgi/cgi</scheduler> -->
<link rel="boinc_scheduler" href="http://boinc.tacc.utexas.edu/boincserver_cgi/cgi">
```
"

Since we did not create this file, it must be getting created automatically during the set-up process. Is it possible that we provided a wrong input during the set-up process? Perhaps we are including "http" in the URL when it may not be required? 

Thanks,
Ritu

**Comment by JuhaSointusalo** [comment]
@ritua2

I changed to issue title to something that describes the problem you are seeing. I also had to edit the issue text so that the important part would actually show. GitHub uses Markdown which renders HTML in not always entirely obvious ways. Preview before posting :)

**Comment by davidpanderson** [comment]
I don't think this problem still exists.
