### ISSUE TITLE
db_purge should also purge the batch table

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#3005]
The db_purge command should also purge the batch table of old completed batches and batches where all the workunits have also been purged.

**Comment by davidpanderson** [comment]
state == BATCH_STATE_RETIRED would be an appropriate condition;
that means that whoever created the batch is done with it.

**Comment by lfield** [comment]
@davidpanderson I looked into the code and if I understand this correctly it is non-trivial to implement. For example a batch.enumerate function would be required in addition to functions such as archive_batch_gz. I would attempt this myself but am concerned that as I don't have the big picture of what is happening, I may make the wrong assumptions.

**Comment by davidpanderson** [comment]
Do purged batches actually need to be archived?
If not, I can supply a small PHP script to do this.

**Comment by lfield** [comment]
I don’t know. I just assumed it would follow the same approach. I personally don’t need the archives. With my current setup I have to wait until all workunits in the batch have finished (sucess, error, timeout) before I retrieve the results and retire the batch. The problem with this approach is that it creates a delay for the successful  results. As the size of the batch increases, the probability that a wu times out tends to certainty and hence all batches will take as long as  the timeout value. I am therefore considering  1 wu per batch.
