### ISSUE TITLE
Android beta version 7.14.1 “Aquire lock”issues

### ISSUE THREAD

**Issue by CarrenS** [BOINC/boinc#3008]
I’m running the beta version which has been running fine until the last day or too. I often find tasks sitting there with a “ready” status, but not crunching (battery charge is good). I have just looked at the event log and I see:

Client Messages

```
29/01/2019 8:05:09 PM|World Community Grid|<![CDATA[
Task ZIKA_000386641_x1r6r_DENV2_capsid_NMR_21_s2_0555_0 postponed for 600 seconds: Waiting to acquire lock
]]>
29/01/2019 8:04:47 PM|World Community Grid|<![CDATA[
Tasks are committed to other platforms
]]>
29/01/2019 8:04:47 PM|World Community Grid|<![CDATA[
No tasks are available for Mapping Cancer Markers
]]>
29/01/2019 8:04:47 PM|World Community Grid|<![CDATA[
No tasks are available for Microbiome Immunity Project
]]>
29/01/2019 8:04:47 PM|World Community Grid|<![CDATA[
No tasks sent
]]>
29/01/2019 8:04:47 PM|World Community Grid|<![CDATA[
Scheduler request completed: got 0 new tasks
]]>
<SNIP>

```
This is now occurring all the time. Within a few minutes of starting boinc this behaviour occurs.

**Comment by AenBleidd** [comment]
Haven't seen this issue. Might be not relevant anymore. Feel free to reopen if that's still the case in the next release.
