### ISSUE TITLE
Project Specific Test Probes

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#3009]
What I would like to do be able to do is to write a test probe that can be run to detect the sanity of the host before a task is downloaded. For example, testing that VritualBox is available. If this probe fails, no task will be downloaded. These probes would be project specific. It is to avoid situations where tasks fail due to a known and detectable issues with the host that are application specific . I would be happy to provide a PR is we can agree on the solution.

**Comment by lfield** [comment]
Is the validator run against results that returned an error?

**Comment by davidpanderson** [comment]
No; we'd have to add an option.

The other question is where to store the info.
The natural place is the host_app_version table.
This has a field max_jobs_per_day that could be used;
e.g. -1 means don't use this app version for this host.
I'd have to make some small changes for this.

**Comment by lfield** [comment]
Yes, reducing this to one per day should be fine. Related to this is that I am using the [wrapper](https://boinc.berkeley.edu/trac/wiki/WrapperApp) and my script returns [206](https://github.com/BOINC/boinc/blob/master/lib/error_numbers.h#L42) if there is a problem. However, it looks like this is not being used and the wrapper is returning 195 EXIT_CHILD_FAILED. Another feature would be to reset the max_jobs_per_day for a specific host. This means that a miss configured node could be removed for a day but if a person is trying to fix the problem they can still get new tasks when they need to test. 

So yes having something where we can parse the stderr for error messages and set the max_jobs_per_day to 1 would be sufficient.
