### ISSUE TITLE
max_wus_in_progress should scale with the number of cores. 

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#3025]
In the [documentation](https://boinc.berkeley.edu/trac/wiki/ProjectOptions) is states that max_wus_in_progress is scaled by N*NCPUS. It looks like this is physical CPUs (sockets) and it should probably be logical CPUs (cores).

**Comment by RichardHaselgrove** [comment]
I think it works that way already. I have one project (NumberFields) which is reporting 'reached a limit of tasks in progress' at 24 tasks. A second machine has 36 tasks in progress. Both are quad-core, single socket, computers, but the second has hyperthreading enabled.

At the client level, I don't think BOINC has the capability of distinguishing sockets / cores / threads: all references to nCPUs in variable names and documentation should be read as threads. BOINC code dates from before the common use of hyperthreading.

Before anyone else chimes in, another project (SETI@Home) operates a fixed limit of 100 tasks of type 'CPU', irrespective of the number of threads available. I think that's a project-level decision, and deviates from the documentation you refer to.

**Comment by lfield** [comment]
We set max_wus_in_progress = 2. On a quad or this resulted in 2 tasks running. I was expecting 4 tasks running and 4 waiting.

**Comment by UweBeckert** [comment]
In recent server software version
<max_wus_in_progress> 2 </max_wus_in_progress> in config.xml means 2 wus per thread.

      <total_limit>
        <jobs>2</jobs>
      </total_limit>
in config_aux.xml means 2 wus in total per host, independent of number of threads

**Comment by lfield** [comment]
I think that something else was causing the issue. It is clear that NCPUS is correct for the host.
