### ISSUE TITLE
The wrapper should use SIGTSTP rather than SIGSTOP

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#3026]
As far as I understand, it is [not possible](https://en.wikipedia.org/wiki/Signal_(IPC)#POSIX_signals) to [catch SIGSTOP](https://github.com/BOINC/boinc/blob/master/lib/proc_control.cpp#L250). SIGTSTP should be used instead.

**Comment by Nevecie** [comment]
SIGTSTP prevents wrapper from suspending a task on Linux. SIGSTOP should be used.
