### ISSUE TITLE
refine "don't work while computer in use"

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#303]
**Reported by davea on 4 Jul 37521381 09:46 UTC**
Work harder to be invisible to user while computer is in use:

1) don't use CPU if non-BOINC CPU usage has exceeded N% in the last M seconds
(e.g. don't compute while user is watching movie on DVD)

2) don't use network while computer is in use

Migrated-From: http://boinc.berkeley.edu/trac/ticket/311

**Comment by romw** [comment]
**Commented by mikus on 18 Aug 37521534 08:00 UTC**

If you make changes, please make sure this new "don't" behavior is __optional__.

 
To me as a user, a beneficial characteristic of BOINC's use of the CPU is that BOINC runs in the background.  When BOINC interferes with my DVD watching, I am perfectly capable of manually suspending BOINC -- I do not want BOINC to "automatically" assume what my personal priorities are.  And I do not care if on Linux my foreground's response time gets worsened by BOINC.

Likewise, let me manage how my network is used - I do not want BOINC to "automatically" assume what my personal priorities are.  [the client often has to wait for a server response, I sometimes start up non-BOINC processes which also use the network -- this way I can accomplish both activities in parallel, and can take down my network connection that much sooner.](Since)

**Comment by romw** [comment]
**Commented by Metamorf on 14 May 39270766 11:33 UTC**
I wish to add my $0.02 to this ticket...

As far as the Linux v6.4.7 is concerned, I would also like to add that 'in use' seems to be defined as keyboard activity only, not mouse.  Now, I understand this is a moot point where boinc-client is running on a server box, but is bloody annoying when both the BOINC Manager and Client are running on the same desktop box (since one can name many applications/games that have little or no use of the keyboard).

So, for the benefit of BOINC-ophiles with boincmgr and boinc-client running on the same desktop PC, 'in use' should mean keyboard ''or mouse'' activity.

**Comment by lfield** [comment]
I don't think that there is an issue here. In use is defined as keyboard/mouse activity and BOINC should suspend if the CPU goes over a set valid.

**Comment by RichardHaselgrove** [comment]
This is one of a whole class of issues originating with #41. BOINC's behaviour was - and still is - basically fixed in the era when computers had a single compute resource - a single CPU (except for the rare moneybags who could afford a Pentium D). People are already starting to discuss the Intel Intel Xeon W-3175X with 28 cores, 56 threads - and that's before we get on to GPUs.

I don't disagree with closing this particular iteration as a duplicate, but please don't lose sight of the underlying issue - we need to be smarter in our available options for (not) in use.

**Comment by lfield** [comment]
I don't think there is any difference today. There are two states. 

1. Is  a person sitting in front of the computer?
1. Is there spare capacity available?

For the first keyboard/mouse activity is the indicator. The exception being watching video. For the second it is CPU/GPU usage. Cores just add an extra parameter to the equation.

**Comment by RichardHaselgrove** [comment]
I disagree. I don't think it should be BOINC's role to decide what "in use" means for any particular user.

Apart from the two cases you cite, a graphic designer (video game author?) might wise to use the full rendering capability of their GPU while working, but might not need to stop BOINC on all CPUs. Other professionals might need heavy-duty CPU support, but be prepared to surrender the tiny factional CPU support that a well-written GPU app consumes. Unless someone can prove me wrong, I don't think the latter case can be accomplished by any of the current settings.

**Comment by lfield** [comment]
So this is a different issue. In both cases the computer is `in use`. What is being defined is a resource sharing policy and yes this can be more complex.  I think that both examples can be met with the options:

> Suspend GPU computing when computer is in use
> Use at most x % of CPU time

In any case this is a policy definition issue and specific examples should be given.
