### ISSUE TITLE
How does my boinc client connect to Science united?

### ISSUE THREAD

**Issue by jacobbogers** [BOINC/boinc#3030]
This template is for miscellaneous issues not covered by the other issue categories.
How does my boinc client connect to Science united
Nowhere do i see a IP or port or any protocol to request projects to calculate on,
I am trying to understand line wire protocol

**Comment by davidpanderson** [comment]
The account manager protocol (used for BAM!, Science United, etc.) is described here:
https://boinc.berkeley.edu/trac/wiki/AccountManagement

Please post questions to boinc_dev rather than as issues.

**Comment by jacobbogers** [comment]
Thanks David, will query boinc_dev)

**Comment by jacobbogers** [comment]
Thanks davi, will do)
