### ISSUE TITLE
Incorrect language (Korean) when Android is Lithuanian

### ISSUE THREAD

**Issue by Knysliux001** [BOINC/boinc#3035]
**Describe the bug**
Android application from the Google Appstore switches to Korean language if Android language is set to Lithuanian. As a result it is nearly impossible to use.

**Steps To Reproduce**
1. Set Android language to Lithuanian
2. Open BOINC

**Expected behavior**
Application should be Lithuanian if it has been translated and English as a fallback.

**System Information (please complete the following information):**
 - OS: Android 8.1.0
 - BOINC Version: Android 7.4.53

**Comment by AenBleidd** [comment]
@Knysliux001, could you please switch to Play Store Beta testing and install newest version of BOINC for Android (7.14) and check one more time?

**Comment by Knysliux001** [comment]
Installed beta version 7.14.1 (ec993779be), some texts are in Lithuanian now, the rest of application seems to be covered in Korean symbols.

**Comment by ChristianBeer** [comment]
It seems to me that the Lithuanian translatian contains partly the wrong language. I don't know how this happened. The best way would be if you would help translating into Lithuanian here: https://www.transifex.com/boinc/boinc/translate/#lt/android/40475947 you can also invite friends to help you. You only need to translate the strings they don't need to be reviewed. The translations you do on transifex will most likely be incorporated into the next Beta version. Please also take a look at the other parts of BOINC.

**Comment by Rytiss** [comment]
The translation in Transifex looks good. I just translated two missing Android strings.

**Comment by AenBleidd** [comment]
Fixed by bf9b095bbbf91bf583530a5e6452b9e1f44fd36b
