### ISSUE TITLE
BOINC Client doesn't detect computer is idle with serial ports connected

### ISSUE THREAD

**Issue by cminnoy** [BOINC/boinc#3036]
**Describe the bug**
BOINC client doesn't detect that the Linux machine is idle after apt dist-upgrade.
The client detected the idle situation BEFORE the dist-upgrade. It can't do it anymore and will not start tasks therefor.

**Steps To Reproduce**
1. Install valilla Ubuntu MATE 18.04 LTS
2. apt-get dist-upgrade

**Expected behavior**
The client should detect that the computer is not used and start to run tasks. 

**Screenshots**

**System Information (please complete the following information):**
 - OS: Linux Ubuntu MATE 18.04.02 LTS
 - BOINC Version: 7.9.3 x86_64 pc-linux-gnu

**Additional context**

**Comment by cminnoy** [comment]
More info:
I have two machines, one Ryzen based and one Threadripper based. Both have the same Ubuntu MATE version with the same BOINC version and all the latest updates.
On the Threadripper BOINC detects correctly that the machine is idle or not.
On the Ryzen BOINC always thinks the machine is busy.

I downloaded the source code of BOINC client (master) and compiled it. Changed the main function into this:

int main(int argc, char** argv) {
        std::cout << "STARTED" << std::endl;
        HOST_INFO info;
        for (int i = 0; i < 100; ++i) {
                std::cout << info.users_idle(false, 1.0) << ' ';
                if (i % 6) std::cout << std::endl;
                sleep(10);
        }
return 0;
}

On the Threadripper this code will start putting out '1's after one minute. But after that it keep on transmitting '1's even when the computer was not idle anymore.
On the Ryzen this code will never output '1's.

So, what's going on?

**Comment by cminnoy** [comment]
Ok, I've been further investigating what is going on and discovered why BOINC doesn't detect the idle of the Ryzen. This has nothing to do with being Ryzen or Threadripper, but with the following.

On the Ryzen machine there is a Arduino plugged into USB. This is seen as a tty device.
Also, there is a daemon running that reads from the Arduino data to do temperature logging.
As soon as that daemon does NOT open the serial port, BOINC starts detecting idle periods.

TO CONCLUDE: Boinc has an issue with serial ports; when data is received from a serial port, Boinc will not detect anymore that the computer is idle.

What does the community think of this?

**Comment by cminnoy** [comment]
File where the tty activity is checked: hostinfo_unix.cpp
Relevant data/functions:
- tty_patterns is a list/pattern of devices boinc will monitor
- vector<string> get_tty_list()  -> filters the devices based on tty_patterns
- all_tty_idle -> takes a stat of each filtered device

So the culprit is here that BOINC doesn't distinguish between the kind of devices.

On Linux/Unix it is indeed difficult to discriminate between 'real' serial devices and interactive ones, like mouse keyboard.

Proposal:
We should be able to set in cc_config.xml to ignore certain devices for checking the idle state.

**Comment by davidpanderson** [comment]
I added this feature in #3044

**Comment by cminnoy** [comment]
Hi David,

How should the pattern be formed in cc_config.xml?

I tried (intuitively):

<ignore_tty>ttyUSB0</ignore_tty>
<ignore_tty>ttyUSB1</ignore_tty>

and as that didn't work after reading your commit:

<ignore_tty>/dev/ttyUSB0</ignore_tty>
<ignore_tty>/dev/ttyUSB1</ignore_tty>

Looking at the code the pattern is compare to 'fullname', so I guess the seconds form would be correct? Unfortunately in both cases it didn't detect the exclusion pattern.

**Comment by davidpanderson** [comment]
It's the latter syntax.  I tested it and it seems to work.

**Comment by ChristianBeer** [comment]
Please note that the comparison used is case sensitive.

**Comment by cminnoy** [comment]
David, Christian,

Case sensitivity is not the issue in this case. That was set correct in the cc_config.xml file.
The vector tty_list is a static and is only filed during start of BOINC. As such any tty device plugged in after BOINC started is not detected. That's not ok.

Another issue is that the kernel decides which name to give to the device. It is possible to add a udev rule to have a link created in /dev, but BOINC does not understand links. What is needed is to have BOINC check that the tty device you exclude is a link, it should also exclude the file(s) linked at.

Again another issue, but maybe not directly related to the above is that when you run two instances of BOINC on one machine, often only ONE instance sees activity on a tty device and stops running, while the second happily keeps on going. As soon as you stop one BOINC instance, the other starts behaving ok. So there is some interaction between the two BOINC instances. I couldn't pinpoint the exact cause yet (maybe stat or atime), but you can see it also happening if you interact over ssh with the computer.

And lastly, also worthy of its own ticket, BOINC doesn't detect mouse actions or window activity (at least not under Ubuntu MATE 18) if you enter via xrdp, vnc or using nomachine. Only if you open a local terminal under those conditions it (sometimes) sees there was some activity on the machine. Opening, closing or moving windows is/are completely ignored by the boinc client(s).
