### ISSUE TITLE
Need GPU Sample Application

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#3046]
The uppercase sample application allows for easy testing and confirmation of the setup of a BOINC project.  However, there is no equivalent version of the uppercase application that could run on Intel/NVIDIA/ATI GPUs.  It would make it easier to test these things if we had access to such a sample application on GPUs.  

This issue represents a request to create a version of the app that would run as GPU apps on the different platforms for the purpose of testing system behavior.

Question:  Is there any reason that we couldn't simply load the cpu versions as GPU versions and run those?  Would that execute the GPU related code pathways on the client and server?  What would be missed if we weren't actually running a GPU app?

**Comment by davidpanderson** [comment]
If you give any app a GPU plan class, all the GPU-related BOINC code will be exercised.

**Comment by TheAspens** [comment]
Ok - I'll work with that then.  Tx.

**Comment by AenBleidd** [comment]
@TheAspens, can this ticket be closed?

**Comment by adamradocz** [comment]
@TheAspens Does it mean, we can expect a GPU-based project on WCG soon? :)

**Comment by TheAspens** [comment]
I wish - our next project was written actually written in Fortran (ack!)  See https://www.worldcommunitygrid.org/forums/wcg/viewthread_thread,41609 

I actually needed it for testing a pull request a month or two ago which is why I opened the issue.
