### ISSUE TITLE
Science United API

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3048]
Some sort of Science United equivalent to the [BOINC API](https://boinc.berkeley.edu/trac/wiki/WebRpc#am_get_info) would be great.

**Comment by ChristianBeer** [comment]
Science United is a special account manager not a project. So it does not need to implement the BOINC project API. Also SU is not part of BOINC but is managed here: https://github.com/davidpanderson/science_united

**Comment by davidpanderson** [comment]
I moved this to the SU repo:
https://github.com/davidpanderson/science_united/issues/14
