### ISSUE TITLE
BSOD crash report (BOINC on Windows 7) 

### ISSUE THREAD

**Issue by yingang** [BOINC/boinc#3059]
When the BSoD happened, I was doing some GPU based (CUDA) processing and BOINC is running in the background (also using GPU through Einstein@Home) .

**System Information (please complete the following information):**
 - OS: Window Embeded System 7
 - BOINC Version: 7.14.2
 - GPU: NVidia GTX 1070 (driver version: 397.64)

**Additional context**
from the windbg output with the [dump file](https://github.com/BOINC/boinc/files/2969232/031419-25396-01.zip), it looks like similar with the problem mentioned in #2056.

>BugCheck F4, {3, fffffa80828dcb10, fffffa80828dcdf0, fffff80001fda8c0}
Probably caused by : wininit.exe
Followup: MachineOwner

>CRITICAL_OBJECT_TERMINATION (f4)
A process or thread crucial to system operation has unexpectedly exited or been
terminated.
Several processes and threads are necessary for the operation of the
system; when they are terminated (for any reason), the system can no
longer function.
Arguments:
Arg1: 0000000000000003, Process
Arg2: fffffa80828dcb10, Terminating object
Arg3: fffffa80828dcdf0, Process image file name
Arg4: fffff80001fda8c0, Explanatory message (ascii)

>Debugging Details:
PROCESS_OBJECT: fffffa80828dcb10
DEBUG_FLR_IMAGE_TIMESTAMP:  0
MODULE_NAME: wininit
FAULTING_MODULE: 0000000000000000 
PROCESS_NAME:  boinc.exe
BUGCHECK_STR:  0xF4_boinc.exe
CUSTOMER_CRASH_COUNT:  1
DEFAULT_BUCKET_ID:  VISTA_DRIVER_FAULT
CURRENT_IRQL:  0
LAST_CONTROL_TRANSFER:  from fffff80002064892 to fffff80001ccf440
STACK_TEXT:  
fffff880`378469d8 fffff800`02064892 : 00000000`000000f4 00000000`00000003 fffffa80`828dcb10 fffffa80`828dcdf0 : nt!KeBugCheckEx
fffff880`378469e0 fffff800`020220db : 00000000`00000001 fffffa81`148ae060 fffffa80`828dcb10 00000000`00000001 : nt!PspCatchCriticalBreak+0x92
fffff880`37846a20 fffff800`01f8b144 : 00000000`00000001 00000000`00000370 fffffa80`828dcb10 fffff800`00000008 : nt! ?? ::NNGAKEGL::`string'+0x27256
fffff880`37846a70 fffff800`01cce6d3 : 00000000`00000370 fffffa81`148ae060 fffffa80`828dcb10 00000000`000003f8 : nt!NtTerminateProcess+0x284
fffff880`37846ae0 00000000`7735bffa : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x13
00000000`0030c568 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x7735bffa
STACK_COMMAND:  kb
FOLLOWUP_NAME:  MachineOwner
IMAGE_NAME:  wininit.exe
FAILURE_BUCKET_ID:  X64_0xF4_boinc.exe_IMAGE_wininit.exe
BUCKET_ID:  X64_0xF4_boinc.exe_IMAGE_wininit.exe
Followup: MachineOwner

**Comment by AenBleidd** [comment]
Not enough info to reproduce. Anyway, this is 4 years old issue, and Win& is no longer supported by Microsoft.
Closing this issue.
