### ISSUE TITLE
Using Help menu items opens two browser windows

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#307]
**Reported by tiker on 19 Jun 37529763 04:00 UTC**
When using any of the links in the help menu that open the web browser, two windows are opened.  One window opens the correct website as it should.  The second window goes to an invalid page and shows the url "http://%1/".  Noticed this with 5.10.13 client.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/324

**Comment by romw** [comment]
**Commented by KSMarksPsych on 17 Jul 37532080 11:06 UTC**
What browser and OS?

I only get a single IE window on Vista (too bad it should be opening Firefox).

**Comment by romw** [comment]
**Commented by tiker on 12 Jul 37532404 19:06 UTC**
Replying to [KSMarksPsych](comment:1):
> What browser and OS?
> 
> I only get a single IE window on Vista (too bad it should be opening Firefox).

Windows XP, SP2.  I use Portable Firefox normally but the client launches IE6.

Just to add a little more confusion, if there is already an existing IE window open then it opens a second window fine to the website without opening a third window with %1 in the URL.  The 2nd window with the invalid URL only occurs when there are no IE windows open when clicking a link from the boinc help menu.

**Comment by romw** [comment]
**Commented by Ageless on 18 Jun 38355845 19:06 UTC**
Same happens in 5.10 versions. New reports coming in about this in [BOINC Dev](http://boinc.berkeley.edu/dev/forum_thread.php?id=2680#17256).

**Comment by romw** [comment]
**Commented by romw on 7 May 39425714 10:40 UTC**
For some reason we are receiving multiple help menu item events.

This bug effects people who have the "Open new browser window" option selected in "Internet Options" advanced settings.  It isn't the default option for this specific setting, at least through Windows Vista.

Punting to 6.10

**Comment by Ageless93** [comment]
Since there's been no further reports of this for years, I am closing this issue.
