### ISSUE TITLE
db_dump creates badge_user.gz.gz and badge_team.gz.gz

### ISSUE THREAD

**Issue by gchilders** [BOINC/boinc#3074]
db_dump creates badge_user.gz.gz and badge_team.gz.gz with two .gz extensions.

**Steps To Reproduce**
1.  With badges enabled, run db_dump and view the stats files.

Then extension is added both when the filename is specified and when the file is opened by the GZIP_FILE class.  The fix is to remove the extension in the former case.  I have fixed it in my local fork below:
https://github.com/gchilders/boinc/commit/958db30e1d3e3aeddba8a6d347037684004302d8

**Comment by AenBleidd** [comment]
Fixed in #3084
