### ISSUE TITLE
"Computing" notification after crash, but no computation done

### ISSUE THREAD

**Issue by arkadiyjs** [BOINC/boinc#3098]
**Describe the bug**
The app seems to download and compute tasks after the initial setup sequence but proceeds to crash the device at some point over the next 24 hours of operation. After powering up the device, a "Computing" notification is displayed without any actual computation done within the app. In addition, the device isn't even supposed to work on the tasks in accordance with the set preferences.

**Steps To Reproduce**
1. Download the APK from the [BOINC website](https://boinc.berkeley.edu/download_all.php).
2. Modify the APK by following [this guide](https://steemit.com/gridcoin/@atlantictech/mining-gridcoin-with-your-phone-complete-guide).
3. Wait for the device to crash over the next 24 hours.

**Expected behavior**
Computation in accordance with the default preferences.

**System Information (please complete the following information):**
 - OS: Android
 - BOINC Version: 7.4.53

**Additional context**
I believe step 2 to have no effect on the issue.

**Comment by AenBleidd** [comment]
@arkadiyjs, please take a look at the issues #2771 and #2467 
By the way, there is newer version in Beta channel on Google Play.
I don;t believe it will fix your issue but at least you could try

**Comment by arkadiyjs** [comment]
Installed the newer version via APKMirror and turned off battery optimization for the app. The "Computing" notification error seems to be solved, but the device continues to crash overnight. At this point, I'm unsure whether it's an issue with BOINC or the device itself.

**Comment by AenBleidd** [comment]
@arkadiyjs, could you please provide any logs if available?

**Comment by arkadiyjs** [comment]
The issue has somehow solved itself. I now use this device solely for BOINC. All other applications were deleted and the device has stopped crashing overnight.
