### ISSUE TITLE
Limited team types

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#310]
**Reported by Didactylos on 5 Jan 37531830 20:00 UTC**
The current team types are
- Unclassified
- Company
- Primary school
- Secondary school
- Junior college
- University or department
- Government agency

This doesn't begin to cover the actual team types, which is presumably why this feature is mostly ignored. Also, the educational types seem overrepresented and are US-centric. Here are some addition team genres observed in the wild:
- religious groups
- non-profits
- national teams
- local, geographic teams
- teams centring around anything from sexual orientation to CPU preference
- teams centring around an existing community, website or webcomic
- personal teams

Migrated-From: http://boinc.berkeley.edu/trac/ticket/327

**Comment by romw** [comment]
**Commented by Ageless on 24 Jul 37882278 12:53 UTC**
Reassigning to David.

**Comment by lfield** [comment]
Standard enumeration problem. More complicated than it sounds as they are defined in multiple places and translated.

**Comment by winkies** [comment]
It seems like almost all team types was added by @davidpanderson  in 2007 :  [19267f0](https://github.com/BOINC/boinc/commit/19267f06e1fa3b890c28a19af5a621bb2eba506b#diff-6eee815f3ebf4dc8bb74e8f9fdb67520977929ab1c14ee10e6e999d717013cc4).

@ChristianBeer @AenBleidd  IMO, this issue and the trac ticket can be closed except if there is a need by the community.

**Comment by AenBleidd** [comment]
Since this is a static list of team types and there is no plans to make it dynamic, I'm closing this issue as 'wontfix'.
New team types could be added by request (there was no any request last 15 years IIRC).
