### ISSUE TITLE
How do install the Boinc server?

### ISSUE THREAD

**Issue by songminkyu** [BOINC/boinc#3103]
There is no manual on how to build and install the Boinc server,
Can I get advice on how to build and install it?

**Comment by AenBleidd** [comment]
Hello @songminkyu,
Please take a look at next links:

- https://boinc.berkeley.edu/trac/wiki/ProjectMain
- https://boinc.berkeley.edu/trac/wiki/ServerIntro
- https://github.com/marius311/boinc-server-docker/blob/master/docs/cookbook.md
