### ISSUE TITLE
How do I forward announcements without RSS?

### ISSUE THREAD

**Issue by songminkyu** [BOINC/boinc#3108]
Is there any way to forward notices to the Boinc Client Manager without an RSS feed on the Boinc Web server?

**Comment by davidpanderson** [comment]
Post news items and check the "show as notice in the BOINC Manager" checkbox.
They're distributed via the notices.php RPC.

**Comment by AenBleidd** [comment]
I believe the answer is informative enough so this ticket could be closed.
