### ISSUE TITLE
Vagrant isn't working

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3113]
**Describe the bug**
I get this error message when I tried to use the Vagrant to create a VM:
` default: [=======================================] 100% Unzipping... m2repository/com/goo
    default: cp: cannot stat '/home/vagrant/.local/share/applications/android-studio.desktop': No such file or directory    default: chmod: cannot access '/home/vagrant/Desktop/android-studio.desktop': No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

**Steps To Reproduce**
1.  Download the Vagrant file from the repo
2.  Install Vagrant
3.  `vagrant up`

**Expected behavior**
Run the script without error message.

**System Information (please complete the following information):**
 - OS: Windows 10

**Comment by AenBleidd** [comment]
@adamradocz, the error you mentioned is a result of the issue that appear earlier.
I believe it is fixed now, please verify
