### ISSUE TITLE
[Android] Add possibility to cancel 'Add Project' procedure

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#3136]
Currently there is no way to cancel 'Add Project' procedure if you accidentally pressed the corresponding button of just found no suitable projects to add.
If is very useful to have 'Cancel' button on 'Add Project' screen.

**Comment by adamradocz** [comment]
Android's default back button can do that.

**Comment by AenBleidd** [comment]
Yes, but in case of first start clicking 'Back' button will just close the application. I believe, in this case application just should return to the main screen

**Comment by adamradocz** [comment]
True.
