### ISSUE TITLE
Treat missing network as a temporary error.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#314]
**Reported by Didactylos on 28 May 37531885 07:33 UTC**

> If you put your laptop on stand by with Windows XP and you put him on again it takes some time to type your password and the wireless connection takes some time to connect to the internet. If boinc doesn't find immediately an internet connection you get a message that boinc can't connect to the internet and you have too click yourselve on the button 'reconnnect to the internet'.
> 
> First it would be easier on a laptop with wireless internet that boinc has a longer time out before giving that message and the other thing is that you shouldn't need to get that pop-up ok button that you have to reconnect. It should automagically reconnect to the internet when you're wireless is working again. It should only give that error if you are not connected to the internet for a long time.

(Suggested by s060319)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/331

**Comment by romw** [comment]
**Commented by Nicolas on 7 May 37532366 00:53 UTC**
It should only give that "warning" if a network connection is really '''required''' and not just when it wants to do any network activity. For example, sending a file for a workunit that just finished, but has '''two weeks left''' for the deadline is definitely not a "required network connection".

**Comment by ChristianBeer** [comment]
If this is still happening with a recent version of BOINC please open a new issue.
