### ISSUE TITLE
The 'Help' link on the Computing preferences window in the BOINC client opens a page on the website with no text

### ISSUE THREAD

**Issue by abowery** [BOINC/boinc#3157]
**Describe the bug**
The 'Help' link on the Computing preferences window in the BOINC client opens a page on the website with no text

**Steps To Reproduce**
1. Open the BOINC Client (I am using the Linux version)
2. Click on 'Options' -> 'Computing preferences..'
3. Click on the 'Help' button.

**Expected behavior**
Expect to be forwarded to a relevant page on the website. Instead a page on the website with no text is shown:
https://boinc.berkeley.edu/wiki/Local_preferences#Advanced_view
Which has a link in it to:
https://boinc.berkeley.edu/wiki/ManagerComputingPrefs
This has no text in it.

**System Information (please complete the following information):**
 - OS: Linux Ubuntu
 - BOINC Version: 7.6.31

**Comment by RichardHaselgrove** [comment]
My browser displays the following text from the Wiki log:

> ManagerComputingPrefs
> This page has been deleted. The deletion and move log for the page are provided below for reference.
> 
> 00:13, 14 February 2017 Admin (Talk | contribs) moved page ManagerComputingPrefs to Editing computing preferences with the BOINC Manager without leaving a redirect.

On the same day, most of the narrative text was removed, leaving the skeletal 'help' page as basically a series of images of the page that the user was seeking help on.

**Comment by AenBleidd** [comment]
Redirect should be fixed on help page.
@davidpanderson, could you please handle this?

**Comment by davidpanderson** [comment]
fixed

**Comment by AenBleidd** [comment]
@davidpanderson 
Maybe it's better to redirect directly to 
https://boinc.berkeley.edu/w/?title=Editing_computing_preferences_with_the_BOINC_Manager&redirect=no
rather than 
https://boinc.berkeley.edu/w/?title=ManagerComputingPrefs&redirect=no#Advanced_view
?
