### ISSUE TITLE
Confidence limits on times

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#316]
**Reported by Didactylos on 27 Jan 37531904 10:40 UTC**
BOINC's time prediction (through no fault of its own) is notoriously inaccurate. However, BOINC already tracks a lot of information about time. Would it be possible to keep enough historical information about each project to be able to give an indication of the precision that the estimate has?

Then, time to completion can be shown as (e.g.) 9 hours  3 hours.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/333

**Comment by romw** [comment]
**Commented by Didactylos on 1 Nov 37532252 16:53 UTC**
Obviously, this is supposed to be an enhancement. Doh.

**Comment by Ageless93** [comment]
BOINC 7 learns about tasks run time and will adjust the time to run after having calculated 10 or more tasks of the same length without errors.
