### ISSUE TITLE
setiathome_8.00_arm-android-linux-gnu__armv6-neon has text relocations

### ISSUE THREAD

**Issue by tlgalenson** [BOINC/boinc#3164]
Error messages:
<code><core_client_version>7.4.39</core_client_version>
<![CDATA[
<stderr_txt>
emory and prevents security hardening. Please fix.
WARNING: linker: setiathome_8.00_arm-android-linux-gnu__armv6-neon has text relocations. This is wasting memory and prevents security hardening. Please fix.
Unable to resolve function unwind_backtrace_signal_arch
Unable to resolve function acquire_my_map_info_list
Unable to resolve function release_my_map_info_list
Unable to resolve function get_backtrace_symbols
Unable to resolve function free_backtrace_symbols
Unable to resolve function format_backtrace_line
Unable to resolve function load_symbol_table
Unable to resolve function free_symbol_table
Unable to resolve function find_symbol
one or more symbols not found. stackdumps unavailable
SIGSEGV: segmentation violation

Exiting...</code>

**Comment by RichardHaselgrove** [comment]
You are running a very old version of BOINC for Android. The first thing to check is whether this is a BOINC (platform) problem, or a SETI (application) problem.

If you look at https://github.com/BOINC/boinc/issues/2927#issuecomment-494809707, you'll see how to get the current test builds of BOINC, produced weekly: if you could switch to one of these, it would help to localize the problem.

**Comment by AenBleidd** [comment]
@tlgalenson, could you please also provide some information about the device you're facing this issue on?
And rather than installing weekly unsigned build please switch to Beta channel on Play Store: https://support.google.com/googleplay/answer/7003180?hl=en-GB and install latest public version.

**Comment by tlgalenson** [comment]
I am running a screen damaged Samsung using an app called "HTC the power to give" which was all that I could find to run Android/Boinc/Seti at the time.  Because of said screen I haven't been able to reach the URL listed above.  Sorry.
