### ISSUE TITLE
BOINC notification area icon is corrupted

### ISSUE THREAD

**Issue by skelband** [BOINC/boinc#3170]
When starting boinc manager on Linux Mint 18.3, 19.0 or 19.1 with MATE desktop manager the notification icon is corrupted.

**Steps To Reproduce**
1.  Open boinc-manager
2.  Enable notification area icon
 
**Expected behavior**
The icon should fit the notification area space.
Instead, the icon seems to be tiled within the area.
Screen capture included

**System Information (please complete the following information):**
 - OS: Linux Mint 18.3, 19.0 and 19.1. Lenovo W530 laptop with NVIDIA Optimus graphics.
 - BOINC Manager Version: 7.9.3 (wxWidgets: 3.0.4)

![notification](https://user-images.githubusercontent.com/8182540/58738663-95641d00-83bb-11e9-9202-ad49e362145a.png)

**Comment by AenBleidd** [comment]
@skelband, 7.9.3 is a very old version, the latest one is 7.14.2. Could you please update ( https://launchpad.net/ubuntu/+source/boinc ) and verify whether this issue still reproducible for you?

**Comment by RichardHaselgrove** [comment]
@AenBleidd - refer to #3052 before spending any time on this one.

**Comment by skelband** [comment]
Will do and thanks. Might be a little while as I;m just going on holiday but I will check!

**Comment by AenBleidd** [comment]
Tray icon is removed in #3052. Closing this as 'Wontfix'
