### ISSUE TITLE
Android version parsing

### ISSUE THREAD

**Issue by JamesMolson** [BOINC/boinc#3172]
https://github.com/BOINC/boinc/blob/master/sched/plan_class_spec.cpp#L63-L79

The above code looks for:
(Android x.y.z
or
(Android x.y

but not
(Android x

My phone reports itself as (Android 9), so the function just returns 0.
Something like
```
n = sscanf(p, "%d", &maj);
if (n == 1) {
return maj*10000;
}
```
should be added before the return 0;

**Comment by AenBleidd** [comment]
@JamesMolson, is it possible for you to provide a patch for this? It would be very great. If not - please let me know, I could find some time to spend fixing this issue.

**Comment by TheAspens** [comment]
Details about how to make a contribution are available at: https://github.com/BOINC/boinc-policy#development-processes

**Comment by nilsjh** [comment]
Thanks to @JamesMolson for spotting this!  This affects the server code and scheduler, so we should add a label for the scheduler. @lfield Please review.

**Comment by nilsjh** [comment]
Also 8.x Android versions are affected and the server does not correctly reject .Android 8.1.0 clients even if the max client version is set to 79999.

  <name>aarch64-android-linux-gnu</name>
  <min_android_version>40100</min_android_version>
  <max_android_version>79999</max_android_version>

**Comment by AenBleidd** [comment]
Removing label `C: Android - Manager` because it is not related to the Manager component of Android client.

**Comment by lfield** [comment]
> Also 8.x Android versions are affected and the server does not correctly reject .Android 8.1.0 clients even if the max client version is set to 79999.
> 
> aarch64-android-linux-gnu
> <min_android_version>40100</min_android_version>
> <max_android_version>79999</max_android_version>

This issue was due to a plan class miss-configuration, not an issue with the code.
