### ISSUE TITLE
Add ability to restart unmanageable VM jobs.

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3173]
**Describe the problem**
When the VM has not enough memory to run, the BOINC will stop it, but not restarting it for a very long time, or until I restart the BOINC.

**Describe the solution you'd like**
I want a button, which restarts the VM job, so when I manually release some memory, it can run as soon as possible.

**Comment by AenBleidd** [comment]
So you're talking about manual queue management that is not implemented in client and I'm not sure it should be.
@davidpanderson, @TheAspens, what do you think?

**Comment by davidpanderson** [comment]
The goal is for the client to do the "right thing" automatically.
What is the right thing in this case?
I don't understand the scenario.

**Comment by adamradocz** [comment]
How long the does it take the client to restart an unmanageable VM job, if there's enough memory again?
When I release enough memory for the VM job, I want to run it as soon as possible. My current scenario looks like this:

- VM job stops because there's not enough memory.
- I finish the memory intensive task.
- I close and restart the boinc to reinitialize the state and run the VM job again.

**Comment by davidpanderson** [comment]
BTW, the BOINC client doesn't monitor the memory usage of non-BOINC processes.  I can't see why running a memory-intensive job would affect BOINC's job scheduling.  What does the event log say at the point where the VM job is stopped?

**Comment by adamradocz** [comment]
```
6/9/2019 8:22:45 AM | Charity Engine | Temporarily failed download of jf_041ab594f2e1f5457e8ffa849caef322: can't resolve hostname
6/9/2019 8:22:45 AM | Charity Engine | Backing off 05:56:34 on download of jf_041ab594f2e1f5457e8ffa849caef322
6/9/2019 8:22:46 AM |  | Project communication failed: attempting access to reference site
6/9/2019 8:22:47 AM |  | Internet access OK - project servers may be temporarily down.
6/9/2019 8:25:13 AM |  | Suspending computation - an exclusive app is running
6/9/2019 8:25:13 AM |  | Suspending network activity - an exclusive app is running
6/9/2019 8:29:25 AM | Charity Engine | Task df360259727a1b0aa36fc11e296560cf_6353368_34_185 postponed for 86400 seconds: VM job unmanageable, restarting later.
6/9/2019 9:23:02 AM |  | Resuming computation
6/9/2019 9:23:11 AM |  | Resuming network activity
6/9/2019 9:23:11 AM | Charity Engine | Started download of jf_aa9aae680fbfd5fc49b588fe1de93abd
6/9/2019 9:23:11 AM | Charity Engine | Started download of jf_8c35ae38ef368cbae683c10809255802
6/9/2019 9:23:15 AM | Charity Engine | Sending scheduler request: Requested by project.
```

When I restarted the BOINC, it was computing again.

**Comment by davidpanderson** [comment]
The "VM job unmanageable" means that a vboxwrapper attempt to suspend, resume, or make a snapshot of the VM failed.  In this case vboxwrapper does a "temporary exit" with a delay of 1 day.  This delay is not recorded in the state file, so if the client is restarted the job will run again.
Notes:
- 1 day seems excessive
- the message generated by vboxwrapper is inadequate - it doesn't say what failed.
- what version of vboxwrapper does Charity Engine use?  the COM or Vboxmanage version?

**Comment by adamradocz** [comment]
`vboxwrapper_2018061901_windows_x86_64` and `vboxwrapper_2019052102_windows_x86_64` can be found in the BOINC folder.

**Comment by davidpanderson** [comment]
Those are probably the COM version.
In any case, I'll change vboxwrapper to print better error messages,
and to restart in 5 minutes instead of 1 day.

**Comment by adamradocz** [comment]
Thanks.

**Comment by hucker75** [comment]
Sorry to reopen this, but it's still a problem.  It's certainly not retrying every 5 minutes.  And this line indicates it's still set to 1 day:
Task camb_boinc2docker_2471226_1671884768.683208_0 postponed for 86400 seconds: VM job unmanageable, restarting later.

**Comment by AenBleidd** [comment]
Is this the first retry that failed? Could you please check the full log, not the last line only?

**Comment by hucker75** [comment]
As Richard Haselgrove pointed out to me in [3181](https://github.com/BOINC/boinc/pull/3181), it may be Cosmology is using outdated wrapper.  I mistakenly thought the wrapper was part of the client end on my PC.

It fails very often with over 50% of the tasks.  Might be the VB version annoying it.  I remember 6 was unworkable, so I went back to 5.  I've just changed to 7, which seems to work sometimes.

There's nothing else in the log.  Do you want me to switch on some of the debug options?

**Comment by AenBleidd** [comment]
Ok, I'll check then what is the version of wrapper this project uses.
Thank you for the report.
