### ISSUE TITLE
[Web] Sandbox implementation HTTP ERROR 500

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3177]
**Describe the bug**
The[ Sandbox implementation](https://boinc.berkeley.edu/sandbox_design.php) page gives HTTP ERROR 500. The page can be seen at https://boinc.berkeley.edu/trac/wiki/SoftwareDevelopment#Client:packaging

**Comment by davidpanderson** [comment]
Thanks; fixed.
