### ISSUE TITLE
[Web] Development Workflow shows error 404

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3178]
**Describe the bug**
The https://github.com/BOINC/boinc-policy/blob/master/Governance_Documents/Governance.md#41-technical-contributions page shows a link to [Development Workflow](https://github.com/BOINC/boinc-policy/blob/master/Governance_Documents/Development_Workflow.md), which shows error 404.

**Comment by TheAspens** [comment]
fixed
