### ISSUE TITLE
VirtualBox Jobs crashing if Hyper-V was installed

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3184]
**Describe the bug**
I use VirtualBox to run VM jobs and everything was working fine. I had to install Hyper-V to do some job, then I uninstalled it. After the uninstall the VM jobs are crashing.

**Steps To Reproduce**
1. Install VirtualBox and run a Job.
2. Install Hyper-V.
3. Remove Hyper-V.
4. Run VirtualBox jobs again.

**System Information (please complete the following information):**
 - OS: Win 10
 - BOINC Version: 7.14.2

**Additional context**
The log shows: `Vbox app stderr indicates CPU VM extensions disabled`, but it's enabled.

**Comment by AenBleidd** [comment]
@adamradocz,
Just curious, did you restart your machine after Hyper-V uninstalled? Could you please also check that Hyper-V was successfully uninstalled? Could you also please run VirtualBox Manager and run some machine (non-boinc) manually> Does it run or crash with error? Thanks

**Comment by adamradocz** [comment]
Yes, I restarted the PC, even reinstalled the virtual box. Hyper-v successfully uninstalled.
I'll try to run other vm tomorrow.

**Comment by adamradocz** [comment]
Other VM's are working.

**Comment by AenBleidd** [comment]
@adamradocz, could you please attach /Logs/VBox.log file from any of the VM task? Actually BOINC itself doesn't verify whether CPU VM extensions enabled or not (I'm not even sure whether it could be done on user level (not driver level like it done in VIrtualBox), it just reads the log generated by VirtualBox for a particular VM and parses these data to find some error markers.

**Comment by adamradocz** [comment]
Where can I find the `VBox.log`?

**Comment by AenBleidd** [comment]
@adamradocz, sorry I had your question completely lost.
I have no running VM tasks right now but I suppose this log should be in slot directory.

**Comment by adamradocz** [comment]
Nothing.

**Comment by truboxl** [comment]
Is this still a problem? It's unlikely now since VirtualBox must have CPU VM extension enabled to install since 6.0 and can use WHPX if Hyper-V is enabled. Talking from a theoretical standpoint...

**Comment by AenBleidd** [comment]
Yes, it's still an issue: I have Hyper-V configured and can't run any VirtualBox instance (maybe it should be configured in a very specific way but default installation doesn't work)

**Comment by ivictbor** [comment]
Not sure related or not, but seems like after WSL2 installation which runs in hyper+V I have crashes of Vitualbox window which runs VM from time to time. Plus it is still much slower then it was before WSL2. I am using VBox 6.1.18

**Comment by AenBleidd** [comment]
@ivictbor, it's a known incompatibility between VirtualBox and Hyper-V: https://superuser.com/a/1208857

**Comment by AenBleidd** [comment]
This is a known problem (also without BOINC) with incompatibility between VBox and Hyper-V on Windows, and there is no known good solution for that.
I saw suggestions to switch in VBox to use Hyper-V driver internally, but this is also not working in most of the cases.
I'm closing this ticket since I see nothing we can do here.
