### ISSUE TITLE
Alternative CPU settings

### ISSUE THREAD

**Issue by Siltaar** [BOINC/boinc#3186]
During the day, I use my machine and need to spare some CPU speed for my usage.
But at night, I can fully load the CPU.

**I would like to be able to switch between two CPU setting profiles automatically**, based on the time of day : few CPU for BOINC during office hours and full access at night.

***

Why would it be needed while BOINC is running with a massive nice setting under GNU+Linux ? It's **because my CPU works at variable speeds** :
- If only one core is running alone it can reach 3GHz (for a short period of time)
- but if my two cores are running at full speed they are stuck at ~1GHz each, and I feel the difference when my tasks are running ~3 time slower.

But I noticed that running both cores + HyperThreading produces more computation for BOINC than one core alone at full speed (mainly because the 3GHz spikes don't last long).

***
Such a feature is available in Transmission BitTorrent client, and I miss it in BOINC :-)
In Transmission, we have, moreover, a turtle icon shown in the status bar (at the bottom of the window) which allows to easily switch between the two setting profiles, overriding the schedule when needed.

**Comment by RichardHaselgrove** [comment]
See #41 - this is probably the most frequently requested update to the BOINC ecosystem.

**Comment by davidpanderson** [comment]
See also #2993

**Comment by bazarassa** [comment]
I guess, i can ask you here, can you combine CPU preferences with CPU temperature sensors?

Yes, I know that I can do it with a simple bash script, but might be a killer feature for me, if BOINC will stop his calculations for some time after CPU package reaches temperature in settings.

**Comment by AenBleidd** [comment]
There are already tickets for this: #1378 and #1379

**Comment by AenBleidd** [comment]
Recently was added two sets of preferences: when device is in use and when it's not is use.
I assume this is a better solution that the one suggested in this ticket.
Closing it as 'wontfix'
