### ISSUE TITLE
Move installer from InstallShield to NSIS

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#3194]
Currently BOINC uses InstallShield to create a installer. It is not free and rather expensive.
I suggest to move away from it and use NSIS instead ( https://nsis.sourceforge.io/Main_Page ).
It is free and easy to use.
I played a little bit with it and found it very easy. I can create test installer next week or so. 
If we consider to use it we should also rewrite boinccas dll that is built with VS2010 now and I found no way to build it with newer versions of VS because of OLE dll usage that is used to communicate with InstallShield installer. So we will need either to rewrite this library on NSIS script language or just clean up existing library from all InstalShield references.
Also moving to NSIS will give us an opportunity to extend existing functionality of installer that is requested by users.
Any thoughts?
I'd like to discuss this on the upcoming Contributions call 6/27/19.

**Comment by adamradocz** [comment]
@AenBleidd, do you have a WIP version?

**Comment by AenBleidd** [comment]
Yes

**Comment by adamradocz** [comment]
Upload it please, if I have time, I'll try to contribute or at least give my 2 cents. :)

**Comment by AenBleidd** [comment]
Ok, I need to polish it then because currently it's not ready to be shown to anyone😜

**Comment by AenBleidd** [comment]
NSIS might not be the best choice for BOINC.
It's required to do a comparison of available toolsets to choose one that will fir BOINC the best.
Closing this in favor of #5065
