### ISSUE TITLE
divide client state file

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#321]
**Reported by davea on 24 Jul 37532808 05:46 UTC**
Currently there's a single client state file.
If one item in it changes (e.g. a task's checkpoint CPU time)
the entire file is rewritten - could be several MB.

Might be better to divide the state file into a large part
that seldom changes, and a small part that changes often.
The small part would have to include:
- active task info (e.g. checkpoint CPU time)
- project debt info
- other stuff??

Migrated-From: http://boinc.berkeley.edu/trac/ticket/338

**Comment by romw** [comment]
**Commented by MikeMarsUK on 25 Mar 37534107 22:40 UTC**

Perhaps it could be split by project (and also by volatile / static as suggested)?  (would have the advantage that corruption would only affect one project).

Sounds like a good idea, but one possible issue - Can the user still downgrade back to 5.x from 6.x without losing their current workunits?  (for example, if the new version they're running turns out to be unstable).

Perhaps a little app in 6.0 which recreates a 5.x style client_state.xml at intervals?  (Whenever boinc starts up and also each hour of running?)

Alternatively, perhaps the code which reads the new format could be backported to 5.x, so the most recent version of 5.x could take either format as input.

**Comment by romw** [comment]
**Commented by Nicolas on 27 Mar 37535123 21:46 UTC**
What about using [SQLite](http://www.sqlite.org/) for the client state? (Please don't throw heavy objects at me).

**Comment by lfield** [comment]
Why is this an issue?

**Comment by RichardHaselgrove** [comment]
Hard drive speed and reliability may have been an issue 11 years ago, when this ticket was opened.

Some progress was made in this direction with the introduction of boinc_task_state.xml files in af93af28f79283541541f67103f54a86a4b082cc.

**Comment by lfield** [comment]
Let's close it then as it is so old and nothing has been done. If there is a problem, a new issue can be created with more up-to-date description again the latest code.
