### ISSUE TITLE
[Website] Update GuiRpcProtocol's wiki

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3212]
[https://boinc.berkeley.edu/trac/wiki/GuiRpcProtocol#get_file_transfers](https://boinc.berkeley.edu/trac/wiki/GuiRpcProtocol#get_file_transfers) doesn't contain the `hostname` tag.

**Comment by Rytiss** [comment]
Can you be more specific, maybe post how the entire section should look like, and I'll put it into the documentation?

**Comment by davidpanderson** [comment]
What hostname?  Each <file_xfer> element includes the URL.
