### ISSUE TITLE
Finish migration to python3

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#3241]
Pull Request #2477 modified the scripts necessary so that creating and updating a project worked with python3 instead of python2.  I believe the following additional python scripts need to be updated to finish the migration to python3:

- ./stripchart/samples/parse_config
- ./tools/parse_config
- ./tools/dbcheck_files_exist
- ./tools/check_project
- ./tools/appmgr
- ./sched/start

**Comment by davidpanderson** [comment]
Fixed in #4043, which works with both 2 and 3
