### ISSUE TITLE
GDPR: option of 'User data is anonymized' doesn't work

### ISSUE THREAD

**Issue by abowery** [BOINC/boinc#3271]
This is in BOINC server code 1.0.3, if this has been fixed in 1.0.4 please close this bug.

I have implemented the GDPR changes described in 'https://boinc.berkeley.edu/trac/wiki/GdprCompliance' on our dev site: https://dev.cpdn.org

In the 'Data Deletion' section a number of options for the value of <enable_delete_account/> are given. On our dev site I have set this to option '1 = User data is anonymized'. In this case the entry for the user should be kept in the database. On our dev site I have tested and it actually deletes the whole user entry rather than just anonymizes it.

**Comment by AenBleidd** [comment]
@abowery, did you read https://boinc.berkeley.edu/trac/wiki/RightToErasure ?
I'm not sure but I believe it could answer your question

**Comment by abowery** [comment]
Hi @AenBleidd 
No I am afraid this is a reproducible bug rather than a question.

**Comment by AenBleidd** [comment]
No problem. I'm not familiar with this functionality, just try to help you.
Did you also read the discussion here: #2447 ?
@TheAspens, could you please take a look at this? As far as I remember, you're the most experienced in this functionality, and you run some tests on it.

**Comment by abowery** [comment]
Update on this:
Apologies, I think this item is a mistake. I don't think this is actually an issue and that it is actually doing what is described in:
https://boinc.berkeley.edu/trac/wiki/GdprCompliance

**Comment by TheAspens** [comment]
Thanks for the update. Let us know if further testing indicates that there is an issue.  I was hoping to get to this this coming weekend.

If further testing reveals that it is working correctly, then please go ahead and close this ticket.

Thanks!
