### ISSUE TITLE
Tasks halted seconds prior to their end in favour of other projects

### ISSUE THREAD

**Issue by smoe** [BOINC/boinc#3286]
The subject line says it. Thinking this further, could we have an option that prevents tasks to ever be interrupted, like tasks being "atomic" in their execution? This would free memory and reduce the average turnaround-time for WUs.

**Comment by Rytiss** [comment]
Some applications are deterministic, but some apps can spend hours in a 99.99% state. Implementing your proposal has been previously been determined to potentially cause deadline troubles on other tasks.

**Comment by smoe** [comment]
Hm. Right. Could this be a (user-controllable?) property of the project/application, then? I am particularly interested in short-run GPU applications.

**Comment by Rytiss** [comment]
Applications already have a flag "fraction_done_exact" which tells the client its completion percentage is deterministic, so maybe this could be based on that.

**Comment by AenBleidd** [comment]
@smoe, the main question is next: why should you ever worry about this?
BOINC build to work in next way:
- you add projects
- you let it run.
That's all. Adding this complexity could be not necessary: if the task is completed in time, why you need to care if there are few seconds left and scheduler paused this task in favor of another?

**Comment by smoe** [comment]
I just asked myself why I worry about all this. An incomplete answer is:

- Motivation to reduce turn-around time for project maintainers - would actually be interesting to have a "run instantly and don't be interupted" kind of WU type - be it for graviational waves to be detected more quickly to allow follow-up observations or something we have not thought about, yet.
- Avoid low-memory situtation (I have enough on my machines, but others may not)
- Uncertainty about how long my local machine may still be running BOINC - what is finished should be finished and hopefully soon sent off. What is almost finish should be allowed to finish before the day ends.
- My checkpointing intervals are typically at 10 or 12 minutes, so the short GPU tasks don't checkpoint at all. But that also means that I lose some 5-6 minutes on average when the end of the day comes per WU - and there are many WUs. And with jobs halted at an unfinished stage this doubles or triples.
- When running on a machine with many GPUs, there is a task finishing about every or two minutes. No need to perform any fancy scheduling at all. My proposal means to reduce complexity and is not adding to it.
- Trust. BOINC doesn't just run. There are people behind it. And they want to their BOINC scheduler to behave just like they themselves would treat their pet WUs.

**Comment by Rytiss** [comment]
* Projects needing fast turnaround have a mechanism for that - they set short deadlines.
* If you worry about your host disappearing - don't keep a big cache.
* BOINC does not preempt tasks if they don't checkpoint; task switching happens after checkpoint. This also handles low memory situation - BOINC unloads the app, but it has checkpointed already.

Your last point says it all - people do want to micromanage things. And yet it still works if they don't :)

I'm inclined to close this as "won't fix". @AenBleidd?

**Comment by RichardHaselgrove** [comment]
Adding one more bullet point to @smoe's last post. The GPU apps he's thinking about are never kept in memory when suspended, so they take significantly longer (in comparative terms) to re-load and re-start if ever suspended.

But @Rytiss's point that they won't be suspended through task switching without checkpointing first is also true and relevant.

**Comment by smoe** [comment]
>     * Projects needing fast turnaround have a mechanism for that - they set short deadlines.
That has a very different semantics from this "[don't disturb my circles](https://en.wikipedia.org/wiki/Noli_turbare_circulos_meos!)" request.
>     * If you worry about your host disappearing - don't keep a big cache.
I don't. Never do. On no machine. Hey, I am doing this for a while.
>     * BOINC does not preempt tasks if they don't checkpoint; task switching happens after checkpoint. This also handles low memory situation - BOINC unloads the app, but it has checkpointed already.

**Ha, this was a good hint.** So you are saying I should have a second look at the checkpointing intervals. If that happend just before the end of my task because I am bad a comparing seconds with minutes or the task is longer than the others, then this may be an explanation for seeing a preemtive task switch just before the task naturally ended.

> Your last point says it all - people do want to micromanage things. And yet it still works if they don't :)
Yes? And BOINC please respects that.

> I'm inclined to close this as "won't fix". @AenBleidd?
I was inclined not to submit my request kind of anticipating a "won't fix". Please give this some extra spin for a few days. I think this would be a mistake. Thank you for the moviation to revisit the checkpointing invervals.

**Comment by smoe** [comment]
I came to the conclusion that the observed nuissance was indeed caused from badly chosen checkpoint intervals. Still, for the other reasons pointed out, I am convinved that this would help BOINC to evolve. Feel free to close.
