### ISSUE TITLE
[Android] Profiles to change settings depending on phone condition.

### ISSUE THREAD

**Issue by CmdrModder** [BOINC/boinc#3288]
A feature that I believe would benefit the Android app would be dynamically changing the settings based on the conditions the phone is in, such as whether it's running on battery power, or plugged in. Granting finer control to the end user would benefit them by allowing them to make a profile to reduce the amount of computing resources dedicated to BIONIC when running on battery power, and reduce it further when the battery reaches certain thresholds (Eg, reduce computing from 4 cores to 2 when 50% battery is reached). This feature would probably fall under advanced preferences, but I do believe that it's worth developing for the volunteers.

**Comment by TheAspens** [comment]
@davidpanderson is working on a change to the underlying way that preferences and settings are managed that will allow for significantly greater ability to express preferences.  See https://boinc.berkeley.edu/trac/wiki/Prefs2 and #2993 

You should compare your desired use case against the capability that will enable and let David know if you see a gap in what you are asking for and what the new prefs will allow.

**Comment by CmdrModder** [comment]
This is actually an excellent plan on the capabilities I had in mind, and it looks like it could even be extended for use on the PC Bionic manager it self.
The only nitpick I see is potentially having some difficulty of having a condition override any other condition that may be true (EG, always turn off bionic at 25% battery, regardless of any other condition that may be met), but other than that, i'm certain that david has this task in the bag.
