### ISSUE TITLE
Disable CPU tasks

### ISSUE THREAD

**Issue by domisse** [BOINC/boinc#3291]
I would like to disable CPU tasks during the day as the PC is really noisy
even if only one CPU task is running.

I was expecting setting  'max_ncpus_pct' to 0% in global_prefs_override.xml would
suspend all CPU tasks but in fact, it allows ALL cpu tasks to run (as value set to 100%)

The only way to stop CPU tasks is to untick 'CPU' in the web interface profile...but then there
is no more way to run CPU tasks during the night.

I've tried to rename the CPU app but boinc discard all CPU tasks when I put back the binary on restart.

So I would be pleased to see a 'disable CPU' option like we already have 'disable GPU' in boincmgr.

**Comment by domisse** [comment]
Someone send me the trick.
In your app_config.xml, set the number of graphic card you want to use :
<project_max_concurrent>1</project_max_concurrent> for 1 GPU
and boinc will use the GPU(s) and stop CPU tasks.

**Comment by RichardHaselgrove** [comment]
Yes - there are multiple ways to work round special cases, but those fixes are no substitute for a thorough design specification which allows flexible configuration of the diverse range of modern hardware.

For other readers, possibly perplexed by this issue: it follows a parallel discussion on the SETI@Home message boards, where the specific case is explored in more detail.
