### ISSUE TITLE
I want to run BOINC in Linux Mint v19.2

### ISSUE THREAD

**Issue by George396** [BOINC/boinc#3294]
Will there ever be a BOINC client or BOINC Manager for Linux Mint v19.2 Cinnamon?

**Comment by adamradocz** [comment]
Use this repository: `ppa:costamagnagianfranco/boinc`

The exact command:
```
add-apt-repository -y ppa:costamagnagianfranco/boinc && \
apt-get update && apt-get install -y  boinc
```

https://www.pcworld.com/article/2942171/how-to-use-ppas-to-install-bleeding-edge-software-in-ubuntu-and-linux-mint.html

**Comment by smoe** [comment]
Hi @George396, were you successful? I admit that the exact paths for package migrations beyond Ubuntu are a bit beyond me. Please speak out if you encountered any issues with that PPA by @LocutusOfBorg.

**Comment by George396** [comment]
Hi Steffen, Yes & No, I was successful in downloading and installing Ubuntu onto my aged ASUS Sabertooth X58 w/an SSD, but it wasn’t successful in operating for more than 15 minutes without crashing.  Bottom line I think my motherboard is failing.  It’s only 10+ years old.  ;*)

**Comment by CharlieFenton** [comment]
@George396: FWIW, crashes of BOINC are often due to overheating. You could try reducing the CPU and / or GPU loads via the Computing Preferences.

**Comment by George396** [comment]
Hi Charlie,

I realize that, but FWIW, I’m running Hardware Monitor from CPUID and it’s showing 39-43 C with 86% CPU utilization when I run Windows 10.  I can’t believe it’s running much different when I run Linux, if anything it’s running cooler.

**Comment by adamradocz** [comment]
Then it's a possible hardware failure.
