### ISSUE TITLE
[Web] ATI brand is used in System requirements page

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3304]
The ATI brand should be renamed to AMD in the https://boinc.berkeley.edu/wiki/System_requirements page.

**Comment by davidpanderson** [comment]
Essentially everything on that page and the related page
https://boinc.berkeley.edu/wiki/List_of_projects_by_system_requirements
is outdated by a decade or two.
Maybe we should not link to them.

**Comment by AenBleidd** [comment]
Looks like this has been changed a log ago
