### ISSUE TITLE
Value Converson warnings

### ISSUE THREAD

**Issue by ShanghaiTimes** [BOINC/boinc#3317]
In the Mac build, there is a file particularly, named parse.h that is throwing a lot of Value Conversion issues. Like this.

eg
/Users/robert/Documents/GitHub/ShanghaiTimes/boinc/lib/parse.h:322:13: Implicit conversion loses integer precision: 'long' to 'int'

As this is referring to 32 bit code - int - should it be chased down and converted to 64 bit code, ie int_fast64_t instead of int.  

Not that easy of course because in one case where x = y it's referring an int to a double.

It's not stopping the build. Is it worth chasing down.

**Comment by RichardHaselgrove** [comment]
My two cents on this comes up with two answers.

On one hand, this was probably coded in older, more parsimonious, times - when memory was rare and expensive. It was probably a valuable optimisation at the time, and provided the values in question never outgrow either limit, the warnings are harmless and can be ignored.

But on the other hand, we have already seen cases where poor variable type choices caused significant problems. Some years ago, the SETI@Home project had to be shut down for rebuilding when first Task, and then Workunit, ID numbers outgrew the chosen database storage. And just a couple of months ago, we had a case where a misplaced comma allowed a 10-digit number to be written to a variable which should only have accepted the two boolean values - true or false.

I cringe whenever I see absurd choices for value storage and expression - like speeds calculated to a millionth of a flop/sec (or one floating point operation per 11.5 days). The advice on these boards has usually been to disregard - even to disable - compiler warnings, but I think that's shortsighted. It would be better to use programming standards (or even a programming language) which prevented us from putting our collective feet in our mouths.

But that's for another day.

**Comment by AenBleidd** [comment]
There is no reason to keep tickets to track build warnings. Closing this as 'wontfix'
