### ISSUE TITLE
change checkpoint timing mechanism

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#332]
**Reported by davea on 9 Feb 37549995 04:26 UTC**
Old: checkpoint timing is driven by a timer in the runtime library.  Checkpoint times of different jobs are out of phase.

New: have the core client send a message saying it's time to checkpoint;  do this synchronously between jobs

Migrated-From: http://boinc.berkeley.edu/trac/ticket/349

**Comment by romw** [comment]
**Commented by Nicolas on 29 Sep 37590158 18:40 UTC**
See also #348.

**Comment by ChristianBeer** [comment]
This is 10 years old if it is still a problem please open a new issue.
