### ISSUE TITLE
[Android] 7.16.3, Another volunteer app is already running on this device

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#3334]
I can only start BOINC once on my Huawei P20 lite (Android 9) and look at it, all other times thereafter, whether I try to recall it from memory or start by its icon, I immediately get a popup that another volunteer app is already running on this device and that only one at a time can run. I have to force close BOINC and restart it for it to work as normal for a bit, before the pop up returns.

**Comment by AenBleidd** [comment]
I believe the real issue is that boinc client crashed, And this is just an aftermath of it.

**Comment by Ageless93** [comment]
Normally when the client crashes I can no longer look at the tasks or the
event log. I can still see those in this occasion.

**Comment by ipa-kamp** [comment]
I have had the same situation on my Samsung Galaxy S8 also running Android 9, the only way is to force stop the app to be able to re launch.

**Comment by cristipurdel** [comment]
Same here with Android 9 LG V30

**Comment by kingcharles1666** [comment]
Mine has the same issue and the app appears to work partially after acknowledging the error message. I can change preferences for example. However no tasks are running, they stay at 0% forever.
Samsung S9 (SM-G960F) with A10 at patch level June 2020
