### ISSUE TITLE
Advanced Preferences Dialog is confusing and inconsistent

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#334]
**Reported by charlief on 9 Apr 37552512 04:26 UTC**
I think there are some problems with the Advanced Preferences. 
1. There is currently no way to know whether you are overriding global preferences except by looking in the BOINC Data directory to see if the `global_prefs_override.xml` file exists.
2. If I change a setting in the Advanced Preferences which does not appear in the Simple GUI Preferences (such as "use at most 16 processors"), and later look at the Simple GUI preferences, the "Customize" checkbox is set.  If I then clear the "customize" check box in the Simple GUI Preferences, this does not necessarily revert all settings to the web-based values, even though on subsequent checks the "customize" checkbox is off.
3. When I press the Clear button, it sets the "Do work while computer is in use" check box, even though my web-based preferences have this option set to No. 

If I then clear the checkbox, it writes a `global_prefs_override.xml` file. This means that if I change my global preferences on the web, those changes will be ignored.

I believe several changes are needed:

 a. Instead of a "Clear" button, the Advanced Preferences dialog should have a "customize" or "override" checkbox like the one in the Simple GUI preferences. 
 a. When the "customize" checkbox is off in the Advanced Preferences, the web-based global preference values should be displayed.  Turning this checkbox off should revert the display to the web-based preferences.
 a. I'm not sure what should be done about problem (2).  One option might be to disable the Simple GUI "customize" checkbox if items are customized in the Advanced Preferences which aren't accessible from the Simple Preferences, and to display a line explaining that you must use the Advanced Preferences to change it.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/351

**Comment by romw** [comment]
**Commented by Nicolas on 12 Sep 37552601 05:20 UTC**
(changed description to use [real lists](WikiFormatting#Lists) and fixed some typos)

**Comment by romw** [comment]
**Commented by Nicolas on 20 Nov 37552610 16:53 UTC**
Maybe we could make checkboxes be in the "undefined state" (see [Tri-state check box](WikiPedia:Checkbox#Tri-state_check_box)) to mean "not customized; use web-based preferences".

Just an idea.

**Comment by ChristianBeer** [comment]
The preference dialog was overhauled in the meantime and AFAIK all listed things are fixed.
