### ISSUE TITLE
BOINC can't connect to client after upgrade to WSL2

### ISSUE THREAD

**Issue by sibebleuze** [BOINC/boinc#3348]
I recently started using Windows Subsystem for Linux (WSL) since I'm trying to learn working with the linux/bash command line before actually going for a full Linux installation. I had BOINC running long before that, and this isn't what started the problem. What did start the problem is when I upgraded to WSL2 (via these steps: https://docs.microsoft.com/en-us/windows/wsl/wsl2-install).

I got into the Windows Insider program via my university account (apparently this is a no go on a personal account) and installed the necessary updates for WSL2. This required a restart of my laptop, as usual with Windows updates, and so after all was done I had to restart BOINC as well.

This is where things got weird. Instead of just going back to work, the manager did start but didn't load my projects. I noticed it didn't even manage to connect to the localhost client. After a bit of messing aroung online looking for solutions, I decided to take a look at the task manager to see if everything was in fact running. That where I noticed the WSL running as a subprocess to BOINC (see first screenshot below). When I killed this subprocess with the task manager, BOINC started behaving normally again, as if nothing ever happened (second screenshot).

![screenshot 1](https://user-images.githubusercontent.com/19614268/67346609-9733a600-f53f-11e9-969c-329a42cba087.png)
![screenshot 2](https://user-images.githubusercontent.com/19614268/67346610-9733a600-f53f-11e9-9b5d-7890b045fe4d.png)

**System Information**
 - OS: Windows 10 build 19002.1002
 - BOINC Version: 7.14.2

Unfortunately this fix didn't last, since when I restart BOINC I have to kill the WSL subprocess again with the task manager, so that is something I think you should get rid off. If this isn't due to something BOINC did, but rather has to do with something Windows is doing, please do report it to them, as you know more about how this works then I do. Also sorry if this has been reported already, I thought I didn't find it in the other issues, but maybe I didn't look hard enough (it's late and all).

**Comment by AenBleidd** [comment]
I'll take a look

**Comment by AenBleidd** [comment]
Was not able to reproduce this on Windows 10 x64 19018.1
![image](https://user-images.githubusercontent.com/3234209/68952020-6f8ed100-07bf-11ea-8789-dd7d571ef243.png)
@sibebleuze, could you please re-verify this on newest insiders build?

**Comment by sibebleuze** [comment]
It's gone now (I'm in Windows 10 x64 19013.1122 right now), thanks for looking into it.
