### ISSUE TITLE
BOINC can be linked to a blockchain to reward the participants.

### ISSUE THREAD

**Issue by aakashsinghbais** [BOINC/boinc#3350]
BOINC can be linked to a blockchain with some cryptocurrency token with which the participants can be rewarded. 
The blockchain may be powered by contributions by the projects being benefited.
This can potentially draw in a huge participation.

**Comment by AenBleidd** [comment]
Please take a look at the https://www.grcpool.com/ project

**Comment by aakashsinghbais** [comment]
Thanks
