### ISSUE TITLE
Within a few hours, BOINC fills RAM/swap with any project active

### ISSUE THREAD

**Issue by mielouk** [BOINC/boinc#3352]
**Describe the bug**

Since a few weeks any active project fills the RAM and swap space within a few hours (5 - 15h?). At first I thought it was only LHC, but after I disabled it the problem still persisted. After disabling any project, one by one, the problem still persisted with any single project active. 
As the RAM usage approaches 100% my computer becomes sluggish and unresponsive. Sometimes, after I've been gone for a few days, I can't even SSH into it. It also happens when I'm using the computer, not only when idle.
Stopping the boinc-client with systemd drops the RAM by a little but stays way high. I've 16GB of RAM and 17GB of swap space. Only after disabling boinc-client and a reboot this problem does not occur any more.

**Steps To Reproduce**
I can't say that there was any special event that might have triggered this. It hasn't been going on since the last update in June.

Settings in the BOINC manager:

- If computer in use 25% RAM
- If computer not in use 66% RAM
- swap max 75%

**Expected behavior**

The RAM shouldn't be filled within hours, so the computer is not reachable any more. So it may run unattended for weeks/months.

**Screenshots**

**System Information**
 - OS: Arch
 - BOINC Version: 7.14.2, last updated on June 24th from 7.12 

**Additional context**

I'm heating my room with my computer. Winter is coming...
Had to restart once to finish this report.

**Comment by mielouk** [comment]
May I provide more information? Is there a way to debug this?

**Comment by davidpanderson** [comment]
Task Manager shows you how much memory each process is using.
What processes are using lots of memory in this case?

**Comment by mielouk** [comment]
![Bildschirmfoto vom 2019-10-30 15-41-46](https://user-images.githubusercontent.com/3057062/67868289-0efb6500-fb2c-11e9-9c0c-40a875bd8a89.png)

![Bildschirmfoto vom 2019-10-30 15-42-23](https://user-images.githubusercontent.com/3057062/67868320-19b5fa00-fb2c-11e9-94b6-0181d9d75026.png)

![Bildschirmfoto vom 2019-10-30 15-42-47](https://user-images.githubusercontent.com/3057062/67868361-29354300-fb2c-11e9-9705-9f1d241d2b78.png)

The first one shows the boinc related usage. The second one shows the biggest RAM users from the rest of the system. The last one is the overall usage on my machine. When I stop the boinc-client.service the RAM stays full.
Somehow the numbers don't add up. These numbers were verified with htop.

**Comment by mielouk** [comment]
![Bildschirmfoto vom 2019-10-31 09-34-22](https://user-images.githubusercontent.com/3057062/67931323-dad28380-fbc1-11e9-9c1e-c8dd99e8d047.png)
![Bildschirmfoto vom 2019-10-31 09-35-25](https://user-images.githubusercontent.com/3057062/67931333-e32abe80-fbc1-11e9-930d-6a88912000c4.png)

As far as I can see, it still doesn't add up.

**Comment by AenBleidd** [comment]
As far as I can see from the top output, active BOINC tasks don't use significant amount of your RAM.
The possible explanation of the picture you see is [here](https://serverfault.com/a/9450)
But this doesn't answer your concern about whole system slow-down.
I'm not an expert linux user but if there is a real memory issue, then there should be intensive page swapping that means there should be huge disk load. In order to verify this please wait until high memory usage and system slow-down happens again then run next command:
`sudo iotop -o`
It should show you all processes and threads that currently uses your hard-drive.
Om my test test machine this utility was not installed by default, so you should first install it. I suppose, you're experiences enough to do it by yourself, if not, please run one of these commands (I don't know what exactly Arch linux uses):
`sudo apt install iotop`
or
`sudo yum install iotop`

**Comment by mielouk** [comment]
I'm aware that Linux uses most of its RAM to cache recent used data. This is reflected in htop via different colouring 

![Bildschirmfoto vom 2019-10-31 11-45-15](https://user-images.githubusercontent.com/3057062/67940471-052d3c80-fbd4-11e9-93f7-588627b43d4d.png)

where 
    Green: Used memory pages
    Blue: Buffer pages
    Orange: Cache pages

https://serverfault.com/questions/180711/what-exactly-do-the-colors-in-htop-status-bars-mean

The problem that I've at the moment is, that this fillup of the green part only happens when the boinc-client is active. I've disabled the client on startup for a few days, so I know for sure that no other program is causing this. As you can see in your requested top output that there are also no other programs that can account for this massive RAM usage.

I've installed iotop on my Arch machine with `sudo pacman -S  iotop`  and will use it shortly.

**Comment by mielouk** [comment]
![Bildschirmfoto vom 2019-10-31 12-13-00](https://user-images.githubusercontent.com/3057062/67942460-242dcd80-fbd8-11e9-9c6a-f081ecec0641.png)
![Bildschirmfoto vom 2019-10-31 12-13-39](https://user-images.githubusercontent.com/3057062/67942521-4d4e5e00-fbd8-11e9-9843-e8cd4bf5c2a5.png)

When the RAM was full I started another Firefox instance. Now the system is very sluggish and video playback became stuttery, as is typing this sentence.

**Comment by mielouk** [comment]
This problem vanished within a few days after I posted the last comment. I've the strong suspicion that some malicious entity intervened with the unencrypted traffic, generated by projects attached to BOINC that don't use transport encryption. I'll close this issue and open a feature request to make all traffic generated via the BOINC-client encrypted.

**Comment by AenBleidd** [comment]
There are two already exist:
#1692
#1345

**Comment by mielouk** [comment]
Yes, I just found them and won't open another one.
