### ISSUE TITLE
User web: remove HTML anchor from page title

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#3358]
**Describe the bug**
As title, on the Team message board page

**Screenshots**
![Team message board](https://user-images.githubusercontent.com/14886436/67851265-01c98080-fb02-11e9-84cd-e31e5bb7f215.png)

**System Information**
 - OS: Windows
 - Browser: Chrome

**Comment by davidpanderson** [comment]
fixed in #3361
