### ISSUE TITLE
Preventing orphaned hosts derailing the CPID

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#336]
**Reported by Didactylos on 9 Dec 37559340 13:20 UTC**
It's a surprisingly common situation: an existing cruncher decides to add a new project, and adds several new hosts dedicated to this new project. Of course, the CPID will only update for the new project if he attaches a host to one of his original projects.

But if he leaves any of his hosts orphaned, then every time they contact the scheduler, they reset the CPID to the old value. The CPID will cycle endlessly, giving unpredictable results in the exported stats.

I think that once a project has the oldest CPID, it should '''keep''' that CPID, ignoring later ones and sending the oldest CPID to those hosts that have a later CPID.

This will require a few changes: a CPID timestamp field in the database, which must be passed in the scheduler request and response, so that the server can compare the age of the provided CPID against the age of the stored CPID.

Components: Scheduler, Database, Daemon.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/353

**Comment by ChristianBeer** [comment]
I believe this was implemented without a DB field but some other means to decide on the age of host-CPID.
