### ISSUE TITLE
Client: make event log messages consistent

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#3360]
Another one arising from a confused user. I personally always set <sched_op_debug> for the event log, so I always see

`30/10/2019 12:05:24 | SETI@home | Project requested delay of 303 seconds`

and I assumed all users saw it, because there's no debug signifier in the message. But https://github.com/BOINC/boinc/blob/master/client/cs_scheduler.cpp#L665 confirms it's restricted to <sched_op_debug>.

All users do see
```
30/10/2019 12:06:01 | SETI@home | update requested by user
30/10/2019 12:06:04 | SETI@home | Sending scheduler request: Requested by user.
30/10/2019 12:06:04 | SETI@home | Requesting new tasks for NVIDIA GPU
30/10/2019 12:06:06 | SETI@home | Scheduler request completed: got 0 new tasks
30/10/2019 12:06:06 | SETI@home | Not sending work - last request too recent: 42 sec
```
Without seeing the scheduler delay request, the last line is meaningless - there is no way of knowing how much of the requested delay remains.

<sched_op_debug> does have a debug version of the delay request:
`30/10/2019 12:05:24 | SETI@home | [sched_op] Deferring communication for 00:05:03`
I'd prefer that all users are shown the first version. alongside the 'too recent' message.

Also acknowledging the backlog issue #1452

**Comment by Rytiss** [comment]
Note that we have now two commits that deal with this issue: @delta1513 changes the data returned by the server, and my commit adds the missing debug flag.

**Comment by AenBleidd** [comment]
@Rytiss, if you can make a review of #3370, then, I believe, after approval of #3371, I can make an octopus merge with no problems
