### ISSUE TITLE
Unable to connect to the core client (macOS Catalina 10.15.1)

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3366]
<img width="547" alt="Screen Shot 2019-11-06 at 1 24 48 PM" src="https://user-images.githubusercontent.com/1305957/68339120-cfd39380-0098-11ea-8cb1-2ed636dd7baf.png">

**Comment by Germano0** [comment]
Are you able to switch to advanced mode and connect to `127.0.0.1`?

**Comment by CharlieFenton** [comment]
We will be issuing a new version of BOINC for OS 10.15 Catalina soon.

**Comment by AenBleidd** [comment]
@AustinConlon, is this still an issue with 7.20.0 release?

**Comment by AenBleidd** [comment]
Closing this for now as there is no any response from the topic starter.
