### ISSUE TITLE
contact each scheduler at least once/week

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#337]
**Reported by davea on 12 Feb 37559805 14:13 UTC**
It would be nice if clients contacted each scheduler at least once/week or so; that way if there's a problem with "runaway workunits" that will never make progress (as happened recently with SETI@home) they can be aborted from the server.

If would also be nice if this can be done in a way that doesn't request a connection from dialup users.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/354

**Comment by romw** [comment]
**Commented by Nicolas on 14 Jun 38373761 08:26 UTC**
Can be done using max_rpc_delay (introduced in [10200]). Maybe this ticket could be closed?

**Comment by ChristianBeer** [comment]
Closing because already implemented.
