### ISSUE TITLE
GitHub permission

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3377]
I was able to push commit directly to master, though I shouldn't.

**Comment by TheAspens** [comment]
If you can tell me how to prevent that, I will happily set it up.  I tried once but wound up blocking a bunch of other access.

**Comment by JStateson** [comment]
Something must be working correctly as I mistakenly did a push to the boinc master instead of my upstream and (fortunately for boinc master ) got a permission denied.

**Comment by adamradocz** [comment]
Thanks for the feedback, I'll close the issue for now.

**Comment by lfield** [comment]
I just managed to push to master by accident. I created a branch but forgot to checkout that branch before working on it.

**Comment by TheAspens** [comment]
The only way I see to do this is to enable the branch protection feature of "Require pull request reviews before merging".    See the comment under "Require status checks to pass before merging" that states:

> To avoid direct pushes, simply enable Require pull request reviews before merging

I can enable this if people agree.

**Comment by TheAspens** [comment]
@JStateson - the reason you weren't able to push to master is b/c you do not have write access to the repository.  Your contributions are made via the fork and pull method.

**Comment by TheAspens** [comment]
@AenBleidd and I tried some things out and we were able to protect the master branch by requiring the "continuous-integration/travis-ci/pr" status check to pass before a branch can be merged into master.  If anyone runs into merging to master please let me know.
