### ISSUE TITLE
HTTP headers should be case-insensitive

### ISSUE THREAD

**Issue by HiMrHu** [BOINC/boinc#3382]
**Describe the problem**
The HTTP header information should be case-insensitive, but the request header field is fixed in the code. Some request libraries set the custom request header to lowercase, causing authentication to fail.
[gui_rpc_server_ops.app](https://github.com/BOINC/boinc/blob/master/client/gui_rpc_server_ops.cpp#L1583)

https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive. 

**Describe the solution you'd like**
The request headers should be uniformly converted to lowercase

**Comment by davidpanderson** [comment]
I made this change

**Comment by davidpanderson** [comment]
(in the dpa_gui_rpc_js branch)

**Comment by HiMrHu** [comment]
Thank you, professor.
