### ISSUE TITLE
python scripts don't work with python2

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#3384]
The python3 changes should have been compatible with python2.

**Comment by talregev** [comment]
Python2 is end of life in 2020. All Linux continue to python3. Why insist support python2? 
https://www.python.org/doc/sunset-python-2/

**Comment by davidpanderson** [comment]
Fixed in #4043

**Comment by talregev** [comment]
I think you can safely close this issue.

**Comment by AenBleidd** [comment]
PR is not merged yet so there is no need to close this issue now
