### ISSUE TITLE
make_random_string not work in vitual machine

### ISSUE THREAD

**Issue by HiMrHu** [BOINC/boinc#3385]
When i  test Boinc on different resolutions, so i used VirtualBox to run a windows 10 virtual machine, but i got unicode error on response for  <get_auth_id/>, I tried debug on boinc, iI found 
that the function exits before it completed because of NET_BAD_KEYSET return,  Just want to confirm is this a potential bug of bonic or that’s because I used virtual machine

![response](https://ms.momocdn.com/11/27/4EB4/54C1.png)

![code](https://ms.momocdn.com/11/27/A4E4/AD32.png)

![code](https://ms.momocdn.com/11/27/B696/55AC.png)

**Comment by davidpanderson** [comment]
Fixed in the dpa_gui_rpc_js branch.
