### ISSUE TITLE
Is BOINC working correctly? (Inactivity)

### ISSUE THREAD

**Issue by raisinc** [BOINC/boinc#3404]
I took a screenshot of my active tasks, went to be then (9 hours later) took another screenshot of the "running" tasks.

Of the  12 running tasks, 10 were "waiting to run" and 2 were running, albeit at what seems to be a very slow rate.

The top grooup of tasks were running last night and the bottom group of tasks were running 9 hours later.

Does everything appear normal?

![BOINC running SLOWLY](https://user-images.githubusercontent.com/15245461/70945096-866b6080-20a8-11ea-828d-27f82b77b89c.jpg)

**Comment by AenBleidd** [comment]
Yes, it's a normal scheduling.
You can go to 'Options'->'Event log options' and check 'sched_op_debug'. This will generate additional logs that will show you how scheduling works and when/why it pauses one tasks in favor of others

**Comment by raisinc** [comment]
Thanks for the insight and returning calm to my worried mind. :-)

Cheers
Chris

**Comment by AenBleidd** [comment]
BTW, you can click on 'Show all tasks' button and it will show you all tasks that are currently loaded on your PC, but just not started yet

**Comment by raisinc** [comment]
Hello, friends! The email sent to me asking for updated permissions alerted me to the inactivity in my working with GIT. I am considering this as a sort of "self-isolation" at the moment (LOL). Will get around to using GIT a lot more with my programming projects (after all, I have plenty of time on my hands now. Gave not left my flat for three weeks and live alone, so I am starting to become stir crazy).
