### ISSUE TITLE
Add: Daily Schedules from sunrise to sunset x/y hours delay for solar computing

### ISSUE THREAD

**Issue by cristipurdel** [BOINC/boinc#3411]
**Describe the problem**
Add the option to use as much energy during the day. I am thinking of setting up a small solar array and use the extra energy for boinc. During the night, boinc should consume minimum energy similar to the sleep mode.

**Describe the solution you'd like**
The sunrise and sunset hours should be retrieved based on timezone, and the x hours should be the delay after sunrise while y hours should be the delay before sunset. The actual hours should be displayed in the window for the current day for reference.

**Additional context**
Option should be disabled by default. Android client should not be a priority.

**Comment by AenBleidd** [comment]
Sound interesting. Should be revisited after #2993 being implemented

**Comment by RichardHaselgrove** [comment]
Note that timezone alone won't be sufficient. Northern and southern hemispheres will be very different. Summer and winter times vary greatly at higher latitudes.

**Comment by AenBleidd** [comment]
I believe it will be easier to get current location (e.g. city) and get information from some open service about dawn and dusk. We can even ask user to set his location to be more accurate with daylight period. I see no privacy issues here as soon as this information will be stored locally and sent nowhere

**Comment by KeithMyers** [comment]
You can grab the sunrise/sunset data from` https://openweathermap.org/` for any city in the world for free.  Even has an API if needed.
`https://openweathermap.org/api`

**Comment by makeasnek** [comment]
There are some external tools for accomplishing this, I wrote one called BOINCThermostat. Basically it will take data from a web URL, a file, or a command-line command, and parse it for a number (temperature) and resume/suspend BOINC based on that number and the temperature range you set. But you of course can feed any non-temperature number into it as well. For example, set your temp range to 70-90 and when sun is up, have a script dump the number "80" into a file, and when down, dump the number 100. You could also dump the output wattage of the actual panels and set your BOINC client to only run when wattage is > a certain #.
