### ISSUE TITLE
Transfer my BOINC iOS app to this repository?

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3412]
What would it take to have my [BOINC iOS app repo](https://github.com/AustinConlon/BOINC-iOS-watchOS) transferred to this official repo? The thought came to mind after seeing the Android app here. This iOS app I started is a convenience for checking credits rather than running jobs on device, but I figure if the project gets more visibility from being in this repo instead then maybe more ambitious features might be collaboratively implemented.

**Comment by AenBleidd** [comment]
Android app can run tasks on devices

**Comment by AustinConlon** [comment]
Right, would that be a prerequisite to moving the iOS project to here? For a while I assumed that running tasks on devices wouldn't get past Apple's review process, but it might actually with the new [BackgroundTasks](https://developer.apple.com/documentation/backgroundtasks) framework.

**Comment by davidpanderson** [comment]
It's best to leave it in a separate repo, but if you'd like I can announce it on the BOINC web site and boinc_dev email list and say you're looking for collaborators.

**Comment by davidpanderson** [comment]
BTW, I think the biggest barrier to a BOINC iOS client is that Apple's rules don't allow an app to dynamically download executable code.

**Comment by AenBleidd** [comment]
@davidpanderson, this issue could be solved by providing project executables in app package. This will require more collaborations with projects and longer delay along with other problems like outdated apps on user's devices but at least this could help us to introduce new platform for BOINC

**Comment by AustinConlon** [comment]
> It's best to leave it in a separate repo, but if you'd like I can announce it on the BOINC web site and boinc_dev email list and say you're looking for collaborators.

Sounds great.

**Comment by adamradocz** [comment]
@AustinConlon could you check out my project? It's a half-done Boinc Manager for android and iOS with a shared codebase. Maybe we can collaborate?

**Comment by AustinConlon** [comment]
@adamradocz my experience is in native Swift development so I'd rather stick to that given finite time. Thanks for mentioning it though.

**Comment by AenBleidd** [comment]
Since this is just a question and it is already answered, I tend to close it.
