### ISSUE TITLE
Distributed Hardware Evolution Project URL doesn't work

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3413]
The website is listed as https://dhep.ga/boinc/, but when I try going there it's just blank.
<img width="1176" alt="Screen Shot 2019-12-29 at 7 13 11 AM" src="https://user-images.githubusercontent.com/1305957/71558703-ecda7200-2a0a-11ea-8615-7d6ab3e98817.png">

**Comment by AenBleidd** [comment]
Looks like domain has multiple redirections and is not valid anymore.
@davidpanderson, could you please check and remove it from projects list?

**Comment by davidpanderson** [comment]
I removed it from the list.
-- D
