### ISSUE TITLE
Build: libnotify required even though --disable-manager is set

### ISSUE THREAD

**Issue by rsertelon** [BOINC/boinc#3416]
**Describe the bug**

Building the BOINC client without the manager fails because of missing libnotify.

**Steps To Reproduce**

Without libnotify available, run:

```
./_autosetup
./configure --disable-server --disable-manager
```
It fails with:

```
./configure: line 36044: syntax error near unexpected token `LIBNOTIFY,'
./configure: line 36044: ` PKG_CHECK_MODULES(LIBNOTIFY, libnotify)'
```

at `./configure` line 36044 there is:

```
if test "${enable_manager}" = yes ; then
    PKG_CHECK_MODULES(LIBNOTIFY, libnotify)
fi
```
It seems that the `--disable-manager` is not properly applied.

**Expected behavior**
Building the client without the manager shouldn't require libnotify since there's no desktop integration.

**Screenshots**
N/A

**System Information**
 - OS: linux x64
 - BOINC Version: 7.16.1

**Additional context**
I'd like to build the client only to run it on a server. To that end, I'm creating a [habitat](https://www.habitat.sh/) package of the boinc client.

**Comment by AenBleidd** [comment]
Can't reproduce this on Debian
![image](https://user-images.githubusercontent.com/3234209/72734700-8e805980-3b9a-11ea-982b-f37145242888.png)

**Comment by rsertelon** [comment]
This is weird. In habitat, it is similar to a linux from scratch installation. I'm not very familiar with configure scripts. Do you have any idea of what could turn the flag to `yes` instead of `no` in the excerpt I've included in OP?

**Comment by AenBleidd** [comment]
@rsertelon, just curious, didn't you make a typo in `--disable-manager` parameter?

**Comment by rsertelon** [comment]
The package build is scripted, and here's the relevant part:

```
  ./_autosetup
  ./configure --disable-server --disable-manager --prefix="${pkg_prefix}"
  make
```
It looks good to me :)

**Comment by rsertelon** [comment]
Can I do something more to help?

**Comment by rsertelon** [comment]
So, I've finally found some time to get back to this. It is _not_ a bug in BOINC.
My build environment couldn't find the `pkg.m4` file for the `PKG_CHECK_MODULES` macro. Thus making the configure phase fail. I've added it to the build using the `ACLOCAL_PATH` env var.
