### ISSUE TITLE
Server Stable release 1.2: internal server errors ...

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#3419]
**Describe the bug**
... when clients request work using the 'Anonymous Platform' mechanism.

**Steps To Reproduce**
1. Create and activate an app_info.xml file
2. Request work from a project reporting 'Server version 715'.
Internal server errors observed at SETI@Home, LHC, LHC-dev

**System Information**
 - OS: Windows 7, Linux Mint
 - BOINC Version: 7.16.3, 7.16.1

**Additional context**
This problem came to light following a server upgrade at SETI@Home on 20 December 2019: existing users with existing, working, app_info.xml files were unable to fetch new work. I reproduced the problem on 22 December at LHC@Home, and reported it by email to @lfield (server release manager).

Further testing at LHC-dev with Laurence and Nils Høimyr has generated the attached debug log. Nils' interpretation is that the scheduler is entering an endless loop and crashes when out of memory.

Nils reports that he has tried to reproduce a stack trace as suggested in https://github.com/BOINC/boinc/issues/1994#issuecomment-318261851, but that the gdb 'trick' "does not work in our environment".

[LHC-dev debug log.zip](https://github.com/BOINC/boinc/files/4035061/LHC-dev.debug.log.zip)

---
I would like to suggest that anonymous platform testing is made a formal part of the Server Release process. This is not the first time that an error of this type has slipped through the net: see #194, #690. In the latter case, I remember both @SETIguy and @bema-aei wasting several days each trying to solve their respective problems at the project level, before @JuhaSointusalo tied the threads together and provided the (common) solution.

In the current case, too, the problem was reported in May 2019 as an LHC project-level problem, but not followed through:
https://lhcathome.cern.ch/lhcathome/forum_thread.php?id=5034
https://lhcathomedev.cern.ch/lhcathome-dev/forum_thread.php?id=473

I understand that it has also been reported at SETI Beta, but with that server currently being down because of hardware issues, I can't provide a reference.

**Comment by AenBleidd** [comment]
@lfield, since this affects LHC, could you please verify whether this is still an issue? Thank you in advance.

**Comment by RichardHaselgrove** [comment]
Fixed by commit 80fe66292e43235e40943a262987b771fad514b3, and incorporated in [Server Release 1.2.1](https://github.com/BOINC/boinc/releases/tag/server_release%2F1.2%2F1.2.1). Closing.
