### ISSUE TITLE
AMD Ryzen R9 3900X CPU flags truncated

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#3431]
7.14.2 showed them for my Ryzen R9 3900X to be:

12-Jan-2020 01:22:49 [---] Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 htt pni ssse3 fma cx16 sse4_1 sse4_2 movebe popcnt aes f16c syscall nx lm avx avx2 svm sse4a osvw ibs skinit wdt tce topx page1gb rdtscp fsgsbase bmi1 smep b 

BOINC 7.16.3 and 7.16.4 on Windows 10 Pro x64 1909 truncate it earlier:
16-Jan-2020 13:14:11 [---] Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 htt pni ssse3 fma cx16 sse4_1 sse4_2 movebe popcnt aes f16c rdrandsyscall nx lm avx avx2 svm sse4a osvw ibs skinit wdt tce topx page1gb rdtscp fsgsbase bmi1

25/01/2020 22:02:11 |  | Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 htt pni ssse3 fma cx16 sse4_1 sse4_2 movebe popcnt aes f16c rdrandsyscall nx lm avx avx2 svm sse4a osvw ibs skinit wdt tce topx page1gb rdtscp fsgsbase bmi1 

https://bugzilla.redhat.com/show_bug.cgi?id=1770000 shows we miss a lot more flags. 
All Ryzen 3900X CPU flags: 
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm art rep_good nopl extd_apicid eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core retpoline_amd ssbd ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 arat npt nrip_save umip arch_capabilities

**Comment by RichardHaselgrove** [comment]
Check the character count - I make it 255 / 254 / 254

The bugzilla one is 565 bytes - best round it up to 1K

**Comment by davidpanderson** [comment]
The Windows client was truncating the features field at 255 chars.
I checked in a fix.
-- D

**Comment by RichardHaselgrove** [comment]
I can't see that checkin in master, release branch, or a PR.

**Comment by AenBleidd** [comment]
@RichardHaselgrove, as I see, it is currently committed to private branch only. I believe @davidpanderson is not ready to make a pull request yet.

**Comment by davidpanderson** [comment]
https://github.com/BOINC/boinc/pull/3432
