### ISSUE TITLE
Account creation page does not work

### ISSUE THREAD

**Issue by kahara** [BOINC/boinc#3464]
**Describe the bug**
Account creation page does not work. Complains about reCAPTCHA failing even though reCAPTCHA is successfully passed.

The following error results (in Finnish):

_"Tiliä ei voi luoda
reCAPTCHA-vastaus oli väärin. Yritä uudelleen.
Napsauta selaimesi Back/Takaisin nappia yrittääksesi uudelleen."_

**Steps To Reproduce**
1. Navigate to https://boinc.berkeley.edu/create_account_form.php
2. Fill in details, **succesfully** pass reCAPTCHA
3. Click button on form to complete account creation

**Expected behavior**
Expect account to be created.

**System Information**
 - OS: macOS 10.15.3
 - BOINC Version: N/A

**Additional context**
Tried with the following browsers, each yielding the same result:
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/82.0.4051.0 Safari/537.36
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0

**Comment by AenBleidd** [comment]
This should be fixed by #3461
