### ISSUE TITLE
Regression: broken build as parse.h requires config.h which isn't part of install `Makefile` target

### ISSUE THREAD

**Issue by brevilo** [BOINC/boinc#3470]
**Describe the bug**
As of PR #2311 `parse.h` requires `config.h` which isn't part of the `Makefile` install target. That in turn breaks the API-build for any dependent build downstream.

**Steps To Reproduce**
1. Build BOINC for pure API use: e.g. `--disable-server --disable-client --with-apple-opengl-framework --enable-install-headers --enable-libraries --disable-manager --disable-fcgi`
2. Compile against `boinc_api.h`

**Expected behavior**
A successful build

**System Information**
 - OS: macOS
 - BOINC Version: master

**Additional context**
The issue about the missing `config.h` dependency was noticed at the time but apparently never resolved. In fact, it seems as if this issue was considered out-of-scope which I don't understand as it obviously breaks the build. Related: any regressions in the build system should be caught by the integration/regression tests which I thought is automated nowadays. Why wasn't this one found then...?

**Comment by AenBleidd** [comment]
Sounds like a duplicate of  #2964

**Comment by brevilo** [comment]
I agree, closing this one...
