### ISSUE TITLE
Real-time computing

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#3479]
Some proposed apps require real-time capabilities in BOINC:

- distributed rendering of virtual worlds
- processing of streamed radio-telescope data
- distributed machine-learning systems like Ray
- distributed MPI-type parallel programming

This can't be done in the current queued-job model, which has inherent high latency.  We need a new "real-time" computing model, which sits alongside the queued-job model.

A real-time job, like a non-CPU-intensive job, is in memory all the time, but not necessarily computing.  The client and the app negotiate when the app computes, using message-passing.  The app initiates this by sending a "I want to compute now" or "I want to compute sometime" message.  The client tells it when it can compute, and when it has to stop.

The client runs real-time jobs except when a) it's ruled out by preferences, b) the project's scheduling priority becomes too low (i.e. computing is owed to other projects), or c) there are real-time jobs from other projects (in which case scheduling priority determines who runs).

Real-time apps have a specified resource usage (CPUs, GPUs) like other apps.  The set of real-time jobs for a given project must fit within the host's resources.

When a real-time app runs, it inputs and outputs are sent over network connections, either to a central coordinator or in a peer-to-peer scheme.

**Comment by davidpanderson** [comment]
Here's a video about Ray: https://github.com/anyscale/academy

**Comment by AenBleidd** [comment]
Closed in favor of #5358
