### ISSUE TITLE
[mac] BuildMacBOINC.sh fails to clean plist templates

### ISSUE THREAD

**Issue by brevilo** [BOINC/boinc#3486]
**Describe the bug**
`BuildMacBOINC.sh` fails to clean existing `*.plist` [templates](https://github.com/BOINC/boinc/tree/master/clientgui/mac/templates) that get copied to the `mac_build` directory during build. Any changes to the original templates files aren't reflected in subsequent builds because they aren't updated if they already exist in `mac_build`. This hinders development and confuses [reviewers of PRs](https://github.com/BOINC/boinc/pull/3473#pullrequestreview-365677561) dealing with template changes.

**Steps To Reproduce**
1. Run `BuildMacBOINC.sh`
1. Change any of the [templates](https://github.com/BOINC/boinc/tree/master/clientgui/mac/templates)
1. Run `BuildMacBOINC.sh` and see of your changes are effective (e.g. compare the `*.plist` file) in `mac_build` (or the apps built)

**Expected behavior**
`BuildMacBOINC.sh` should `rm -f` any `*.plist` templates as part of its (default) `clean` target.

**Comment by CharlieFenton** [comment]
Good point. I think this is the first template change in many years, so I hadn't noticed. Another solution would be to change the code in clientgui/mac/setversion.cpp to always replace the *.plist files, even  if they already exist with the correct version number.

**Comment by brevilo** [comment]
Sure, fine with me. Whatever does the trick...

**Comment by CharlieFenton** [comment]
changing the code in clientgui/mac/setversion.cpp would fix it even when a developer builds directly using the Xcode IDE rather than the `BuildMacBOINC.sh` script. Many or most experienced Mac developers would use the Xcode IDE directly, just as Windows developers use Microsoft's Visual Studio IDE
