### ISSUE TITLE
Change to signup.php breaks validation of terms of use

### ISSUE THREAD

**Issue by nilsjh** [BOINC/boinc#3492]
The change from 

**Steps To Reproduce**
1. Click Join on a project web page to join a project.
2. This brings you to "signup.php" that breaks the terms of use validation introduced earlier that was implemented with create_account_form.php.

Broken since this commit: https://github.com/BOINC/boinc/commit/4a3eb03b2689b52e2b7ba2b7e38d1919b1278ae6

**Expected behavior**
The expected behaviour is for the user to see a form that includes the terms of use for the project (e.g. with create_account_form.php )

**System Information**
 - OS: Server: CentOS 7.7 Client: Any browser
 - BOINC server release 1.2.0

**Additional context**
Affects only GDPR compliant sites with Terms of Use flags enabled.

Can be fixed by reverting to the previous version of bootstrap.inc that points to create_account_form.php

**Comment by AenBleidd** [comment]
@lfield, Is this still an issue?

**Comment by lfield** [comment]
There is no way to navigate to `signup.php.  Closing
