### ISSUE TITLE
[Android] 7.16.5: BOINC instantly crashing on startup

### ISSUE THREAD

**Issue by numbermaniac** [BOINC/boinc#3495]
**Describe the bug**
Just updated to the new version of BOINC on the Play Store. As soon as I open it, it crashes instantly. If I attempt to ignore the prompt and go to the Event Log, it will be empty. After a few seconds, the app will close itself.

**Steps To Reproduce**
1. Download the new BOINC update from the Play Store.
2. Open it, and wait about 5 seconds.

**Screenshots**
![BOINC](https://user-images.githubusercontent.com/5206120/76268972-109c1d00-62c4-11ea-812c-e18ae7ae0ef1.png)

**System Information**
 - OS: Android 9
 - BOINC Version: 7.16.5

**Additional context**
Restarted my phone, didn't fix the issue. Moto G6 Play running on Android 9 Pie. Didn't have this issue with the previous version of BOINC.

**Comment by Stiwi** [comment]
I have the same problem with Android 10.

It seems to crash when boinc is allowed to work.  If I am not charging my phone everything seems fine.
After changing the setting so boinc can work on battery it chrashed instantly.

**Comment by SteveHawk** [comment]
Same here with Xiaomi MI6 running MIUI 11 beta (Android 9).
Everytime I press start, the client shows tasks running (but actually not), and if I press the pause button entire client just crashes and exits.

**Comment by PeterHaartsen** [comment]
> 
> 
> I have the same problem with Android 10.
> 
> It seems to crash when boinc is allowed to work. If I am not charging my phone everything seems fine.
> After changing the setting so boinc can work on battery it chrashed instantly.

Same here, Android 10 on Samsung Galaxy S9 plus.

**Comment by IRainman** [comment]
Same problem, ALL version of the BOINC crashed when it's going to background :((( Android 10, OnePlus 7 Pro. Android sucks.

**Comment by cristipurdel** [comment]
Same here for Android 9 with LG V30. I guess it is because it is because of beta option for BOINC. The 7.16.3 from https://boinc.berkeley.edu/dl/?C=M;O=D runs apparently ok sideloaded

**Comment by talregev** [comment]
> * OS: Android 9

Also for me. The new version 7.16.5 is crash on android 9.

**Comment by adamradocz** [comment]
7.16.5 crashes me too but 7.16.3 works fine.

**Comment by juanro49** [comment]
I have same problem #3698

**Comment by jonathandl2** [comment]
Problem began when my carrier (Verizon) pushed an update to my Samsung (March of this year, I think.

**Comment by talregev** [comment]
@jonathandl2 I already fix this problem for 7.16.5 and also it already fix in the master.

**Comment by AenBleidd** [comment]
7.16.5. was a completely buggy release.
Closing this since there is no this issue anymore on the latest private build.
