### ISSUE TITLE
Android 11: using Scoped Storage

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#3497]
I'm not sure if this has any consequences for BOINC on Android, but Android 11 will use Scoped Storage (see https://www.androidcentral.com/what-scoped-storage) and _Any app that is targeted for Android 10 or later must use the new storage APIs, and that includes Scoped Storage. _

**Comment by AenBleidd** [comment]
According to the article, this applies to external (visible to user and other applications) folders and files.
BOINC doesn't use this and stores all files inside it's sandboxed folder.
So currently as far as I see, this change will not affect us.
