### ISSUE TITLE
Code improvements results from Cppcheck

### ISSUE THREAD

**Issue by jensdenbraber** [BOINC/boinc#3513]
I ran [cppcheck](https://github.com/danmar/cppcheck) on the Boinc codebase which resulted in the some code improvements. 

Download the results here: [boinc_cppcheck.zip](https://github.com/BOINC/boinc/files/4365631/boinc_cppcheck.zip)

**Comment by AenBleidd** [comment]
Thank you for collecting this data. You're always welcome to fix any of these found issues.

**Comment by AenBleidd** [comment]
Code is constantly changes. There is no reason to track such a ticket. Closing it as 'wontfix'
