### ISSUE TITLE
BOINC is not seeing any of my GPUs

### ISSUE THREAD

**Issue by valeriob01** [BOINC/boinc#3520]
I have ROCm 3.10 installed on Debian, and boinc client is not seeing any of my 2 gpus (AMD Vega64). Other applications work fine.

**Comment by Rytiss** [comment]
Please enable coproc_debug in your cc_config.xml, restart the client, and attach the log here. It should show the entire GPU detection process, so maybe we can figure out where it hangs up.

**Comment by valeriob01** [comment]
Tue 24 Mar 2020 03:41:51 PM CET |  | Starting BOINC client version 7.14.2 for x86_64-pc-linux-gnu
Tue 24 Mar 2020 03:41:51 PM CET |  | log flags: file_xfer, sched_ops, task, coproc_debug
Tue 24 Mar 2020 03:41:51 PM CET |  | Libraries: libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Tue 24 Mar 2020 03:41:51 PM CET |  | Data directory: /var/lib/boinc-client
Tue 24 Mar 2020 03:41:51 PM CET |  | [coproc] launching child process at /usr/bin/boinc
Tue 24 Mar 2020 03:41:51 PM CET |  | [coproc] with data directory /var/lib/boinc-client
Tue 24 Mar 2020 03:41:51 PM CET |  | [coproc] NVIDIA: libcuda.so: cannot open shared object file: No such file or directory
Tue 24 Mar 2020 03:41:51 PM CET |  | [coproc] ATI: libaticalrt.so: cannot open shared object file: No such file or directory
Tue 24 Mar 2020 03:41:51 PM CET |  | [coproc] OpenCL library present but no OpenCL-capable devices found
Tue 24 Mar 2020 03:41:51 PM CET |  | No usable GPUs found
Tue 24 Mar 2020 03:41:51 PM CET |  | [libc detection] gathered: 2.28, Debian GLIBC 2.28-10
Tue 24 Mar 2020 03:41:51 PM CET |  | Host name: devops1
Tue 24 Mar 2020 03:41:51 PM CET |  | Processor: 12 AuthenticAMD AMD Ryzen 5 3600 6-Core Processor [Family 23 Model 113 Stepping 0]
Tue 24 Mar 2020 03:41:51 PM CET |  | Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd sev ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca
Tue 24 Mar 2020 03:41:51 PM CET |  | OS: Linux Debian: Debian GNU/Linux 10 (buster) [4.19.0-5-amd64|libc 2.28 (Debian GLIBC 2.28-10)]
Tue 24 Mar 2020 03:41:51 PM CET |  | Memory: 15.68 GB physical, 15.96 GB virtual
Tue 24 Mar 2020 03:41:51 PM CET |  | Disk: 27.37 GB total, 4.29 GB free
Tue 24 Mar 2020 03:41:51 PM CET |  | Local time is UTC +1 hours
Tue 24 Mar 2020 03:41:51 PM CET |  | Config: GUI RPCs allowed from:
Tue 24 Mar 2020 03:41:51 PM CET | PrimeGrid | URL http://www.primegrid.com/; Computer ID 995517; resource share 100
Tue 24 Mar 2020 03:41:51 PM CET | PrimeGrid | General prefs: from PrimeGrid (last modified 24-Mar-2020 10:52:11)
Tue 24 Mar 2020 03:41:51 PM CET | PrimeGrid | Host location: none
Tue 24 Mar 2020 03:41:51 PM CET | PrimeGrid | General prefs: using your defaults
Tue 24 Mar 2020 03:41:51 PM CET |  | Reading preferences override file
Tue 24 Mar 2020 03:41:51 PM CET |  | Preferences:
Tue 24 Mar 2020 03:41:51 PM CET |  | max memory usage when active: 12039.44 MB
Tue 24 Mar 2020 03:41:51 PM CET |  | max memory usage when idle: 14447.33 MB
Tue 24 Mar 2020 03:41:51 PM CET |  | max disk usage: 3.38 GB
Tue 24 Mar 2020 03:41:51 PM CET |  | (to change preferences, visit a project web site or select Preferences in the Manager)
Tue 24 Mar 2020 03:41:51 PM CET |  | Setting up project and slot directories
Tue 24 Mar 2020 03:41:51 PM CET |  | Checking active tasks
Tue 24 Mar 2020 03:41:51 PM CET |  | Setting up GUI RPC socket
Tue 24 Mar 2020 03:41:51 PM CET |  | gui_rpc_auth.cfg is empty - no GUI RPC password protection
Tue 24 Mar 2020 03:41:51 PM CET |  | Checking presence of 165 project files

**Comment by valeriob01** [comment]
RESOLVED: installedfglrx-driver glx-alternative-glx 

Tue 24 Mar 2020 04:11:31 PM CET |  | cc_config.xml not found - using defaults
Tue 24 Mar 2020 04:11:31 PM CET |  | Starting BOINC client version 7.14.2 for x86_64-pc-linux-gnu
Tue 24 Mar 2020 04:11:31 PM CET |  | log flags: file_xfer, sched_ops, task
Tue 24 Mar 2020 04:11:31 PM CET |  | Libraries: libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Tue 24 Mar 2020 04:11:31 PM CET |  | Data directory: /home/sel/Downloads/BOINC
Tue 24 Mar 2020 04:11:31 PM CET |  | OpenCL: AMD/ATI GPU 0: Vega 10 XL/XT [Radeon RX Vega 56/64] (driver version 3084.0 (HSA1.1,LC), device version OpenCL 2.0, 8176MB, 8176MB available, 13353 GFLOPS peak)
Tue 24 Mar 2020 04:11:31 PM CET |  | OpenCL: AMD/ATI GPU 1: Vega 10 XL/XT [Radeon RX Vega 56/64] (driver version 3084.0 (HSA1.1,LC), device version OpenCL 2.0, 8176MB, 8176MB available, 13353 GFLOPS peak)
Tue 24 Mar 2020 04:11:31 PM CET |  | [libc detection] gathered: 2.30, Debian GLIBC 2.30-2
Tue 24 Mar 2020 04:11:31 PM CET |  | Host name: devops1
Tue 24 Mar 2020 04:11:31 PM CET |  | Processor: 12 AuthenticAMD AMD Ryzen 5 3600 6-Core Processor [Family 23 Model 113 Stepping 0]
Tue 24 Mar 2020 04:11:31 PM CET |  | Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd sev ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca
Tue 24 Mar 2020 04:11:31 PM CET |  | OS: Linux Debian: Debian GNU/Linux 10 (buster) [4.19.0-5-amd64|libc 2.30 (Debian GLIBC 2.30-2)]
Tue 24 Mar 2020 04:11:31 PM CET |  | Memory: 15.68 GB physical, 15.96 GB virtual
Tue 24 Mar 2020 04:11:31 PM CET |  | Disk: 872.68 GB total, 439.27 GB free
Tue 24 Mar 2020 04:11:31 PM CET |  | Local time is UTC +1 hours
Tue 24 Mar 2020 04:11:31 PM CET |  | Last benchmark was 18345 days 15:11:31 ago
Tue 24 Mar 2020 04:11:31 PM CET |  | No general preferences found - using defaults
Tue 24 Mar 2020 04:11:31 PM CET |  | Preferences:
Tue 24 Mar 2020 04:11:31 PM CET |  | max memory usage when active: 8026.29 MB
Tue 24 Mar 2020 04:11:31 PM CET |  | max memory usage when idle: 14447.33 MB
Tue 24 Mar 2020 04:11:31 PM CET |  | max disk usage: 439.18 GB
Tue 24 Mar 2020 04:11:31 PM CET |  | don't use GPU while active
Tue 24 Mar 2020 04:11:31 PM CET |  | suspend work if non-BOINC CPU load exceeds 25%
Tue 24 Mar 2020 04:11:31 PM CET |  | (to change preferences, visit a project web site or select Preferences in the Manager)
Tue 24 Mar 2020 04:11:31 PM CET |  | Setting up project and slot directories
Tue 24 Mar 2020 04:11:31 PM CET |  | Checking active tasks
Tue 24 Mar 2020 04:11:31 PM CET |  | Setting up GUI RPC socket
Tue 24 Mar 2020 04:11:31 PM CET |  | Checking presence of 0 project files
Tue 24 Mar 2020 04:11:31 PM CET |  | This computer is not attached to any projects
Tue 24 Mar 2020 04:11:31 PM CET |  | Suspending GPU computation - computer is in use
Tue 24 Mar 2020 04:11:52 PM CET |  | Fetching configuration file from https://www.primegrid.com/get_project_config.php
Tue 24 Mar 2020 04:12:05 PM CET |  | Running CPU benchmarks
Tue 24 Mar 2020 04:12:05 PM CET |  | Suspending computation - CPU benchmarks in progress
Tue 24 Mar 2020 04:12:36 PM CET |  | Benchmark results:
Tue 24 Mar 2020 04:12:36 PM CET |  | Number of CPUs: 12
Tue 24 Mar 2020 04:12:36 PM CET |  | 7198 floating point MIPS (Whetstone) per CPU
Tue 24 Mar 2020 04:12:36 PM CET |  | 73763 integer MIPS (Dhrystone) per CPU
Tue 24 Mar 2020 04:12:36 PM CET |  | Resuming computation
Tue 24 Mar 2020 04:12:37 PM CET | PrimeGrid | Master file download succeeded
Tue 24 Mar 2020 04:12:42 PM CET | PrimeGrid | Sending scheduler request: Project initialization.
Tue 24 Mar 2020 04:12:42 PM CET | PrimeGrid | Requesting new tasks for CPU and AMD/ATI GPU
