### ISSUE TITLE
Dockerfile with all necessary build components preinstalled

### ISSUE THREAD

**Issue by mcandre** [BOINC/boinc#3531]
**Describe the problem**

For Linux users, a Dockerfile with everything preinstalled for building boinc, would be a very fast way indeed to onboard onto the project.

**Describe the solution you'd like**

Add a `Dockerfile`, such as a Debian or CentOS distribution, with all the compilers, dependencies, linters, and so on installed. The Dockerfile generates a Docker image, which is able to build Linux boinc binaries.

**Additional context**

Relates to https://github.com/BOINC/boinc/issues/3529

**Comment by AenBleidd** [comment]
From my personal experience, there is no such big amount of dependencies to create docker image instead of using native system

**Comment by adamradocz** [comment]
I made one 2 years ago. https://github.com/adamradocz/boinc-client-builder-docker
