### ISSUE TITLE
Cannot resume GPU operation from the manager

### ISSUE THREAD

**Issue by ghaiklor** [BOINC/boinc#3535]
**Describe the bug**

When clicking the "Resume GPU" options it does nothing. GPU does not start to spin the fans or make any useful load and the button remains the same "Resume GPU"

<img width="259" alt="Screenshot 2020-03-27 at 13 35 58" src="https://user-images.githubusercontent.com/3625244/77752272-ecfd0480-702f-11ea-86ca-74887f1e52c2.png">

**Steps To Reproduce**
Not sure, it works before on the previous version, but today I got an update to the 7.14.3 and it does not work anymore.

**Expected behavior**
When I click "Resume GPU" I expect to see that GPU is starting to work

**System Information**
 - OS: MacOS 10.15.4 (19E266)
 - BOINC Version: 7.14.3

**Comment by ghaiklor** [comment]
I've managed to grab some logs from GUI RPC, but nothing interesting so far. I see that the request was sent from the GUI.

<img width="1150" alt="Screenshot 2020-03-27 at 13 42 57" src="https://user-images.githubusercontent.com/3625244/77752812-f6d33780-7030-11ea-9bc3-74486a128d3d.png">

**Comment by AenBleidd** [comment]
Could you please whether you have GPU tasks is queue?

**Comment by AenBleidd** [comment]
Also it's possible that you have more prioritized CPU tasks that should be finished first and no CPU resources to run additional GPU task

**Comment by ghaiklor** [comment]
@AenBleidd 

> Could you please whether you have GPU tasks is queue?

I have, yes

> Also it's possible that you have more prioritized CPU tasks that should be finished first and no CPU resources to run additional GPU task

No prioritising.

I was managed to fix that by going to Activity tab:

<img width="335" alt="Screenshot 2020-03-27 at 15 20 33" src="https://user-images.githubusercontent.com/3625244/77760124-8e8b5280-703e-11ea-9e3f-d72a7c3db5ec.png">

After that "Resume GPU" changed back to "Snooze GPU" and everything came back to normal. So, seems like an UI problem?

**Comment by CharlieFenton** [comment]
I just now tested this on OS 10.15.4 with BOINC 7.14.3 and it works correctly. I could not reproduce your problem.

**Comment by ghaiklor** [comment]
@CharlieFenton as I said, it works now, so it could be a glitch after upgrading just for my local machine 🐛 

What else I noticed right now is that when you have Dark Mode in MacOS, 7.14.3 becomes 

<img width="2032" alt="Screenshot 2020-03-27 at 18 45 17" src="https://user-images.githubusercontent.com/3625244/77779684-91487080-705b-11ea-83d9-5fbc2cef5d7e.png">

**Comment by CharlieFenton** [comment]
> when you have Dark Mode in MacOS

Please see issue #2917

**Comment by ghaiklor** [comment]
Closing this one as "possible glitch after upgrade"

**Comment by CharlieFenton** [comment]
> when you have Dark Mode in MacOS

I have released BOINC 7.14.4 for Macintosh which tells the OS to not use dark mode for BOINC even when Dark Mode is generally selected. This workaround allows BONC to be usable under Dark Mode until BOINC can be updated to fully support dark mode.
