### ISSUE TITLE
Option crunching from battery

### ISSUE THREAD

**Issue by Gevetus** [BOINC/boinc#3560]
Hello. I installed boinc to my smartphone samsung A20S and to the tablet samsung. I want to crunch when my device is power from battery. But i don't see this option, instead this i see two options "from wall socket"-the first and the fourth option. Version of boinc 7.4.53. 
 
![Screenshot_20200405-124803_BOINC](https://user-images.githubusercontent.com/63200276/78503488-808cae80-776f-11ea-8439-c6900e16b7f8.jpg)
![Screenshot_20200405-124810_BOINC](https://user-images.githubusercontent.com/63200276/78503494-88e4e980-776f-11ea-80df-cd0e43218e2c.jpg)

**Comment by AenBleidd** [comment]
it should be there. You just need to scroll down. It is a known UI issue

**Comment by Gevetus** [comment]
I cann't scroll it. Nothing happens.

**Comment by AenBleidd** [comment]
Try to reinstall then. I'll take a look at it but it will not be fixed soon because it's not highest priority issue. I'm sorry.

**Comment by Gevetus** [comment]
I reinstalled it with the same result.

**Comment by Ageless93** [comment]
I've asked that he post it here after he posted it on the BOINC forums
first.
The weird thing is, in English it works correctly. If this was just a
translation problem, the 4th option to run  on battery would still need to
have the same underlying code as it did in English. But apparently it
doesn't, which I cannot explain. Just switching to Russian shouldn't affect
the code so much that it shows and uses wall socket code in two places.

**Comment by AenBleidd** [comment]
This should be already fixed in the latest release.
