### ISSUE TITLE
Android: optionally allow computing when screen is on

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#3569]
User email:
 I've been using it on my phone to help out with corona virus research but would rather have it on my Nvidia shield since it's constantly plugged in all day. The only thing is there's no option to turn off screen so it can start crunching the numbers like my phone does.

**Comment by adamradocz** [comment]
There's already an option for that. Pause computation when screen is on.

**Comment by AenBleidd** [comment]
I believe this option is hidden by default and could be changed after checking `Show advanced preferences and controls` option
