### ISSUE TITLE
[Windows Installer] Installer properties doesn't work.

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3570]
**Describe the bug**
The PROJINIT_URL property doesn't work.

**Steps To Reproduce**
1. Install the BOINC v7.16.5 on a fresh PC with the following command.
2. `boinc_7.16.5_windows_x86_64.exe /v"/qn PROJINIT_URL=https://www.worldcommunitygrid.org PROJINIT_AUTH=abcdef1234567890abcdef012345678"`

**Expected behavior**
After the installation when I start the BOINC Manager I expect the WCG attached.

**System Information**
 - OS: Windows 7 x64, Windows 10 x64
 - BOINC Version: 7.14.2, 7.16.5

**Comment by davidpanderson** [comment]
I think this feature was removed at some point; I can't find it in the code.  You can do this by putting an account_*.xml file in the BOINC directory.

**Comment by adamradocz** [comment]
In this case, the [https://boinc.berkeley.edu/wiki/Creating_custom_installers](https://boinc.berkeley.edu/wiki/Creating_custom_installers) should be updated.

**Comment by AenBleidd** [comment]
When I will have time to continue with #3194, maybe this feature could be added to new installer if it will be required

**Comment by adamradocz** [comment]
I think it'd be useful. Plus an attach account manager option too.

**Comment by AenBleidd** [comment]
I believe this is a preferred way of doing this: #2250
@davidpanderson, could you please update documentation and remove options that are not in the installer anymore?

**Comment by davidpanderson** [comment]
I'll remove it from the docs.
