### ISSUE TITLE
Using Boinc Android as a Lib

### ISSUE THREAD

**Issue by thiagopelikan** [BOINC/boinc#3572]
**Describe the problem**
Is it possible to have Boinc running on my own app using it as a lib? I want to create an app with other features and one of them should use BOINC. Is HTC Power to Give doing this on their APK?

I've been trying to compile the project to see how it works, but I'm having a lot of difficulties, in addition I see that you are improving the project every day, so I would like to know if this possibility(be made available as a lib) exists.

**Describe the solution you'd like**
I don't know the solution for this, maybe it's already available and I couldn't found it, or we could simple use Intents and Services for example

**Comment by AenBleidd** [comment]
What is the purpose of this? What exactly you want to use?

**Comment by thiagopelikan** [comment]
What is the purpose of this?
I want to connect my App to an existing BOINC project and help computing. The app must include some info on how to improve humanity, like places to do donation, but I don't have much details for now, I'm just studying the possibility to use BOINC on this idea. 

What exactly you want to use?
I want a way to connect to a BOINC project, starting computing, get infos from computing and send data to BOINC after computing is done.

**Comment by AenBleidd** [comment]
BOINC client (compiled as executable) could be used in this way. Closing for now
