### ISSUE TITLE
Android: Cannot add boinc account manager of Science United. It not on the list.

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#3581]
**Describe the bug**

**Steps To Reproduce**
1. install android boinc
2. add project -> add account manager
3. search in the list Science United

**Expected behavior**
Should be option to add Science United account manager.

**Screenshots**

**System Information**
 - OS: 
android 8 (also android 7).
 - BOINC Version: 
7.4.53

**Additional context**

**Comment by AenBleidd** [comment]
Science United is available in Android BOINC 7.16.3. In is available on Play Store Beta

**Comment by talregev** [comment]
It a great news that android boinc will upgrade to 7.16.x version!
I will wait for the release.
