### ISSUE TITLE
Android: user can add multiple account manager

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#3582]
**Describe the problem**
A clear and concise description of the problem you're looking to solve.
I can only add one account manager. 

**Describe the solution you'd like**
I want to add multiple account manager to boinc android. 
It will distribute equally between two account managers, if there on account manager will be lack with work or projects, the other account manager can be fill out. also it will be nice if you let the user choose the amount of work between two account managers. 

**Additional context**
Android client.
Android 8 and above.
version 7.4.53

**Comment by AenBleidd** [comment]
It is not possible by design to add more than one Account Manager.
