### ISSUE TITLE
Checkpoints are ignored or not generated

### ISSUE THREAD

**Issue by jmaschtaler** [BOINC/boinc#3586]
Hello,

every time I (re-)boot my computer the tasks are computed at their beginning at 0 %.

The BOINC Mangers offers to set a time in seconds to "Request tasks to checkpoint at most every x seconds".
Either such checkpoints are ignored or are not generated.

System:
Ubuntu 18.04
BOINC* 7.9.3+dfsg-5ubuntu2 (from official repos)

Syslog does not show any hints.

My attempts:
- Change the time.
- Use local prefs.
- Use web prefs.

Any idea how to get checkpoints recognized?

Thanks and best regards,
Jörg

**Comment by davidpanderson** [comment]
Which projects?  Some projects have apps that don't checkpoint.

**Comment by jmaschtaler** [comment]
Hi David,

thanks for answering.

I didn't know that checkponts are not supported by every project.

The project is Rosetta@Home.
I tried to figure it out but cannot find any info about that.

Do you know by chance?

Thanks,
Jörg

**Comment by AenBleidd** [comment]
@jmaschtaler, btw, you use quite old version of BOINC, you should consider to update to the latest one. You can find appropriate PPA here: https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/boinc?field.series_filter=bionic
Regarding Rosetta, it's better to ask on their forums. 
You should also inspect Rosetta's logs in slots directory (if you don't know how to find it, just ask me and I'll help you), maybe they tries to save checkpoints but failed for some reason.

**Comment by adamradocz** [comment]
@jmaschtaler I've noticed that nowadays some Rosetta projects don't checkpoint. You can check for yourself which ones. Just click on the Task and Properties and look for the `CPU time since checkpoint` feature. If it's bigger eg 10 minutes, it doesn't checkpoint or very rarely.

![CPU time since checkpoint](https://user-images.githubusercontent.com/16503773/79036183-0b353980-7bc6-11ea-9294-e0f9c170bec2.PNG)

**Comment by jmaschtaler** [comment]
Just a little workaround I accidentally discovered:
Suspending the tasks (before shutdown) does generate a checkpoint (or sort of).
Resuming the tasks after the boot does the trick.
