### ISSUE TITLE
Please release a beta version for Android as soon is possible!

### ISSUE THREAD

**Issue by IRainman** [BOINC/boinc#3589]
Currently Rosetta fights with COVID-19 on Android devices too. But BOINC work normally for me only on Android 6 and 4.3.1 installed on the very old devices. In the newer version, this does not work: Android 10 ( https://boinc.bakerlab.org/rosetta/show_host_detail.php?hostid=4094074  ) always kills BOINC, and the calculations do not work at all, on Android 9 ( https://boinc.bakerlab.org/rosetta/show_host_detail.php?hostid=4093981 ), it is periodically killed by the system. Booth of this devices don't use all the cores, only 7 from 8, or 3 from 4. :(

Please release version without this critical defect. All other defects currently is unimportant.

P.S. Android sucks.

**Comment by AenBleidd** [comment]
The latest stable BOINC for Android is 7.4.53. It was reported to work quite stable even on Android 10. For the new version, see information in #3561

**Comment by IRainman** [comment]
@AenBleidd 7.4.53 it's not working, rly:
1) If the app going to background it's instantly killed by system.
2) If the app is an active application, only the screen is switch off computation stopped immediately.
3) If the app running on the system start, or after killing by system (1), it's only use 1 little core.
4) For start the app you need to stop it after the device is booting and open it from launcher and don't touch the device after it (3).
5) You need to enable option "don't disable screen" in debug options.
As the result, the version 7.4.53 only "works" with the display is active and the BOINC is active too - it's equivalent  to not working.

**Comment by AenBleidd** [comment]
I understand you. But the problem is that all issues you described is a result of new kernel restrictions and scheduling policies that Google introduced in Android. There are some tricks you can do to overcome it (e.g. in battery saving optimization settings add BOINC as an exception) but almost nothing can be done from application side. I assure you: if we'd have a solution for this - we'd immediately release a new version. Currently we plan to change the architecture (see the issue I mentioned in previous message) but this also will not fix all problems you described. If you want more details - feel free to contact me directly in discord.

**Comment by davidpanderson** [comment]
Vitalii:

We need to give users information about how to make BOINC work on their
phone
(if it's possible at all).
Otherwise users - in large numbers - will install BOINC, see that it
doesn't work,
uninstall it, give it a 1-star review, and never return.

We need a page something like this:
https://boinc.berkeley.edu/wiki/Android_issues
... with some actual information.

Do we know enough to complete this page?

Let's talk about this on Skype, soon.

-- D

**Comment by IRainman** [comment]
@AenBleidd I also know the real situation. In fact, the latest version on which **BOINC works normally is Android 7**. You should honestly write about this everywhere including Google Play and also explain what problems exist in newer versions of Android. Correctly written by @davidpanderson, **you need a clear list of problems with the description of crutches for those who want to somehow use BOINC on new versions of Android. Until this is done BOINC does not work.** Sorry. The reputation of the project is very important, now there is a unique situation when we have the opportunity to attract new users to the community against the backdrop of the fight against COVID-19, but we cannot lie to all these people that it works because it does not work ;)

**Comment by IRainman** [comment]
I also see additional methods available for developers 
It:
https://stackoverflow.com/questions/44443690/notificationcompat-with-api-26/44524976#44524976
And, probably, it:
https://stackoverflow.com/questions/34573109/how-to-make-an-android-app-to-always-run-in-background?noredirect=1&lq=1

**Comment by AenBleidd** [comment]
Please take a look at #3561. I left information there why it's not working anymore

**Comment by IRainman** [comment]
@AenBleidd then write, please, everywhere that the current version only works up to version Android 7, and also that work is underway to write a completely new application that will work well, without crutches and, possibly, not only on Android, but also on iOS ;)

**Comment by AenBleidd** [comment]
But it works. Not for everyone, not so stable. But works. I have successful reports

**Comment by Ageless93** [comment]
I have 3 Android devices running 7.4.53, two Android 7.0, one Android 8.1
with no problems at Universe, Einstein, Asteroids and the last resends of
Seti.

My Android 9 device can run it, as long as I then don't use the phone (turn
on the screen) as then BOINC will crash.

**Comment by IRainman** [comment]
@Ageless93 on Android 8.1 your devices use all cores or not? It was in Android 8 that mechanisms were implemented that broke everything.

**Comment by Ageless93** [comment]
The device with Android 8.1 only has 4 of the same cores, so it uses all of
them. One of the Android 7 devices has 8 cores, of which I can use only 4.
But that has a whole different reason than the fact we can use BOINC or not
on these Android versions.

**Comment by truboxl** [comment]
What exactly is the state of BOINC Android on master branch? You can compile BOINC Android native client yes, but upon loading up to Android Studio and it has tons of errors upon running on the emulator. It wasn't like that before. Isira said it was not a complete rewrite but most of the code has changed and broken.

**Comment by AenBleidd** [comment]
Currently BOINC for Android is not ready for release. Current master version is cleaned from outdated code and a little bit simplified. But yet because of Google updated policy in newest API it is not ready for release without major architecture change

**Comment by IRainman** [comment]
and somewhere there is the promised version 7.16.7 (or 7.17), is it possible to compile it? I need a fix so that the application does not killed by system "for every sneeze". I have a smart alarm clock https://play.google.com/store/apps/details?id=com.urbandroid.sleep it works great, does not allow the device to fall asleep with the screen off and does not killed by system. As I understand it, one line in the manifest is enough for it to be the same?

**Comment by AenBleidd** [comment]
There is no promised version neither 7.16.7 not 7.17. If you want - you can compile master branch.

> I need a fix so that the application does not killed by system "for every sneeze".

There is no such fix.

I know nothing about application you mentioned, but I suppose it's very different from the BOINC (at least, it's not so heavy for the system).

> As I understand it, one line in the manifest is enough for it to be the same?

I don't know about what line you're talking about, but if you can share it here, we can check it. Also, you can check it by yourselves if you decide to build your own copy of BOINC for Android.

**Comment by IRainman** [comment]
I probably found another crutches list for the current version of BOINC is worked fine https://forum.xda-developers.com/showpost.php?p=78588761&postcount=7 .  Now I test it.

**Comment by Isira-Seneviratne** [comment]
The current master works fine. We should be able to release a new beta version once it has been confirmed to work on older devices (those that are running KitKat), so it would be great if anyone is willing to test it on any older devices they have.

![Screenshot_20200607-045836_BOINC](https://user-images.githubusercontent.com/31027858/83956463-17fba400-a87c-11ea-8a80-6548bb052a62.png)

**Comment by talregev** [comment]
We wroking on it.

**Comment by AenBleidd** [comment]
Due to the new requirements on Play Store, BOINC will not be released there for a while.
Newer releases will be published in the official web-site (https://boinc.berkeley.edu/download_all.php)
Possibly there will be releases on F-Droid but there is not exact info about it yet.

New BOINC would appear on PlayStore after significant change: #3561
