### ISSUE TITLE
Notifications message about "fetching tasks for CPU" is from 1 project only, while 4 are affected

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#3590]
I have multiple projects set to run just on GPU, so all of those are telling me at startup:
11/04/2020 17:46:08 | collatz | Your settings do not allow fetching tasks for CPU.  To fix this, you can change Project Preferences on the project's web site.
11/04/2020 17:46:08 | Einstein@Home | Your settings do not allow fetching tasks for CPU.  To fix this, you can change Project Preferences on the project's web site.
11/04/2020 17:46:08 | Milkyway@Home | Your settings do not allow fetching tasks for CPU.  To fix this, you can change Project Preferences on the project's web site.
11/04/2020 17:46:08 | SETI@home Beta Test | Your settings do not allow fetching tasks for CPU.  To fix this, you can change Project Preferences on the project's web site.

Yet only the Collatz project is showing this message in Notifications. I would expect all four of them to show there.
This is in
11/04/2020 17:45:42 |  | Starting BOINC client version 7.16.5 for windows_x86_64
11/04/2020 17:45:43 |  | OS: Microsoft Windows 10: Professional x64 Edition, (10.00.18363.00)

**Comment by RichardHaselgrove** [comment]
This event log message was introduced in commit 40f0cb44f4fcd11eb2789408dfc868de63e42242, the big one about "Avoid starvation when max_concurrent is used, and related fixes."

I'm getting one notice for each installed device type, even though I have multiple preference exclusions across seven projects.

**Comment by Ageless93** [comment]
A lot of people find these notifications annoying and are asking for a way to silence them. 

Perhaps we should make sure that for those who don't mind, for those who like to have the reminder about their preferences, that we keep this but fix it do it shows it for all projects. 

And for those who dislike this behaviour, that there's an option to silence these kinds of notifications. 
Notification leveling perhaps, not unlike the GUI messages level in the Android client?

**Comment by RichardHaselgrove** [comment]
No, he didn't. I take responsibility for that edit.
