### ISSUE TITLE
libcurl link test may fail with "cannot find -lssl"

### ISSUE THREAD

**Issue by truboxl** [BOINC/boinc#3591]
**Describe the bug**
See https://github.com/BOINC/boinc/blob/master/m4/libcurl.m4#L109

              if test "x`echo \""$LIBCURL"\" | grep ssl`" = x ; then

It checks for `curl-config --features` which outputs `SSL`
Unfortunately `grep ssl` doesn't take into account capitalise `SSL` which causes `SSL_LIBS` to be not included in libcurl test, causing the linker to have `cannot find -lssl` and `cannot find -lcrypto`

See also https://curl.haxx.se/libcurl/using/curl-config.html

> How do I know if libcurl was built with SSL support?
> 
> $ curl-config --feature | grep SSL

Edit: Corrected the variables. Fun fact `curl-config --feature` and `curl-config --features` have the same output.

**Comment by AenBleidd** [comment]
@truboxl, could you please provide a PR that will contain case insensitive grep command?

**Comment by truboxl** [comment]
I think I got it wrong, it looks for `curl-config --libs` which outputs `-lssl`
I think I will investigate further why libcurl test doesn't include the SSL include folders when linking...

**Comment by truboxl** [comment]
I got it wrong again, the link test involves OpenSSL `-L/...` and not OpenSSL `-I/...`
But there's still something wrong with the test.

It checks for `-lssl` then assumes `LIBCURL=` can be used for link test but it may lack OpenSSL `-L/...`.

For my setup, `SSL_LIBS=` has the OpenSSL `-L/...` and `-lssl`
but because the test checks only for `-lssl` and skips over including `SSL_LIBS=`.

I think adding an extra test of `SSL_LIBS=` for OpenSSL `-L/...` before the `-lssl` test is needed

as checking `LIBCURL=` may only output libcurl `-L/...`
and its hard to differentiate from the two `-L/...`.

I still dunno where it source `SSL_LIBS=` from as it mention only once.

I also dunno this should be fixed or not as there's a note to override this.
https://github.com/BOINC/boinc/blob/master/m4/libcurl.m4#L29

I also think there's a need for clean up the identation, doesn't work too well in VS Code...
