### ISSUE TITLE
ifdef ANDROID

### ISSUE THREAD

**Issue by truboxl** [BOINC/boinc#3596]
**Describe the bug**
See https://groups.google.com/d/msg/android-ndk/cf9_f1SLXls/gHqd6AFfAgAJ
and https://stackoverflow.com/questions/6374523/how-to-detect-compilation-by-android-ndk-in-a-c-c-file
and funnily enough https://github.com/BOINC/boinc/blob/master/client/android/AndroidBuild.sh#L284

**Steps To Reproduce**
When passing NDK Clang with `$CC -E -dM - < /dev/null | grep -i android`, the output is:
```
#define __ANDROID_API__ 21
#define __ANDROID__ 1
#define __VERSION__ "4.2.1 Compatible Android (5900059 based on r365631c) Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 207d7abc1a2abf3ef8d4301736d6a7ebc224a290)"
#define __clang_version__ "9.0.8 (https://android.googlesource.com/toolchain/llvm-project 207d7abc1a2abf3ef8d4301736d6a7ebc224a290)"
```

Suggest changing `ANDROID` to `__ANDROID__` wherever ifdef is as much as possible, if not all.

**Expected behavior**
Clang will work out the rest. Users don't need to pass `-DANDROID` or whatever that variant during compile anymore.

**Comment by truboxl** [comment]
`-DANDROID_64` is also useless

https://github.com/BOINC/boinc/commit/5d31a75b7c24feb58b32425ea118225210227817
https://github.com/BOINC/boinc/commit/802225c7e4bf9bdfd0e5e64d2c2c4f0df0d9e7f9

There maybe other parameters that don't affect the Android compile process or just outright bugs.

**Comment by AenBleidd** [comment]
@truboxl, could you please provide PR with such changes? Thanks in advance

**Comment by truboxl** [comment]
Current progress:
1. I am still finding the ifdef responsible for controlling the handling the network detection to a Java UI and change that to something that is controllable.

1. Some patches from https://github.com/BOINC/boinc/blob/master/client/android/AndroidBuild.sh should be applied too.

1. A simple change of `ANDROID` to `__ANDROID__` is not easy
given how many occurrences found using `grep 'ANDROID' -R`

1. `ANDROID_NEON` and `ANDROID_VFP` should be changed to something that applies automatically, maybe something from these:
```
$ ./armv7a-linux-androideabi16-clang -E -dM - </dev/null | grep -i ARM
#define __ARMEL__ 1
#define __ARM_32BIT_STATE 1
#define __ARM_ACLE 200
#define __ARM_ARCH 7
#define __ARM_ARCH_7A__ 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH_PROFILE 'A'
#define __ARM_EABI__ 1
#define __ARM_FEATURE_CLZ 1
#define __ARM_FEATURE_DSP 1
#define __ARM_FEATURE_LDREX 0xf
#define __ARM_FEATURE_QBIT 1
#define __ARM_FEATURE_SAT 1
#define __ARM_FEATURE_SIMD32 1
#define __ARM_FEATURE_UNALIGNED 1
#define __ARM_FP 0xc
#define __ARM_FP16_ARGS 1
#define __ARM_FP16_FORMAT_IEEE 1
#define __ARM_NEON 1
#define __ARM_NEON_FP 0x4
#define __ARM_NEON__ 1
#define __ARM_PCS 1
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_SIZEOF_WCHAR_T 4
#define __ARM_VFPV2__ 1
#define __ARM_VFPV3__ 1
#define __arm 1
#define __arm__ 1
```
```
$ ./aarch64-linux-android21-clang -E -dM - </dev/null | grep -i ARM
#define __ARM_64BIT_STATE 1
#define __ARM_ACLE 200
#define __ARM_ALIGN_MAX_STACK_PWR 4
#define __ARM_ARCH 8
#define __ARM_ARCH_ISA_A64 1
#define __ARM_ARCH_PROFILE 'A'
#define __ARM_FEATURE_CLZ 1
#define __ARM_FEATURE_DIRECTED_ROUNDING 1
#define __ARM_FEATURE_DIV 1
#define __ARM_FEATURE_FMA 1
#define __ARM_FEATURE_IDIV 1
#define __ARM_FEATURE_LDREX 0xF
#define __ARM_FEATURE_NUMERIC_MAXMIN 1
#define __ARM_FEATURE_UNALIGNED 1
#define __ARM_FP 0xE
#define __ARM_FP16_ARGS 1
#define __ARM_FP16_FORMAT_IEEE 1
#define __ARM_NEON 1
#define __ARM_NEON_FP 0xE
#define __ARM_PCS_AAPCS64 1
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_SIZEOF_WCHAR_T 4
```
