### ISSUE TITLE
vboxwrapper unnecessarily disables VirtualBox hardware acceleration on nested vm's

### ISSUE THREAD

**Issue by pbellchambers** [BOINC/boinc#3598]
**Describe the bug**
When running boinc inside a vm that has virtualbox installed (i.e. a nested vm), even if virtualbox on this vm supports hardware acceleration the following code in vboxwrapper deliberately disables it, thus preventing tasks that would otherwise run from being able to do so:

line 376 in: **samples/vboxwrapper/vbox_vboxmanage.cpp**
```
        if (strstr(aid.host_info.p_features, "hypervisor")) {
            vboxlog_msg("Running under Hypervisor. Disabling VirtualBox hardware acceleration support.");
            disable_acceleration = true;
        }
```

**Steps To Reproduce**
I am using google cloud compute for this:
1. Setup an ubuntu vm on google cloud compute with nested virtualisation enabled: https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances
2. Confirm that it is enabled on the vm: `grep -cw vmx /proc/cpuinfo`
3. Install virtualbox on the vm
4. Install boinc
5. Connect to a project that has virtualbox based tasks
Result:
6. These tasks fail with the following errors in the log for the task:
> Running under Hypervisor. Disabling VirtualBox hardware acceleration support.
> ERROR: Invalid configuration.  VM type requires acceleration but the current configuration cannot support it.

It is untrue that the current configuration cannot support it.

See example failed task:
https://www.cosmologyathome.org/result.php?resultid=28141538

And proof that such tasks do work on the same vm with nested hardware acceleration (I had to spoof the data in /proc/cpuinfo to remove the "hypervisor" flag, and it worked fine):
https://www.cosmologyathome.org/result.php?resultid=28142701

**Expected behavior**
vboxwrapper should not disable hardware acceleration support in virtualbox in cases where it _is supported_. Is there any reason why this check cannot be removed entirely, as presumably if virtualbox did not support hardware acceleration then it itself would fail anyway? Does vboxwrapper need to deliberately set it to fail?

**Screenshots**
n/a

**System Information**
 - OS: Ubuntu 19.10 on google cloud compute (N1 instance, 4 CPU's, 16 GB ram), with nested virtualisation enabled: https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances
 - BOINC Version: 7.16.3
 - Virtualbox version: 6.0.19

**Additional context**
n/a

**Comment by davidpanderson** [comment]
That check was added by @nikolasgianna of CERN here: https://github.com/BOINC/boinc/commit/9d8abbb5f033ae080cd99cbd9b28c34add355edf

**Comment by pbellchambers** [comment]
I think it was added much earlier than that. The earliest I could find from a cursory look was in samples/vboxwrapper/vbox_unix.cpp in 2014 (which appears to have been later refactored into the current file):
https://github.com/BOINC/boinc/commit/557c15dbf03f541f8eab21e1a3c9104813ecb7f5#diff-3cd3308aaa785965729c4a80d7ebe8ee

Also on a closer inspection, the check actually appears in two places in the current code:
https://github.com/BOINC/boinc/search?q=%22running+under+hypervisor%22&unscoped_q=%22running+under+hypervisor%22

Line 376 in samples/vboxwrapper/vbox_vboxmanage.cpp
Line 523 in samples/vboxwrapper/vbox_mscom_impl.cpp

**Comment by nikolasgianna** [comment]
As @pbellchambers  mentioned that check was not added by me. 

The two files mentioned are the two different interface implementations, COM for Windows and VBoxmanage for everything else (including Windows).

**Comment by AenBleidd** [comment]
@computezrmle, any chance you could handle this?

**Comment by computezrmle** [comment]
If a project distributes a VM that is configured as 64-bit vboxwrapper never disables hardware virtualization:
See:
https://github.com/BOINC/boinc/blob/76dffd0dda2ee7a7f881e3dd08c35edec497a504/samples/vboxwrapper/vbox_vboxmanage.cpp#L415-L431


LHC@home does not distribute 32-bit VMs any more.
If other projects do they may consider to switch to 64-bit guests.


Beside that nested hardware-virtualization on Intel requires at least VirtualBox 6.1.0 and a Broadwell CPU.
See:
https://www.virtualbox.org/wiki/Changelog-6.1

**Comment by AenBleidd** [comment]
@computezrmle, thank you for investigation.

I see no reason to distribute 32-bit VMs in 2022 but if some Projects do that - there should be a reason for that and thus 'disabling hardware acceleration' might be essential for them as well.
Since this is done via configuration file and hot automatically in VBoxWrapper - I see no reason to fix this.
If some Project still uses 32-bit VM and has this option in their configuration file - such a Project should be informed via their forum.
Closing this as 'wontfix'
