### ISSUE TITLE
The project lacks clear and prescriptive instructions

### ISSUE THREAD

**Issue by noloader** [BOINC/boinc#3602]
Hi Everyone,

Here's a feedback item. The project might want to treat it as a feature request.

I tried to donate spare computing cycles to the BIONC seti@home project.  First I went to https://boinc.berkeley.edu/. There are pages of information, but no clear and prescriptive instructions. I expected to have a set of instructions like:

1. download client at xxx
2. start the linux client using xxx command
3. verify the client is running with xxx command

Simple, clear and prescriptive instructions are missing.

Another page is https://boinc.berkeley.edu/download.php. That suggests I setup a virtual machine, and then go read a manual. Again, missing simple, clear and prescriptive instructions.

I then went to Debian's page at https://wiki.debian.org/BOINC. I was able to get as far as installing some packages, but I don't know if they installed properly or the programs were running. A simple search for "determine if seti@home is running" turned up spurious noise. Again, missing simple, clear and prescriptive instructions.

At this point I have wasted about 30 minutes of my time trying to figure out how to donate to the project. My next step will be to remove the project packages.

In the future, if you really want people to help, then remove all the barriers. Provide simple, clear and prescriptive instructions. Don't waste hours of my time telling me to read man pages, and don't waste hours of my time telling me to rummage through manuals and web pages.

In the bigger picture, you should probably stop engineers from writing manuals and web pages.  This is the result when you allow engineers to do non-technical things. They screw it up every time because they lack UX training. Instead, you should have someone with UX training and experience do it.

The perplexing part (to me) is, Berkely has an [Information Systems](https://www.ischool.berkeley.edu/programs/mims) program. The program is full of UX expertise who can help with the usability problems. Why hasn't the project tapped their expertise?

**Comment by Ageless93** [comment]
You went to https://boinc.berkeley.edu/ but didn't see the "User Manual" link there, second item under Learn More? You could also have filled in "Install BOINC" in a search engine. I tried both Google and Bing and both give the link to https://boinc.berkeley.edu/wiki/Installing_BOINC, which coincidentally is the User Manual. 

Berkeley has nothing to do with Seti or BOINC, other than that the servers are stored there. Both BOINC and Seti are driven by volunteers only.

**Comment by davidpanderson** [comment]
Um, actually both the SETI@home and BOINC projects are based at UC Berkeley.

**Comment by Ageless93** [comment]
I know that David, but it's not what I meant. Both Seti and BOINC may be
based at Berkeley, but afaik Berkeley doesn't give any help in programming
BOINC or Seti - which is what the OP went for - or it must be done by
volunteers from Berkeley who do this on their own accord. And I said that
the servers are stored there - and obviously run from there seeing the URL
addresses saying so.

-- Jord van der Elst.

**Comment by davidpanderson** [comment]
Staff of SETI@and BOINC are UC Berkeley employees.  Please check with me before making statements about these projects.

**Comment by smoe** [comment]
I am happy to hear that you found the BOINC Wiki pages. I'll get my mind straight about how we could be more friendly to those who googled into that for whom this may be their first encounter with BOINC and volunteer crunching in general. I am not exactly sure if you have any question left for me (or someone else) to answer.

@davidpanderson - are there youtube videos for people to follow? I am sure there are. Maybe the download page could point to one or two of them.  As someone working with the command line a lot and who is prefering the old interface of the boinc manager over the new stylish one, I am afraid I happily disqualify myself from commenting on UX concerns.

@noloader - nice space invaders pic! With such credentials - you must have been asking for a friend.

**Comment by smoe** [comment]
Added a mini-instruction that should answer your questions on https://wiki.debian.org/BOINC. For more, if you think this makes a difference to the world - please come up with something yourselves that would have helped you in your first encounter. For any of the folks reading these issues this is really, really difficult.
