### ISSUE TITLE
Server counts aborts/detached as errors

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#361]
**Reported by ohiomike on 17 Sep 37645784 08:53 UTC**
With workunit settings : max # of error/total/success results 2, 3, 3 minimum quorum 2 initial replication 2.
If 2 users abort the WU or detach from the project, the people that have completed the WU lose their work. If it possible to:
1) Not count aborts/detached as errors?
or
2) Subtract completed from errors (if 1 result is complete, 3 errors would be allowed)?  

Migrated-From: http://boinc.berkeley.edu/trac/ticket/378

**Comment by ChristianBeer** [comment]
This should be the case already in current servercode.
