### ISSUE TITLE
Close to tray on Linux

### ISSUE THREAD

**Issue by LinAGKar** [BOINC/boinc#3638]
**Describe the problem**
Currently, boinc-manager does not have a tray icon, so closing the window closes boinc-manager completely, and for some reason it takes boinc-client with it, even though boinc-client is lanched as a systemd service. Thus, using boinc requires having the boinc-manager window open at all times.

**Describe the solution you'd like**
Boinc-manager should have a tray icon, and keep running in the tray when the window is closed.

**Comment by AenBleidd** [comment]
https://github.com/BOINC/boinc/pull/3052

**Comment by AenBleidd** [comment]
I'm closing this because of the reasons mentioned in #3052
