### ISSUE TITLE
Exiting boinc-manager stops boinc-client service

### ISSUE THREAD

**Issue by LinAGKar** [BOINC/boinc#3639]
**Describe the bug**
When you exit boinc-manager, it stops boinc-client, even if boinc-client was not started by boinc-manager.

**Steps To Reproduce**
1. Start boinc-client as a systemd service.
2. Start boinc-manager
3. Exit boinc-manager

**Expected behavior**
boinc-client keeps running.

**System Information**
 - OS: OpenSUSE Tumbleweed
 - BOINC Version: 7.16.3

**Comment by AenBleidd** [comment]
https://github.com/BOINC/boinc/pull/3052

**Comment by LinAGKar** [comment]
That one states that boinc-client keeps running when exiting boinc-manager, which is not the case.

**Comment by AenBleidd** [comment]
https://github.com/BOINC/boinc/pull/3094

**Comment by AenBleidd** [comment]
BOINC Manager can't kill the client if it's run as a service on Linux

**Comment by LinAGKar** [comment]
It does though. When I stop the manager, the client exits. It doesn't look like it kills it directly though, there is nothing in the log about it getting a signal, like there is is I run kill.

**Comment by RichardHaselgrove** [comment]
It may be a problem introduced by the distro package maintainers. The raw BOINC code (as seen in the new self-extracting archive available at https://boinc.berkeley.edu/download_all.php) produces a different Manager from the one the Linux packagers are producing.

**Comment by LinAGKar** [comment]
Possibly, though I did try replacing the manager and client binaries with ones I built from source, which fixed the idle detection, but it did not fix this issue, so then the problem must be in some other file.

**Comment by Germano0** [comment]
@AenBleidd 
> #3094
has been reverted. 
@LinAGKar I created [this patch](https://src.fedoraproject.org/rpms/boinc-client/blob/master/f/manager_close_no_service_stop.patch) time ago for Fedora / CentOS / RHEL to avoid Manager stopping BOINC client service when user closes the Manager.
You may want to ask the OpenSUSE package maintainer to give a look to all the patches I created. Comments are at
https://src.fedoraproject.org/rpms/boinc-client/blob/master/f/boinc-client.spec
