### ISSUE TITLE
General improvement for ARM platform

### ISSUE THREAD

**Issue by truboxl** [BOINC/boinc#3657]
**Describe the problem**
Split off from https://github.com/BOINC/boinc/issues/3596#issuecomment-616013774
Maybe will find some time for PR, here are just some initial plans

Currently benchmark optimisation has been limited to specifically 32bit ARM Android platform. Suggest update the sources to allow all ARM platform (arm and aarch64 / arm64) to benefit from the same optimisation.

https://github.com/BOINC/boinc/commit/7b2ca9e787a204f2a57f390bc7249bb7f9997fea will be a starting point.

**Describe the solution you'd like**
EDIT: see linked PR for reference. Note that the linked PR is outdated. aarch64 checking code can be removed since its assumed to have NEON always.

**Additional context**
This commit https://github.com/BOINC/boinc/commit/e3fa4ce5567bf4ef36d62325121f9e962912039e seems to suggest not to use NEON in aarch64. Why though? [All ARMv8 devices (and by extension aarch64) ship with NEON.](https://developer.android.com/ndk/guides/cpu-arm-neon) Yes there are 32bit ARMv8 out there.

Android NDK 21 also compiles with NEON (see above link) and [PIE](https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#additional-required-arguments) by default. Maybe time to drop some workaround like Cortex-A8 (Galaxy S) as I don't see them capable running Android 4.1.

https://github.com/BOINC/boinc/issues/1702

https://github.com/magnumripper/JohnTheRipper/issues/1998

EDIT: Changed some parts

**Comment by talregev** [comment]
> Cortex-A8 (Galaxy S) as I don't see them capable running Android 4.1.

I am running old devices with new android. 
for example on galaxy gio and galaxy pop+ , i put android 4.4
and galaxy s2 i put android 7.2

Why if you switch to Android NDK 21 it will stop support android 4.4 and above?

**Comment by truboxl** [comment]
While its true older phone can be flashed with custom ROM with newer Android version allowing them to run newer apps,
you can't deny that they are usually paired with very very small RAM.
WCG for example straight up stops you from running tasks if they find that the device don't have enough RAM for the tasks to run.
The oldest phone with its official stock ROM that I have that can run WCG is Galaxy S Advance with 768MB RAM but really just 512MB free. So a rule of thumb is anything lesser than 1GB RAM devices really aren't worth to do work these days.

NDK 21 currently provides compile tools for use as far API 16 (4.1). So its not possible to build BOINC for even older Android version unless using older NDK.
The beta Android client has moved on to 4.4 as minimum, so some people may no longer able to download from Google Play.
It's possible to bring it back down to 4.1 if anyone is willing to:
backport the features (eg: device name change!),
maintain large amount of workarounds and
ensure compatibility across different versions of Android from 4.1 to 10
since the actual minimum requirement is device needs to be able to run Position Independent Executable (Android 4.1+)

**Comment by talregev** [comment]
> The beta Android client has moved on to 4.4

For me 4.4 is fine.

**Comment by Isira-Seneviratne** [comment]
> backport the features (eg: device name change!),

Why does it need to be backported?

**Comment by truboxl** [comment]
@Isira-Seneviratne I was under the impression this isn't something that can work on older Android version, but I guess I was wrong

**Comment by talregev** [comment]
We now doing the effort to support android 4.4
Older version will be still tricky: (4.1 and armv6 phone). 
NDK 21 will support all of this. We will switch soon.

**Comment by truboxl** [comment]
In light of Apple's announcement, its worth to revisit this idea again. However from my testing the current benchmark (with NEON enabled) does not scale well with big.LITTLE cores and you will end up with an inverse scale. For example, my 2+6 cores phone scales up from 1-2 cores but drops exponentially starting with 3.

**Comment by talregev** [comment]
We already support android 4.1 and above (api 16).  And it possible to compile our code with ndk 21 with a little effort. 
But we don't have code for ios at all. So you think our mac code will be good for iphone?

**Comment by talregev** [comment]
@truboxl I am not sure why you re-open this issue.

**Comment by talregev** [comment]
Also arm64 are compile with neon by default.

**Comment by talregev** [comment]
And I think there is not neon optimization for x86 or x86_64. correct me if I wrong.

**Comment by truboxl** [comment]
> But we don't have code for ios at all. So you think our mac code will be good for iphone?

Possibly. Since mac apps can run on iOS with changes nowadays. But BOINC is not on mac App Store anyway so iOS port is unlikely. If there is a mac with big.LITTLE configuration, the benchmark will not reflect its performance.

Unfortunately, Android GUI does not have ondemand run CPU benchmarks option so testing will be hard.

> Also arm64 are compile with neon by default.

arm_neon.h is not included therefore no neon code was produced for aarch64 I think. I will do more digging.

> And I think there is no neon optimization for x86 or x86_64. correct me if I wrong.

https://github.com/BOINC/boinc/search?q=intrin.h&unscoped_q=intrin.h
