### ISSUE TITLE
Sporadic BSOD in Win7 SP1 on Snooze

### ISSUE THREAD

**Issue by daniel-starke** [BOINC/boinc#3668]
**Describe the bug**
Sometime, I experiene a Blue Screen of Death when I hit snooze in the systray context menu of the BOINC Manager.

**Steps To Reproduce**
1. Run Rosetta@home
2. Do Snooze

**Expected behavior**
No blue screen.

**Screenshots**
See attached [bsod.txt](https://github.com/BOINC/boinc/files/4564032/bsod.txt).

**System Information**
 - OS: Microsoft Windows 7 SP1 (6.1.7601.24540)
 - BOINC Version: 7.16.5

**Additional context**
None.

**Comment by AenBleidd** [comment]
Please attach minidump

**Comment by daniel-starke** [comment]
minidump: [050120-30888-01.zip](https://github.com/BOINC/boinc/files/4564084/050120-30888-01.zip)

**Comment by AenBleidd** [comment]
It's hard to say what was the reason of this issue.
Anyway, Win7 is not supported by Microsoft anymore.
Also, since then there were a lot of changes in the BOINC codebase.
Closing this issue for now.
