### ISSUE TITLE
Compile android ndk on windows.

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#3669]
This template is for miscellaneous issues not covered by the other issue categories.
I am using windows 10. Download msys64 for support sh and more linux command.
I modified the script and compile, but I have some issue, and I have questions:

My current issue, when it try to compile boinc for arm, it didn't recognize 'pkg-config'. but in the visual studio is download it and compile it. in  $ boinc\3rdParty\Windows\vcpkg. 

1. Why in the script it say no for compile openssl and curl? 
2. How you compile android ndk on windows?
3. Can we transform these scripts to cmake scripts? 
Android studio will compile and download all relevant 3rdparty, like openssl and curl and dpkg. All compilation will be inside android studio no matter your os.
4. Can you publish compiled ndk binaries for android studio? (arm, arm64, x86, x64 platform) for 7.6.15 or 7.6.16?

https://developer.android.com/ndk/guides
https://developer.android.com/studio/projects/add-native-code

**Comment by talregev** [comment]
We can keep boinc with current build system. 
We can convert the openssl and curl and pkg-config scripts that will download and recognized by boinc build system using cmake.
If I will give it the correct pkg-config folder, it will work?

**Comment by AenBleidd** [comment]
@talregev, I suggest you to instal WSL and compile BOINC for Android there

**Comment by talregev** [comment]
I will try. any pre install need inside wsl?

**Comment by AenBleidd** [comment]
Yes. Mainly all necessary packages that is required to build on linux

**Comment by AenBleidd** [comment]
> 1. Why in the script it say no for compile openssl and curl? 

It is done to optimize CI build that uses cache. By default, openssl and curl are building.

> 2. How you compile android ndk on windows?

Personally I use preconfigured linux VM

> 3. Can we transform these scripts to cmake scripts? 
> Android studio will compile and download all relevant 3rdparty, like openssl and curl and dpkg. All compilation will be inside android studio no matter your os.

I see no reason for this. You have to transform linux version then too

> 4. Can you publish compiled ndk binaries for android studio? (arm, arm64, x86, x64 platform) for 7.6.15 or 7.6.16?

By default they are published here: https://boinc.berkeley.edu/dl/

**Comment by talregev** [comment]
It not working on wsl.
![wsl](https://user-images.githubusercontent.com/7043539/80833326-fe20ce80-8bf6-11ea-983a-565889782121.PNG)

**Comment by talregev** [comment]
> By default they are published here: https://boinc.berkeley.edu/dl/

Which binary i need to download? that ndk compile.

**Comment by talregev** [comment]
> It is done to optimize CI build that uses cache. By default, openssl and curl are building.

When I run the scripts, when it "no" it not compile, when I change to "yes" it compile the openssl and curl. 
So I didn't understand why it "no" on default.

**Comment by AenBleidd** [comment]
> It not working on wsl.

It's because you run linux command from Windows pulled repo.
You need inside WSL pull repo again.
The issue is with line endings:
- linux uses \n
- windows uses \r\n

**Comment by AenBleidd** [comment]
> Which binary i need to download? that ndk compile.

You mean build APK?
There is no another pre-compiled binaries

**Comment by talregev** [comment]
Thanks, I will try.

**Comment by talregev** [comment]
> You mean build APK?

No. build binaries for ndk. 
After you run the script: build_all.sh it produce ndk binaries for android. 
It possible to publish it there?  https://boinc.berkeley.edu/dl/

**Comment by AenBleidd** [comment]
> When I run the scripts, when it "no" it not compile, when I change to "yes" it compile the openssl and curl.
So I didn't understand why it "no" on default.

Where did you find 'no' by default?

>No. build binaries for ndk.
After you run the script: build_all.sh it produce ndk binaries for android.
It possible to publish it there? https://boinc.berkeley.edu/dl/

It's redundant. Built binaries for release versions are already inside APK. There is no reason to publish these binaries for non-release builds

**Comment by talregev** [comment]
> It's redundant. Built binaries for release versions are already inside APK. There is no reason to publish these binaries for non-release builds

It will be more easy for me, if I want only change java code inside android app.
I don't need to compile all ndk binaries, and start the compilation process more faster. 



> Where did you find 'no' by default?
> 
> >

in buildAndroidBOINC-CI.sh
line 125,126:
export COMPILEOPENSSL="no"
export COMPILECURL="no"

**Comment by AenBleidd** [comment]
> buildAndroidBOINC-CI.sh

Suffix 'CI' supposed to tell that it is for CI ;)

**Comment by talregev** [comment]
inside build_all.sh script:
It using only CI:
```bash
./buildAndroidBOINC-CI.sh --cache_dir "$ANDROID_TC" --build_dir "$HOME/3rdParty" --arch arm
./buildAndroidBOINC-CI.sh --cache_dir "$ANDROID_TC" --build_dir "$HOME/3rdParty" --arch arm64
./buildAndroidBOINC-CI.sh --cache_dir "$ANDROID_TC" --build_dir "$HOME/3rdParty" --arch x86
./buildAndroidBOINC-CI.sh --cache_dir "$ANDROID_TC" --build_dir "$HOME/3rdParty" --arch x86_64

```

So I don't understand my mistake.

**Comment by AenBleidd** [comment]
https://github.com/BOINC/boinc/blob/15f3aa6aa012c74f46b34bc9053f12c8c4f4ad29/android/buildAndroidBOINC-CI.sh#L141-L156

If flag files are not found, these variables are changed to 'yes'

**Comment by talregev** [comment]
Thanks. now I understand why it not working before.

**Comment by talregev** [comment]
I will close this issue, I success compile it on windows inside wsl.
typing:
```bash
$ sudo apt install git python make m4 pkg-config dh-autoreconf libmysqlclient-dev libssl-dev python-mysqldb  libnotify-dev

```
take it from here: 
https://boinc.berkeley.edu/trac/wiki/SoftwarePrereqsUnix
under ubuntu without the php5 software.
