### ISSUE TITLE
Rosetta@home now use HTTPS, Boinc list of projects doesn't

### ISSUE THREAD

**Issue by unguul** [BOINC/boinc#3687]
See https://boinc.bakerlab.org/rosetta/forum_thread.php?id=13894#95682 for more information

**Comment by AenBleidd** [comment]
@davidpanderson could you please fix this in all_projects_list.xml?

**Comment by unguul** [comment]
@AenBleidd Sorry, took me a minute to create the PR myself.

**Comment by AenBleidd** [comment]
This list is located in another place and is not synced with the one on GitHub. PR will have no effect

**Comment by unguul** [comment]
@AenBleidd Oh. My bad then. I'll close the PR. Thanks for letting me know.

**Comment by davidpanderson** [comment]
I updated all_projects_list.xml

**Comment by unguul** [comment]
I think we can close this as there's already #3496 which I missed and https://github.com/BOINC/boinc/pull/3688#issuecomment-624855566.
