### ISSUE TITLE
Linux Host O/S Platform Display

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#369]
**Reported by ohiomike on 2 May 37671366 17:46 UTC**
It would be nice if the /show_host_detail.php pages showed the version of Linux running, instead of just "Linux". ie- Linux i386, Linux x86_64, etc. There is currently no way to tell if a host is running 32 or 64 bit Linux on a HR project.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/386

**Comment by romw** [comment]
**Commented by Rytis on 5 Sep 37671395 08:00 UTC**
It's what the client reports, so it's not related to web site. Changing component.

**Comment by ChristianBeer** [comment]
fixed in #1562
