### ISSUE TITLE
Client scheduler incorrectly calculates free disk space

### ISSUE THREAD

**Issue by KenSharp** [BOINC/boinc#3706]
The client seems to correctly calculate disk usage and free space using get_host_info(), but the scheduler calculates these details again using get_disk_usages(). The former correctly calculates the free disk space, the latter does not.

get_disk_usages() simply counts the amount of data in the data directories. This is then compared to the total size of the disk. The result is an incorrect calculation of remaining disk space.

Counting the "data" as opposed to the actual disk usage cannot account for compression, deduplication, or any other magic.

For example:

BOINC is storing 10 GB of data on a 20 GB partition.
The data compresses well and uses only 5 GB disk space.
get_host_info() reports that there is 15 GB of disk space available.
get_disk_usages() reports that there is 10 GB of disk space available.

In my case, I saw a dramatic reduction of disk space thanks to compression and deduplication, but on scheduler request the server reported that there was not enough space on the drive. In fact there was plenty.

[Took my tiny brain a while to see what was going on.](https://boinc.berkeley.edu/forum_thread.php?id=13662)

 - OS: Ubuntu Linux 20.04 (5.4.0-1009-gcp)
 - BOINC Version: 7.16.6+dfsg+202004191509~ubuntu20.04.1
 - Filesystem: BTRFS

I can only assume that this will be an issue for any filesystem that supports compression, deduplication, hardlinking, etc. Which is a lot of systems.

Setting up a VM on a cloud provider, one tends to use as few resources as possible because every little thing costs extra. During the COVID-19 pandemic I have set up VMs with many processors, lots of RAM and as little disk space as I can get away with to simply crunch COVID-19-related work units. Deduplication and compression has helped here. Unfortunately BOINC does not want to play ball.

**Comment by davidpanderson** [comment]
Thanks for finding this.  I'll check in a fix shortly.

**Comment by Vulpine05** [comment]
Apologizes for my lack of knowledge, but I would like to point you to [#3344](url=https://github.com/BOINC/boinc/issues/3344), which although unrelated, may be grabbing incorrect disk usage as well?

**Comment by davidpanderson** [comment]
That issue involves the display of data, not the data itself.
