### ISSUE TITLE
Text clipped on macOS upon app launch

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3713]
The bug goes away when I switch focus away from the window. Strangely enough, it also goes away when I take a screenshot, so I had to take a picture of my screen to show the issue.

- macOS 10.15.5 Beta (19F83c)
- BOINC Manager version 7.16.6
- wxWidgets version 3.1.0

![IMG_0601](https://user-images.githubusercontent.com/1305957/81901289-230c2e80-9573-11ea-864e-176ae095de8e.jpeg)

**Comment by CharlieFenton** [comment]
Not only the text but also the popup menu above it have not been drawn. I can't reproduce this on OS 10.15.4.
> The bug goes away when I switch focus away from the window. Strangely enough, it also goes away when I take a screenshot,

I notice you are running a beta version of OS 10.15.5. This behavior makes me suspect this might be a refresh / drawing bug in the OS 10.15.5 beta.

**Comment by AustinConlon** [comment]
Filed this in Feedback Assistant to Apple (FB7702325).

**Comment by AenBleidd** [comment]
@AustinConlon, is this still an issue?

**Comment by AenBleidd** [comment]
Since there was no any updates on this during last year, closing as 'works for me'.
