### ISSUE TITLE
SRBase broken link

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3728]
SRBase is one of the preselected projects in BOINC Manager, and its link is broken: http://srbase.my-firewall.org/sr5/.

**Comment by RichardHaselgrove** [comment]
Not strictly BOINC Manager, but the all_projects_list which also drives https://boinc.berkeley.edu/projects.php

From there, the same link works, but reports that the project is down for maintenance.

**Comment by Rytiss** [comment]
The link is valid, their server had crashed on May 17 when this issue was posted.
