### ISSUE TITLE
Delay computation until computer has completed startup processes

### ISSUE THREAD

**Issue by GregVernon** [BOINC/boinc#3738]
**Describe the problem**
I have enough cores to often be using my computer at the same time as I'm running multiple BOINC tasks in the background.  My Win10 computer has a small amount of startup processes, but after updates or restarts with multiple apps open (e.g. dozens of browser tabs) it can take a while to restart these apps.  It takes longer when BOINC restarts and starts computation immediately on tasks.

**Describe the solution you'd like**
It would be nice to have an option to delay computations until startup processes have completed, or until a certain amount of time has passed since the restart (whichever's smaller).  This would allow the computer the resources it needs to startup quickly, then immediately dive into the user's compute preferences.

**Comment by davidpanderson** [comment]
See the <start_delay> option:
https://boinc.berkeley.edu/wiki/Client_configuration#Options

**Comment by techsy730** [comment]
While you could probably rig up something fancy depending on your service manager you have installed, I think <start_delay> is close enough for most use cases that I don't think any dev time is needed for something more involved.

**Comment by GregVernon** [comment]
Which of these options does this?
![image](https://user-images.githubusercontent.com/868479/83566908-f6966300-a4dd-11ea-9cf1-277a89e30925.png)

**Comment by RichardHaselgrove** [comment]
See the related discussion on the Linux systemd case in #3150

**Comment by RichardHaselgrove** [comment]
@GregVernon: start_delay is a cc_config.xml option

https://boinc.berkeley.edu/wiki/Client_configuration

**<start_delay>nseconds</start_delay>**
Specify a number of seconds to delay running applications after client startup.

**Comment by GregVernon** [comment]
Ah, gotcha.  Thanks for the help :)  I'm going to close the issue.
