### ISSUE TITLE
Team description should use BBCode

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#374]
**Reported by Rytis on 3 Jun 37679728 13:20 UTC**
Team description should use BBCode (it's currently using HTML); when creating, also provide a converter to migrate HTML --> BBCode.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/391

**Comment by romw** [comment]
**Commented by Didactylos on 29 Mar 37680374 04:26 UTC**
Is there any particular reason for this? BBCode is for forums - and, frankly, low quality. HTML is an official standard. Why change?

**Comment by romw** [comment]
**Commented by John37309 on 31 Oct 37895208 17:20 UTC**
Replying to [Didactylos](comment:1):
> Is there any particular reason for this? BBCode is for forums - and, frankly, low quality. HTML is an official standard. Why change?

Because the vast majority of team founders do not know html

This is what most BOINC team pages look like;
http://setiathome.berkeley.edu/team_display.php?teamid=50536

With BB code or a rich text editor, team pages could look like my profile;
http://setiathome.berkeley.edu/view_profile.php?userid=8478945

John37309/Johnney Guinness

**Comment by romw** [comment]
**Commented by DeadJDona on 25 Oct 39107624 15:06 UTC**
Replying to [John37309](comment:2):
> Because the vast majority of team founders do not know html

Lack of someone intelligence not a BOINC problem.

> This is what most BOINC team pages look like;
> http://setiathome.berkeley.edu/team_display.php?teamid=50536
> 
> With BB code or a rich text editor, team pages could look like my profile;
> http://setiathome.berkeley.edu/view_profile.php?userid=8478945

Oh man! I prefer first variant.

**Comment by ChristianBeer** [comment]
It's a lot of hassle to migrate from HTML to BBCode and even BBcode is not very convenient.
