### ISSUE TITLE
"This project is using an old URL." notices persist in BOINC client.

### ISSUE THREAD

**Issue by AG5BPilot** [BOINC/boinc#3744]
When a project changes its URL, typically from http: to https:, you get a notice informing you that you should detach from the project and then add the project using the new URL.  This is shown in the "Notices" tab in the BOINC manager.  The exact message is "This project is using an old URL. When convenient, remove the project, then add <URL>".

When you detach and re-add the project, the message still is shown in the BOINC manager.  Closing the BOINC manager doesn't clear the message.  Closing the BOINC client will clear the message.

**Steps To Reproduce**
1. Have a message on a project saying that you need to change the URL.  If you don't currently have such a message, you *might* be able to create this scenario by attaching with http: instead of https:.  I'm not really certain if that will work, and it might depend on the apache configuration on the server.  
2. When you have the message in your notices, detach from the project.
3.  Add the project, using the new, correct, URL.
4. Observe that the notice about having a new URL is still present in the BOINC manager.

**Expected behavior**
After attaching with the correct URL, the notice should no longer show in the BOINC manager, or be reported by the BOINC client to an alternate manager such as BOINCTasks.

**System Information**
 - OS:  Windows 10
 - BOINC Version: 7.14.2

**Comment by davidpanderson** [comment]
Or better, not show the notice in the first place; I'll work on that.

**Comment by CharlieFenton** [comment]
Would it be possible for the client to automatically fix the URL (changing _http:_ to _https:_) instead of showing the message?
