### ISSUE TITLE
Mac App Store

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3745]
Could BOINC Manager be distributed on the [Mac App Store](https://developer.apple.com/app-store/mac/)? This would mean more exposure to more people and simplify the updating process for the user.

**Comment by CharlieFenton** [comment]
The Manager by itself is not useful. The installer must also include the BOINC client and, ideally, the BOINC screensaver. I don't think the client would meet Apple's guidelines for the Mac App store (it downloads project executables, for example.)

**Comment by AustinConlon** [comment]
Ah okay, thought it was in one app. I was guessing Mac App Store review would be more lenient than for their other platforms, but not sure about their policy for executables on macOS.
