### ISSUE TITLE
Interactive editor for BBCode

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#375]
**Reported by Rytis on 11 Feb 37679749 10:13 UTC**
All places that have BBCode editing should have at least a simple !JavaScript based editor (WYSIWYG would be better).

Migrated-From: http://boinc.berkeley.edu/trac/ticket/392

**Comment by romw** [comment]
**Commented by Nicolas on 22 Apr 40414076 10:13 UTC**
Isn't this done already?

**Comment by romw** [comment]
**Commented by Rytis on 15 Aug 40414105 10:40 UTC**
Basic editor is implemented, WYSIWYG would be nice though.

**Comment by ChristianBeer** [comment]
I don't know of any WYSIWYG BBCode editor. There are a lot for HTML availabel and some can convert BBCode to HTML but since we store BBCode not HTML this is not helpful.
