### ISSUE TITLE
Drop building switcher binary everywhere in Makefiles

### ISSUE THREAD

**Issue by truboxl** [BOINC/boinc#3751]
Probably a very low priority for cleaning up the Makefiles.
Need checking with projects.
Probably need a Mac to test...

Previous discussion:
https://github.com/BOINC/boinc/pull/2780
https://github.com/BOINC/boinc/issues?q=mac+switcher

**Comment by RichardHaselgrove** [comment]
I was surprised to find a switcher in the **Linux** client output CI build I tested four days ago

https://bintray.com/beta/#/boinc/boinc-ci/pull-requests/PR3709_2020-05-18_745e5056?tab=files
