### ISSUE TITLE
Make BOINC service start Automatic (delayed start).

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#376]
**Reported by Ageless on 12 Oct 37682277 19:33 UTC**
As requested by Tank Master on the [BOINC forums](http://boinc.berkeley.edu/dev/forum_thread.php?id=1943&nowrap=true#12319):

"With a service install in vista (perhaps in BOINC version 6), can it be installed as "Automatic (delayed start)" instead of "automatic"? This will hold off starting the service until all the regular services have loaded, thus reducing the impact on the system when rebooting or from turning it on. Also, you can further reduce system impact in Vista by having the BOINC apps run with "low I/O priority" and "low memory priority". This will give greater priority to tasks the system and the user are running. Lastly, is it possible to have the task auto restart if it unexpectedly stops? I see it as an option that you can manually set, but I do not know if programs can set this when they are installed."

[Additional post](http://boinc.berkeley.edu/dev/forum_thread.php?id=1943&nowrap=true#12325):

"I do have an issue with the delayed start on some of the older systems that auto log in when the comp starts up. If I have the BOINC manager to start when I log in, the service is not always running yet because other services are still loading. In this case, the manager will manually launch the BOINC process like it was installed as a single user. This is why I suggested using it with BOINC v6 for a service install is the only option and the manager can be rewritten to take that into accordance by not launching BOINC on its own."

Migrated-From: http://boinc.berkeley.edu/trac/ticket/393

**Comment by romw** [comment]
**Commented by Ageless on 15 Oct 37682282 12:26 UTC**
Not sure if David was the person to assign it to, so reassigning to Rom.

**Comment by romw** [comment]
**Commented by romw on 16 Oct 40859060 19:06 UTC**
Setup bugs are being punted to a future release.  This work item should be completed with the new open source installer.

**Comment by ChristianBeer** [comment]
There is an option to delay starting science apps via config.xml. This should be adjustable via the Manager but that is not part of this issue.
