### ISSUE TITLE
schema.sql and constraints.sql not working

### ISSUE THREAD

**Issue by longtomin** [BOINC/boinc#3773]
**Describe the bug**
the provided schema.sql creates the tables, the contraints.sql is adding the indicies.
The team table is created with the engine InnoDB, the contrains.sql gives this error message:
Error Code: 1178. The storage engine for the table doesn't support descending indexes

After removing the engine=InnoDB statement from the schema.sql I get this error message:
Error Code: 1795. InnoDB presently supports one FULLTEXT index creation at a time

**Steps To Reproduce**
1. Create a new MySQL database
2. run the schema.sql script.
3. run the constraints.sql script.

**Expected behavior**
Both scripts should run without error one time at the setup of the BOINC server.

**System Information**
 - OS: 
 - BOINC Version: 7.17

**Comment by longtomin** [comment]
Workaround:
1. remove all engine statements in the schema.sql, let MySQL decide what is the best to store the information.
2. comment the alter team in the constraints.sql out and run it after the schema.sql against the empty database.

Question: Should there be a sql script which is removing everything like drop table if exists XYZ?

**Comment by davidpanderson** [comment]
What version of MySQL?

**Comment by longtomin** [comment]
Select @@version; returns '8.0.20-commercial'

**Comment by davidpanderson** [comment]
What does mysql --version (on the command line) say?

**Comment by longtomin** [comment]
Hello, the linux boinc server says mysql  Ver 15.1 Distrib 5.5.65-MariaDB, for Linux (x86_64) using readline 5.1
But we have the database on a separate server within a cluster, so the boinc server itself is not hosting the mysql instance. And we accessed the database with a MySQLWorkbench from a windows client machine with the version 8.0 8.0.19 build 15713499 CE (64 bits) Community.
We run the two scripts from the windows client with the MySQLWorkbench and got these errors.

**Comment by longtomin** [comment]
Hello,

the two fulltext indicies are the problem within the constraints.sql script.
Change it to this did the trick:

alter table team
    add unique(name),
    add fulltext index team_name_desc(name, description),
    -- add fulltext index team_name(name),
    add index team_avg (expavg_credit desc),
        -- db_dump.C
    add index team_tot (total_credit desc),
        -- db_dump.C
    add index team_userid (userid);
	
-- 2nd Index created separately, as InnoDB does not allow to create more than one fulltext index at a time.

alter table team add fulltext index team_name(name);

**Comment by davidpanderson** [comment]
Current MySQL supports descending indices.
Please upgrade your server.
