### ISSUE TITLE
boinccmd tool, please add "retry all transfers" option

### ISSUE THREAD

**Issue by IanSteveC** [BOINC/boinc#3774]
**Describe the problem**
the boinccmd tool currently only allows you to retry transfers one by one, and you need to specify the project and exact filename for each one. that is very tedious. 

**Describe the solution you'd like**
BOINC manager has a dropdown selection to "retry all transfers", which retries all pending transfers regardless of name or project. I would like the same functionality to be added to boinccmd. 

**Additional context**
this will make scripting an automated retry command to all stuck transfers much easier without having to parse each filename and pass commands one by one, and especially for those who do not run a GUI and/or cannot use BOINC manager.

**Comment by cwallbaum** [comment]
Hi @IanSteveC,

"Tools" -> "Retry pending transfers" corresponds to

```# boinccmd --network_available```

From the manpage:

```
--network_available
    Tell the client to retry deferred network communication
```

And yep, I think that this nomenclature is very misleading...

walli

**Comment by hucker75** [comment]
Sorry to reopen this, but I've started using this successfully until I realised running this command makes Boinc forget the wait time the project has required before I can ask for new tasks, so Boinc is hammering servers for new work and never getting any as it's too annoying.  Please make this command not cause forgetting of wait time.
