### ISSUE TITLE
[Windows][Linux][Mac][Android] Unify icon in all platforms of Boinc 

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#3775]
> **Describe the problem**
> A clear and concise description of the problem you're looking to solve.

These days, each client had it own icon that represent boinc.

> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.

Need one icon that represent boinc for all clients for all platforms. 

> **Additional context**
> Add any other context or screenshots about the feature request here.

Tip: Don't close the ticket if you don't like the request.

**Comment by AenBleidd** [comment]
See no reason to update existing icons if they look ok on any particular OS.
If any OS generally changes requirements to the UI icons - we can adjust it separately.
Closing this ticket
