### ISSUE TITLE
[Bug][Windows] Disk tab advanced view in Hebrew show in mirror view. 

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#3822]
> **Describe the bug**
> A clear and concise description of what the bug is.

Disk tab advanced view in Hebrew show in mirror view.  Instead Right to left.
> **Steps To Reproduce**

1. Install boinc
2. Switch to Hebrew (I don't know how).
> **Expected behavior**
> A clear and concise description of what you expected to happen.

It show the disk in Hebrew in Right to left in correct way.

> **Screenshots**
> If applicable, add screenshots to help explain your problem.

![Disk-hebrew-bug](https://user-images.githubusercontent.com/7043539/84250012-28c64700-ab14-11ea-9081-159ed38f8a9a.PNG)
> **System Information**

 - OS: Windows 10 build 2004 (Yes with the new May 2020 update).
 - BOINC Version: 7.16.7

> **Additional context**
> Add any other context about the problem here.

Even that you don't understand the Hebrew letters, you can notice the few English letters that they in mirror view. I think this bug for all right left language that boinc support.

**Comment by AenBleidd** [comment]
Closed as a duplicate of #988
