### ISSUE TITLE
[Android v7.16.3] First implementation of battery prefs changes not initially sticking

### ISSUE THREAD

**Issue by bunnybooboo** [BOINC/boinc#3823]
**Describe the bug**
After almost 2 weeks of not ultilising my Android phone for BOINC I took the plunge into v7.16.3. I attempted to set it just as I had successfully using 7.4.53. Initially setting preferences did not seem to reflect WU progress hours later.

**Steps To Reproduce**
1. Download https://boinc.berkeley.edu/dl/boinc_7.16.3.apk
2. Enable "Install from unknown resources"
3. Enter credentials to connect to Rosetta@home project
4. Wait for benchmark tests to finish
5. I edited the following preferences:

    - deselect "Pause computation when screen is on" (I'm not a heavy phone user, tending to manually suspend only when required)
    - deselect "Transfer tasks on WiFi only"
    - Power sources for computation: select "battery" and press "Save"
    - Min. battery level: "10%"
    - Used CPU cores: "3" (device has 4)
    - Pause at CPU usage above: "70%"
    - RAM limit: "60%"

**Expected behavior**
I expected all these prefs changes to save. After 6 or so hours of battery enabled use I spotted WU progress was at best an additional 0.5%.

**System Information**
 - OS: Android 9 on LG G6 (H-870)
 - BOINC Version: 7.16.3

**Additional context**
I've since disabled the battery option. Saved. Enabled it again. Saved again. Seems to have finally resolved the issue. WU's are progressing as expected.

**Comment by bunnybooboo** [comment]
As an additional measure I have enabled in Android:

Settings >> Battery | Battery saver, Power saving exclusions >> Power saving exclusions >> BOINC (toggle ON)

**Comment by AenBleidd** [comment]
@bunnybooboo, yes, it's a known issue. Try to follow recommendations from here: https://boinc.berkeley.edu/wiki/Android_FAQ

**Comment by bunnybooboo** [comment]
Thanks for the heads up. I did resolve using this method previously in v7.4.53. It resulted in me not having to leave the device charged, implement a screensaver, or leave charging as recommended in the wiki. As I've had to install this new version to get past the security cert I thought to document what I did along the way this time. In case it might help get past this Android 9 limitation in a more functional way.

**Comment by randyfrisch** [comment]
Any plans to get BOINC working on Android again?!  I was running it on give devices before Cert-gate happened a month ago.  I'm sure we're losing out on a lot of distributed computing power.

**Comment by AenBleidd** [comment]
> Any plans to get BOINC working on Android again?! 

Yes

P.S. Even if you ask the same question in all tickets, this will not speed-up the process

**Comment by AenBleidd** [comment]
BOINC should work correctly when run an keep an foreground. Also it should be added to exclusion in battery optimization list
