### ISSUE TITLE
[Android v7.16.3] Expanding task renders it uncollapsible

### ISSUE THREAD

**Issue by bunnybooboo** [BOINC/boinc#3824]
**Describe the bug**
When navigating through to `Tasks` all downloaded tasks have `>` icon to expand individual tasks for more detailed information. Pressing it again does not close it.

**Steps To Reproduce**
1. Hamburger menu
2. Tasks
3. Select the `>` icon in the task list

**Expected behavior**
Open/close of task detail. Only open/expand is operational. Closing does not work

**System Information**
 - OS: Android 9 (LG H-870)
 - BOINC Version: 7.16.3

**Additional context**
Rectified by: Hamburger menu >> select another menu option >> hamburger menu >> tasks (all tasks are back to default display as closed)

**Comment by truboxl** [comment]
Duplicate of #3324
May take some time to get the fix out there in the future

**Comment by bunnybooboo** [comment]
Thanks @truboxl and apologies for not spotting that dupe. I've been searching but clearly not well enough.
