### ISSUE TITLE
Feature request: Vbox Only When Idle cc_config flag

### ISSUE THREAD

**Issue by Pichu0102** [BOINC/boinc#3839]
**Describe the problem**
Virtualbox tasks running in the background of a PC can cause sluggishness in response to input due to process priority issues as mentioned in https://github.com/BOINC/boinc/issues/2785. In addition, sometimes Virtualbox tasks will still cause sluggishness while in the background even if the user has manually changed VBoxHeadless process priorities via Task manager or some other method to Low.

**Describe the solution you'd like**
A solution that allows Virtualbox tasks to only run when the PC is idle, like GPUs can be set to only run when idle for a period of time, would be ideal for cases such as these.

**Additional context**
No other context.

**Comment by davidpanderson** [comment]
I added this to #2993

**Comment by AenBleidd** [comment]
Closed this as it should be implemented in scope with #2993
