### ISSUE TITLE
BOINC@TACC shows error message

### ISSUE THREAD

**Issue by jakobjakobson13** [BOINC/boinc#3850]
When the boinc connects to BOINC@TACC (`https://boinc.tacc.utexas.edu`) the following error gets reported: `BOINC@TACC | This project is using an old URL.  When convenient, remove the project, then add http://boinc.tacc.utexas.edu/` .

**Comment by AenBleidd** [comment]
@jakobjakobson13, you should address this message to BOINC@TACC to ask them to change default server address.
There is nothing BOINC should do with this

**Comment by RichardHaselgrove** [comment]
Well, it's perhaps a miscommunication between BOINC@TACC and the maintainer of BOINC's all_projects_list.xml - or perhaps it depends on how @jakobjakobson13 attached to the project.

**Comment by jakobjakobson13** [comment]
> Well, it's perhaps a miscommunication between BOINC@TACC and the maintainer of BOINC's all_projects_list.xml - or perhaps it depends on how @jakobjakobson13 attached to the project.

It was automatically attached by scienceunited

**Comment by RichardHaselgrove** [comment]
That could well be the problem, because account managers like Science United bypass the 'get_project_config.php' mechanism - which correctly returns

`<master_url>http://boinc.tacc.utexas.edu/</master_url>`

in this case.

**Comment by talregev** [comment]
So you need to talk also with Science United.
Even when you attach the https link it still give you this error. This error don't indicate if you on https or not.

**Comment by jakobjakobson13** [comment]
It should be taken care of it by scienceunited.
