### ISSUE TITLE
Amazon Fire tablet can't connect to Einstein@Home anymore

### ISSUE THREAD

**Issue by AG5BPilot** [BOINC/boinc#3873]
I have several 5th generation Amazon Fire tablets that just stopped being able to connect to Einstein@Home.  This is almost certainly the expired certificate problem, and will probably eventually prevent connecting to all projects as their certificates expire.  This will render these devices unusable.

The OS version is 5.3.6.4

Since Amazon Fire tablets are locked into the Amazon ecosystem, I can only download updated BOINC clients from the Amazon store.

If possible, please build an updated Android app with the new certificates and upload it to the Amazon store.

**Comment by randyfrisch** [comment]
Any plans to get BOINC working on Android again?! I was running it on give devices before Cert-gate happened a month ago. I'm sure we're losing out on a lot of distributed computing power.

**Comment by AenBleidd** [comment]
> Any plans to get BOINC working on Android again?!

Yes

**Comment by kit344** [comment]
Settings
Security & Privacy
Advanced
Apps from Unknown Sources

**Comment by AG5BPilot** [comment]
@kit344, Thanks for the idea, but even with "Apps from unknown sources" enabled, the installation fails.  It starts to install, does something for a while, and then errors out with "App not installed".  Same behavior on three different tablets.

**Comment by kit344** [comment]
> @kit344, Thanks for the idea, but even with "Apps from unknown sources" enabled, the installation fails. It starts to install, does something for a while, and then errors out with "App not installed". Same behavior on three different tablets.

You could try uninstalling the previous version first.
I think the 7.16.3 is 64bit.compatible
Earlier versions are 32bit only.
I have seen similar errors on some app when upgrading from 32bit to 64bit

**Comment by AenBleidd** [comment]
Not an issue anymore on 7.16.16
