### ISSUE TITLE
Test BOINC under MacOS 11 Big Sur

### ISSUE THREAD

**Issue by CharlieFenton** [BOINC/boinc#3876]
@AustinConlon has begun testing BOINC under the beta release of MacOS 11 Big Sur (Thank you!)

**Comment by RobTDev** [comment]
I've been testing BOINC 7.16.6 under macOS Big Sur for the past week or so, can report no issues so far other than some expected minor UI issues that may need cleaned up, that's to be expected though with the overall changes in the OS.

Attaching to projects, detaching projects, running work all seems to be quite smooth from experience so far.

One point that might need a separate issue and discussion will be around future Macs coming later this year as they transition from x86 intel processors to Apple Silicon which is based on the ARM64 architecture - [Apple Silicon - Overview](https://developer.apple.com/news/?id=ywv74y7m)

The transition is expected to take 2 years so there's still a bit of time but eventually all future Macs will run on Apple Silicon so BOINC will need re-compiled for that architecture.

**Comment by CharlieFenton** [comment]
> One point that might need a separate issue and discussion will be around future Macs coming later this year as they transition from x86 intel processors to Apple Silicon which is based on the ARM64 architecture

@RobTDev Please see #3827. The first step can be to make any changes necessary for Xcode 12 to build BOINC as an _x86_64 / Apple Silicon_ Universal Binary, It should be possible to do this using the Xcode 12 beta running under MacOS 11 beta, as discussed [here](https://github.com/BOINC/boinc/issues/3875#issuecomment-651459437).

**Comment by AenBleidd** [comment]
@CharlieFenton, do we still need this ticket or it could be closed?
