### ISSUE TITLE
Attaching to a Project using an Account Manager, does not use custom Resource Share from Account Manager Host settings

### ISSUE THREAD

**Issue by JacobWKlein** [BOINC/boinc#3877]
**Describe the bug**
Attaching to a Project using an Account Manager, does not use custom Resource Share from Account Manager Host settings

**Steps To Reproduce**
I have an Account Manager (AM) setup, and configured for my hosts.
I also have custom Resource share values, for each of the projects for each of the hosts.
If the Host is attaching to the project from the AM, it does not use the custom Resource Share.
This often catches me by surprise, because it's not using the settings that I carefully defined!

As a workaround, I have to change the AM host project resource share to some other value, sync, change it back, sync.
A needless wasteful pain.

Reproduced using BAM!, 7/1/2020, on BOINC 7.16.7.

**Expected behavior**
When attaching via AM, the custom Resource Share from the AM Host settings should be respected.

**Comment by talregev** [comment]
What os are you using?

**Comment by JacobWKlein** [comment]
Windows 10 x64. But this is an old problem.

**Comment by talregev** [comment]
For general tip, it always nice and make life easy to give the dev all the information they need. os system is important information. 
Thank you.

**Comment by davidpanderson** [comment]
I'm not sure if this is a bug in BOINC or in BAM!.
Jacob, can you please send an acct_mgr_reply.xml file
from a host showing the problem?

**Comment by JacobWKlein** [comment]
There are at least 2 related bugs going on here.

My scenario is:
- I have custom AM-controlled-host-specific-resource-shares, for every project, for my host, synced to the client.
- I used Tools > Stop Using .. to disconnect the host from the AM.
- The resource shares for my project reverted to the normal project-stored-venue-resource-shares, as expected I think.
- As a test, I manually removed 1 of my projects, MilkyWay
- I used Tools > Use account manager.. .. to reconnect the host to the AM.
- BUG #1: It attached the host to the project, but did not pass/use the AM-controlled-host-specific-resource-share (of 0).
- BUG #2: For all of the other projects, it did not restore the AM-controlled-host-specific-resource-shares. The reply only had the 1 project in it.

See attached. 
[acct_mgr_reply.zip](https://github.com/BOINC/boinc/files/4906323/acct_mgr_reply.zip)
Can you reproduce it hopefully?

Shouldn't the AM have sent my AM-controlled-host-specific-resource-shares, even for projects that it didn't need to reattach, when I reattached the AM?

Frustrating, because my only workaround is to now go back and change the AM-controlled-host-specific-resource-shares for every project on the host, to "trigger a change" that gets sync'd to the client.

**Comment by JacobWKlein** [comment]
Maybe detaching from the AM is a bad example, because it looks like it reattached as a "new host", which also is unfortunate. I'll see if I can get a better example where I just remove 1 project while staying attached to the AM.

**Comment by JacobWKlein** [comment]
Here you go.
Attached:
[acct_mgr_reply.zip](https://github.com/BOINC/boinc/files/4906344/acct_mgr_reply.zip)

My steps are:
- Used AM, to detach the project from the host
- Synchronized the Client to the AM, and it detached the project
- Used AM, to reattach the project, using the custom resource share of 0
- Synchronized the Client to the AM, and it reattached the project
- BUG: It showed 100 resource share in the UI, and kept that resource share after initial contact with the project, EVEN THOUGH the AM reply had clearly said "<resource_share>0</resource_share>" for the project.

Thoughts?
