### ISSUE TITLE
Rewriting the warning when detaching/aborting/resetting

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#388]
**Reported by Ageless on 31 Dec 37698742 02:40 UTC**
Can the warning message that shows up in BOINC Manager when a person is about to detach, be changed?

At this moment the warning is "Are you sure you want to detach from project 'project-name'?

I request for an inclusion in the warning that any work still being worked on/uploading/to be reported will be deleted when the person detaches. 

So as an example:

"Please confirm that you want to detach from project 'project-name'.
 Any tasks for this project that are waiting to run, running, suspended, uploading, or to be reported WILL be deleted." 

Yes detach / No cancel

Migrated-From: http://boinc.berkeley.edu/trac/ticket/405

**Comment by romw** [comment]
**Commented by Ageless on 28 Jun 37698751 23:06 UTC**
For more information, see [this BOINC forums thread](http://boinc.berkeley.edu/dev/forum_thread.php?id=2110).

**Comment by romw** [comment]
**Commented by Nicolas on 16 Jan 37699236 03:06 UTC**
Keywords are separated with '''spaces'''! Trac doesn't care if you add commas in between, 'warning' is a keyword, 'message' is another.

**Comment by romw** [comment]
**Commented by Ageless on 5 Jan 37699525 02:40 UTC**
Replying to [Nicolas](comment:3):
> Keywords are separated with '''spaces'''! Trac doesn't care if you add commas in between, 'warning' is a keyword, 'message' is another.
Yes sir! A bit nicer wouldn't be bad. But consider me slapped. 

Now for the rewriting of the title and adding to the request... hehehe. :-)

**Comment by romw** [comment]
**Commented by Ageless on 5 Dec 37699554 00:53 UTC**
Additional request for the warning messages when Resetting and Aborting individual tasks and/or uploading tasks. 

* Resetting a project only shows "Are you sure you want to reset project 'project-name'?"
other approach:

"Please confirm that you want to reset project 'project-name'.
Any tasks for this project that are waiting to run, running, suspended, uploading, or to be reported WILL be deleted." 

* Aborting an individual task now shows: "Are you sure you want to abort this task 'task-name'? (Progress: xx%, Status: its status)"
other approach:

"Please confirm that you want to abort task 'task-name'. 
When aborting this task, it will be deleted from your system. You will not receive any credit for it."

* I don't have an example of an uploading abort handy, so I don't know what the original message says. 
But the approach would be the same as in Aborting the task:

"Please confirm that you want to abort the uploading of task 'task-name'. 
When aborting this upload, the task will be deleted from your system. You will not receive any credit for it."

**Comment by romw** [comment]
**Commented by Nicolas on 8 Sep 37717149 04:53 UTC**
Another suggestion: Experienced BOINCers know clearly what happens when detaching. Add a "Don't show this message again" checkbox to the popup.

**Comment by romw** [comment]
**Commented by Nicolas on 14 Apr 37717152 06:40 UTC**
,,Replying to [Ageless](comment:4):,,
> ,,Yes sir! A bit nicer wouldn't be bad. But consider me slapped.,,

,,I really didn't mean it in a rude way; but who knows what mood I was at the time... Anyway, I think Trac should do something like ordering tags alphabetically '''while you type them'''; that way people would surely understand how they work :),,

**Comment by romw** [comment]
**Commented by romw on 23 Nov 39156798 14:13 UTC**
Kind of late for the 6.6 milestone, punting to the 6.8 milestone.

**Comment by romw** [comment]
**Commented by romw on 30 Oct 39425701 16:26 UTC**
To late for 6.8, wouldn't give the localizers enough time.

**Comment by ChristianBeer** [comment]
Messages changes a lot since this was reported. Please open a new issue if there are still strings to improve.
