### ISSUE TITLE
Add a project backup function

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#39]
**Reported by KSMarksPsych on 1 Jun 37296620 04:00 UTC**
Posted by: 
Date: 6:03 PM 10-01-2005
A nice feature addition for some projects (CPDN currently) would be an automatic backup of the state of that project.

The project state would be backed up something like daily. If the workunit crashes then the backup copy would be moved back into the working spot and tried again before reporting a client error.

This would have to be set on a project by project basis, since there is little point to doing this for projects other than CPDN at this time. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/39

**Comment by romw** [comment]
**Commented by MikeMarsUK on 6 Nov 37316222 08:53 UTC**
This would be '''extremely''' useful from CPDNs viewpoint.  The vast majority of crashes are due to transient problems during the 3 months or so the model needs to run (windows killing the workunit at shutdown, files locked by antivirus programmes, the graphics drivers collapsing, general PC instability).

http://climateapps1.oucs.ox.ac.uk/beta/forum_thread.php?id=84&nowrap=true#506

One problem with current ad-hoc backup strategies is with multicore systems and multiproject systems - everything has to be rolled back as a unit even if it was only one result which crashed.

For reference here is an autobackup tool which was written by RRodway (a participant on the BBC project):
http://bbc.cpdn.org/forum_thread.php?id=2748

**Comment by romw** [comment]
**Commented by Didactylos on 17 May 37879861 17:46 UTC**
This should be resolved by treating transient errors correctly, and restarting from checkpoints.

There's still a case for a backup feature, though, so I'm leaving this open. Let's reassess during 6.0 alpha testing, and decide whether BOINC's error handling still needs supplementing.

**Comment by lfield** [comment]
As far as I understand, this very old issue suggests retrying a crashed wu assuming some general PC instability. The system already does this and places limits on the number of times a wu can be retried. The only savings would be bandwidth with respect to the downloading of the wu input files somewhere else and reducing the number of errors reported. On the other hand, a wu might be run multiple times on an unstable environment. My view is that this optimization would add complexity for little real gain. It would be better to fix the underlying in stability. The overall system is already designed to work well in such an environment.
