### ISSUE TITLE
Syntax error on website

### ISSUE THREAD

**Issue by Peppernrino** [BOINC/boinc#3904]
On the bottom of the page - https://boinc.berkeley.edu/wiki/Creating_a_skin_for_the_BOINC_Manager - it states how to test the BOINC skin you've created, by running "C:\Program Files\BOINC\boincmgr.exe -c" with the -c flag inside the quotes.

It should be:

"C:\Program Files\BOINC\boincmgr.exe" -c

**Comment by Ageless93** [comment]
Fixed. 
Thanks
