### ISSUE TITLE
The usage of regex in replace will change only the first match. 

### ISSUE THREAD

**Issue by fix27** [BOINC/boinc#3910]
drupal/sites/all/libraries/tinymce/jscripts/tiny_mce/themes/advanced/js/ color_picker.js

The usage of regex [line :83] in replace [line :83] will change only the first match. Consider using a regular expression with the global replacement flag (/g).

83: namedLookup[value.replace(/\s+/, '').toLowerCase()] = key.replace(/#/, '').toLowerCase();

p.s. recommendation deepcode.ai

**Comment by AenBleidd** [comment]
This issue is related to 3rdparty library: https://github.com/tinymce/tinymce
