### ISSUE TITLE
typeof is compared to undefined

### ISSUE THREAD

**Issue by fix27** [BOINC/boinc#3911]
drupal/sites/default/boinc/modules/contrib/ckeditor/plugins/mediaembed/ plugin.js

typeof [line :63] is compared [line :63] to undefined [line :63] . This comparison is invalid, because typeof always returns strings.

63:                    if (typeof(element.children[x].attributes.width) != undefined) {
64:                      element.children[x].attributes.width = element.attributes.width;
65:                    }
66:                    if (typeof(element.children[x].attributes.height) != undefined) {
67:                      element.children[x].attributes.height = element.attributes.height;

p.s. recommendation deepcode.ai

**Comment by AenBleidd** [comment]
This issue is related to 3rdparty library: https://github.com/ckeditor/
