### ISSUE TITLE
Upgrading BOINC deletes cc_config and installing BOINC does not creat one any more

### ISSUE THREAD

**Issue by Sandman192** [BOINC/boinc#3917]
**Describe the bug**
I get an error message saying something in the lines "can't find cc_confing.xml - running default. Was never that way with older versions of BOINC.

**Steps To Reproduce**
Not with 10 days of work of 20 WUs. I'm not aborting all of it. I thought it would create a cc_config.xml file from a clean install of BOINC so all I have to do is change a 0 to a 1 for all GPUs when BOINC creates the config file. But no. It worked before in older versions of BOINC. _How do you think I know about cc_config.xml? It's not in the BOINC wiki/BOINC_Help or wiki/Client_configuration._

**Expected behavior**

**Screenshots**
Don't have one since I found the settings to add all GPUs to run.

**System Information**
 - OS: 10
 - BOINC Version: 7.16.7

**Additional context**
1. Upgrading to v7.16.7 deletes cc_config.xml.
2. Fresh install does not create cc_config.xml **any more**.

Plus, make running all GPUs by default and an option and put it in "Computing preferences under Tools" for running all GPU settings.

<cc_config>
<options>
<use_all_gpus>1</use_all_gpus>
</options>
</cc_config>

**Also, why is options and /options not showing up in Preview while writing in this form?** It's just after cc_config and before /cc_config and shows blank lines instead.

I had to google this when cc_config.xml when it was missing. And to tell you it was very hard to find the settings.

Edit: Ignore all I posted and close this report. I found out how cc_config.xml was created by changing the "Even log options" it created the file.

But please put an option in the settings where you can change it to running all GPUS and make it as default. It's BOINC and is designed to run CPUs and **GPUs**. How my cc_config.xml file got deleted I will never know.

**Comment by RichardHaselgrove** [comment]
> OS: 10

Please include platform. I'm assuming Windows?

> Fresh install does not create cc_config.xml any more.

It never did. cc_config is an optional file, which the user may create, or not, as they wish.

**Comment by Sandman192** [comment]
Forgot to put Windows 10
And I just edit on the first post at the bottom of my mistake.
