### ISSUE TITLE
[Minecraft@home] Auto-attach doesn't work

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#3932]
**Describe the bug**
When trying to auto-attach client hangs forever trying to send RPC request

**Steps To Reproduce**
1. Create account on Minecraft@home
2. Install BOINC
3. Run BOINC Manager after installation

**Expected behavior**
BOINC Manager and BOINC client run and Minecraft@home attached

**System Information**
 - OS: Windows x64
 - BOINC Version: 7.16.7

**Additional context**
Looks like there is some data race or something similar. Initial token lookup request to project server failed:

```
20-Jul-2020 01:29:02 [---] Doing token lookup RPC to Minecraft@Home
20-Jul-2020 01:29:02 [---] token lookup RPC failed: retry
```

**Log file with all flags enabled**

[stdoutdae.txt](https://github.com/BOINC/boinc/files/4946777/stdoutdae.txt)

**Comment by davidpanderson** [comment]
I couldn't repro this.  Maybe it was a transient problem at the project.
