### ISSUE TITLE
BOINC isn't suspending computation when non-BOINC cpu usage is high

### ISSUE THREAD

**Issue by wolfbeast** [BOINC/boinc#3935]
**Describe the bug**
BOINC isn't suspending computation when non-BOINC cpu usage is high, despite having settings to suspend computation to that effect.

**Steps To Reproduce**
1. Set BOINC up:
    - Use local preferences
    - Use 50% of processors on a high core count machine
    - 100% of cpu time used.
2. Set "suspend when non-boinc cpu usage is above": 30% (also tried 50%)
3. Launch a heavy-load, multi-core task

**Expected behavior**
BOINC should suspend computation when the heavy load task runs

**Screenshots**
![image](https://user-images.githubusercontent.com/3359132/87923887-6c4e9200-ca7e-11ea-889f-11d4423f0ad6.png)

**System Information**
 - OS: Windows Server 2008 R2
 - BOINC Version: 7.16.7

**Additional context**
Hardware: 2x 6c/12t Xeon L5640 (24 logical processors total)
60GB RAM

This machine is used for multithreaded compilation which bumps CPU usage outside of BOINC to 95%+ when active, and BOINC should suspend, but it doesn't. Even if fully loaded, BOINC continues to compute.
Even suspending and resuming manually while the task is running resumes the BOINC computation tasks when CPU usage is already over 95%.
It happens irrespective of which projects attached to (seems to be a clear BOINC scheduling problem)

**Comment by Ageless93** [comment]
I just tested it on my system with setting the value to 7%, then ran a Kaspersky database update (which uses 8% CPU).

> 20/07/2020 11:55:10 |  | Reading preferences override file
> 20/07/2020 11:55:10 |  | suspend work if non-BOINC CPU load exceeds 7%
> 20/07/2020 11:55:10 |  | Suspending computation - CPU is busy
> 20/07/2020 11:55:10 | Rosetta@home | [cpu_sched] Preempting JHR_bd5_14318_n_0000100004_0000020_0_fragments_fold_SAVE_ALL_OUT_990551_24_0 (left in memory)
> 20/07/2020 11:55:10 | Rosetta@home | [cpu_sched] Preempting JHR_bd5_05111_c_0000200008_0000008_0_fragments_fold_SAVE_ALL_OUT_963479_24_0 (left in memory)
> 20/07/2020 11:55:10 | Rosetta@home | [cpu_sched] Preempting JHR_b2_02877_c_full_17_0000100002_0000014_1_fragments_fold_SAVE_ALL_OUT_991321_24_0 (left in memory)
> 20/07/2020 11:55:10 | Rosetta@home | [cpu_sched] Preempting JHR_bd4_01971_c_0000100004_0000019_0_fragments_fold_SAVE_ALL_OUT_994204_24_0 (left in memory)
> 20/07/2020 11:55:10 | Rosetta@home | [cpu_sched] Preempting b4k_8814_fold_SAVE_ALL_OUT_956605_919_0 (left in memory)
> 20/07/2020 11:55:10 | Rosetta@home | [cpu_sched] Preempting b4k_5283_fold_SAVE_ALL_OUT_958064_919_0 (left in memory)
> 20/07/2020 11:55:10 | Rosetta@home | [cpu_sched] Preempting b4k_8563_fold_SAVE_ALL_OUT_958198_919_0 (left in memory)
> 20/07/2020 11:55:10 | Rosetta@home | [cpu_sched] Preempting b4k_8205_fold_SAVE_ALL_OUT_958183_919_0 (left in memory)
> 20/07/2020 11:55:10 | Rosetta@home | [cpu_sched] Preempting b3x_7312_fold_SAVE_ALL_OUT_957241_919_0 (left in memory)
> 20/07/2020 11:55:10 | Rosetta@home | [cpu_sched] Preempting b3x_1594_fold_SAVE_ALL_OUT_956731_919_0 (left in memory)
> 20/07/2020 11:55:10 | Rosetta@home | [cpu_sched] Preempting tgfbR1_3_SAVE_ALL_OUT_IGNORE_THE_REST_4gt4bw5q_986472_1_0 (left in memory)
> 

So works for me. 
This is on Windows 10 with a single CPU (Ryzen 3900X running single threaded)

**Comment by wolfbeast** [comment]
I think it might be related to having a high core count? 24 for me, and on the forum I also saw a GNU/Linux report of something similar on a machine with 32 cores.

**Comment by Ageless93** [comment]
Turned on SMT on my CPU, allowed 23 Rosetta tasks to start and run for a while. Then set NON-BOINC CPU load to 4%, reran the test. Started Google Earth. 

> 20/07/2020 14:41:02 | Rosetta@home | [checkpoint] result b4d_2271_fold_SAVE_ALL_OUT_954585_30_0 checkpointed
> 20/07/2020 14:41:09 | Rosetta@home | [checkpoint] result bmpr2_attempt3_0_SAVE_ALL_OUT_IGNORE_THE_REST_5jn2ih1o_951189_2_0 checkpointed
> 20/07/2020 14:41:10 | Rosetta@home | [checkpoint] result b3x_1505_fold_SAVE_ALL_OUT_956729_919_0 checkpointed
> 20/07/2020 14:41:13 | WUProp@Home | [checkpoint] result data_collect_v4_1592371802_368919_1 checkpointed
> 20/07/2020 14:41:19 | Rosetta@home | [checkpoint] result bmpr1_attempt3_4_SAVE_ALL_OUT_IGNORE_THE_REST_8tm0cb3e_951620_2_0 checkpointed
> 20/07/2020 14:41:25 | Rosetta@home | [checkpoint] result b3x_4810_fold_SAVE_ALL_OUT_956985_919_0 checkpointed
> 20/07/2020 14:41:26 | Rosetta@home | [checkpoint] result b4k_18645_fold_SAVE_ALL_OUT_957863_943_0 checkpointed
> 20/07/2020 14:41:30 | Rosetta@home | [checkpoint] result b3x_4758_fold_SAVE_ALL_OUT_956974_919_0 checkpointed
> 20/07/2020 14:41:31 | Rosetta@home | [checkpoint] result bmpr1_attempt3_5_SAVE_ALL_OUT_IGNORE_THE_REST_3gr3hd8t_951626_2_0 checkpointed
> 20/07/2020 14:41:33 | Rosetta@home | [checkpoint] result b4k_18660_fold_SAVE_ALL_OUT_957864_943_0 checkpointed
> 20/07/2020 14:41:37 | Rosetta@home | [checkpoint] result bmpr2_attempt3_9_SAVE_ALL_OUT_IGNORE_THE_REST_4eu5sp8y_951666_2_0 checkpointed
> 20/07/2020 14:41:38 | Rosetta@home | [checkpoint] result b3x_7287_fold_SAVE_ALL_OUT_957239_919_0 checkpointed
> 20/07/2020 14:41:38 | Rosetta@home | [checkpoint] result b3x_7936_fold_SAVE_ALL_OUT_957293_943_0 checkpointed
> 20/07/2020 14:41:44 | Rosetta@home | [checkpoint] result JHR_bd5_15664_c_0000100004_0000019_0_fragments_fold_SAVE_ALL_OUT_994296_26_0 checkpointed
> 20/07/2020 14:41:49 | Rosetta@home | [checkpoint] result JHR_bd5_11434_c_0000200006_0000001_0_fragments_fold_SAVE_ALL_OUT_978817_26_0 checkpointed
> 20/07/2020 14:41:49 | Rosetta@home | [checkpoint] result b3x_6680_fold_SAVE_ALL_OUT_957165_943_0 checkpointed
> 20/07/2020 14:41:50 | Rosetta@home | [checkpoint] result JHR_bd5_04926_c_0000100001_0000007_0_fragments_fold_SAVE_ALL_OUT_979840_26_0 checkpointed
> 20/07/2020 14:41:56 | Rosetta@home | [checkpoint] result b3x_1505_fold_SAVE_ALL_OUT_956729_919_0 checkpointed
> 20/07/2020 14:42:00 | Rosetta@home | [checkpoint] result bmpr1_attempt3_1_SAVE_ALL_OUT_IGNORE_THE_REST_5ys1iz7k_951182_2_0 checkpointed
> 20/07/2020 14:42:13 | WUProp@Home | [checkpoint] result data_collect_v4_1592371802_368919_1 checkpointed
> 20/07/2020 14:42:20 | Rosetta@home | [checkpoint] result bmpr2_attempt3_0_SAVE_ALL_OUT_IGNORE_THE_REST_5jn2ih1o_951189_2_0 checkpointed
> 20/07/2020 14:42:27 | Rosetta@home | [checkpoint] result JHR_b2_03614_n_full_17_0000100003_0000011_0_fragments_fold_SAVE_ALL_OUT_965143_24_0 checkpointed
> 20/07/2020 14:42:32 | Rosetta@home | [checkpoint] result b3x_1638_fold_SAVE_ALL_OUT_956733_919_0 checkpointed
> 20/07/2020 14:42:35 | Rosetta@home | [checkpoint] result bmpr2_attempt3_9_SAVE_ALL_OUT_IGNORE_THE_REST_4eu5sp8y_951666_2_0 checkpointed
> 20/07/2020 14:42:38 | Rosetta@home | [checkpoint] result bmpr1_attempt3_5_SAVE_ALL_OUT_IGNORE_THE_REST_3gr3hd8t_951626_2_0 checkpointed
> 20/07/2020 14:42:40 | Rosetta@home | [checkpoint] result tgfbR2_3_SAVE_ALL_OUT_IGNORE_THE_REST_8cs3zr6o_958361_1_0 checkpointed
> 20/07/2020 14:42:45 | Rosetta@home | [checkpoint] result tgfbR2_3_SAVE_ALL_OUT_IGNORE_THE_REST_8cs3zr6o_958361_1_0 checkpointed
> 20/07/2020 14:42:52 | Rosetta@home | [checkpoint] result JHR_bd4_02142_n_0000100001_0000021_0_fragments_fold_SAVE_ALL_OUT_971108_2_0 checkpointed
> 20/07/2020 14:43:07 | Rosetta@home | [checkpoint] result rb_07_18_31941_31639__t000__0_C1_SAVE_ALL_OUT_IGNORE_THE_REST_1002521_211_0 checkpointed
> 20/07/2020 14:43:11 | Rosetta@home | [checkpoint] result b4k_20702_fold_SAVE_ALL_OUT_957940_919_0 checkpointed
> 20/07/2020 14:43:13 | WUProp@Home | [checkpoint] result data_collect_v4_1592371802_368919_1 checkpointed
> 20/07/2020 14:43:17 | Rosetta@home | [checkpoint] result b4d_2271_fold_SAVE_ALL_OUT_954585_30_0 checkpointed
> 20/07/2020 14:43:25 | Rosetta@home | [checkpoint] result bmpr2_attempt3_0_SAVE_ALL_OUT_IGNORE_THE_REST_5jn2ih1o_951189_2_0 checkpointed
> 20/07/2020 14:43:32 | Rosetta@home | [checkpoint] result b3x_4810_fold_SAVE_ALL_OUT_956985_919_0 checkpointed
> 20/07/2020 14:43:36 | Rosetta@home | [checkpoint] result bmpr1_attempt3_4_SAVE_ALL_OUT_IGNORE_THE_REST_8tm0cb3e_951620_2_0 checkpointed
> 20/07/2020 14:43:38 | Rosetta@home | [checkpoint] result b3x_4758_fold_SAVE_ALL_OUT_956974_919_0 checkpointed
> 20/07/2020 14:43:52 | Rosetta@home | [checkpoint] result b4k_18660_fold_SAVE_ALL_OUT_957864_943_0 checkpointed
> 20/07/2020 14:43:53 | Rosetta@home | [checkpoint] result b4k_18645_fold_SAVE_ALL_OUT_957863_943_0 checkpointed
> 20/07/2020 14:43:55 | Rosetta@home | [checkpoint] result JHR_bd5_11434_c_0000200006_0000001_0_fragments_fold_SAVE_ALL_OUT_978817_26_0 checkpointed
> 20/07/2020 14:43:56 | Rosetta@home | [checkpoint] result JHR_bd5_04926_c_0000100001_0000007_0_fragments_fold_SAVE_ALL_OUT_979840_26_0 checkpointed
> 20/07/2020 14:43:58 | Rosetta@home | [checkpoint] result b3x_7936_fold_SAVE_ALL_OUT_957293_943_0 checkpointed
> 20/07/2020 14:43:59 | Rosetta@home | [checkpoint] result JHR_bd5_15664_c_0000100004_0000019_0_fragments_fold_SAVE_ALL_OUT_994296_26_0 checkpointed
> 20/07/2020 14:44:00 | Rosetta@home | [checkpoint] result b3x_7287_fold_SAVE_ALL_OUT_957239_919_0 checkpointed
> 20/07/2020 14:44:03 | Rosetta@home | [checkpoint] result b3x_1505_fold_SAVE_ALL_OUT_956729_919_0 checkpointed
> 20/07/2020 14:44:09 | Rosetta@home | [checkpoint] result JHR_bd5_11434_c_0000200006_0000001_0_fragments_fold_SAVE_ALL_OUT_978817_26_0 checkpointed
> 20/07/2020 14:44:13 | WUProp@Home | [checkpoint] result data_collect_v4_1592371802_368919_1 checkpointed
> 20/07/2020 14:44:16 | Rosetta@home | [checkpoint] result bmpr1_attempt3_1_SAVE_ALL_OUT_IGNORE_THE_REST_5ys1iz7k_951182_2_0 checkpointed
> 20/07/2020 14:44:18 | Rosetta@home | [checkpoint] result b3x_4758_fold_SAVE_ALL_OUT_956974_919_0 checkpointed

> 20/07/2020 14:44:21 |  | Suspending computation - CPU is busy

> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting b3x_1505_fold_SAVE_ALL_OUT_956729_919_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting b4d_2271_fold_SAVE_ALL_OUT_954585_30_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting bmpr1_attempt3_5_SAVE_ALL_OUT_IGNORE_THE_REST_3gr3hd8t_951626_2_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting bmpr1_attempt3_1_SAVE_ALL_OUT_IGNORE_THE_REST_5ys1iz7k_951182_2_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting b3x_4810_fold_SAVE_ALL_OUT_956985_919_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting JHR_b2_03614_n_full_17_0000100003_0000011_0_fragments_fold_SAVE_ALL_OUT_965143_24_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting bmpr2_attempt3_0_SAVE_ALL_OUT_IGNORE_THE_REST_5jn2ih1o_951189_2_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting bmpr2_attempt3_9_SAVE_ALL_OUT_IGNORE_THE_REST_4eu5sp8y_951666_2_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting b3x_7287_fold_SAVE_ALL_OUT_957239_919_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting b3x_1638_fold_SAVE_ALL_OUT_956733_919_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting rb_07_18_31941_31639__t000__0_C1_SAVE_ALL_OUT_IGNORE_THE_REST_1002521_211_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting b3x_4758_fold_SAVE_ALL_OUT_956974_919_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting JHR_bd4_02142_n_0000100001_0000021_0_fragments_fold_SAVE_ALL_OUT_971108_2_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting tgfbR2_3_SAVE_ALL_OUT_IGNORE_THE_REST_8cs3zr6o_958361_1_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting b4k_20702_fold_SAVE_ALL_OUT_957940_919_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting bmpr1_attempt3_4_SAVE_ALL_OUT_IGNORE_THE_REST_8tm0cb3e_951620_2_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting b4k_18645_fold_SAVE_ALL_OUT_957863_943_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting b4k_18660_fold_SAVE_ALL_OUT_957864_943_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting JHR_bd5_11434_c_0000200006_0000001_0_fragments_fold_SAVE_ALL_OUT_978817_26_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting b3x_6680_fold_SAVE_ALL_OUT_957165_943_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting b3x_7936_fold_SAVE_ALL_OUT_957293_943_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting JHR_bd5_15664_c_0000100004_0000019_0_fragments_fold_SAVE_ALL_OUT_994296_26_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [cpu_sched] Preempting JHR_bd5_04926_c_0000100001_0000007_0_fragments_fold_SAVE_ALL_OUT_979840_26_0 (left in memory)
> 20/07/2020 14:44:21 | Rosetta@home | [checkpoint] result b3x_4810_fold_SAVE_ALL_OUT_956985_919_0 checkpointed

> 20/07/2020 14:44:31 |  | Resuming computation
>

**Comment by Ageless93** [comment]
So on Windows 10, 2004, it works. With 23 threads doing Rosetta and an NCI task running WUProp. 
Not saying it isn't a bug, it could be to do with you having two CPUs. Or Windows Server.

**Comment by wolfbeast** [comment]
Just reporting what I'm seeing and it's definitely a bug. Perhaps the calculation of "non-boinc cpu usage" is wrong. Your low threshold percentages might trigger it then; have you tried using a higher number and actually -loading- the system? Because 4%/8% really isn't a reason in my situation to suspend BOINC (nor should it really be anywhere else...) it only becomes important if I actually _need_ the cpu power for other tasks.

**Comment by wolfbeast** [comment]
If it calculates it _per core_ or _per process_ compared to the total computational power then that is absolutely wrong! That way you'd never be able to detect on a multi-core machine if it's busy.
It needs to check the **cumulative load**. Just like BOINC does, other processes will also spawn many childs to do parallel computation. As you can see with the resource meter (top right) the system load is a full 100%. BOINC takes at most 50% even if not pushed to the background by process priority, so the other cumulative 50% and likely more is taken by other processes. That is > 30% and BOINC should suspend, and it does not.

So the check should be:
`cumulative(all) - cumulative(boinc) > preference%` and if true, suspend. But it clearly does something other than that.

**Comment by davidpanderson** [comment]
The mem_usage_debug log flag shows the non-BOINC CPU usage.

**Comment by Ageless93** [comment]
Running 11 Rosetta and 12 Prime95 tasks on one CPU, Prime95 only peaks twice to near 95% usage:
20/07/2020 21:05:17 |  | [mem_usage] non-BOINC CPU usage: 3.65%
20/07/2020 21:05:27 |  | [mem_usage] non-BOINC CPU usage: 6.34%
20/07/2020 21:05:37 |  | [mem_usage] non-BOINC CPU usage: 32.42%
20/07/2020 21:05:47 |  | [mem_usage] non-BOINC CPU usage: 59.39%
20/07/2020 21:05:57 |  | [mem_usage] non-BOINC CPU usage: 94.62%
20/07/2020 21:06:07 |  | [mem_usage] non-BOINC CPU usage: 94.76%
20/07/2020 21:06:17 |  | [mem_usage] non-BOINC CPU usage: 78.87%
20/07/2020 21:06:27 |  | [mem_usage] non-BOINC CPU usage: 78.95%
20/07/2020 21:06:37 |  | [mem_usage] non-BOINC CPU usage: 77.43%
20/07/2020 21:06:47 |  | [mem_usage] non-BOINC CPU usage: 73.54%
20/07/2020 21:06:57 |  | [mem_usage] non-BOINC CPU usage: 67.09%
20/07/2020 21:07:07 |  | [mem_usage] non-BOINC CPU usage: 67.76%
20/07/2020 21:07:17 |  | [mem_usage] non-BOINC CPU usage: 67.57%
20/07/2020 21:07:27 |  | [mem_usage] non-BOINC CPU usage: 67.47%
20/07/2020 21:07:37 |  | [mem_usage] non-BOINC CPU usage: 77.39%
20/07/2020 21:07:47 |  | [mem_usage] non-BOINC CPU usage: 78.86%
20/07/2020 21:07:57 |  | [mem_usage] non-BOINC CPU usage: 78.70%
20/07/2020 21:08:07 |  | [mem_usage] non-BOINC CPU usage: 73.94%
20/07/2020 21:08:17 |  | [mem_usage] non-BOINC CPU usage: 69.79%
20/07/2020 21:08:28 |  | [mem_usage] non-BOINC CPU usage: 0.00%

@wolfbeast perhaps your 95% is just too high. Run with all your intended processes and the [mem_usage_debug flag](https://boinc.berkeley.edu/wiki/Client_configuration#Logging_flags) on and see what sweet spot is hit with non_BOINC CPU usage and set the percentage accordingly. Most project applications are set to Low priority (for GPU at Below Normal), so they should sidestep any higher priority applications anyway. They won't stop running and be in memory. they just won't run at their full cycles then. Only at the scraps still left over from higher priority processes.

**Comment by wolfbeast** [comment]
OK I looked at the log with the flag enabled and there's definitely something amiss with how it calculates things.
My compilation task spawns 20 threads, leaving 4 free for i/o and misc things and will hit a continuous CPU usage on the box well above what BOINC sees. I'm not sure how BOINC measures CPU but it's certainly not true to what is going on. it regularly measures 0% CPU or low 10%. This run it actually stopped twice, but only for one "measurement" then it found 0% again and resumed...

```
7/20/2020 7:52:05 PM |  | Re-reading cc_config.xml
7/20/2020 7:52:05 PM |  | log flags: file_xfer, sched_ops, task, mem_usage_debug
7/20/2020 7:52:06 PM |  | [mem_usage] enforce: available RAM 30714.90MB swap 61428.87MB
7/20/2020 7:52:07 PM |  | Re-reading cc_config.xml
7/20/2020 7:52:07 PM |  | log flags: file_xfer, sched_ops, task, mem_usage_debug
7/20/2020 7:52:08 PM |  | [mem_usage] enforce: available RAM 30714.90MB swap 61428.87MB
7/20/2020 7:52:11 PM | World Community Grid | [mem_usage] OPN1_0005237_01481_0: WS 125.23MB, smoothed 125.23MB, swap 202.73MB, 0.00 page faults/sec, user CPU 8970.947, kernel CPU 5.663
7/20/2020 7:52:11 PM | World Community Grid | [mem_usage] OPN1_0005285_06080_0: WS 138.96MB, smoothed 138.96MB, swap 216.30MB, 0.00 page faults/sec, user CPU 8947.687, kernel CPU 8.081
7/20/2020 7:52:11 PM | World Community Grid | [mem_usage] OPN1_0005181_05611_0: WS 137.70MB, smoothed 137.70MB, swap 215.00MB, 0.00 page faults/sec, user CPU 8425.474, kernel CPU 7.582
7/20/2020 7:52:11 PM | World Community Grid | [mem_usage] OPN1_0005314_06033_0: WS 153.61MB, smoothed 153.61MB, swap 230.94MB, 0.00 page faults/sec, user CPU 8230.114, kernel CPU 10.546
7/20/2020 7:52:11 PM | World Community Grid | [mem_usage] OPN1_0005171_03221_0: WS 125.24MB, smoothed 125.24MB, swap 202.74MB, 0.00 page faults/sec, user CPU 7908.081, kernel CPU 5.288
7/20/2020 7:52:11 PM | World Community Grid | [mem_usage] OPN1_0005314_05254_0: WS 125.14MB, smoothed 125.14MB, swap 202.65MB, 0.00 page faults/sec, user CPU 7109.059, kernel CPU 5.117
7/20/2020 7:52:11 PM | World Community Grid | [mem_usage] OPN1_0005171_03196_0: WS 125.05MB, smoothed 125.05MB, swap 202.71MB, 0.00 page faults/sec, user CPU 6855.667, kernel CPU 6.427
7/20/2020 7:52:11 PM | World Community Grid | [mem_usage] OPN1_0005273_06021_0: WS 124.95MB, smoothed 124.95MB, swap 202.73MB, 0.00 page faults/sec, user CPU 5860.708, kernel CPU 3.884
7/20/2020 7:52:11 PM | World Community Grid | [mem_usage] OPN1_0005314_02624_0: WS 154.21MB, smoothed 154.21MB, swap 231.46MB, 0.00 page faults/sec, user CPU 4585.088, kernel CPU 7.722
7/20/2020 7:52:11 PM |  | [mem_usage] BOINC totals: WS 1210.10MB, smoothed 1210.10MB, swap 1907.28MB, 0.00 page faults/sec
7/20/2020 7:52:11 PM |  | [mem_usage] All others: WS 2494.17MB, swap 2110.91MB, user 122814.112s, kernel 19163.475s
7/20/2020 7:52:11 PM |  | [mem_usage] non-BOINC CPU usage: 1.44%

mem reports snipped from here on for brevity

7/20/2020 7:52:21 PM |  | [mem_usage] non-BOINC CPU usage: 0.00%
7/20/2020 7:52:31 PM |  | [mem_usage] non-BOINC CPU usage: 4.07%
7/20/2020 7:52:41 PM |  | [mem_usage] non-BOINC CPU usage: 1.15%
7/20/2020 7:52:51 PM |  | [mem_usage] non-BOINC CPU usage: 0.00%
7/20/2020 7:53:01 PM |  | [mem_usage] non-BOINC CPU usage: 3.18%
7/20/2020 7:53:12 PM |  | [mem_usage] non-BOINC CPU usage: 2.39%
*** task started **
7/20/2020 7:53:22 PM |  | [mem_usage] non-BOINC CPU usage: 5.14%
7/20/2020 7:53:32 PM |  | [mem_usage] non-BOINC CPU usage: 5.15%
7/20/2020 7:53:42 PM |  | [mem_usage] non-BOINC CPU usage: 5.09%
7/20/2020 7:53:52 PM |  | [mem_usage] non-BOINC CPU usage: 5.58%
7/20/2020 7:54:02 PM |  | [mem_usage] non-BOINC CPU usage: 2.63%
7/20/2020 7:54:13 PM |  | [mem_usage] non-BOINC CPU usage: 5.35%
7/20/2020 7:54:23 PM |  | [mem_usage] non-BOINC CPU usage: 0.00%
7/20/2020 7:54:33 PM |  | [mem_usage] non-BOINC CPU usage: 7.29%
7/20/2020 7:54:43 PM |  | [mem_usage] non-BOINC CPU usage: 12.08%
7/20/2020 7:54:53 PM |  | [mem_usage] non-BOINC CPU usage: 5.57%
7/20/2020 7:55:03 PM |  | [mem_usage] non-BOINC CPU usage: 9.91%
7/20/2020 7:55:13 PM |  | [mem_usage] non-BOINC CPU usage: 0.01%
7/20/2020 7:55:24 PM |  | [mem_usage] non-BOINC CPU usage: 2.83%
7/20/2020 7:55:34 PM |  | [mem_usage] non-BOINC CPU usage: 34.71%
7/20/2020 7:55:34 PM |  | Suspending computation - CPU is busy
7/20/2020 7:55:44 PM |  | [mem_usage] non-BOINC CPU usage: 46.72%
7/20/2020 7:55:54 PM |  | [mem_usage] non-BOINC CPU usage: 0.00%
7/20/2020 7:55:54 PM |  | Resuming computation
7/20/2020 7:56:04 PM |  | [mem_usage] non-BOINC CPU usage: 24.08%
7/20/2020 7:56:14 PM |  | [mem_usage] non-BOINC CPU usage: 0.00%
7/20/2020 7:56:24 PM |  | [mem_usage] non-BOINC CPU usage: 10.26%
7/20/2020 7:56:35 PM |  | [mem_usage] non-BOINC CPU usage: 16.71%
7/20/2020 7:56:45 PM |  | [mem_usage] non-BOINC CPU usage: 11.22%
7/20/2020 7:56:55 PM |  | [mem_usage] non-BOINC CPU usage: 33.06%
7/20/2020 7:56:55 PM |  | Suspending computation - CPU is busy
7/20/2020 7:57:05 PM |  | [mem_usage] non-BOINC CPU usage: 0.00%
7/20/2020 7:57:05 PM |  | Resuming computation
7/20/2020 7:57:15 PM |  | [mem_usage] non-BOINC CPU usage: 6.25%
```

**Comment by wolfbeast** [comment]
How exactly _does_ boinc measure this non-BOINC CPU usage? Would be thrown off by constantly spawning and closing of new processes? (because that is what is happening in effect when I run the task -- it will run 20 parallel compile threads that will call cl.exe from the command-line to compile one file, terminate cl, then launch a new cl process for the next file, and so on, and so forth. So that is rapid-fire launching of new processes that take cpu, but are closed the moment the file is compiled. If your measurement depends on processes that a permanent, then it will not see the majority of the CPU used. Why aren't you using the system performance API to measure total CPU load?

**Comment by davidpanderson** [comment]
Every 10 seconds it computes the cumulative CPU time of non-BOINC processes,
and subtracts the previous measurement.
As you point out, this doesn't account short-lived processes.
But it's not clear how to improve this.
Total CPU usage doesn't distinguish BOINC/non-BOINC.

**Comment by davidpanderson** [comment]
Actually it is clear how to improve it; I'll have a go at it.

**Comment by davidpanderson** [comment]
Yup - that's how to do it.

**Comment by GreenReaper** [comment]
I ran into this playing 4K video (one of the things it's intended to address) even when set it to 1% (BOINC would cycle on and off every 10 seconds, sometimes 0.00%, other times 0.60% when Task Manager showed 2-3%). I think I see at least one issue.

[On Windows, total_cpu_time() retrieves the total user-mode time](https://github.com/BOINC/boinc/blob/43a883060dbfb6bf643fe5a958f3587d62201e6a/lib/procinfo_win.cpp#L157). But this does not account for system (kernel/driver) time on behalf of other applications. In particular, hardware-acellerated video playback appears to count almost exclusively as system time (looking at the graph in Task Manager with the context menu item "show kernel times" on), which is as you might expect.

As such, I think you need something like this there (accounting for the fact that idle time is system/kernel time):
```
    x.LowPart = u.dwLowDateTime + (s.dwLowDateTime - i.dwLowDateTime);
    x.HighPart = u.dwHighDateTime + (s.dwHighDateTime - i.dwHighDateTime);
```
This is in line with [the "old" method of accounting](https://github.com/BOINC/boinc/blob/9f702850afa5060ff0fdfd5825b9a3b21900c3c5/client/app.cpp#L529) which added `user_time` and `kernel_time` from the `PROCINFO` structures.

**Comment by GreenReaper** [comment]
I tried the build artifacts but they didn't do quite what I expected, i.e. match Task Manager for low-level utilization. That said I don't know that there is anything wrong with the commit, it just isn't doing what I thought it'd do ("accurate" non-BOINC CPU usage that doesn't vary wildly depending on whether BOINC is running tasks or not), and it may be that it never will.

[Others have faced this issue](https://stackoverflow.com/questions/68738852/get-cpu-load-using-getsystemtimes) with GetSystemTimes not always matching expectations.

Looking further it seems that [in modern versions of Windows](https://www.hwinfo.com/forum/threads/windows-11-22h2-cpu-usage.8121/) Task Manager is now reporting on the "Core Utility" (in HWiNFO) capped to 100% (it can actually go over that, up to 129.1% here - [seemingly due to turbo boost](https://learn.microsoft.com/en-us/troubleshoot/windows-client/performance/cpu-usage-exceeds-100)).

This links to % Processor Utility/Performance performance counters rather than ticks-based monitoring which may be negatively impacted by dynamic core frequencies and power management, and probably competing tasks as suggested earlier.
