### ISSUE TITLE
[client] <gui_rpc_debug/> when enabled crash the client after a while

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#3936]
**Describe the bug**
When enabled crash the client after some time

**Steps To Reproduce**
1. Enable <gui_rpc_debug>
2. Wait for some time

**Expected behavior**
Client doesn't crash

**System Information**
 - OS: Windows x64
 - BOINC Version: 7.16.7

**Comment by Ageless93** [comment]
How much time is "some time"? 
I've been running with the flag on for 20 minutes now and it's still going strong. 
Is this with BOINC Manager open? With the event log visible?

**Comment by AenBleidd** [comment]
I didn't check this yet. I just created a separate ticket from this thread: #3925

**Comment by Ageless93** [comment]
Some other weird things going on though. It worked fine while I added it via the event log options menu. But on an exit & restart of the client things went haywire. I had constantly flashing windows, the Projects tab would not fully populate. 

BOINC Manager constantly gave the "communicating with BOINC client, please wait" window with the Exit BOINC Manager and cancel buttons. Pressing cancel didn't help here, that'll just exit & return the "please wait" window. 
Then I pressed Exit BOINC Manager, which resulted in both the client and the manager leaving memory but all Rosetta tasks to stay in memory and running. I had to manually exit them one by one from Windows Task Manager. 

It looks like that bug we had earlier, where 1,500 lines would write every second to event log, which was impossible for the manager to do (can't write 1.5 second worth of info in one second). But that would completely hang the manager.

**Comment by dbareis** [comment]
Sounds to me the issue caused by this flag was logged (or occurred and not logged) BEFORE it started outputting 1500 lines per second.

Also why isn't the log written in an async thread or at least more than 'x' attempts to log in a second then logs a "999 log messages dropped" message?

**Comment by AenBleidd** [comment]
Closed as a duplicate of #3592
