### ISSUE TITLE
Help to install Boinc in bionicpup64 8.0

### ISSUE THREAD

**Issue by jef33usa** [BOINC/boinc#3958]
**Describe the bug**
Help to install Boinc in bionicpup64 8.0

**System Information**
 - OS: 
 - BOINC Version: 

Distro: bionicpup64 8.0
Window Manager: JWM v2.3.7
Desktop Start: xwin jwm

Development:
 Bash: 4.4.19
 Geany: 1.33
 Gtkdialog: 0.8.4
 Perl: 5.26.1
 Python: 2.7.15rc1
 Yad: 0.40.0 (GTK+ 2.24.32)
 --
 busybox: 1.29.3
 dhcpcd: 6.6.2
 Glibc: 2.27
 OpenSSL: 1.1.0g  2 Nov 2017, built on: reproducible build, date unspecified
 wpa_supplicant: 2.6

**Additional context**
I need help to install Boinc in bionicpup64 8.0

**Comment by AenBleidd** [comment]
@jef33usa, I suggest you to write on Discord to #help channel: https://discord.gg/wPRafUq
