### ISSUE TITLE
C++ coding standards documentation

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3969]
It would be helpful for this project to document standards for its C++ codebase, [like LLVM does for example](https://llvm.org/docs/CodingStandards.html).

**Comment by AenBleidd** [comment]
It is documented here: https://boinc.berkeley.edu/trac/wiki/CodingStyle

Yes, it should be updated but you already could use it

**Comment by AenBleidd** [comment]
There is currently nothing to do here
