### ISSUE TITLE
Remove "drupal" folder

### ISSUE THREAD

**Issue by jensdenbraber** [BOINC/boinc#3971]
I would assume that the old BOINC website would be located in the **"drupal"** folder. I think that this can be removed to clean up te repo. The current website is located here: [https://github.com/BOINC/boinc-site](https://github.com/BOINC/boinc-site)

**Comment by AenBleidd** [comment]
`drupal` folder contains project template website.
https://github.com/BOINC/boinc-site is a BOINC website ( https://boinc.berkeley.edu/ ) If I recall correctly

**Comment by ballen4705** [comment]
I think this is the web site code used by Einstein@Home.  It would be nice to leave it in the BOINC distribution, in case others want to use it.

**Comment by brevilo** [comment]
ballen4705 is right. The `/drupal` folder contains the generic Drupal incarnation of the BOINC web code and projects are free to try it. There's no "official" support for it, though, and the only production deployment of it can be seen at Einstein@Home. 

BOINC's standard web code resides in `/html`.
