### ISSUE TITLE
Read config files does not update CPU/GPU usage automatically in status line

### ISSUE THREAD

**Issue by Vulpine05** [BOINC/boinc#3974]
**Describe the bug**
The description of the CPU/GPU usage in the status line of BOINC Manager for a task does not update in real time when these values are modified in an app_config file.  The app_config file is read correctly, and the CPU/GPU usage as dictated in the app_config file are followed, but the description in the status line does not update after the app_config file is re-read.  This applies to both active and inactive tasks.

The correct CPU/GPU usage will not update until you exit BOINC and then run it again.

**Steps To Reproduce**
1.  BOINC Manager running in advanced view.
2.  Open an app_config.xml file for a project.
3.  Revise <cpu_usage>0.5</cpu_usage> to <cpu_usage>1.0</cpu_usage>.
4.  Save app_config.xml and close.
5.  In BOINC Manager, open "Options", click on "Read config files".

**Expected behavior**
I would expect the 0.5 CPU + 0.5 GPU to revise to display "1.0 CPU + 0.5 GPU" within a reasonable amount of time.

**System Information**
 - OS: Windows 10 Home, Version 2004
 - BOINC Version: 7.16.7

**Additional context**
Switching between advance/simple views, or showing all/active tasks does not update to the correct CPU/GPU usage.

**Comment by davidpanderson** [comment]
app_config.xml files are read only when the client starts.

**Comment by RichardHaselgrove** [comment]
No, they're not. I've frequently made the changes that @Vulpine05 describes: app_config.xml files are read **and acted upon** when the 'read config files' menu is invoked.

The display is updated for new tasks received from the project server, without restarting the client.

The only time a client restart is required is when an app_config.xml file is removed.

**Comment by RichardHaselgrove** [comment]
I had a private email overnight, inviting me to double-check my facts. Fair enough. These two screenshots, taken about a minute apart, tell the story.

![Screenshot at 2020-08-17 11-14-58](https://user-images.githubusercontent.com/14886436/90388027-1968fa00-e07f-11ea-8f01-0be8ddadb884.png)
(Screenshot at 2020-08-17 11-14-58)

![Screenshot at 2020-08-17 11-16-01](https://user-images.githubusercontent.com/14886436/90388050-24238f00-e07f-11ea-8f16-0feded9fe8aa.png)
(Screenshot at 2020-08-17 11-16-01)

The only action taken between the two images was 'read config files' - I had pre-prepared an app_config.xml file for Einstein, changing CPU and GPU counts from 0.01/1 to 1/0.5

Note that the third (cached) Einstein task started running immediately, and a fourth Einstein task was downloaded, displaying the new settings, and also started straight after download. Event Log (summarised) attached.

[App_config log.txt](https://github.com/BOINC/boinc/files/5083757/App_config.log.txt)

I also discovered, along the way, that app_config.xml files are read and acted upon when the Event Log settings are changed in the GUI. Go figure.

**Comment by Vulpine05** [comment]
Thanks for confirming, @RichardHaselgrove.  I have noticed the new tasks were using the updated CPU/GPU usage, too, but I wasn't able to confirm when I posted the issue.  What you have described matches what I have been experiencing.

**Comment by sirzooro** [comment]
I logged the same issue in the past: https://github.com/BOINC/boinc/issues/1903

**Comment by MaxMaximus** [comment]
Yes, i also see such behavior each time i edit app_config.xml   - BOINC miss information update of task display in work queue after apply new setting from a app_config.xml.

Only minor correction/addition - WUs status updates after BOINC restart and for NEW (downloaded after config update and re-read) it updates immediately without restart. But it does not update status for any WUs which were already present in work queue before config update.

**Comment by Vulpine05** [comment]
Duplicate of #1903.
