### ISSUE TITLE
upload optional if error

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#40]
**Reported by KSMarksPsych on 22 Nov 37296654 18:13 UTC**
Posted by:
Date: 7:27 PM 10-13-2005
add a `<no_upload_if_error>` element to `<file_info>`. If present, don't upload the output file if result error. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/40

**Comment by ChristianBeer** [comment]
If there is a project that needs this please open a new issue with more information.
