### ISSUE TITLE
Check VirtualBox version prior to installation

### ISSUE THREAD

**Issue by Vulpine05** [BOINC/boinc#4009]
**Describe the bug**
When installing BOINC with VirtualBox, the installer overwrites whatever version of VirtualBox is presently installed, even if it is newer.

**Steps To Reproduce**
1.  Uninstalled BOINC.
2.  Installed VirtualBox 6.1.14.
3.  Installed BOINC 7.16.11 with VirtualBox 6.1.12.  I accepted prompts to install VirtualBox.
4.  After installation was complete, I checked VirtualBox, and found the version is 6.1.12.

**Expected behavior**
Either VirtualBox would have remained at version 6.1.14, or the installer would have at least asked if I wanted to downgrade to the older version.

**System Information**
 - OS: Windows 10 Home, Version 2004
 - BOINC Version: 7.16.11

**Additional context**
To be fair, I wondered if this was a VirtualBox problem, not a BOINC problem.  After re-installing 6.1.14, I downloaded a copy of 6.1.12.  It installed without asking if I wanted to overwrite the newer version.  Still, I would think that the BOINC installer could make this version check and prompt the user if this is what they want to do?

**Comment by tristanolive** [comment]
The BOINC installer can do this. I know where the setting is for it, but changing it does not seem to make a difference for me in the .ism file. (It looks like the property is in a .prq file outside of the repository).

This should be the process to make the change, at least:

1. In the InstallShield project, find the Oracle VM VirtualBox entry under "Redistributables"
2. Right-click and "Edit Prerequisite"
3. Select the Conditions tab
4. Add a condition with the following parameters:
   - Type: A registry entry has a specified version value
   - Registry key: HKEY_LOCAL_MACHINE\SOFTWARE\Oracle\VirtualBox
   - Registry value name: VersionExt
   - Registry value data: (VirtualBox version included with the BOINC package)
   - Run this prerequisite if: Data on target system is less than specified data
   - Check the following registry: 64-bit

Then it just needs to be included in the repository somehow.

**Comment by davidpanderson** [comment]
This condition was already there, but the selected registry was "default" rather than 64-bit,
and I guess this cause it not to work.  I changed it; will be in next release.
 
The .prq file is in the Installshield VM, in
C:/program files/InstallShield/2011/SetUpPrerequisites 
I added this to the BOINC repo, as win_build/installerv2/Oracle.... .prq

**Comment by AenBleidd** [comment]
Fixed in e36f86de8f451b20f2cb071c76c72694328b1475
