### ISSUE TITLE
Is HTTP/2 enabled on the server side?

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#4015]

**Comment by davidpanderson** [comment]
Where would this come into play?

**Comment by Rytiss** [comment]
It would be an option that projects themselves would have to configure in their web server software of choice (most likely Apache). It does have some optimizations regarding multiple assets being requested when browsing the webpages (no need to make separate connections, and the server could choose to send assets without client explicitly requesting them), but the performance impact to the scheduler operation would be minimal if any at all.

**Comment by AenBleidd** [comment]
@lfield, could you please verify that?

**Comment by lfield** [comment]
As far as I understand, the configuration of the Web server is under the control of the project.
