### ISSUE TITLE
Non-root users

### ISSUE THREAD

**Issue by wiedenhoeft** [BOINC/boinc#4016]
It is unclear (at least to me) from the documentation if BOINC works in an environment where the person responsible for running BOINC (i.e. attaching projects, set CPU usage etc.) is not the administrator. In big organizations, individuals might have the approval of the higher-ups, and have the software installed by the admin for them, but might otherwise be asked to leave the IT department alone as much as possible so as to not tie up company resources.

I actually find myself in this situation, and from the fact that the Berkeley installer (which did not work for me) does not require root privileges I assumed that this would not be an issue. I was even added to the boinc group, yet I still cannot attach any projects or run benchmarks.

I would like to request that this use case be made explicit in the documentation (or easier to find), or that such a use case be supported if it is not.

**Comment by davidpanderson** [comment]
I'd definitely like to offer a BOINC installer for Linux that doesn't require root privileges.  That's the goal of the self-extracting archive offered on the download page.

To do this, we need to build binaries with static linkage to any libraries not included in base Linux distros.  I'm not sure this is possible for the Manager, but it should be possible for the client and boinccmd.

I'm interested in working on this, preferably outside the autoconf framework, but I'm not a Linux expert.  If anyone wants to help with this, please let me know.

**Comment by davidpanderson** [comment]
The client's main dependency is Curl, which in turn uses a lot of other libraries.  It might be good to build our own Curl with features not used by BOINC disabled.

**Comment by AenBleidd** [comment]
@davidpanderson, hm, maybe it would be possible to use [vcpkg](https://github.com/microsoft/vcpkg) then?
They have curl build that could be configured: https://github.com/microsoft/vcpkg/blob/master/ports/curl/CONTROL

**Comment by davidpanderson** [comment]
Is that useful for Linux?

**Comment by AenBleidd** [comment]
Unfortunately, I can't answer this question. It could be used on linux with no issues but how is it useful - I don't know because I'm not using linux a lot anymore. 
For VS2019 we're already using vcpkg to build 3rdparty libraries and for me it's faster and easier than in was before.

**Comment by AenBleidd** [comment]
In order to install and use the software you need to be the owner of the hardware.
If you are using company hardware, and you are not allowed to install anything on it - you should not do it in any case.
I don't see reasonable to support so-called 'portable' installations since the provided installers are fits the purposes of the majority of our users.
Closing this without any further actions.
