### ISSUE TITLE
Can't use new database connection in create_work function

### ISSUE THREAD

**Issue by ashirao** [BOINC/boinc#4032]
**Describe the bug**
The following line of code in tools/backend_lib.cpp hard codes the use of boinc_db database connection defined in boinc_db.cpp. This prevents an application from using its own database connection for creating workunits via create_work function. Furthermore, the application may crash when boinc_db.mysql is not initialized.

backend_lib.cpp:388             
`wu.id = boinc_db.insert_id()`

The line should be replaced with the following:

backend_lib.cpp:388             
`wu.id = wu.db->insert_id();`

**Steps To Reproduce**
1. Define a database connection for inserting information about workunits into the mysql database. Database connection must be initialized

```
DB_CONN dbconn;
dbconn.open(db_name, db_host, db_user, db_passwd);
```

2. Pass the database connection to a workunit (wu)

`DB_WORKUNIT wu = DB_WORKUNIT(&dbconn);`

3. Pass the wu to create_work function 

```
create_work(
        wu,
        in_template,
        path,
        config.project_path(path),
        infiles,
        2,
        config
    ); 
```

**Expected behavior**
create_work function should update the mysql database using dbconn and not boinc_db database connection. 

**Screenshots**
NA

**System Information**
 - OS: ubuntu 18.04
 - BOINC Version: 7.17.0

**Additional context**
NA

**Comment by tomasbrod** [comment]
Possible other instances: `credit.cpp:write_modified_app_versions`, `sched_util.cpp:min_transition_time`.
