### ISSUE TITLE
Redesign for BOINC

### ISSUE THREAD

**Issue by yairamsalem** [BOINC/boinc#4034]
My name is Ido Kislev. I’m an 18 years old graphic designer, political adviser, and Wikipedia editor (since I was 10, one of the youngest in the world), and I don't know English very well so please excuse me for my bad grammar :)

For many years I really liked the idea of Boinc, and I’ve always installed it on my computers, But one of the things that always annoys me tho, is the design. 

The icon of Boinc is something that always on my Dock, it appears on billions of screens around the world, and it's… well, not a masterpiece. My grandpa (Prof. Mordechai E. Kislev) and most of my family from my dad's side are scientists and academic people. Except for MIT, I’ve never met any academic organization with a modern design language. But I love Boinc very much, I want this project to succeed even more, and I really want it to be an example of what a scientific project should look like. 

I want to offer myself, non-profit, as a designer. I want to rebrand this whole thing. I want it to be featured in Brand New, Dieline, CreativeReview. I want it to be mention in circles that never thought they will talk about it. I want to create a design system based on the values and aesthetics of Metro, Tumblr, Anthology Of Emo, Dropbox, and ComedyCentral designs. I promise it’s the beginning of history. And here it is:

![BOINC](https://user-images.githubusercontent.com/37295566/94348394-90ad8880-0044-11eb-8e1b-b613824ad7a0.png)

When designed more like a commercial brand, BOINC will be able to become a beautiful and mainstream brand that everybody who will come across it will love to meet, install and see on their home screens. It will be known as a brand that helps. A brand that matters. A brand with purpose.

![BOINC icon](https://user-images.githubusercontent.com/37295566/94348943-13384700-0049-11eb-870e-33676d9a21e4.png)

With this design, people will enter the website understanding right away what BOINC is and why they should install it. From first sight at someone's story (share option for all the major social media outlets is critical and very important) until the moment of installation, the graphic tools, the language, the whole experience of BOINC will be desired. 

While I’m still not sure about the fonts and colors, I really believe in this icon, idea, and design system. It's an easily recognizable and memorable icon and full of character and meaning. While the current website and graphic design are a sketch, with placeholder texts and beta fonts, I think that such a redesign it's almost our duty, especially in these dangerous times. After all, as more people will use BOINC, more quickly global and important problems will be solved. I will happy to hear your thoughts, and I'm all hope that BOINC will choose this promising path :)

**Comment by adamradocz** [comment]
I agree that the design could be updated, but I think the original concept is more straightforward and appealing.

**Comment by yairamsalem** [comment]
The design can be changed through the way but I think, for the sack of the project and it's publicity, redesign based on this general guidelines can be a massive difference. Is there a process of voting or something to move it forward?

**Comment by AenBleidd** [comment]
There is no plans to do any redesign. Closing this for now.
