### ISSUE TITLE
Rewrite MySQL/python interface

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#4039]
The python scripts that access the DB (create_project, update_versions) use a module called MySQLdb
(these scripts were written in 2003; that was the only option at that point).
MySQLdb doesn't work with Python 3 and as far as I can tell is unlikely to in the future.

So we need to use something else.  I think the best candidate is Mysql Connector/Python:
https://dev.mysql.com/doc/connector-python/en/

The other issue is that the DB interface code (py/Boinc/db_base.py)
was largely borrowed from a class project in an undergrad DB class or something.
It has fancy logic to cache DB rows and to auto-fetch rows pointed to from other tables.
We don't need any of this stuff; it complicates the code and should be tossed.

**Comment by lfield** [comment]
One thing to consider is whether we would like to go all the way use a Web development framework such as Django or Flask.

**Comment by davidpanderson** [comment]
Fixed in #4043.  Turns out the the "mysqlclient" module (for Python 3) has the same interface as the MySQLDB module.
