### ISSUE TITLE
Installation process says it failed despite completing on Apple Silicon

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#4040]
The installation succeeded and it launched BOINC Manager after, despite showing this error message (macOS 11.0 Beta (20A5374i)):
![Screen Shot 2020-09-28 at 6 16 12 PM](https://user-images.githubusercontent.com/1305957/94501717-5c0e0e00-01b7-11eb-9f32-e374123b0cb0.png)

**Comment by AustinConlon** [comment]
I'll close for now, I experienced this when installing Apple's SF Symbols app which leads me to believe it's a system bug.

**Comment by CharlieFenton** [comment]
@AustinConlon: During installation, you can press command-L and command-3 to open the installer log window and enable a full installer log. Before closing the installer, click on the Save button at the top right of the log window to write it to a file. If you need help interpreting it, send it to me. You can toggle between showing errors only and full log in the top right of the log window. But if you are sending me the log, please send the full log.
