### ISSUE TITLE
Use snap for Linux install

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#4042]
Snap is an alternative to dpkg-based software distribution on Linux.
It has features that may be useful for BOINC:
https://snapcraft.io/blog/a-technical-comparison-between-snaps-and-debs

**Comment by truboxl** [comment]
Duplicate? https://github.com/BOINC/boinc/issues/2485

**Comment by AenBleidd** [comment]
Closed as a duplication of #2485
