### ISSUE TITLE
Secure connection to Boinc for Android to Client, in this case BoincTasks

### ISSUE THREAD

**Issue by efmer** [BOINC/boinc#4044]
I'm working on Boinc for Android, specially the external GUI calls.
That is implemented right now.
I looked at the current authorization used between the BOINC Client and the BOINC Manager and BoincTasks.
One option was to make a secure socket connection, but that turned out a pain to implement.
So I opted for a AES GCM exchange over the regular socket.
That way it's easy to implement and should be as safe as a secure socket connection and certainly better than the current insecure method.
For now only the password exchange is encrypted, but at a later point the whole communication layer could be encrypted.

**Comment by AenBleidd** [comment]
Assigned to @efmer

**Comment by efmer** [comment]
Finished implementing.
Right now BoincTasks 1.82 is able to connect with an encrypted password.
The "old" connection method is supported as well. 
Together with a connection matching lock  and an approved IP on both sides should even make the "old" method OK to use if handled properly.

**Comment by AenBleidd** [comment]
@efmer, I see no PR from you. Did you manage to fix this on BointTasks side without changing boinc client?
