### ISSUE TITLE
7.16.16 Size of the font for the tabs in Advanced view scales badly with the rest of BOINC Manager

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4073]
7.16.16
All right, so the font size for the tabs has been adjusted and now the text fits. But the text size is the same whether I use a small window of BOINC Manager or a screen filling one (3840x2160). 

I mean... just look at it. Does this scale correctly? 
https://i.ibb.co/kJzY7J1/7-16-16-tabs-font-size-1.png
https://i.ibb.co/PMkVdP8/7-16-16-tabs-font-size-2.png

**Comment by BryanQuigley** [comment]
Don't all Fonts in BOINC not scale with window size (isn't that most apps?)?  If the font is readable in the smaller image wouldn't it be readable in the expanded one?
