### ISSUE TITLE
Consolidate "Tools" menu items into the "File" menu?

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#4078]
What do you think of perhaps bringing all or some of the "Tools" menu items into the "File" menu? At first I expected  "Add project..." to be under "File."

File:
![Screen Shot 2020-10-31 at 11 36 42 PM](https://user-images.githubusercontent.com/1305957/97796675-4fc00b00-1bd2-11eb-825f-cf1550750885.png)

Tools:
![Screen Shot 2020-10-31 at 11 36 34 PM](https://user-images.githubusercontent.com/1305957/97796677-551d5580-1bd2-11eb-9c68-2a5d91422ca1.png)

**Comment by CharlieFenton** [comment]
I don't have an opinion about this, but I want to point out that this is not specific to MacOS. BOINC has the same GUI, including the menu layout, on all desktop computer platforms, including MacOS, Windows and Linux, and of course we want to ensure that the GUI remains the same across all platforms. So if we decide to change it for Macs, we will also want to change it for the others.

The GUI is implemented using wxWidgets specifically to make it cross-platform. I suggest you remove "MacOS" from the title of this PR.

**Comment by AenBleidd** [comment]
I'd not move any menu anywhere: people are already used to find them where they are located now. Don't be like Microsoft that used to move buttons in there toolbars in Office applications every release so after upgrade you have to spent several days to find menus that were moved and you have no idea where.

**Comment by davidpanderson** [comment]
I agree with @AenBleidd

**Comment by AustinConlon** [comment]
Got it, didn't know the menu bar was also the same across platforms.
