### ISSUE TITLE
Apple Silicon CPU load much lower than limit specified in BOINC

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#4079]
![Screen Shot 2020-11-02 at 1 17 14 AM](https://user-images.githubusercontent.com/1305957/97851016-a6e4df00-1ca9-11eb-92e6-9ef9685ae508.png)
![Screen Shot 2020-11-02 at 1 19 57 AM](https://user-images.githubusercontent.com/1305957/97851021-a8160c00-1ca9-11eb-86da-e4e6f5d1fb83.png)

**Comment by AenBleidd** [comment]
Why do you think it's BOINC but not WCG application that doesn't use the core for 100%?

**Comment by CharlieFenton** [comment]
_Use 100% of the CPUs_ means use every CPU, not keep all CPUs 100% busy. BOINC is using 8 CPUs. If the computer has 8 CPUs, then it is using 100% of the CPUs (that is, all 8.) BOINC cannot run more than one task on each CPU. (One exception is for GPU tasks which can use part of a CPU; I believe they can share a CPU.)

The _% CPU_ column in the Activity Monitor display shows what portion of each CPU core's cycles is being used by each process. That is different from the setting in BOINC's Computing Preferences.

**Comment by AustinConlon** [comment]
I was only referring to the "% of CPU time."

**Comment by Ageless93** [comment]
The N% of CPU time is the maximum CPU load that the project's science
applications can use, it's not that this is the maximum the science
application must always use.

**Comment by CharlieFenton** [comment]
> I was only referring to the "% of CPU time."

Sorry, my oversight. To add to the comment from @Ageless93, there are many reasons why BOINC projects might not be able to use 100% of CPU time. The operating system needs some CPU time to perform its various housekeeping tasks and other duties, apps may be waiting for disk I/O to complete, there are typically many background tasks that require a slice of time, etc. 

BOINC project apps usually run at a very low process priority in order to have minimum impact on the responsiveness of the system and on the system's ability to perform other functions.

**Comment by SETIguy** [comment]
I don't know much about Apple's ARM cores, but some of the ARM CPUs used in
mobile devices are asymmetric, meaning not every core has access to the
same resources, and that can result in low usage numbers (using standard
unix definitions of process states) when a process waits to be transferred
to a core with the appropriate resources.  For an extreme example, if a
(hypothetical) processor has 8 cores and 1 FPU, if we run 8 floating point
intensive apps it could show up as about 12.5% (total) usage or 100% usage
depending on how the kernel views the architecture (does the process stay
in the run state while waiting for the FPU or in a wait state).  It's also
possible that there is contention for resources across threads on threaded
processors.  On intel linux such contention is handled without changing the
process state, but it doesn't need to be handled that way.

Can you guess that I've had this argument with android apps before?



-- 
Eric Korpela
korpela@ssl.berkeley.edu
AST:7731^29u18e3
