### ISSUE TITLE
Battery and Activity Preference on Named Venues Broken

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#408]
**Reported by Alinator on 29 Aug 37757249 11:33 UTC**
Refer to this Post in the Web Interfaces Message Board.

http://boinc.berkeley.edu/dev/forum_thread.php?id=2156

Alinator

Migrated-From: http://boinc.berkeley.edu/trac/ticket/426

**Comment by romw** [comment]
**Commented by Ageless on 8 Aug 38195791 13:46 UTC**
Setting specific options such as "Suspend work while computer is in use?" in the separate venues is broken. Both in the older code (such as Einstein@Home uses) and in the newer code (that some new projects use). Seti seems to be unaffected. [[br]]

Trying to set up a venue with "Suspend work while computer is in use?" to Yes, then updating the changes on the website, always shows that the option has jumped back to the default No.

**Comment by ChristianBeer** [comment]
Should be fixed in latest servercode.
