### ISSUE TITLE
Add support for Wine on Linux

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#4080]
Wine allows to run Windows apps on Linux. Some projects (e.g. Gerasim) have Windows apps only, what is inconvenient for people who run Boinc mostly on Linux machines.

Some time ago BOINC Mgr started supporting Windows Subsystem for Linux, to allow running Linux apps on Windows. You probably can partially reuse this code to support Wine on Linux.

**Comment by AenBleidd** [comment]
Not sure if this is really needed: Gerasim is the only project that has Windows only applications.
I thought about this before and not sure that this worths it

**Comment by sirzooro** [comment]
RakeSearch project also has Windows-only app, now it helps Gerasim with calculations.

**Comment by truboxl** [comment]
Unlike WSL which usually just two major versions, Wine have several, so some thoughts:

1. I think projects should just package their Windows app as a thin Wine app if they do not intend to make a native Linux app.
There's no telling which Wine version will break the project app. Be it runtime errors or result inaccuracies...
Multiply by the fact that each distro ships their own Wine patches, debugging is hard.
BOINC on Wine doesn't even work properly till this day.

2. A proper approach should be following what Valve did with SteamPlay + Proton. Each game have their own Wine version tested and approved for use. But whether BOINC want to do heavy lifting is out of the question.

3. Another approach is asking users to ABUSE `binfmt_misc` without needing to modifying the source code.
A seamless execution of Windows app on Linux is possible.
I just did a test on WSL and its working (Linux BOINC inside WSL spawning Windows tasks on real Windows) thanks to:
```
$ paste /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /tools/init
flags: F
offset 0
magic 4d5a
```
Change that to `/usr/bin/wine`, Linux BOINC client use Linux calls, Wine act as an interpreter, profit.
However, that will open up another can of worms: supporting cross platform, maybe even cross architecture with QEMU, or even possibly "Rosetta2" on Linux.

**Comment by AenBleidd** [comment]
@truboxl, still not sure that this is needed: imho compile cross platform application is still easier and more stable for Projects than do so much support to be able to run Windows applications on Linux. Regarding cross architecture, it's definitely not needed: I saw no OSX specific applications. According to what I see now, only Android has less Project support than OSX so I see no reason to do such weird stuff

**Comment by cminnoy** [comment]
Another approach is to support native docker on the host. Docker containers are now supported using VirtualBox. The process here is that the BOINC client downloads an iso that boots inside the VirtualBox of the client. The iso containing the distro, then pulls docker images into the VM and starts running. That mechanism can already be used to support windows applications using Wine. The develper just has to put Wine in a docker and voila. The downside here is that VirtualBox can't handle GPU tasks.
BOINC doesn't do (as far as I know) real docker containers on the host machine. If that was possible, you can use Wine AND you can also have access to the GPUs.

**Comment by AenBleidd** [comment]
Closed as not needed
