### ISSUE TITLE
[Manager] Windows x64 memory leaks to investigate

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4083]
During the Debug session VS2019 reports some memory leaks. They are not critical but should be investigated someday.

[Report](https://drive.google.com/file/d/1iFkBhAqFPgBlfrQn5zt3WxNusyrTAB0i/view?usp=sharing)

**Comment by davidpanderson** [comment]
Those may not be memory leaks.
When the manager makes a GUI RPC (for example, get_state())
it passes a structure (CC_STATE) containing vectors of pointers to
dynamically allocated objects.
get_state() deletes these objects, then creates new ones.
So at any given point, the manager's CC_STATE object will have lots of
dynamic objects;
that may be what is being reported here.

**Comment by AenBleidd** [comment]
Yeah, I believe you're right. I just saw this huge report and wanted to save it for myself to take a look someday and understand whether we really have a memory leak here or it is just a false positive detection.

**Comment by AenBleidd** [comment]
Should be revisited later with the latest codebase
