### ISSUE TITLE
[Draft] [Android] Investigate how to move project executables to RO folder

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4089]
Starting from API 29 all executable binaries should be inside 'lib' folder that is RO.
Current BOINC client relies on the workflow when executable binaries are located near project tasks data and are copied (directly or via softlink) to slots directory.
Since we have no possibility to execute any code from writable directory, this workflow should be changed to use softlinks only.
Also all project files should be opened via full path only (or at least to rely on executable file location).

**Comment by davidpanderson** [comment]
"plugin" systems for Android.  I have no idea what they do, but might be worth looking at.
https://github.com/didi/VirtualAPK
https://github.com/Tencent/Shadow
https://github.com/Qihoo360/RePlugin

**Comment by AenBleidd** [comment]
@davidpanderson, thank you. I'll do a research this week

**Comment by Jordan-Hall** [comment]
@AenBleidd  did you make any progress with this?

**Comment by AenBleidd** [comment]
This whole story is currently on hold. Why are you asking?

**Comment by Jordan-Hall** [comment]
Because I've been looking into fixing Android APK version using applicationInfo.nativeLibraryDir

**Comment by AenBleidd** [comment]
This is just a piece of the story. If you want to help - let's discuss it on Discord

**Comment by Jordan-Hall** [comment]
Whats the link to the discord? Never joined boincs discord

**Comment by AenBleidd** [comment]
@Jordan-Hall, https://discord.gg/wPRafUq

**Comment by AenBleidd** [comment]
I decided not to continue with this issue.
