### ISSUE TITLE
Use number of cores, not number of  "cpus", for task allocation

### ISSUE THREAD

**Issue by hwpfeil** [BOINC/boinc#4096]
Using a Ryzen 7 CPU with 8 cores and 2 threads per core, boinc launches 16 simultaneous tasks, each with 2-3 threads. Boinc quickly exhausts system resources, particularly when compiling the kernel or vulkan sdk at the same time.

Instead of swamping the system with 32 or 48 simultaneous threads, do not use the number of processors returned by /proc/cpuinfo to determine how many tasks to launch, use the number of cores and the number of threads per core to determine available resources per task. Boinc should launch #tasks = #cores, not #tasks = #available processors. 

**System Information** 
 - OS: Linux
 - BOINC Version:  7.17.0 x86_64-pc-linux-gnu

For example, rosetta launches tasks with 3 threads each or 48 threads with max_ncpus_pc=100 and cpu_usage_limit=100, my usual setting in the past. For rosetta, I have to set ncpus=25; for einstein, ncpus=50.

**Comment by AenBleidd** [comment]
Could you please provide a screenshot of 'top' that shows the situation you described? Thanks in advance

**Comment by RichardHaselgrove** [comment]
Not an exact comparison, but Rosetta for Windows also launches multiple threads:

![Rosetta threads](https://user-images.githubusercontent.com/14886436/99181376-0b7e5000-2726-11eb-8132-9dac08f98a5c.png)

In the Windows case, only one thread - the 'worker' thread consume significant CPU resources. This is a 4-core machine, and has many non-BOINC processes running: the most efficient worker thread performance possible would be 25%.

BOINC supports true multi-threaded apps with multiple worker threads, but in that case a project would specify an MT plan_class to prevent over-commitment of the CPU.

I agree, it can be useful to identify the cases where two threads occupy one core, or two cores share one FPU, but I think that's as far as we should go.

If anyone knows a graphical equivalent of Process Explorer for Linux, I could repeat the test.

**Comment by hwpfeil** [comment]
KDE/Plasma has ksysguard, which displays running processes. A recent rosetta task had 3 threads and used 4Gb ram. An obsolete method for determining processor cores reads /proc/cpuinfo line-by-line and each time it finds the word "processor" it increases the processor count. That method served well years ago before multi-threaded cores. Today you have to find the first line containing "cpu cores", which has the correct number of available cores. That is how many tasks boinc should launch for
`model name	: AMD Ryzen 7 1700 Eight-Core Processor`
'cpu cores	: 8`
To find out the number of available threads, in case you want a well-behaved program that launches only as many threads as are available, look for
`siblings	: 16`
With Rosetta's 3-threads per task, you really should launch only 5 tasks, because one more would exceed the "siblings" on an 8 core processor with each core running 2 simultaneous threads.

**Comment by AenBleidd** [comment]
According to your logic, you should have no more than 16 threads in the hole system.
As it was written before, Rosetta has only **one** core that do a heavy load. Other are just waiting for some synchronization. If in your case we will launch only 5 tasks of Rosetta, you will have 5 cores loaded and 11 cores idle. I'm afraid it's not the behavior we and you want to see. If every Rosetta application launch several threads that do a significant load for every single-breasted tasks - then it's a cheating. But I also run Rosetta for several years and never saw such behavior. So from my prospective everything is good, and the ticket could be closed. If you want to know why Rosetta launch several threads for every process but only one do a load - you should ask this question on their forum.

**Comment by hwpfeil** [comment]
You don't seem to understand the difference between CPU cores and active threads. 5 Rosetta tasks launch 15 parallel threads, a light workload. It is when each of those threads grabs 4Gb ram that the system grinds to a crawl, taking minutes just to get a command prompt in a konsole window to kill the threads and cease using the swap partition. Active disc r/w competing with system swap on the same drive is what overloads things. Your method of counting threads, or /proc/cpuinfo: siblings, as cores, then launching that number of tasks is what generates 48 parallel threads competing for the 2 threads on each of the 8 cores. Rosetta just grabs what resources Boinc allocates. Einstein, for example, launches 2 threads per task. 
Pay attention: this only happens on my Ryzen box. The AMD A6-9225 and AMD A6-5200 laptops in my render farm behave according to your perspective with no ludicrous system loads. It is not a client problem, It is only on the Ryzen 7 box that I have to set max_ncpus_pct below 100 in .boinc_data/global_prefs.xml.
Where did you get your Masters in Computer Science?

**Comment by AenBleidd** [comment]
Again: single threaded task has **one** work thread and could have several other threads **that don't generate any significant load**. We determine the maximum threads that we can run on particular CPU. Ryzen 7 has 8 cores (2 threads each) that mean that we can start **16** parallel tasks that have **one** main thread that do load. If you Rosetta application has more that 1 thread (per task) that generate workload - you should ask on their forum.

> Where did you get your Masters in Computer Science?
You can read this on my LinkedIn (link you can find in my profile).

**Comment by CallMeFoxie** [comment]
Looking at the screenshot posted above it clearly shows how much load has each thread done. One "lots" and the rest "none".

**Comment by CallMeFoxie** [comment]
Also
> taking minutes just to get a command prompt in a konsole window to kill the threads and cease using the swap partition. Active disc r/w competing with system swap on the same drive is what overloads things. 

is where your problem is. Do not enable swap if you want something to behave nice. Actually limit the max memory usage to the point where you start OOMing *before* running out of memory on the node itself.

**Comment by hwpfeil** [comment]
I'm sorry you don't understand the problem. I thought when I mentioned KDE, I implied that I'm talking about Linux systems. The above screen shot is from a Windows system. Windows is not Linux, and thereby hangs a tale. Go find someone who understands Linux systems programming. Obviously if it works on Windows, your code will work anywhere, according to your replies.

**Comment by Ageless93** [comment]
Vitalii asked you in his first post in this thread to show a screenshot of
'top' showing the situation at hand, thus far you haven't. Instead you're
becoming obnoxious and shouty.

But here's in a nutshell: BOINC doesn't do any science. That's done by the
projects science applications. If they for whatever reason don't play well
with what you expect them to do, first thing you do is ask at the project
what their intentions are. Maybe it's some fluke they don't know they do
yet.

But under no circumstances, even when it's highly entertaining, do you get
in here and start a yelling fest at the developers just because you think
you're not heard correctly. Certainly not when since the first post you've
neglected to serve any tangible evidence to your claim.

**Comment by AenBleidd** [comment]
> I'm sorry you don't understand the problem. I thought when I mentioned KDE, I implied that I'm talking about Linux systems. The above screen shot is from a Windows system. Windows is not Linux, and thereby hangs a tale. Go find someone who understands Linux systems programming. Obviously if it works on Windows, your code will work anywhere, according to your replies.

16 threads CPU on Linux is still 16 threads CPU on Windows. The same rule is applied to OSX and any other modern OS. So, if you have in preferences to use 100% of the CPUs, BOINC should run (in your case) 16 tasks max (here we're not talking about GPU and NCI tasks because they have special conditions) on **any** system: Windows, linux, OSX, Android.

And this CPU has the same amount of cores (and threads) on both Windows and Linux. So I don't need to be Linux system developer to count up to 16.

**Comment by RichardHaselgrove** [comment]
Yes, in posting the **Windows** screenshot, I made it clear that it was "not an exact comparison", but an example of the clear, factual, information that would enable us to understand your concerns and point you in the right direction.

` 5 Rosetta tasks launch 15 parallel threads, a light workload. It is when each of those threads grabs 4Gb ram`

(your words, from https://github.com/BOINC/boinc/issues/4096#issuecomment-731620270) My computer science training is admittedly out of date, but my understanding is that memory is allocated to the application as a whole, not multiple times to each separate thread. That's certainly how the Windows tools display it:

![Rosetta memory](https://user-images.githubusercontent.com/14886436/99901426-814a6480-2cae-11eb-823a-5940fe43bf13.png)
Notice also that both of the Rosetta tasks in that display use far less that 4 GB ram, but they do use different amounts: one is a dt_ task, the other is a niv_ task. Rosetta runs many different research projects in parallel, and your problem might relate to just one of them. If so, you should ask them to implement some form of selection process. That would be for the project to implement (some have), not for BOINC.
