### ISSUE TITLE
Why doesn't Mod apk work for chromecast?

### ISSUE THREAD

**Issue by lisacathey** [BOINC/boinc#4103]
Why doesn't Mod apk work for chromecast?
Last night I download Deezer Apk from this site [Deezer Premium Apk](https://deezerpremium-apk.com) . They said it works for Chromecast. But It didn't. And a pop up shows this apk doesn't not secure for my device. These type of apk are secure? Should I uninstall it?

**Comment by AenBleidd** [comment]
It's not a repo of Deezer application
