### ISSUE TITLE
Constant spamming of "No protocol specified" in journal

### ISSUE THREAD

**Issue by mystiquewolf** [BOINC/boinc#4114]
**Describe the bug**
Constant spamming of `boinc[1718]: No protocol specified` in `journalctl`

**Expected behavior**
Should not spam this error constantly

**System Information**
 - OS: Ubuntu 20.04.1
 - BOINC Version: 7.16.6

**Additional context**

**Comment by AenBleidd** [comment]
Closed as a duplicate of #2256
