### ISSUE TITLE
BOINC Crashes Computer with Mac OS 11 and BOINC 7.16.11

### ISSUE THREAD

**Issue by paulpickelmann** [BOINC/boinc#4122]
When I leave my computer, a MacBook Air idle and running BOINC it eventually crashes and reboots.

**Comment by AenBleidd** [comment]
@paulpickelmann, does this still happen? Could you please attach logs?
The behavior you described could be because of overheat. Try to decrease amount of CPUs available for BOINC.

**Comment by paulpickelmann** [comment]
His seams to be fixed as of Mac OS Big Sur 11.3.

  —  Paul
