### ISSUE TITLE
Travis CI is no longer free

### ISSUE THREAD

**Issue by truboxl** [BOINC/boinc#4123]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

travis-ci.org will be shutdown by 2020-12-31
free plan will become free trial
building for macOS requires credits

Other alternatives: https://ropensci.org/technotes/2020/11/19/moving-away-travis/

I am not sure whether BOINC is affected or not, so I created this issue for a discussion

**Comment by AenBleidd** [comment]
Me and @ChristianBeer are working on moving ci to GitHub actions

**Comment by AenBleidd** [comment]
Just for reference: https://github.com/ChristianBeer/boinc/pull/1
