### ISSUE TITLE
Add "Suspend when no mouse/keyboard input in last XX minutes" to local client

### ISSUE THREAD

**Issue by Stoobiedoo** [BOINC/boinc#4153]
**Describe the problem**
Most of the preferences are duplicated from the website to the local program. When setting "Computing preference - Using local overrides", the local preferences do not have the option:
Suspend when no mouse/keyboard input in last XX minutes 
This seems to be the only option that is not in both locations. In this case, even though the system may be using Local overrides, it still goes to the website to get this one preference.

**Describe the solution you'd like**
Implement the "Suspend when no mouse/keyboard input in last XX minutes" preference in the local client and do not go to website if local overrides are being used.

**Additional context**

![image](https://user-images.githubusercontent.com/6288850/105197783-d5789600-5af1-11eb-9e8f-558f79814632.png)
![image](https://user-images.githubusercontent.com/6288850/105197901-f640eb80-5af1-11eb-9ad9-b61996e7007a.png)

**Comment by CharlieFenton** [comment]
The website option "Suspend when no mouse/keyboard input in last XX minutes" is split onto 3 lines in local preference, to allow suspending CPU or GPU computation independently. The three lines are:
```
Suspend when computer is in use
Suspend GPU when computer is in use
In  use means mouse/keyboard input in last xx minutes
```
