### ISSUE TITLE
Ability to limit total number of workunits per day within a project

### ISSUE THREAD

**Issue by bearnol** [BOINC/boinc#4167]
Gracefully and optionally at the control of the project admin (config.xml?)
Also, preferably easily and safely back portable to older server instance(s)

**Comment by AenBleidd** [comment]
What is the idea behind this? Why this is needed?
What exactly you want to limit?
Number of workunits generated or sent or processed?

**Comment by bearnol** [comment]
Thanks for your message. Please see below for specific response(s)
J

Sent from my iPad

> On 25 Apr 2021, at 20:22, Vitalii Koshura ***@***.***> wrote:
> 
> ﻿
> What is the idea behind this? Why this is needed?
> 
To limit the load on a lesser-capable server.
> What exactly you want to limit?
> 
Total amount of work processed each day.
> Number of workunits generated or sent or processed?
> 
Number of workunits generated, and thus the number sent, and in turn the number processed (or at least that’s the idea :)

**Comment by davidpanderson** [comment]
This would be implemented by project-specific code in the work generator.
