### ISSUE TITLE
[Windows Installer] Remove not needed dlls

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4168]
**Describe the problem**
Since all necessary dependencies are linked now as a libraries, next DLLs should be removed from the installer
- libcurl.dll
- libeay32.dll
- msvcp100.dll
- msvcr100.dll
- ssleay32.dll
- zlib1.dll

**Describe the solution you'd like**
In best case there should be a custom step added to remove existing DLLs from the user installation folder.

**Comment by RichardHaselgrove** [comment]
> to remove existing DLLs

The existing uninstaller already does this. And uninstall is run as a precursor to any update. I think we're good to go.

**Comment by talregev** [comment]
We should create the installer on the ci, and test it as part of the tests. (manual tests i guess).

**Comment by AenBleidd** [comment]
There is no free version of InstallShield, so building this on CI currently is not possible.
There is already a task to rewrite installed on NSIS but it's not a top priority now.
So we just keep it as-is.
