### ISSUE TITLE
GPUs are underutilized

### ISSUE THREAD

**Issue by gjkisa** [BOINC/boinc#4172]
I dedicated a few NVidia Quadro K6000 GPUs to various projects. These GPUs are older but they are still monsters in GFLOPs performance with over 2800 compute cores. The newer boards have even more. In other words, the GPU pipeline can easily handle several kernels simultaneously. But, I barely see 15-20% GPU load on a single GPU task. Basically, the compute kernels launched do not have enough numeric complexity. I see the projects like Milkyway@home and Universe@home running GPU tasks for 3-5 minutes. 

What needs to happen is a better load balancer to launch more than one task per GPU. The current design will result in increasingly less resource utilization (or underutilization) as the hardware is becoming more and more powerful. 

I believe all NVidia and AMD compute cards report the computational load and memory utilization. Therefore, Boinc manager can launch automatically as well. But, it may be better to communicate with the user code about the resource needs. Therefore, the user code should be able to notify Boinc manager about the compute cores it will be taking for GPU tasks and additional tasks should be allowed by the Boinc manager up to total compute cores. 

In the short run, Boinc manager can readily start multiple GPU tasks on a single GPU and check the load on the GPU. In the long run, the user code should supply hints about the maximum load it will use in advance. 

Just a thought.

**Comment by AenBleidd** [comment]
By default it's a project who defines how much resources of GPU and CPU is used by their tasks. But you can easily change this if you think that your GPU can run more than 1 task: https://boinc.berkeley.edu/dev/forum_thread.php?id=13202&postid=93826

**Comment by gjkisa** [comment]
> By default it's a project who defines how much resources of GPU and CPU is used by their tasks. But you can easily change this if you think that your GPU can run more than 1 task: https://boinc.berkeley.edu/dev/forum_thread.php?id=13202&postid=93886

The message thread you pointed out suggests a manual configuration to launch two tasks on one GPU, not sure this is the right configuration, copying straight the example configuration; 

```
<app_config>
     <app>
         <name>hsgamma_FGRPB1G</name>
     <gpu_versions>
         <gpu_usage>0.5</gpu_usage>
         <cpu_usage>0.2</cpu_usage>
      </gpu_versions>
    </app>
    <app>
       <name>hsgamma_BRP4G</name>
    <gpu_versions>
        <gpu_usage>0.5</gpu_usage>
        <cpu_usage>0.2</cpu_usage>
    </gpu_versions>
   </app>
</app_config>

```

In any case, my point was automatically launching additional tasks on the GPU by Boinc Manager. I cannot babysit and adjust these manually...

Am I missing something here? Thx in advance.

**Comment by AenBleidd** [comment]
> In any case, my point was automatically launching additional tasks on the GPU by Boinc Manager. I cannot babysit and adjust these manually...

BOINC knows nothing about real GPU (or CPU) utilization by any task (or Project). So it uses values defined by Project developers.
We assume that they know why they are put these values and not other.

**Comment by RichardHaselgrove** [comment]
I don't think that's true. The guidance to project developers in https://boinc.berkeley.edu/trac/wiki/AppPlan says (at the end)

> In all cases (NVIDIA and ATI), the application is assumed to use 1 GPU, and the CPU usage is assumed to be 0.5% the FLOPS of the GPU. If there is a choice, the scheduler will give preference to later classes, i.e. it will pick cuda23 over cuda.

So, BOINC's in charge, but by way of an estimation, not a calculation. 

Hence my request for a better system in #2949.

**Comment by AenBleidd** [comment]
What I meant is that if Project set to use 1 GPU - we will use exactly 1 GPU and will not monitor during the runtime what is actual GPU usage and if it's lower than set - run one more GPU task on the same GPU.

**Comment by davidpanderson** [comment]
Fully using powerful GPUs is a good goal, but it's complicated:
1) "GPU usage" is two separate things: number of cores used, and amount of (video) RAM used.  The client can run additional GPU jobs only if they fit in both.
2) Are there cross-platform, cross-vendor APIs for finding usage info?  I couldn't find any last time I looked.
3) What if a job's GPU usage changes halfway through a job?  A RAM allocation request might fail because we're running other GPU jobs.

**Comment by gjkisa** [comment]
The first criteria is always the memory, but then the computational load. Most modern (gpu) hardware will queue the task and won't launch when the resources (memory and cores) requested are not available anyway. 

I copied and pasted the configuration above into the project directory (Milky Way), set the gpu_usage to 0.25 and cpu_usage (for gpu tasks) to 0.1. So, each NVidia K6000 card uses 4 tasks per gpu. It increased output by 4 times obviously, but the load on the gpu is still around 55-60% and memory usage is negligibly small. 

Each gpu can easily handle up to 5 tasks and sometimes 6, but that critical last 16% depends on the load (so that it does not exceed 100%) and it needs to be dynamically monitored (but it won't crash the gpu, but queued). I left it at 4 tasks per gpu for now because I cannot actively monitor Boinc, so the gpu is under utilized by 33% when its idle time is donated to Boinc projects. So, these inefficiencies can add up quickly... 

Most modern gpus (since 2010 and later) allow the load inquiries, it is not a rocket science. Instead of queueing, the task can be assigned to the next gpu board on the hardware. The servers I donated their free capacity to Boinc have all more than one K6000 cards on them (per motherboard). The newer compute cards have significantly more computation capacity (GP100 and GV100 compute cards), so I believe this is something you want to address better and optimally in the Boinc Manager. This will be increasingly needed more, not less...

I attached the script I used for milkyway here for reference; 

```
<app_config>
    <app>
        <name>milkyway</name>
        <gpu_versions>
            <gpu_usage>0.25</gpu_usage>
            <cpu_usage>0.1</cpu_usage>
        </gpu_versions>
    </app>
    <app>
        <name>milkyway_nbody</name>
        <gpu_versions>
            <gpu_usage>0.25</gpu_usage>
            <cpu_usage>0.1</cpu_usage>
        </gpu_versions>
    </app>
</app_config>

```

**Comment by gjkisa** [comment]
> Fully using powerful GPUs is a good goal, but it's complicated:
> 
> 1. "GPU usage" is two separate things: number of cores used, and amount of (video) RAM used.  The client can run additional GPU jobs only if they fit in both.
> 2. Are there cross-platform, cross-vendor APIs for finding usage info?  I couldn't find any last time I looked.
> 3. What if a job's GPU usage changes halfway through a job?  A RAM allocation request might fail because we're running other GPU jobs.

For #1: I agree, but the order should be first about allocating the memory, then launching on available cores though. Often we do the allocation and copy the data over the PCI pipeline to the GPU card while the other cores are busy and computing the existing jobs. This has been possible on most architectures to overcome the additional time it takes to copy data over PCI pipeline to GPU RAM (from the regular CPU RAM). If the GPU memory is not available, the task will have to wait. (more about this below)

For #2: Not sure it exists. Opencl is general enough, but cuda offers more features. Ideally, a Boinc API that abstracts the different GPU specs and features needs be developed at the task level (unless this is already available) and the tasks should be distributed based on the specs and features requested. So, the app developer should know exactly what to expect from the hardware. (memory, cores, computation interface such as cuda or opencl with version in the most broadest sense)

For #3: Most GPUs will queue the copy and compute requests (at least in opencl and cuda) until the resources become available, and then they will be run. Most hardware still support only one copy operation at a time over PCI, some support bi-directional copying now (but still one read and one write). So, it is better to queue the entire task on the other available cards (if there are more than one GPU cards on the same board), if they are free first, otherwise queue the task on one GPU. 

So, the point is that if the tasks know the initial specifications of the hardware, the resources will eventually become available for it to run on the hardware queue. So, the tasks should not hang waiting for resources forever, but ideally they may be killed, if the app is buggy and waits for more and more resources that will never become available (the hardware may gracefully fail the allocation requests to begin with).
