### ISSUE TITLE
Doc: add links for each build status badge

### ISSUE THREAD

**Issue by winkies** [BOINC/boinc#4174]
In README, when you click on build status it displays a svg image.
It will be nice that redirects to the corresponding Github Actions.

**Comment by winkies** [comment]
Something like [this](https://github.com/winkies/boinc/pull/3/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

**Comment by AenBleidd** [comment]
Looks good. Can you please open a PR?

**Comment by winkies** [comment]
Sure :)
