### ISSUE TITLE
No doxygen documentation

### ISSUE THREAD

**Issue by cminnoy** [BOINC/boinc#4184]
**Describe the bug**
As a starting coder you expect that the code base is well documented. Having doxygen files and insource documentation helps al lot. Lacking documentation is as bad as a bug. 

**Steps To Reproduce**
git clone boinc
See source code

**Expected behavior**
make doxydoc -> generated doxygen documentation

**Comment by winkies** [comment]
You can't expect to have code base well documented for almost 20 years old software.

For software development, you can find the documentation: [here](https://boinc.berkeley.edu/trac/wiki/SoftwareDevelopment).

[A Doxygen integration](https://github.com/BOINC/boinc/search?q=doxygen) for Drupal  seems to be done long time ago.

**Comment by cnergyone** [comment]
Reverse: You can't expect a 20 year old software which is still being used by hundred of thousand of people, with a growing community to NOT have good documentation.

**Comment by winkies** [comment]
We could discuss the need for documentation (based on tech choice, debt technical, format ...) but we won't do it.

If it really matters, please feel free to provide doxygen file and documentation ;)

**Comment by AenBleidd** [comment]
We have documentation on our wiki (link in the comment above) and soon plan to move it to GitHub.
There is no need to duplicate it in Doxygen format
