### ISSUE TITLE
Android BOINC 7.16.16, when notch enabled Android notification bar is blue. When notch disabled, Android notification bar is black

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4188]
Will add screenshots, or it didn't happen. ;)
Weirdly enough, the notch isn't even visible on the screenshot that has the notch enabled. 

But okay, my phone (Huawei P20 lite) has the option to enable or disable the notch that the camera lens lives in. When I have the notch enabled the top notification bar in Android is blue when BOINC is open. When I disable the notch though, the notification bar stays black when I open BOINC. This may be an Android thing though, because enabling the notch will increase the screen size to around the notch, while disabling it will just add a black bar there. That also changes colour when going to Settings for instance. 

Still, putting it out here in case someone else wants to report this (and therefore immediately set to wontfix). 

[Blue notification bar](https://ibb.co/xjfvcTT)
[Black notification bar](https://ibb.co/R4MZQKC)

**Comment by AenBleidd** [comment]
This is a desired behavior. Status bar uses the 'main' color of application (ours is blue). A lot of other applications act in the same way.
