### ISSUE TITLE
Android BOINC 7.16.16 crashes when doing anything else on my phone

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4197]
Doing anything else with my phone will crash BOINC.... Just anything.
Open a browser, and loading the BOINC forums, BOINC crashes and restarts (giving the notification that it just started).
Open Instagram and watching Mel's dailies, BOINC crashes and restarts (giving the notification that it just started).
Doing finance, BOINC crashes and restarts (giving the notification that it just started).

About the only thing I can open is my Gems or Jewels game app. 
Opening Google Play Store and updating my apps... do I need to say it? 

The earliest latest Log start is of 19:39:12

**Comment by RichardHaselgrove** [comment]
And of course there's no access to an archived stdoutdae.txt?

**Comment by Ageless93** [comment]
No, as I don't think #3328 ever made it into this version. But then neither did using the SD card for the data directory.

**Comment by Ageless93** [comment]
So now I have that BOINC will crash and restart even when I look at BOINC. It's mostly when something else wants to use a lot of CPU cycles, like video playback. I do sometimes see BOINC try to suspend and then crash & restart. So I assumed it had to do with the "Suspend when non-BOINC CPU usage is above N%", and first set it to 100%. That didn't help. Then set it to 0%, that didn't help either. It's still crashing and restarting. Maybe to do with the tasks it runs: Universe and Einstein.

**Comment by Ageless93** [comment]
At this moment BOINC Manager was crashing when I was trying to open the Event Log. For unknown reasons BOINC wants to suspend at times while it's on a charger, and since I still have some of those Universe tasks on here that are being calculated, so when BOINC suspends the suspending of these tasks takes over a minute and during that time BOINC manager will crash when I do anything with my phone. 

Apparently it'll do fine when one just charges their phone and doesn't touch anything. Or I have a hyper sensitive phone.

**Comment by Ageless93** [comment]
Okay, that BOINC suspends when doing anything else with my phone may be due to the hard-coded "don't compute while active" that I find in the event log. This is always showing, even when I have unchecked "Pause computation when the screen is on". 

It's visible on screenschot 5:
https://i.ibb.co/DCMk5xP/1.jpg
https://i.ibb.co/s1pgbn3/2.jpg
https://i.ibb.co/gjgV1Vh/3.jpg
https://i.ibb.co/Z2cVkVQ/4.jpg
https://i.ibb.co/mD37HTH/5.jpg
https://i.ibb.co/QpbzGp3/6.jpg

And here are my preferences: https://i.ibb.co/DLx2dmN/preferences.jpg

**Comment by talregev** [comment]
Do you have a [WUProp@Home](http://wuprop.boinc-af.org/) in your android running? 
I know it cause boinc to crush when it start, after I open it running, and it not crush any more, and everything continue as normal.
And It only for this project.

**Comment by Ageless93** [comment]
Nope, WuProp is not added on this phone. I only added the projects available through the projects list in BOINC, not any from external. All except for Asteroids as its server seems to be down again.

**Comment by AenBleidd** [comment]
Should be fixed by #4248

**Comment by AenBleidd** [comment]
This should be already fixed. If not - please reopen ticket after testing new release.
