### ISSUE TITLE
[Bug report] mali GPU not detected on android boinc 7.16.16

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#4204]
Add support in android gpu - mali gpu.
https://developer.arm.com/ip-products/graphics-and-multimedia/mali-gpus/mali-driver-development-kit
And Intel GPU:
https://software.intel.com/content/www/us/en/develop/tools/opencl-sdk.html

I can help to compile mali ddk on android, and I can help to compile opencl-sdk in windows and linux. 

-------------------------------------------------------------
After edit:
mali GPU not support on android boinc 7.16.16

**Comment by AenBleidd** [comment]
BOINC already supports this. If you want to help projects to build their application for these GPUs - please either write on their forums or use mailing list boinc_projects@ssl.berkeley.edu

**Comment by talregev** [comment]
If it already support it don't show any indication that it did. So even If a project have a binary that support it, it has no way to know. 
So I should report it as a bug.

**Comment by AenBleidd** [comment]
Do you have an example when BOINC client doesn't recognize any GPU?

**Comment by talregev** [comment]
Yes. I have many.

**Comment by Ageless93** [comment]
Mine is recognized, and BOINC asks for work for it on a regular basis from all projects, but since none have an application for the Mali GPU no work is gotten. I'm not so sure I even want my Mali GPU to be used without my phone having active cooling, because the GPU gets quite hot when in use (by for example my navigation app, it has overheated my phone already). 

https://i.ibb.co/s1pgbn3/2.jpg

**Comment by talregev** [comment]
I have Mali-G32. Did you install some driver?

**Comment by AenBleidd** [comment]
> I'm not so sure I even want my Mali GPU to be used without my phone having active cooling

You just need a tank with liquid nitrogen where you can put your phone overnight ;)

**Comment by Ageless93** [comment]
I did not install any driver, I have several devices with Mali GPUs that are detected by 7.4.53 without a problem. 
As for cooling, all my other Android devices are actively cooled. They lay on top of a cupboard in my living room with a 200mm case fan at 5V blowing cool air over them. 

That's a luxury I don't have in my car.

**Comment by RichardHaselgrove** [comment]
I'm sure my Samsung tablet had a Mali GPU when I bought it: in fact, it's still visible on my SETI account page https://setiathome.berkeley.edu/show_host_detail.php?hostid=8865273

> Coprocessors	OpenCL GPU Mali-G71 (1853MB) driver: 2.00

But that was then. Now, with v7.16.16, it reports "No usable GPUs found" at startup. But it still shows a preference not to use the not-GPU when the computer is in use, with no option in preferences to change that.

**Comment by AenBleidd** [comment]
I'll check this

**Comment by talregev** [comment]
Can we open the issue? 
I will change it to bug report.
Also I am using android boinc 7.16.16 and don't see the mali-gpu.

**Comment by AenBleidd** [comment]
Hm, one of mine devices has correct GPU recognition:
![image](https://user-images.githubusercontent.com/3234209/108552529-bb4cf600-72f1-11eb-92a6-eb7aaee78975.png)

**Comment by RichardHaselgrove** [comment]
If you look at the SETI account page I linked earlier, the other important bits are
```
Operating System | Android4.4.111-16611318 (Android 9)
BOINC version | 7.16.3
Last time contacted server | 12 Dec 2019, 9:27:38 UTC
```
SETI hasn't ever got an active scheduler now, so no more updates can be transferred into the database.

If v7.16.3 was able to detect a Mali, then so should v7.16.16. But the tablet was running Android 9 back then, and is running Android 10 now. Could that have affected GPU detection or utilisation?

**Comment by AenBleidd** [comment]
> Could that have affected GPU detection or utilisation?

Theoretically - yes.  I have Android 10 device, and neither 7.4.53 nor 7.16.3 nor 7.16.16 detects GPU on this device.
I'll debug it. I left this with low priority because anyway there is no any Project for Android
