### ISSUE TITLE
Android BOINC 7.16.16 "don't compute while active" is hardcoded and ignores preferences

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4221]
Despite me setting Non-BOINC CPU Usage to 0% or 100% (either should disable this preference) and having unchecked "Pause when screen is on", BOINC will suspend when the screen is on and I do anything on my phone while it's charging. 

The "[don't compute while active](https://i.ibb.co/mD37HTH/5.jpg)" line is being acted upon, it should follow the preference of "Pause when screen is on" and it doesn't. 

When I choose to use my phone while it's being charged, BOINC should follow the preferences set by the user and not follow its own plan.

**Comment by AenBleidd** [comment]
Mmm.... I believe here we need to write better instructions to the users.
Google requires now, that application stop any background activity when they are not on foreground (because of the better battery life, better user experience etc).
Not sure we can do smth with it.
I'll keep it in my backlog for now but maybe will then just convert it to write better instructions how to use BOINC nowadays.

**Comment by Ageless93** [comment]
This happens solely when the phone is being charged, so battery life shouldn't be in the equation. 
The line was also there (and acted upon) in 7.4.53, so it's not something new. 

Better instructions for the users don't help when you have preferences settings that are ignored by the application. Then you can just as well do away with options as "Pause when the screen is on/off" and "Pause when non-CPU usage is above N%" because BOINC will suspend anyway when you do something with your device.

**Comment by AenBleidd** [comment]
> This happens solely when the phone is being charged, so battery life shouldn't be in the equation.

It's just an explanation by Google why they force application in background to stop any valuable activity.

> Better instructions for the users don't help when you have preferences settings that are ignored by the application. Then you can just as well do away with options as "Pause when the screen is on/off" and "Pause when non-CPU usage is above N%" because BOINC will suspend anyway when you do something with your device.

If BOINC application stays on foreground - both of these options are valid (maybe "Pause when non-CPU usage is above N%"  not so much needed anymore but anyway)

**Comment by Ageless93** [comment]
So you can do away with all the preferences that allow BOINC to do work despite the device being in use then. Because it won't follow them anyway. I wonder what happens when the device is being charged, BOINC does work and the Google Play Store does an automatic update of apps. Will that also pause BOINC? Heck for that matter, won't BOINC just be stopped at any time if left alone because it does things in the background? 

(And maybe it does, and that explains #4219)

**Comment by AenBleidd** [comment]
> I wonder what happens when the device is being charged, BOINC does work and the Google Play Store does an automatic update of apps. Will that also pause BOINC?

If BOINC is on foreground and "Pause when non-CPU usage is above N%" not set - BOINC should continue working.

> Heck for that matter, won't BOINC just be stopped at any time if left alone because it does things in the background?

Yes, that's why we moved as much as we can to foreground. So if BOINC application is on foreground - all other processes launched by BOINC are on foreground too, so it should continue working.

> (And maybe it does, and that explains #4219)

Might be, but I need to do a proper investigation first before making any assumptions.

**Comment by AenBleidd** [comment]
Google limited background activity of applications (even when device is charging). So if application goes to background, soon it will be paused by the Android scheduler.
Both options are still valid for BOINC running on foreground.
When "Pause when screen is on" is unchecked, BOINC continue running with no issues.
When "Pause when non-CPU usage is above N%" is set and some core activity of Android happens, BOINC will be correctly pause.
Closing this as not an issue.
