### ISSUE TITLE
Android BOINC 7.16.16 copyright 2003-2016

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4223]
The copyright window on "About" states years 2003-2016

![copyright 2003-2016](https://user-images.githubusercontent.com/10869587/108627049-de8fb680-7453-11eb-866c-af86c2b98363.jpg)

**Comment by RichardHaselgrove** [comment]
On my tablet screen (10" / 25cm full HD - landscape orientation), this dialog is still truncated after "IBM Corporation and" - it loses the last two lines. Can't illustrate because the swipe gesture to take a screenshot dismisses the 'About' display :-(
But it's the same df0239e6f0 build.

**Comment by AenBleidd** [comment]
@RichardHaselgrove, should be fixed via #4225 (always wanted to fix that behavior)

**Comment by AenBleidd** [comment]
This will be fixed in scope with #4217 as it's an issue with localization only
