### ISSUE TITLE
[Android] Remote monitoring: User should be able to edit gui_rpc_auth.cfg file

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4232]
Part of #1699.

- [x] Add GUI element in Advanced settings to display current content of gui_rpc_auth.cfg file
- [x] If gui_rpc_auth.cfg file doesn't exist or empty - generate new password (32 characters long)
- [x] By default, this password should be hidden (with dots like password)
- [x] When user clicks on this element, dialog box should be displayed with current password unhidden
- [x] In this dialog user should be able to set new password, this password should be written to gui_rpc_auth.cfg file
- [x] Empty password is not allowed, user should be notified about this
- [x] Add description line to inform user: 'BOINC client will be relaunched after password change"

**Comment by talregev** [comment]
> Part of #1699.
> 
> * [x]  Add GUI element in Advanced settings to display current content of gui_rpc_auth.cfg file
> * [ ]  If gui_rpc_auth.cfg file doesn't exist or empty - generate new password (32 characters long)
> * [ ]  By default, this password should be hidden (with dots like password)
> * [ ]  On the right side f the element should be a button 'Show\Hide' password
> * [ ]  If user clicks to show password, it should be unhide
> * [ ]  If user clicks to hide password, it should be hide again
> * [ ]  On the left of 'Show\Hide' password button should be 'Edit' password button
> * [ ]  If user clicks 'Edit' password button, it should be able to set new password, and this password should be written to gui_rpc_auth.cfg file
> * [ ]  If user sets new password while client is already running with remote monitoring on, user should be informed that after new password set, client will be restarted and all running tasks will be interrupted
> * [ ]  If user confirms change password when remote monitoring is on, restart client
> * [ ]  NICE TO HAVE: Add protection to both buttons ('Show' password and 'Edit' password) to confirm act with default device protection mechanism: password or Fingerprint/FaceID if available).

1/11

**Comment by AenBleidd** [comment]
@talregev, You can check point right in the header

**Comment by talregev** [comment]
I don't have write access to this issue

**Comment by AenBleidd** [comment]
Ok, then I'll check them for you ;)

**Comment by talregev** [comment]
I want to update my progress, so I will do it from the comment. not big deal
