### ISSUE TITLE
Android BOINC 7.16.16 will crash each time it resumes from suspend

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4240]
I've been tracking this bug for a while now. Have [multiple screenshots](https://photos.app.goo.gl/RYZwrm7ESkqip6gJ7) of the event log showing that each time that BOINC suspends, upon resuming the client crashes and restarts. It won't show in the GUI, you can be in the Tasks tab and just see the tasks go from Ready state into Running state, but when you then look in Event Log, it'll show that the client restarted. 

Which wouldn't be a problem, but for that some tasks have long in between checkpoints, so they'll restart at a way lower percentage - sometimes even from start. Others don't like this and when they reach 100%, they'll just restart from 0% for another round (Universe) for 27 hours. 

Then there's the bigger problem and that's that BOINC is running but suspended. I attach the charger, see BOINC resume. Then the client crashes, and doesn't restart, the BOINC icon disappears. When I see it I'll manually restart the client, but it's happened plenty of times that I put my phone on charger throughout the night and find in the morning that BOINC auto-suspended on itself or something else, resumed, crashed and didn't restart. 

I first thought the problem with the resume/crash/restart was due to a combination of different tasks, but it's even doing it now I am running the cache empty, and it's down to two Rosetta's. Yes, I'm well aware this may even be just my phone being the problem. 

Personally I feel this one shouldn't have progressed to recommended immediately without going through a beta stage, but alas, if the BOINC community feels this is the state in which we can release mature BOINC releases, then so be it. I'm done testing, I've reported what I wanted, I see no movement on fixes. Therefore I am running my cache empty and will uninstall this BOINC from my phone when done. So I can finally do something on my phone without the constant notifications that it's suspended, resumed, or that I need to plug in a charger when one is plugged in.

**Comment by AenBleidd** [comment]
@Ageless93, thank you very much for such great testing.
There are a lot of different issues, and I'm working on fixing them.
Meanwhile, I can say from ny observations, you need to remove BOINC from battery optimization and run it every time you want to let it work and keep on foreground. Then it will work with no issues.
When I'll have exact instructions, I'll update them.

**Comment by AenBleidd** [comment]
Should be fixed by #4248

**Comment by AenBleidd** [comment]
Should be fixed in the new release. Please reopen this ticket if this issue will be still there after testing a new release.
