### ISSUE TITLE
New code to look for GUI password file doesn't allow any flexibility, so doesn't work.

### ISSUE THREAD

**Issue by original-birdman** [BOINC/boinc#4249]
In `lib/gui_rpc_client.cpp` `read_gui_rpc_password()` states:
```
// Linux: look in:
//  - current dir
//  - a directory specified in /etc/boinc-client/config.properties
//  - /var/lib/boinc-client
```
However, this is **not** a useful set of locations.
This is an _application_, so using _system_ locations isn't going to work for people building this as a stand-alone application.
The code always used to look for this in the BOINCs `wlib` directory, and this is the obvious place to look - but it no longer does. Why not?

The current dir is a variable location, and hence and hence a bad place to look for ANY password.
`/etc/` on my Asus routers is in a read-only ROM, so I can't create a `boinc-client` subdir there (and I also can't do so on a system where I do not have root access).
`/var/lib/boinc-client` has the same issues. `lib/common_defs.h` says that this can be defined in `configure`, but it can't. There is no option to do so.

So the search for this file needs to be improved. In particular, BOINC's `wlib` directory needs to be re-enabled.

**Comment by AenBleidd** [comment]
BOINC client is not a regular application but a service aka daemon. And this kind of applications should have only one instance running at the same time. That means that the configuration should be in a system location.
There is currently nothing that should be changed on the client side.

**Comment by original-birdman** [comment]
> BOINC client is not a regular application but a service aka daemon. And this kind of applications should have only one instance running at the same time. That means that the configuration should be in a system location. There is currently nothing that should be changed on the client side.

Hence completely ignoring the fact that:

- the client is not s service daemon
- the current directory is not a constant., whereas the BOINC `wlib` directoiry is constant.

**Comment by RichardHaselgrove** [comment]
Both the Windows and Linux applications are bi-modal: they can be installed under service control, or they can be installed as user applications.

For Windows, the choice is made at installation time by whoever's in charge of the machine at that time.

For Linux, installation was delegated to distro repo maintainers. They tend to be 'corporate facing', and chose to make service mode the default.

The new BOINC in-house scripts have chosen to follow the corporate/repo inheritance. It would be nice to have a user-mode option as well.

**Comment by AenBleidd** [comment]
For user mode option there is a Flatpak installation available: https://flathub.org/apps/edu.berkeley.BOINC
Soon there will be also a snap package as well.

Also, you still can run BOINC client from the directory its located, and al the data will be saved there.
Fore everything else there is a config file.

**Comment by original-birdman** [comment]
This issue is about where the password is stored, and **that** is used by the client code (as well as by the daemon).
There is no option to let the client (_i.e._ the user running it) to use a location which they own.
Consequently, to use a password you have to use a system location _and_ make it **world-readable**, which rather destroys any security from having a password.

**Comment by AenBleidd** [comment]
you don't need to make it world-readable.
you just need to add your user to the 'boinc' group:
```
sudo usermod -a -G boinc $USER
```
Ref: https://boinc.berkeley.edu/gui_rpc.php

**Comment by AenBleidd** [comment]
and yes, you can always pass the password manually to the `boinccmd`: https://github.com/BOINC/boinc/wiki/Boinccmd-tool

**Comment by Vulpine05** [comment]
> For user mode option there is a Flatpak installation available:

I knew of the Flatpak installer, but I was not aware of the user option for it.  I think it would be great to update the installation instructions for Linux to note the difference between the system and user installations, as well as providing a Flatpak link.

**Comment by RichardHaselgrove** [comment]
> The new BOINC in-house scripts have chosen to follow the corporate/repo inheritance. It would be nice to have a user-mode option as well.

I've now had some time to experiment with the BOINC in-house script (specifically, the version for Ubuntu 24.04) and it appears to operate in both modes - though this isn't mentioned anywhere in the documentation. If interested parties would like to investigate further, my experiences are described in #5787.
