### ISSUE TITLE
BOINC-Client doesn't exist in the official Manjaro repositories

### ISSUE THREAD

**Issue by PhotoLinux** [BOINC/boinc#4264]
I wanted to install BOINC on my Manjaro laptop, but I could only find the boinc-manager in the official Manjaro repositories.
It would be nice, if you could add boinc-client to the Manjaro repositories.

**Comment by AenBleidd** [comment]
Looks like this distro is based on Archlinux, try to use this article to install and run BOINC: https://wiki.archlinux.org/index.php/BOINC

**Comment by AenBleidd** [comment]
According to this: https://manjaro.lucassymons.net/stable/community/x86_64/
boinc client is present in the packae
