### ISSUE TITLE
BOINC manager freezes when I enter email

### ISSUE THREAD

**Issue by SpaceNerden** [BOINC/boinc#4292]
**Describe the bug**
New install with VB. I run, get the add project menu. I choose Einstein@home, Click on `Email Address`, No letters, cursor locked in the text cursor (the skinny thing you see when hovering over a text box) I can't click out, or type, or even paste text in. Not even close the window. I had to close it with Task manager. 

**Steps To Reproduce**
1. [Download](https://boinc.berkeley.edu/download.php)
2. Install
3. Run
4. Get "New Project" window
5. Choose `Collatz Conjecture` or `Einstein@Home`
6. Attempt to enter email for New account (old account also has same problem)

**Expected behavior**
1. [Download](https://boinc.berkeley.edu/download.php)
2. Install
3. Run
4. Get "New Project" window
5. Choose `Collatz Conjecture` or `Einstein@Home`
6. Attempt to enter email for New account (or old)
7. Enter password
8. Finish adding project

**System Information**
 - OS: WINDOWS 10
 - BOINC Version: 7.16.11 x64

**Comment by RichardHaselgrove** [comment]
What input language are you trying to use? It has been reported that the input boxes can't handle Microsoft Pinyin, but work when switched to English (US) or other languages.

**Comment by SpaceNerden** [comment]
> What input language are you trying to use? It has been reported that the input boxes can't handle Microsoft Pinyin, but work when switched to English (US) or other languages.

I'm using Japanese, I'll see if switching to US works.

**Comment by SpaceNerden** [comment]
Yup, just use US/UK and it works.

**Comment by RichardHaselgrove** [comment]
Since we have a considerable amount of interest from Chinese and other Asian language users at the moment, perhaps this should be looked into at source.

Or maybe it's a topic for next month's virtual workshop?

**Comment by SpaceNerden** [comment]
I saw that a similar issue got marked as a major issue (Sept 2020), Maybe next update?

**Comment by AenBleidd** [comment]
It should be investigated first, it could be an issue in wxWidgets
