### ISSUE TITLE
[Server] one_result_per_user_per_wu potentially broken

### ISSUE THREAD

**Issue by polymetric** [BOINC/boinc#4303]
**Describe the bug**
The server configuration option `one_result_per_user_per_wu` seems to not function as expected. I've seen 3 separate BOINC servers that have this option enabled and some users get two tasks from the same workunit. If the `one_result_per_host_per_wu` option is not enabled, a single host can get both tasks from a workunit:
![Screenshot_from_2021-03-29_15-13-09](https://user-images.githubusercontent.com/13613437/113120235-5ed9d200-91df-11eb-91d1-db3f3bc258cf.png)
I spoke with the SiDock@home admin and, at the time of that log entry, `one_result_per_user_per_wu` was enabled but `one_result_per_host_per_wu` was not.

**Affected Projects**
- Minecraft@Home
- SiDock@home
- my own private BOINC instance

**Steps To Reproduce**
1. Enable the rule `one_result_per_user_per_wu` in config.xml.
2. Wait for some new tasks to be distributed.
3. Go to the ops panel, click 'Workunits' under 'Browse database', then paste this into the 'additional clauses' box: `id in (select r.workunitid from result r join result r2 on r.workunitid = r2.workunitid and r.hostid <> r2.hostid and r.userid = r2.userid)`
4. Alternatively, in a clean BOINC server test environment, simply attach one host and watch as it gets both replications.

**Expected behavior**
The query should return no results - hosts should not get two results from the same workunit.

**Screenshots**
my BOINC instance:
![firefox_2021-03-31_05-17-05_7547](https://user-images.githubusercontent.com/13613437/113121158-59c95280-91e0-11eb-819b-80596f1a4548.png)
Minecraft@Home:
![1guy2results](https://user-images.githubusercontent.com/13613437/113121369-95641c80-91e0-11eb-9447-d51f267cfbb3.png)
SiDock@home:
![Screenshot_from_2021-03-29_15-13-09](https://user-images.githubusercontent.com/13613437/113120235-5ed9d200-91df-11eb-91d1-db3f3bc258cf.png)

**System Information**
 - OS: Debian 10 Buster (used by my private BOINC server)
 - BOINC Version: 1.2.0 (https://github.com/BOINC/boinc/tree/server_release/1/1.2) (version used by both my server and Minecraft@Home)
 - BOINC Version: 1.1.0 (version used by SiDock@home)

**Additional Context**
Minecraft@Home config.xml: https://github.com/minecrafthome/minecrafthome/blob/master/images/makeproject/project/config.xml#L35

Feel free to ask for additional clarification if I missed anything!

**Comment by davidpanderson** [comment]
Do you happen to know if both results were returned in a single scheduler request?

**Comment by polymetric** [comment]
That I don't know, sorry.

**Comment by AenBleidd** [comment]
@lfield, is there any chance you could try to take a look at this issue?

**Comment by lfield** [comment]
I can not reproduce this issue on LHC@home dev. I notice that those two project are not running the latest code.
