### ISSUE TITLE
reusing already processed output

### ISSUE THREAD

**Issue by HxpGames** [BOINC/boinc#4326]
.

**Comment by AenBleidd** [comment]
BOINC operates in a little bit different way: user receives a small chunk of data that should be calculated. And usually this piece of data is unique so the result is never known. 
Also, sometimes calculate the same data is faster than download a huge database and search in it (e.g. calculate small prime numbers).

**Comment by HxpGames** [comment]
> 
> 
> BOINC operates in a little bit different way: user receives a small chunk of data that should be calculated. And usually this piece of data is unique so the result is never known.
> Also, sometimes calculate the same data is faster than download a huge database and search in it (e.g. calculate small prime numbers).

make it self known
