### ISSUE TITLE
Too many points have been scored.

### ISSUE THREAD

**Issue by EugeneMikhalov** [BOINC/boinc#4329]
Hello! I have got too many points. Now, a total amount of points is smaller than average one:) An evident error.
 [Screenshot](https://drive.google.com/file/d/1B1Vfmp_DRaNLZnEgvpYy6zgr8zAcBeth/view?usp=sharing)

**System Information**
 - OS: W10 Home
 - BOINC Version: 7.16.11 x64

**Comment by AenBleidd** [comment]
@EugeneMikhalov, what numbers do you see on your profile page on every project with incorrect numbers?
Are these numbers the same as in the Manager window?

**Comment by RichardHaselgrove** [comment]
What exactly is the problem? Note that in your screenshot, the 'average' shows two decimal places, using the USA/UK convention of a period to separate units from fractions. Despite the extra digits, in all cases the value in the 'total' column is greater than the value in the 'average' column.

**Comment by AenBleidd** [comment]
@EugeneMikhalov,
Einstein@home:
Total: 6 810 746 887 (~6 billion)
Average: 15 882 412.26 (~15 million)
Looks fine to me.

**Comment by HxpGames** [comment]
why dont you fix the errors , do you need mental help

**Comment by AenBleidd** [comment]
@HxpGames, there is no issue here, just misunderstanding. Do you have smth to add?
