### ISSUE TITLE
BOINC-wide teams has several bugs

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#434]
**Reported by Saenger on 4 Apr 37833731 04:26 UTC**
1.: No multi-founder options:
We (SETI.Germany, not one of the smallest teams) have 28 founders. We like it this way. But our team was automatically founded on the team list in Berkeley, so, afaik, we will be affected by this. Since most projects have not implemented this "feature" I can't yet say how.

2.: No project specific team description possible:
We have in our team descriptions a (bigger) common part for all projects, and some special part for just this project where it's good for. This has to be possible in the future, so an opt-out of the description update is necessary.

3.: Teams were created with copy'n'paste from Seti with unwanted consequences:
Our founder probably never was asked about this "feature", he was not seen on our boards for quite a while, and he is since even longer not any more our team page admin. That job has changed twice since he founded S.G @Classic. So we don't have access to this team account. The actual team leaders need to be contacted by those who set up this accounts.

4.: Team leaders have to be notified about new founded teams by mail from new projects
I've had another ticket about this issue with the mail addresses, but have to concede that you generally don't hold security and spam protection that high as I do. So if the mail is imported by some new project, the founder hast to be made aware of this asap, otherwise someone can probably hijack the team by "initiate transfer".

Discussion of this in the Forum: http://boinc.berkeley.edu/dev/forum_thread.php?id=2234

Migrated-From: http://boinc.berkeley.edu/trac/ticket/455

**Comment by romw** [comment]
**Commented by davea on 20 Aug 37833855 10:13 UTC**
Please use the Google boinc-team-founders list:
http://groups.google.com/group/boinc-team-founders
rather than this bug-tracking system
to discuss issues related to BOINC-wide teams.

**Comment by romw** [comment]
**Commented by Saenger on 26 Jun 37833876 04:00 UTC**
I won't use google, that' not an option. They are no serious provider.
Where else is the appropriate place on the proper Berkeley pages to put this bugs if not here?

**Comment by romw** [comment]
**Commented by Didactylos on 19 May 37834031 05:46 UTC**
Where was the BOINC Team feature discussed before implementation?

Where is it documented?

I feel it is just one in a line of features that were sprung on the BOINC community without being fully worked out first. Now we're dealing with the fallout, and I'm still not clear on the point of this feature or how it works. I went ahead and tried it for my team, and it hasn't brought any advantage that I can see.

And since when did BOINC use Google Groups for discussion?

If this is a BOINC feature, then '''here''' is precisely the correct forum for this discussion. If it isn't, then.... *wibble*

Forgive my bluntness, but I want some clarity on this.

**Comment by romw** [comment]
**Commented by Nicolas on 1 Feb 37834157 14:13 UTC**
Why not another mailing list, why ''outsource'' into Google Groups? And I see no reason to disallow anonymous read access on the group. You can't even join without admin approval! What's so secret going on in there?

**Comment by romw** [comment]
**Commented by Saenger on 31 Oct 37841128 21:46 UTC**
There was another post by David Anderson in this dubious Google group. Why don't you discuss this in an official place, where all can join?

Google has no sense of privacy, it's bad enough to use it as a search tool, but they will never get an account by me, they are not serious. There are plenty prober places to discuss this in the open here on the official servers in Berkeley, not this shady back room.

If you further use this non-forum I have to deduct that you don't want it discussed in the open.

**Comment by romw** [comment]
**Commented by Didactylos on 10 Jul 37879894 05:20 UTC**
Combining #409 with this ticket. Refer to #409 for additional discussion.

**Comment by ChristianBeer** [comment]
This handles problems during "birth" of this feature.
