### ISSUE TITLE
Missing GPUs in the "Top GPU Models" page, possibly due to low GPU count?

### ISSUE THREAD

**Issue by TunaErtemalp** [BOINC/boinc#4357]
**Describe the problem**
This is from my post [http://www.primegrid.com/forum_thread.php?id=9658&nowrap=true#149970](http://www.primegrid.com/forum_thread.php?id=9658&nowrap=true#149970). The gist of it is that I have one Win10 host with two NVIDIA 3080s that contributed to an application on PrimeGrid, yet even after 500+ successful results, the **Top GPU Models** page for that app ([http://www.primegrid.com/gpu_list.php#WW](http://www.primegrid.com/gpu_list.php#WW)) only lists 3080 for Linux, and not Windows. Here is an edited/updated/trimmed copy/paste of the relevant thread to save you a trip there:

> I have one host with dual 3080s that has generated a bunch of valid WW jobs (500+ as of this writing): http://www.primegrid.com/results.php?hostid=782330&offset=0&show_names=0&state=4&appid=33
> 
> But http://www.primegrid.com/gpu_list.php#WW shows nothing for 3080 under Windows right now (there is only the Linux entry).
> 

One response was: 

> I believe there need to be some minimum number of cards of a type before the type shows up.

(**PS:** In the meantime, I switched my host to run another application on PrimeGrid, [http://www.primegrid.com/results.php?hostid=782330&offset=0&show_names=0&state=4&appid=11](http://www.primegrid.com/results.php?hostid=782330&offset=0&show_names=0&state=4&appid=11), it already finished 1000+ good WUs, yet [http://www.primegrid.com/gpu_list.php#AP27](http://www.primegrid.com/gpu_list.php#AP27) doesn't show any 3080 stats for Windows.)

**Describe the solution you'd like**
To which, my reply was:

> Hmmm.... Assuming that's the case, methinks including the number of cards in the PG system next to each listing in parentheses would be nice. That would also make it possible to show the cards with low counts, but maybe with an (*) to indicate visually that the perf value is statistically not yet mature, while still giving the audience an idea.
> 
> Just a thought...
> 

**Additional context**
No further context. I am assuming this is common BOINC code as opposed to PrimeGrid-specific. It is just a suggestion to make things make a bit more sense, therefore entered as a Feature Request. However, if the premise of "minimum number of cards to show up in the list" is a bad assumption, then the current behavior of missing 3080s under Windows would be a bug, and fix plus my suggestion would be a fix+feature.

**Comment by AenBleidd** [comment]
Looks like this statistics is build on last 2k results.
@TunaErtemalp, is it possible that results from 3080 are not in the last 2k batch on results of this particular app for Windows platform?

**Comment by TunaErtemalp** [comment]
I'll ask on PrimeGrid.

**Comment by TunaErtemalp** [comment]
Please see [http://www.primegrid.com/forum_thread.php?id=9658&nowrap=true#150296](http://www.primegrid.com/forum_thread.php?id=9658&nowrap=true#150296) for details. This turns out to be a PrimeGrid issue. It is using a **LIMIT 3000** on the SQL query to avoid getting 10s or 100s of thousands of results to sort through, which would have brought the database performance down for more important things. That **LIMIT** is resulting in an _arbitrary_ list being returned that gets processed to create the statistics page, and that arbitrary list is probably more of a stable selection of the results than a _random_ selection of them for every query.
