### ISSUE TITLE
Sever status page TR's colors migrate to CSS file and some minor improvements in "white.css" file.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#436]
**Reported by Simek on 14 Dec 37836864 08:53 UTC**
Sever status page TR's colors migrate to CSS file and some minor improvements in "white.css" file.
(It sometimes causes a problem when somebody edit CSS file - colors disappear form server status file. This patch eliminate this bug.)

All changes are included in attached patch files.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/457

**Comment by romw** [comment]
**Commented by Simek on 23 Jul 37836872 03:33 UTC**
sorry for upload white.css file twice...

**Comment by romw** [comment]
**Commented by Rytis on 19 Jan 37841745 08:26 UTC**
(In [14078]) - user web: style server status page with CSS, some cleanup of the stylesheet (fix #457).

**Comment by romw** [comment]
**Commented by Simek on 30 Dec 37841783 21:20 UTC**
I create patch for "white.css" in OPS directory. This file need update too.

**Comment by ChristianBeer** [comment]
This is fixed in current servercode.
