### ISSUE TITLE
Boinc builds on Raspberry Pi 400 and Ubuntu Mate 64

### ISSUE THREAD

**Issue by w4jkl** [BOINC/boinc#4387]
I've successfully built yesterday's git clone main Boinc on a Raspberry Pi 400 running Ubuntu Mate for Pi 4B on the following configuration:
Ubuntu 20.10 64 bit
Kernel Linux 5.8.0-1024-raspi aarch64
Mate 1.24.1
Hardware shows
Memory: 3.7GiB
Graphics: V3D 4.2
Boinc installed at /usr/local/bin/ and usr/local/lib
and I was even able to get boincscr to build but I haven't got the screensaver to work yet. It probably doesn't matter since the Pi400 is no speed demon, but I thought I would try.
Until the Raspberry Pi Org. has their own 64 bit OS running, this is one of the more common Pi4B 64 bit systems that actually work for people like me, who just gotta have 64 bits.
Everything essential Boinc works in my testing thus far.
Thought you might be interested.
Regards,
John

**Comment by AenBleidd** [comment]
Hello @w4jkl,

Thanks for letting us know!
