### ISSUE TITLE
Right clicking the BOINC Manager logo on the titlebar on Windows causes it to instantly crash

### ISSUE THREAD

**Issue by 2tbc1887** [BOINC/boinc#4407]
**Describe the bug**
The BOINC Manager will instantly crash if the titlebar logo is right clicked.
**Steps To Reproduce**
1. Open the BOINC Manager
2. Right click the BOINC Manager logo in the titlebar

**Expected behavior**
Standard titlebar context menu items
**Screenshots**

**System Information**
 - OS: Windows 10
 - BOINC Version: 7.16.11

**Additional context**

**Comment by AenBleidd** [comment]
Duplicate of #4312

**Comment by RichardHaselgrove** [comment]
And already fixed in #4198. We're just waiting for the release.
