### ISSUE TITLE
[Android] Add determiners in some sentences

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4431]
At this moment, according to Transifex, some of the strings to be translated miss out on determiners before words as client and account manager. I see sentences such as "When changed, BOINC client will be relaunched." which sound better as "When changed, the BOINC client will be relaunched.", or "Use account manager to control this device" versus "Use an account manager to control this device". We should probably walk by all sentences to check for missing determiners.

**Comment by AenBleidd** [comment]
Should be already fixed in #4447
