### ISSUE TITLE
[Android] Work units, tasks or something else?

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4432]
At present the "Other" chapter in the Android BOINC advanced preferences states:
"Work unit buffer (days)"  
"Additional work unit buffer (days)"

On the desktop we talk about "tasks", not "work units". I think we should keep one unit all over the place, not use different names in different places.

**Comment by AenBleidd** [comment]
@Ageless93, the funny fact: this was here for years but mentioned only now ;)

**Comment by Ageless93** [comment]
On the course I follow I just pointed out that one of the pictures we need
to add to the web page we make shows a bumble bee, while the page we need
to make is about saving honey bees and their honey. Bumble bees do make
honey but only for themselves... So there too I pointed that out and got as
answer that I was the first to ever see that and report it. So it's just my
week. ;-)

-- Jord

**Comment by Ageless93** [comment]
I even see that now in Transifex:
Line 127: Limits the amount of RAM **tasks** are allowed to occupy.
Line 128: Work unit buffer (days)
Line 129: Additional work unit buffer (days)

Weird.

**Comment by AenBleidd** [comment]
As I said, this was hear for year, just nobody took an attention to it.
Thanks for catching this, @Ageless93

**Comment by davidpanderson** [comment]
The wording on the web prefs is:
Store at least	0.1 days of work
Store up to an additional	0.5 days of work
