### ISSUE TITLE
--remote_file parameter in create_work does not seem to work as advertised in documentation

### ISSUE THREAD

**Issue by BoySanic** [BOINC/boinc#4440]
According to [JobSubmission](https://boinc.berkeley.edu/trac/wiki/JobSubmission), we can use the --remote_file parameter to specify a URL, size of the file in bytes, and MD5sum for files served by a separate web server.

Additionally, [JobTemplates](https://boinc.berkeley.edu/trac/wiki/JobTemplates) suggests that there are two ways that we can provide remote file information. Either via parameters in create_work or with input templates. 

The documentation seems to suggest that this is an OR situation, not that we need both. 

Unfortunately, my findings have been that the code path is guaranteed to launch process_input_template, and it will throw an ERR_XML_PARSE if the number of files passed into create_work doesn't equal the number of files given in the wu template.

Ideally we'd like to give create_work the remote_file URL without needing to create an input template for every job, as we have about 1.3 million jobs to create and it seems needlessly messy to create/generate such a large number of templates.

I'm hoping to get some clarification on what the functionality should be., or what I might be doing wrong.

Below is the method by which I'm calling create_work:

```
counter = 0
 while read line; do
  wu_name="appname_$((counter))_$((counter+1))')"
  echo "create_work: ${wu_name}"
  bin/create_work --appname appname \
    --result_template templates/appname_out \
    --remote_file "<URL> 2400 $(echo $line)"\
    --priority 12000 \
    --min_quorum 2 \
    --wu_name "${wu_name}" \
    --rsc_fpops_est 3e13 \
    --rsc_fpops_bound 3e20 \
    --delay_bound 604800
  counter+=1
 done <<< "$(cat ./appname_taskinfo.txt)";
```

Thanks in advance!

**Comment by davidpanderson** [comment]
What does the WU template contain?

**Comment by BoySanic** [comment]
This is the WU template (when I do pass it into create_work):

```
<input_template>
    <file_info>
        <nbytes>2400</nbytes>
    </file_info>
    <file_ref>
        <open_name>ocinput</open_name>
        </copy_file>
    </file_ref>
    <workunit>
        <rsc_fpops_est>3e16</rsc_fpops_est>
        <rsc_fpops_bound>6e20</rsc_fpops_bound>
        <delay_bound>604800</delay_bound>
    </workunit>
</input_template>
```

**Comment by davidpanderson** [comment]
You're getting the error
"All file properties must be defined if at least one is defined (url, md5_cksum, nbytes)",
right?
Omit the
<nbytes>2400</nbytes>
in the WU template.

**Comment by BoySanic** [comment]
Dave,

I tried a few different variants of that file. Please see below:

`<input_template>
    <file_info>
    </file_info>
    <file_ref>
        <open_name>ocinput</open_name>
        </copy_file>
    </file_ref>
    <workunit>
        <rsc_fpops_est>3e16</rsc_fpops_est>
        <rsc_fpops_bound>6e20</rsc_fpops_bound>
        <delay_bound>604800</delay_bound>
    </workunit>
</input_template>`

Receives error: #file refs != #file infos

`<input_template>
    <file_ref>
        <open_name>ocinput</open_name>
        </copy_file>
    </file_ref>
    <workunit>
        <rsc_fpops_est>3e16</rsc_fpops_est>
        <rsc_fpops_bound>6e20</rsc_fpops_bound>
        <delay_bound>604800</delay_bound>
    </workunit>
</input_template>`

Receives error: 
process_input_template: 1 input files given, but template has 0
process_input_template(): unexpected XML tag or syntax

`<input_template>
    <workunit>
        <rsc_fpops_est>3e16</rsc_fpops_est>
        <rsc_fpops_bound>6e20</rsc_fpops_bound>
        <delay_bound>604800</delay_bound>
    </workunit>
</input_template>`

Receives error:

process_input_template: 1 input files given, but template has 0
process_input_template(): unexpected XML tag or syntax

**Comment by davidpanderson** [comment]
The <file_ref> elements go inside the <workunit> element.
See https://boinc.berkeley.edu/trac/wiki/JobTemplates#Inputtemplates

**Comment by BoySanic** [comment]
That worked!

Thank you so much. Sorry it ended up being something simple I missed in documentation.
