### ISSUE TITLE
Support nativ SailfishOs client

### ISSUE THREAD

**Issue by dennisroczek** [BOINC/boinc#4488]
I have a Volla Phone with SailfishOS using the community edition, so without aliendavek / android integration thus not being able to run BOINC. Would be nice to have BOINC as a native client there.

**Comment by AenBleidd** [comment]
Even if this looks like a good idea, unfortunately the market share of Sailfish OS is too low. Also that  fact that there is a possibility (yes, I understand that some vendors might not include it) to run Android applications natively on it, makes no real reason to make another native solution.
Another argument to not do this is the requirement to use Qt (or Python) for the native Sailfish OS applications.
BOINC Manager is currently written on wxWidgets (for the desktop OSs) and on Java/Kotlin for Android, and supporting one more GUI framework is not reasonable.
That is why I'm closing this feature request without any further actions.
