### ISSUE TITLE
[Android]Latest release v7.18.1 is on libcurl 7.74 from 12/2020

### ISSUE THREAD

**Issue by user8446** [BOINC/boinc#4500]
Hello,

Just pointing out that libcurl used is v 7.74 from 12/2020 but the latest release is 7.78. Currently, there are 9 vulnerabilities in 7.74: https://curl.se/docs/releases.html

**Comment by AenBleidd** [comment]
@user8446,

Thank you for your report.

We're using vcpkg as our dependencies manager. Currently the latest version of libcurl on vcpkg is 7.74.0: https://github.com/microsoft/vcpkg/blob/master/ports/curl/vcpkg.json
Once it will be updated there - next release of Android BOINC will contain updated version too.

You can help us (and other users of vcpkg) if you provide and update to vcpkg to build latest version of libcurl.

Thanks in advance.

**Comment by talregev** [comment]
Waiting for this PR on vcpkg
https://github.com/BOINC/boinc/issues/4500
