### ISSUE TITLE
GPU no longer is found

### ISSUE THREAD

**Issue by iiyt** [BOINC/boinc#4525]
BOINC Manager no longer sees my GPU.  It has been running for years, and reported an error that the GPU was missing DURING A RUN.  Around that same time, BOINC crashed every few minutes.  After a reboot, and reinstall of the very latest 64-bit windows rev, the GPU no longer appears at all.

My GPU is fully functional, as per the windows device manager, and standard utility (driving my displays, showing the NVIDIA control panel, etc).  No errors anywhere else.  And nothing on my system hardware has changed in years.

**Steps To Reproduce**
1. Start BOINC 

**Expected behavior**
Under the Activity menu, I expect to see a section on GPU (use always, based on prefs, suspend).  That menu group is no longer present. 

**Screenshots**
Log file:
9/16/2021 12:27:43 PM |  | Starting BOINC client version 7.16.11 for windows_x86_64
9/16/2021 12:27:43 PM |  | log flags: file_xfer, sched_ops, task
9/16/2021 12:27:43 PM |  | Libraries: libcurl/7.47.1 OpenSSL/1.0.2s zlib/1.2.8
9/16/2021 12:27:43 PM |  | Running as a daemon (GPU computing disabled)
9/16/2021 12:27:43 PM |  | Data directory: F:\BOINC
9/16/2021 12:27:43 PM |  | Running under account boinc_master
9/16/2021 12:27:43 PM |  | No usable GPUs found
9/16/2021 12:27:43 PM |  | app version refers to missing GPU type NVIDIA
9/16/2021 12:27:43 PM | PrimeGrid | Application uses missing NVIDIA GPU
9/16/2021 12:27:43 PM |  | app version refers to missing GPU type NVIDIA
9/16/2021 12:27:43 PM | PrimeGrid | Application uses missing NVIDIA GPU

If the GPU is systemically disabled somehow, I don't know how that would have happened, or how to fix it.  

**System Information**
 - OS: Windows 10 Pro 10.0.19042
 - BOINC Version: 7.16.11 x64 (wxWidgets 3.0.1)

**Comment by AenBleidd** [comment]
As you can see from the log, your BOINC is running as a daemon (service):
`9/16/2021 12:27:43 PM | | Running as a daemon (GPU computing disabled)`
Deinstall BOINC, and then durin installation uncheck 'Service install'
![image](https://user-images.githubusercontent.com/3234209/133675539-269b378f-ee0e-4775-be02-bd55ffd8bd44.png)
