### ISSUE TITLE
Remove dead projects?

### ISSUE THREAD

**Issue by BryanQuigley** [BOINC/boinc#4528]
**Describe the bug**
Many of the projects on the project list are dead?

https://csgrid.org/csg/ project says No Longer active.  

Doesn't load:
https://www.cpdn.org
https://asteroidsathome.net/boinc/
https://boinc.ibercivis.es/ibercivis/ 
https://mindmodeling.org/
https://rake.boincfast.ru/

**Expected behavior**
No one wastes time with dead links when searching for projects.

**Additional context**
Happy to setup something automated to make sure projects still exist.

**Comment by BryanQuigley** [comment]
It's very possible some of these are just down right now.. but it's still quite a number.

**Comment by davidpanderson** [comment]
Thanks!
- I removed Ibercivis, MindModeling, and Rake, which indeed seem to be dead.
- "www.cpdn.org" was the wrong URL for Climateprediction.net; I fixed this.
- Asteroids@home was sending jobs a few days ago; they may be temporarily down.

**Comment by BryanQuigley** [comment]
@davidpanderson 
Thanks! just an fyi - Asteroids@home is still down.
