### ISSUE TITLE
No tray icon on 7.16.16

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#4536]
**Describe the bug**

**Steps To Reproduce**
1. 
2. 

**Expected behavior**

**Screenshots**

**System Information**
 - OS: Microsoft Windows [Version 10.0.19043.1237]
 - BOINC Version: 7.16.16

**Additional context**
Downloaded from here
https://boinc.berkeley.edu/dl/boinc_7.16.16_windows_x86_64.exe

**Comment by AenBleidd** [comment]
7.16.16 is not a valid Windows release. There is not such issue on master. Closing as invalid

**Comment by kotenok2000** [comment]
Then why there is a installer with this version?

**Comment by AenBleidd** [comment]
You can find recommended version here: https://boinc.berkeley.edu/download_all.php

**Comment by AenBleidd** [comment]
> Then why there is an installer with this version?

This was a test build. Since it's not neither `Recommended` nor `Development` version on the page mentioned above - it's not suppose to be installed and used

**Comment by RichardHaselgrove** [comment]
Then remove it from public view. There **was** an issue - this issue - when it first appeared. You fixed that, and I tested the CI artifact. I'm still running the fixed version, in fact.
