### ISSUE TITLE
Bootable ISO Image was last available in aug 2019.

### ISSUE THREAD

**Issue by BryanQuigley** [BOINC/boinc#4537]
**Describe the bug**
Download page offers a bootable ISO image, but link is dead and was last available in 2019.

**Steps To Reproduce**
1. Go to https://boinc.berkeley.edu/download_all.php and click "install BOINC using a package manager, run it using Docker, or use a bootable ISO image"
2.  Which leads you to https://boinc.berkeley.edu/wiki/Installing_BOINC#Using_a_bootable_image
3.  Clicking on PADOLF@home brings you to a dead link.

Investigating further I don't think it's been up since Aug 2019. https://web.archive.org/web/*/http://plfcomputing.com/padolfathome.html

**Expected behavior**
No dead links.

**Additional context**
If there is demand for this, I'd be interested in trying to make it happen again.

**Comment by davidpanderson** [comment]
Thanks.  I removed that link.

**Comment by cwallbaum** [comment]
With regard to [https://boinc.berkeley.edu/forum_thread.php?id=12387#85652](https://boinc.berkeley.edu/forum_thread.php?id=12387#85652), this should finally be removed.

You might want to take a look at [https://delta1512.github.io/BOINCOS/](https://delta1512.github.io/BOINCOS/) instead.

**Comment by davidpanderson** [comment]
I removed that thread, and added a link to BOINCOS

**Comment by BryanQuigley** [comment]
BOINC OS hasn't been updated since 2018.. https://github.com/delta1512/BOINCOS/releases/tag/v2.0.1-Beta

**Comment by davidpanderson** [comment]
Does it still work?

**Comment by davidpanderson** [comment]
Thanks; I added a link to the ARM image
