### ISSUE TITLE
Stop offering really old versions?

### ISSUE THREAD

**Issue by BryanQuigley** [BOINC/boinc#4543]
With #4542 this will mean BOINC depends on the cert store in Windows being up-to-date. I fully support the idea of only supporting currently supported versions of OSes (and the change to use the Windows cert store) - or at least dropping really old versions. 

If this is indented, I propose it's a good time to clean up the download all page:
Windows 64-bit
Vista/7/8/8.1/10 -> just rename -> 8.1/10/11  (8.1 is in extended paid support)

Windows 32-bit 
At least drop 6.6.38 and 5.8.16 (win 95!) - maybe drop entirely?

Apple Mac (Power PC or 32-bit Intel)
MacOS 10.4.0+
Drop

Linux
The recommended version is from 2014. Obviously we recommend use a package manager - but can we stop offering any versions from the download page?  Alternatively, I'm happy to work on making an updated version for Linux (or maybe evaluate the flatpak).

**Comment by AenBleidd** [comment]
@BryanQuigley, flatpak is already here: 
https://flathub.org/apps/details/edu.berkeley.BOINC
Maybe you could add Snap instead https://github.com/BOINC/boinc/issues/2485 ?

**Comment by BryanQuigley** [comment]
Sorry, yes I meant offering the flatpak as the default way to get BOINC.

**Comment by AenBleidd** [comment]
Not sure flatpak is used more than 'sudo apt install' :)

**Comment by CharlieFenton** [comment]
@BryanQuigley The reason we offer versions of BOINC for older operating systems is that it is common for people to repurpose their old obsolete computers to run BOINC when they upgrade. I prefer keeping these available, though I must concede that there is no point keeping ones that use such an old version of OpenSSL that their certificates prevent getting work from project servers.

Another reason for having older versions of BOINC available from https://boinc.berkeley.edu/download_all.php is that, despite our efforts to thoroughly test each release, problems sometimes show up after a version is released and it is important for users to be able to get an earlier build.

> Obviously we recommend use a package manager - but can we stop offering any versions from the download page?

What is wrong with the way the current link https://boinc.berkeley.edu/download.php works from the BOINC home page https://boinc.berkeley.edu for Windows and Apple computers?

**Comment by BryanQuigley** [comment]
>The reason we offer versions of BOINC for older operating systems is that it is common for people to repurpose their old obsolete computers to run BOINC when they upgrade.

Absolutely that makes sense to some extent, but I would be shocked if Windows 95/NT/98/ME or PPC Mac computers are useful for any project today.

> What is wrong with the way the current link https://boinc.berkeley.edu/download.php works from the BOINC home page https://boinc.berkeley.edu for Windows and Apple computers?

Nothing at all - that comment was specific to Linux.

>despite our efforts to thoroughly test each release, problems sometimes show up after a version is released

Absolutely, I'm not suggesting you stop having a recommended and an older version for OSes that have active development (but that's usually like 7.16.7 (old) vs 7.16.11 (Recommended) .

**Comment by AenBleidd** [comment]
Linux case will be fixed when #5151 is done.
There is nothing else that should be done on download page for now.
