### ISSUE TITLE
[CI] Switch to vcpkg manifest mode for all vcpkg builds

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4547]
- [ ] Android
- [ ] Linux
- [ ] Windows

This is important to be able to lock dependencies versions on release branch between minor releases.

Reference: https://vcpkg.readthedocs.io/en/latest/examples/manifest-mode-cmake/

**Comment by talregev** [comment]
Please let me edit this issue.

**Comment by talregev** [comment]
You should add mingw and mac as well. and check android and linux.

**Comment by talregev** [comment]
I will open a new issue. please close this one.

**Comment by AenBleidd** [comment]
Closed in favor of #4707
