### ISSUE TITLE
BOINC check for new versions won't work on arm64 Macs

### ISSUE THREAD

**Issue by CharlieFenton** [BOINC/boinc#4551]
**Describe the bug**
New Mac clients are universal binaries containing both arm64 and x86_64 code. 
  On Intel Macs, the primary platform is x86_64-apple-darwin and no secondary platform
  On arm64 Macs, the primary platform is arm64-apple-darwin and the secondary platform is x86_64-apple-darwin

But https://boinc.berkeley.edu/download.php shows only x86_64-apple-darwin:
```
<version>
    <platform>Apple Mac (64-bit Intel and Apple Silicon)</platform>
    <dbplatform>x86_64-apple-darwin</dbplatform>
    <description>Recommended version (Unix command-line version)</description>
    <date>16 Sep 2021</date>
    <version_num>7.16.19</version_num>
    <url>https://boinc.berkeley.edu/dl/boinc_7.16.19_universal-apple-darwin.dmg</url>
    <filename>boinc_7.16.19_universal-apple-darwin.dmg</filename>
    <size_mb>3.77</size_mb>
    <installer>Command-line client (no GUI)</installer>
</version>

```
universal binaries either need to be in there twice, once for each platform, or there needs to be a provision for multiple primary platforms in both client/current_vrsion.cpp
and https://boinc.berkeley.edu/download.php

**NOTE:** The first solution will work with existing clients, but the second solution will only work with new clients.  
 - OS: MacOS 11
 - BOINC Version: 7.16.19

**Comment by davidpanderson** [comment]
The above comment is relevant to web pages but not the XML used by client; I'll make a change shortly.

**Comment by davidpanderson** [comment]
We now show (in the XML) the universal binaries once for each platform; let me know if that works.

**Comment by CharlieFenton** [comment]
I inspected the _get_current_version-old.xml_ file downloaded from https://boinc.berkeley.edu/download.php?xml=1 and it looks good to me, though I have no way to test it on an M1 Mac. @bema-aei or @AustinConlon the easiest way to test this on an M1 Mac might be to install an older arm64 Mac client and select "Check for new version" from the BOINC Manager's Help menu.

**Comment by CharlieFenton** [comment]
@davidpanderson: When I select "Check for new version" from the BOINC Manager's Help menu soon after installing an older version (BOINC 7.16.14) on my Intel Mac, the dialog says there  is no new version available, but the Event Log says
`A new version of BOINC is available (7.16.19). <a href=https://boinc.berkeley.edu/download.php>Download</a>` If I select "Check for new version again, the dialog does correctly show that there is a new version available.

This  happens whether I do it during or after the client runs CPU benchmarks. However, I had installed the older version (7.16.14) over the current version, so this may be an artifact of that. The problem occurred even when I installed the older version twice in a row,

@bema-aei @brevilo @AustinConlon I wanted to make you aware of this for when you test it.

**Comment by AenBleidd** [comment]
@CharlieFenton, I know about this issue. It occurs because new version check doesn't wait for new XML to be downloaded. It should be fixed, I just had no time to do this. I can fix it the week if needed

**Comment by CharlieFenton** [comment]
@AenBleidd I think that you are correct. I took a look at the code. Even though the latest  _get_current_version.xml_ file was already in the BOINC Data folder, the client does not set `gstate.newer_version` until it has downloaded a fresh get_current_version.xml file, but it responds to the _get_newer_version_ RPC from the Manager immediately. The function `static void handle_get_newer_version(GUI_RPC_CONN& grc)` in _gui_rpc_server_ops.cpp_ needs to wait for `void GET_CURRENT_VERSION_OP::handle_reply(int http_op_retval)` to complete.

The call to `gstate.new_version_check(true);` from `static void handle_get_newer_version(GUI_RPC_CONN& grc)` only starts the asynchronous download of the _get_current_version.xml_ file.

I believe this means that, after a new version becomes available, the first "Check for new version" from the BOINC Manager's Help menu will also fail unless the client has done its periodic (every two weeks) newer version check since the new version became available.

**Comment by AenBleidd** [comment]
#4557 ticket created

**Comment by brevilo** [comment]
> I don't have an M1 (Apple Silicon / arm64) Mac to test this on. I've added @brevilo as a reviewer.

Me neither, I'm afraid. @bema-aei should be aware by now and can be added as a formal reviewer of someone raised his member level accordingly (see previous comment).

**Comment by CharlieFenton** [comment]
@bema-aei I don't know if selecting a version for download from the web site uses the same mechanism as checking for new versions from the client, though it is definitely good to know the website download link works. (Was that also broken before?)

Could you also temporarily install an older arm64 Mac client and select "Check for new version" from the BOINC Manager's Help menu? Due to a different bug mentioned above, you may need to do this twice before the dialog says that a new version is available. (@AenBleidd  will fix the other bug soon.)

Here is the [link](https://boinc.berkeley.edu/dl/boinc_7.16.14_macOSX_universal.zip) to older version 7.16.14.

Thank you.
