### ISSUE TITLE
problems installing in Ubuntu

### ISSUE THREAD

**Issue by donburch888** [BOINC/boinc#4553]
**Describe the bug**
Does not install and run on linux

**Steps To Reproduce**
1. Clicked the link on https://boinc.berkeley.edu/download.php and ran
when that didn't work
2. "sudo apt-get install boinc-client boinc-manager" per https://boinc.berkeley.edu/wiki/Installing_BOINC#Linux

**Expected behavior**
Install and run without errors - something like on windows. 

**Screenshots**
```
don@Muscle:~$ ./Downloads/boinc_7.4.22_x86_64-pc-linux-gnu.sh
use /home/don/BOINC/run_manager to start BOINC
don@Muscle:~$ ~/BOINC/run_manager
./boincmgr: error while loading shared libraries: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory


don@Muscle:~$ sudo apt-get install boinc-client boinc-manager
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libboinc7 libwxgtk-webview3.0-gtk3-0v5
Suggested packages:
  boinc-client-opencl boinc-client-nvidia-cuda
The following NEW packages will be installed:
  boinc-client boinc-manager libboinc7 libwxgtk-webview3.0-gtk3-0v5
0 to upgrade, 4 to newly install, 0 to remove and 26 not to upgrade.
Need to get 2,383 kB of archives.
After this operation, 9,675 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://au.archive.ubuntu.com/ubuntu hirsute/universe amd64 libboinc7 amd64 7.16.16+dfsg-1 [399 kB]
Get:2 http://au.archive.ubuntu.com/ubuntu hirsute/universe amd64 boinc-client amd64 7.16.16+dfsg-1 [475 kB]
Get:3 http://au.archive.ubuntu.com/ubuntu hirsute/universe amd64 libwxgtk-webview3.0-gtk3-0v5 amd64 3.0.5.1+dfsg-2 [49.6 kB]
Get:4 http://au.archive.ubuntu.com/ubuntu hirsute/universe amd64 boinc-manager amd64 7.16.16+dfsg-1 [1,459 kB]
Fetched 2,383 kB in 2s (1,180 kB/s)        
Preconfiguring packages ...
Selecting previously unselected package libboinc7:amd64.
(Reading database ... 246809 files and directories currently installed.)
Preparing to unpack .../libboinc7_7.16.16+dfsg-1_amd64.deb ...
Unpacking libboinc7:amd64 (7.16.16+dfsg-1) ...
Selecting previously unselected package boinc-client.
Preparing to unpack .../boinc-client_7.16.16+dfsg-1_amd64.deb ...
Unpacking boinc-client (7.16.16+dfsg-1) ...
Selecting previously unselected package libwxgtk-webview3.0-gtk3-0v5:amd64.
Preparing to unpack .../libwxgtk-webview3.0-gtk3-0v5_3.0.5.1+dfsg-2_amd64.deb ...
Unpacking libwxgtk-webview3.0-gtk3-0v5:amd64 (3.0.5.1+dfsg-2) ...
Selecting previously unselected package boinc-manager.
Preparing to unpack .../boinc-manager_7.16.16+dfsg-1_amd64.deb ...
Unpacking boinc-manager (7.16.16+dfsg-1) ...
Setting up libboinc7:amd64 (7.16.16+dfsg-1) ...
Setting up libwxgtk-webview3.0-gtk3-0v5:amd64 (3.0.5.1+dfsg-2) ...
Setting up boinc-client (7.16.16+dfsg-1) ...
Setting up boinc-manager (7.16.16+dfsg-1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for libc-bin (2.33-0ubuntu5) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for mailcap (3.68ubuntu1) ...

don@Muscle:~$ ~/BOINC/run_manager
./boincmgr: error while loading shared libraries: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory
don@Muscle:~$ cd BOINC
don@Muscle:~/BOINC$ ./run_client --daemon
./boinc: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
don@Muscle:~/BOINC$ ./run_manager
./boincmgr: error while loading shared libraries: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory
don@Muscle:~/BOINC$ 
```

**System Information**
 - OS: Ubuntu 20.04 
 - BOINC Version: 

**Additional context**
This reminds me why Boinc isn't already running ... becase it didn't install/run when I swapped from Windows to Ubuntu on my desktop machine.

**Comment by cwallbaum** [comment]
Forget about Boinc 7.4.22, that's a very old version from 2014. You can safely delete `/home/don/Downloads/boinc_7.4.22_x86_64-pc-linux-gnu.sh` and remove the entire installation directory in your home (`/home/don/BOINC/`).

Using `sudo apt-get install boinc-client boinc-manager` was the correct way to install Boinc on Ubuntu. The Boinc client is installed as a system service, which means that it runs in the background and is automatically started at boot time. You can control this service via `systemctl`. To see if the Boinc client is currently running, open a console/terminal and run `sudo systemctl status boinc-client.service` which should tell you something like `Active: active (running)...`. To `stop`, `start` or `restart` the client, replace `status` in the command above accordingly, e.g. `sudo systemctl stop boinc-client.service`.

To control the client, there's the Boinc manager (`boincmgr`), a gui application that you can run on your desktop to add projects or make changes to the client's configuration/settings. There's also a commandline tool (`boinccmd`), but you might only need it if you installed Boinc on a server with no desktop environment at all.

Btw.: Boinc's configuration files are found in `/etc/boinc-client/`, its data directory in `/var/lib/boinc-client/` - just in case you need to make any changes which might not be done via the Boinc manager.

If you also like to use your gpu(s) for _crunching_, you have to install some additional packages. First of all, you need the proprietary drivers from AMD/NVIDIA (using Intel gpus with Boinc mostly doesn't make sense) - if Ubuntu finds any gpu, it should offer you to install these drivers via just one or two mouse clicks more or less automatically - and secondly, you need to `sudo apt-get install boinc-client-opencl boinc-client-nvidia-cuda`, depending on what gpu(s) you have and/or the projects support.

Hope that helps.

**Comment by AenBleidd** [comment]
@donburch888,

To use the latest version of BOINC please add this PPA first: https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/boinc
Then follow the steps mentioned by @cwallbaum.
