### ISSUE TITLE
Support other windows editions

### ISSUE THREAD

**Issue by Toby-Broom** [BOINC/boinc#4565]
**Describe the problem**
Looking at the change #4468 I noticed my windows version is not reported correctly either:

 OS: Microsoft Windows 10: x64 Edition, (10.00.19043.00) vs WindowsProductName : Windows 10 Pro for Workstations.

**Describe the solution you'd like**

Use the new GetProductInfo function (sysinfoapi.h) to report the different windows editions correctly.

**Additional context**
https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getproductinfo

#ifndef PRODUCT_PRO_WORKSTATION
#define PRODUCT_PRO_WORKSTATION        0x000000A1
#endif

**Comment by Toby-Broom** [comment]
it probably needs these lines too, looking in hostinfo_win.cpp

                            case PRODUCT_PRO_WORKSTATION:
                                safe_strcat(szSKU, "Windows 10 Pro for Workstations ");
                                break;

**Comment by Toby-Broom** [comment]
My test system is AMD one so I was waiting for a good patch before upgrading on that one, my others I was just going to wait for MS to push it, I did enable TMP and secure boot so there should not be a reason for them not to get the update.

**Comment by Toby-Broom** [comment]
I checked 0x000000A1 is the product type for Pro for Workstations on windows 11 also, so I guess that my example was wrong should be :

case PRODUCT_PRO_WORKSTATION:
                            safe_strcat(szSKU, "Pro for Workstations ");
                            break;

Then the snprintf will build up the correct string. so it will say Windows 10 Pro for Workstations or Windows 11 Pro for Workstations

**Comment by MagicQuantumMechanic** [comment]
Thanks Toby ( I have been too busy to update any of mine to 11 and even didn't run the usual testing either)

**Comment by Toby-Broom** [comment]
Here's a Win11 Pro for WS's machine, like before since it doesn't know this version of windows it just say x64
(https://lhcathome.cern.ch/lhcathome/show_host_detail.php?hostid=10294367)

**Comment by Toby-Broom** [comment]
Additionally, I maybe a better solution would be to refactor the code that it doesn't even report the product type,  I don't think it adds that much value?  Since Linux doesn't even have these sub divisions
