### ISSUE TITLE
Problem with text highlighting

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#4566]
**Describe the bug**
If i try to highlight project url in in project info screen by  double clicking text it does not highlight last letter so when I press copy highlighted it copies incomplete link.
**Steps To Reproduce**
1. 
2. 

**Expected behavior**

**Screenshots**
![Снимок экрана (39)](https://user-images.githubusercontent.com/8822292/138175414-2faf700c-b220-478f-8539-8c14c08e6260.png)

**System Information**
 - OS: Windows 11 Microsoft Windows [Version 10.0.22000.258]
 - BOINC Version: 7.16.20

**Additional context**
On some projects only "/" gets cut off, but on others letter gets cut off too.

**Comment by kotenok2000** [comment]
This is a list of my projects urls copied
https://sech.me/boinc/Amicabl
http://asteroidsathome.net/boin
https://boinc.tacc.utexas.edu
https://csgrid.org/csg
https://climateprediction.ne
https://boinc.thesonntags.com/collat
http://www.cosmologyathome.org
http://einstein.phys.uwm.edu
http://gaiaathome.eu/gaiaathom
http://gerasim.boinc.ru
https://www.gpugrid.net
https://root.ithena.net/us
https://www.kryptosathome.com
https://boinc.multi-pool.info/latinsquare
https://lhcathome.cern.ch/lhcathom
http://milkyway.cs.rpi.edu/milkywa
https://minecraftathome.com/minecrafthom
https://www.mlcathome.org/mlcathom
http://moowrap.net
https://boinc.nanohub.org/nanoHUB_at_hom
http://escatter11.fullerton.edu/nf
http://numberfields.asu.edu/NumberFields
https://boinc.progger.info/odlk
http://www.primegrid.com
http://boincvm.proxyma.ru:30080/test4vm
https://quchempedia.univ-angers.fr/athome
https://rake.boincfast.ru/rakesearc
http://www.rnaworld.de/rnaworld
https://boinc.bakerlab.org/rosett
https://www.sidock.si/sidoc
http://srbase.my-firewall.org/sr5
https://boinc.tbrada.eu
http://gene.disi.unitn.it/tes
https://universeathome.pl/universe
http://www.vdwnumbers.org
http://www.worldcommunitygrid.org
https://wuprop.boinc-af.org
http://yafu.myfirewall.org/yafu
http://www.rechenkraft.net/yoy

**Comment by AenBleidd** [comment]
Is not reproducible anymore on the latest build on master. Should have been fixed on wxWidgets side.
