### ISSUE TITLE
Build docs: How to run the Manager from a macOS build?

### ISSUE THREAD

**Issue by TrevorBurnham** [BOINC/boinc#4580]
I'm interested in contributing to this project, but I'm having trouble with the build instructions for macOS. I followed the instructions in [HowToBuildBOINC_XCode.pdf](https://github.com/BOINC/boinc/blob/a80d131a8c011b62761464925f08fe3758ebc709/mac_build/HowToBuildBOINC_XCode.pdf] and managed to get the build steps to run successfully, but I don't see any instructions for executing the build artifacts.

In particular, I want to run the BOINC Manager (the GUI) from a local build, so that I can work on issues like #2917. After I run `source setupForBoinc.sh && source BuildMacBOINC.sh`, the `mac_build/build/boinc.build/Deployment` build dir contains these subdirs:

```
BOINC_Client.build
detect_rosetta_cpu.build
libboinc.build
SetVersion.build
```

None of these seem to correspond to the Manager. Can someone help me figure out what I'm missing?

**Comment by CharlieFenton** [comment]
Follow the instructions under _Building BOINC Manager Installer_, then run the installer you just built.

**Comment by CharlieFenton** [comment]
For debugging BOINC on MacOS, it is better to build using the Xcode GUI rather than the _BuildMacBOINC.sh_ script so that you can run it under the Xcode debugger.

There is an extra wrinkle even if wxWidgets now supports dark mode on Macs. The main BOINC Advanced View displays use _BOINCListCtrl_, which is derived from _wxListCtrl_, which is a native control only under MS Windows but not on MacOS or Linux. So the wxWdgets implementation of _wxListCtrl_ probably requires significant modification.

**Comment by AenBleidd** [comment]
I believe question is answered and this tiket could be closed.
Feel free to reopen it if smth is still unclear.

P.S. #2917 ticket is better discuss in the corresponding thread since this particular ticket is about different topic.

**Comment by TrevorBurnham** [comment]
> For debugging BOINC on MacOS, it is better to build using the Xcode GUI rather than the *BuildMacBOINC.sh* script so that you can run it under the Xcode debugger.

Thank you, appreciate the help! I've tried running the project in Xcode, but haven't been able to get it working. When I try to build the `mgr_boinc` target, the "Link boinc (arm64)" step fails with several errors of the form "Undefined symbols for architecture arm64". (Possibly because I'm on an M1 Mac.) Any ideas?

<details>
  <summary>Full error output</summary>
<pre><code>Ld /Users/trevor.burnham/Library/Developer/Xcode/DerivedData/boinc-apujxcbhdoddkbhcynxmlqsmjwjo/Build/Intermediates.noindex/boinc.build/Development/BOINC_Client.build/Objects-normal/arm64/Binary/boinc normal arm64 (in target 'BOINC_Client' from project 'boinc')
    cd /Users/trevor.burnham/code/boinc/mac_build
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-macos10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -L/Users/trevor.burnham/Library/Developer/Xcode/DerivedData/boinc-apujxcbhdoddkbhcynxmlqsmjwjo/Build/Products/Development -L../../curl-7.79.1/lib/.libs -L../../c-ares-1.17.2/src/lib/.libs -L../../openssl-3.0.0/ -F/Users/trevor.burnham/Library/Developer/Xcode/DerivedData/boinc-apujxcbhdoddkbhcynxmlqsmjwjo/Build/Products/Development -filelist /Users/trevor.burnham/Library/Developer/Xcode/DerivedData/boinc-apujxcbhdoddkbhcynxmlqsmjwjo/Build/Intermediates.noindex/boinc.build/Development/BOINC_Client.build/Objects-normal/arm64/boinc.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/trevor.burnham/Library/Developer/Xcode/DerivedData/boinc-apujxcbhdoddkbhcynxmlqsmjwjo/Build/Intermediates.noindex/boinc.build/Development/BOINC_Client.build/Objects-normal/arm64/boinc_lto.o -Xlinker -no_deduplicate -stdlib\=libc++ -L. -lcurl -lcares -lcrypto -lssl -lldap -lz -framework IOKit -framework OpenGL -framework Carbon -framework Security -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/trevor.burnham/Library/Developer/Xcode/DerivedData/boinc-apujxcbhdoddkbhcynxmlqsmjwjo/Build/Intermediates.noindex/boinc.build/Development/BOINC_Client.build/Objects-normal/arm64/boinc_dependency_info.dat -o /Users/trevor.burnham/Library/Developer/Xcode/DerivedData/boinc-apujxcbhdoddkbhcynxmlqsmjwjo/Build/Intermediates.noindex/boinc.build/Development/BOINC_Client.build/Objects-normal/arm64/Binary/boinc

Undefined symbols for architecture arm64:
  "_idn2_check_version", referenced from:
      _curl_version in libcurl.a(libcurl_la-version.o)
      _curl_version_info in libcurl.a(libcurl_la-version.o)
      _Curl_idnconvert_hostname in libcurl.a(libcurl_la-url.o)
  "_idn2_free", referenced from:
      _conn_free in libcurl.a(libcurl_la-url.o)
      _Curl_free_idnconverted_hostname in libcurl.a(libcurl_la-url.o)
      _create_conn in libcurl.a(libcurl_la-url.o)
  "_idn2_lookup_ul", referenced from:
      _Curl_idnconvert_hostname in libcurl.a(libcurl_la-url.o)
  "_idn2_strerror", referenced from:
      _Curl_idnconvert_hostname in libcurl.a(libcurl_la-url.o)
  "_nghttp2_http2_strerror", referenced from:
      _http2_handle_stream_close in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_is_fatal", referenced from:
      _http2_send in libcurl.a(libcurl_la-http2.o)
      _on_frame_recv in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_pack_settings_payload", referenced from:
      _Curl_http2_request_upgrade in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_priority_spec_init", referenced from:
      _h2_pri_spec in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_callbacks_del", referenced from:
      _Curl_http2_setup in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_callbacks_new", referenced from:
      _Curl_http2_setup in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_callbacks_set_error_callback", referenced from:
      _Curl_http2_setup in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_callbacks_set_on_begin_headers_callback", referenced from:
      _Curl_http2_setup in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_callbacks_set_on_data_chunk_recv_callback", referenced from:
      _Curl_http2_setup in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_callbacks_set_on_frame_recv_callback", referenced from:
      _Curl_http2_setup in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_callbacks_set_on_header_callback", referenced from:
      _Curl_http2_setup in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_callbacks_set_on_stream_close_callback", referenced from:
      _Curl_http2_setup in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_callbacks_set_send_callback", referenced from:
      _Curl_http2_setup in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_check_request_allowed", referenced from:
      _h2_process_pending_input in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_client_new", referenced from:
      _Curl_http2_setup in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_del", referenced from:
      _http2_disconnect in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_get_remote_settings", referenced from:
      _on_frame_recv in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_get_stream_user_data", referenced from:
      _on_frame_recv in libcurl.a(libcurl_la-http2.o)
      _on_data_chunk_recv in libcurl.a(libcurl_la-http2.o)
      _on_stream_close in libcurl.a(libcurl_la-http2.o)
      _on_begin_headers in libcurl.a(libcurl_la-http2.o)
      _on_header in libcurl.a(libcurl_la-http2.o)
      _data_source_read_callback in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_mem_recv", referenced from:
      _h2_process_pending_input in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_resume_data", referenced from:
      _Curl_http2_done_sending in libcurl.a(libcurl_la-http2.o)
      _http2_send in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_send", referenced from:
      _Curl_http2_done in libcurl.a(libcurl_la-http2.o)
      _h2_session_send in libcurl.a(libcurl_la-http2.o)
      _http2_conncheck in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_set_local_window_size", referenced from:
      _Curl_http2_switched in libcurl.a(libcurl_la-http2.o)
      _Curl_http2_stream_pause in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_set_stream_user_data", referenced from:
      _Curl_http2_done in libcurl.a(libcurl_la-http2.o)
      _Curl_http2_switched in libcurl.a(libcurl_la-http2.o)
      _on_frame_recv in libcurl.a(libcurl_la-http2.o)
      _on_stream_close in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_upgrade2", referenced from:
      _Curl_http2_switched in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_want_read", referenced from:
      _should_close_session in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_session_want_write", referenced from:
      _Curl_http2_done_sending in libcurl.a(libcurl_la-http2.o)
      _http2_getsock in libcurl.a(libcurl_la-http2.o)
      _should_close_session in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_strerror", referenced from:
      _h2_process_pending_input in libcurl.a(libcurl_la-http2.o)
      _Curl_http2_switched in libcurl.a(libcurl_la-http2.o)
      _Curl_http2_stream_pause in libcurl.a(libcurl_la-http2.o)
      _http2_conncheck in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_submit_ping", referenced from:
      _http2_conncheck in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_submit_priority", referenced from:
      _h2_session_send in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_submit_request", referenced from:
      _http2_send in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_submit_rst_stream", referenced from:
      _Curl_http2_done in libcurl.a(libcurl_la-http2.o)
      _on_frame_recv in libcurl.a(libcurl_la-http2.o)
      _on_header in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_submit_settings", referenced from:
      _Curl_http2_switched in libcurl.a(libcurl_la-http2.o)
  "_nghttp2_version", referenced from:
      _curl_version_info in libcurl.a(libcurl_la-version.o)
      _Curl_http2_ver in libcurl.a(libcurl_la-http2.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</code></pre>
</details>

**Comment by CharlieFenton** [comment]
These errors are all from trying to link curl. Make sure you are using the correct version of curl, and rebuild it. If you are building from the GIT Master source tree, that is _curl 7.73.0_. Run the following:
```
cd {path{}/curl-7.73.0
source {path}/mac_build/buildcurl.sh -clean
```

**Comment by CharlieFenton** [comment]
CORRECTION: the current version of curl for GIT Master is curl-7.79.1, so your should run the following:
```
cd {path{}/curl-7.79.1
source {path}/mac_build/buildcurl.sh -clean
```

**Comment by TrevorBurnham** [comment]
Thanks. I had the `curl-7.79.1` dir in the correct place, but I hadn't run `buildcurl.sh`. (I don't see any mention of it in `HowToBuildBOINC_XCode.pdf`.) Unfortunately, after running that script, I still saw the same errors in Xcode.

I grepped the project for references to `buildcurl.sh` and found [buildMacDependencies.sh](https://github.com/BOINC/boinc/blob/a80d131a8c011b62761464925f08fe3758ebc709/3rdParty/buildMacDependencies.sh), so I tried running that. That successfully built all of the 3rd-party libraries in `3rdParty/mac`, but I can't seem to get Xcode to recognize the builds in that directory. The build now fails with

```
'openssl/rsa.h' file not found
```

even after I add `"$(SRCROOT)/../3rdParty/mac/openssl-3.0.0/include"` to "Header Search Paths". I've confirmed that `openssl-3.0.0/include/openssl/rsa.h` exists, so I'm not sure why Xcode isn't picking it up. Any ideas? (How was it picking up the `../openssl-3.0.0` dir that I previously had as a sibling of `boinc/`?)

**Comment by CharlieFenton** [comment]
_buildMacDependencies.sh_ is **not** the  correct script you should use; it is used by the continuous integration tests in GITHub and will not put the libraries in the correct place for building on your Mac. As the build instructions _HowToBuildBOINC_XCode.pdf_ say, you need to build the libraries using:
```
cd {path}/BOINC_dev/boinc/mac_build/
source setupForBoinc.sh -clean

```
Please make sure you are following every step in the _HowToBuildBOINC_XCode.pdf_ build instructions exactly.

**Comment by CharlieFenton** [comment]
_setupForBoinc.sh_ runs _buildcurl.sh_, along with the other individual scripts for building each dependent library (_buildc-ares.sh_, _buildfreetype.sh_, _buildFTGL.sh_, _buildopenssl.sh_ and _buildWxMac.sh_). I strongly recommend you read the comments and code in each of these scripts for a better understanding. If you plan to work on BOINC bugs, you will need to familiarize yourself with the code.
