### ISSUE TITLE
Fix the software behaviour for closing the BOINC manager window

### ISSUE THREAD

**Issue by elfring** [BOINC/boinc#4599]
I am trying the software “BOINC 7.19.0” out on an openSUSE Tumbleweed system.
I got another scientific application running here as it is indicated by the program “BOINC Manager”.
Thus the computation progress is displayed as usual (in principle).

:eyes: But I observe that the corresponding service is stopped (together with active background processes) after closing the application window (shortcut “Ctrl+W”) for this program.
:thought_balloon: I would expect that the computations may be continued.
* I would appreciate if an additional command like “`systemctl restart boinc-client`” can be avoided for this use case.
* Is there a need to reconsider information from [a previous issue like “Closing manager window minimizes it instead (Linux)”](https://github.com/BOINC/boinc/issues/1348 "Clarification request") once more? :thinking:

**Comment by AenBleidd** [comment]
Basically this is a duplicate of #3105.
Closing it for now, since the entire feature should be revisited and handles in a more appropriate way.
