### ISSUE TITLE
Very strange CPU management (i9 12900K)

### ISSUE THREAD

**Issue by jeremythille** [BOINC/boinc#4604]
**Describe the bug**

CPU : i9 12900K, 24 threads (8 P-cores + 8 E-cores)

BOINC set to "Use 100% of the CPUs, 100% of the time, run always"

Result :
✔ 24 tasks shown running concurrently in BOINC
✔ 24 different processes in the task manager
❌ 8 cores used at 100% in the task manager + 16 cores idle ("parked")
❌ Each process is shown to use 0~2% of CPU, despite the graphs showing 8 CPU used at 100% in the task manager's "performance" tab

✔ Running "CPU benchmark" does use 100% of all 24 CPUs for a few seconds, though

Result :

**Steps To Reproduce**
1. Run BOINC on an i9 12900K in Windows 10, I guess?

**Expected behavior**

Use 100% of the CPUs and 100% of their time

**Screenshots**

![2022-01-17_082649](https://user-images.githubusercontent.com/3706912/149727403-fbd243b7-3cf0-47af-a2c3-b049e30b839d.png)

![2022-01-17_082929](https://user-images.githubusercontent.com/3706912/149727235-ab748244-6d0e-476a-aaa4-3fcb3bb521c3.png)

![2022-01-17_084204](https://user-images.githubusercontent.com/3706912/149728128-1d8a3dab-b05e-46a3-bb4e-7ec6b56fb084.png)

**System Information**
 - OS: Windows 10 Version 10.0.19043 Build 19043
 - BOINC Version: 7.16.20 x64

**Additional context**

I have tried to reinstall BOINC completely, same problem

**Comment by AenBleidd** [comment]
BOINC doesn't apply any CPU affinity. So if several processes are run on the same CPU while other CPUs are idle - it's a decision of Windows to schedule CPU resource usage this way. 
To be honest, I've never saw such a behavior.
Not sure it is possible to watch in realtime what CPU core is used by what process (at least I don't know any way of doing this).

**Comment by jeremythille** [comment]
But then why does running a CPU benchmark from BOINC use all CPUs correctly?

**Comment by Ageless93** [comment]
The first problem is that you compare the use of the CPU as an older multicore CPU where you shouldn't do so. You should instead compare these CPUs to ARM CPUs where BOINC also won't use some of the cores, but if set to 100% CPU it double or triple loads everything on the efficiency cores. 

The second problem is that Windows 10 doesn't completely support the new Alder Lake CPUs, or at least the ""Thread Director," a dedicated piece of silicon circuitry inside the CPU that provides hints to the operating system on how to best distribute processes among the "Golden Cove" performance cores and "Gracemont" efficiency cores." This is fully supported in Windows 11 only; for Windows 10, Alder Lake does provide the static UEFI CPPC2 "favored cores" table to the OS, which contains some information on the core configuration. ([Source](https://www.techpowerup.com/review/alder-lake-windows-10-performance/))

I wouldn't expect any of the BOINC projects to have released a (test) application yet that can use the different hybrid cores in your CPU coherently. 
An option you can try is to disabled the efficiency cores in the BIOS and see what that does. 
Another option is to use Windows' CPU affinity. ([Source](https://www.techpowerup.com/review/alder-lake-windows-10-performance/7.html))

**Comment by AenBleidd** [comment]
> But then why does running a CPU benchmark from BOINC use all CPUs correctly?

Benchmark app might use CPU affinity for their threads internally

**Comment by jeremythille** [comment]
So should I close the issue as expected behaviour (or won't fix?) What should I do?

**Comment by AenBleidd** [comment]
> So should I close the issue as expected behaviour (or won't fix?) What should I do?

Keep it as is. I'll handle it by myself later.
Thanks.

**Comment by Le-zOU** [comment]
I have exactly the same issue on a i9-14900k

![Image](https://github.com/user-attachments/assets/65ddb1cb-ff04-4c8d-8697-ad76442b4dec)
