### ISSUE TITLE
Can't get RPC password: gui_rpc_auth.cfg not found.

### ISSUE THREAD

**Issue by mmahmoudian** [BOINC/boinc#4606]
First things first: Thanks for developing and maintaining such software. highly appreciated. :+1:

**Describe the bug**

I get `Can't get RPC password: gui_rpc_auth.cfg not found.` when I use boinccmd regardless of if I provide the password manually or let it file the file itself.

The `boinccmd` produces the error every single time even for `--version` 

The command above working without even providing the password clearly means that the `boinccmd` can access the process. Either it doesn't need the password (which is weird) or it can access the password which begs the question why the other commands doesn't work

**Steps To Reproduce**
1. install Boinc via `pacman` official repo (`sudo pacman --sync boinc`)
2. add some projects and get it to work (of course going through the pain of reading https://boinc.berkeley.edu/dev/forum_thread.php?id=14013#101083
3. when it is working and have done few tasks done (and confirmed from the pool), try anything with `boinccmd`

**Expected behavior**

- I expect to see things like `--version` to work without needing to access the password. (screenshot below)
- I expect to not see the error when the file permission is correct (screenshot below)
- I expect to not see the error when I manually provide the password (screenshot below)

**Screenshots**

![image](https://user-images.githubusercontent.com/390889/150151061-ccf4d98d-3234-40f2-ac09-d4c5a3b1f417.png)
![image](https://user-images.githubusercontent.com/390889/150153100-ed837828-928e-4000-913c-9ec013d94f52.png)

**System Information**
 - OS: Manjaro (fully updated)
     - Kernel: 5.10.89-1-MANJARO x86_64
     - Desktop: KDE Plasma 5.23.4
 - BOINC Version: boinccmd,  built from BOINC 7.16.20

**Additional context**

Let me know if you need info on anything. I just provided those that I thought might be useful for tracking this issue down.
I also tried to make sure [this is not duplicate](https://github.com/BOINC/boinc/issues?q=is%3Aissue+boinccmd+pass) but still there is a chance that I have missed something, so sorry about that beforehand.

**Comment by AenBleidd** [comment]
Closed as a dupliate of #4267

**Comment by mmahmoudian** [comment]
I don't think it is duplicate as even when I manually provide the password (the screenshot above), the error remains. Therefore it is not about being able to read the file.

**Comment by AenBleidd** [comment]
> I don't think it is duplicate as even when I manually provide the password (the screenshot above), the error remains. Therefore it is not about being able to read the file.

It still this error.

**Comment by AenBleidd** [comment]
@mmahmoudian, you can check forums for the case you have. All you need is to fix permissions of this file to tee your user read it.

**Comment by mmahmoudian** [comment]
As you can see also in the screenshot, the permission for that file is rw-r--r-- (a.k.a 644) which means it is readable by everyone. That is the reason the gui application can successfully work.

**Comment by Ageless93** [comment]
We have a nice long thread about this [at the BOINC forums](https://boinc.berkeley.edu/forum_thread.php?id=14013#101083), you can read through it and if none of the options there work add to it.

**Comment by mmahmoudian** [comment]
So all that discussions in all those links above were **completely waste of time and useless**. It is so so bad that boinc after all these years doesn't have proper errors and documentation.

## Solution

For others who land on this issue, don't waste your time on those threads above, instead read https://wiki.archlinux.org/title/BOINC or just do the following:

```sh
# stop the service just in case it is running
systemctl stop boinc-client.service

# add your user to the "boinc" group
usermod -a -G boinc $(whoami)

# make sure you are at home
cd ~/

# create a symlink to the password file
ln -s /var/lib/boinc/gui_rpc_auth.cfg gui_rpc_auth.cfg

# make sure the link you created is readable
chmod 640 gui_rpc_auth.cfg

# start the service (this might take couple of seconds, so wait for a little bit)
systemctl start boinc-client.service

# test if everything works
boinccmd --get_host_info
```

Remember that the `boinccmd` has lots of rough edges and the documentation is not up to date. So be patient and try everything.

P.s: I might at some point calm down and contribute to this project by making the errors better and more informative.

**Comment by MagicQuantumMechanic** [comment]
Thanks for the over 200 emails in the last 60 seconds


​Samson
________________________________
