### ISSUE TITLE
Problem with <max_concurrent>0</max_concurrent> 

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#4617]
**Describe the bug**
I have set this  app_config, but boinc still computes rosetta app in addition to rosetta_python_projects 
[app_config.txt](https://github.com/BOINC/boinc/files/7966612/app_config.txt)

**Steps To Reproduce**
1. 
2. 

**Expected behavior**
<max_concurrent>0</max_concurrent> should disallow computing of given app
**Screenshots**

**System Information**
 - OS: Microsoft Windows [Version 10.0.22000.469]
 - BOINC Version: 7.16.20

**Additional context**

**Comment by computezrmle** [comment]
Rosetta has 3 apps in their app list:
- Rosetta (currently v4.20)
- Rosetta Mini (currently v3.78; outdated but still listed)
- rosetta python projects (vbox64; currently v1.03)

Unlike other projects Rosetta does not offer a setting where a volunteer can select/deselect individual apps.
Instead, they offer a switch on each computer details page where a volunteer can skip/unskip vbox apps.
That switch is only visible if the computer reports VirtualBox being installed.

That way the server either sends
- non-vbox tasks or
- a mix of vbox and non-vbox tasks

As long as there are non-vbox tasks in the server queue the server will not send rosetta python only.
What to do with the non-vbox tasks if a volunteer gets them but disallows to process them?

Beside that <max_concurrent>0</max_concurrent> is already in use for telling the client there's no limit at all.

**Comment by kotenok2000** [comment]
So how do i set limit to 0?

**Comment by AenBleidd** [comment]
Closing this as `Not an issue`
