### ISSUE TITLE
apk can't be installed

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [BOINC/boinc#4618]
**Describe the bug**

The `.apk` doesn't get installed on Android phone.

The app says: 'The app was not installed.'

The version I tried to install was https://boinc.berkeley.edu/dl/boinc_7.18.1.apk and I have the Avast antivirus

Later I will dig with `adb` `logcat`, and will also add more info, having little time for now

**Steps To Reproduce**
1. Install the `boinc` `apk` for the first time, `.apk` goes from the external `sd` card (not from app markets like `fdroid`, not from internal storage);
2. Follow the short `apk` install wizard & see the message.

**Expected behavior**
App should install.

**System Information**
 - OS: Android 9
 - Hardware brand: Sony phone XA2
 - Hardware model name: H4213
 - `BOINC` Version: https://boinc.berkeley.edu/dl/boinc_7.18.1.apk

**Additional context**

Btw I'm an experienced sw dev, also know Andr. dev somewhat.

**Comment by AenBleidd** [comment]
Did you allow installation from unknown sources?

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
(Just a tmp quick note) I think yes but unsure, wasn't able to quickly find the exact answer, I need to answer later.

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
@AenBleidd I'm unsure how to get the exact answer to your question, but I see this:

1. Chrome browser app is currently `allowed` to `install the unknown apps`;
2. I open Chrome browser app;
3. I type the URL `https://boinc.berkeley.edu/dl/boinc_7.18.1.apk` and open it;
4. I download the `.apk` file once again;
5. I open the downloaded file;
6. Avast antivirus checks it and tells it's safe;
7. The screen tells that this app doesn't require special permissions, I click Install;
8. It answers `App installed`, I click Open

All now seems to be okay, the defect did not repeat.
