### ISSUE TITLE
Tasks requiring more disk space despite over 300GB free on a dedicated drive

### ISSUE THREAD

**Issue by photohac** [BOINC/boinc#4643]
**Describe the bug**

Rosetta@home: Notice from serve 
Rosetta needs 1907.35MB more disk 
space. You currently have 0.00 MB available and it needs 1907.35 MB.

SiDock@home: Notice from server
CurieMarieDock on BOINC + zipped 
input, checkpoints and progress bar needs 128.00MB more disk space. You 
currently have 0.00 MB available and it needs 128.00 MB.

This can not be possible. BOINC is on a dedicated 500GB drive (465 partition) of which only 129 is being used and there is 336 free.

Memory usage is 62% of 49,078MB

Rosetta is running 14 Python Vbox tasks and one standard 4.2 task 
Prior to that SiDock was running 15 tasks

**Steps To Reproduce**
1.  unknown
2. 

**Expected behavior**

This problem should not happen

**Screenshots**

**System Information**
 - OS:  Win10
 - BOINC Version:  7.16.20 Vbox 6.1.30

**Additional context**

RAH is Vbox and SiDock is non Vbox so hard to pin down if it is Vbox related or not.
![data drive](https://user-images.githubusercontent.com/99243332/154723472-3a52cb2d-f09a-4858-88e3-c8b61b1a81e1.png)
![disk space](https://user-images.githubusercontent.com/99243332/154723474-1958db6a-45e2-4a70-beec-6562bd52d4ff.png)
![notices](https://user-images.githubusercontent.com/99243332/154723476-9286f321-cf40-4af5-8e28-ae44752270d4.png)

**Comment by AenBleidd** [comment]
Looks like you limited allowed disk usage by BOINC. Check preferences

**Comment by AenBleidd** [comment]
![image](https://user-images.githubusercontent.com/3234209/154724124-385fd65a-3f79-432b-9ff2-5b6285904b80.png)

**Comment by computezrmle** [comment]
And a screenshot from the "harddisk" tab of your BOINC manager.

**Comment by photohac** [comment]
![comp pref](https://user-images.githubusercontent.com/99243332/154730264-0bcf8453-096c-4291-97c2-4e93c588f219.png)
![dsik pref](https://user-images.githubusercontent.com/99243332/154730265-16fe0162-497f-40eb-9691-a16fe36d3545.png)

**Comment by AenBleidd** [comment]
Hm, are you sure you still have space left on that device? Settings looks fine for me

**Comment by photohac** [comment]
![drive](https://user-images.githubusercontent.com/99243332/154731996-c6380fb6-b57d-495c-b467-e299be393f41.png)

**Comment by photohac** [comment]
No other ideas? 
Is it a bug with BOINC or the projects or what?
It is not the first time this has happened.
Leave it in your hands now....

**Comment by AenBleidd** [comment]
Yeah, that looks like a bug. I'll check it out and reach to you either with solution or to ask for more information.
Thanks for the report.

**Comment by photohac** [comment]
Thanks alot!
Hear from you in the future.

**Comment by photohac** [comment]
New project new error of the same kind:

2/23/2022 1:56:01 PM | GPUGRID | Message from server: New version of ACEMD needs 3814.70MB more disk space.  You currently have 0.00 MB available and it needs 3814.70 MB.


No settings have changed since I introduced this problem to you.

**Comment by Ageless93** [comment]
Could you please post the contents of your global_prefs.xml and global_prefs_override.xml files from the BOINC Data directory?

**Comment by photohac** [comment]
<global_preferences>

    <source_project>https://lhcathome.cern.ch/lhcathome/</source_project>
    <source_scheduler>https://lhcathome.cern.ch/lhcathome_cgi/cgi
</source_scheduler>

<mod_time>1637344257</mod_time>
<max_ncpus_pct>100</max_ncpus_pct>
<cpu_usage_limit>100</cpu_usage_limit>
<run_on_batteries>1</run_on_batteries>
<run_if_user_active>1</run_if_user_active>
<run_gpu_if_user_active>1</run_gpu_if_user_active>
<idle_time_to_run>3</idle_time_to_run>
<suspend_if_no_recent_input>0</suspend_if_no_recent_input>
<suspend_cpu_usage>0</suspend_cpu_usage>
<work_buf_min_days>0.1</work_buf_min_days>
<work_buf_additional_days>0.75</work_buf_additional_days>
<cpu_scheduling_period_minutes>60</cpu_scheduling_period_minutes>
<disk_interval>60</disk_interval>
<disk_max_used_gb>100</disk_max_used_gb>
<disk_min_free_gb>2</disk_min_free_gb>
<disk_max_used_pct>100</disk_max_used_pct>
<ram_max_used_busy_pct>80</ram_max_used_busy_pct>
<ram_max_used_idle_pct>90</ram_max_used_idle_pct>
<leave_apps_in_memory>1</leave_apps_in_memory>
<vm_max_used_pct>50</vm_max_used_pct>
<max_bytes_sec_down>0</max_bytes_sec_down>
<max_bytes_sec_up>0</max_bytes_sec_up>
<daily_xfer_limit_mb>0</daily_xfer_limit_mb>
<daily_xfer_period_days>0</daily_xfer_period_days>
<dont_verify_images>0</dont_verify_images>
<confirm_before_connecting>0</confirm_before_connecting>
<hangup_if_dialed>0</hangup_if_dialed>
<venue name="school">
<max_ncpus_pct>100</max_ncpus_pct>
<cpu_usage_limit>100</cpu_usage_limit>
<run_on_batteries>1</run_on_batteries>
<run_if_user_active>1</run_if_user_active>
<run_gpu_if_user_active>1</run_gpu_if_user_active>
<idle_time_to_run>3</idle_time_to_run>
<suspend_if_no_recent_input>0</suspend_if_no_recent_input>
<suspend_cpu_usage>0</suspend_cpu_usage>
<work_buf_min_days>0.1</work_buf_min_days>
<work_buf_additional_days>0.75</work_buf_additional_days>
<cpu_scheduling_period_minutes>60</cpu_scheduling_period_minutes>
<disk_interval>60</disk_interval>
<disk_max_used_gb>0</disk_max_used_gb>
<disk_min_free_gb>1</disk_min_free_gb>
<disk_max_used_pct>90</disk_max_used_pct>
<ram_max_used_busy_pct>50</ram_max_used_busy_pct>
<ram_max_used_idle_pct>90</ram_max_used_idle_pct>
<leave_apps_in_memory>0</leave_apps_in_memory>
<vm_max_used_pct>75</vm_max_used_pct>
<max_bytes_sec_down>0</max_bytes_sec_down>
<max_bytes_sec_up>0</max_bytes_sec_up>
<daily_xfer_limit_mb>0</daily_xfer_limit_mb>
<daily_xfer_period_days>0</daily_xfer_period_days>
<dont_verify_images>0</dont_verify_images>
<confirm_before_connecting>0</confirm_before_connecting>
<hangup_if_dialed>0</hangup_if_dialed>
</venue>
</global_preferences>

------------------------------------------------------------

<global_preferences>
   <run_on_batteries>1</run_on_batteries>
   <run_if_user_active>1</run_if_user_active>
   <run_gpu_if_user_active>1</run_gpu_if_user_active>
   <suspend_cpu_usage>0.000000</suspend_cpu_usage>
   <start_hour>0.000000</start_hour>
   <end_hour>0.000000</end_hour>
   <net_start_hour>0.000000</net_start_hour>
   <net_end_hour>0.000000</net_end_hour>
   <leave_apps_in_memory>1</leave_apps_in_memory>
   <confirm_before_connecting>0</confirm_before_connecting>
   <hangup_if_dialed>0</hangup_if_dialed>
   <dont_verify_images>0</dont_verify_images>
   <work_buf_min_days>1.000000</work_buf_min_days>
   <work_buf_additional_days>0.750000</work_buf_additional_days>
   <max_ncpus_pct>95.000000</max_ncpus_pct>
   <cpu_scheduling_period_minutes>60.000000</cpu_scheduling_period_minutes>
   <disk_interval>60.000000</disk_interval>
   <disk_max_used_gb>0.000000</disk_max_used_gb>
   <disk_max_used_pct>100.000000</disk_max_used_pct>
   <disk_min_free_gb>2.000000</disk_min_free_gb>
   <vm_max_used_pct>70.000000</vm_max_used_pct>
   <ram_max_used_busy_pct>90.000000</ram_max_used_busy_pct>
   <ram_max_used_idle_pct>98.000000</ram_max_used_idle_pct>
   <max_bytes_sec_up>0.000000</max_bytes_sec_up>
   <max_bytes_sec_down>0.000000</max_bytes_sec_down>
   <cpu_usage_limit>100.000000</cpu_usage_limit>
   <daily_xfer_limit_mb>0.000000</daily_xfer_limit_mb>
   <daily_xfer_period_days>0</daily_xfer_period_days>
</global_preferences>

**Comment by Ageless93** [comment]
I have the feeling that the <disk_max_used_gb>0.000000</disk_max_used_gb> here is literally Use at maximum 0GB, not "unlimited". What happens when you insert a value here? Say 50GB?

**Comment by photohac** [comment]
Don't know.
These errors pop up at random.
In the program I have it set for leave 2GB free and use the rest.

I have never messed with anything on this level!

Have a look further up at the screen shots of the settings and then tell me
what to change where.

**Comment by Ageless93** [comment]
In the Disk and Memory tab set "Disk: Use no more than N" to a value bigger than 0. Size is in gigabytes. Like I opted, what happens when you set it to 50 and then save?

**Comment by photohac** [comment]
You will have to give me about 20 hours to get back to you. I'm shutting
down for the night and when I'm up, I'll let it run while I'm at work.

**Comment by computezrmle** [comment]
I suspect the error is in function max_allowable_disk here:
https://github.com/BOINC/boinc/blob/master/sched/sched_send.cpp#L348

While disk_max_used_gb=0 is thought to be interpreted "unlimited" L360 sets a default limit of 100GB.
If hit this results in x1 (L377-L381) being the limiting "x".

Same can happen to x2 if the client is installed on small disks since L363 sets prefs.disk_max_used_pct to a default of 50.

Workaround for older clients:
Don't leave disk_max_used_gb and disk_max_used_pct at "0".
Instead use higher limits.

**Comment by photohac** [comment]
[computezrmle] - seems you were onto something. No errors since I turned on the system and 8am this morning.

You mentioned older builds, but I am using the latest release, so I guess this issue carried over. Something to correct for next release I guess.

Anyway, thanks all of you who posted. If it pops up again, I'll say something, but based on what your linked to and your solution, I don't think it will show up again.

**Comment by talregev** [comment]
Can you show the disk tab?
Also this notification can remain even if you have the space.

**Comment by AenBleidd** [comment]
> Can you show the disk tab? Also this notification can remain even if you have the space for the project and everything is fine.

The issue was already found: https://github.com/BOINC/boinc/issues/4643#issuecomment-1049738451

**Comment by photohac** [comment]
If the issue was discovered what appears to be 2 years or so ago, why does
this bug persist? Or am I reading the dates wrong on that post?

**Comment by AenBleidd** [comment]
@photohac, maybe it's already fixed but just not yet released. I had no time to look at it, sorry.

**Comment by photohac** [comment]
Oh no problem.

Just putting a value in the use ___ GB is easy enough. It works for me and
other Rosetta crunchers have found other solutions.

It would be nice to have this fixed in the next release.

**Comment by AenBleidd** [comment]
Ok, so this is basically an issue with interpretation of '0' on client side and on server side.
- on client side '0' means no limits
- on server side '0' means no data, using 100GB by default
Even if this will be fixed, that doesn't mean that this will be automatically resolved for all projects because they still could use older version for quite a long time.
@davidpanderson, what do you think, show this issue be fixed, and if yes - in which way?

**Comment by photohac** [comment]
If you don't fix it, can it be published in some FAQ?

When you web search for this problem, short of this discussion or someone
in a project user group that knows this problem, there is no information
available.

**Comment by AenBleidd** [comment]
Should be fixed via #4923
