### ISSUE TITLE
no work with AMD GPU Radeon Pro W6600

### ISSUE THREAD

**Issue by tron03** [BOINC/boinc#4647]
**Describe the bug**

**Steps To Reproduce**
1. start boinc >>> GPU Radeon Pro W6600 not recognized
2. 

**Expected behavior**
No Work Unit for that GPU

**Screenshots**

**System Information**
 - OS: Windows 10
 - BOINC Version: most recent

**Additional context**

**Comment by AenBleidd** [comment]
@tron03, are you sure you didn't install BOINC as a service? You can check it next way:
1. Open Windows Task Manager (Ctrl+Shift+Esc)
2. Go to 'Services' tab
3. Search for BOINC.

If you found BOINC among the services, you need to uninstall BOINC and reinstall it but keep checkbox 'Service Install' unchecked:
![image](https://user-images.githubusercontent.com/3234209/156650159-867b5aea-9018-4d39-a7c6-a3faf0a6723b.png)

**Comment by AenBleidd** [comment]
Potentially a misconfiguration on user's device. Closing this since there was no response last 6 months.
