### ISSUE TITLE
Provide up to date premade vboxwrapper executables

### ISSUE THREAD

**Issue by computezrmle** [BOINC/boinc#4649]
The BOINC manual page mentions a couple of premade vboxwrapper executables here:
https://boinc.berkeley.edu/trac/wiki/VboxApps#Premadevboxwrapperexecutables

Who can/will compile fresh versions from the source code at:
https://github.com/BOINC/boinc/tree/master/samples/vboxwrapper

and copy them to the download server:
https://boinc.berkeley.edu/dl/

The executables should be compiled with "--enable-optimize" respectively "-O3 -ffast-math".

**Comment by AenBleidd** [comment]
Released
