### ISSUE TITLE
When detaching a Project, BOINC doesn't send cancellation information to the server

### ISSUE THREAD

**Issue by hucker75** [BOINC/boinc#4657]
If I detach a project, Boinc doesn't tell the project anything, I see from the server there are still tasks "in progress".

[https://boinc.bakerlab.org/rosetta/results.php?hostid=6181958](url) shows two tasks in progress, but I detached that machine.

**Comment by RichardHaselgrove** [comment]
The BOINC code has to handle the case where a project server has been switched off or completely disconnected from the internet - without interfering with ongoing communications with other, active, servers.

That needn't preclude a detaching client from attempting to report its departure and clean up behind itself - with a suitable timeout on the attempt. But at the moment it does.

**Comment by hucker75** [comment]
Agreed.  It was just a suggestion to be included if easy to implement.  It would let the server hand those out to someone else immediately.

**Comment by AenBleidd** [comment]
While the idea is interesting, on practice there is no reason reason to implement a complex mechanism for this purpose, since on the majority of project unreported tasks will be expired and resent within several days.
