### ISSUE TITLE
CPU scheduling with Intel Performance (P)-cores and Efficiency (E)-cores incorrect

### ISSUE THREAD

**Issue by Toby-Broom** [BOINC/boinc#4663]
**Describe the bug**
Windows detects BOINC as background task and schedules only to Ecores

**Steps To Reproduce**
1. Launch Boinc connected to LHC @ home but only running sixtrack (I guess it would be same for rosetta etc)
2. Ensure no other programs are running and boinc is in tray on windows
3. remotely monitor CPU load should be about 30-40% on 12900 with 8 P and 8 E cores
4. launch task manager, CPU load is now 100 %

**Expected behavior**
Work scheduled to all cores

**Screenshots**

**System Information**
 - OS: Windows11
 - BOINC Version: 7.16.20

**Additional context**

**Comment by AenBleidd** [comment]
Thank you for the report.
Could you please change Windows setting to optimize background tasks instead of GUI applications?

https://www.tenforums.com/tutorials/89429-adjust-processor-resources-best-performance-windows-10-a.html

**Comment by Toby-Broom** [comment]
Yes seems to fix it, however I'm not sure this is obvious for beginner BOINC users, I leave it the the product owner to prioritize.

**Comment by AenBleidd** [comment]
@Toby-Broom, yes, let's keep it open for a while, but to determine headless Windows machine might be not an easy task

> however I'm not sure this is obvious for beginner BOINC users

Not sure any beginner BOINC user runs headless Windows server :)

**Comment by Toby-Broom** [comment]
Fair enough

**Comment by OrihuelaConde** [comment]
I would change the title to "Incorrect CPU scheduling with 12th Gen Intel" because it is affected on every system, not only "headless computers".
Windows is assigning  BOINC's task to E-Cores instead of P-Cores, even prioritising background services.

![image](https://user-images.githubusercontent.com/12591371/164758555-1de3d01b-b6a0-4614-b24c-113a1f107dc9.png)
![image](https://user-images.githubusercontent.com/12591371/164758658-26a44cbe-4e8d-469e-88f2-af94a5315dc0.png)

Intel i7 12700F

**Comment by Toby-Broom** [comment]
It fixed it for me changing the settings, I just put headless as for me it seemed to work fine when I was logged in

**Comment by Toby-Broom** [comment]
This seems to have come back, I had set windows to favour background tasks but it does not work anymore.  Only Opening BOINC will make it go at full speed.  I now have 13th Gen

**Comment by Toby-Broom** [comment]
Edition	Windows 11 Pro
Version	23H2
Installed on	‎6 ‎Nov ‎2022
OS build	22631.3155
Experience	Windows Feature Experience Pack 1000.22684.1000.0

I make a bug to Microsoft referencing this, I'm not sure the issue is with BOINC, windows/CPU does not recognise that BOINC needs all the CPU

**Comment by AenBleidd** [comment]
We're not planning currently to add any CPU pinning or whatever, and we rely on the OS to schedule processes correctly on available CPU cores.
Closing this without any action for now.

**Comment by Toby-Broom** [comment]
You can feedback to MS here [https://aka.ms/AAqge2i](url)

**Comment by AenBleidd** [comment]
![image](https://github.com/BOINC/boinc/assets/3234209/eec30fc0-6c38-432b-84a6-38ca03902b72)

**Comment by Toby-Broom** [comment]
Strange the button to generate the link is called 'share'

![image](https://github.com/BOINC/boinc/assets/27242647/cb420544-bb91-42fa-aef9-31052064df22)

**Comment by OrihuelaConde** [comment]
> ![image](https://private-user-images.githubusercontent.com/3234209/330954756-eec30fc0-6c38-432b-84a6-38ca03902b72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NjM2NTUsIm5iZiI6MTcxNTg2MzM1NSwicGF0aCI6Ii8zMjM0MjA5LzMzMDk1NDc1Ni1lZWMzMGZjMC02YzM4LTQzMmItODRhNi0zOGNhMDM5MDJiNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMTI0MjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE0ZGZmNDdiN2M5MDM0ZGZjY2ZhYmRjNTVmZWM5NWViNGU5NWZmNDEwYjUwN2NmY2JiNTJmOGJjNDc5ZmFhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4I1oXlcze3Vviq-v0jfrVcHihiNHe_6PSF2-pQsrT0o)

Same issue.

**Comment by Toby-Broom** [comment]
Sorry, I assume for Microsoft Share does not really mean share.
