### ISSUE TITLE
Move ComputerMRU to a user managed config file.

### ISSUE THREAD

**Issue by towstone** [BOINC/boinc#4682]
**Describe the problem**
ComputerMRU is located in .BOINC Manger that changes constantly

**Describe the solution you'd like**
Allow users to manage the ComputerMRU list.

We manage BOINC Clients across remote locations using multiple BOINC Manger instances. The ComputerMRU does not store all our clients so we have to enter several manually after every reboot. We are not looking for account management.

**Comment by davidpanderson** [comment]
I don't understand the problem.  Please be more specific.

**Comment by towstone** [comment]
The challenge is when from BOINC Manager a user selects File - New BOINC Manager window...
A New BOINC Manager window comes up with a new "BOINC Manager - Select Computer" popup window and there is a Host name: dialog with a dropdown list. This list appears to come from the ComputerMRU list in the constantly changing .BOINC Manger gui state file. We want that list to be managed by users and not a static length list from a file the app(s) uses to store state.

**Comment by AenBleidd** [comment]
@towstone, if the list is constantly changing, maybe for you will be easier to run BOINC Manager from command line passing necessary URL as a parameter?

Regarding this list, I can say for linux, I need to check this, but in case of Windows this list is saved in Windows registry, so it can be easily managed/changed by any user wit admin permissions

**Comment by RichardHaselgrove** [comment]
I am familiar with both these storage mechanisms, and @towstone is right: the linux file is a single text file, more akin to the old .ini file structure from Windows 3 days. Most of it is concerned with persistent visual effects for the Manager - column widths and order, for example - but [ComputerMRU] is in there.

The Windows registry is known to be vulnerable, and the standard advice is to meddle with it as rarely as possible - and even then, only under caution. Having said that, there appears to be a bug in BOINC's handling of the MRU entries: one of my machines is listed 7 times, in positions 7 to 13 inclusive. Duplicates appear at the end of the list, slowly over time.

**Comment by towstone** [comment]
The goal with this request was to improve the tool, we already have a work around. Might be time for me to explore some code, who knows might be a fun challenge.

**Comment by AenBleidd** [comment]
Not sure it worths to move Manager settings from Windows registry to file.
Closing this for now as 'wontfix'
