### ISSUE TITLE
[Android][vcpkg] Remove vcpkg pinning

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4696]
Currently there is a major issue with Android and OpenSSL 3.0.2:
- Android vcpkg build is failed because of clang issue (https://github.com/openssl/openssl/issues/18059). It would be possible to workaround this if https://github.com/openssl/openssl/pull/18056 is merged but still using custom port only.

When https://github.com/microsoft/vcpkg/pull/24004 and https://github.com/openssl/openssl/pull/18056 are merged, new port should be created to properly fix that in vcpkg upstream

**Comment by CharlieFenton** [comment]
FWIW, OpenSSL 3.0.2 builds correctly on Apple clang version 13.1.6 under Xcode 13.3 on Macintosh

**Comment by AenBleidd** [comment]
> FWIW, OpenSSL 3.0.2 builds correctly on Apple clang version 13.1.6 under Xcode 13.3 on Macintosh

Nice! One problem less. Thank you for testing this.

This might be still interesting for you: https://github.com/openssl/openssl/issues/18055
