### ISSUE TITLE
[Windows] Provide an installer for arm64

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4697]

**Comment by martinsuchan** [comment]
Hi, I just bought my new laptop - it's a Microsoft Copilot+ PC Lenovo Yoga Slim 7x with the new **ARM64 Snapdragon X Elite CPU and Windows 11 ARM**.
I'm wondering what are the plans for releasing stable BOINC client natively compiled and running on Windows 11 ARM64? Right now I run the x64 client 8.0.2 in emulated mode. Thanks

**Comment by AenBleidd** [comment]
Hello, the current plan is to have the new installer ready for testing before the end of this year.
So stay tuned.

**Comment by martinsuchan** [comment]
Is there a ticket for adding the ARM64 installer to the downloads page? It's still nowhere to be found, thanks.
https://boinc.berkeley.edu/download_all.php

**Comment by AenBleidd** [comment]
@martinsuchan, it's not released yet, so obviously it's not present on the download page.
Once it will be ready - we will make an alpha release, make an announcement, and it will appear on the download page.
Stay tuned ;)
If in the meanwhile you are interested in testing the dev build - please let me know and I'll send you one.
