### ISSUE TITLE
Ramanujan machine boinc project doesn't have anything under Supported systems in attach project wizard

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#4717]
**Describe the bug**
Ramanujan machine boinc project doesn't have anything under Supported systems in attach project wizard
**Steps To Reproduce**
1. 
2. 

**Expected behavior**

**Screenshots**
![Снимок экрана (171)](https://user-images.githubusercontent.com/8822292/163716494-8c5e5e78-706a-4de1-b699-a2ed256f13bb.png)

**System Information**
 - OS: Microsoft Windows [Version 10.0.22000.613]
 - BOINC Version: 7.16.20 64

**Additional context**

**Comment by AenBleidd** [comment]
@davidpanderson, platforms tags are missing in 'all_projects_list.xml' for `Ramanujan Machine' project.
Could you please fix it?

**Comment by davidpanderson** [comment]
Fixed.
