### ISSUE TITLE
Definition of stage_file function in C++

### ISSUE THREAD

**Issue by jellythefish** [BOINC/boinc#4733]
There is a binary executable for staging input files and it is written in php.
https://github.com/BOINC/boinc/blob/master/tools/stage_file

In projects we usually use this tool like `bin/stage_file`

But for my needs i was searching for such API in C++ and was able to find only declaration in `bachend_lib.h`:
https://github.com/BOINC/boinc/blob/2f166edb7350e57afaff565740e03a1bde98fae2/tools/backend_lib.h#L118
It has got no definition in `bachend_lib.cpp` or somewhere else across the repository.

Is this a work in progress or may it be a feature request?

**Comment by AenBleidd** [comment]
@davidpanderson, this function declaration was added in https://github.com/BOINC/boinc/commit/c529c3c50d24e003095442e1070ae7a41d0ee59c
but I don't see it was ever implemented.
Is this a leftover that should be deleted?

**Comment by davidpanderson** [comment]
Looks like I intended to implement stage_file() in C++ but didn't get around to it.
At this point it's probably easiest to use system() to run the PHP script from C++.

**Comment by jellythefish** [comment]
I may try to make one based on PHP implementation.
Is it ok and will you have an opportunity to review?

**Comment by davidpanderson** [comment]
By all means!  Let me know if you need any help or advice.

**Comment by jellythefish** [comment]
@davidpanderson, @AenBleidd  
Hi there! I made some stuff over there as we discussed https://github.com/BOINC/boinc/pull/4816
There are some things i am confused about.
I tried to make both the tool - executable binary and the libarary function.
I am not sure whether the signature of the lib func is ok with the arguments passed to the tool.
Also, not sure wheter i return error codes and print errors to stderr correctly. There are also some concerns about general code style and its C/C++ mixing.
Will be very thankful if you review and make some comments and issues.

**Comment by AenBleidd** [comment]
Hello @jellythefish, thank you for your PR.
I'll take a look at the code.

**Comment by davidpanderson** [comment]
Unless efficiency is an issue, I'd recommend invoking the PHP script from C++ using system().  In any case, don't change the name of stage_file since that will break some projects.

**Comment by jellythefish** [comment]
> Unless efficiency is an issue, I'd recommend invoking the PHP script from C++ using system(). In any case, don't change the name of stage_file since that will break some projects.
Ok, i'll change the name of stage_file back to .php version, actually agree with you. Just thought it would be kind of uniform to use my c++ lib functions and tool as it is usually done in BOINC. I tried to make totally same function behavior as in .php be, but just in case will leave this script default in usage.
