### ISSUE TITLE
Utility that change all the link of vcpkg for testing

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#4743]
@AenBleidd
Please add another utility that change all the link of vcpkg for testing. 
`https://github.com/microsoft/vcpkg` -> other link for testing from command line

**Comment by talregev** [comment]
Should we have one file that every one will read this link, and we can change only on this file?

**Comment by AenBleidd** [comment]
I don't think this will be a simple change. If you want to do that - go ahead.

**Comment by talregev** [comment]
For all the linux script is will be simple change. I already did similar thing in android script when you ask my to unify code in that was related to 2 script. 
I will do it for all the linux script, then the utility will change only in 2 places: for windows and this script.

**Comment by talregev** [comment]
Will you do that Utility?

**Comment by AenBleidd** [comment]
> Will you do that Utility? 

Yes, I will.

**Comment by AenBleidd** [comment]
Not planned anymore.
