### ISSUE TITLE
Task action: "Suspend after next checkpoint"

### ISSUE THREAD

**Issue by pataquets** [BOINC/boinc#4748]
**Describe the problem**
On client shutdown or task suspend, non-checkpointed work is lost. So far, I've found uncheckpointed work for 1h or even 2h worth, which is quite a waste, if stopped and lost.
When an orderly shutdown is possible (eg. reviewing tasks before shutdown/restart), you can wait tasks to checkpoint before suspending/quitting, but it's tedious and inconvenient.
It can be helpful when shutting down, but also for switching tasks/projects.

**Describe the solution you'd like**
I would like to have a 'Suspend after next checkpoint' task action. Thus, I could send it to all running tasks to guarantee that no work is lost.

**Additional context**
Assumptions:
* Tasks notify client on checkpoint, which can react accordingly.
* Some tasks do not checkpoint, which is fine. It's up to you to know it if you intend to do "whatever at checkpoint".

This feature would later enable also a 'checkpointed shutdown' for the whole client. You can manually trigger it as a command when winding down before shutdown, set it as an opt-in behaviour on `SIGTERM` or do it on another signal. Lots of people might find it helpful to avoid wasted work (time and electricity).

**Comment by AenBleidd** [comment]
BOINC client doesn't know when application will do checkpoint next time (and if it will do it ever), but with such a functionality we will have the situation that it will take significant time for BOINC client to being stopped, thus making worse users' experience.
I'm closing this issue without any action.

**Comment by pataquets** [comment]
Hi @AenBleidd. Thanks for the feedback.

However, I'd like to point out that the "after next checkpoint" clause, implicitly means that the user has to know what this means or, at the very least, find out better what it means. I mean, if it were me, I'd find out beforehand what "after next checkpoint" translates, just to be safe.
As it's not replacing normal shutdown, but adding a conditional one, I think the user can not expect anything near "shutdown soon", but "after checkpoint". Another issue would be if the user knows it or not when selecting. You have a valid point about ensuring the user knows, which could be addressed by making it more visible in the GUI, perhaps.
If I, as a user, select to "shutdown after checkpoint", it's reasonable to expect me to know beforehand or at least have found previously what "after checkpoint" means. If I'm selecting the option without being aware of its implications, if I find the client is not shutting down, it's entirely my fault, IMO.
My point is "if user chooses 'after checkpoint' he/she has to be aware what it means".

As stated in my OP, I understand "after checkpoint" might translate to "never" for projects not doing checkpointing at all. But as stated before, I expect this to be kind of an "advanced user" feature.

Losing/wasting compute time due to not being able to better plan shutdown would be a pity. The intention is to provide a tool to optimize compute for users, as an advanced/power user option.

I'd like to ask you to reconsider the feature request. I'll be happy to further discuss any other concern about this.

**Comment by AenBleidd** [comment]
The main problem here is that you can't estimate when every particular application will do the checkpoint, and thus user will never know how long they should wait until BOINC shutdown.
And this is in general very bad experience.
We can add timeout, but this will not help: yes, we help the setting to checkpoint every XXX minutes, but this is a recommendation to the application, and we can't force application to checkpoint, since this is not possible.
So, there will be even more confusion from the users, that might set timeout equal to checkpoint time, and then they will see the data loss and slow application close.
Double frustration, I'd say.
That is why it's better not implement this functionality and keep the current behavior as-is.
