### ISSUE TITLE
Master failing on Mke

### ISSUE THREAD

**Issue by Dave-catcher** [BOINC/boinc#4781]
./_autosetup and ./configure --disable-server run fine. Make fails on Master downloaded today with

/usr/bin/ld: boincmgr-taskbarex.o: undefined reference to symbol 'gtk_status_icon_set_visible'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-3.so.0: error adding symbols: DSO missing from command line

Machine is ryzen7 32GB RAM xUbuntu22.04 Tested on host machine and also on clean install of OS in VM. 7.20.0 client release compiles and installs without issue both on host machine and on VM.

**Comment by talregev** [comment]
You install also the manager:
First make sure you install wxwidgets on your computer.

tbd:
```
sudo apt install ....
```

Then you need to add wx config path parameter to ./configure

`--with-wx-prefix=`

You can take hints from ci.

**Comment by AenBleidd** [comment]
@Dave-catcher, thank you for the report.
Current master is under development and not it's not recommended to use it in most cases. We recently created a 7.20.0 tag that is going to be a new Release candidate.
Please use it.
And we will take a look at your report and investigate why current building way is not working as expected.

**Comment by AenBleidd** [comment]
@Dave-catcher, thank you for the report.
Current master is under development and not it's not recommended to use it in most cases. We recently created a 7.20.0 tag that is going to be a new Release candidate.
Please use it.
And we will take a look at your report and investigate why current building way does not work as expected.

**Comment by talregev** [comment]
@Dave-catcher Please also make a list of all the packages you install on the clean install.

**Comment by Dave-catcher** [comment]
Packages installed on top of default installation
autoconf 2.71-2
build-essential 12.9ubuntu3
curl 7.81-0ubuntu1.2
dash 0.5.11+git20210903+0
diffutils 1:3.8.0ubuntu2
libc6 2.35-ubuntu3
libcurl4-openssl-dev
libdebconfclient0 0.261ununtu1
libgtk-3-dev
libnotify-dev 0.7.9-3ubuntu5
libssl-dev 3.0.2-0ubuntu1.2
libtool 2.4.6-15build2
libwebkit2gtk-4.0-dev 2.36.3-0ubuntu0.22.04
libwxgtk-webview3.0-gtk3-0v5
libwxgtk3.0-gtk3-dev
m4 1.4.18-5ubuntu2
make 4.3-4.1build1
mokutil 0.4.0-1ubuntu2
ncurses-base 6.3-2
ncurses-bin 6.3-2
openssl3.0.2-0ubuntu1.2
os-prober 1.79ubuntu2
pkg-config 0.29.2-1ubuntu3
python3-wxgtk-media4.0 4.0.7+dfsg-13build1
shim-signed 1.51+15.4-0ubuntu9wx-common 3.0.5.1+dfsg-4
wx3.0-headers 3.0.5.1+dfsg-4

Fairly certain that is all the relevant ones. Sorry if I have put in some irrelevant ones.

**Comment by talregev** [comment]
> Packages installed on top of default installation autoconf 2.71-2 build-essential 12.9ubuntu3 curl 7.81-0ubuntu1.2 dash 0.5.11+git20210903+0 diffutils 1:3.8.0ubuntu2 libc6 2.35-ubuntu3 libcurl4-openssl-dev libdebconfclient0 0.261ununtu1 libgtk-3-dev libnotify-dev 0.7.9-3ubuntu5 libssl-dev 3.0.2-0ubuntu1.2 libtool 2.4.6-15build2 libwebkit2gtk-4.0-dev 2.36.3-0ubuntu0.22.04 libwxgtk-webview3.0-gtk3-0v5 libwxgtk3.0-gtk3-dev m4 1.4.18-5ubuntu2 make 4.3-4.1build1 mokutil 0.4.0-1ubuntu2 ncurses-base 6.3-2 ncurses-bin 6.3-2 openssl3.0.2-0ubuntu1.2 os-prober 1.79ubuntu2 pkg-config 0.29.2-1ubuntu3 python3-wxgtk-media4.0 4.0.7+dfsg-13build1 shim-signed 1.51+15.4-0ubuntu9wx-common 3.0.5.1+dfsg-4 wx3.0-headers 3.0.5.1+dfsg-4
> 
> Fairly certain that is all the relevant ones. Sorry if I have put in some irrelevant ones.
> 
> As I said, the release candidate7.20.0 compiled without issue.

We want to understand why. because the change made on master doesn't related to your error.
Did you try also my suggestion to compile it with additional parameter to configure?

**Comment by talregev** [comment]
Also please write me:
wx-config --libs

**Comment by talregev** [comment]
> libwxgtk-webview3.0-gtk3-0v5

This should replace by this one as I suggested:
`libwxgtk-webview3.0-gtk3-dev`
The error related to this one.

**Comment by talregev** [comment]
I think in 7.20 you compile wxwidgets without WebView.
And in the master it compile wxwidgets with WebView.
But missing lib dependency.

**Comment by Dave-catcher** [comment]
> wx-config --libs



> Also please write me the results for this command: `$ wx-config --libs`

-L/usr/lib/x86_64-Linux-gnu -pthread  -lwx_gtk3u_xrc-3.0 -lwxgtk3u_webview-3.0 -lwx_gtk3u_html-3.0 -lwx_gtk3u_qa-3.0 -lwx_gtk3u_adv-3.0 -lwx_gtk3u_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0

**Comment by Dave-catcher** [comment]
> libw

Just checked, both are installed.

**Comment by Dave-catcher** [comment]
Don't know what I have changed.

> > libwxgtk-webview3.0-gtk3-0v5
> 
> This should replace by this one as I suggested: `libwxgtk-webview3.0-gtk3-dev` The error related to this one.
ran apt install libwxgtk-webview3.0-gtk3-dev and it said newest version already installed. After trying again starting with a clean folder from unzipping master, it has worked so this can be closed.
