### ISSUE TITLE
ARM64 Linux Support for Wrapper App

### ISSUE THREAD

**Issue by ckrause** [BOINC/boinc#4782]
**Describe the problem**
The wrapper app is not support on ARM 64-bit GNU/Linux. We have user requests to support ARM64 for our Boinc project (LODA). 

**Describe the solution you'd like**
Add ARM64 Linux version of the wrapper app.

**Comment by cwallbaum** [comment]
About a year ago I successfully compiled the wrapper for Debian 9/10 and Ubuntu 18.04/20.04, each for armhf and arm64, and they ran fine as far as I remember. I cannot say anything about the current development branch, but could you be more specific with "not supported"?

**Comment by AenBleidd** [comment]
@cwallbaum 
> but could you be more specific with "not supported"

There is no binary available for download from our website

**Comment by ckrause** [comment]
Can you please upload the binary of the wrapper app to https://boinc.berkeley.edu/dl/ ?

**Comment by AenBleidd** [comment]
Once it will be released - it will be uploaded there. Please wait a bit.
