### ISSUE TITLE
Per project limitations

### ISSUE THREAD

**Issue by bonze82** [BOINC/boinc#4790]
Some workunits such as climate prediction are huge, is it possible to make a per project limits such as lhc has server side.

Something such as this but on the client side not the server side: 
![image](https://user-images.githubusercontent.com/8306092/173745705-9e860b27-28c5-42ec-a6ee-e369419540f7.png)

The max number of jobs would be a huge benefit. Btw I have lhc limited for troubleshooting a vbox issue.

**Comment by AenBleidd** [comment]
While this is in general a good idea, on practice it's not applicable to the majority of projects.
We are not gonna implement this, and let projects decide (and implement if needed) by their own
