### ISSUE TITLE
[Manager] Memory access error on closedown

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#4793]
**Describe the bug**
I've seen this popup a couple of times since installing the test version of v7.20.0

![image](https://user-images.githubusercontent.com/14886436/174061252-11e86612-5a2e-4f00-b0dc-9d6556c802c1.png)

**Steps To Reproduce**
I think it occurs when the Manager (running mimised) is force-closed by the operating system in preparation for a reboot. Further testing required.

**System Information**
 - OS: Windows 7/64 professional
 - BOINC Version: 7.20.0

**Comment by Vulpine05** [comment]
@RichardHaselgrove , when you have a moment, could you provide more detail on your steps?  I tried to reproduce this in Windows 10 with the pre-release build, and I couldn't replicate the error.  All I did was minimize the Manager window (that is, it was in the task bar, not just the system tray), and the restarted manually.

**Comment by Crystal-Pellet** [comment]
Reported bug is occurring and reproducable under 3 of the 4 possibilities when system is shutdown.
1. Boinc Manager application window open on the screen
2. Boinc Manager iconized on the status bar
3. Boinc Manager iconized in the system tray

Only when the Boinc Manager is minimized to the status bar the application error doesn't appear.

![Boincmgr](https://user-images.githubusercontent.com/107885995/174669707-c8470797-0ac6-456c-a269-3e8f417e9b62.png)

**Comment by AenBleidd** [comment]
Is the error the same for the current master build?
@RichardHaselgrove, @Crystal-Pellet, could you please use this executable and check again https://github.com/BOINC/boinc/suites/7006198503/artifacts/274916661 ?
Thank you both in advance

**Comment by Crystal-Pellet** [comment]
Your pre-release 7.21.0 creates the same error under same conditions.
![Boincmgr21](https://user-images.githubusercontent.com/107885995/174724625-c7c33fae-c57b-476d-b504-91489f7537df.png)

**Comment by AenBleidd** [comment]
@Crystal-Pellet, thanks for testing this.

**Comment by AenBleidd** [comment]
@Crystal-Pellet, unfortunately I'm unable to reproduce this locally so I require your help here.
May I ask you to activate postmortem debugger (https://www.windowscentral.com/how-use-procdump-create-dump-files-windows-10), try to reproduce this and send me a dump file once succeed?
Also, please do this with the this executable: https://github.com/BOINC/boinc/suites/7006198503/artifacts/274916661

Thank you in advance

**Comment by Crystal-Pellet** [comment]
I first looked if the boincmgr.exe was still present when I cancel the shutdown with the error pop-up open.
Else other actions would be worthless. Luckily it was.
Attached you would find the zip with a mini-dump and the extended dump from the process state with the pop-up error open.
Unfortunately 69MB is not supported to upload here. So you'll find now only the mini-dump
[boincmgr.exe_220622_161554.zip](https://github.com/BOINC/boinc/files/8958583/boincmgr.exe_220622_161554.zip)
.

**Comment by Crystal-Pellet** [comment]
@AenBleidd: Write me a private message with your e-mail into my inbox of Boinc Berkeley Message board.
You seem to have 4 User ID's overthere. My User ID 33650.
I'll send the zip with the mini dump and full dump to that e-mail address.
Discord told me that the invite could not be accepted :( but not why not.

**Comment by AenBleidd** [comment]
@Crystal-Pellet, message is sent.

**Comment by bonze82** [comment]
@RichardHaselgrove: Different memory voltages shouldn't matter, memory such as pc3l runs at pc3 voltages without an issue. Can you please elaborate. and system specs would be nice as it might be a system board issue and not a windows issue. I'm running linux and have pc3l and pc3 in the same system and running stable for 6+ months. I have seen systems with too much ram, did that to my current network server, and it was unstable also different speed ram sticks can cause instability.

**Comment by AenBleidd** [comment]
@Crystal-Pellet, could you please test this executable https://github.com/BOINC/boinc/suites/7057774204/artifacts/278233453 ?
In case of a crash please send me memory dump again.
Thank you for your testing.

**Comment by Crystal-Pellet** [comment]
@AenBleidd: Crash, thus dump to: https://drive.google.com/file/d/1fKyJuBtdlhe9iz6ffLUJz9eVK5rFv9uB/view?usp=sharing

**Comment by AenBleidd** [comment]
@Crystal-Pellet, may I ask you to do one more test?
https://github.com/BOINC/boinc/suites/7069056724/artifacts/278926554
I believe I understand what's going on but still have no idea why this happens now and completely not reproducible on my side.
Thanks a lot for your help!

**Comment by Crystal-Pellet** [comment]
@AenBleidd: It's hard to find the problem, if you can't reproduce it yourself, but it seems you hit the nail on the head in the dark.
With your last version, I can't reproduce it either, so it seems you solved the problem without knowing the cause.
This time no dump file from me.
