### ISSUE TITLE
[wasm] Generate device or browser unique id

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4798]
When BOINC client runs on Desktop, it generates a unique device id even if Data folder was removed between runs. This helps to avoid device duplicates on user profile page.
This behavior is achieved by reading device MAC address.

For WASM hardware identifiers could not be read.

There should be implemented some functionality to generate unique id for device (or at least browser) from JS code.

Ref: https://github.com/fingerprintjs/fingerprintjs

**Comment by talregev** [comment]
Also here:
https://stackoverflow.com/questions/49692073/how-can-i-get-a-unique-device-id-in-javascript
