### ISSUE TITLE
an error happened if I close the PC without exiting BOINC

### ISSUE THREAD

**Issue by LezheGao** [BOINC/boinc#4807]
**Describe the bug**
If I close the PC without exiting BOINC，an error happened（the screenshot）.
**Steps To Reproduce**
1. Close the PC without exiting BOINC

**Expected behavior**

**Screenshots**
![1 (2)](https://user-images.githubusercontent.com/76685272/175185252-1c9532c8-7d0a-47db-874d-d688c743b5c9.jpg)

**System Information**
 - OS: windows11
 - BOINC Version:7.20.0 

**Additional context**

**Comment by AenBleidd** [comment]
Closed as a duplicate of #4793
