### ISSUE TITLE
[Manager][linux] Search for skins to display on Simple View

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4809]
Currently BOINC Simple View on linux has no default skin and looks not so nice as on other OSs.
It would be nice to look for default skin in the next locations:
- /usr/share/boinc-manager/skins/
- /usr/local/share/boinc-manager/skins/
- ./skins

**Comment by RichardHaselgrove** [comment]
This needs co-ordination with the Linux distribution maintainers. At the moment, my distro (@LocutusOfBorg's PPA, based on Debian) doesn't even deploy the skins folder - so looking for it won't make any difference. We should agree on a location for the default and other skins.

**Comment by AenBleidd** [comment]
Exactly. The email is already sent, and this ticket just for reference and possibly better place of discussion than private email.
