### ISSUE TITLE
Request for News Editor

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#481]
**Reported by Ageless on 16 Oct 37891061 19:06 UTC**
At this moment when projects want to add to their news, they have to edit project_news.inc which can be awkward at times. It would be nice if there was a news editor included, which would store whatever news was put in directly in project_news.inc 

Perhaps that Newsletters could be written from this editor as well. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/502

**Comment by romw** [comment]
**Commented by przybd on 5 Jul 38233534 01:46 UTC**
This really needs to be looked at. It's quite an inconvience to have to edit the inc file.

**Comment by ChristianBeer** [comment]
This was implemented in the meantime and News are now part of the forums.
