### ISSUE TITLE
Keep track of project's files

### ISSUE THREAD

**Issue by CyberTailor** [BOINC/boinc#4815]
**Describe the problem**
I use BOINC anonymous platform, and some files in the project directory are handled by the package manager. When I detach from a project, these files are gone.

**Describe the solution you'd like**
Keep track of all project's files downloaded by the BOINC client. When user detaches from the project, client should delete only these files, not the entire directory.

**Comment by AenBleidd** [comment]
While in general idea is good, however there is no easy way to implement it since BOINC client doesn't have full list of files that might be in the project directory, that is why it's safer to remove the project directory completely during detach.
