### ISSUE TITLE
[Manager] When restoring column visibility, column is restored at end of tab.

### ISSUE THREAD

**Issue by Vulpine05** [BOINC/boinc#4824]
**Describe the bug**
In advanced view of BOINC Manager, the user has the ability to hide columns.  If a column is hidden, changes are accepted, then made visible again, that column is moved to be the last column, regardless of where it was prior to hiding it.

**Steps To Reproduce**
1. Open BOINC Manager, Advanced View.
2. "Options"->"Select Columns..."
3. Unselect any column that is not the last for its tab (Project is a great example), click Save.
4. Open "Select Columns..." again.  The column that is hidden has now moved in this window to the last location.
5. Selecting this column, then clicking Save will bring the column back, but now it is the last column.

**Expected behavior**
It would be ideal if the column would be restored to its original place.

**Screenshots**
Item 3 above, before hitting Save:
![image](https://user-images.githubusercontent.com/58096400/177019373-7b7c841e-3b6f-4424-82f1-2cfd5a64ae73.png)

Step 4 above:
![image](https://user-images.githubusercontent.com/58096400/177019383-13c967bf-a9ce-4da0-b05c-fc80e7ee7f72.png)

**System Information**
 - OS: Windows 10
 - BOINC Version: 7.20.0

**Additional context**
Clicking on "defaults" helps reset where the column was before, but now any other changes the user may have made are lost.

**Comment by CharlieFenton** [comment]
In case you're not already aware, you can rearrange the columns by dragging them left or right, though this only works on MS Windows. So you can easily move the restored column where you want it.

Restoring a previously deleted column to its earlier position can get complex. Consider this scenario: You delete the 4th of 7 columns, then rearrange all the remaining 6 columns by dragging them left or right. If you now add the deleted column, what is its correct "previous" position? Is it to the right of the column that had been in position 3 before rearranging? To the left of the column that had originally been in position 5? Is it in position 4? There is no absolute answer.
