### ISSUE TITLE
Problem with BOINC Notice being issued - World Community Grid change of URL

### ISSUE THREAD

**Issue by raisinc** [BOINC/boinc#4833]
![BOINC message re World Community Grid](https://user-images.githubusercontent.com/15245461/177901872-c84a2527-b91b-4584-8db2-86babbcc2bc7.jpg)

This message keeps appearing in the BOINC Manager's Notices.
After I remove the World Community Grid project and then add it using the changed URL,  BOINC loads it but changes the URL back to the one which **IS** being used by World Community Grid (apparently) namely:
http://www.worldcommunitygrid.org/

Is there a problem?

**Comment by RichardHaselgrove** [comment]
Yes, there is a problem, but it's a project problem, not a BOINC problem. New owners took over the WCG, and are facing a very steep learning curve. Mistakes are being made, but hopefully will - eventually - be ironed out.
