### ISSUE TITLE
[Bug report][Manager] When switch skins, it also change application name

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#4848]
When switch skins, it also change application name:
![image](https://user-images.githubusercontent.com/7043539/179350103-0da1b797-925e-492a-a221-063f2a19c3d7.png)

**Comment by AenBleidd** [comment]
This is a feature, not a bug

**Comment by talregev** [comment]
> This is a feature, not a bug

Should I close this issue? :P

**Comment by AenBleidd** [comment]
Yes, please.
Just FYI: https://github.com/BOINC/boinc/blob/b908e8f7864fa9969198288e7d36ed08b212ffa6/clientgui/skins/World%20Community%20Grid/skin.xml#L30
