### ISSUE TITLE
I can't see some of my project.

### ISSUE THREAD

**Issue by LezheGao** [BOINC/boinc#4860]
**Describe the bug**
In https://boinc.berkeley.edu/cert_dev.php,I can't see some of my project.

**Steps To Reproduce**
1. goto https://boinc.berkeley.edu/cert_dev.php
2. input your CPID and Name
3. Press the button

**Screenshots**
![image](https://user-images.githubusercontent.com/76685272/182007311-3742f79c-51f9-4dd6-bdbc-da79f1a3e251.png)
![image](https://user-images.githubusercontent.com/76685272/182007315-72f53271-ffc2-4c7f-a16c-c75448001ae4.png)
**System Information**
 - OS: Windows11
 - BOINC Version: 20.0.2
***P.S.***
I could not see iThena sence I have a point(yesterday)

**Comment by LezheGao** [comment]
I have found them when their points>100,can you fix that??

**Comment by davidpanderson** [comment]
I added a "min credit" field to the form.

**Comment by LezheGao** [comment]
> 我在表格中添加了一个“最低信用”字段。

OK,thanks

**Comment by LezheGao** [comment]
Wait,this problum solved.But when does this Update once？A day？？

**Comment by LezheGao** [comment]
Can you made it into 1hour or 2hours？？Thanks.

**Comment by LezheGao** [comment]
This is not myfirst problem.so I‘ll close it.......And start a new one.Expect you soulve it(I'm sorry I am so rude,but I am a chinese,I can't speek English well).

**Comment by LezheGao** [comment]
Wait，I still can‘t see my iThena:
![image](https://user-images.githubusercontent.com/76685272/182056643-c55cc870-2a8f-4eec-bf38-6dafcca883ff.png)
![image](https://user-images.githubusercontent.com/76685272/182056660-41c0c4f3-0e28-4b9a-9cf8-66fcbc53fbba.png)

**Comment by LezheGao** [comment]
Is this a problem about the "min credit"?
