### ISSUE TITLE
[Coverity] sizeof finding

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4872]
New issue found by Coverity:
https://github.com/BOINC/boinc/blob/ce3cf4dfe1c2d56c9df99cc9c62e85be0a59ec07/client/file_names.cpp#L325-L329
![image](https://user-images.githubusercontent.com/3234209/183295287-d6a551cf-2766-4e01-82e2-ad85f3273fe5.png)
![image](https://user-images.githubusercontent.com/3234209/183295338-b302ca0f-48ef-4312-ba70-8048a8ed5814.png)

@computezrmle, since this was introduced by your code, I kindly ask you to fix it.
Thank you in advance

**Comment by davidpanderson** [comment]
Let's avoid sweeping changes that don't fix any actual problems.

**Comment by AenBleidd** [comment]
@davidpanderson, sorry, my bad. That's an issue that was found after an improvement I asked @computezrmle for. I made this ticket just for easier tracking of it by myself.
