### ISSUE TITLE
Apple M1 Platform Support

### ISSUE THREAD

**Issue by ckrause** [BOINC/boinc#4890]
**Describe the problem**
Most new Macs are running on Apple M1 silicon (ARM-based). This architecture is currently not supported by BOINC:
https://github.com/BOINC/boinc/blob/master/tools/project.xml

**Describe the solution you'd like**
Support Apple M1 platform (ARM-based) including the BOINC client / manager and the wrapper app.

**Comment by CharlieFenton** [comment]
All BOINC releases since version 7.16.12 (17 November 2020) have had full M1 support. They have all been universal binaries with both native Apple Silicon and native Intel code.

**Comment by RichardHaselgrove** [comment]
The Einstein project also has native M1 science applications, but I'm not aware of any others. I can't comment on the status of the wrapper.

**Comment by AenBleidd** [comment]
Closing this as invalid since everything that should be done is already in place and tested.

**Comment by CharlieFenton** [comment]
I have uploaded a Universal binary (x86_64 and arm64) of the wrapper app to the server. You can download it [here](https://boinc.berkeley.edu/dl/wrapper_26017_universal-apple-darwin.zip).

**Comment by ckrause** [comment]
Thanks! We use consumed in LODA. The Activity Monitor show the correct kind now ("Apple").
