### ISSUE TITLE
7.20.2 : pre-release or stable production release

### ISSUE THREAD

**Issue by squid-f** [BOINC/boinc#4899]
**Describe the bug**
When building and running boinc-client and boinc-manager, "BOINC Manager (Pre-release)" appears as a headline on the boinc-manager window bar.

**Steps To Reproduce**
1. Build 7.20.2 for source, using the tarball provided
2. Start client and open manager
3. Look at the headline on the boinc-manager window bar

**Expected behavior**
Pre-release should not appear, assuming it is a stable production release

**Screenshots**
![pre-release headline](https://user-images.githubusercontent.com/11743181/185873031-ae2d158f-aeec-40ba-ba17-04d6830d20fa.png)

**System Information**
 - OS: Linux x86_64 Mageia 8
 - BOINC Version: 7.20.2

**Additional context**
n/a

**Comment by AenBleidd** [comment]
@squid-f, are you using tarball from this tag https://github.com/BOINC/boinc/releases/tag/client_release%2F7.20%2F7.20.2 ?

**Comment by squid-f** [comment]
> @squid-f, are you using tarball from this tag https://github.com/BOINC/boinc/releases/tag/client_release%2F7.20%2F7.20.2 ?

Yes, I am using https://github.com/BOINC/boinc/releases/tag/client_release%2F7.20%2F7.20.2

**Comment by RichardHaselgrove** [comment]
@LocutusOfBorg PPA also displays pre-release.

**Comment by RichardHaselgrove** [comment]
The problem is at
https://github.com/BOINC/boinc/blob/client_release/7.20/7.20.2/version.h.in#L24

**Comment by AenBleidd** [comment]
@RichardHaselgrove, you are looking at master branch. On release it should be everything fine: https://github.com/BOINC/boinc/blob/82d0a3731c743884b6e7a25d68c6558eca691635/version.h

**Comment by CharlieFenton** [comment]
The Mac release of BOINC 7.20.2 does not display _pre-release_. It was, of course, built from the _client_release/7.20/7.20.2_ tag on GitHub.

**Comment by RichardHaselgrove** [comment]
No, my code link explicitly pointed to the client_release/7.20/7.20.2 tag in the release branch.

But it pointed to a different file, version.h.in - I haven't yet checked whether/if that would influence the clientgui source tree.

**Comment by AenBleidd** [comment]
@RichardHaselgrove, sorry, my bad. I'll check it out. Thank you for doing this.

**Comment by squid-f** [comment]
Hi. Just checked version.h from the source tarball I have. Pre-release tag is commented:
```
/* Package is a pre-release (Alpha/Beta) package */
//#define BOINC_PRERELEASE 1
```

**Comment by RichardHaselgrove** [comment]
And in version.h.in?

It's usually active in development branches, but de-activated (commented out) when a branch is considered ready for release.

**Comment by squid-f** [comment]
> And in version.h.in?
> 
Bingo! It is set in version.h.in:
```
/* Package is a pre-release (Alpha/Beta) package */
#define BOINC_PRERELEASE 1
```

**Comment by AenBleidd** [comment]
I'll fix that for the next release. Thank you all for the report and investigation
