### ISSUE TITLE
When i disable leave non-gpu tasks in memory and suspend computing tasks stay in memory.

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#4903]
**Describe the bug**
When i disable leave non-gpu tasks in memory and suspend computing tasks stay in memory.
**Steps To Reproduce**
1. Run several non-gpu tasks.
2. Disable  leave non-gpu tasks in memory.
3. Suspend.
4. Open task manager.

**Expected behavior**
Suspending kills task processes if  leave non-gpu tasks in memory is disabled.
**Screenshots**

**System Information**
 - OS: Microsoft Windows [Version 10.0.22000.856]
 - BOINC Version: 7.20.2

**Additional context**

**Comment by Ageless93** [comment]
Tasks will stay in memory when they haven't checkpointed yet. Some tasks have very long times between checkpoints, others may not checkpoint at all (is this still true though?). If a task hasn't checkpointed at least once, it will stay in memory with this option disabled and BOINC still running.
