### ISSUE TITLE
Invalid Client RPC password. Try reinstalling BOINC. How to troubleshoot on Windows

### ISSUE THREAD

**Issue by Isocosmic** [BOINC/boinc#4904]
**BOINC Manager Connection Error "Invalid Client RPC password. Try reinstalling BOINC" pops up, all my projects have disappeared and BOINC Disabled **

BOINC Status: not connected to client.

_How it all started_

My projects were not running when System was idle, it said system is busy & no computations @ all, so changed preferences, still same issue persisted.

Then wanting to monitor why no computation was happening overnight, i checked on activity log, it only said system is busy & computation stopped.

i wanted to understand the problem better, so all i did was go to 'options Tab' then Activity Log Options and check box all flags "BOINC Diagnostic Log Flags".

checked box for all types of debugs and simulations listed, basically tick marked all the listed Flags in Event Log.
then clicked on Save, as soon as i hit 'Save' something refreshed and started refreshing for 10 seconds.
Then this Error popped up " Invalid Client RPC Password. Try Reinstalling BOINC "
This issue started as soon as i changed the "activity log options".

**Screenshot**

![Screenshot (2433)](https://user-images.githubusercontent.com/63298882/186573938-e20e06ff-5c35-4f73-9b17-eabc7b2790f0.png)

**System Information**
 - OS: WIndows 8.1
 - BOINC Version: 7.20.2

**Additional context**
i dont use virtual box @ all since the very beginning.

only Non-GPU task are running always.

i dont use Linux, neither do i know how to code n stuff, please suggest a troubleshoot in windows language only.

**Comment by RichardHaselgrove** [comment]
Some thoughts appropriate for this forum.

1. It's 99%+ certain that this error message is **false** - there's nothing wrong with the password, and re-installing BOINC won't improve the situation.
2. In general, this message seems to appear when the client becomes too busy to handle communications with the Manager.
3. Sometimes, that happens when the client is communicating with a project server. But in this particular case, it's likely to have occurred because the internal RPC link has been flooded by too many event log messages.

What are the implications for this development community?

1. Can we **please** change the message, or be more careful about the occasions on which it's triggered?
2. Recovery. We'll handle this case in the community, in the parallel boinc_alpha conversation. But it's tricky, especially when the cause is too many event log flags. That's in data - which is why re-installing won't work - and the data folder is hard to find in a default Windows installation. I'll look to see if an emergency 'restore event log flags to default' could be added to the Manager, for use even when the client can't be contacted.
3. Prevention. A big red warning on the top of the 'Event log options' dialog?

**Comment by Isocosmic** [comment]
Mr. Richard Haselgrove.

**Issue Resolved** Thank you for your assistance.

Suggested Solution by BOINC ALPHA: 

"You cannot run all debug flags at the same time, that's more information per second than an RPC can handle"

you have to go to the data directory, search for **cc_config.xml** edit it (with a plain text editor) and **change all the debug flags to 0 (zero)**, bar task, sched_ops and file_xfer, save the file and restart BOINC.

This worked like a charm, it disenchanted and restored my BOINC Manager.

closing ticket as **ISSUE RESOLVED**

**Comment by Isocosmic** [comment]
RESOLVED

THANK YOU

**Comment by Vulpine05** [comment]
> 3. Prevention. A big red warning on the top of the 'Event log options' dialog?

We could run a check to see how many event log check boxes are selected.  If it exceeds a certain number, a dialog box can pop up telling the user to reduce the amount of options.  I am not sure what that quantity is, but this should be fairly easy to add.

We could possibly do the same when reading the event log flags in starting up, too.

**Comment by Ageless93** [comment]
> We could run a check to see how many event log check boxes are selected. If it exceeds a certain number, a dialog box can pop up telling the user to reduce the amount of options.

It's not the quantity of check boxes, but which ones. There are two or three that generate an enormous amount of traffic and when selected at the same time, they overwhelm the amount of traffic the RPC can handle. It's easy to generate up to 1,500 lines per second, while the RPC can only handle something like 1,000 lines. 
 
Flags like <rr_simulation>, <rrsim_detail>, <work_fetch_debug> are high traffic ones.

**Comment by RichardHaselgrove** [comment]
> how many event log check boxes

It's not really just a case of 'how many' - a lot are very benign, and produce very little traffic. It's the few that generate a large number of lines, regularly and frequently, that are the problem.  rr_simulation, work_fetch, and the http pair come to mind as examples. I wondered if we could come up with an agreed list. and separate those out into a "Here lies danger" list: then we could restrict the selection to just one of the danger list, or require a separate "I have read and understood the warnings, and I want to go ahead anyway" box to be ticked.

**Comment by AenBleidd** [comment]
So maybe just make like a warning when saving settings with any of these flags saying that this will might lead to an issue?

And it's not generally possible to make a recovery of client from Manager because they might not be on the same machine.
So, recovery should be kept manual and not automatic.

**Comment by AenBleidd** [comment]
@Ageless93, @RichardHaselgrove, this sounds like a new feature request. Could please any of you create a new ticket with a proper description, and then we can continue this discusiion there

**Comment by Ageless93** [comment]
> I'll look to see if an emergency 'restore event log flags to default' could be added to the Manager, for use even when the client can't be contacted.

There is already a "Default" button on the Event Log Flags window, but you can't reach it or use it when BOINC Manager cannot connect to the client. The same will happen to any other "default" button in the manager. 

We probably more need a different description than "More info..." on the link to the explanation of what each flag does, or a mouse-over message on each one saying what they do and on the high traffic ones a warning not to use these together with the other high traffic flags (and say which ones). The hardest way is to just only allow one high traffic flag per session.

**Comment by AenBleidd** [comment]
> The hardest way is to just only allow one high traffic flag per session.

I don't agree. Users should be able to do whatever they, they only thing we should do is to warn them about the consequences

**Comment by RichardHaselgrove** [comment]
On your previous point - if this dialog is generated as an 'event in service', we could save a record of 'last host contracted' and 'data folder used'. If the last host was blank or localhost, reversion to default should be possible.

**Comment by AenBleidd** [comment]
@RichardHaselgrove, we can discuss this, but from my point of view, this is a very rare case, and it will work under very special conditions (local machine only). Also, it will require a lot of additional verifications like 'do this repair on request when no client is connected, and user should start BOINC Manager with a very special command line parameters to not try to connect to the client automatically, that will definitely not happen if the client is busy, and Manager will just hangs on start.

So, my opinion is that we should just warn users and nothing more

**Comment by AenBleidd** [comment]
What we could probably do is to make a separate tool (repair?) that could repair some wrong settings, but this definitely should be separated from Manager
