### ISSUE TITLE
Boinc client won't start with cc_config, exclude_gpu, device_num=99

### ISSUE THREAD

**Issue by sam8641** [BOINC/boinc#4906]
**Describe the bug**
Boinc client fails to start when cc_config.xml have exclude_gpu, device_num=99. The only error message is from BOINC manager, "The BOINC client has exited unexpectedly 3 times within the last 3 minutes".

**Steps To Reproduce**
1. Open cc_config.xml
2. `<cc_config><exclude_gpu><url>http://milkyway.cs.rpi.edu/milkyway/</url><device_num>99</device_num><type>ATI</type></exclude_gpu></cc_config>`

**Expected behavior**
Starts up and work, maybe with a warning about invalid device_num

**System Information**
 - OS: Windows 10
 - BOINC Version: 7.20.2

**Additional context**
Old Boinc version 7.16.20 did start ok, but may have some random stability problems with invalid device_num.
[cc_config.txt](https://github.com/BOINC/boinc/files/9438900/cc_config.txt)

**Comment by Vulpine05** [comment]
I can replicate this.  Windows 10, BOINC version 7.20.2.  Slight change from ATI to NVIDIA to account for my GPU.

I'm not familiar with the coprocessor settings in cc_config, but shouldn't that be defined in your file as well?  Regardless, if someone erroneously enters the wrong device number in the xml file, this shouldn't stop BOINC from running.
