### ISSUE TITLE
Linux: downstream releases broken in specific repositories

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#4930]
Mainstream Linux releases of the BOINC client / manager packages are handled by repo teams. But problems rebound by causing reputational damage to BOINC and, ultimately, UCB.

There have been sporadic grumblings for some time about an inability to run repository installations of BOINC for versions of Linux such as Ubuntu 22.04 LTS and Mint 21. None of them were specific enough for us to be able to pinpoint the source of the problem.

A conversation I had yesterday on the BOINC message board finally seems to identify the answer. We went from

> I upgraded linux mint to v21 about a month ago. I've been T/S off and on since but have reached a point of giving up.

via a single piece of advice to

> Hot damn! That did it...I'm back in business.
> Thank you!

(source: https://boinc.berkeley.edu/forum_thread.php?id=14792)

The advice was to **discard** the version 18.1 of BOINC supplied by the repositories, and replace it with version 20.2: I suggested @LocutusOfBorg's PPA as the source.

Version 18.1 was **never released** by BOINC for any desktop OS (Apple, Linux, or Windows). It was exclusively an Android release. It now appears likely that the desktop source code included in https://github.com/BOINC/boinc/tree/client_release/7/7.18 is seriously broken.

Now that we have had a reliable, recommended, release version 7.20.2 for over 2 months, working on all three platforms (although the platforms supported are not made clear in https://github.com/BOINC/boinc/releases), I suggest that we take urgent, proactive, action to get v7.18.1 **removed** from any Linux package that may have been inadvertently published, and get it replaced by v7.20.2

As an unknown, independent, volunteer, my voice won't carry enough weight to achieve that by itself. It needs to be an authoritative, clear, release instruction from a known BOINC source in the Linux arena - @davidpanderson, @lfield, or @AenBleidd come to mind.

It would also be helpful if Linux users with package maintenance connections (@Germano0, @LocutusOfBorg) could help to reinforce the message.

**Comment by AenBleidd** [comment]
@RichardHaselgrove, AFAIK @LocutusOfBorg if responsible for maintaining mainstream linux releases, so I can't remove faulty version from there.
All I can do from my side (and will try to do that with the new release) is to keep Desktop/Android releases always in sync, so there will be no major releases dedicated to any particular platform.

**Comment by KeithMyers** [comment]
@AenBleidd, @LocutusOfBorg doesn't have or ever did have the Android 7.18 release on his PPA.  His PPA is exclusive to Ubuntu.

The problem occurred because the other Debian distro maintainers grabbed the 7.18.1 Android version release from the BOINC Github tag release branch and didn't pay attention to the tag description [Android]

**Comment by dpapakonstantis** [comment]
is anyone working to resolve this issue for Linux?
is there any way to escalate this?
or bring it to the attention of someone who can sort it out?

**Comment by RichardHaselgrove** [comment]
Sadly, it seems not. And I'm not sure if anyone is still working on v7.22, which was found to be broken on a test launch in the meantime.

**Comment by AenBleidd** [comment]
We're working on 7.22.*, and there should be soon a new alpha release.

Speaking about the original question, we're gonna solve this issue somehow.
Currently I have no estimations when this will be resolved.

Stay tuned for updates.

**Comment by AenBleidd** [comment]
We're gonna move to the self-hosted linux packages on the official BOINC web-site.
Here's the list of the OSs that will be supported first: https://github.com/BOINC/boinc/wiki/Linux-DEB-and-RPM-support
Once we have tested them, and they appear in the more or less stable state - it will be announced and recommended for public usage.
Since we're not going to fix any distro (and in any case we're not maintaining them), this issue could be closed for now.

**Comment by Germano0** [comment]
I am already maintaining the client for Fedora and RHEL based distros

**Comment by AenBleidd** [comment]
@Germano0, once our vanilla packages are stable, would be nice if you align packages you maintain with the upstream.
Thank you.
