### ISSUE TITLE
Make BOINC urls case-insensitive

### ISSUE THREAD

**Issue by makeasnek** [BOINC/boinc#4937]
**Describe the problem**
When a user is given a URL to attach to a BOINC project, it will not work if the case is not correct. For example: boincproject.com/boinc would work but boincproject.com/BOINC would not. Domain names are case-insensitive, and I see no reason for case-sensitive URL handling. There is a chance that a user without the correct case-sensitive URL may try to attach to a project and therefore have issues doing so. Making URL handling case-insensitive would eliminate this source of error and confusion.

This is a further extension of https://github.com/BOINC/boinc/issues/4801

I realize this is a small issue and there are more important ones, just wanted to raise it as an idea.

**Describe the solution you'd like**
Make BOINC server URL handling case-insensitive

**Comment by Vulpine05** [comment]
This appears to be a problem for URLs with additional '/' after 'http(s)://'.  I was able to reproduce this for projects such as Amicable Numbers and Rosetta@home, but not with Climateprediction.net or World Community Grid.

Error is "Project not found - The URL you supplied is not that of a BOINC-based project.  Please check the URL and try again."

**Comment by davidpanderson** [comment]
handle_project_attach() should call canonicalize_master_url() instead of massaging the URL itself.
canonicalize_master_url() should convert to lower case.

**Comment by Vulpine05** [comment]
> handle_project_attach() should call canonicalize_master_url() instead of massaging the URL itself. canonicalize_master_url() should convert to lower case.

I think I understand what you're saying for handle_project_attach(), sounds like the code should get simplified there.  However, I'm not sure canonicalize_master_url() converts the url to lower case:
https://github.com/BOINC/boinc/blob/1016b872229f7084c954f9d9e618d80bba55745f/lib/url.cpp#L201-L207
I'm not too familiar with changing upper/lower case, but the comments on this function appear to do what it says and nothing more.

**Comment by AenBleidd** [comment]
Closing this as an invalid.
Explanation: https://github.com/BOINC/boinc/pull/5027#issuecomment-1328329224
