### ISSUE TITLE
BOINC 7.18.1 client refuse to start with specific CPU.

### ISSUE THREAD

**Issue by TechMasse** [BOINC/boinc#4956]
**Describe the bug**
The BOINC client refuse to run/load [as a service] with a Pentium G3240T present (_probably the same with a number of other Pentium G family CPUs too_)

**Steps To Reproduce**
1. Normal install procedure, including OpenCL.
2. A error message is generated when trying to start the client - STATUS=4/ILL.

**System Information**
 - OS: Lubuntu 22.04.1 LTS
 - BOINC Version: 7.18.1

**Additional context**
Less than two weeks ago, I got my hands on six refurbished _Dell OptiPlex 3020 Micro_ and started to prepare them last weekend. Tried to run the client on the first and it failed. Tried the remaining five and those failed the very same way (_which rules out any faulty CPU_). I suspected that the issue is CPU related anyway. Didn't bother much at the time, as I already had ordered a better CPU, an i7-4785T, to test if it was possible to upgrade beyond Dell's official specifications (_4th gen. i5/35W. It's not unusual that the hw manufacturers don't update their manuals._) The BOINC system requirements [Linux] specify Pentium 500 MHz or greater (_ie. Pentium III [or a Mendocino family/2nd gen. Celeron]_). The OptiFlex 3020M originally fit Pentium G3240T is a Haswell CPU @2.70 GHz, so it should have been working.

I got the i7-4785T earlier this week and tested it immediately without any issues - the BOINC client is running fine. The main feature differences between the CPUs are that the G3240T lack support for Hyper-Threading, vPro and some extra AES instructions (_other than having no Turbo Boost, less cores/threads and cache than the 4785T_) If any of these three are required, it should be included in the system requirements.

Related to BOINC, I have so far come across different [Debian/Ubuntu] error messages (_STATUS=..._), which I have searched on the Internet and have not found any relevant/useful explanations. One of them is earlier reported here.

**Comment by Toby-Broom** [comment]
Did you check this #3355

**Comment by AenBleidd** [comment]
@TechMasse, Recommended BOINC to install on linux is 7.20.2, you can take it from this PPA: https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/boinc

**Comment by TechMasse** [comment]
@AenBleidd 

Yes, that works. Thanks!
