### ISSUE TITLE
Boinc reports cpu time incorrectly. on windows 11 22h2

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#4957]
**Describe the bug**
Boinc reports cpu time incorrectly.
Rosetta uses cpu time to adjust workunit length.
By default Rosetta workunits take 8 hours of cpu time.
On 226232 they will continue crunching for too long.
**Steps To Reproduce**
1. Install Windows 11 22622.521
2. Run TN-Grid
3.Compare Runtime and cpu time
**Expected behavior**
Elepse time and cpu time shouldn't differ much.
**Screenshots**
![Снимок экрана (231)](https://user-images.githubusercontent.com/8822292/194765086-b95c0ad6-75e8-4731-bcd3-491017800e02.png)
![Снимок экрана (232)](https://user-images.githubusercontent.com/8822292/194765128-739ea8f7-81a5-4e6e-8255-a6d6213c368b.png)

**System Information**
 - OS: Microsoft Windows [Version 10.0.22622.521]
 - BOINC Version: 7.20.2

**Additional context**

**Comment by AenBleidd** [comment]
I'm not sure you understand correctly what do these values mean: please read this article first https://en.wikipedia.org/wiki/CPU_time
Also you can check these values in ProcessExplorer and it will show you basically the same values as they are shown in BOINC Manager: https://en.wikipedia.org/wiki/CPU_time

**Comment by kotenok2000** [comment]
Process explorer and windows task manager display different cpu usage.
![Снимок экрана (233)](https://user-images.githubusercontent.com/8822292/194765912-7343adfb-4f01-4323-8309-a10e7896e40b.png)

**Comment by AenBleidd** [comment]
Process explorer shows more exact values. But before you asked about CPU time, not CPU usage. So what is your main confusion here?

**Comment by hucker75** [comment]
I don't understand this either.  I also use Boinctasks, and my CPU% column shows % of ONE CORE (or perhaps the number of cores expected for that task), so things like TN-Grid which are single core programs show nearly 100%.  Why do you have only nearly 10%?

**Comment by kotenok2000** [comment]
Maybe this will shed some light?
]https://www.neowin.net/news/windows-11-cpu-usage-reporting-is-apparently-buggy-including-on-task-manager/

**Comment by hucker75** [comment]
No calculations from Boinc are accurate.  For example I have a Primegrid GPU task which has done 30% in 1 day, yet it says the other 70% will take 100 days.  With programming like that, it's surprising it works at all.

**Comment by kotenok2000** [comment]
When i run workunits on all cores cpuid hwmonitor thinks that only core 0 is used.

**Comment by hucker75** [comment]
I use HWInfo, Windows 11 task manager, MSI Afterburner, Boinctasks.  All report correct % usage on all projects for CPU ad GPU.

**Comment by kotenok2000** [comment]
Are you running Windows 11 22000 , 22621 or 22622?

**Comment by hucker75** [comment]
Ah, I use 22000, I assumed I was up to date.  Windows update will not give me any more.  Are you using something from the Insider Program?  If so I guess they broke it, and you should direct this problem to them.

**Comment by kotenok2000** [comment]
v>f

**Comment by hucker75** [comment]
You could try it.  I've seen all sorts work better with BIOS updates, but usually stuff like fan control, not something the OS does.  But maybe the CPU usage is under BIOS control?  I thought it was OS only, but maybe not.

**Comment by kotenok2000** [comment]
I have uppdated efi to the latest version. Didn't help.

вс, 9 окт. 2022 г., 23:14 Peter Hucker ***@***.***>:

**Comment by hucker75** [comment]
There are many people complaining Windows11 does things similar to what you're experiencing.  I found:

"Go to "Windows Settings>Power>Power Mode" and change the Power Mode setting to <Best Power Efficiency>"

and

"It is probably just a bug if your BIOS is up to date, there is another large update coming in a couple of weeks"

But why do you have 22H2 and I do not?  I cannot acquire it in Windows update, perhaps they pulled it due to bugs?

**Comment by kotenok2000** [comment]
I have used windows 11 update assistant
https://www.microsoft.com/software-download/windows11

**Comment by TNM9999** [comment]
I also recently updated to Win11 22H2 on two of my Boinc machines. Both are showing CPU usage % as being very low when compared to pre-22H2. Previously, these machines would show CPU usage of 95-98% for each task. The picture below (using Boinc Tasks) shows that usage has dropped around half on one of them.

It appears that 22H2 has changed how the CPU usage calculation is being made or reported.

Elapsed time is correct. CPU usage time and % are very low:
![image](https://user-images.githubusercontent.com/115507540/194956903-4893a83b-692b-470a-bfba-145231046292.png)

This is a sample from World Community Grid showing that the low CPU time/utilization is being used by the projects:
![image](https://user-images.githubusercontent.com/115507540/194960844-04a7fa4d-1bdd-4a26-9fd6-457749cdb3e8.png)

**Comment by hucker75** [comment]
Not sure what you mean by "22H2", my version is in numbers only.  I'm on 10.00.22621.00 on one machine which I think is the same thing and don't have this problem.  Boinctasks reports almost 100% for every task.

**Comment by TNM9999** [comment]
It is the latest, updated version of Windows 11. It was officially released in the past month or so.

Windows 11, version 22H2

**Comment by kotenok2000** [comment]
Can you run ver in command line?

**Comment by TNM9999** [comment]
I think that this is it:
Microsoft Windows 11 Home
Version = 10.0.22621  Build 22621

**Comment by kotenok2000** [comment]
when i run ver i get this


Microsoft Windows [Version 10.0.22622.608]

**Comment by hucker75** [comment]
So you are both seeing the problem, on 22621 and 22622.  Yet I am not seeing it on 22621.  The only difference is mine is Enterprise.

**Comment by TNM9999** [comment]
When I run winver, the response is:
![image](https://user-images.githubusercontent.com/115507540/194975465-39eedd86-6316-4232-9d80-c0d1143155ef.png)

I will check the version on my other Windows 11 computer tomorrow.

My third computer is still running Windows 10 and the CPU usage is correct. 95-98% or so.

**Comment by kotenok2000** [comment]
I rmembered thaat i have process hacker 3.0.4953 installed with kernel driver and VulnerableDriverBlocklistEnable set to 0
at HKLM\System\CurrentControlSet\Control\CI\Config\
https://processhacker.sourceforge.io/nightly.php
