### ISSUE TITLE
Disk usage pie chart shows projects multiple times in the mouse-over

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#496]
**Reported by Ageless on 19 Oct 37956691 20:26 UTC**
I got this question from TJM through the Enigma forums. 

"Hello Jord,

Take a look at these graphs:

http://plikens.no-ip.net/plikens/298x81rav/Clipboard02.png
http://plikens.no-ip.net/plikens/297xwdcgj/bug1.png

at the second screen you can see that the tooltip shows 'boincsimap' instead of hydrogen@home. Purely cosmetic, but it's still a bug. Is it a known problem ?"

I then checked the pie chart on the right in my BOINC 5.10.30 and found I have two entries for Einstein@Home, both 55.30MB big. They are the same colour as well (pink). 
If I then go further down the pie chart and check what projects the mouse-over says it 'sees', I notice that it finds the projects it found first again. I have duplicates of Einstein, Alpha BOINC, Hydrogen, LHC, Leiden Classical etc. 

Something weird in the mouse-over code. And difficult to explain. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/517

**Comment by romw** [comment]
**Commented by Nicolas on 26 May 37956746 23:33 UTC**
The cause is indeed the duplicated colors.

**Comment by romw** [comment]
**Commented by Der Meister on 16 Mar 37957021 08:26 UTC**
This was already reported on boinc_dev a month ago:
http://lists.ssl.berkeley.edu/pipermail/boinc_dev/2007-November/009154.html

There were also a few additional comments in this thread and David Anderson commited a change to the color-generating code. It should now create random colors and hopefully no duplicates.

**Comment by romw** [comment]
**Commented by marekz on 23 Feb 37995243 03:06 UTC**
Replying to [Ageless](ticket:517):

Think it's the same as ticket #238. :-)

**Comment by ChristianBeer** [comment]
Should be fixed in current (7.6.33) version.
