### ISSUE TITLE
save button not on screen

### ISSUE THREAD

**Issue by hpvpp** [BOINC/boinc#4970]
system details
OS: Ubuntu 20.04 LTS fully uptodate
screen: 1366x768
boinc manager: version: 7.16.6(x64)
wxWidgets version: 3.0.4

problem description
panel: boinc manager>Options>Computing preferences
problem: "Save" button not visible
problem: panel is taller than will fit on available screen space

screenshot
![Screenshot from 2022-10-13 14-13-12](https://user-images.githubusercontent.com/20672356/195491878-0f413e7a-6fae-4d08-86ac-051894fe2eb8.png)

**Comment by AenBleidd** [comment]
Already fixed via #4941
