### ISSUE TITLE
Autopause GPU usage when it is occupied by another program, e.g. video playing

### ISSUE THREAD

**Issue by putianyi889** [BOINC/boinc#4986]
**Describe the problem**
I'd like to run BOINC in idle time, but it is not smart enough. I can ask it to stop when I use the keyboard or the mouse, but I also want it to stay calm when, e.g. I'm watching videos. At present, the GPU program kicks in when I haven't touched the machine for a while, interfering with video playing and for once leading to machine crash.

**Describe the solution you'd like**
The simplest solution would be to have an individual setting, stopping the GPU when CPU and/or GPU usage is above some threshold.
Currently only CPU can be controlled in this way.

**Comment by AenBleidd** [comment]
I believe, #2301 contains a better approach of the same issue.
I keep this ticket open for a while in case someone would like to discuss it, but personally I think it should be closed as a duplicate.

**Comment by putianyi889** [comment]
> I think it should be closed as a duplicate.

agreed

**Comment by davidpanderson** [comment]
BTW: when CPU computing stops, so does GPU computing.

**Comment by putianyi889** [comment]
but I do want the CPU to keep running.

**Comment by davidpanderson** [comment]
I see.  The problem is that we haven't found a reliable way of figuring out when a movie is being watched.  CPU usage isn't a good indicator.  GPU usage may be a good indicator but we currently don't know how to measure it.

**Comment by putianyi889** [comment]
Is it possible to have a browser extension communicating with the boinc manager somehow?

**Comment by davidpanderson** [comment]
That's a good idea, although I'd prefer not to get into the business of developing browser extensions

**Comment by AenBleidd** [comment]
Completely agree. There should be more universal way to detect this thanakijg a browser extension.
