### ISSUE TITLE
Drag highlighting doesn't work on rocky linux 8

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#4991]
**Describe the bug**
When i try to select several lines in boinc manager on rocky linux 8 it  doesn't work
**Steps To Reproduce**
1. Install rocky linux from https://download.rockylinux.org/pub/rocky/8.6/Live/x86_64/Rocky-XFCE-8-x86_64-20220515.4.iso
2. Install boinc with sudo dnf install boinc*
3. Start boinc with systemctl start boinc-client.service
**Expected behavior**

**Screenshots**
![Снимок экрана (247)](https://user-images.githubusercontent.com/8822292/198619115-32eb9a5a-473c-4f6e-a737-24ba535305ec.png)

**System Information**
 - OS: Rocky linux 8
 - BOINC Version: 7.20.2
 - Wxwidgets: 3.0.4

**Additional context**

**Comment by RichardHaselgrove** [comment]
Also observed on Linux Mint 20 and 21 with 'Mate' desktop.

However, keyboard extensions (shift-click, ctrl-click) do work.

**Comment by AenBleidd** [comment]
I suspect this might be an wxWidgets issue. Will take a look

**Comment by RichardHaselgrove** [comment]
Yes, probably wxWidgets. Drag selection does work in other programs - FireFox, text editor.

**Comment by AenBleidd** [comment]
Ok, this is a limitation of the wxWidgets.
I don't see any reason to create any custom implementation of this functionality.
