### ISSUE TITLE
[vboxwrapper] Build is failed on the older system because of c++11 lambda usage

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4993]
https://github.com/BOINC/boinc/blob/213028bb9523ee14800ad0866202f28945c3792c/samples/vboxwrapper/vbox_vboxmanage.cpp#L608-L609

This need to be rewritten to get rid of:
- lambda
- cbegin/cend

@computezrmle, please fix that

**Comment by CharlieFenton** [comment]
I get this error on the Mac:
`vbox_vboxmanage.cpp:609:44: error: expected expression
                        type_line.begin(), [](unsigned char c) { return tolower(c); });
`

**Comment by davidpanderson** [comment]
Use downcase_string() from lib/str_util.h
