### ISSUE TITLE
User setting: default sort mode on top pages

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#50]
**Reported by KSMarksPsych on 16 Dec 37296889 05:46 UTC**
Posted by: 
Date: 9:22 AM 10-15-2005
the default sort mode defined in most pages on most projects seems to be by RAC. However, some of us that are skeptical of RAC having any meaning at all, would prefer to have all the sorts done by Total Credit. Would it be possible to have a Site preference for that?

Migrated-From: http://boinc.berkeley.edu/trac/ticket/50

**Comment by lfield** [comment]
The columns on the statistics pages can be sorted. I believe that this is no longer and issue.
