### ISSUE TITLE
Wrong permssions on html/cache directory

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#5008]
b'set_cached_data(): can\'t open ../cache/f2/server_status.php_job_status

# ll lhcathome-dev/html/cache -d
drwxrws--- 1 apache boinc 291 Nov  9 22:23 lhcathome-dev/html/cache

https://github.com/BOINC/boinc/blame/master/py/Boinc/setup_project.py#L300

```
lfield@ThinkPad-X1:~$ chmod 600 test_file 
lfield@ThinkPad-X1:~$ ll test_file 
-rw------- 1 lfield lfield 0 Nov  9 15:26 test_file
lfield@ThinkPad-X1:~$ python3 -c "import os; os.chmod('test_file', 0o2770)"
lfield@ThinkPad-X1:~$ ll test_file 
-rwxrws--- 1 lfield lfield 0 Nov  9 15:26 test_file*
```
Seen on the server_release_1.4 branch

**Comment by Frigyes06** [comment]
@lfield This issue is indicated fixed, and appears to work correctly for others (https://github.com/BOINC/boinc/pull/5007)
Is this issue still happening for you?

**Comment by lfield** [comment]
@Frigyes06 I am not sure this is an issue. Will re-open if it happens again. Thanks for following up.
