### ISSUE TITLE
BOINC unable to connect client

### ISSUE THREAD

**Issue by anish1-9** [BOINC/boinc#5018]
BOINC unable to connect client
BOINC unable to connect client, not running any tasks

**Steps To Reproduce**
1. Unable to connect to client
2. Unable to run any tasks

**Expected behavior**
Must be able to connect to internet and automatically run tasks on my computer

**Screenshots**
![image](https://user-images.githubusercontent.com/97441682/202700164-726b3abc-1eba-440d-a0fc-670c3a0ecbda.png)

**System Information**
 - OS: Windows 11
 - BOINC Version: 7.20.2 (64 bit)+virtualBox

**Comment by AenBleidd** [comment]
@anish1-9, please go to the Options->Other options, check that 'Run the client' is checked, then restart BOINC Manager.
P.S. BOINC client is a local application installed with the Manager, and 'Disconnected' shows that BOINC Manager is disconnected from the local client.
P.P.S. BOINC Manager can also manage BOINC client running remotely, but I don't think this is your case currently

**Comment by AenBleidd** [comment]
Since there is no reply, closing this as 'Invalid'
