### ISSUE TITLE
[Manager]: fix minor graphics bug in #5010

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#5019]
**Describe the bug**
Manager command button switches to 'Stop graphics', but has no action.

Applies when graphics window is active: seen on Windows OS only, but expected to apply to Linux too.

Change introduced during work to work round new Mac security demands.

**Steps To Reproduce**
1. Click 'Show graphics' button in Manager.
2. Note button label changes to 'Stop graphics'.
3. Click it. Graphics window remains open.

**Expected behavior**
Button acts and closes window, as it does in v7.20.2 and before.

**System Information**
 - OS: Windows 7, 10, 11 
 - BOINC Version: test build incorporating #5010 or later.

**Additional context**
Alternative solution would be to remove the Show / Stop label change, but the consensus is that keeping the display and re-activating - the action would be better.

**Comment by CharlieFenton** [comment]
> Change introduced during work to work round new Mac security demands.

Actually, this bug was introduced in commit 1ab508f3d8 on 13 August 2020. Apparently, no one noticed until now.

**Comment by RichardHaselgrove** [comment]
But it isn't expressed in the Windows v7.20.2 release build dated 19 July 2022, which is what misdirected my confirmation tests. There must be some other reason why it has lain dormant until now.

**Comment by CharlieFenton** [comment]
@RichardHaselgrove You are correct. I didn't read the old code closely enough. The bug is new in 7.20.3
