### ISSUE TITLE
Manager: cherrypick PR #5022 to release branch

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#5029]
Client+Manager release branch 7.20.4 has been certified for release for the Macintosh platform only, but it has been picked up by @LocutusOfBorg as a development release for Ubuntu. (We have no control over that part of the process).

Patch #5022 was developed as a bugfix specifically to ensure compatibility across the Linux, Mac and Windows platforms. I think it should be applied to the release branch.

**Comment by AenBleidd** [comment]
This looks like a good candidate for linux-only release. I don't plan to create new minor release for Windows, so I'll just create a new tag (probably a release as well) and will notify @LocutusOfBorg to make a new build for linux.

THank you, @RichardHaselgrove

**Comment by RichardHaselgrove** [comment]
That seems fair enough. In my experience, Windows users mainly use the installer, but Linux users are more likely to self build. And the real hard core will use master anyway. I emailed Gianfranco via launchpad, but I haven't received a reply yet.

**Comment by LocutusOfBorg** [comment]
Hello, please tag me directly here :)

**Comment by AenBleidd** [comment]
@LocutusOfBorg, please make a new build for linux from the `client_release/7.20/7.20.5` tag.
Let me know when this is done so I can close the ticket.
Thank you in advance

**Comment by AenBleidd** [comment]
Not sure this is a good solution. We will think about best approach

**Comment by LocutusOfBorg** [comment]
done!

**Comment by RichardHaselgrove** [comment]
Hasn't shown up in my Update Manager yet, but I'll keep refreshing and test it when it does.

**Comment by AenBleidd** [comment]
Ok, I'll keep it then open.
@RichardHaselgrove, please close this ticket when you're done with the testing

**Comment by RichardHaselgrove** [comment]
Yes, I'll report back and close the ticket if NFA is needed.

There's the question of how to clarify the scope of any particular release. I think there are three cases to consider.

The general case is a combined release for the three main desktop platforms - Apple, Linux, and Windows. The would normally be a 'minor version' release. (*)

Then there's a special release for a single platform - either an external problem, like the expired certificate in Windows or the OS X security changes, or a bugfix for a specific problem like the current case. This would be a 'build' version release. (*)

And then there's Android. This has been largely separate from the mainstream releases, but I know you'd like to combine them. Do we have the human developer bandwidth to do that consistently?

(*) Using the Major.Minor.Build terminology from the 'Version Numbering' appendix to the [Client Release Process](https://github.com/BOINC/boinc-policy/blob/master/Development_Documents/Client_Release_Process.md) document.

**Comment by RichardHaselgrove** [comment]
v7.20.5 has made its way through the Linux Mint Update Manager system, along with a good wodge of Linux kernel updates. Applied them all, and BOINC loads and runs cleanly. Graphics apps can be started and stopped from the Manager. Closing as done.

**Comment by Vulpine05** [comment]
I was able to get my machines with Ubuntu 18.04 updated to 7.20.5.  However, the version is listed as a pre-release.  It shouldn't display that, should it?

**Comment by RichardHaselgrove** [comment]
Where did you get 7.20.5 from? I tested from Gianfranco's PPA, which is intended as a fast pre-release channel. I would expect releases from Ubuntu repositories to be full releases, though.

**Comment by LocutusOfBorg** [comment]
Hello, is 7.22.0 ready for linux usage?

**Comment by RichardHaselgrove** [comment]
Not yet, because of https://github.com/BOINC/boinc/issues/5072#issuecomment-1403336588

**Comment by AenBleidd** [comment]
> Hello, is 7.22.0 ready for linux usage?

This is not the correct place to ask this question, but anyway.

Your PPA contains up-to-date version of BOINC for all supported versions of Ubuntu.

But if you go to the official Ubuntu distro https://packages.ubuntu.com you will see that:
- 18.04 (Ubuntu version) => 7.9.3 (BOINC version)
- 20.04 => 7.16.6
- 22.04 => 7.18.1
- 22.10 => 7.20.2

Is there a way to update BOINC there as well?

Also, looks like BOINC is not usable just after installation from the official Ubuntu distro packages, and user has to do a lot of actions to make it works.
Is there a way to fix that (because your PPA has no such issues IIRC).

**Comment by LocutusOfBorg** [comment]
@AenBleidd do you have a wiki with the steps for the user to perform to make it usable? because I don't really know, the ppa is the same packaging as Ubuntu (except for older releases)

**Comment by AenBleidd** [comment]
I don't have it, and usually these are just the pieces of information on forums.
Maybe this is because some distros have outdated version, but mainly after installation user has to do next:
- sudo systemctl enable boinc-client
- add user to BOINC group
- fix permissions of gui_rpc_auth.cfg because by default BOINC Manager can't connect to the running client.

Also, it's still not clear for me why older (but still supported) versions of Ubuntu does not have an up-to-date version of BOINC that is available on your PPA.

**Comment by Vulpine05** [comment]
@LocutusOfBorg , I can help with the steps.  Let me find my notes and report back.

**Comment by LocutusOfBorg** [comment]
>Also, it's still not clear for me why older (but still supported) versions of Ubuntu does not have an up-to-date version of BOINC that is available on your PPA.

because on stable Ubuntu, upgrading packages to newer version should be done with lot of testing, to avoid introducing regressions. There are some whitelisted packages for newer releases (e.g. chrome/firefox/virtualbox), but this is something I try to avoid, unless there are specific bugs to fix.

**Comment by Vulpine05** [comment]
@LocutusOfBorg sorry, I thought I kept good notes but I can't seem to find them.  Let me tell you anecdotally what I encountered.

I would do a clean installation of Ubuntu, either 18.04 or 20.04.  I would then try to install BOINC by using either Ubuntu Software or your PPA.  When I would run the Manger, the Manger window would appear, but then I'd get a popup message stating something to the effect that a client couldn't be found.  I feel like I tried using the command line (sudo apt-install boinc-manager boinc-client), and even though it successfully installed, it would still get the same problem.

I think my solution was to go back and forth trying to uninstall and reinstall the client and manager, and at some point everything would work together.  All I know is it was definitely not user friendly.

Sorry, I know this isn't as helpful as you probably need.  I can try to reproduce the problem with a clean installation of Ubuntu if you want to get you more specific information.  Let me know if you would prefer 18.04, 20.04, or a different version.

**Comment by CharlieFenton** [comment]
@LocutusOfBorg 7.22.0 has been withdrawn because it ignores the user's throttling settings and always runs BOINC at 100% of CPU time, which could overheat and potentially damage a user's computer. Do not distribute it. We are working on a fix for that and other related issues.
