### ISSUE TITLE
Manager exist un-expectly when applying new preferences

### ISSUE THREAD

**Issue by johnroyer** [BOINC/boinc#5049]
**Describe the bug**
Modify perferences in dialog, and lick "save" button. BOINC manager crashed and exit (It happens rarely). 
But tasks still runing in the background.

If open BOINC manager again, BOINC manager can not detect those background tasks, and will create new task process.

**Steps To Reproduce**
1. Open preference dialog
2. Modify some configurations
3. Click "save"

**Expected behavior**
BOINC manager should save new preference, and then apply it to current environment.

**Screenshots**
In Windows task manager, project processes are sub proccess of BOINC manager.
![2022-12-30_141051](https://user-images.githubusercontent.com/114491/210040077-3b846be6-d191-4be5-a226-79e25d0a820c.png)

If BOINC manager proccess will exit, but project process will still runing.

**System Information**
 - OS: Winwodws 10 Professional
 - BOINC Version: 7.20.2 (x64)

**Additional context**
Issue does not happen oftenly. BOINC manager crashes maybe becuse "save tasks no more then X days" modified, but I am bot pretty sure.

**Comment by Vulpine05** [comment]
@johnroyer do you have your keyboard set to Microsoft Pinyin?  I wonder if this is related to #4014.

**Comment by johnroyer** [comment]
@Vulpine05 : I do use Chinese input method, but not Microsoft Pinyin.

Thanks for reply.

**Comment by AenBleidd** [comment]
@johnroyer, please setup post mortem dump creation like it's described here: https://www.atmosera.com/blog/procdump-post-mortem-switches-order-matters/
Then please try to crash BOINC and check for a dump file in the folder you specified from the article above.
When you have dump file, please attach it to this ticket.
Thank you in advance.

**Comment by johnroyer** [comment]
@AenBleidd Thanks for support.

I can not find a stable way to crash BOINC. I will keep ProcDump monitor BOINC proccesses, and updates if any new discoveries.

**Comment by AenBleidd** [comment]
I'll close it. Thanks for the feedback. If you will manage to reproduce the same issue again - feel free to reopen this ticket.
