### ISSUE TITLE
MacOS 7.20.4 permissions problem

### ISSUE THREAD

**Issue by tcoradeschi** [BOINC/boinc#5057]
MacOS client 7.20.4 seems to have some sort of a permissions problem when it tries to write output files to disk

I see this on both Mohave and High Sierra machines (both at the most recent revision). /library/application support/BOINC data is owned by user boinc_master and is in group boinc_master, with R+W permissions for both.

Fri Jan 6 13:08:52 2023 | World Community Grid | Started download of MCM1_0194376_5284_MCM1_0194376_5284.txt
Fri Jan 6 13:08:52 2023 | World Community Grid | Started download of mcm1.dataset-sarc1.txt
Fri Jan 6 13:08:53 2023 | World Community Grid | Finished download of MCM1_0194376_5284_MCM1_0194376_5284.txt
Fri Jan 6 13:09:10 2023 | World Community Grid | Finished download of mcm1.dataset-sarc1.txt
Fri Jan 6 13:09:11 2023 | World Community Grid | Starting task MCM1_0194376_5284_2
Fri Jan 6 13:09:13 2023 | World Community Grid | Computation for task MCM1_0194376_5284_2 finished
Fri Jan 6 13:09:13 2023 | World Community Grid | Output file MCM1_0194376_5284_2_r912214080_0 for task MCM1_0194376_5284_2 absent

Not project specific, either.
Sat Jan 7 08:27:24 2023 | Einstein@Home | Starting task p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1
Sat Jan 7 08:27:25 2023 | Einstein@Home | Computation for task p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1 finished
Sat Jan 7 08:27:25 2023 | Einstein@Home | Output file p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1_0 for task p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1 absent
Sat Jan 7 08:27:25 2023 | Einstein@Home | Output file p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1_1 for task p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1 absent
Sat Jan 7 08:27:25 2023 | Einstein@Home | Output file p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1_2 for task p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1 absent
Sat Jan 7 08:27:25 2023 | Einstein@Home | Output file p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1_3 for task p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1 absent
Sat Jan 7 08:27:25 2023 | Einstein@Home | Output file p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1_4 for task p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1 absent
Sat Jan 7 08:27:25 2023 | Einstein@Home | Output file p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1_5 for task p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1 absent
Sat Jan 7 08:27:25 2023 | Einstein@Home | Output file p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1_6 for task p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1 absent
Sat Jan 7 08:27:25 2023 | Einstein@Home | Output file p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1_7 for task p2030.20200708.G52.56-02.70.S.b0s0g0.00000_1504_1 absent

Any thoughts would be greatly appreciated.

Tom Coradeschi

**Comment by AenBleidd** [comment]
@CharlieFenton, could you please take a look?

**Comment by CharlieFenton** [comment]
This is nothing new. It is not unusual for users to see the "output file absent" message on an occasional task.  I suspect it can occur for different reasons, though I don't know why it typically does and never worry about it. I run Einstein tasks constantly and see this issue in the log just once for Einstein and once for Rosetta since November 10 . However, I have no way to test on older versions of MacOS, though we have not had any other reports of this.

If you search the  [BOINC message boards](https://boinc.berkeley.edu/forum_index.php) for "absent" you will find at least 12 threads about "output files absent."

Sorry, I have no time to look at this further, other than offering the usual advice to reinstall BOINC.

**Comment by RichardHaselgrove** [comment]
'Output file absent' is a common, and standard, **symptom** that a science task has failed to reach its intended conclusion. You need to look deeper into the original **cause** of whatever led up to the report - an error of some sort, typically an application crash or shortage of disk space. Look at your tasks on the project web site, read the Client State and Exit Status, read the stderr.txt output, ask other users for advice.

**Comment by tcoradeschi** [comment]
Well, thanks, I think. So I guess that the same failure, on two different computers, running two different versions of MacOS, both trying to run two different projects, is "how it's supposed to work". 

Uninstalling and reinstalling is pretty much the first thing you do, and on the rebuilt computer, something I've probably done 3 or 4 times now. It would be interesting to roll back to the prior release. Maybe I'll give that a shot, if I can find the binary.

Neither computer has returned a work unit to either of the projects in weeks.

I see the following in the logs as well. If that ain't a permissions problem, not sure what is. (yes, a little frustrated, as I've been running BOINC for probably 15 years now)

08-Jan-2023 22:15:04 [Einstein@Home] merge_info(): failed to change permissions of einsteinbinary_BRP4G_1.60_x86_64-apple-darwin
08-Jan-2023 22:15:04 [Einstein@Home] merge_info(): failed to change permissions of einsteinbinary_BRP4_1.60_graphics_x86_64-apple-darwin
08-Jan-2023 22:15:04 [Einstein@Home] merge_info(): failed to change permissions of hsgamma_FGRP5_1.11_x86_64-apple-darwin__FGRPSSE
08-Jan-2023 22:15:04 [Einstein@Home] merge_info(): failed to change permissions of einstein_O2MD1_2.10_graphics_x86_64-apple-darwin
08-Jan-2023 22:15:04 [Einstein@Home] merge_info(): failed to change permissions of fftwf-wisdom_FGRP5_1.11_x86_64-apple-darwin

**Comment by CharlieFenton** [comment]
@tcoradeschi Thank you for providing the additional logs; those had the critical information to show that it does appear to be a permissions issue. I have not been able to reproduce your problem on MacOS 13 Ventura. I'll try to arrange to test on a Mac running Mojave or High Sierra.

I may ask you to run some additional tests if I can't reproduce the issue.

**Comment by tcoradeschi** [comment]
No problem. Just let me know what you need.

**Comment by CharlieFenton** [comment]
@tcoradeschi Please provide us the _/Library/Application Support/BOINC Data/stdoutdae.txt_ file from each of the two computers spanning the relevant time period, ideally going back to January 3 or earlier. If the earliest entry in that file is later than January 3, please also provide the _/Library/Application Support/BOINC Data/stdoutdae.old_ file. These files do not contain any personal data.

You can attach the files to your reply. You might want to zip them first.

I have managed to get MacOS 10.13.6 High Sierra running on an old Intel iMac which apparently has a bad GPU chip, so I am running it via screen sharing from another Mac. I attached to Einstein@home since that is one of the projects you cited. I have not seen any problems yet.

**Comment by CharlieFenton** [comment]
@tcoradeschi also please provide us the /Library/Application Support/BOINC Data/stderrdae.txt file from each of the two computers.

**Comment by tcoradeschi** [comment]
Attached is the file from the computer running MacOS 12.6.2.

Very strangely, when I updated the BOINC install back to 7.20.4 (from 7.20.2), it started running properly and continues to do so. I do see permission errors in stdoutdae.txt (attached), e.g.
11-Jan-2023 19:12:05 [Einstein@Home] merge_info(): failed to change permissions of einstein_O3MD1_1.02_x86_64-apple-darwin__GW-SSE2

/Library/Application Support/BOINC Data/stderrdae.txt is empty
[stdoutdae.txt](https://github.com/BOINC/boinc/files/10401350/stdoutdae.txt)

**Comment by tcoradeschi** [comment]
Attached are the logs from MacOS 10.13.6. There are entries in the stderrdae.txt file, but all appear old. It's attached here.
[stderrdae.txt](https://github.com/BOINC/boinc/files/10401429/stderrdae.txt)
[stdoutdae.txt](https://github.com/BOINC/boinc/files/10401430/stdoutdae.txt)

**Comment by tcoradeschi** [comment]
If you'd like, I can do a clean install of 7.20.4 (rather than an update) and provide you the results from that operation.

That would include uninstalling, deleting /Library/Application Support/BOINC Data/ and then re-installing, I think.

**Comment by CharlieFenton** [comment]
@tcoradeschi Thank you, that is very helpful. You had not mentioned that you have BOINC running as a service (daemon.) That changes everything! Very few people configure BOINC that way, so I was not expecting that. Do you happen to know whether any user was logged in the permission errors occurred?

I will begin testing that way and let you  know what I find.

**Comment by CharlieFenton** [comment]
@tcoradeschi I have now reproduced the _merge_info(): failed to change permissions_ and _Output file absent_. I think I may have found the problem. Please download and install [this](https://boinc.berkeley.edu/dl/boinc_test_13Jan2023.zip) test build and let us know if it fixes this issue.

**Comment by tcoradeschi** [comment]
Ah, yes. I am doing that. So, on the MacOS 10.13.6 machine, there is rarely anyone logged in. The one running 12.6.2 typically has two users logged in 24/7.

**Comment by tcoradeschi** [comment]
At least on the MacOS 12.6.2 machine, that seems to have done it (installed and rebooted). I will update the other one shortly and let you know.
[stdoutdae.txt](https://github.com/BOINC/boinc/files/10411344/stdoutdae.txt)

**Comment by tcoradeschi** [comment]
Thanks for making this happen, folks!
