### ISSUE TITLE
BOINC crashing

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [BOINC/boinc#5063]
Hello,
so I run BOINC on Windows 10 and it sometimes throws errors or crashes.
So my system is running 24/7 and it sometimes crashes and basically wastes the time where it could do useful work.

Can you guys work a little on BOINC, improve UI, make it more user friendly and make not crash?

**Comment by AenBleidd** [comment]
Hello @4e576rt8uh9ij9okp,thank you for the report.
Could you please provide more information about the crash?
What exactly is crashed? BOINC Manager, BOINC client, running Project application, etc?
Please attach logs if available.
Thank you in advance

**Comment by AenBleidd** [comment]
Hello @4e576rt8uh9ij9okp,
thank you for the detailed answer.
Looks like you do not use BOINC in a right way.
First, be sure to open in BOINC `Options` -> `Computing preferences` and on the `Computing` tab set preferred settings.
For example, these are my settings:
![image](https://user-images.githubusercontent.com/3234209/214061951-0178175e-74a6-443a-ac85-1501fc4030b4.png)
Also, if you want BOINC to run always even when not idling but stop computations when certain process is running (e.g. any video game), please in BOINC open 'Options' -> `Exclusive applications` and set there all applications that should 'pause' BOINC computations. Please pay attention that the top most list is the list that will 'stop' `CPU and GPU` applications and the list on the bottom will 'stop' only GPU applications.
After that, please be sure to check in BOINC `Activity` and set `Run based on preferences` and `Use GPU based on preferences`.

If you do all this, you should have no issues like you described above.
If you still have some questions or issues - you could find an answer here: https://boinc.berkeley.edu/wiki/Preferences
or just drop me another message.

By the way, your last message doesn't contain any information about actual crashes of BOINC. Do you still have them?

**Comment by 4e576rt8uh9ij9okp** [comment]
No since the last crash I haven't seen any crashes or errors.

**Comment by 4e576rt8uh9ij9okp** [comment]
I think I will stop using BOINC because it just eats my whole PC and I can't do anything. I also don't understand why BOINC uses the Core0 while the whole system runs on the Core0 and makes it lag, stutter, unresponsive...

**Comment by AenBleidd** [comment]
@4e576rt8uh9ij9okp, did you set your BOINC settings the way I wrote you above?

**Comment by 4e576rt8uh9ij9okp** [comment]
No, I set it my way. You don't want to run any simulations while you use your PC. I use my PC 12h while programming, that means the CPU runs at max 2%... so obviously I want to make a use of the CPU and allow BOINC to run tasks. But because BOINC is SOO GREEDY it just takes as much as it can, without leaving any gaps etc.

I have Suspend when* all unchecked... and I have enabled Suspend when non bionic CPU usage is above 20% so when I even use something else it's still OK. I don't really mind it run all the time, my issue is that it should just STOP doing tasks when I'm play games more logical solution would be to suspend when anything is in "full screen" and I could then make a exception of that so for lets say, Browser Videos, Netflix app and VLC player.

This is how I've set it up. It's on 95% and it's much better. I will try 90% maybe this will solve my issue of randomly lagging when browsing the internet etc.
![image](https://user-images.githubusercontent.com/104687522/214322534-c64a833a-41b2-4703-a545-d23e775c6f2a.png)

**Comment by AenBleidd** [comment]
@4e576rt8uh9ij9okp,

`Use at most ___% of the CPUs` -> determines how many CPU cores will be used by BOINC
`Use at most ___% of CPU time` -> determines how much time time of every core will be used by BOINC.

> I don't really mind it run all the time, my issue is that it should just STOP doing tasks when I'm play games

And you can do this my setting exclusions (please check my comment with the explanations: https://github.com/BOINC/boinc/issues/5063#issuecomment-1400432726)

> more logical solution would be to suspend when anything is in "full screen"

It would be really great to have such a functionality, and we have a ticket for that: #2301,
Unfortunately, this functionality was not implemented yet.

By the way, please update to the latest version of BOINC 7.22.0, and you will be able to set different set of preferences for ` In use` and `Not in use` mode.

**Comment by 4e576rt8uh9ij9okp** [comment]
I've already set exclusions sadly it doesn't always trigger, some games have launchers that start and then later close and open a new process with a game.

**Comment by AenBleidd** [comment]
> I've already set exclusions sadly it doesn't always trigger, some games have launchers that start and then later close and open a new process with a game.

Yes, in this case you should set real game binary, and not just the launcher.

**Comment by 4e576rt8uh9ij9okp** [comment]
> > I've already set exclusions sadly it doesn't always trigger, some games have launchers that start and then later close and open a new process with a game.
> 
> Yes, in this case you should set real game binary, and not just the launcher.

Ok and how do I fix the bigger issue, when browsing my PC is really unresponsive. Mouse laggs, yes the mouse cursor is lagging, browser is lagging to, for example I click a button and it takes like 0.5-1s till the browser reacts.
I have now almost 300k credits for the CERN Project, my issue here is that my PC is unresponsive and I will stop donating my idle CPU and electricity bill if there is no solution.
Even if I set the CPU utilization to 50% it's somehow OK... but it sometimes still stutters when the core0 hits over 95%.

I don't mind paying more monthly for the bill or donating my CPU power, but I have a issue if I have a bad time using my PC.

Tell me what to set my PC and I set it and forget it.

**Comment by AenBleidd** [comment]
@4e576rt8uh9ij9okp, IIRC, all LHC@Home applications require VirtualBox when running on Windows (please correct me if I'm wrong because I really don't remember).
VirtualBox applications are very special type of applications, they are running virtual machines instead of simple applications.
And when these Virtual Machines do checkpointing (that basically means that they save their state to the disk), it make a huge load on the hard drive, and if you don't have a really fast SSD and run more than 1 VirtualBox task - then you will really have issues while working on your PC.
In this case I suggest either to switch to another project that doesn't require Virtual Box or to suspend BOINC when PC is in use (this could be done via the BOINC Settings).

**Comment by 4e576rt8uh9ij9okp** [comment]
@AenBleidd Hi there, so I have another issue where BOINC eats my whole PC how I mentioned above. It doesn't happen always it happens randomly like once a week sometimes more sometimes less. It basically "ignores any limits" and just chews through resources. Now the CPU isn't at 100% but the RAM is at 99%. You can imagine that I can't do anything when I hit 99% RAM
Just to open file explorer I wait like 10-15s... you can forget browsing. Pausing the project doesn't do anything, as soon as it starts it's 99% RAM again.

![boinc](https://user-images.githubusercontent.com/104687522/217139299-664b23aa-1617-49e0-ab81-49c8205c0da9.png)

**Comment by Frigyes06** [comment]
> @AenBleidd Hi there, so I have another issue where BOINC eats my whole PC how I mentioned above. It doesn't happen always it happens randomly like once a week sometimes more sometimes less. It basically "ignores any limits" and just chews through resources. Now the CPU isn't at 100% but the RAM is at 99%. You can imagine that I can't do anything when I hit 99% RAM Just to open file explorer I wait like 10-15s... you can forget browsing. Pausing the project doesn't do anything, as soon as it starts it's 99% RAM again.
> 
> ![boinc](https://user-images.githubusercontent.com/104687522/217139299-664b23aa-1617-49e0-ab81-49c8205c0da9.png)

Can you send a screenshot of the expanded view of the BOINC processes? It is entirely possible that the problem exists in a project and not BOINC itself. What projects are you running?

**Comment by 4e576rt8uh9ij9okp** [comment]
> 

Hi, after a month when this screenshot was posted, you sadly can not expect me to expand this view as it's way to late to show it.
When it crashes again I will post it here.

LHC@home

**Comment by 4e576rt8uh9ij9okp** [comment]
I saw a BSOD but all i could see is that fltmgr.sys has crashed.

I'm planning to run Proxmox because Windows is such a trash OS...
