### ISSUE TITLE
[Windows] Compare installation toolsets

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#5064]
There are 3 possible candidates to be used to create new Windows Installer:
- [ ] InnoSetup: https://jrsoftware.org/isinfo.php
- [ ] NSIS: https://sourceforge.net/projects/nsis/
- [ ] WiX Toolset: https://wixtoolset.org/

It's required to compare these 3 solutions and choose one that will fit best for BOINC.

### Comparation matrix

| Requirement | InnoSetup | NSIS | WiX Toolset | 
| --- | --- | --- | --- |
| Free of charge | [:heavy_check_mark:](https://jrsoftware.org/isinfo.php) | [:heavy_check_mark:](https://nsis.sourceforge.io/License) | [:heavy_check_mark:](https://github.com/wixtoolset/wix/blob/develop/LICENSE.TXT) |
| In active development and has at least 1 release per year | [:heavy_check_mark: 2023-12-15](https://jrsoftware.org/isdl.php) | [:x: 2021-09-25](https://nsis.sourceforge.io/Download) | [:heavy_check_mark: 2023-04-06](https://github.com/wixtoolset/wix/releases) |
| Has no major security issues | [:x:](https://www.opencve.io/cve?cvss=&search=InnoSetup) | [:x:](https://www.opencve.io/cve?cvss=&search=Nullsoft+Scriptable+Install+System) | [:x:](https://www.opencve.io/cve?cvss=&search=WiXToolset) |
| Is able to create native x64 and native arm64 installers without emulation | [:x:](https://jrsoftware.org/ishelp/topic_64bitlimitations.htm) | [:x:](https://sourceforge.net/p/nsis/feature-requests/547/) | [:heavy_check_mark:](https://wixtoolset.org/docs/fourthree/faqs/#x64-and-arm64-bundles) |
| Is able to call functions from the custom dll during installation | [:heavy_check_mark:](https://jrsoftware.org/ishelp/topic_scriptdll.htm) | [:heavy_check_mark:](https://nsis.sourceforge.io/Calling_an_external_DLL_using_the_System.dll_plugin) | [:heavy_check_mark:](https://wixtoolset.org/docs/schema/wxs/customaction/) |
| Is able to generate MSI  | [:x:](https://jrsoftware.org/ishelp/topic_64bitlimitations.htm) | [:x:](https://nsis.sourceforge.io/Features) | [:heavy_check_mark:](https://wixtoolset.org/docs/about/) |
| Is able to run embedded installer (VirtualBox in our case) during installation | [:heavy_check_mark:](https://stackoverflow.com/a/20753218/4210508) | [:heavy_check_mark:](https://stackoverflow.com/a/51451829/4210508) | [:heavy_check_mark:](https://wixtoolset.org/docs/tools/burn/#chain) |
| Supports installation parameters via cli | [:heavy_check_mark:](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline) | [:heavy_check_mark:](https://nsis.sourceforge.io/Get_command_line_parameter_by_name) | [:heavy_check_mark:](https://www.oreilly.com/library/view/wix-36-a/9781782160427/ch16s11.html) |

### Legend
| Sign | Meaning |
| --- | --- |
| :heavy_check_mark: | Passed |
| :x: | Failed |

**Comment by talregev** [comment]
What is missing for this task?

**Comment by AenBleidd** [comment]
> What is missing for this task? 

Toolsets comparation and final decision which one to use

**Comment by Frigyes06** [comment]
InnoSetup: Pretty easy and straightforward for simple stuff. Doesn't appear to have command line interface to compile installer with script. Seems to be Pascal oriented?
NSIS: Widely used and supported, has a straightforward scripting language. Can compile installer from a windows command prompt.
WiX Toolset: Integrates very well with the .NET framework, especially MSBuild SDK. Can be run from the command line. Linux version exists, but is experiencing some issues. See: https://github.com/wixtoolset/issues/issues/4381/

All three tools have great documentation, although I found NSIS and WiX documentation easier to navigate and understand than InnoSetup.

In my opinion WiX Toolset would be the best for BOINC, as we use Visual Studio, and WiX is supported trough HeatWave extension.

**Comment by talregev** [comment]
> InnoSetup: Pretty easy and straightforward for simple stuff. Doesn't appear to have command line interface to compile installer with script. Seems to be Pascal oriented? NSIS: Widely used and supported, has a straightforward scripting language. Can compile installer from a windows command prompt. WiX Toolset: Integrates very well with the .NET framework, especially MSBuild SDK. Can be run from the command line. Linux support exists, but is experiencing some issues. See: [wixtoolset/issues#4381](https://github.com/wixtoolset/issues/issues/4381)
> 
> All three tools have great documentation, although I found NSIS and WiX documentation easier to navigate and understand than InnoSetup.
> 
> In my opinion WiX Toolset would be the best for BOINC, as we use Visual Studio, and WiX is supported trough HeatWave extension.

Preferable tool that can compile and create on the ci. 
If you have some examples, that will be great.

**Comment by Frigyes06** [comment]
I can try to craft up examples. Not today though. Would you like one for each or just for WiX? I'm not sure if InnoSetup is CI compatible at all :)

**Comment by AenBleidd** [comment]
@Frigyes06, thank you for the input.
Please hold on with this ticket.
There are some more requirements that should be met to choose any particular toolset.

Yes, I have a simple sample of NSIS but I doubt we will use it.

@talregev, all three toolsets could be built on ci.

**Comment by talregev** [comment]
> There are some more requirements that should be met to choose any particular toolset.

Can you specify all the requirements for toolset?

**Comment by AenBleidd** [comment]
> Can you specify all the requirements for the toolset?

I don't have a complete list of requirements for now, so when I have it - I update this ticket.
I have no time yet to research and have a clear understanding which requirements are important and which are not.

**Comment by AenBleidd** [comment]
Ok, requirements are there. I hope I didn't forget anything important.
If someone decides to work on this ticket, please don't forget to put a link that proofs every ✔️ and/or ❌. In the best case this should be a link to the documentation section (or a quote from it with the link to the page if it's not possible to put a direct link to the documentation section).

**Comment by talregev** [comment]
@AenBleidd Thank you. Please also put issue that we want to solve that the new installer should hold.
For example, this issue: #5118

@Frigyes06 Are you interesting to do this research?

**Comment by AenBleidd** [comment]
> @AenBleidd Thank you. Please also put issues that we want to solve that the new installer should hold. For example, this issue: #5118 

Please check #5066

**Comment by talregev** [comment]
> > @AenBleidd Thank you. Please also put issues that we want to solve that the new installer should hold. For example, this issue: #5118
> 
> Please check #5066

I see you include #5118 as almost the last in this long list. This issue need to investigated in the research part, and not in the end. Also we need more issue like it that are important to boinc. Please make that list. Thank you.

**Comment by AenBleidd** [comment]
> I see you include #5118 as almost the last in this long list. 

These issues are not ordered. This is just a list. Last doesn't mean has less importance.

> This issue need to investigated in the research part, and not in the end. 

In any case this is not a top priority issue. Also, it's actually not related to the installer script itself but to the custom dll that is run from the installer. And since it's currently not known whether we will keep existing dll or completely replace it (in case the new installation toolset won't be able to call functions from the dll during installation and this is the only disadvantage of it).

> Also we need more issues like it that are important to boinc. Please make that list. Thank you.

This list is already in #5066. Everything else could be added later while working on the new installer.
We try to stick to the agile, not to the waterfall, so we don't require all tickets to be created and discussed before start working on the topic.

As you understand, the prio one task is to convert existing installation script to the new toolset keeping all or almost all existing functionality. We have no outdated settings there, so we need to preserve them all for smooth user experience: in the best case user should not mention that they are running a new installer.

**Comment by talregev** [comment]
> > I see you include #5118 as almost the last in this long list.
> 
> These issues are not ordered. This is just a list. Last doesn't mean has less importance.
> 
> > This issue need to investigated in the research part, and not in the end.
> 
> In any case this is not a top priority issue. Also, it's actually not related to the installer script itself but to the custom dll that is run from the installer. And since it's currently not known whether we will keep existing dll or completely replace it (in case the new installation toolset won't be able to call functions from the dll during installation and this is the only disadvantage of it).
> 
> > Also we need more issues like it that are important to boinc. Please make that list. Thank you.
> 
> This list is already in #5066. Everything else could be added later while working on the new installer. We try to stick to the agile, not to the waterfall, so we don't require all tickets to be created and discussed before start working on the topic.
> 
> As you understand, the prio one task is to convert existing installation script to the new toolset keeping all or almost all existing functionality. We have no outdated settings there, so we need to preserve them all for smooth user experience: in the best case user should not mention that they are running a new installer.

You didn't explain why we don't need to make an effort and invest time in research to see if new installer will solve the known bug.
Even if this task is low priority it doesn't mean that we don't need to do it in professional way. 

> Everything else could be added later while working on the new installer.

Try to fix know bug after you choose a installer it much harder. This is not connected to agile or waterfall. In both system you need invest time to choose the right tool for the job. Known issues is a great starting point.

**Comment by AenBleidd** [comment]
> You didn't explain why we don't need to make an effort and invest time in research to see if new installer will solve the known bug. Even if this task is low priority it doesn't mean that we don't need to do it in professional way.

> Try to fix know bug after you choose a installer it much harder. This is not connected to agile or waterfall. In both system you need invest time to choose the right tool for the job. Known issues is a great starting point.

Because this issue is not related to the installer. And while choosing the proper toolset you should not consider existing bugs in existing installer but rather stick to the general requirements that are listed in the first comment.
This existing bug could be solved even in the old installer, but since we plan to move to the new one, I see no reason to invest any time trying top fixing it now.
And it will take exactly the same time to fix it in the new installer (maybe even during the development phase and not as a separate ticket) as in the old one.
You want to investigate existing issues - go ahead.
But when you develop something new to replace something existing - you should forget about existing issues and focus on the new functionality / new architecture / new UI/UX / etc.
This is a basic principle of software designing.

**Comment by talregev** [comment]
> Because this issue is not related to the installer.

I am talking to add similar known bugs that important to this issue, not this issue itself. 

> You want to investigate existing issues - go ahead

You are the maintainer of this repo. You are know better than me what is important to boinc. Also you are the one that go all over the issues and categorize it. You know better then anyone whats issues are good to investigated to this research and  you should add them.

**Comment by AenBleidd** [comment]
> I am talking to add similar known bugs that important for the research , not this issue itself.

All these issues are listed in #5066.
Yes, it's possible that I missed some related tickets, and I'll recheck this once, but currently while doing research for the new installation toolset you should consider only requirements, and not existing issues. Reasons are already explained above.

**Comment by talregev** [comment]
> > I am talking to add similar known bugs that important for the research , not this issue itself.
> 
> All these issues are listed in #5066. Yes, it's possible that I missed some related tickets, and I'll recheck this once, but currently while doing research for the new installation toolset you should consider only requirements, and not existing issues. Reasons are already explained above.

This is mixed from task that need to do with some known issue. I recognize only one. That why we should only the known issue.
If all of them are in #5006, you should add them to here to be more clear.

**Comment by AenBleidd** [comment]
> If all of them are in #5006, you should add them to here to be more clear.

Ok, I'll repeat this the third time: while doing research to choose new installation toolset you should stick to the **requirements only** and forget about **existing** issues of the **current** installer. Is that clear?

**Comment by talregev** [comment]
> > If all of them are in #5006, you should add them to here to be more clear.
> 
> Ok, I'll repeat this the third time: while doing research to choose new installation toolset you should stick to the **requirements only** and forget about **existing** issues of the **current** installer. Is that clear?

I already explain why is it important to have also research the known issues for the new installer. You are proposing non professional way.

**Comment by Frigyes06** [comment]
> @AenBleidd Thank you. Please also put issues that we want to solve that the new installer should hold.
> For example, this issue: #5118
> 
> @Frigyes06 Are you interesting to do this research? 

Yeah, I can do this. I estimate it will be done by wednesday.

**Comment by AenBleidd** [comment]
> I already explain why is it important to have also research the known issues for the new installer. 

If you want - you're free to do that.

> You are proposing non professional way.

This is your personal opinion. If you want to do this task your way - I can't stop you from doing that.

For me to make a decision about the next toolset we will use for BOINC - is to met requirements I listed in the first message.
All other issues will be solved during the development because they are not related to the chosen toolkit but just a bugs in the existing implementation. And even more: these are just bugs in **our** code, not something that exists in the toolset itself.

**Comment by talregev** [comment]
> > @AenBleidd Thank you. Please also put issues that we want to solve that the new installer should hold.
> > For example, this issue: #5118
> > @Frigyes06 Are you interesting to do this research?
> 
> Yeah, I can do this. I estimate it will be done by wednesday.

Thank you!

**Comment by AenBleidd** [comment]
> Yeah, I can do this. I estimate it will be done by wednesday.

Take your time: sometimes it's better to spend more time to make the best decision

**Comment by tristanolive** [comment]
It might not be a hard requirement, but InstallShield is set up to digitally sign the executables included in the installer (boinc.exe, boincmgr.exe, etc). Worst case, this could probably be scripted independently, but it would be nice if the toolset included some level of integration.

Otherwise, I think the list of requirements looks pretty good. I'll be glad to take part in some testing of toolsets once we get there. I build some custom installers for account managers, but generally they don't stray too far from following the standard BOINC process.

**Comment by AenBleidd** [comment]
Executables inside installer are already signed with Visual Studio.
That is why this is not a part of the requirements list.

@tristanolive, I'll let you know when we have something to test. Thank you for your help.

**Comment by tristanolive** [comment]
Right you are, InstallShield only signs the additional files that it is producing. I'm not sure what the purpose would be of some of that; files such as "D.tmp" or "certificate.msi". The final step of signing the installer itself would still be significant, but that is easy to do manually. Thanks for setting the details straight!

**Comment by AenBleidd** [comment]
According to the comparation table, the best tool to use is `WiX Toolset`: https://wixtoolset.org/
