### ISSUE TITLE
Potential SQL Injection Vulnerability in Default BOINC Website

### ISSUE THREAD

**Issue by thomasdonlon** [BOINC/boinc#5081]
I'm a developer for MilkyWay@home, and our project recently failed a routine vulnerability scan from our host institution. The potential vulnerability comes from the "next_url" parameter in the BOINC website file "create_account_form.php" (link to the relevant code on github here https://github.com/BOINC/boinc/blob/master/html/user/create_account_form.php).

From what I understand, the vulnerability is this: if you put something in the website url after "create_account_form.php", like "create_account_form.php?next_url=1", then the page reloads but everything after the ? persists in the url. I'm told that this is difficult but not impossible to utilize for a SQL injection attack. Here's the full report that we got from our routine vulnerability scan:

```
Using the GET HTTP method, Nessus found that :

+ The following resources may be vulnerable to blind SQL injection :

+ The 'next_url' parameter of the /milkyway/create_account_form.php CGI :

/milkyway/create_account_form.php?next_url='+and+'b'>'a

-------- output --------
<p class="lead">If you already have an account and want to run Mil [...]
    <div class="container">
        <form class="form-horizontal" method="post" action="create_accou
nt_action.php"><input type="hidden" name="next_url" value="">
    
        <div class="form-group">
-------- vs --------
<p class="lead">If you already have an account and want to run Mil [...]
    <div class="container">
        <form class="form-horizontal" method="post" action="create_accou
nt_action.php"><input type="hidden" name="next_url" value="' and 'b'>'a"
>
    
        <div class="form-group">
------------------------
```

This looks like the scan was able to access unintended php source code for this webpage via the url line.

We would like to fix this issue so that it isn't a problem in the future. However, I don't have any experience with this sort of thing, and I was wondering if any of you who knew more could help us out. Additionally, we wanted to bring it to your attention so that the BOINC website code could get fixed, so that other people don't experience any issues from this in the future.

It looks like the BOINC code tries to sanitize the "next_url" parameter with the function "sanitize_local_url" in https://github.com/BOINC/boinc/blob/master/html/inc/util.inc. Maybe this sanitize function can be changed in some way to prevent this problem? Or maybe there's a better fix. 

I also posted about this on the boinc forums [here](https://boinc.berkeley.edu/forum_thread.php?id=14904&postid=110987#110987) but they recommended that I post the issue here instead.

Let me know if you'd like any more information about the issue and I'm happy to share.

**Comment by AenBleidd** [comment]
@thomasdonlon, thank you for the report.
@davidpanderson, @lfield, could you please check this?

**Comment by davidpanderson** [comment]
I can't see how this is a SQL injection vulnerability,
or a way to see PHP code (HTML is not PHP)
or any other vulnerability.
Am I missing something?
