### ISSUE TITLE
Create self-extracted linux shell script to install BOINC Client and BOINC Manager

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#5094]
It is necessary to have self-extracted linux shell script to install vanilla BOINC Client and BOINC Manager.
Requirements:
- [ ] Two scripts are required: x64 and ARM64
- [ ] Should contain BOINC Client, BOINC CLI (boinccmd) and BOINC Manager.
- [ ] User should be able to choose what to install (via parameters or by simple cli ui), BOINC Client (boinc & boinccmd) and/or BOINC Manager (boincmgr).
- [ ] All binaries should be built with libc statically linked
- [ ] Should extract all necessary files to the default location or to the location set by user (via command line or simple cli ui)
- [ ] Should set all necessary permissions, create group and add user to this group if needed
- [ ] Should be able to set autorun on system startup (systemctl)
- [ ] Should work on at least on Debian/Ubuntu
- [ ] This script should be automatically created on CI

**Comment by davidpanderson** [comment]
I suggest that this be as simple as possible: perhaps just a zip file containing
- the client, boinccmd, and manager
- a README with instructions for how to run the client at boot,
  and how to make it run as a separate user account
  (or better yet, links to web pages with these instructions)

**Comment by AenBleidd** [comment]
Closing this is favor of #5151
