### ISSUE TITLE
Boinc unable to detect rend.exe from Sheepit for exclusive application

### ISSUE THREAD

**Issue by hucker75** [BOINC/boinc#5097]
**Describe the bug**
I'm trying to get Boinc to pause while rend.exe from Sheepit is running, as the two running together makes the PC extremely unresponsive.  Although Boinc detects other programs like games ok, it will not detect this one.

**Steps To Reproduce**
1. Tell Boinc of the exclusive application rend.exe
2. Install and run Sheepit while Boinc is using all CPU cores.
3. Wait for Sheepit to run a render frame.

**Expected behavior**
Boinc should pause, but it does not, and the computer locks up until the render frame is finished (usually a few minutes).

**System Information**
 - OS: Windows 11
 - BOINC Version: 7.20.2

**Comment by AenBleidd** [comment]
BOINC usually not able to detect processes that run less than 1 second, so if this your case, and 'rend.exe' application runs like for every frame and takes usually less that 1 second until finished - it won't be detected by BOINC.
In this case u suggest to add to exclusive applications main application of Sheepit software.

**Comment by hucker75** [comment]
Please delete this issue and accept my apologies, I had Boinc set to run always instead of as preferences!  I forgot about that setting.

**Comment by hucker75** [comment]
On second thoughts, one little tweak that would help - allow Boinc to pause only the CPU, and still use the GPU.

**Comment by AenBleidd** [comment]
> One little tweak that would help - allow Boinc to pause only the CPU, and still use the GPU. I don't want it to pause the GPU, as Sheepit doesn't use that. But I need it to pause the CPU, or both running at once slows the GPU tasks in Boinc.

GPU tasks usually use some amount of CPU core time as well, so this is not the option

**Comment by hucker75** [comment]
Some amount.  But not much.  Things like Sheepit need the CPU, but not the GPU.  The odd core to help the GPU is negligible.

Just as you have the option for GPU off only for games, even though the game does use a bit of CPU.

**Comment by RichardHaselgrove** [comment]
For once, I agree with Peter. In this era of multi-core CPUs, "a GPU app needs some CPU" is an excuse, not a reason.
