### ISSUE TITLE
BOINC Linux Download Page is confusing

### ISSUE THREAD

**Issue by makeasnek** [BOINC/boinc#5129]
**Describe the bug**
The BOINC download page (https://boinc.berkeley.edu/download.php) for Linux is giving users information that IMO is incorrect. The big green "download BOINC" button links to the Berkeley installer but my understanding is that this installer is only suggested if user's don't have a package manager as the next line says, in smaller text, "We recommend that instead you[ install BOINC using a package manager, run it using Docker, or use a bootable ISO image". Most Linux users are using an OS that comes with a package manager, that should be the default option represented in the big green button, especially since package manager will automatically update BOINC if a security release is issued.

I am not aware if the packages in the Debian or Ubuntu repos currently work, I know the PPA doesn't work with Mint and I suspect Ubuntu as well, so until that is fixed that option should be removed as it doesn't work out of the box.  (see https://github.com/BOINC/boinc/issues/5124)

**Suggested Resolution**

- Big green button should link to https://boinc.berkeley.edu/wiki/Installing_BOINC#Linux
- Otherwise make it clear which is the suggested and best supported option for Linux users, depending on their distro
- Install on Ubuntu page should be updated to use apt instead of aptitude, I believe aptitude is deprecated https://boinc.berkeley.edu/wiki/Installing_BOINC_on_Ubuntu
- Suggest language change "To install BOINC on Ubuntu, type: " -> "To install BOINC on Ubuntu, type the following commands in the terminal: " with each command being on a separate line so users unfamiliar with apt do not think it is a single command
- Synaptic package manager is no longer installed by default on Ubuntu, so should be removed
- Potentially include boinc-client-opencl boinc-client-nvidia-cuda as suggested packages to install. My understanding is that they won't harm anything if installed and un-needed, but may be otherwise critical for BOINC to use the GPU. Users may not know which GPU they have.

**Comment by Aurum420** [comment]
I'm trying to upgrade Linux computers but have yet to figure out how. Seems BOINC folks have changed a lot of the way they do things but haven't updated links and instructions. E.g.,

From this page https://boinc.berkeley.edu/

BOINC client 7.20.2 released
A new version of the client has been released for Windows and Mac OS. Download it [here](https://boinc.berkeley.edu/download.php). Release notes are here. 27 Jul 2022

goes to this page https://boinc.berkeley.edu/download_all.php which is stops at 7.16.6.

From https://wiki.debian.org/BOINC is old too:

aurum@B-4:~$ sudo apt-get install boinc-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
boinc-client is already the newest version (7.16.6+dfsg-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

aurum@B-4:~$ sudo apt-get upgrade boinc-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
boinc-client is already the newest version (7.16.6+dfsg-1).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

I found 7.20.2 at https://github.com/BOINC/boinc/releases but it unzips to a set of pdb files with no instructions how to actually upgrade BOINC client. Tried the Linux Synaptic Package Manager but it reinstalled 7.16.6.

**Comment by AenBleidd** [comment]
@Aurum420, currently you should install BOINC on Linux from this PPA: https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/boinc

**Comment by davidpanderson** [comment]
Another problem is that the "autoattach" mechanism (used by Science United and maybe some projects) routes installer downloads through a script that changes the filename to including account info.  This works for Win and Mac (where the installers are served from the BOINC server) but not for Linux.

**Comment by AenBleidd** [comment]
I believe, if we make this ( https://github.com/BOINC/boinc/issues/5094 ) we might be able to enable 'autoattach' feature there as well.
I'll open a separate ticket for that.

**Comment by makeasnek** [comment]
So it looks like this bug will be fixed when the new deb is released, but until then can a warning or something be added to the download page so users don't download a broken package? Maybe something like "PPA package is currently broken, please install from your distribution's repository"? (relevant: https://github.com/BOINC/boinc/issues/5124)

**Comment by makeasnek** [comment]
Download link is still pointing me to sh installer?

**Comment by AenBleidd** [comment]
Hopefully soon we will have an updated installer

**Comment by davidpanderson** [comment]
Which download link?
https://boinc.berkeley.edu/download.php
should now direct the user to
https://boinc.berkeley.edu/wiki/Installing_on_Linux
... which advises them to use a package manager.

The download link on project web sites will do the same thing
once they update their PHP code with this PR.
I've done this on Science United, and it seems to work correctly.

**Comment by makeasnek** [comment]
On https://boinc.berkeley.edu/download.php the big green button is still linking me to https://boinc.berkeley.edu/dl/boinc_7.4.22_x86_64-pc-linux-gnu.sh

I tried refreshing the page in case it was a cache thing, maybe there's a server-side cache that is serving up the old page or something?

**Comment by makeasnek** [comment]
Just noticed the images of the boinc client change each time, fun little feature!

**Comment by davidpanderson** [comment]
Oops!!  My bad.  Should work now.

**Comment by makeasnek** [comment]
Works now :)

**Comment by dpapakonstantis** [comment]
Newbie alert !

following the instructions from

https://boinc.berkeley.edu/wiki/Installing_BOINC_on_Debian_or_Ubuntu

after the step:
sudo apt install boinc

i get the following message 


"```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 boinc-client : Depends: libboinc7 (= 7.18.1+dfsg-4) but 7.20.5+dfsg+202212021500~ubuntu22.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```"


any ideas?

thanks

D

**Comment by Aurum420** [comment]
Try adding the repository either in Software Sources:
ppa:costamagnagianfranco/boinc
Or from the command line 
sudo add-apt-repository ppa:costamagnagianfranco/boinc

**Comment by dpapakonstantis** [comment]
it works!
many thanks :)

**Comment by dpapakonstantis** [comment]
it looks like it's working but, not long after, it crashes
