### ISSUE TITLE
boinccmd --get_tasks simpler formatting

### ISSUE THREAD

**Issue by bdwyer2** [BOINC/boinc#5130]
**Describe the problem**
I would like to easily be able to see a list of running tasks with 1 line per task

**Describe the solution you'd like**
Maybe an additional command like `--get_tasks_list` that returns something like this:

```
$ boinccmd --get_tasks_list
WU Name ------- Deadline ----------- State ----------- % Done
wu_1234567 ---- 1/1/1/ 11:11:11 ---- Uploading ------- 100%
wu_7890123 ---- 1/1/1/ 11:11:11 ---- Executing ------- 90%
wu_4567890 ---- 1/1/1/ 11:11:11 ---- Executing ------- 50%
wu_1234567 ---- 1/1/1/ 11:11:11 ---- Pending --------- 0%
```

**Comment by computezrmle** [comment]
CLI output is often parsed within scripts.
Please, no format change just to make it look "nicer".

**Comment by bdwyer2** [comment]
> CLI output is often parsed within scripts. Please, no format change just to make it look "nicer".

I proposed adding a new CLI option `--get_tasks_list`, not changing the output of `--get_tasks`

**Comment by davidpanderson** [comment]
Great idea.  I'll add this either as a new command or an option to --get_tasks

**Comment by davidpanderson** [comment]
Here's what I have so far.  Suggestions?
```
> boinccmd --get_task_summary
Project        % Done  Elapsed   Deadline              Status     Procs  WU name
Einstein@Home  13.53%  03:03:03  25-May-2020 20:21:40  executing  1 CPU  LATeah1020F_792.0_138060_0.0
Einstein@Home  13.55%  03:01:14  25-May-2020 20:22:45  executing  1 CPU  LATeah1020F_792.0_139476_0.0
Einstein@Home  13.53%  03:03:36  25-May-2020 20:22:45  executing  1 CPU  LATeah1020F_792.0_139535_0.0
Einstein@Home  13.61%  03:10:25  25-May-2020 20:22:44  executing  1 CPU  LATeah1020F_824.0_49619_0.0
Einstein@Home  13.59%  03:01:31  25-May-2020 20:22:44  executing  1 CPU  LATeah1020F_792.0_139948_0.0
Einstein@Home  13.55%  03:09:22  25-May-2020 20:22:44  executing  1 CPU  LATeah1020F_824.0_49442_0.0
Einstein@Home  13.61%  03:10:11  25-May-2020 20:22:45  executing  1 CPU  LATeah1020F_792.0_138591_0.0
Einstein@Home  13.59%  03:01:15  25-May-2020 20:22:45  executing  1 CPU  LATeah1020F_792.0_140184_0.0
```

**Comment by bdwyer2** [comment]
> Here's what I have so far. Suggestions?
> 
> ```
> > boinccmd --get_task_summary
> Project        % Done  Elapsed   Deadline              Status     Procs  WU name
> Einstein@Home  13.53%  03:03:03  25-May-2020 20:21:40  executing  1 CPU  LATeah1020F_792.0_138060_0.0
> Einstein@Home  13.55%  03:01:14  25-May-2020 20:22:45  executing  1 CPU  LATeah1020F_792.0_139476_0.0
> Einstein@Home  13.53%  03:03:36  25-May-2020 20:22:45  executing  1 CPU  LATeah1020F_792.0_139535_0.0
> Einstein@Home  13.61%  03:10:25  25-May-2020 20:22:44  executing  1 CPU  LATeah1020F_824.0_49619_0.0
> Einstein@Home  13.59%  03:01:31  25-May-2020 20:22:44  executing  1 CPU  LATeah1020F_792.0_139948_0.0
> Einstein@Home  13.55%  03:09:22  25-May-2020 20:22:44  executing  1 CPU  LATeah1020F_824.0_49442_0.0
> Einstein@Home  13.61%  03:10:11  25-May-2020 20:22:45  executing  1 CPU  LATeah1020F_792.0_138591_0.0
> Einstein@Home  13.59%  03:01:15  25-May-2020 20:22:45  executing  1 CPU  LATeah1020F_792.0_140184_0.0
> ```

Looks great!

Maybe the deadline isn't necessary here?

What happens to the `Procs` column if the task requires a GPU? Does that make this too long?

**Comment by davidpanderson** [comment]
with a GPU it would say e.g. ".2 CPU and 1 NVIDIA GPU".
That would make it kind of long, but I think it's important to show that info.

**Comment by bdwyer2** [comment]
Understood. Maybe in the future you could specify which fields you want to see.

Eg `boinccmd --get_task_summary -O "Project,Pct_Done,Status"`

**Comment by davidpanderson** [comment]
I added optional column selectors:

```
 --get_task_summary [pcedsrw]       show tasks (1 line per task)
    p: project name
    c: completion %
    e: elapsed time
    d: deadline
    s: statue
    r: resource usage
    w: WU name
```
