### ISSUE TITLE
Boinc client and manger crash when remove all projects in boinc manager. 

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#5138]
**Describe the bug**

OS windows 11.

**Steps To Reproduce**
1.  Add 4 projects  (Einstein, WCG, WUprop, Rosetta) with account manager (BAM).
3.  Let them download all and start crunch. 
4.  Stop using account manager.
5. Select all projects 
6. Push on remove and remove them all by once. 

**Expected behavior**

All projects should removed and client and manager shouldn't crash. 

**Screenshots**

**System Information**
 - OS:  windows 11
 - BOINC Version:  7.23

**Additional context**

**Comment by davidpanderson** [comment]
I was unable to repro this (Win 10, master branch).  Anyone else see it?

**Comment by AenBleidd** [comment]
On Win11 there are some breaking changes in several internal libraries.
I'll try to reproduce this later this week.

**Comment by talregev** [comment]
@davidpanderson I did it with account manager. Also need to remove them all at once. no one by one. I will update the issue.

**Comment by talregev** [comment]
@davidpanderson If you are reading this, I would like to talk. I finished to develop gui rpc with WebSocket for Windows and Linux.

**Comment by AenBleidd** [comment]
@talregev, websockets implentation is not a trivial change, and you should discuss it **before** starting any implementation.
Please open a PR to start discussion there, since this ticket has nothing similar with websockets.

**Comment by davidpanderson** [comment]
Tal, I'd be happy to talk; email me to set it up.

Re websockets: people from CERN started down this road a few years ago to enable browser-based GUIs for BOINC.  They abandoned the idea when I added support for GUI RPCs over HTTP, which accomplishes the same goal.

**Comment by AenBleidd** [comment]
@talregev, as I said already, I'll try to reproduce this. Meanwhile, if you have this issue reproducible constantly, it would be nice if you attach crashdump to this ticket (and also PDBs since you probably built this by yourself).
Thank you in advance

**Comment by AenBleidd** [comment]
Ok, I just tried to reproduce this with the latest build from master but for me it was working fine, I have no crash.
@talregev, please attach crashdump and PDB files (otherwise crashdump will be mostly useless) to this ticket.
Thank you in advance.

**Comment by davidpanderson** [comment]
BTW, when you're using an account manager, the GUI doesn't let you remove projects that were added by it.  In my test, I used Science United; it attached 3 projects. I stopped using SU, then selected all the projects and removed them.  They got removed one at a time; nothing crashed.

**Comment by talregev** [comment]
I am put this issue on hold. If you are not able to reproduce, We can set this issue on draft until I will provide more information. 
@davidpanderson I did the same as you. Also added wcg that is not working for now. Maybe it one of the reason? But I will leave this issue for now.

**Comment by AenBleidd** [comment]
> I am put this issue on hold. If you are not able to reproduce, We can set this issue on draft until I will provide more information. 

There is no way to put issue on hold or make it draft, so I'll keep 'Validate' label for a while.

> I did the same as you. just with BAM. Also added wcg that is not working for now. Maybe it one of the reason?

I don't think it depends on project but it's hard to say for sure.
Also, I don't believe scenario you described is commonly used, so we can definitely wait until you are be able to provide crash dumps.
BTW, if you don't know how to setup post mortem debugger (to catch any crash and save crash dump), here's a good article: https://www.atmosera.com/blog/procdump-post-mortem-switches-order-matters/

**Comment by talregev** [comment]
fixed in #5189
