### ISSUE TITLE
Remoting to Android Boinc only lasts an hour or so

### ISSUE THREAD

**Issue by hucker75** [BOINC/boinc#5145]
**Describe the bug**
Connecting to an Android Boinc with either Boinctasks or Boinc Manager suddenly stops working after about an hour or so.  Restart it and it's ok again.

**Steps To Reproduce**
1. Run Boinc official client on Android (11) and have tasks running.
2. Allow remote connections.
3. Connect from a Windows (11) PC with either Boinc Manager or Boinctasks.
4. After an hour or two, it will lose connection, but it's still computing ok.
5. Reboot Android device and it works again.

**System Information**
 - OS: Android 11 and Windows 11
 - BOINC Version: Android 7.18.1 and Windows 7.20.2, Boinctasks version 1.90.

**Comment by AenBleidd** [comment]
Thanks for the report.

Could you please answer next questions to help reproduce this? Thank you in advance

- Do you have Android BOINC running on the foreground on the phone?
- Do you have Android BOINC in battery optimization exceptions?
- Do you have Android device screen on or off?
- Do you have Android device connected to charger or not?

**Comment by hucker75** [comment]
Yes, I usually have it open in the foreground, although I do make calls etc so it's not always there.  I also lock the screen which turns the screen off, but neither of those stop it immediately.  I even tried "closing" Boinc's window (no idea how I'm meant to close Boinc completely, I'm not overly familiar with Android, and there's no exit command in the menu).  When I unplug it (it's usually on charge), Boinc is set to snooze, but I just tried unplugging and replugging it, and the connection stayed open, and I saw it pause and resume all the tasks.

Boinc prefs tell it to pause if battery is below 50% or the power is disconnected, and sometimes the battery can go below 50% as the charger isn't very powerful.  I looked in battery optimisation, and Boinc was on, I'll try turning that off.  Maybe it was up to something when the battery got lower.

**Comment by hucker75** [comment]
The change you suggested has worked, thanks.  Boinc needs battery optimization turned off.  I wonder if the installer could ask the user to do that?  I've had other apps request me to do things, and open the relevant system setting for me to authorize.

**Comment by AenBleidd** [comment]
There is a ticket #4420 to implement this functionality.
