### ISSUE TITLE
Task descendants can be calculated incorrectly due to PID recycling on Windows

### ISSUE THREAD

**Issue by BrianNixon** [BOINC/boinc#5152]
Windows [readily](https://devblogs.microsoft.com/oldnewthing/20110106-00/?p=11813 "Old New Thing") recycles process IDs, and does not update a running process’s ‘parent PID’ when its parent exits. This can lead to the situation where BOINC thinks that unrelated processes are descendants of tasks it is managing, which causes trouble in two ways:

1. When a task is killed, `kill_descendants()` kills things it shouldn’t.
_Example:_ At logon, `userinit.exe` (PID 1000) launches `explorer.exe` (PID 1234), then exits. Some time later, a BOINC task happens to receive PID 1000. Killing that task also kills Explorer.

2. CPU time is calculated incorrectly, which can prevent checkpointing from working properly.
_Example:_ At startup, `boinc.exe` (PID 2000) spawns itself (creating PID 2345) and exits to return control to the invoking console. Some time later, a BOINC task happens to receive PID 2000. Computing that task’s CPU time counts the CPU time of all descendants of the BOINC client, which could be a huge value. As tasks finish, subsequent calculations happen to compute a smaller CPU time for PID 2000, but these are never applied (because of the check in `TASK::cpu_time()` in the wrapper), meaning `checkpoint_cpu_time` appears not to change, which prevents the task state file getting created/​updated in `ACTIVE_TASK_SET::get_msgs()`.

One possible fix might be to consider process creation time when building the process tree, and only allowing parent-child relationships to be established where the child is younger than the parent. (Though this could break if time goes backwards due to clock correction.)

**Comment by davidpanderson** [comment]
Wow!  Thanks for noticing this.  I'll implement the fix you suggest.

Am I correct in thinking that this problem doesn't exist on Unix/Mac
because a process that exits while children exist becomes a zombie
(and its PID is not reused)?

**Comment by CharlieFenton** [comment]
> Am I correct in thinking that this problem doesn't exist on Unix/Mac
because a process that exits while children exist becomes a zombie
(and its PID is not reused)?

As far as I know, that is correct on the Mac (which is UNIX under the hood.) I know for sure that PIDs are not reused for a long time on the Mac. I know that exited tasks (typically project executables) disappear from the list in Apple's _Activity Monitor_, but I've never checked to see whether they remain as zombies.

**Comment by BrianNixon** [comment]
> Am I correct in thinking that this problem doesn't exist on Unix/Mac
> because a process that exits while children exist becomes a zombie
> (and its PID is not reused)?

On reflection, the bug title is a little misleading: it’s not so much the PID recycling/​reuse that’s the issue, it’s the lack of re-parenting of orphan processes on Windows, meaning that a process can appear to be a child of something nonexistent or unrelated.

On Unixy systems, orphaned processes always get adopted (traditionally by PID 1/​`init`, though it’s [much more complicated](https://unix.stackexchange.com/a/177361) than that these days). Those systems will recycle PIDs sooner or later, but that’s not an issue for BOINC because the adoptive parent is still running.

(Also, just for ~nitpicking~ clarity in terminology: a _zombie_ process is something slightly different: that’s a process that has `exit()`ed but whose [possibly adoptive] parent has yet to `wait()` for it.)

**Comment by BrianNixon** [comment]
> Am I correct in thinking that this problem doesn't exist on Unix/Mac
> because a process that exits while children exist becomes a zombie
> (and its PID is not reused)?

On reflection, the bug title is a little misleading: it’s not so much the PID recycling/​reuse that’s the issue, it’s the lack of re-parenting of orphan processes on Windows, meaning that a process can appear to be a child of something nonexistent or unrelated.

On Unixy systems, orphaned processes always get adopted (traditionally by PID 1/​`init`, though it’s [much more complicated](https://unix.stackexchange.com/a/177361) than that these days). Those systems will recycle PIDs sooner or later, but that’s not an issue for BOINC because the adoptive parent is still running.

(Also, just for ~nitpicking~ clarity in terminology: a _zombie_ process is something slightly different: that’s a process that has `exit()`ed but whose [possibly adoptive] parent has yet to `wait()` for it.)

**Comment by davidpanderson** [comment]
Dang!  I somehow forgot what zombie meant.  Brian, are you at U of Pitt?  Email me sometime - davea at berkeley dot edu
