### ISSUE TITLE
App checkpoints can be missed on Windows

### ISSUE THREAD

**Issue by BrianNixon** [BOINC/boinc#5154]
This might be more an app bug than a BOINC issue, but after it came up [at SiDock​@home](https://www.sidock.si/sidock/forum_thread.php?id=225&postid=2008#2008) I thought I’d mention it here…

The wrapper detects checkpoints in `TASK::has_checkpointed()` by polling the last-modification time of the file written by the app. On Windows, this is not a reliable IPC mechanism because of the way [writing to files](https://learn.microsoft.com/windows/win32/api/fileapi/nf-fileapi-writefile) works:
> the last write time is not fully updated until all handles used for writing have been closed.

In the SiDock case, the app writes the checkpoint to the file but keeps the handle open to reuse for the next checkpoint. So there’s an argument that this is not a proper checkpoint. The symptom is that even though the app does correctly checkpoint and resume, BOINC’s elapsed time resets to zero every time the task is stopped and restarted (because its task state file never gets created).

The reliable way for the wrapper to work would be to read the entire file, checksum the content, and compare checksums rather than timestamps. But that could add substantial overhead (since the state file is under the control of the application, and could be huge).

**Comment by davidpanderson** [comment]
Let's leave it the way it is, and tell SiDock to close the file, and change the wrapper doc to say this.

**Comment by AenBleidd** [comment]
I'll tell SiDock folks about this issue
