### ISSUE TITLE
Get rid of verify_files_on_app_start

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#5165]
This is a project flag (in config.xml, send in scheduler replies) that tells the client to verify
the MD5 of all files (executable and input) prior to starting each job.

If files are big (e.g. VM images) this produces a big burst of disk I/O.
Disk I/O isn't prioritized so this can cause the system to become unresponsive.
Also, it's synchronous (the client doesn't overlap it with RPCs)
so the BOINC Manager shows a "communicating with client" while it's happening.

The file check doesn't accomplish anything.
Apparently people thought it would prevent users from maliciously replacing project executables.
But it doesn't do this.
Users can substitute whatever file they want, and modify client_state.xml to change
the nbytes and md5_cksum.

So let's just get rid of it.

**Comment by AenBleidd** [comment]
I don't agree: this also helps to identify download errors or partial downloads and do not process corrupted files.

**Comment by davidpanderson** [comment]
Files are verified after download.
That's not what I'm talking about.
I'm talking about a check done before each time a job is started.

**Comment by AenBleidd** [comment]
Ah, pardon. Then I'm ok with this change

**Comment by davidpanderson** [comment]
Some notes on the general issue, and the proposed change:
-------------------------------
Ensuring the integrity of downloaded project files (task input, app version)

BOINC takes various measures to ensure that, when a task runs,
its executable and input files are what the project originally provided.
There are various possible sources of inconsistency:

1) The server's copy of the file is changed somehow
    (by hackers, or accidentally)
2) Errors in file transfer
    Note: AFAIK this has never happened;
    TCP is a reliable transport protocol.
3) The client's copy of the file is deleted or truncated
    while the client is not running
4) The client's copy of the file is deleted or truncated
    while the client is running
5) The client's copy of the file is modified
    Note: detecting intentional modifications to a file is impossible.
    Whoever modifies a file can also change its size and MD5 fields
    in the client state file.

Terminology:

A file can be:

present: its FILE_INFO record is marked as PRESENT
on_disk: it's on disk
size_checked: it's on disk and the size is what's in FILE_INFO
contents_checked: it's on disk and the MD5 cksum matches what's in FILE_INFO
    If the file is big, this takes a while,
    and (because disk I/O is not prioritized)
    it can cause the system to be unresponsive.
    Normally (see below) the client does it "asynchronously";
    i.e. it continues to respond to GUI RPCs while the check is in progress.

After a file is downloaded, its contents are checked asynchronously
and it's marked as PRESENT.
This protects against 1) and 2).

When the client starts up, it checks all files to see
if they are on disk and have the right size.
If not it marks tham as not PRESENT and starts a new download.
This protects against 3).

Old: (<= 7.23.0):
    when a task is started, the client synchronously checks the
    contents of its files.
    If a task has big files (and/or a lot of tasks are starting)
    this can cause
    - the manager to be unresponsive (because the check is synchronous)
    - the entire system to bog down

    This check is done only if the project
    has a "verify_files_on_app_start" flag set.
    A lot of projects have this set.
    Currently it defaults to off when you create a project,
    but I think that at some point it defaulted to on.

New:
    When a task is started:
    a) check that all its files are "present".
        If any are not, the task errors out.
        (This could heppen in case 3), and the new download hasn't finished.)
    b) check that all files are on disk
        If any are not, mark as not present and start a new download.
        The task errors out.
        This protects against 4).
    b) if process creation fails,
        synchronously check the contents of the app version files.
        If bad cksum, mark as not present and start a new download.
        The task errors out.
        This protects against accidental modifications to executable files,
        which probably never happens.

    The project verify_files_on_app_start flag is not longer used.
