### ISSUE TITLE
Exclusive app is running... Show which app.

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [BOINC/boinc#5168]
**Describe the problem**
So BOINC wasn't running over night because apparently an exclusive app was running so no credits for me sadly.

**Describe the solution you'd like**
I would like to see the exclusive app's name being logged into the log feed so I can see what is causing the stop.

**Additional context**
I use my PC also as a gaming PC so having the exclusive app' being logged into the feed can help me debug the issue.

**Comment by davidpanderson** [comment]
This is shown with the "mem_usage_debug" flag, but that shows a bunch of other stuff too, and it shows it every 10 seconds.

We should show a message only for the start and end of the execlusive app period.
What option should this be under?  Maybe cpu_sched?

**Comment by AenBleidd** [comment]
> What option should this be under?  Maybe cpu_sched?

I believe this is a good flag to show such information
