### ISSUE TITLE
Feature Request: Option to manually override external CPID

### ISSUE THREAD

**Issue by makeasnek** [BOINC/boinc#5177]
**Describe the problem**
Background: BOINC uses several forms of CPID, this is in regards to the external CPID, which is used to track statistics across projects. A user, when signing up to multiple projects, initially has several different external CPIDs which eventually "converge" onto one "dominant" CPID. This dominant CPID is the oldest CPID.

Problem: There are several things which can cause this external CPID to change:

- Adding removing projects from BOINC manager: If user removes oldest project, CPID changes. 
- Installing new copy of OS or BOINC but being unable to attach to oldest project because it no longer exists or is down

When this CPID changes, it can cause problems with other services which rely on this CPID, such as websites which track user stats across projects. A user's cross-project stats should not depend on them keeping their oldest project attached.

Additionally, sometimes it may take a while for the CPID's to converge on a new setup (such as one project being down or some other edge cases which I don't know about) leading to "split CPID" which is a difficult problem to solve.

**Describe the solution you'd like**
Make it possible to force BOINC to use a specific external CPID by issuing a command via the api (boinccmd and RPC) or by setting a field in BOINC manager preferences.

**Comment by KeithMyers** [comment]
Most users are ignorant of the command line. Preferable solution would be through the Manager Preferences interface.

**Comment by davidpanderson** [comment]
The CPID mechanism should be invisible to users.  If there's a problem, it should be handled automatically

**Comment by KeithMyers** [comment]
Handled automatically . . . .  by whom??

**Comment by makeasnek** [comment]
And how would an automated mechanism handle this differently than it currently does?

There are already a number of users who have arrived at hackey solutions to this problem, such as:

1. Shut down BOINC
2. Manually edit client_state.xml file to include chosen CPID
3. Restart BOINC

But obviously having to advise users to do this is painful, many of them may encounter problems with incorrect characters or line endings etc. It's not user-friendly at all, yet encountering this problem is basically an inevitability for any project (like BOINC Games) which uses CPID. It won't effect all users, but some users will inevitably be effected. And there is no real alternative to using CPID for tracking stats cross-project.

Another potential solution, aside from adding a manual override to BOINC's API, would be to have BOINC client "remember" the first CPID it ever encounters, and forever force all future projects to use that CPID.

**Comment by davidpanderson** [comment]
That's what I was thinking of.  I'll write a design proposal.

**Comment by davidpanderson** [comment]
```
User CPID:

This is a 32-char string representing a particular email address
(i.e. accounts w/ same email on a number of projects).
It doesn't allow hackers to infer the email addr
(e.g. it's not just a hash of the addr).
It's used in stats XML exports to identify accounts;
stats sites use this to show a user's total across projects.

When a user CPID is shown publicly (stats export, or user web page)
it's hashed with the user email addr.
This is called the "external user CPID".
Doing this prevents hackers from falsely adding credit to some else's account
(why they'd do this, I don't know).

current design:
    A project server generates random CPID when user record is created
    It's stored in the DB (user.cross_project_id)
    It's propagated to clients via scheduler RPCs:

    scheduler reply:
        includes
            email hash
            CPID
            user create time
        the client stores this info in the PROJECT object
    scheduler request:
        of projects with same email hash,
        include CPID of the oldest (earliest user create time)
        The project updates the user DB record with this CPID

problem:
    if the user detaches from the oldest project,
    the client will send projects the 2nd-oldest user CPID
    the user CPID will change, confusing stats sites

proposed design (client; no server change):
    the client stores a map
        email_hash => (CPID, time)
        storing the oldest CPID for that email hash
    scheduler reply:
        if map entry for the email hash exists
            if user.create_time < map entry time
                update map entry
        else
            create map entry
    scheduler request:
        include map entry CPID

Notes:
    The first account created with a given email addr determines the CPID,
        even if that project goes away, or the user detaches from it
```

**Comment by KeithMyers** [comment]
It's good the proposed change is in the user client and not the server client code.  This solves the issue of projects that won't update their server code or who run custom server code.

**Comment by makeasnek** [comment]
Thank you for the lightning fast fix for this problem David!

**Comment by TheRealYeti** [comment]
Would it be possible to keep the Cross-Projekt-ID even if the E-Mail-Adress gets changed ?

I'm running BOINC since early starting and a lot of projects have retired meanwhile. Since now I had all the time the same E-Mail-Adress, so my stats show the History of all ever crunched projects.

Mow I would like to change my E-Mail-Adress but for the retired Projects I never can change the Mail-Adress and if I'm right I will loose these retired projects in my stats
