### ISSUE TITLE
Boinc client doesn't populate cc_config.xml

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#5184]
**Describe the bug**
 Boinc client doesn't populate cc_config.xml unless i select the Options >> Event Log Options and toggle a previously unselected logging option, which  creates a fully populated cc_config.xml file.
**Steps To Reproduce**
1.  install boinc-client with apt
2. Start it with systemctl
3. /var/lib/boinc-client contains following

This is a minimal configuration file cc_config.xml of the BOINC core client.
For a complete list of all available options and logging flags and their
meaning see: https://boinc.berkeley.edu/wiki/client_configuration
<cc_config>
  <log_flags>
    <task>1</task>
    <file_xfer>1</file_xfer>
    <sched_ops>1</sched_ops>
  </log_flags>
</cc_config>

**Expected behavior**
boinc-client populates file on start.
i have to modify logging options with boinc-manager to make boinc-client populate cc_config.xml

**Screenshots**

**System Information**
 - OS: [Version 10.0.22621.1485]
 - BOINC Version: 7.22

**Additional context**

**Comment by AenBleidd** [comment]
@davidpanderson, I assume this is expected and desires behavior, right?

**Comment by davidpanderson** [comment]
Yes (unless someone convinces me otherwise)
