### ISSUE TITLE
Add option to run BOINC screen saver only.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#519]
**Reported by Ageless on 5 Mar 38038895 12:26 UTC**
This is a request from Thom Little [posting on the BOINC Dev forums](http://boinc.berkeley.edu/dev/forum_thread.php?id=2414), to be able to run with the BOINC screen saver only, not the application's one kicking in. 

I quite like the idea. On some computers the BOINC screen saver runs without problems, it's when the project application's screen saver kicks in that the problems start. To allow the screen saver to run anyway, have the option to disable the project's screen saver. 

I understand from Rom that this is possible with BOINC 6, so setting the milestone to that. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/540

**Comment by romw** [comment]
**Commented by romw on 5 Mar 39425704 04:00 UTC**
Punting remaining new feature work to 6.10

**Comment by Ageless93** [comment]
This is already an option in BOINC 7's [screen saver options](http://boinc.berkeley.edu/wiki/BOINC_screensaver#Screensaver_Settings): set Run project screensavers for to the option Never.
