### ISSUE TITLE
Mark forum read feature

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#52]
**Reported by KSMarksPsych on 18 Dec 37296894 22:40 UTC**
Posted by:
Date: 4:47 PM 11-07-2005
Isn't there yet. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/52

**Comment by romw** [comment]
**Commented by KSMarksPsych on 31 Jan 37298129 06:13 UTC**
Posted by: 
Date: 9:53 AM 11-28-2005
Most forum sites have this option. This function comes in handy when you've read the threads you want to read and you want to clear out the rest of the unread thread icons.

- Misfit

**Comment by romw** [comment]
**Commented by Eric Myers on 9 Apr 37355583 21:46 UTC**
Good idea.  I have this working on Pirates now (needs to be tested more thoroughly)

**Comment by romw** [comment]
**Commented by Rytis on 7 Sep 37545953 15:33 UTC**
(In [13182]) - user web: add a feature to mark all threads as read (forums). (fix #52)

**Comment by romw** [comment]
**Commented by Ageless on 4 Feb 37776816 12:53 UTC**
Is it possible to enhance this feature so it works on only the threads in the forum you are presently reading? I mean now the option sits at the top of most forum indexes, but also at the top of independent forums. 

Pressing it in any forum marks threads read in all forums for that project. So either the change should be that the option only appears on the forum index, or that only the threads in the one forum you pressed the option in will be marked read, while all other unread threads in other forums of that project stay unread.

**Comment by romw** [comment]
**Commented by Nicolas on 7 Jan 37776867 01:46 UTC**
me: I just clicked "Mark all threads as read" while I was on a specific forum category[I was surprised to find it marked '''all''' categories as read[[br]([br]]
me:)]
Rytis: well[ever wondered why it's mark '''all''' threads?[[br]([br]]
Rytis:)]
me: maybe we need it as "mark '''this''' forum as read"

**Comment by romw** [comment]
**Commented by Ageless on 7 Jul 37778137 10:13 UTC**
Replying to [Nicolas](comment:5):
> Rytis: well[Rytis: ever wondered why it's mark '''all''' threads?[[br]([br]]
>)]
> me: maybe we need it as "mark '''this''' forum as read"

Yup. As when pressing it in any single forum we'd expect only the threads in that forum to be marked as read. Comparing it to phpBB forums, the distinction could be made:[the index it'll say  "Mark all forums read".[[br]([br]]

On)]
In any forum it'll say "Mark all topics read". [[br]]

**Comment by romw** [comment]
**Commented by Eric Myers on 1 Feb 41077837 06:13 UTC**
The way I have it set up on Pirates@Home you can click on the little yellow icon next to the thread title, the one that indicates that there are unread postings.   That marks the thread as being read (and the yellow icon vanishes).

It would also be useful to have a button at the top of the list of threads which allows one to mark all the threads in that forum as being read.

Right now there is only a button in the main list of forums which marks all threads in all forums as being read.  This is okay, but less useful than either of the two methods mentioned above.

**Comment by ChristianBeer** [comment]
This was fixed some time in the past and is working AFAIK.
