### ISSUE TITLE
Boinc manager not reporting tasks details macOS 13.3.1

### ISSUE THREAD

**Issue by JeromeC2023** [BOINC/boinc#5205]
I just upgraded my Intel iMac (one of the latest late 2020) from macOS 12 to latest 13.3.1.

System is working fine and I didn't experience any flaw but Boinc Manager 7.20.4 is only listing the tasks and their status, but not anymore the run time / % / remaining / deadline... I see only 0 or --- instead of numbers and %. 

All the text looks OK : project name, application name, task name, status. 

BoincTasks Js is doing the job, though.

I reinstalled boinc (7.20.4) but same behavior. 

<img width="1437" alt="Capture d’écran 2023-04-21 à 23 38 26" src="https://user-images.githubusercontent.com/131522798/233775582-4ddf130e-6cd8-454f-b967-c642664277ce.png">

**Comment by CharlieFenton** [comment]
I’m out of town and will look at this next week.

**Comment by JeromeC2023** [comment]
I forgot to mention that the data usage tab and statistical tab are just empty. 

<img width="1808" alt="Capture d’écran 2023-04-23 à 11 56 08" src="https://user-images.githubusercontent.com/131522798/233832921-94f686c8-7d65-430a-9088-eab80877f1be.png">

<img width="1804" alt="Capture d’écran 2023-04-23 à 11 56 18" src="https://user-images.githubusercontent.com/131522798/233832930-2f26d9f7-2902-4710-9c58-36083ec8979b.png">

(I do have plenty of asteroid credits, I have the same display regardless the project I choose)

**Comment by JeromeC2023** [comment]
... and same for the project tab, I have the project list and the proper status, but no figures.

The notifications tab is OK, the problem is with figures.

**Comment by CharlieFenton** [comment]
I don't have an Intel Mac, but on my Apple Silicon Mac I can reproduce this on almost every language which I have tried (French, German, Italian, Greek, Danish, Dutch, Spanish, Russian.) But none of these problems occur when the language is set to English, Hebrew or Chinese. I will investigate further.

**Comment by CharlieFenton** [comment]
I believe I have found the problem and will release a hot fix within the next few days.

**Comment by CharlieFenton** [comment]
@JeromeC2023 BONC 22.0.7 is now available for download. Please let us know if you still have this problem.

Note: There is also a screensaver bug under MacOS13.3.1 that is widely reported, and apparently has no workaround. If you have multiple displays connected to the computer, the screensaver usually does not appear on the main display. (The bug is intermittent, so it does occasionally appear on the main monitor.) Since the BOINC screensaver uses only the main display, it does not appear at all on Macs with multiple screens. Apple will reportedly fix this in the next release of macOS.

**Comment by JeromeC2023** [comment]
Hello, I see a 7.20.7 published yesterday on boinc website for "Apple Mac (64-bit Intel and Apple Silicon)", could it be the "22.0.7" and/or the "7.22.1" mentioned above ? (I must confess I'm completely confused)

If the answer is "none of them", where can I download the good one to test ? 

Regarding boinc screensaver on mac, it's been years I don't use it on my mac, and I only have my iMac main display.

**Comment by JeromeC2023** [comment]
Thanks, actually I had downloaded that 7.20.7 version from the official website just after I wrote this (and then went for dinner) and now I just installed and tested it : it is solving the issue in tabs tasks / projects / statistics, great !!

But in "data usage" tab all is still empty though.

**Comment by CharlieFenton** [comment]
> BONC 22.0.7 is now available for download.

Sorry for the typo. (I don't know how that came out of my fingers.) That should be 7.20.7.

**Comment by CharlieFenton** [comment]
> But in "data usage" tab all is still empty though.

@JeromeC2023 It works for me on my Apple Silicon iMac under MacOS 13.3.1. I set my computers region to France and language to French , and set BOINC Manager to French.  Here is what I see:
 
<img width="2207" alt="Capture d’écran 2023-05-02 à 19 22 18" src="https://user-images.githubusercontent.com/10470356/235822333-9bb89800-8c01-4af1-a1ef-ee6158aa7b20.png">
<img width="2207" alt="Capture d’écran 2023-05-02 à 19 22 39" src="https://user-images.githubusercontent.com/10470356/235822384-b95d72c0-e6af-489c-aa66-ddb4cfacfc37.png">

**Comment by JeromeC2023** [comment]
The statistic tab is OK 

![image](https://user-images.githubusercontent.com/131522798/236396347-72c0ea75-4359-4be9-982f-cd5e86fcbf0c.png)

the issue is with the data usage tab

either I have this 

![image](https://user-images.githubusercontent.com/131522798/236396423-16d69d7a-eee4-401a-ba5e-bd53785986e7.png)

but I also noted it got me disconnected from the client or even crashing when staying on this tab, or  (sometimes, not always) even having irrational behaviour of the *other* tabs after living this tab (completely blank with no content)  

and now after my latest restart of boinc I also got this display 

![image](https://user-images.githubusercontent.com/131522798/236396561-3c7be695-e0b6-46ea-8833-83ae887373db.png)

so yes it is weird. 

But again, I can live without :)

Last I note a strange display from the task you can notice some of the rows with bold characters   

![image](https://user-images.githubusercontent.com/131522798/236397136-72f88d95-fdb6-4fff-8a04-a459a9ac8a04.png)

but only when boinc manager window does not have the focus, as soon as I click in the window (inside the grid on a row) then no more bold rows. 

In the project tab I have a similar but different behaviour  : 

![image](https://user-images.githubusercontent.com/131522798/236397302-827ba6a5-0810-4064-8036-56f8e8f49fab.png)

but depending on where I click inside the grid, the bold may, or not, disappear 

Weird but again, no real issue.

**Comment by JeromeC2023** [comment]
To complete the information, with macOS version 7.22.1 published 9th May, even some remaining display glitches (with strange "variable bold rows") were solved.

Data usage tab is still blank (empty circles). Not a big deal.
