### ISSUE TITLE
Show VM Console not working on Linux with Virtualbox 7.x

### ISSUE THREAD

**Issue by Toby-Broom** [BOINC/boinc#5214]
**Describe the bug**
The Show VM command is hardcoded to rdesktop-vrdp & Oracle removed it

https://www.virtualbox.org/changeset/95323/vbox

[https://github.com/BOINC/boinc/blob/e443a364263705a895394e07f188a6a5d966c3f3/clientgui/MainDocument.cpp#L1947](url)

**Steps To Reproduce**
1. Start a task that has a VM attached e.g. LHC@Home
2. Once up and running press the Show VM Console button

**Expected behavior**
RDP to VM is launched.

**System Information**
 - OS: Ubuntu 23.04
 - BOINC Version: 7.20.5

**Additional context**

Workaround was to make a simlink after installing the default rdesktop 

ln -f /usr/bin/rdesktop /usr/bin/rdesktop-vrdp

It was removed in v7 / 23.04

https://packages.ubuntu.com/lunar/amd64/virtualbox/filelist

vs 22.10 with the 6.1 branch

https://packages.ubuntu.com/kinetic/amd64/virtualbox/filelist

**Comment by davidpanderson** [comment]
Thanks for reporting this.
I changed things so that if rdesktop-vrdp isn't there,
the managers tries "rdesktop", then "xfreerdp"
