### ISSUE TITLE
Boinc doesnt detect and suspend work when computer is in use

### ISSUE THREAD

**Issue by Cat22** [BOINC/boinc#5223]
**Describe the bug**
I selected to have boinc suspend when user input is detected
boinc does not ever detect key presses or mouse movement and suspend
**Steps To Reproduce**
1. In computing preferences select the computing tab and check-mark the "Suspend when computer is in use"
2.  Enter a timeout value, in my case it is 15 minutes

**Expected behavior**
Boinc should suspend when i either move the mouse or press a key
If undisturbed for 15 minutes, boinc should resume normal operation
**Screenshots**

**System Information**
 - OS:  OpenSuse Tumbleweed 04-25-2023 
 - BOINC Version:  7.22.0 x86_64

**Additional context**

**Comment by AenBleidd** [comment]
Closed as a duplicate of #1187
