### ISSUE TITLE
Licensing my files without my permission

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#5237]
In this PR https://github.com/BOINC/boinc/pull/5235 Vitalii add licensing to files that I created without my permission.
All the files that I created and without boinc licensing, I am not allow to add licensing or modify them.
Please revert the changes.

@davidpanderson For your attention.

**Comment by davidpanderson** [comment]
Please read https://github.com/BOINC/boinc#copyright

**Comment by AenBleidd** [comment]
@talregev, please use your energy to do smth useful, instead of constantly fighting with me and/or other BOINC maintainers.
And yes, before contributing to any open-source project, read their copyright ;)
