### ISSUE TITLE
Seperate processor options for 'While computer is in use' and 'not in use'

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#524]
**Reported by krator on 19 Oct 38059339 21:20 UTC**
Allow seperate processor options for then the computer is in use and when the computer is not in use.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/545

**Comment by romw** [comment]
**Commented by krator on 11 Jul 38059342 06:13 UTC**
Replying to [krator](ticket:545):
> Allow seperate processor options for then the computer is in use and when the computer is not in use.


This was supposed to be an enhancement.  Sorry.

**Comment by romw** [comment]
**Commented by KSMarksPsych on 28 Aug 38060315 12:00 UTC**
Changed to enhancement and added component.

**Comment by ChristianBeer** [comment]
duplicate of #41
