### ISSUE TITLE
Unable to configure BOINC Manager on my Mac Studio M1 Max

### ISSUE THREAD

**Issue by Signalshifter** [BOINC/boinc#5243]
**Describe the bug**
There are no configuration tabs on the Simple screen, I can find no way to configure BOINC, I can't even get to the advanced screen
**Steps To Reproduce**
1. You can see the problem simply by opening BOINC on this Mac Studio M1 Max, no configuration tabs
2. 

**Expected behavior**
I am looking for the configuration options,

**Screenshots**
![Screenshot 2023-05-18 at 10 38 31](https://github.com/BOINC/boinc/assets/99382887/57cd45c6-c3c1-4aef-a4e9-4ce7d105278f)

**System Information**
 - OS: macOS Ventura 13.3.1
 - BOINC Version: 7.22.1 

**Additional context**
I have run BOINC Manager on my Window machines for more the 14 years with no problems, and it is running just fine on my new Mac but I cannot configure it like a can with the Windows version.

**Comment by AenBleidd** [comment]
I'm have no experience with MacOS, but IIRC if the application has system menu, it should be shown at the very top of your screen. Could you please check this?

**Comment by Signalshifter** [comment]
Here are screen shots of the BOINC Managers icons opened I don't see a system menu but I am a real noob with macOS, been a Microsoft person since the MSDOS days.

![Uploading 13293143-7216-4E87-8342-270E2ACDC19D_1_201_a.png…]()
![676DC7D3-2BA4-4FB1-9472-4625CCBC23B9_1_201_a](https://github.com/BOINC/boinc/assets/99382887/63fcbe1d-09d7-4769-b10a-67
![20326162-88E9-4F36-AED9-5CB837F559AA_1_201_a](https://github.com/BOINC/boinc/assets/99382887/2f64856f-3c1d-4d32-903c-a37d599509e8)
b219c1d589)
![Uploading C83ED3D7-077D-4442-9AFF-403D4A2AED0D_1_201_a.png…]()

**Comment by AenBleidd** [comment]
This is a tray icon. System menu is usually too left

**Comment by AenBleidd** [comment]
And this menu is visible when you have your BOINC Manager window the top most window on your desktop

**Comment by AenBleidd** [comment]
No problem.
