### ISSUE TITLE
Can't attached project in linux

### ISSUE THREAD

**Issue by BeHajek** [BOINC/boinc#5247]
**Describe the bug**
A clear and concise description of what the bug is.I am also having a problem of not being able to attach projects that I already have an existing accounts for., but I can create new accounts and attach the project.The operating system is linuxmint-21.1-cinnamon-64bit. The boinc version is BOINC client version 7.22.1 for x86_64-pc-linux-gnu

**Steps To Reproduce**
1. Install inuxmint-21.1-cinnamon-64bit and then BOINC client version 7.22.1 for x86_64-pc-linux-gnu
2. Attempt to attach a project that you already have an account. i.e gpugrid, Einstein, milkyway, asteroids 

**Expected behavior**
Boinc freezes and fails to attached it.
**Screenshots**

**System Information**
 - OS: linuxmint-21.1-cinnamon-64bit
 - BOINC Version: 7.22.1 for x86_64-pc-linux-gnu

**Additional context**
Add any other context about the problem here. See link: https://www.gpugrid.net/forum_thread.php?id=5392

**Comment by KeithMyers** [comment]
A key point I think that needs emphasizing it that it always core-dumps in the client.service when the join project process as an existing user is attempted.

I wonder if the client.service is not handling the creation of the data directory in /home/$USER well when it is running the join process.

**Comment by davidpanderson** [comment]
I couldn't repro this in master using boinccmd, e.g.
boinccmd --project_attach https://boinc.berkeley.edu/test/ xxxxx

Does it happen only when using the manager?

**Comment by BeHajek** [comment]
It happens both using the boinc manager and the weak key (ie boincccmd --project attached  https://www.gpugrid.net/ xxxxx).

In the boinc manager it crashes when attaching to an "Yes, existing user" option and not the "No, new user" option.

It happened to for Einstein, gpugrid, milkyway and asteroids projects. I never tried to attach https://boinc.berkeley.edu/test/.

**Comment by davidpanderson** [comment]
I can't repro this in master using GPUGRID.
Where did you get the client from, and how did you install it?

**Comment by BeHajek** [comment]
This is what I installed from this web site, as separate OS on its separate disc :

https://www.linuxmint.com/download.php

Following these instructions:

https://linuxmint-installation-guide.readthedocs.io/en/latest/

I installed boincs through its software manager.

**Comment by BeHajek** [comment]
![Screenshot from 2023-05-23 20-13-45](https://github.com/BOINC/boinc/assets/134241239/62c7fd4f-71c9-41d4-818b-abf661ddc7e4)
![Screenshot from 2023-05-23 18-40-12](https://github.com/BOINC/boinc/assets/134241239/300aae97-4f6b-4809-82d4-349201617a3f)

**Comment by BeHajek** [comment]
I spent the evening remove the flatpak version and reinstall linux mint. I attempt ed a manual reinstall of boinc the items are in the correct directory.
![Screenshot from 2023-05-23 19-49-59](https://github.com/BOINC/boinc/assets/134241239/ba82fa1a-5c67-4994-99d2-89c7f8afc5f4)
![Screenshot from 2023-05-23 19-50-47](https://github.com/BOINC/boinc/assets/134241239/e2f68844-6230-419f-acce-6539759843ac)

**Comment by KeithMyers** [comment]
Well does the regular BOINC installation attach existing users now?
Or first question . . does BOINC run at all now?

**Comment by BeHajek** [comment]
I started with this
![Screenshot from 2023-05-24 04-22-08](https://github.com/BOINC/boinc/assets/134241239/078ba82d-46d5-41d9-a5bc-b2feb866d543)

**Comment by BeHajek** [comment]
I did this
![Screenshot from 2023-05-24 04-24-39](https://github.com/BOINC/boinc/assets/134241239/8deb25fa-2e50-4702-8812-9109a9ec6d29)

**Comment by BeHajek** [comment]
Reboot
Then I did this:
![Screenshot from 2023-05-24 04-28-41](https://github.com/BOINC/boinc/assets/134241239/1ee6462d-61c6-42e3-b851-3f394e799432)

**Comment by BeHajek** [comment]
The I did this
![Screenshot from 2023-05-24 04-31-08](https://github.com/BOINC/boinc/assets/134241239/a6a48594-8ca2-4f50-a539-75932ae5a4a5)

**Comment by BeHajek** [comment]
Here is the software manager.
![Screenshot from 2023-05-24 04-38-06](https://github.com/BOINC/boinc/assets/134241239/4d01fb1d-c205-445e-967a-73073db7c59c)

**Comment by RichardHaselgrove** [comment]
> Reboot
> Then I did this:

I see two problems with that.

1) The Mint repository has downloaded BOINC v 7.18.1 for you. **This was never certified by BOINC for use on Linux.** The Ubuntu maintainers really ought to have got a grip on this by now.
2) Mint is also recommending that you install boinc-opencl and something involving mesa that I can't read. Most of this conversation has taken place on the GPUGrid boards: GPUGrid is exclusively an nvidia-cuda project, and I see you have a suitable RTX card. If any additional package is needed, it would be the cuda one, but usually the basic boinc-manager and boinc-client are enough (though not v7.18). What you do need, however, are a proper set of NVidia drivers direct from them - not mesa or any other third party.

**Comment by KeithMyers** [comment]
Use these instructions for installing BOINC on Mint.

[https://www.reddit.com/r/BOINC4Science/comments/12h0g7v/quick_guide_installing_boinc_on_linux_right_now/](url)

**Comment by RichardHaselgrove** [comment]
Broken link, corrected.

Unfortunately, it doesn't mention - and so far as I can see, doesn't resolve - the broken v7.18.1 problem.

**Comment by KeithMyers** [comment]
No, still 7.18.1 but from the comments on Discord it works for people that have been directed to this page.
They get a functioning Boinc they can use with Gridcoin.

**Comment by KeithMyers** [comment]
Make sure you have done this to get the permissions squared away.

`sudo usermod -a -G boinc $USER`

**Comment by BeHajek** [comment]
This is what I just did the GPU grid thread posts of this morning:
![Screenshot from 2023-05-24 17-35-02](https://github.com/BOINC/boinc/assets/134241239/9c783bb4-88f4-4410-9021-bce93cc9bc08)
![Screenshot from 2023-05-24 17-35-40](https://github.com/BOINC/boinc/assets/134241239/07aa70ff-9833-420f-b924-0c2fd4e32cc8)

**Comment by BeHajek** [comment]
![Screenshot from 2023-05-24 17-52-46](https://github.com/BOINC/boinc/assets/134241239/dfee2a14-f66d-4b13-82de-2
![Screenshot from 2023-05-24 17-53-26](https://github.com/BOINC/boinc/assets/134241239/ea69c7bb-6ddf-4d0e-b674-9937b72a42e8)
7a45ea4600c)

**Comment by KeithMyers** [comment]
I would now just ignore the service and see whether the client will run at all when launched from its resident directory.  You would also then be able to see all of the output messaging.

Open a Terminal and navigate to /usr/bin where the binary resides.

```
cd /usr/bin
ls |grep boinc
ls -ail |grep boinc
```

This proves the binaries reside here and whether their execution bits are set properly.
Then execute the boinc client binary directly in the Terminal.

`./boinc`

You should see the printout of the client starting in the Terminal.  This is the same output that gets sent to the stdoutdae.txt file which is the same as what gets printed in Event Log in the Manager

If it looks like the client is running correctly, then we need to execute the Manager and see if it connects to the client.

Open another Terminal session in the the same /usr/bin directory and execute the Manager.

`./boincmgr`

See if the Manager connects to the client in the bottom status bar of the Manager.   It should say 'Connected to localhost (7.18.0)'

Post back the screenshots at each step.

**Comment by KeithMyers** [comment]
Went back and examined more closely your screenshot of adding your username to the boinc group.

You goofed with your username. The command should run without the help for options displaying.

Your username should not have the $ prompt in front of it.  It doesn't look like the $USER system variable was parsed correctly. 

It should just be: bedrichhajek

Redo the usermod command.

`sudo usermod -a -G boinc bedrichhajek`

Then check that your username now belongs to the boinc group.

`groups bedrichhajek`

**Comment by BeHajek** [comment]
![Screenshot from 2023-05-24 20-10-19](https://github.com/BOINC/boinc/assets/134241239/495eaffe-2da2-4efb-b352-7353f6e7b12a)

**Comment by BeHajek** [comment]
rebooted

**Comment by BeHajek** [comment]
![Screenshot from 2023-05-24 20-18-28](https://github.com/BOINC/boinc/assets/134241239/07322cbf-7af1-42a9-9a9b-bf7d9fe56807)
Now I did this again.

**Comment by BeHajek** [comment]
Then this happened:
![Screenshot from 2023-05-24 20-36-28](https://github.com/BOINC/boinc/assets/134241239/364baa02-8d51-4b37-b860-8120544ee478)

**Comment by KeithMyers** [comment]
I didn't want you to start the service. So before you execute the client binary in the /usr/bin directory, stop the client service from running.

`sudo systemctl stop boinc-client`

I want you to just execute the binary as a standalone process. To prove that the binary can execute correctly just on its own.

OK, let's back up just a bit and prove that all the dependencies for the binary are available. If any are missing the client binary can't run.

Open a Terminal again in /usr/bin
Then execute this command and post the screenshot of the results.

`ldd .boinc`

And please post a screenshot of this command output.

**Comment by BeHajek** [comment]
![Screenshot from 2023-05-24 22-22-26](https://github.com/BOINC/boinc/assets/134241239/a1675c19-597a-486e-8942-37e2a571e03d)
Items is posted.

**Comment by KeithMyers** [comment]
You didn't execute the command from /usr/bin.  Look at the prompt.  Look at your previous screenshot where you cd to the /usr/bin directory.  Notice how the prompt has the /usr/bin path before the $ prompt and after the user@hostname: It should look like this:
keith@midget:/usr/bin $

```
cd /usr/bin
pwd
ls |grep boinc
ldd ./boinc
```
pwd is short for 'print working directory'

**Comment by BeHajek** [comment]
![Screenshot from 2023-05-25 04-47-54](https://github.com/BOINC/boinc/assets/134241239/03019169-63df-4c55-a44c-39dfae657d76)

**Comment by BrianNixon** [comment]
> illegal instructions

This is on an AMD Phenom? BOINC has been [reported](https://boinc.berkeley.edu/forum_thread.php?id=14968) to fail on chips without AVX

**Comment by KeithMyers** [comment]
Please post the output of:
`lscpu`
in the Terminal here in this issue.

**Comment by RichardHaselgrove** [comment]
When BOINC is compiled for release, especially by a repository maintainer, who is responsible for

a) compiling libraries like libboinc.so.7. ?
b) setting the compiler directives for the build script ?

I don't see why a BOINC core program would ever benefit from AVX - it's a management and information tool, not an optimised scientific research cruncher.

**Comment by davidpanderson** [comment]
We're in the process of moving package-building to Github, so that we have control over these things.

**Comment by KeithMyers** [comment]
That will be a most welcome evolution of BOINC.  Thanks in advance.

**Comment by BeHajek** [comment]
After purging the system:
![Screenshot from 2023-05-25 19-37-47](https://github.com/BOINC/boinc/assets/134241239/7fd1a7d9-d09a-4c78-bf37-cb47e7c8c8de)
![Screenshot from 2023-05-25 19-38-47](https://github.com/BOINC/boinc/assets/134241239/f1d2675f-59df-4405-a214-67582ae55b6e)
![Screenshot from 2023-05-25 19-39-01](https://github.com/BOINC/boinc/assets/134241239/380aa578-d684-4d6a-b2e7-ab3dcf046d54)
![Screenshot from 2023-05-25 19-41-34](https://github.com/BOINC/boinc/assets/134241239/b47ae059-6331-4d5b-8649-150b00d0ac14)
![Screenshot from 2023-05-25 19-44-07](https://github.com/BOINC/boinc/assets/134241239/ab458fb1-8f32-4078-a264-a7d1f648cbba)
![Screenshot from 2023-05-25 19-45-49](https://github.com/BOINC/boinc/assets/134241239/ca9179b5-d6b5-4281-aa
![Screenshot from 2023-05-25 19-46-20](https://github.com/BOINC/boinc/assets/134241239/d57af917-547c-4c9f-97c3-ed1393006aca)
bc-35329ceccbae)
![Screenshot from 2023-05-25 19-48-32](https://github.com/BOINC/boinc/assets/134241239/f49bbb2a-b49a-4221-9829-85f01e2ec8d3)

**Comment by BeHajek** [comment]
The last picture is after reboot.

**Comment by BeHajek** [comment]
![Screenshot from 2023-05-25 20-12-56](https://github.com/BOINC/boinc/assets/134241239/30feab4e-707b-4245-8829-fa9b52885b74)
![Screenshot from 2023-05-25 20-14-40](https://github.com/BOINC/boinc/assets/134241239/0e488c1e-9752-4ef7-a9cf-11f5835e60a2)
![Screenshot from 2023-05-25 20-15-26](https://github.com/BOINC/boinc/assets/134241239/3df9b05d-0f2a-40fb-b932-83179433cce7)
![Screenshot from 2023-05-25 20-15-50](https://github.com/BOINC/boinc/assets/134241239/9cada5b9-5c5a-4598-b943-41f00a7d2dd1)
We are going around in circles.

**Comment by BeHajek** [comment]
![Screenshot from 2023-05-25 20-21-12](https://github.com/BOINC/boinc/assets/134241239/ac36745c-ace0-4833-8a34-672ab68c8ab6)

**Comment by BeHajek** [comment]
Here is the highlighted line:
Thu 25 May 2023 07:49:32 PM EDT |  | Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt cpb hw_pstate vmmcall npt lbrv svm_lock nrip_save pausefilter

**Comment by BeHajek** [comment]
Boinc manager freezes, and I have to force quit.

**Comment by KeithMyers** [comment]
Because you installed the PPA, that installs the standard Boinc service.  That automatically starts the boinc client. That is why you kept getting the warning of another client is running when you started another client process from the /usr/bin directory.

I think the only issue you have now is the standard one of the boinc client process having only roots rights and the user is not allowed to start the client or start the Manager and have it hook to the client.

You need to go through the process of adding your user again to the boinc group

`sudo usermod -a -G boinc bedrichhajek`

Again, after a reboot, check that you user belongs to the boinc group for permissions to run the Manager as user and have the Manager connect to the client as user.

`groups bedrichhajek`

You shouldn't need to start the client or the Manager from the /usr/bin directory anymore.  That was just for a sanity check to prove the binaries are executable.

Now the boinc service should start automatically everytime you boot and start the client.  Then clicking on the Manager icon on the Desktop should connect to the running client so you can add projects and manage the client.

If you are still having issues with connecting to the client with the Manager, then we can do some editing of the boinc.service file and change some permissions.

You can always verify the client is running in the background by viewing the process list in the System Monitor. Or open a Terminal and use htop to view the running processes by searching on boinc.

**Comment by BeHajek** [comment]
![Screenshot from 2023-05-25 21-37-36](https://github.com/BOINC/boinc/assets/134241239/66c8f433-2c27-4313-84c0-108008ec5d3a)
![Screenshot from 2023-05-25 21-38-19](https://github.com/BOINC/boinc/assets/134241239/edf8ce96-f114-46ac-b255-017a6fe502f4)
I managed to attached the project by the weak method in the terminal.

**Comment by KeithMyers** [comment]
OK, great . . . .  a little progress.  I'd still like to know why you can't attach as an existing user account.

At least the client is runinng and can be connected to by the Manager.

**Comment by BeHajek** [comment]
Actually in the end, I was able to, but only using the weak key method:

bedrich@bedrich-MS-7599:~$ boinccmd –project_attach https://www.gpugrid.net/ [weak key]

The other way didn't work.

**Comment by BeHajek** [comment]
file:///home/bedrich/Pictures/Screenshot%20from%202023-07-09%2017-56-49.png
I had another issue with boinc, after running well for several weeks with no issues, I reboot the computer and this is what I had on the screen. While I other computer is running find

**Comment by BeHajek** [comment]
Nevermind, I solved this problem myself.

In the Boinc window, I clicked file, then select computer, then typed in the host name.
I don't know how this happened, but it's fixed.

**Comment by AenBleidd** [comment]
There are a lot of issues described in this ticket (and most of them were already reported, and some of them even solved).
Nevertheless, we're going to host our own linux packages on the official BOINC web-site.
Once this is tested and ready to be publicly used - it will be announced separately.
Stay tuned.
