### ISSUE TITLE
[DB] schema inconsistent with updates

### ISSUE THREAD

**Issue by brevilo** [BOINC/boinc#5271]
The current DB schema (as defined across `db/schema*.sql`) lacks a number of tables create (and not dropped) via `html/ops/db_update.php`, namely:

* [`credit_multiplier`](https://github.com/BOINC/boinc/blob/master/html/ops/db_update.php#L611)
* [`state_counts`](https://github.com/BOINC/boinc/blob/master/html/ops/db_update.php#L629)
* [`trickle_down`](https://github.com/BOINC/boinc/blob/master/html/ops/db_update.php#L54)
* [`trickle_up`](https://github.com/BOINC/boinc/blob/master/html/ops/db_update.php#L54)

Please:
1. Add the missing tables to the schema or, alternatively, drop them in a new DB update
2. Compare the schema against the updates and ensure they're consistent as I might have missed other issues

Thanks

**Comment by davidpanderson** [comment]
These tables aren't used by the BOINC server code, so they don't belong in schema.sql.
Some projects (e.g. CPDN) may be using them, so we can't drop them in dp_update.php.
The status quo is fine.

**Comment by brevilo** [comment]
Hm, please help me then: isn't `html/ops/db_update.php` meant to update the DB schema as it evolves and aren't the `db/schema*.sql` files used to define the current schema at any given point in time? How can I, as a project, determine if my local BOINC DB schema is in line with the current upstream schema? I mean, since I (like all other project, I presume) ran all the updates in `html/ops/db_update.php` it means my schema contains said tables above. Yet any new project won't contain them, so there's an obvious inconsistency there.

If those tables serve no general purpose it's OK not to include them in `db/schema.sql` but they should then be defined in a separate schema definition, e.g. `db/schema_cpdn.sql` (or similar), like the other apparently optional schema definitions in the `db/schema_*.sql` files, no? This way it would be clear what context these tables (still) belong to and that they're not some forgotten remnant. This is the only way I can make an informed decision to drop them locally, or not.

Going forward I'd like to ask you not to include any optional/single-project tables (as in not defined in `db/schema*.sql`) in `html/ops/db_update.php`, since these updates will reach every project.

Thanks

**Comment by brevilo** [comment]
I'm still interested in getting the open questions in my previous post answered and/or please share your opinion on my thoughts. Thanks.
