### ISSUE TITLE
BOINC Manager on MacOS: Window / Help menus reversed

### ISSUE THREAD

**Issue by EelcoV** [BOINC/boinc#5272]
Every MacOS application has Window and Help as the last two menus in its menubar.
The BOINC Manager on MacOS has Help and Window as its last two menus: the order is reversed.
The Help menu should be the last menu on the menubar.

MacOS Ventura 13.4
BOINC Manager 7.20.4.

**Comment by AenBleidd** [comment]
@CharlieFenton, is it something that should be fixed for consistency with other MacOS applications for better user experience?

**Comment by CharlieFenton** [comment]
Tis has already been fixed in BOINC 7.22.2 (probably due to a fix in wxWidgets.)

**Comment by CharlieFenton** [comment]
@EelcoV by the way, the current official release version of BOINC for MacOS is 7.20.7, not 7.20.4. But the menu order is fixed in the current development version 7.22.2.
