### ISSUE TITLE
Boinc hacking Facebook perfils...

### ISSUE THREAD

**Issue by AutoDolor** [BOINC/boinc#5276]
Good morning.
Apparently, there is a backdoor that allows to know the e-mail. It has been happening to me since I installed BOINC, and one of my profiles disappeared... I didn't think much of it. It was in World Grid....
However, yesterday, I join another project, with a different e-mail, and that I use in another Facebook account, and, coincidentally, also deleted...
Apart, it creates a "new user" called BOINC_master.
I use Windows 10 Pro 222H2.
I have uninstalled Boinc, and deleted that "ghost user".
I think there is a severe security problem, or some hacker has created a way to get data out of our computer. The first one was a user from Bulgaria, this morning one from USA...
I will not put my computer at risk again...

**Comment by AenBleidd** [comment]
1. Never user the same Email-Password pair twice to create account on different services.
2. Always use Endpoint protection software on Windows.
3. Run full system scan with Endpoint protection software (almost every major vendor provides a free tool).
4. Do not connect via BOINC to the projects not in the official list provided by BOINC unless you trust it.
5. BOINC uses secure connection by default to communicate with project servers, so it doesn't expose your email and password.
