### ISSUE TITLE
Missing strings to translate in French po files

### ISSUE THREAD

**Issue by LLyaudet** [BOINC/boinc#5297]
**Describe the bug**
Some strings to translate are missing from po files.
Hence, the translators think they have translated everything when it is not the case.

**Steps To Reproduce**
1. Look here : https://github.com/BOINC/boinc/blob/857b0a7ba56356e347764a434879daeb203db67d/tools/gui_urls.xml#L13
2. There is the string "Your tasks".
3. Look here : https://github.com/BOINC/boinc/blob/857b0a7ba56356e347764a434879daeb203db67d/locale/fr/BOINC-Manager.po
4. The string "Your tasks" is missing.

**Expected behavior**
All strings that need translation should be found for all languages
(with an empty translation when the translation is not yet available).

**System Information**
 - OS: Ubuntu 23.04
 - BOINC Version: 7.20.5 x86_64-pc-linux-gnu

**Additional context**
I created an account on transifex but saw there that 100 % of strings were translated in French,
meaning that not all strings to translate are reported to transifex.
I suppose many other languages will be impacted, thus it should be checked for all :)

**Comment by LLyaudet** [comment]
I saw the following strings missing for French:
- "Home page"
- "Your tasks"
And that's all after a quick of the manager.

**Comment by AenBleidd** [comment]
`BOINC-Manager.po` contains localizations strings for BOINC Manager only.
AFAIK, we have no localization for XML files at all, and on the project side only PHP files contain 
translations.
`boinc/toold/gui_urls.xml' is the file for the server part only, and it contains information that could be set by project administrators manually, so there is no way to provide a generic translation for such a file: https://github.com/BOINC/boinc/wiki/GuiUrls

**Comment by LLyaudet** [comment]
Thanks for the fast answer :). I'll open a discussion on the forum of the project then.

**Comment by LLyaudet** [comment]
I did found how the other strings where translated and how some projects had full translations:
https://github.com/BOINC/boinc/pull/5302
Please accept my fix :)
