### ISSUE TITLE
Allow renaming of computers

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#532]
**Reported by thanar on 2 Jan 38125835 21:20 UTC**
I have many LANs and each one of them contains computers named "PC1", "PC2" and so on, due to LAN needs. I find it hard to monitor my computers under BOINC's computer list web page. I believe allowing computer renaming through the web site would be a great idea, and not so difficult to implement.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/554

**Comment by romw** [comment]
**Commented by thanar on 30 Sep 38126089 20:53 UTC**
This feature could also be enhanced by a general computer management tool, where you could rename/merge/group computers and so on... For example one could group lab computers, or even merge two different BOINC records that it's in fact the same computer (hardware) with dual boot.

**Comment by ChristianBeer** [comment]
This was reported 9 years ago and I haven't seen anyone else seconding this feature.
