### ISSUE TITLE
[linux] Wrong ownership of the /var/lib/boinc directory

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#5324]
Install changed the ownership of the /var/lib/boinc directory to root from boinc. This resulted in the client not being able to write to the existing data directory.

Originally reported here: https://github.com/BOINC/boinc/discussions/5315#discussioncomment-6704426

**Comment by kotenok2000** [comment]
It happens at least since 7.18.1+dfsg-4 on ubuntu 22.04

**Comment by AenBleidd** [comment]
> > It happens at least since 7.18.1+dfsg-4 on ubuntu 22.04
> 
> It was probably done to suit the Android environment then, without proper care being taken to isolate it to that platform.

I'm not sure. I don't remember doing anything like this, also on Android we have a different structure.
I believe, it just became broken during attempts to fix Ubuntu packages (and since there was a lot of miscommunications with the distro maintainers, and a lot of disagreements, it was left in a 'dirty' state).
I'm gonna fix that soon and make our linux packages ready for testing this Fall.

**Comment by kotenok2000** [comment]
So they will be forced to rebuild it?

**Comment by kotenok2000** [comment]
Will there be new standalone boinc installers like https://boinc.berkeley.edu/dl/boinc_ubuntu_7.16.6_x86_64-pc-linux-gnu.sh
?

**Comment by AenBleidd** [comment]
Standalone installers are not currently planned.
We might provide standalone DEB and RPM packages for manual download and installation for OSs that are not listed on the page in my comment above.
But we might reconsider this if there will be a high demand.
Stay tuned.
