### ISSUE TITLE
[linux] wrong starting directory when running BOINC client from the systemctl

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#5325]
The systemd boinc-client.services file in /usr/lib/systemd/system tries to start the boinc-client out of /usr/local/bin instead /usr/bin.

Originally reported here: https://github.com/BOINC/boinc/discussions/5315#discussioncomment-6704426

**Comment by gj82854** [comment]
Information in #5315 (comment) has incorrect information. It should state that the systemd directory is /usr/lib/systemd/system NOT /var/lib/systemd/system. I mis-typed the comment

**Comment by AenBleidd** [comment]
@gj82854, thank you for the correction! I have fixed it in the description of this ticket.

**Comment by mcagriaksoy** [comment]
I have investigated the sourcecode but, I could not find any hard coded ` /usr/local/bin ` boinc-client starting instead of using `/usr/bin.`

**Comment by gj82854** [comment]
In the boinc/client/scripts/boinc-client.service.in file there is @EXEC_PREFIX@ value that is initialized in another file somewhere. About a month ago I was going through the code and found where that was set but, unfortunately, I didn't make a note of what file I found it in. It was set to usr/local. I'm not a developer so I'm not familiar with github and it's search capabilities. If you were searching for string usr/local/bin you may not find anything. I would suggest searching on EXEC_PREX or usr/local (leave off the bin) and see if that leads to something. I will go back try and find where I found that setting.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by gj82854** [comment]
It seems @EXEC_PREFIX@ is set in boinc/client/scripts/boinc-client.in. The comments indicate that it is set by autoconf. Maybe, the problem is in the build process and not the code itself. All of this is just speculation on my part

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
