### ISSUE TITLE
Not work “Show only alert” buton Event log window

### ISSUE THREAD

**Issue by Chamiu** [BOINC/boinc#5328]
**Describe the bug**
Not work “Show only alert” buton Event log window. -> Show blank Event log.

**Steps To Reproduce**
1. menubar -> Tools -> “Event log…”
2. open “BOINC Manager - Event log” window
3. select a line of project name inside columun “project”  2. window
4. tap “Show only alert” button.

**Expected behavior**
Only log of the selected project will be displayed in “BOINC Manager - Event log”

**Screenshots**
none

**System Information**
- OS: macOS Vwntura.5 on MacBook Air Late 2020 (Apple M1)
- BOINC Version: 7.24.1

**Additional context**
none

**Comment by AenBleidd** [comment]
Maybe there are just no alerts?
Are you sure you have any in your log?

**Comment by Vulpine05** [comment]
The show only alerts button just filters alerts, if any are present. If you want to see alerts of a particular project, you need to show only alerts and filter by project.  The order that you click on the buttons does not matter.

**Comment by Chamiu** [comment]
Sorry, I'm mistake operation.
I misidentified the "Show only this project" button and "Show only alert" because I thought there was a "Show only this project" button on the left.
"Show only alert" button add from 7.24 ?

**Comment by Chamiu** [comment]
> Sorry, I'm mistake operation.
> I misidentified the "Show only this project" button and "Show only alert" because I thought there was a "Show only this project" button on the left.
> "Show only alert" button add from 7.24 ?

self reply -> https://github.com/BOINC/boinc/pull/5313
