### ISSUE TITLE
Are any of these mouse/kbd lines still relevant?

### ISSUE THREAD

**Issue by BryanQuigley** [BOINC/boinc#5353]
**Describe the bug**
We check 3 devices that maybe never worked?
See first 3 idle_time lines here: https://github.com/BOINC/boinc/blob/master/client/hostinfo_unix.cpp#L2132

I noted it was described as not being useful in #1187 and it seems like it was mostly removed in https://github.com/BOINC/boinc/commit/0e16d026ce50fdadee8d3629bbdd95b5a5298416

It was discussed that it was not found in any modern distro to work. 

Does anyone know anywhere where it works?  If not, can we remove it?

The original line:
"    // We should find out which of the following are actually relevant
    // on which systems (if any)"
is from 16 years ago.

**System Information**
 - OS: Linux
 - BOINC Version:  master

**Comment by AenBleidd** [comment]
I suggest to continue this discussion in #1187, since it's not so nice to have several (we already have at least two) separate discussions about the same issue.
Closing this as a duplicate.
