### ISSUE TITLE
support sporadic apps

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#5358]
There are proposals for apps that need to compute sporadically; I'll call them 'sporadic apps'.
Typically, the computer running BOINC is acting as a worker node in a distributed computing system
outside of BOINC.
Such systems often involve some form of parallel computing:
lots of worker nodes must run at the same time,
typically exchanging data with other worker nodes using P2P communication or via a relay.
The app communicates with a server of this system to get work requests.
When a work request is active, BOINC should let the app use all the computing resources it needs,
preempting other jobs if necessary.

Implementing this requires some additions to BOINC's app API,
changes to the client, changes to vboxwrapper,
and changes to the logic of the app.

Proposed design:

client->app messages:
ok_to_compute (true or false)
    false if:
    - CPU (or GPU if relevant) computing is suspended
    - other projects have priority now (e.g. deadline crunch)
    This is sent every N sec for reliability

app->client messages:
computing_state
    - not computing and don't want to
    - not computing but want to
    - currently computing
    sent every N sec for reliability

client: new app type 'sporadic'
(along with regular and non-CPU-intensive).
Sporadic apps always run.
Various changes to scheduling logic (details TBD)

vboxwrapper: forward messages to/from the VM

app:
loop
   if get not OK to compute from BOINC client
      if computing, stop
      send "can't compute" message to server
  if get OK to compute from BOINC client
      send "can compute" to server
  if get request from server
     state = currently computing
     start computing

**Comment by davidpanderson** [comment]
Basic idea of changes to client scheduler:
add a 'sporadic scheduler' function to the main loop;
10 sec period is probably enough.

for each sporadic app
   if it's allowed to run (based on resource usage and user prefs)
      if app state is 'want to compute'
         reserve processors (pick GPU)
         do CPU reschedule
      send OK to run message
   else
      if status is computing
         free resources
         do CPU reschedule

**Comment by davidpanderson** [comment]
See https://github.com/BOINC/boinc/wiki/Sporadic-Applications/

**Comment by Rytiss** [comment]
One edge case: network is disabled, computing is enabled. If a sporadic app has a job, it could finish computing it, but it would not be allowed (although probably not enforceable) to send the results back to the guest system server and/or report that network is no longer available.

One could consider suspended networking to equal suspended computation, but there may be use cases where that isn't desirable, so it may be best to add an extra state for network access.

**Comment by Technologov** [comment]
what are "sporadic apps" and how are they different from "normal apps" ?

**Comment by AenBleidd** [comment]
@Technologov, please read detailed explanation here: https://github.com/BOINC/boinc/wiki/Sporadic-Applications

**Comment by nightblade9** [comment]
Are there any existing sporadic applications? Will there be a wiki page somewhere that lists them as they appear in BOINC?

**Comment by davidpanderson** [comment]
None so far, but hopefully soon.

**Comment by nightblade9** [comment]
Where can I find a list once there are one or more? Will it be on the BOINC wiki somewhere?
