### ISSUE TITLE
Mingw64 support

### ISSUE THREAD

**Issue by ahorek** [BOINC/boinc#5367]
**Describe the problem**
MSVC is a preferable choice on Windows, but it would be nice to support mingw64 (based on GCC 13).

Unfortunately, there are some platform issues. I've fixed some of them. It is sufficient for building Boinc libraries for a Boinc app on this platform, but not enough to fix everything (building a client is still failing).

Is there any interest in supporting this platform?

**Describe the solution you'd like**
build the whole project without errors on mingw64 platform.

**Additional context**
I can provide some fixes, but I'll need help with fixing other issues.

thanks!

**Comment by AenBleidd** [comment]
We support building BOINC libraries and sample applications for Windows using MinGW 10.3.0: https://github.com/BOINC/boinc/actions/workflows/mingw.yml?query=branch%3Amaster++
This is enough for the developers who would like to build their application to run on BOINC.
I don't see any reason we should support building the Client and Manager with the MinGW as well: BOINC is currently distributed for Windows with the installer that works on Windows Vista/7/8/8.1/10/11.
Also, last couple of years developers could build their applications for BOINC using `vcpkg`: https://github.com/microsoft/vcpkg/tree/master/ports/boinc

If you have any issues building BOINC libraries and/or sample applications - please open a separate ticket with the description of the environment (MinGW version) and exact error message.

**Comment by ahorek** [comment]
Thanks for the reply, Yes, I can confirm building just libraries is enough for an app to run on BOINC. This is what I need and it works without issues.
