### ISSUE TITLE
No rules at Private Messages

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#537]
**Reported by Ageless on 14 Sep 38138328 01:20 UTC**
I just noticed this, there are no rules shown when using the PM on any of the BOINC forums. Aren't the normal posting rules also in effect when PMing? 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/559

**Comment by romw** [comment]
**Commented by Nicolas on 8 Sep 38138600 08:00 UTC**
> Aren't the normal posting rules also in effect when PMing?
And maybe some more.

**Comment by Ageless93** [comment]
Rules are now a part of the PM system. 
See https://github.com/BOINC/boinc/commit/620ba64c72ca3b41e120e449bc9f31431c85ccd3
