### ISSUE TITLE
Remove two unnecessary null pointer checks for the variable “m_RPCWaitDlg”

### ISSUE THREAD

**Issue by elfring** [BOINC/boinc#5378]
:eyes: The member function “`CMainDocument::RequestRPC`” contains the statement “`m_RPCWaitDlg = new AsyncRPCDlg();`”.
[Redundant checks are still applied](https://github.com/BOINC/boinc/blob/ed69f05b396fcd09007181bb72ea61927f182bb0/clientgui/AsyncRPC.cpp#L659 "Update candidate: CMainDocument::RequestRPC()") (despite of this implementation detail).
:thought_balloon: Thus I suggest to remove them.

**Comment by AenBleidd** [comment]
You can go ahead and create a PR with the fix 😉

**Comment by elfring** [comment]
:crystal_ball: [The software evolution can be continued accordingly](https://github.com/BOINC/boinc/pull/5379 "Delete two unnecessary null pointer checks for the variable “m_RPCWaitDlg”"), can't it?

**Comment by elfring** [comment]
>…, and create the dialog only if it's actually used.

Will further source code adjustments belong to other issues? :thinking:

**Comment by AenBleidd** [comment]
@elfring, this particular request belongs to the same PR: #5379.

**Comment by elfring** [comment]
@davidpanderson did not add his comment as a direct contribution to my pull request for this issue.

**Comment by AenBleidd** [comment]
@elfring, ok, if you want, I can say next way: request of @davidpanderson belongs to this particular issue (#5378) and the corresponding PR (#5379)

**Comment by elfring** [comment]
:thought_balloon: I would prefer a clearer separation between remaining open issues for the affected software components.

**Comment by AenBleidd** [comment]
@elfring, you're the author of this issue. It was a request from the maintainer to improve your PR. This improvement belongs to the same component and to the same function that is touched by your PR.
Please, take into the consideration the comment from the maintainer and improve your PR.
Thank you in advance

**Comment by AenBleidd** [comment]
Closing this as 'not needed'. Please read more detailed explanation here: https://github.com/BOINC/boinc/pull/5379#issuecomment-1738925231
