### ISSUE TITLE
BOINC doesn't stop on android 13.

### ISSUE THREAD

**Issue by kozak243** [BOINC/boinc#5384]
Hi! I noticed my phone got really hot so I checked with 'top' command as super user in terminal emulator what's causing that. It was BOINC. I got so hot, it was hard to hold in my hands. I then realized: not only it was making my phone hotter than set (or than phone's throttling), it was using 100% of my CPU while not plugged into the charger and with screen turned on and unlocked. 4 separate things it didn't respect. I have no idea why is that. In previous custom ROMs it behaved the exact same way. I can provide any other info you need to diagnose that but I have no clue what can be needed.

![image](https://github.com/BOINC/boinc/assets/115477155/a6df538a-9f68-473b-a54b-65582c8c41bb)

**Comment by AenBleidd** [comment]
This is already fixed in #4189 and will be available in the next release.
