### ISSUE TITLE
Wrapper support for sporadic apps

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#5394]
The wrapped app (VM or native) needs to negotiate with the client about when to compute.
The easiest way to do this is via 2 files, client->app and app->client.
The wrapper (or vboxwrapper) reads/writes these,
converting to shared-memory message passing with the client.

**Comment by AenBleidd** [comment]
@davidpanderson, I thought this is already implemented. Could you please confirm?

**Comment by davidpanderson** [comment]
fixed in #5410
