### ISSUE TITLE
select app version based on CPU features

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#540]
**Reported by davea on 15 Oct 38154100 15:06 UTC**
Add new fields to app_version:
1. a tab-separated list of regular expression matched against the "features" list (SSE etc.)
2. a list of regular expressions matched against the "accelerators" list (GPUs and other coprocessors)
3. a "value"

The scheduler would send the highest-value app version
that for which the host matches all the reg exps

Migrated-From: http://boinc.berkeley.edu/trac/ticket/562

**Comment by romw** [comment]
**Commented by Nicolas on 22 Sep 38154161 13:46 UTC**
Reformat as a proper [list](WikiFormatting#Lists).

**Comment by ChristianBeer** [comment]
@davidpanderson I'm not sure if this is still relevant. Please closes or move to Server milestone.

**Comment by davidpanderson** [comment]
The plan class mechanism lets you do this.
