### ISSUE TITLE
Boinc is outdated on F-Droid

### ISSUE THREAD

**Issue by homersimpsons** [BOINC/boinc#5404]
- Boinc download should be available on F-Droid (https://boinc.berkeley.edu/download_all.php?platform=android)
- The latest version on F-Droid is 7.22.1 (https://f-droid.org/en/packages/edu.berkeley.boinc/)
- The latest version on GitHub is 7.24.1 (https://github.com/BOINC/boinc/releases/tag/client_release%2F7.24%2F7.24.1)

Can F-Droid repository be updated ?
Is there any way to automate it with the GitHub release ?

**Comment by AenBleidd** [comment]
@homersimpsons, I don't believe this is something we can automate.
I'll check and update it on F-Droid

**Comment by AenBleidd** [comment]
I'm not aware about the F-Droid release cycle, but merge request to update BOINC to 7.24.1 was already merged: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13901
