### ISSUE TITLE
Packages list needs to be updated?

### ISSUE THREAD

**Issue by Toby-Broom** [BOINC/boinc#5409]
**Describe the bug**
From the disussion here seems like this page is out of date, I tried to edit the wiki but seems like I can not.

**Steps To Reproduce**
1. got to this page https://github.com/BOINC/boinc/wiki/SoftwarePrereqsUnix
2. view items

**Expected behavior**
Packages are correct

**Screenshots**

**System Information**
 - OS: N/A
 - BOINC Version: mabey you upated the webview dependence

**Additional context**
[Add any other context about the problem here.](https://boinc.berkeley.edu/forum_thread.php?id=15029)

**Comment by Toby-Broom** [comment]
libcurl4-openssl-dev installs v8.2 which then fails around here in the m4 https://github.com/BOINC/boinc/blob/f9e6855e51e9ea4c5eb58af09a15bc980036ac71/m4/libcurl.m4#L222

**Comment by AenBleidd** [comment]
> libcurl4-openssl-dev installs v8.2 (on ubuntu 23.10) which then fails around here in the m4,when trying to make a build with --enable-client-release per https://github.com/BOINC/boinc/wiki/CompileClient
> 
> https://github.com/BOINC/boinc/blob/f9e6855e51e9ea4c5eb58af09a15bc980036ac71/m4/libcurl.m4#L222

This doesn't happen on Ubuntu 22.04. For me it looks like an issue in libcurl4-openssl-dev, not in the BOINC build system.

**Comment by Toby-Broom** [comment]
Can you help me as to what your are testing, it seems like something to do with lber ber_scanf but I'm not sure what these really are

**Comment by AenBleidd** [comment]
@Toby-Broom, I don't understand your question. Could you please rephrase it somehow? Thank you in advance.

**Comment by Toby-Broom** [comment]
@AenBleidd Sorry, what does this failing step do?

checking for curl-config... /usr/bin/curl-config
checking for the version of libcurl... 8.2.1
checking for libcurl >= version 7.17.1... yes

- checking for ber_scanf in -llber... no

checking whether libcurl is usable... no

I get the the other steps.

**Comment by AenBleidd** [comment]
@Toby-Broom, could you please share the content of the `/usr/bin/curl-config` file on your Ubuntu 23.10 installation?
I suspect in the new version of Ubuntu they deprecated some of the protocols supported by the curl

**Comment by AenBleidd** [comment]
@Toby-Broom, could you please also try to install `libldap-dev` manually?
E.g. sudo apt-get install libldap-dev
Does this resolve the issue?

**Comment by Toby-Broom** [comment]
@AenBleidd I think this migh be split in 2 issues? the not able to build seems like seperate topic to my orginal topic that the post on the BOINC forums seems missalined with the Wiki documentation here.

**Comment by Toby-Broom** [comment]
@AenBleidd i tried to go though the release notes from 7.81 in Jammy to 8.2.1 Mantic but there is so much that changed its hard for me since I don't have good knowldge of what BOINC needs.

#! /bin/sh
#***************************************************************************
#                                  _   _ ____  _
#  Project                     ___| | | |  _ \| |
#                             / __| | | | |_) | |
#                            | (__| |_| |  _ <| |___
#                             \___|\___/|_| \_\_____|
#
# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at https://curl.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
# SPDX-License-Identifier: curl
#
###########################################################################

prefix="/usr"
exec_prefix=${prefix}
cppflag_curl_staticlib=

usage()
{
    cat <<EOF
Usage: curl-config [OPTION]

Available values for OPTION include:

  --built-shared says 'yes' if libcurl was built shared
  --ca        ca bundle install path
  --cc        compiler
  --cflags    pre-processor and compiler flags
  --checkfor [version] check for (lib)curl of the specified version
  --configure the arguments given to configure when building curl
  --features  newline separated list of enabled features
  --help      display this help and exit
  --libs      library linking information
  --prefix    curl install prefix
  --protocols newline separated list of enabled protocols
  --ssl-backends output the SSL backends libcurl was built to support
  --static-libs static libcurl library linking information
  --version   output version information
  --vernum    output the version information as a number (hexadecimal)
EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

while test $# -gt 0; do
    case "$1" in
    # this deals with options in the style
    # --option=value and extracts the value part
    # [not currently used]
    -*=*) value=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) value= ;;
    esac

    case "$1" in
    --built-shared)
        echo yes
        ;;

    --ca)
        echo "/etc/ssl/certs/ca-certificates.crt"
        ;;

    --cc)
        echo "gcc"
        ;;

    --prefix)
        echo "$prefix"
        ;;

    --feature|--features)
        for feature in AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets alt-svc brotli libz threadsafe zstd ""; do
            test -n "$feature" && echo "$feature"
        done
        ;;

    --protocols)
        for protocol in DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS LDAP LDAPS MQTT POP3 POP3S RTMP RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP; do
            echo "$protocol"
        done
        ;;

    --version)
        echo libcurl 8.2.1
        exit 0
        ;;

    --checkfor)
        checkfor=$2
        cmajor=`echo $checkfor | cut -d. -f1`
        cminor=`echo $checkfor | cut -d. -f2`
        # when extracting the patch part we strip off everything after a
        # dash as that's used for things like version 1.2.3-CVS
        cpatch=`echo $checkfor | cut -d. -f3 | cut -d- -f1`

        vmajor=`echo 8.2.1 | cut -d. -f1`
        vminor=`echo 8.2.1 | cut -d. -f2`
        # when extracting the patch part we strip off everything after a
        # dash as that's used for things like version 1.2.3-CVS
        vpatch=`echo 8.2.1 | cut -d. -f3 | cut -d- -f1`

        if test "$vmajor" -gt "$cmajor"; then
            exit 0;
        fi
        if test "$vmajor" -eq "$cmajor"; then
            if test "$vminor" -gt "$cminor"; then
                exit 0
            fi
            if test "$vminor" -eq "$cminor"; then
                if test "$cpatch" -le "$vpatch"; then
                    exit 0
                fi
            fi
        fi

        echo "requested version $checkfor is newer than existing 8.2.1"
        exit 1
        ;;

    --vernum)
        echo 080201
        exit 0
        ;;

    --help)
        usage 0
        ;;

    --cflags)
        if test "X$cppflag_curl_staticlib" = "X-DCURL_STATICLIB"; then
          CPPFLAG_CURL_STATICLIB="-DCURL_STATICLIB "
        else
          CPPFLAG_CURL_STATICLIB=""
        fi
        echo "$CPPFLAG_CURL_STATICLIB"
        ;;

    --libs)
        CURLLIBDIR=""
        if test "Xyes" = "Xno"; then
          echo ${CURLLIBDIR}-lcurl -lnghttp2 -lidn2 -lrtmp -lssh -lssh -lpsl -lssl -lcrypto -lssl -lcrypto -lgssapi_krb5 -llber -lldap -llber -lzstd -lbrotlidec -lz
        else
          echo ${CURLLIBDIR}-lcurl
        fi
        ;;
    --ssl-backends)
        echo "OpenSSL v3+"
        ;;

    --static-libs)
        if test "Xyes" != "Xno" ; then
          echo -Wl,-Bstatic -lcurl -Wl,-Bdynamic -lnghttp2 -lidn2 -lrtmp -lssh -lssh -lpsl -lssl -lcrypto -lssl -lcrypto -lgssapi_krb5 -llber -lldap -llber -lzstd -lbrotlidec -lz
        else
          echo "curl was built with static libraries disabled" >&2
          exit 1
        fi
        ;;

    --configure)
        echo " '--build='\`dpkg-architecture -qDEB_BUILD_GNU_TYPE\` '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/'\`dpkg-architecture -qDEB_HOST_MULTIARCH\` '--runstatedir=/run' '--disable-maintainer-mode' '--disable-dependency-tracking' '--disable-symbol-hiding' '--enable-versioned-symbols' '--enable-threaded-resolver' '--with-lber-lib=lber' '--with-gssapi=/usr' '--with-nghttp2' '--includedir=/usr/include/'\`dpkg-architecture -qDEB_HOST_MULTIARCH\` '--with-zsh-functions-dir=/usr/share/zsh/vendor-completions' '--with-libssh' '--without-libssh2' '--with-openssl' '--with-ca-path=/etc/ssl/certs' '--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt' 'build_alias='\`dpkg-architecture -qDEB_BUILD_GNU_TYPE\` 'CFLAGS=-g -O2  -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection usr/src/curl-8.2.1-1ubuntu3.1 ' 'LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'"
        ;;

    *)
        echo "unknown option: $1"
        usage 1
        ;;
    esac
    shift
done

exit 0

**Comment by AenBleidd** [comment]
@Toby-Broom, have you tried to install 'libldap-dev' manually as I wrote above?

**Comment by Toby-Broom** [comment]
New error :)

apt -qq list libldap-dev
libldap-dev/mantic,now 2.6.6+dfsg-1~exp1ubuntu1 amd64 [installed]


checking for curl-config... /usr/bin/curl-config
checking for the version of libcurl... 8.2.1
checking for libcurl >= version 7.17.1... yes
checking for ber_scanf in -llber... yes
checking whether libcurl is usable... no
configure: error: 
================================================================================
ERROR: could not find (recent enough) development-libs for libcurl.

  If libcurl-dev is installed on your system, make sure that the script
  'curl-config' is found in your PATH, and that
  'curl-config --version' gives something recent enough (see above).

  You can download libcurl from: http://curl.haxx.se/

libcurl-dev does not exist as a package 

apt list libcurl-dev
Listing... Done

apt list libcurl*
Listing... Done
libcurl-ocaml-dev/mantic 0.9.2-3build4 amd64
libcurl-ocaml/mantic 0.9.2-3build4 amd64
libcurl3-gnutls/mantic-updates,mantic-security,now 8.2.1-1ubuntu3.1 amd64 [installed,automatic]
libcurl3-gnutls/mantic-updates,mantic-security 8.2.1-1ubuntu3.1 i386
libcurl3-nss/mantic-updates,mantic-security 8.2.1-1ubuntu3.1 amd64
libcurl3-nss/mantic-updates,mantic-security 8.2.1-1ubuntu3.1 i386
libcurl4-doc/mantic-updates,mantic-updates,mantic-security,mantic-security 8.2.1-1ubuntu3.1 all
libcurl4-gnutls-dev/mantic-updates,mantic-security 8.2.1-1ubuntu3.1 amd64
libcurl4-gnutls-dev/mantic-updates,mantic-security 8.2.1-1ubuntu3.1 i386
libcurl4-nss-dev/mantic-updates,mantic-security 8.2.1-1ubuntu3.1 amd64
libcurl4-nss-dev/mantic-updates,mantic-security 8.2.1-1ubuntu3.1 i386
libcurl4-openssl-dev/mantic-updates,mantic-security,now 8.2.1-1ubuntu3.1 amd64 [installed]
libcurl4-openssl-dev/mantic-updates,mantic-security 8.2.1-1ubuntu3.1 i386
libcurl4/mantic-updates,mantic-security,now 8.2.1-1ubuntu3.1 amd64 [installed,automatic]
libcurl4/mantic-updates,mantic-security 8.2.1-1ubuntu3.1 i386
libcurlpp-dev/mantic 0.8.1-5.1 amd64
libcurlpp0/mantic 0.8.1-5.1 amd64

**Comment by AenBleidd** [comment]
You haven't installed 'libcurl4-dev'

**Comment by Toby-Broom** [comment]
Package libcurl4-dev is a virtual package provided by:
  libcurl4-nss-dev 8.2.1-1ubuntu3.1
  libcurl4-openssl-dev 8.2.1-1ubuntu3.1
  libcurl4-gnutls-dev 8.2.1-1ubuntu3.1

libcurl4-openssl-dev/mantic-updates,mantic-security,now 8.2.1-1ubuntu3.1 amd64 [installed]

Could be a packaging problem?

Side note also libcurl 7.17.1 was released in 2007, its seem like curl has plenty of securtiy issue, so a min newer version would be  lower risk.  If I want to build BOINC 5.2 fair to use old version.

**Comment by AenBleidd** [comment]
'libcurl4-openssl-dev' is the correct one

**Comment by AenBleidd** [comment]
This is not a packaging problem. This is just an outdated documentation.

**Comment by AenBleidd** [comment]
I have updated the page. Should be fine now.
@Toby-Broom, please test. If this works for you - then let me know, and I'll close this ticket.

**Comment by Toby-Broom** [comment]
Great thanks
