### ISSUE TITLE
Documentation update for compiling boinc server

### ISSUE THREAD

**Issue by makeasnek** [BOINC/boinc#5412]
Just a quick update on this documentation since I don't have wiki editing permissions:
https://github.com/BOINC/boinc/wiki/SoftwarePrereqsUnix

On Ubuntu 20.04.6 I was able to install the dependencies with:
`sudo apt install m4 autoconf libtool`

libtool and autoconf are missing from the current apt get line

**Comment by AenBleidd** [comment]
Page is updated. Thank you for noticing this.
