### ISSUE TITLE
Multi GPU not consistantly applied

### ISSUE THREAD

**Issue by Toby-Broom** [BOINC/boinc#5417]
**Describe the bug**
BOINC said its using 2 different GPUs but nvidia-SMI said its only using 1

**Steps To Reproduce**
1. Run Einstien WU
2. Inspect data in BOINC and nvidia-smi

**Expected behavior**
Consistnely applied to both GPUs

**Screenshots**
![image](https://github.com/BOINC/boinc/assets/27242647/ddceadfa-7d1b-4a5f-bb9c-8fdd2d95db78)
![image](https://github.com/BOINC/boinc/assets/27242647/2e25d704-e901-47df-8d88-ea5e6b56cd27)

**System Information**
 - OS: Ubuntu 23.10, nvidia driver 535
 - BOINC Version: 7.24.1

**Additional context**
its not consistent, sometimes it goes to both GPU, so maybe its a timing thing where it doesn't check

**Comment by AenBleidd** [comment]
@Toby-Broom, as you can see on the first screenshot, BOINC client told the running application which GPU it should use.
Please report this issue to Einstein@home, because it looks like their application just ignores the value from the BOINC client, and uses incorrect GPU.

**Comment by Toby-Broom** [comment]
Thanks for the clarification, I pass over to them
