### ISSUE TITLE
Show stderr for aborted tasks

### ISSUE THREAD

**Issue by hucker75** [BOINC/boinc#5425]
**Describe the problem**
Not sure if this is something Boinc is not doing, or a problem with Ralph, the Alpha test for Rosetta.  These are VB tasks.

A [task](https://ralph.bakerlab.org/result.php?resultid=5433248) was sent to me with the usual 3 day deadline, but it ran for 5 days, using 100% of a CPU core.  I eventually gave up and aborted it, even though they say not to abort them, as this one looked like it would go on indefinitely.  I assumed it would have useful information in stderr for them to work out why it was stuck in a loop, but the information is not there.  Strangely on my task list [https://ralph.bakerlab.org/results.php?userid=86770](https://ralph.bakerlab.org/results.php?userid=86770) it shows as 0 CPU time, which is untrue, it was using a whole core for 5 days.

However [this one](https://ralph.bakerlab.org/result.php?resultid=5432455) shows plenty information.

Also posted to Ralph forum: [https://ralph.bakerlab.org/forum_thread.php?id=916](https://ralph.bakerlab.org/forum_thread.php?id=916)

**Describe the solution you'd like**
Stderr should have information even though the task is stopped part way, as it could be useful to figure out what caused it to never finish.

**Comment by AenBleidd** [comment]
VBox log is written to the separate file, and IIRC this file is usually transferred to the server when WU is aborter. However, the information from this file is usually not shown on the web UI.
It would be nice here to clarify from the Project admins that they have received all the logs, and if this is true - then this ticket could be closed.

**Comment by hucker75** [comment]
Unfortunately I've not seen anything from the project admins in Rosetta or Ralph in a long time.  They don't seem to interact with their users anymore.  If you need to test it, it would be best to set something up with another project.  I'll copy what you just said to the forum incase they're listening.

**Comment by davidpanderson** [comment]
I haven't looked at vboxwrapper in a while.  If the app (running in the VM) writes to stderr, what happens to it?  It should probably get written to a file in shared/, which should then get copied to the slot directory when the job finished or is aborted.  That way it would end up on the server.

**Comment by davidpanderson** [comment]
The vbox log, IIRC, contains what vboxwrapper is doing, not what the app is doing.  Also, I think it's copied to the server only if it's listed as an output file of the job.

**Comment by hucker75** [comment]
> I haven't looked at vboxwrapper in a while. If the app (running in the VM) writes to stderr, what happens to it? It should probably get written to a file in shared/, which should then get copied to the slot directory when the job finished or is aborted. That way it would end up on the server.

Agreed, if it's not doing this, aborted tasks could end up like mine with nothing for the project staff to look at, so no way of knowing if I aborted it because I didn't want to do it, or because it was stuck in a loop.

**Comment by davidpanderson** [comment]
Peter, do you do any C++?
(unfortunately vboxwrapper is kind of a big mess right now)

**Comment by hucker75** [comment]
Sorry, I'm not a programmer at all.
