### ISSUE TITLE
macOS Dark Mode Does Not Work

### ISSUE THREAD

**Issue by aaronraimist** [BOINC/boinc#5434]
**Describe the bug**
I updated to BOINC 7.42.2 but dark mode still does not work on macOS.

According to #5267 and the release notes for version 7.42.1, dark mode should work when using the BOINC advanced view on macOS.

**Steps To Reproduce**
1. Enable dark mode
2. Open BOINC
3. Open advanced view

**Expected behavior**
BOINC uses dark mode

**Screenshots**
<img width="1706" alt="screenshot 1" src="https://github.com/BOINC/boinc/assets/5855073/489285b4-4c69-4ca0-a513-35be58a92a0a">

<img width="752" alt="screenshot 2" src="https://github.com/BOINC/boinc/assets/5855073/630e7879-a035-481f-b1d6-75750579ca05">

**System Information**
 - OS: macOS 13.6.2
 - BOINC Version: 7.24.2
 - wxWidgets Version: 3.2.2

**Comment by AenBleidd** [comment]
@aaronraimist, does your MacOS currently in the Dark Mode? BOINC Manager follows the current system settings when switching to/from Dark Mode

**Comment by AenBleidd** [comment]
@CharlieFenton, could you please take a look?

**Comment by aaronraimist** [comment]
> @aaronraimist, does your MacOS currently in the Dark Mode? BOINC Manager follows the current system settings when switching to/from Dark Mode

@AenBleidd Yes. I keep macOS in dark mode all the time. I also tried switching between light and dark mode while BOINC was running but that didn't help.

**Comment by CharlieFenton** [comment]
It works for me (Mac OS 14.1.1 on M1 iMac.) What version of MacOS are you running?
<img width="2149" alt="Screenshot 2023-11-21 at 9 04 52 PM" src="https://github.com/BOINC/boinc/assets/10470356/1f54a59b-18b8-4468-84e7-86d96675a4c9">

**Comment by aaronraimist** [comment]
macOS 13.6.2

I did some more investigating and for some reason `NSRequiresAquaSystemAppearance = 1;` was in `defaults read edu.berkeley.boinc`. I don't know if there is some migration that didn't run properly or what. After running `defaults delete edu.berkeley.boinc NSRequiresAquaSystemAppearance` dark mode is working properly. I'll assume this was just a problem on my computer so I'll close this.

**Comment by CharlieFenton** [comment]
Sorry, I just saw that you are running MacOS 13.6.2. The latest version of Ventura I have installed is 13.6, and dark mode works fine on my M1 iMac under that version of MacOS as well. I looked into updating to 13.6.2, but the last version of Ventura the App Store offers my compute is 13.6.1. I suspect perhaps 13.6.2 was for Intel Macs only? While it's possible that something changed from 13.6 to 13.62 that would affect BOINC's dark mode, that seems unlikely.

We have not had any other reports of dark mode not working for BOINC 7.24.2.

**Comment by aaronraimist** [comment]
13.6.2 is only for 2021-2023 MacBook Pros and 2023 iMacs. It only changes a few small things so I don't suspect it is the OS.

My suspicion is some step during the installer process didn't run properly on my machine for some reason since getting rid of that preference is one of the things your PR did https://github.com/BOINC/boinc/pull/5267/files#diff-ddd78afa21f77629932ead5b4f67a3db10ed1d6bad0a18c923199023acb3aadd. 

I only run BOINC in the winter (to avoid the heat of my computers fighting A/C) so before I updated to 7.24.2 I was probably running a version that was nearly a year old. Perhaps that's updating from that relatively old version was the cause or just more likely just a fluke. Either way, glad it's working now. Thanks for the quick response.
