### ISSUE TITLE
Boinc Server 1.4.2

### ISSUE THREAD

**Issue by oppiet30** [BOINC/boinc#5441]
**Describe the bug**
Deprecated: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /home/boincadm/boinc/projects/html/user/login_action.php on line 163

Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /home/boincadm/boinc/projects/html/user/login_action.php on line 186
**Steps To Reproduce**
1. git clone https://github.com/BOINC/boinc.git
2. cd boinc
3. git checkout tags/server_release/1.4/1.4.2 -b server_release/1.4.2
4. followed instructions to compile.
5. followed instructions to create a project.
6. 

**Expected behavior**
It to work
**Screenshots**

**System Information**
 - OS: 
 - BOINC Version: 

**Additional context**

**Comment by oppiet30** [comment]
PHP 8.2.13 (cli) (built: Nov 21 2023 09:55:59) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.2.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.13, Copyright (c), by Zend Technologies

**Comment by oppiet30** [comment]
Also have these two deprecations:
Deprecated: Creation of dynamic property BoincUser::$prefs is deprecated in /home/boincadm/boinc/projects/html/inc/forum_db.inc on line 164
Deprecated: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /home/boincadm/boinc/projects/html/user/login_form.php on line 26

**Comment by AenBleidd** [comment]
@davidpanderson, could you please take a look?
