### ISSUE TITLE
Show history of last checkpoints made (eventually with a time graph)

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#545]
**Reported by 512upload on 24 Aug 38165136 12:26 UTC**
The title pretty much says everything about the new feature suggestion I'm making...

Migrated-From: http://boinc.berkeley.edu/trac/ticket/567

**Comment by romw** [comment]
**Commented by Nicolas on 22 Sep 38165146 01:46 UTC**
But useful descriptions won't make any harm...

I think this feature is more appropriate for a 3rd party manager. When [enabling checkpoint_debug](ClientMessages), addons have access to the checkpoint times, enough information to make a graph.

**Comment by romw** [comment]
**Commented by Nicolas on 21 Oct 38168147 18:13 UTC**
Replying to [Nicolas](comment:1):
> When [enabling checkpoint_debug](ClientMessages), addons have access to the checkpoint times, enough information to make a graph.
Although it would be preferred if the core client could export such internal data in a better format (and available without annoying users with debug messages).

**Comment by ChristianBeer** [comment]
The current (7.6.33) Manager displays time of last checkpoint. I don't see the need to make a graph from this information or make it a non-debug feature.
