### ISSUE TITLE
No Work on One [;atform

### ISSUE THREAD

**Issue by awilddog** [BOINC/boinc#5454]
I have 3 Windows 11 computers 2 laptops, and one tablet.  One of the laptops "Dynabook" does not receive work for World Community Grid, nore does it show up in "devices". The lack of work began after the latest Windows 11 update.  Has anyone else run across this problem?  Work for "Asteroids@home" is received.

**Comment by AenBleidd** [comment]
WCG nowadays has issues from time to time, and they don't always have work available. You should check their website.

**Comment by awilddog** [comment]
Actually, the problem was "local".  After reinstalling BOINC, during the install and adding WCG as a project, I realized that somehow my user id ***@***.******@***.***> had been corrupted to ***@***.******@***.***>.  After correcting - everything words fine.
