### ISSUE TITLE
[macOS] [OpenCL] [ARM] Boinc AppleM (ARM) client cannot run OpenCL programs after update to Sonoma

### ISSUE THREAD

**Issue by stream1972** [BOINC/boinc#5456]
**Describe the bug**

Important Note: this bug may be specific only to AppleM (i.e. ARM) version of Mac OS and/or client running on M1/M2 CPU.

After recent update of MacOS to Sonoma, all OpenCL programs from all projects started to fail with following error message from Mac OpenCL stack:
```
UNSUPPORTED (log once): buildComputeProgram: cl2Metal failed
<built-in>:1:10: fatal error: cannot open file './opencl-c.h': Permission denied
#include "opencl-c.h"
         ^
```
And application exits because OpenCL kernel cannot be compiled.

I've asked one of users to run this application from command line under normal user account. It worked without errors.

```
geneferg version 22.12.2 (macOS arm64, clang-15.0.3, boinc-7.20.2)
Copyright (c) 2022, Yves Gallot
genefer is free source code, under the MIT license.

Command line: '-h'

Running on device 'Apple M1', vendor 'Apple', version 'OpenCL 1.2 ', driver '1.2 1.0'.
330000000^{2^15} + 1: 00:02:16, 0.147 ms/bit, data size: 1.12 MB.
200000000^{2^16} + 1: 00:08:17, 0.275 ms/bit, data size: 2.25 MB.
... (and so on) ...
```

This makes me think that Mac ARM Boinc client or its account **has not enough privileges**, causing OpenCL stack to fail in its operations when application is started from Boinc client.

**Steps To Reproduce**
1. Get a Mac with M1 or M2 processor.
2. Attach to project with native support for M1/M2 GPU (for example, any of "Genefer" or "AP27" applications on PrimeGrid).
3. All tasks will fail with error above.

To check that application is working under normal user account:
1. Download Genefer AppleM GPU application from https://primegrid.com/download/genefer22g_macarm64_22.12.02
2. If gmp is not installed in the system (using homebrew or somehow else), download https://www.primegrid.com/download/macarm64_libgmp.10.dylib , rename it to `libgmp.10.dylib` and put in same folder as main executable.
3. Make main file executable: `chmod +x genefer22g_macarm64_22.12.02`
4. Run program in "benchmark" mode: `./genefer22g_macarm64_22.12.02 -h`
5. The program should run and print some information about throughput of your system like in the log above.

**Expected behavior**
It worked before update to Sonoma

**System Information**
 - OS: Mac OS ARM, M1/M2 CPU/GPU.
 - BOINC Version: 7.22.2, 7.24.2

**Comment by AenBleidd** [comment]
There was already a report about this. User has found the next solution:
"To solve this issue, I had to uninstall and reinstall BM!".

@CharlieFenton, could you please check if there is a better solution to automatically fix this problem?

**Comment by CharlieFenton** [comment]
> all OpenCL programs from all projects started to fail

Not all projects have OpenCL applications, and I don't see a file _opencl-c.h_. 
Which projects and what are the projects' application? 
What is the path to the file _opencl-c.h_?
Are the projects sending this file along with the application's executables and data?

If it is a permissions issue, then reinstalling BOINC is the standard and simplest solution. But if it is a file downloaded as part of a project's application, there may be a problem in the way the project handles it.

**Comment by CharlieFenton** [comment]
It's not unusual for a MacOS update to mess up BOINC's permissions, requiring a reinstall of BOINC. What is surprising here is that in those cases, BOINC normally refuses to run and instead shows an alert saying that there is a problem with permissions and asking the user to reinstall it, but it sounds like that did not happen here.

FWIW, the previous report (n the BOINC Alpha email list) said the person had to "uninstall and reinstall" BOINC Manager; it's unclear whether just running the installer was sufficient to fix it without first running the _Uninstall BOINC_ utility..

**Comment by stream1972** [comment]
> Not all projects have OpenCL applications, and I don't see a file opencl-c.h.

All AppleM OpenCL applications are failing now. This not a PrimeGrid-only stuff, although easiest way to test it is to try PG's any of "Genefer" series or "AP27" application for AppleM.

opencl-c.h is a system file, part of the OS itself. It's used internally by OS / video drivers / OS OpenCL stack. Any OpenCL application calls clCreateKernel() API which does very complex job compiling OpenCL program source code into GPU machine code. When running under Boinc, this call fails returns "Permission denied" error message above. It works when app is run under normal account. 

The account used by client is definitely lacking something, its permissions are insufficient to read system file `opencl-c.h`. One of users reported that this file is world-readable but it's not working anyway, so some other kind of security/access rights can be involved. But I have no Mac and cannot test. May be client must be added to one more group to be able to access OpenCL API in Sonoma? (Like 'video' group in Linux). If you can post few commands to query information about capabilities of Boinc service account and possible security attributes of given file (and compare them with normal account), users definitely will help you to find a difference / missing bit.

> FWIW, the previous report (n the BOINC Alpha email list) said the person had to "uninstall and reinstall" BOINC Manager; it's unclear whether just running the installer was sufficient to fix it without first running the Uninstall BOINC utility..

Before posting this report, I've asked user to upgrade Boinc to latest version to be sure that problem still exist (7.22.2 -> 7.24). Nothing changed, i.e. reinstall or upgrade will not help. I'll ask him to do full uninstall first.

**Comment by CharlieFenton** [comment]
I have reproduced this on my M1 iMac, but it did not involve updating or reinstalling MacOS. I have been running MacOS 14.1.1 Sonoma for some time. I had run PrimeGrid several years ago, but was not attached to the project currently. I updated my PrimeGrid preferences to have them send me only tasks for M1 GPUs, then attached to PrimeGrid.

I then received a genefer20 task which failed immediately with the same error you reported:
> <built-in>:1:10: fatal error: cannot open file './opencl-c.h': Permission denied

I then reset the project to prevent BOINC from reporting the error, in case that would cause PrimeGrid to delay sending me a new task. After I received another genefer20 task, but before I allowed it to start, I uninstalled and reinstalled BOINC Manager. The PrimeGrid task has been running happily now for over 45 minutes.

This indicates that the problem also occurs when PrimeGrid is first downloaded. Reinstalling BOINC Manager sets all permissions in the BOINC Data directory and its subdirectories. So it's possible that there may be a problem with the permissions in the files downloaded from PrimeGrid that get corrected when BOINC is then reinstalled, and that somehow caused the permissions error reading _opencl-c.h_, though it's not at all clear to me how.

> opencl-c.h is a system file, part of the OS itself

In that case, there is of course no way that reinstalling BOINC could modify the permissions of opencl-c.h.

The current PrimeGrid task is only 0.4% complete after 48 minutes. After it finishes (which could be a few days at this rate), I will again reset the project and update it to get a fresh download of its files. I will then examine their ownership and permissions before and after again reinstalling BOINC Manager to see if her is any useful information there.

**Comment by stream1972** [comment]
I suggest to select "Genefer 16" application only and abort existing tasks. All Genefer applications are using same executable file, and Genefer 16 is shortest one, task will finished in few minutes. Also you can try AP27 application.

**Comment by CharlieFenton** [comment]
The _genefer20_ task finally completed successfully.

 I performed the following test sequence:
Set my PrimeGrid preferences to run only _Genefer16_ applications
Detached from PrimeGrid
Uninstalled BOINC Manager
Reinstalled BOINC Manager to (hopefully) get back to the state before installing PrimeGrid
Suspended all computation, but allowed network activity
Reattached to PrimeGrid
Allowed PrimeGrid to download its files including one _Genefer16_ task
suspended network activity
set PrimeGrid to No New Tasks
Made a copy of the BOINC Data directory, preserving all ownership, permissions, ACLs, etc. (`cp -pR` in Terminal.)
Set Use GPU Always and Run Always
The task succeeded

I had hoped this sequence would cause the task to fail so that I could reproduce my earlier failure and examine the ownerships and permissions before the failure, but since it succeeded I wasn't able to do that. 

I don't know what to try next to try to analyze the problem. I won't have more time to spend on this until after the New Year.

**Comment by CharlieFenton** [comment]
@stream1972 I think I've found the cause of the problem and have submitted a solution as PR #5502. It warns the user if a reinstall is necessary after a system update and refuses to run until the reinstall is done. The changes also eliminate the need to uninstall before reinstalling.

I'll release a new build probably early next week for you to try.

**Comment by davidpanderson** [comment]
Thanks for the quick fix.  I posted a news item announcing the new version.

**Comment by MagicQuantumMechanic** [comment]
> BOINC 7.24.3

Is that ready for an update somewhere David?
(was just checking at LHC)

**Comment by AenBleidd** [comment]
> > BOINC 7.24.3
> 
> 
> 
> Is that ready for an update somewhere David?
> 
> (was just checking at LHC)

Check it here: https://boinc.berkeley.edu/download.php

**Comment by MagicQuantumMechanic** [comment]
I don't see BOINC 7.24.3 there 
It is still  7.24.1

**Comment by brevilo** [comment]
Just for the record: this issue also caused our Metal app to crash with a signal 6 (`SIGABRT`) on 70% of the tasks. I reported that in the previous projects call. It turned out that, on Apple Silicon, OpenCL and Metal are both using the private `GPUCompiler` framework to compile kernels at runtime (when needed). Said compilation failed due to the permission issue with the following, similar error:
```
<built-in>:1:10: fatal error: cannot open file './metal_types': Permission denied
#include "metal_types"
         ^
```
BOINC 7.24.3 indeed seems to have fixed that.

Cheers

**Comment by bema-aei** [comment]
@davidpanderson Mac users complain that they didn't get notified of the new version in the client (or manager). I don't know how this notification works, but could that be arranged?

**Comment by AenBleidd** [comment]
@bema-aei, users are not notified because this is an alpha version, and it's not recommended to use yet.
Users who installed it, did that manually using the notification from the email for alpha testers.
That is why it's quite strange to hear such complain, because this is our usual way of work.

**Comment by brevilo** [comment]
The version in this context is 7.24.3 and that's offered here: https://boinc.berkeley.edu/download.php

How can this be an alpha version?

**Comment by davidpanderson** [comment]
8.0 is being alpha tested; the client notifies users only of new recommended versions.

The 8.0 client reports Apple GPUs as type 'apple_gpu'.
Make sure you have the appropriate plan classes.

**Comment by brevilo** [comment]
Thanks Charlie!

**Comment by AenBleidd** [comment]
@brevilo, sorry for my previous reply. I messed up a little bit another ticket. My bad.
