### ISSUE TITLE
More PHP 8 deprecation warnings

### ISSUE THREAD

**Issue by gchilders** [BOINC/boinc#5467]
Here are three more PHP 8 deprecation warnings I've found in the current code.

PHP Deprecated:  Implicit conversion from float-string "2564.529459" to int loses precision in /html/inc/util.inc on line 444
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in html/inc/util.inc on line 1042
PHP Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in html/inc/boinc_db.inc on line 147

**Comment by AenBleidd** [comment]
@davidpanderson, could you please take a look?

**Comment by gchilders** [comment]
One more just popped up in my logs.

 PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in html/inc/user.inc on line 229

**Comment by gchilders** [comment]
And these:
Deprecated: round(): Passing null to parameter #1 ($num) of type int|float is deprecated in html/user/server_status.php on line 180
Deprecated: round(): Passing null to parameter #1 ($num) of type int|float is deprecated in html/user/server_status.php on line 181
Deprecated: round(): Passing null to parameter #1 ($num) of type int|float is deprecated in html/user/server_status.php on line 182

**Comment by gchilders** [comment]
The first two are still present. However, the line numbers I reported are wrong due to stuff added to page_tail_aux() in my local code.  Here they are again with the correct line numbers. Sorry about that.

PHP Deprecated: Implicit conversion from float-string "2564.529459" to int loses precision in /html/inc/util.inc on line 424
PHP Deprecated: trim(): Passing null to parameter https://github.com/BOINC/boinc/issues/1 ($string) of type string is deprecated in html/inc/util.inc on line 1022

**Comment by gchilders** [comment]
And add...
PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in html/user/am_set_info.php on line 132
