### ISSUE TITLE
BOINC wrapper does not suspend task processes

### ISSUE THREAD

**Issue by piedar** [BOINC/boinc#5480]
**Describe the bug**

As of #3045, the BOINC wrapper started sending `SIGTSTP` instead of `SIGSTOP` to suspend its child processes.

On my Linux systems `SIGTSTP` works only for processes connected to a TTY.  I suspect there is some arcane historical reason for this requirement.  [BSD documents this signal](https://man.freebsd.org/cgi/man.cgi?sektion=3&query=signal) as a "stop  signal generated from keyboard" but doesn't say whether it's supposed to work for a detached daemon process.

For example, this doesn't work.

```
$ ps 175008
    PID TTY      STAT   TIME COMMAND
 175008 ?        RN   794:41 cmdock -c -j 1 -b 1 -x -r target.prm -p /opt/cmdock-0.2.0/data/scripts/dock.prm -f htvs.ptc -i ligands.sdf -o docking_out
$ sudo kill -SIGTSTP 175008
$ ps 175008
    PID TTY      STAT   TIME COMMAND
 175008 ?        RN   794:41 cmdock -c -j 1 -b 1 -x -r target.prm -p /opt/cmdock-0.2.0/data/scripts/dock.prm -f htvs.ptc -i ligands.sdf -o docking_out
```

But `SIGSTOP` does work.

```
$ sudo kill -SIGSTOP 175008
$ ps 175008
    PID TTY      STAT   TIME COMMAND
 175008 ?        TN   797:42 cmdock -c -j 1 -b 1 -x -r target.prm -p /opt/cmdock-0.2.0/data/scripts/dock.prm -f htvs.ptc -i ligands.sdf -o docking_out
```

So the change in #3045 has made it impossible for the BOINC wrapper to suspend job processes and it should be reverted.  The BOINC wrapper should send `SIGSTOP` to its child processes.

**Steps To Reproduce**
1. Run a task using the latest [wrapper/26018](https://github.com/BOINC/boinc/releases/tag/wrapper%2F26018) release.
2. Suspend the task.
3. Notice that the task appears suspended in BOINC but its worker process keeps running.

**Expected behavior**

The task's worker process should go into a stopped state, shown as `T` by `ps` and `htop`.

**System Information**
 - OS: x86_64-pc-linux-gnu
 - BOINC Version: 7.22.0

**Additional context**

This bug does not appear when running the official cmdock binaries because they ship an old version of the BOINC wrapper from back before the bug was introduced.  I only noticed it while trying out the [anonymous platform](https://boinc.berkeley.edu/wiki/Anonymous_platform) feature with the latest BOINC wrapper.

**Comment by AenBleidd** [comment]
@lfield, since you were the author of that change, could you please validate this issue?
Thank you in advance.

**Comment by lfield** [comment]
This might not be related to the terminal but the fact that the SIGTSTP signal is not acted upon. In the general case we probably just want the process to be stopped, so this change should probably be reverted. In the cases where is is needed a custom wrapper should probably be used.

**Comment by davidpanderson** [comment]
All the docs say that SIGTSTP should work, even for processes without a TTY.
And yet (on my Ubuntu system) it doesn't.

I'll make a PR that changes the default to SIGSTOP,
but adds a cmdline option to wrapper to use SIGTSTP instead
(for cases where the wrapped program is itself a wrapper of some sort).

**Comment by kotenok2000** [comment]
Why didn't you reuse official old wrapper for cmdock?

**Comment by piedar** [comment]
> Why didn't you reuse official old wrapper for cmdock?

No special reason - I just used the [boinc-wrapper](https://gitweb.gentoo.org/repo/proj/guru.git/tree/sci-misc/boinc-wrapper) package from GURU.  Didn't know it would make any difference at the time.
