### ISSUE TITLE
[client] Incorrect CPU time shown when application is running with the wrapper

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#5494]
When application is launched by BOINC client using the wrapper, CPU time is shown incorrectly (looks like it shows the CPU time of the wrapper itself, not the actual running application).
Elapsed time is shown correctly, but such a low CPU time might confuse users who don't aware that application is using a wrapper, and might think that the application has been stuck.

![image](https://github.com/BOINC/boinc/assets/3234209/18d6ce9e-78d1-47a0-9fa7-487c1924b4bb)

**Comment by davidpanderson** [comment]
The Rakesearch application is unusual.
It has a main program, spstarter.exe.
It runs a subprogram, CanCPUCoreAssa.exe.
This runs for a second or two, then exits.
spstarter.exe then runs it again, over and over.

The way the wrapper measures CPU isn't designed for this.
Every 10 seconds it looks at the process tree of the main process
and adds up the CPU time of the descendants.
If subprocesses started and exited within those 10 seconds,
it doesn't see them.

I can't think of a way to measure CPU time that works with
lots of short subprocesses.
Maybe Rake Search can restructure their app to avoid this.
