### ISSUE TITLE
use substrate?

### ISSUE THREAD

**Issue by gogo2464** [BOINC/boinc#5508]
**Describe the problem**
avoid to recode everything

**Describe the solution you'd like**
We might use substrate library.I need your opinion.

**Comment by AenBleidd** [comment]
BOINC doesn't use Blockchain

**Comment by gogo2464** [comment]
ah sorry!!!it is a serverless proof ok sorry!!!

**Comment by gogo2464** [comment]
ok because from what I see in the project, you proove that some calculus has been done.

It is a great amount of process. And I think we should use useful work to slow operation in bitcoin like crypto transaction instead of bruteforcing useless hash.

**Comment by AenBleidd** [comment]
@gogo2464, https://gridcoin.us/

**Comment by gogo2464** [comment]
thanks!

**Comment by gogo2464** [comment]
ah ok so BOINC is the list of project where gridcoin is the proof?

thanks!!!
