### ISSUE TITLE
Static screen when running

### ISSUE THREAD

**Issue by garnetri** [BOINC/boinc#5516]
The BOINC program leaves a static image on screen for some projects (Looking at you SETI) and this has resulted in a screen burn on my brand new monitor... I would request that all projects be checked for static images before having people's computers run them. At a cursory glance, admittedly quite cursory, I don't see any options regarding what to display while the project is running.

**Comment by davidpanderson** [comment]
The BOINC screensaver itself doesn't have static images.
Some of the project-specific graphics programs may have static images.
SETI@home hasn't been active for several years.
The screensaver is optional; you can turn it off.
