### ISSUE TITLE
Boinc 7.25.0 (builds of 4th and 5th March 2024) wont run boinc NCI apps in NCI mode

### ISSUE THREAD

**Issue by borg17** [BOINC/boinc#5529]
**Describe the bug**
Old Boinc 7.24.1 will run wuprop@home and radioactive@home NCI apps (Non-CPU-intensive) in NCI mode

new Boinc 7.25.0 will run them in normal mode (and even try to get more then 1 WU)

**Steps To Reproduce**
1. try BOINC 7.24.1 on Windows with some work units and 1 wuprop@home (and if geiger counter aviable radioactive@home)
2. compare it with BOINC 7.25.0

**Expected behavior**
BOINC should be able to run NCI apps in NCI mode (like 7.20.x / 7.22.x or 7.24.x)

**Screenshots**
Boinc 7.24.1:
![boinc2_7241](https://github.com/BOINC/boinc/assets/153916567/eaf5b75b-739d-42b1-9295-ad00026a887f)
Boinc 7.25.0:
![boinc2_7250](https://github.com/BOINC/boinc/assets/153916567/6347885e-36d8-464e-8f77-79cf704d72bf)

**System Information**
 - OS: Windows 10
 - BOINC Version: 7.25.0 (build 2024.03.04 / 2024.03.05)

**Additional context**

**Comment by AenBleidd** [comment]
Should be fixed by #5527
