### ISSUE TITLE
Stray quotation mark on index page

### ISSUE THREAD

**Issue by AlPiskun** [BOINC/boinc#5538]
There is a stray " displayed on newer BOINC project homepages:

![bug](https://github.com/BOINC/boinc/assets/44337048/ca123b12-1a74-46b8-a48b-becfadbae25f)

Examples:
[BOINC Central](https://boinc.berkeley.edu/central/)
[SPT](https://boinc.termit.me/adsl/)
[Parlea](https://parlea.ru/boinctest/)
[The Ramanujan Machine](https://rnma.xyz/boinc/)

It is apparently generated from schedulers.txt and shows up as a double quote after cgi here
`<link rel="boinc_scheduler" href="https://boinc.berkeley.edu/central_cgi/cgi" ">`

**Comment by AenBleidd** [comment]
@davidpanderson, could you please take a look?
