### ISSUE TITLE
Please tell me, why? nothing for macOS version on 8.0.0

### ISSUE THREAD

**Issue by Chamiu** [BOINC/boinc#5543]
Why is macOS version not include  [Release Client/Manager Release 8.0.0 · BOINC/boinc](https://github.com/BOINC/boinc/releases/tag/client_release%2F8.0%2F8.0.0) ?
Even though there is 9 fix in macOS in the update content.

**Comment by CharlieFenton** [comment]
Please be patient. We are all volunteers here. I will build it soon when I have time.

**Comment by AenBleidd** [comment]
Build for MacOS is not ready yet. It will be available soon on the website.
Please wait for the official announcement (as you may notice, there was no one yet).
