### ISSUE TITLE
Gerasim doesn't recognise BOINC version 8.0

### ISSUE THREAD

**Issue by Corsair-63** [BOINC/boinc#5549]
**Describe the bug**
Installed latest BOINC version (windows x11), all installation corrects.
Gerasim project doesn´t download new job because it says that version should be higher than 7.XXX

**Steps To Reproduce**
1. Install BOINC
2. Start crunching in Gerasim project.
3. after completion of job the wu is uploaded
4. the project request new job, but not downloaded because the project says that BOINC version must be higher than 7.xx.xx

**Expected behavior**
this project should have to recognise this BOINC version properly.

**Screenshots**
N/A, version back to 7.41.1 in order getting new job.

**System Information**
 - OS: Windows 11 (x64)
 - BOINC Version: 8.0.0

**Additional context**
not tested another whole projects if that also happens with them.

**Comment by AenBleidd** [comment]
@Corsair-63, thank you for the report.
I'll let Gerasim@home project admins know that there is such an issue, because this is not something that could be solved from the BOINC side.
I'm closing this ticket for now.
For further updates, please forums of Gerasim@home project.
