### ISSUE TITLE
gpu_usage must be positive in app_config.xml after update to 8.0.0

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#5557]
**Describe the bug**
gpu_usage must be positive in app_config.xml after update to 8.0
**Steps To Reproduce**
1. use attached app_config generated by boinctasks 1.93 beta
2. update to 8.0.0

**Expected behavior**

**Screenshots**

**System Information**
 - OS: windows 11
 - BOINC Version: 8.0.0

**Additional context**
[app_config.xml.txt](https://github.com/BOINC/boinc/files/14772525/app_config.xml.txt)

**Comment by AenBleidd** [comment]
I don't see we have changed this parameter behavior in 8.0.0.
What is the problem you have?
If this config was generated by BoinTasks (3rd party application), it should be fixed accordingly.

**Comment by RichardHaselgrove** [comment]
BoincTasks produces a fully-populated version of app_info.xml, with every allowable tag present and containing a value.

When you prepare a file for a CPU-only application, you still get a <gpu_versions> tag, with <gpu_usage> set to zero.

Zero is not positive - that's what triggers the error.

**Comment by AenBleidd** [comment]
So, I strongly believe this is not an issue of BOINC. Closing this as 'invalid'.

**Comment by kotenok2000** [comment]
Then why was boinc not reporting it before 8.0?
