### ISSUE TITLE
Errors trying to install Boinc client 8.0.0 on FC39

### ISSUE THREAD

**Issue by gj82854** [BOINC/boinc#5560]
When entering:   sudo dnf config-manager --set-enabled boinc-alpha-fc39  I get an error indicating that the repo is not found.
I when went back and modified the --add-repo command to sudo dnf config-manager --add-repo https://boinc.berkeley.edu/dl/linux/alpha/fc39/boinc-alpha-fc39.repo and then retried the --set-enabled command. The --set_-enabled then worked successfully. However, nothing installs. Issuing a sudo dnf --refresh upgrade shows the FC39 alpha repository in the list but boinc-client 8.0.0 is not in the list of packages to be upgraded. Issuing a sudo dnf install boinc-client results in a message that the boinc-client is already at the latest release (which is 7.20.1). 

I did notice that the .repo file in boinc.berkeley.edu/dl/linux/alpha/fc39 is smaller in size than the .repo file in /boinc.berkeley.edu/dl/linux/alpha/fc38. Is there something possibly missing out the the FC39 .repo file?

**Comment by AenBleidd** [comment]
@gj82854,
Looks like here we have a little documentation issue.
Please try to follow this steps and check if that works for you: https://github.com/BOINC/boinc/wiki/Linux-DEB-and-RPM-support#installation-1

**Comment by gj82854** [comment]
I removed everything that was used previously and followed your instructions:

***@***.***:/etc/yum.repos.d# dnf config-manager --add-repo https://boinc.berkeley.edu/dl/linux/alpha/fc39
Adding repo from: https://boinc.berkeley.edu/dl/linux/alpha/fc39
***@***.***:/etc/yum.repos.d# dnf config-manager --set-enabled boinc.berkeley.edu_dl_linux_alpha_fc39
***@***.***:/etc/yum.repos.d# rpm --import https://boinc.berkeley.edu/dl/linux/alpha/fc39/boinc.gpg
***@***.***:/etc/yum.repos.d# dnf install boinc-client
created by dnf config-manager from https://boin 4.2 kB/s | 3.2 kB 00:00
Package boinc-client-7.20.2-7.fc39.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by AenBleidd** [comment]
@gj82854, ok, for update you should run
`sudo yum update boinc-client`
and/or
`sudo yum update boinc-manager`

**Comment by gj82854** [comment]
I updated ALL repositories and it now shows up in the list:

***@***.***:/etc/yum.repos.d# dnf --refresh upgrade
created by dnf config-manager from https://boin 8.0 kB/s | 3.0 kB 00:00
Fedora 39 - x86_64 25 kB/s | 25 kB 00:00
Fedora 39 openh264 (From Cisco) - x86_64 7.5 kB/s | 989 B 00:00
Fedora 39 - x86_64 - Updates 100 kB/s | 22 kB 00:00
Dependencies resolved.
================================================================================
Package Arch Version Repository Size
================================================================================
Installing:
kernel x86_64 6.7.10-200.fc39 updates 161 k
kernel-core x86_64 6.7.10-200.fc39 updates 16 M
kernel-devel x86_64 6.7.10-200.fc39 updates 20 M
kernel-modules x86_64 6.7.10-200.fc39 updates 59 M
kernel-modules-core x86_64 6.7.10-200.fc39 updates 33 M
kernel-modules-extra x86_64 6.7.10-200.fc39 updates 2.6 M
Upgrading:
boinc-client x86_64 8.0.0-494 boinc.berkeley.edu_dl_linux_alpha_fc39
2.8 M
btrfs-progs x86_64 6.8-1.fc39 updates 1.2 M
clevis x86_64 20-1.fc39 updates 54 k
clevis-luks x86_64 20-1.fc39 updates 34 k
cpp x86_64 13.2.1-7.fc39 updates 11 M
emacs-filesystem noarch 1:29.3-1.fc39 updates 7.2 k
gcc x86_64 13.2.1-7.fc39 updates 34 M
glibc x86_64 2.38-17.fc39 updates 2.2 M
glibc-common x86_64 2.38-17.fc39 updates 354 k
glibc-devel x86_64 2.38-17.fc39 updates 86 k
glibc-gconv-extra x86_64 2.38-17.fc39 updates 1.6 M
glibc-headers-x86 noarch 2.38-17.fc39 updates 570 k
glibc-langpack-en x86_64 2.38-17.fc39 updates 667 k
gnutls x86_64 3.8.4-1.fc39 updates 1.1 M
libaom x86_64 3.8.2-1.fc39 updates 1.8 M
libatomic x86_64 13.2.1-7.fc39 updates 40 k
libgcc x86_64 13.2.1-7.fc39 updates 115 k
libgomp x86_64 13.2.1-7.fc39 updates 324 k
libreswan x86_64 4.14-1.fc39 updates 1.3 M
libstdc++ x86_64 13.2.1-7.fc39 updates 867 k
libtirpc x86_64 1.3.4-1.rc3.fc39 updates 93 k
pciutils x86_64 3.11.1-1.fc39 updates 100 k
pciutils-libs x86_64 3.11.1-1.fc39 updates 51 k
rpcbind x86_64 1.2.6-4.rc3.fc39 updates 57 k
shim-x64 x86_64 15.8-3 updates 467 k
Installing dependencies:
libnsl x86_64 2.38-17.fc39 updates 113 k
Removing:
kernel x86_64 6.5.10-200.fc38 @updates 0
kernel-core x86_64 6.5.10-200.fc38 @updates 65 M
kernel-devel x86_64 6.5.10-200.fc38 @updates 68 M
kernel-modules x86_64 6.5.10-200.fc38 @updates 56 M
kernel-modules-core x86_64 6.5.10-200.fc38 @updates 30 M
kernel-modules-extra x86_64 6.5.10-200.fc38 @updates 2.4 M

Transaction Summary
================================================================================
Install 7 Packages
Upgrade 25 Packages
Remove 6 Packages

Total download size: 191 M
Is this ok [y/N]:

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by gj82854** [comment]
After installing the updates, boinc-client 8.0.0 is now running on the host.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by AenBleidd** [comment]
Documentation has been updated.
Thank you for reporting and testing this!
