### ISSUE TITLE
Errors installing boinc-client 8.0.0 on Ubuntu 22.04

### ISSUE THREAD

**Issue by gj82854** [BOINC/boinc#5561]
I ended up with the following issues when trying to install the 8.0.0 boinc-client on Ubuntu 22.04 LTS:

1. apt-key is deprecated so one gets a few warning messages associated with that command
2. There is a syntax error in the sources list file in /etc/apt/sources.list.d/archive_uri-https_boinc_berkeley_edu_dl_linux_alpha_jammy-jammy.list. I fixed the error and was able to install the boinc-client
3. Once the install finishes. I noticed that the modules in /usr/local/bin are not owned by root. I fixed that and was able to start the client

**Comment by AenBleidd** [comment]
1. Is not an issue. Yes, it might be good to fix it, but this is not a blocker for the installation.
2. I was not able to reproduce this on clean Ubuntu 22.04. Could you please specify what is the issue you have?
3. Yes, I also see that the owner is not correct (and this need to be fixed), however this doesn't prevent me from running both client and Manager. What issues do you have here except the wrong ownership?

**Comment by gj82854** [comment]
- You are correct. It was just a warning message but when it comes to the key it would be best, I assume, to use the recommended process.

- After adding the repo, inside the sources list file, the entry was:

deb https://boinc.berkeley.edu/dl/linux/alpha/jammy/ main

I kept getting syntax errors every time apt tried to read the file. I fixed it as follows:

deb https://boinc.berkeley.edu/dl/linux/alpha/jammy/ jammy main

- I didn't try to start the client and it may have worked but I didn't want to mess up permissions in the /var/lib/boinc directories with the client running with that UID/GID combination. My understanding of linux permissions is that root is UID 0. Any other UID other than 0 might produce unpredictable results on other machines because it would depend on what was assigned to that UID on that particular machine. This is a know issue with NFS. If one uses NFS in their environment it is useful to synchronize the UIDs across all machines that use NFS.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by AenBleidd** [comment]
@gj82854,

> - After adding the repo, inside the sources list file, the entry was:
> deb https://boinc.berkeley.edu/dl/linux/alpha/jammy/ main
> I kept getting syntax errors every time apt tried to read the file. I fixed it as follows:
> deb https://boinc.berkeley.edu/dl/linux/alpha/jammy/ jammy main

Did you follow this instructions: https://boinc.berkeley.edu/linux_install.php?os_num=5&build=alpha

I don't have any syntax errors.

**Comment by gj82854** [comment]
No. I did the install about a week ago or so and followed the instructions on github. These instructions look updated compared to what I had. If that is the case then this is no longer a problem.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Toby-Broom** [comment]
I also have the apt-key error I think it would be good to fix it.

**Comment by Toby-Broom** [comment]
> @gj82854,
> 
> > * After adding the repo, inside the sources list file, the entry was:
> >   deb https://boinc.berkeley.edu/dl/linux/alpha/jammy/ main
> >   I kept getting syntax errors every time apt tried to read the file. I fixed it as follows:
> >   deb https://boinc.berkeley.edu/dl/linux/alpha/jammy/ jammy main
> 
> Did you follow this instructions: https://boinc.berkeley.edu/linux_install.php?os_num=5&build=alpha
> 
> I don't have any syntax errors.

I followed the instructions to upgade from 7.20.5 to 8.0.0

**Comment by AenBleidd** [comment]
@Toby-Broom, thank you, we will update the documentation accordingly.

**Comment by Toby-Broom** [comment]
@AenBleidd 

a one liner for the key install is:

gpg --no-default-keyring --keyring /tmp/keyring.gpg --keyserver keyserver.ubuntu.com --recv-key 40254C9B29853EA6 && sudo gpg --no-default-keyring --keyring /tmp/keyring.gpg --output /etc/apt/keyrings/boinc.gpg --export

I think the key should be in /usr/share/keyrings/ not in the apt directory?
