### ISSUE TITLE
Radio buttons and checkboxes aren't visible on boinc 8.0 kubuntu 22.04

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#5563]
**Describe the bug**

**Steps To Reproduce**
1. install kubuntu 22.04
2. install boinc-manager from repository deb https://boinc.berkeley.edu/dl/linux/alpha/jammy/ jammy main
3. notice that it doesn't depend on boinc-client
4. Install boinc-client
5. see tha ti doesn't show radio buttons and checkboxes.

**Expected behavior**

**Screenshots**
![image](https://github.com/BOINC/boinc/assets/8822292/e2449d94-1cef-4b5e-a22f-3f50df5c1ee5)
![image](https://github.com/BOINC/boinc/assets/8822292/57598889-e58e-4d96-81ba-8498af12e9a1)

**System Information**
 - OS: kubuntu 22.04.4
 - BOINC Version: 8.0

**Additional context**

**Comment by AenBleidd** [comment]
@kotenok2000, the fix for this issue is already in the nightly build: https://github.com/BOINC/boinc/wiki/Linux-DEB-and-RPM-support
It would be nice if you could try it and check that it works for you now.
Thank you in advance.
