### ISSUE TITLE
Install error 'failed to create symbolic link'

### ISSUE THREAD

**Issue by Toby-Broom** [BOINC/boinc#5564]
**Describe the bug**
There was an error the 1st time I tried to install 8.0.0

**Steps To Reproduce**
1.  sudo apt update && sudo apt upgrade

**Expected behavior**
installs the 1st tuime

**Screenshots**
Hit:1 http://ch.archive.ubuntu.com/ubuntu mantic InRelease
Hit:2 http://ch.archive.ubuntu.com/ubuntu mantic-updates InRelease
Hit:3 http://security.ubuntu.com/ubuntu mantic-security InRelease
Hit:4 http://ch.archive.ubuntu.com/ubuntu mantic-backports InRelease
Hit:5 https://boinc.berkeley.edu/dl/linux/alpha/jammy jammy InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://boinc.berkeley.edu/dl/linux/alpha/jammy jammy InRelease' doesn't support architecture 'i386'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libboinc7 libjavascriptcoregtk-4.0-18 libwebkit2gtk-4.0-37 libwxbase3.2-1 libwxgtk-webview3.2-1 libwxgtk3.2-1
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  boinc-client boinc-manager
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 14.3 MB of archives.
After this operation, 9,051 kB disk space will be freed.
Do you want to continue? [Y/n]
Get:1 https://boinc.berkeley.edu/dl/linux/alpha/jammy jammy/main amd64 boinc-client amd64 8.0.0-494 [2,637 kB]
Get:2 https://boinc.berkeley.edu/dl/linux/alpha/jammy jammy/main amd64 boinc-manager amd64 8.0.0-494 [11.6 MB]
Fetched 14.3 MB in 3s (4,942 kB/s)
(Reading database ... 215880 files and directories currently installed.)
Preparing to unpack .../boinc-client_8.0.0-494_amd64.deb ...
Unpacking boinc-client (8.0.0-494) over (7.20.5+dfsg-1.1) ...
Preparing to unpack .../boinc-manager_8.0.0-494_amd64.deb ...
Unpacking boinc-manager (8.0.0-494) over (7.20.5+dfsg-1.1) ...
Setting up boinc-client (8.0.0-494) ...
ln: failed to create symbolic link '/etc/boinc-client/global_prefs_override.xml': File exists
dpkg: error processing package boinc-client (--configure):
 installed boinc-client package post-installation script subprocess returned error exit status 1
Setting up boinc-manager (8.0.0-494) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu1) ...
Processing triggers for man-db (2.11.2-3) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Errors were encountered while processing:
 boinc-client
E: Sub-process /usr/bin/dpkg returned an error code (1)

**System Information**
 - OS: 23.10
 - BOINC Version: 8.00

**Additional context**

**Comment by Toby-Broom** [comment]
to fix the i386 warning you'd need this line in soruce

deb [signed-by=/etc/apt/keyrings/boinc.gpg arch=amd64] https://boinc.berkeley.edu/dl/linux/alpha/jammy jammy main
# deb-src https://boinc.berkeley.edu/dl/linux/alpha/jammy jammy main

**Comment by Toby-Broom** [comment]
I couldn't repo on 2nd computerm so I'm not sure exactly how to repo

**Comment by Toby-Broom** [comment]
I had some issues on one computer also, where the /var/lib/boinc directory was created but on other computer its a symlink to /var/lib/boinc-client

**Comment by AenBleidd** [comment]
I'll try to fix that in the upgrade script.
Just FYI: distro maintainers added files/directories to locations different from the BOINC recommended.

**Comment by Toby-Broom** [comment]
I can move to the designed location 💯

**Comment by Toby-Broom** [comment]
> I'll try to fix that in the upgrade script. Just FYI: distro maintainers added files/directories to locations different from the BOINC recommended.

https://github.com/BOINC/boinc/wiki/UnixClientPackage
https://github.com/BOINC/boinc/wiki/AdminInstallerUnix

These pages talk about on Debian that it should be /var/lib/boinc-client, so some documenation clean up as well.
