### ISSUE TITLE
Apple M1 GPU not recognized by 8.0.0

### ISSUE THREAD

**Issue by pi17388** [BOINC/boinc#5565]
**Describe the bug**
Running PrimeGrid and Einstein at Home GPU-applications.  In prior releases (most recent 7.24.3) both applications performed correctly.  As of the recent install (testing of 8.0.0) the logs and mgr display messages indicating that the M1 GPU is not recognized/present.  
**Steps To Reproduce**
1. 
2. 

**Expected behavior**
See above.

**Screenshots**
<img width="1272" alt="Screenshot 2024-03-30 at 20 46 08" src="https://github.com/BOINC/boinc/assets/165528288/ad29518f-d8bb-489f-80fd-ea000fc75c49">
**System Information**
Fri Mar 29 07:14:16 2024 |  | OpenCL: Apple GPU 0: Apple M1 (driver version 1.2 1.0, device version OpenCL 1.2, 10923MB, 10923MB available, 64 GFLOPS peak)
Fri Mar 29 07:14:16 2024 |  | Processor: 8 Apple Apple M1
Fri Mar 29 07:14:16 2024 |  | Processor features: amx_version_1 arm64 armv8_1_atomics armv8_2_fhm armv8_2_sha3 armv8_2_sha512 armv8_crc32 floatingpoint neon neon_fp16 neon_hpfp ucnormal_mem fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clfsh ds acpi mmx fxsr sse sse2 ss htt tm pbe pni pclmulqdq dtse64 mon dscpl vmx est tm2 ssse3 cx16 tpr pdcm sse4_1 sse4_2 aes seglim64
Fri Mar 29 07:14:16 2024 |  | OS: Mac OS X 14.4.1 (Darwin 23.4.0)
Fri Mar 29 07:14:16 2024 |  | Memory: 16.00 GB physical, 289.60 GB virtual
Fri Mar 29 07:14:16 2024 |  | Disk: 460.43 GB total, 289.60 GB free
Fri Mar 29 07:14:16 2024 |  | Local time is UTC -4 hours

**Additional context**

**Comment by pi17388** [comment]
I did not include the "steps to reproduce" but for completeness:
1. Install 8.0.0 on Apple MacBook Air configured with an M1 ARM chip (16GB of RAM).
2. Restart Boincmgr
3. Run applications supporting GPU processing in the PrimeGrid and Einstein at Home libraries.

Thanks in advance for your assistance with the error report.

Jon Fox

**Comment by AenBleidd** [comment]
@pi17388, previously BOINC was not "aware" about the Apple M1 GPU, and the PG project made their customization to run their application on this GPU.
With the release of 8.0.0, I strongly believe PG project should fix their configuration to adjust it to the new BOINC version.
Please report this back to them, since we also need their feedback on this.
Thank you in advance.

**Comment by pi17388** [comment]
Understood.  I'll see what they say and report back.Thanks.JonOn Mar 30, 2024, at 21:05, Vitalii Koshura ***@***.***> wrote:﻿
@pi17388, previously BOINC was not "aware" about the Apple M1 GPU, and the PG project made their customization to run their application on this GPU.
With the release of 8.0.0, I strongly believe PG project should fix their configuration to adjust it to the new BOINC version.
Please report this back to them, since we also need their feedback on this.
Thank you in advance.

**Comment by CharlieFenton** [comment]
@AenBleidd I also see this with both Einstein and PrimeGrid. BOINC 7.24.3 shows this:

> 31-Mar-2024 01:41:22 [---] Data directory: /Library/Application Support/BOINC Data
31-Mar-2024 01:41:23 [---] OpenCL: Apple M1 0: Apple M1 (driver version 1.2 1.0, device version OpenCL 1.2, 10923MB, 10923MB available, 8 GFLOPS peak)
31-Mar-2024 01:41:23 [---] Version change (8.0.0 -> 7.24.3)

But BOINC 8.0.0 shows this:

> 31-Mar-2024 01:45:16 [---] OpenCL: Apple GPU 0: Apple M1 (driver version 1.2 1.0, device version OpenCL 1.2, 10923MB, 10923MB available, 64 GFLOPS peak)
31-Mar-2024 01:45:16 [---] app version refers to missing GPU type Apple M1
31-Mar-2024 01:45:16 [Einstein@Home] Application uses missing Apple M1 GPU
31-Mar-2024 01:45:16 [---] app version refers to missing GPU type Apple M1
31-Mar-2024 01:45:16 [PrimeGrid] Application uses missing Apple M1 GPU
31-Mar-2024 01:45:16 [---] Version change (7.24.3 -> 8.0.0)

@davidpanderson: What makes this especially strange is that my  computer does not currently have any PrimeGrid tasks at all, and has no GPU Einstein tasks. The only Einstein app_version in _client_state.xml_ that specifies a GPU specifies OpenCL:
`<plan_class>Apple_M-opencl</plan_class>`

The only Primegrid app_version in _client_state.xml_ that specifies a GPU also specifies OpenCL:
`<plan_class>opencl_Apple_M_GFN20</plan_class>`

So I suspect this is a problem in the BOINC client's handling of plan classes requiring OpenCl on Apple Silicon GPUs.

**Comment by davidpanderson** [comment]
The 8.0 client reports Apple GPUs as type 'apple_gpu'.
Pre-8.0 clients report them as the model returned by OpenCL, e.g. 'Apple M1'.

Projects that have Apple GPU apps (OpenCL or Metal) should
use appropriate plan classes, i.e. with names starting with 'apple_gpu'.

**Comment by AenBleidd** [comment]
Closing this as 'wontfix' since this is nothing that should be fixed on the BOINC side.
Feel free to reopen it.
