### ISSUE TITLE
New Version Check broken on Apple Silicon macs

### ISSUE THREAD

**Issue by CharlieFenton** [BOINC/boinc#5568]
**Describe the bug**
The new version check code always reports no new version  when run on Apple Silicon (arm64) Macs. This was mentioned [in this comment](https://github.com/BOINC/boinc/issues/5456#issuecomment-2031238482) as part of issue #5456.

The problem is that the _get_current_version.xml_ file returned by the BOINC server lists only _x86_64-apple-darwin_ as the platform for the X86_64 and arm64 universal binary, but the `parse_version()` function checks for a match only with the primary platform, which is _arm64-apple-darwin_. on an Apple Silicon Mac Here is the entry for the current 7.24.3 version from the _get_current_version.xml_ file:
`<version>`
`    <platform>Apple Mac (64-bit Intel and Apple Silicon)</platform>`
`    <dbplatform>x86_64-apple-darwin</dbplatform>`
`    <description>Recommended version (Unix command-line version) (MacOS 10.13+)</description>`
`    <date>30 Jan 2024</date>`
`    <version_num>7.24.3</version_num>`
`    <installer>Command-line client (no GUI)</installer>`
`    <url>https://boinc.berkeley.edu/dl/boinc_7.24.3_universal-apple-darwin.dmg</url>`
`    <filename>boinc_7.24.3_universal-apple-darwin.dmg</filename>`
`    <size_mb>4.54</size_mb>`
`    <min_os_version>101300</min_os_version>`
`    <max_os_version>999999</max_os_version>`
`</version>`
This could be fixed in the client code by checking both primary and secondary platforms, but this would not fix it for current versions of BOINC already in the field, so they would never be notified of newer versions. 

These "universal" binaries contain two copies of BOINC, one compiled for Intel (with primary platform _x86_64-apple-darwin_) and the other compiled for arm64 (with primary platform _arm64-apple-darwin_.)  So these are actually separate builds for the 2 platforms in one file. 

To ensure backward compatibility this would best be fixed on the server side by including two entries for each version. The entries would be identical except for the <dbplatform> tag: one should have _x86_64-apple-darwin_ and the other should have _arm64-apple-darwin_.

Note that the same issue applies to older universal binaries built for both 32-bit and 64 bit Intel Macs ( _i686-apple-darwin_ and _x86_64-apple-darwin_) and those built for Power PC or 32-bit Intel ( _i686-apple-darwin_ and _powerpc-apple-darwin_.)

**Comment by CharlieFenton** [comment]
> this would best be fixed on the server side by including two entries for each version

As the following comment says in versions.inc, this problem was identified back in October 2021 in issue #4551:
> // Mac Universal builds contain code for both Intel 64 and 
// Apple Silicon (ARM64) Macs, but the two architectures 
// report different primary platforms so we need to include
// these builds in both the $mac and $mac_arm arrays for
// the client's New Version Check code to handle them properly.
// See GitHub Issue #4551 for more details.

**Comment by davidpanderson** [comment]
I changed download_all.php (XML version) so that the Intel/ARM versions
appear separately for each platform.

**Comment by AenBleidd** [comment]
@CharlieFenton, could you please verify that this works as intended?
Thank you in advance.

**Comment by CharlieFenton** [comment]
Yes, it works correctly now. Thank you.
