### ISSUE TITLE
v8 BOINC Manager is not able to connect to a BOINC client

### ISSUE THREAD

**Issue by AlPiskun** [BOINC/boinc#5595]
**Describe the bug**
Since installing version 8.0.0, I have seen (several times on different Windows hosts) a Connection Failed dialog box:

![bm](https://github.com/BOINC/boinc/assets/44337048/38cd6000-d6d6-4143-97c0-513f4b6622cb)

I have not been able to repair or reinstall v8 after this without removing or renaming C:\ProgramData\BOINC
**Reinstalling BOINC ver 7.24.1 will also fix the problem without removing or renaming.**

See attached stdoutdae and stderrdae.txt
[stderrdae.txt](https://github.com/BOINC/boinc/files/15054092/stderrdae.txt)
[stdoutdae.txt](https://github.com/BOINC/boinc/files/15054093/stdoutdae.txt)

stdoutdae always abruptly ends similar to this when BOINC reinstall is needed (referring to a different GPUGRID task): 
18-Apr-2024 08:09:47 [GPUGRID] Found finish file for a34-SFARR_TESTv11-0-1-RND2725_2; exit code 195
18-Apr-2024 08:09:47 [GPUGRID] Task a34-SFARR_TESTv11-0-1-RND2725_2: no shared memory segment

**System Information**
 - OS: Windows 10
 - BOINC Version: 8.0.0

**Comment by AenBleidd** [comment]
This is already fixed. Meanwhile please use these artifacts to fix this issue: https://github.com/BOINC/boinc/actions/runs/8768687107/artifacts/1432524289
