### ISSUE TITLE
Another instance of boinc manger is already running

### ISSUE THREAD

**Issue by Toby-Broom** [BOINC/boinc#5605]
On windows with v 8.0 when I unexpectedly recieve this dialouge

**Steps To Reproduce**
1. Run boinc at startup so its already in the tray or start manually
2. from the start menu launch boinc
3. recieve message

**Expected behavior**
Boinc opens with no message

**Screenshots**
![image](https://github.com/BOINC/boinc/assets/27242647/eba0de67-2d39-4ff4-ab11-61728a11196f)

**System Information**
 - OS: Windows 11 23H2
 - BOINC Version: 8.0

**Additional context**
If I open from the tray with right click then there is no message.

**Comment by AenBleidd** [comment]
This is an expected behavior: when you try to launch another instance of BOINC Manager, it shows you the message and opens (pops up) that instance of BOINC Manager that is already running.

**Comment by AenBleidd** [comment]
Reference: #5485

**Comment by Toby-Broom** [comment]
Ok, its a strange behaviour to me, if others agree then I would make a feature request.

**Comment by RichardHaselgrove** [comment]
I think that the problem here is a Windows one: when BOINC Manager is started automatically at logon, it automatically launches the client and moves to minimised status in the system tray / notifications area (terminology has changed).

But the icon representing the BOINC Manager is set to 'Only show notifications' - i.e. invisible unless something requires attention. The casual user (at this point) isn't necessarily aware that **both** the client **and** the Manager are running: nothing is visible onscreen.

Windows does have available a system tray property of 'Show icon and notifications' - but the means of setting this manually has changed from version to version (of Windows). I don't have enough current knowledge of Windows to know if it can be set by our current installer tools.

**Comment by AenBleidd** [comment]
> I think that the problem here is a Windows one: when BOINC Manager is started automatically at logon, it automatically launches the client and moves to minimised status in the system tray / notifications area (terminology has changed).

No, by default BOINC Manager isn't hidden in the system tray at start up.

> I don't have enough current knowledge of Windows to know if it can be set by our current installer tools.

I'm pretty much sure it can be set, but I don't really see this valuable: this message is harmless, it just tells you that you have already the BOINC Manager running, and just pops it up for you.
All you need is just to click 'OK' in the message box.

But this message box serves another purpose: if for some reason BOINC Manager window is hidden somewhere and could not be shown for some reason (e.g. behind the top most window, and this window prevents other windows to be on top of it), then the user might be confused, why the BOINC Manager doesn't run.

So, as for me, there is nothing we should change in the current behavior.

**Comment by Toby-Broom** [comment]
I didn't set anything for boinc so whatever the windows defaults are.  Is "opening" BOINC really a notification?

As said I find it a bit strange behavour but as @AenBleidd said its harmless, if others agree that they find it strange then it would be worth to find a solution if its just me then I accept the consensus.

**Comment by RichardHaselgrove** [comment]
>... it just tells you that you have already the BOINC Manager running, and just pops it up for you.

Those are two separate statements: 'tells you', and 'pops up'. I think that we should perhaps double-check that they are both still true in current versions of Windows. Perhaps @Toby-Broom could keep a close eye on exactly what happens next time he logs on to this machine?

I agree - _**provided**_ we can confirm that the new (second) copy of the Manager transfers control to the first, and brings it to visibility onscreen, then that's enough. But I seem to remember having problems getting a visible, usable, copy of the Manager onscreen when this change first occurred with Windows 10.

**Comment by RichardHaselgrove** [comment]
OK, I see that. I haven't started testing v8 for myself yet (I'm concentrating more on working with projects at the moment). Looking at the prior reference https://github.com/BOINC/boinc/pull/5485, I see that it is proposed for v7.26.0 (now renumbered v8.0). There's no reference to any preceding issue, and no independent review.

Can you remember what triggered that particular PR? Looking at it now, I rather agree with @Toby-Broom: it feels like a strange message for a first time user, installing and coming to grips with the BOINC system for the first time.

**Comment by AenBleidd** [comment]
> Can you remember what triggered that particular PR?

I received a couple of requests from the sources outside of GitHub (don't remember exactly), and the last one came from @davidpanderson directly, after which this change was basically implemented.

>  it feels like a strange message for a first time user, installing and coming to grips with the BOINC system for the first time.

I don't agree on that.
First, after the user installed BOINC and checked the checkbox at the end 'Launch BOINC Manager', it will be launched and on top of other windows.
If the user didn't check that checkbox and instead started the BOINC Manager manually, they will also see it.
The only way to see this message (and to be confused), is to close BOINC Manager (by clicking on 'X' button) and do not be aware that it was not finished but instead hidden in the tray, and then relaunching the application. And even in this case the user will see the BOINC Manager window shown up and informing the user, that it was already running.

I don't understand the confusion of @Toby-Broom: haven't you ever be informed that when you close BOINC Manager window it becomes hidden in the system tray and continues running?

As for me, we have already too long discussion on the tiniest and harmless change.

**Comment by Toby-Broom** [comment]
The video is a demo of the behavour. As said won't fix is fien for me its you're decision.
