### ISSUE TITLE
Multiple and conflicting installation instructions for Linux package

### ISSUE THREAD

**Issue by Vulpine05** [BOINC/boinc#5623]
I have a potential issue with a Linux installation of BOINC 8.1, but before I write anything I want to be sure the issue can be replicated after I do a clean installation.  I discovered there are two different installation pages.

One is [here](https://boinc.berkeley.edu/linux_install.php?os_num=5&build=nightly) (directed from the download all web page).
The other one is [here](https://boinc.berkeley.edu/wiki/Installing_on_Linux) (directed from the BOINC wiki).

The information on both pages are not the same, but I think there is information that is valuable on both pages (how to install on the first link, how to uninstall a previous version on the second link).  Is it possible to consolidate both of these pages into one?

**Comment by AenBleidd** [comment]
Depends on the installer you are using, but for the new installer the first link is more precise).
Thank you for pointing that out, we will fix the documentation accordingly.

**Comment by AenBleidd** [comment]
Documentation has been updated
