### ISSUE TITLE
not work usable CPUs has change on BOINC Manager 8.0.3dev.

### ISSUE THREAD

**Issue by Chamiu** [BOINC/boinc#5659]
**Describe the bug**

not work
- Number of usable CPUs has changed from 2 to 4.
- Number of usable CPUs has changed from 4 to 2.

**Steps To Reproduce**
1. install 8.0.3dev.
2. launch 8.0.3dev.

**Expected behavior**

not use machine
Mon 17 Jun 08:03:27 2024 |  | Number of usable CPUs has changed from 2 to 4.

use machine
Mon 17 Jun 08:16:01 2024 |  | Number of usable CPUs has changed from 4 to 2.

**Screenshots**

Mon 17 Jun 08:03:27 2024 |  | Number of usable CPUs has changed from 2 to 4.
Mon 17 Jun 08:16:01 2024 |  | Number of usable CPUs has changed from 4 to 2.

**System Information**
 - OS: macOS Sonoma.5
 - BOINC Version: 8.0.3 Dev.

**Additional context**

No

**Comment by CharlieFenton** [comment]
I have noticed for quite some time seemingly random messages going back and forth between 2 and 4 useable CPUs even when I was not using the computer, i=on my M1 iMac running MacOS 14.5 Sonoma (and several macOS 14.x versions.)

**Comment by Chamiu** [comment]
@CharlieFenton There's also that issue.
It's just my rule of thumb, macOS gives a notification when it's in the next state, it recognizes that it's in use and seems to be switching.
- display sleep
- lock Mac

Maybe, "macOS wants a notification, so it's in use, isn't it?" I'm imagining that it is recognized by the state monitoring logic on the BOINC side.

It may be interesting to stop notifying each other and verify it.
I'll try it before going to bed tonight.
