### ISSUE TITLE
boinc 8.0.3 (x64) Waiting for memory

### ISSUE THREAD

**Issue by dwsom** [BOINC/boinc#5667]
**Describe the bug**
max CPUs used: 32
Status:
19x "Running"
13x "Waiting for memory"

BOINC computing preferences:
Using local prefs.
99% memory limit
99% swap limit
Disk Limit: Leave at least 1GB

**Steps To Reproduce**
1. install 8.0.3
2. launch 8.0.3

**Expected behavior**
100% CPU / 32 running tasks

**Screenshots**
![boinc-8-0-3_Tasks](https://github.com/BOINC/boinc/assets/158524282/4fd701c1-2fdb-4676-9476-72f3033df582)
![boinc-8-0-3_Disk](https://github.com/BOINC/boinc/assets/158524282/0ddb464c-d803-4b4f-a8b7-8de3f05306a8)
![boinc-8-0-3_prefs-Computing](https://github.com/BOINC/boinc/assets/158524282/364685ff-ec0b-4da8-a7ea-598391311c9a)
![boinc-8-0-3_prefs-Disk](https://github.com/BOINC/boinc/assets/158524282/b753aadd-88a0-4e96-8530-c442aa78fa3a)
![boinc-8-0-2_Tasks](https://github.com/BOINC/boinc/assets/158524282/c614e666-6476-454f-99b3-1511fedbbe8c)
![boinc-gnome-system-monitor](https://github.com/BOINC/boinc/assets/158524282/93be98db-a2b7-4feb-acac-0a40ffa5282d)

**System Information**
 - OS: Linux NixOS nixpkgs-unstable
 - BOINC Version: 8.0.3 (x64)

**Additional context**
nixos-config:
services.boinc.extraEnvPackages = with pkgs; [ libglvnd brotli rocmPackages.clr.icd ]; #rosetta-beta + OpenCL

**Comment by AenBleidd** [comment]
This is the same issue as #5659.
@davidpanderson, could you please investigate?

**Comment by dwsom** [comment]
@AenBleidd
Ah, ok. Thank you.
I was not sure if this was the same issue.

**Comment by AenBleidd** [comment]
@dwsom, this is ok, since you have provided a lot of additional useful information.
So thank you very much for your report!
