### ISSUE TITLE
Make the download link active (hyperlink) when checking the availability of new versions

### ISSUE THREAD

**Issue by MaxMaximus** [BOINC/boinc#5676]
Hello.

This issue about work of "Check for new BOINC version" function from "Help" menu of the BOINC Manager.

**Describe the problem**
The check itself works correctly and when it detects that a new version is available, it displays the correct (up-to-date) link to download installation package. It's "https://boinc.berkeley.edu/download.php"
The problem is that this link is displayed as an inscription on the form (label), and not an active link (hyperlink) or at least a text field that can be copied.
It is impossible neither to click it nor to copy it.

**Describe the solution you'd like**
Make it an active link (hyperlink) instead of a label. So the user can click on it and immediately open it in the browser. You can't expect a user to write the link text manually character by character from a form image shown and then enter it into the browser's address bar.

Although this link is not difficult to find other ways, for example, it appears in "notices" tab when new versions are automatically checked and detected when the client is launched. But the current implementation (and it has been this way for many years/BOINC versions) makes this particular menu item useless to the user.

**Additional context**
Screenshot:
![BOINC_download_link](https://github.com/BOINC/boinc/assets/6316214/f4e0cce2-39a3-482d-ab22-5404996192dc)
Taken from a BOINC version 7.24.1 running on Windows х64. But it will be same on any version except the latest because the most recent one will display a message that no new versions have been found instead of this download link.

**Comment by MaxMaximus** [comment]
Also in the events log same downdload link is also not active. But at least here it is displayed as a simple text that can be copied+pasted.
```
05/07/2024 16:50:01 |  | A new version of BOINC is available (8.0.2). <a href=https://boinc.berkeley.edu/download.php>Download</a>
```

**Comment by davidpanderson** [comment]
Currently the Notices tab is the only place we can show active links (and other HTML).

I think I can remove the <a tags from the event log.

For the dialog: I agree that it's bad to just show the URL (which can't even be copied).
We could add a button that closes the dialog and opens the URL in a browser.
Or we could say 'see Notices'.

**Comment by AenBleidd** [comment]
I can fix the dialog by adding a new button to open the link in a default browser. This should be easy enough and easy to use.

**Comment by CharlieFenton** [comment]
On the Mac, the project URL in the Add Project dialog is a working hyperlink. I don't have a Windows or a Linux box on which to check this.

**Comment by MaxMaximus** [comment]
> On the Mac, the project URL in the Add Project dialog is a working hyperlink. I don't have a Windows or a Linux box on which to check this.

I tested it on Windows. Hyperlinks in the forms for adding a new project are also active and working just fine:
![BOINC_add_project](https://github.com/BOINC/boinc/assets/6316214/075c09a7-ba1b-4a7c-8541-50887e7f4377)

I think the problem is that the dialog of the new version is NOT a form at all, but a standard simple message. It cannot actually display hyperlinks or any other interactive content. Only plain text and a fixed set of buttons like OK/Cancel/Yes/No.
So the solution may be to replace the message box with a simple form there active hyperlink are definitely possible.
