### ISSUE TITLE
"Unsafe app blocked" when installing Android client 8.0 on Android 14

### ISSUE THREAD

**Issue by rwaldura** [BOINC/boinc#5684]
**Describe the bug**
Installing the 8.0.2 Android client triggers on-screen message:
"Unsafe app blocked. This app was built for an older version of Android etc." — see screenshot.
Install proceeds fine, once the message is dismissed: [Install anyway]

**Steps To Reproduce**
1. adb install dld/boinc_8.0.2.apk
2. see on-screen message

**Expected behavior**
No message; installs silently.

**Screenshots**
![Screenshot_20240713-085901b](https://github.com/user-attachments/assets/f0fdf97d-5a70-452e-9a1a-cbc50b00c228)

**System Information**
- OS
husky-user 14 AP2A.240705.005 11942872 release-keys
gmscore versionName=24.26.32 (190408-650348549)
 - BOINC Version: 8.0.2

**Comment by AenBleidd** [comment]
Unfortunately, it's impossible to fix this without complete redesign of the application (see #5344 for more details).
Closing this as 'won't fix' for now.
