### ISSUE TITLE
Make install failing

### ISSUE THREAD

**Issue by MoiseRousseau** [BOINC/boinc#5690]
**Describe the bug**
`make install` target fail because some examples does not have that target

**Steps To Reproduce**
```
./_autosetup
./configure --disable-client --disable-manager --enable-apps --prefix=$HOME/install
make
make install
```

**Expected behavior**
No error

**System Information**
 - OS: Ubuntu 24.04 in a LXD container
 - BOINC Version: Release 8.0.2 from Github

**Additional context**
Fixed adding a dummy install target in:
* boinc-client_release-8.0-8.0.2/samples/condor/Makefile
* boinc-client_release-8.0-8.0.2/samples/multi_thread/Makefile

For example:
```
install:
	echo "Dummy install"

**Comment by bjauny** [comment]
Hey there, I'll be glad to tackle this.

**Comment by bjauny** [comment]
I have the following message while building/installing:

`fatal: No names found, cannot describe anything.`

It comes from the `git describe` call in **generate_svn_version.sh**. Is it normal? Should I ignore it?

**Comment by AenBleidd** [comment]
@bjauny, you should follow this manual to build BOINC: https://github.com/BOINC/boinc/wiki/Building-boinc-on-unix

**Comment by bjauny** [comment]
OK, it seems the error comes from the fact that my fork doesn't have any tag matching `server_release/*`. I will have a mock install ready by tomorrow for Hacktoberfest, but is it enough or a **real** install is needed for this issue?

**Comment by AenBleidd** [comment]
@bjauny, build it with 
```
./configure --disable-client --disable-manager --enable-apps --disable-server
```
There should not be this error then.

**Comment by bjauny** [comment]
Sorry to be a pain, but it's still here. Tail of the log follows.

To be clear on the environment/setup:
- WSL2 on W11 (Ubuntu)
- installed the listed pre-requisites in the Wiki
- forked the repo and cloned locally
- `./_autosetup`
- `./configure --disable-client --disable-manager --enable-apps --disable-server --prefix=$HOME/install`
- `make`

Apart from the `git describe` failing, everything is OK.

```Making all in doc
make[2]: Entering directory '/home/bjauny/git/boinc/doc'
make[3]: Entering directory '/home/bjauny/git/boinc/doc'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/bjauny/git/boinc/doc'
make[2]: Leaving directory '/home/bjauny/git/boinc/doc'
make[2]: Entering directory '/home/bjauny/git/boinc'
cd . && sh generate_svn_version.sh
fatal: No names found, cannot describe anything.
make[2]: Leaving directory '/home/bjauny/git/boinc'
make[1]: Leaving directory '/home/bjauny/git/boinc'
```

**Comment by AenBleidd** [comment]
ok, just ignore it then. this is not the actual error of this ticker.

**Comment by MoiseRousseau** [comment]
Thanks for tackling this.

My ultimate objective of this was to create a deb package for BOINC server. I also have to add the following instructions for an app to be run after installation:
```
PYVER=$(python -c "import sys; print(f'{sys.version_info[0]}.{sys.version_info[1]}')")

mv ./packaging/lib/python$PYVER/site-packages/ ./packaging/lib/python$PYVER/dist-packages
sed -i 's/\/root\/boinc-client_release-8.0-8.0.2/\/usr\/share\/boinc-server-maker/g' ./packaging/lib/python3.10/dist-packages/boinc_path_config.py
mv ./packaging/libexec/boinc-server-maker/* ./packaging/usr/share/boinc-server-maker/
mv ./packaging/share/boinc-server-maker/* ./packaging/usr/share/boinc-server-maker/
cp ./boinc-client_release-8.0-${VERSION}/db/*.sql ./packaging/usr/share/boinc-server-maker/db/
cp -r ./boinc-client_release-8.0-${VERSION}/html/project.sample ./packaging/usr/share/boinc-server-maker/html/
cp ./boinc-client_release-8.0-${VERSION}/sched/pshelper ./packaging/usr/share/boinc-server-maker/sched/
```

Note my `packaging` directory is the installation target directory. This could be the hard drive root `/`.

**Comment by AenBleidd** [comment]
@MoiseRousseau, BOINC Server is a complex product, and majority of the Projects who install it, do some customization of it.
Making a package (DEB, RPM or any other) in this case is useless.
We currently support only BOINC client and BOINC Manager to be packaged (see: https://boinc.berkeley.edu/linux_install.php).

**Comment by MoiseRousseau** [comment]
@AenBleidd I did not meant to create an official Deb package. But just to report the steps to have a working BOINC server installation. For example, the current installation installs components in non standard path, python library in a folder that is not on PYTHONPATH, or lacks the sql script to interact with the database. So I was unable to create a simple test project.

**Comment by AenBleidd** [comment]
@MoiseRousseau, please start here: https://github.com/BOINC/boinc/wiki/Computing-with-boinc

**Comment by MoiseRousseau** [comment]
@AenBleidd I already succeeded make it working with the install target and the steps and I sent you. Just reporting what I have done for other people to reproduce if they need
