### ISSUE TITLE
Use CSS instead of HTML for formatting

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#573]
**Reported by Didactylos on 21 Sep 38262016 17:46 UTC**
Use CSS instead of HTML for formatting where possible
- clean up white.css
- improve the look
- develop alternative looks (perhaps with the curiously popular rounded corners).

Source: DevProjects

Migrated-From: http://boinc.berkeley.edu/trac/ticket/595

**Comment by romw** [comment]
**Commented by Nicolas on 18 Jul 38262062 20:26 UTC**
Breaking it down in individual tasks:
 * [Use heading tags in the correct order](http://www.w3.org/QA/Tips/Use_h1_for_Title).
 * Get rid of many table-based layouts, like the header on top of all pages (it's a table with two cells, one for the header, and another as placeholder for a logo).
 * Get rid of '''all''' `<font>` and `<center>` tags. I don't think there is any appropriate exception to this.
 * Use semantic elements. For example, replace `<span class="title">` with an `<h2>` element (or whatever appropriate level), `<td class="heading">` with `<th>`, etc.
 * Use more [meaningful CSS class names](http://www.w3.org/QA/Tips/goodclassnames), saying what the element is, not what it should look like. A class named 'smalltext' is useless if somebody makes it have big text. 'forum-description' is a lot better.

**Comment by Ageless93** [comment]
Isn't this what the [Bootstrap stylesheet](https://boinc.berkeley.edu/trac/wiki/StyleSheets) does?

**Comment by AenBleidd** [comment]
Is it still an issue?

CC: @davidpanderson

**Comment by davidpanderson** [comment]
Old issue; mostly fixed by bootstrap conversion.
