### ISSUE TITLE
BOINC not running (a bit generic I know but this is the specific statement presented)

### ISSUE THREAD

**Issue by gsd4me** [BOINC/boinc#5762]
My apologies if this has been asked before: in my defence I don't  have the time to do a detailed search on the matter, but I have done a quick search, but nothing has come up. so ....
When my laptop is not being used, BOINC is supposed to do its thing but now every time that it is 'allowed' to proceed, I get the screen notification that "BOINC is not running" and I have to reconnect to the server to get positive work done. I have changed various configuration options and settings but the situation still occurs
This is a newish 'problem' (past few months now) so obviously encompasses W10 upgrades and BOINC reconnections but is becoming very frustrating as it is something that I am unable to correct easily and intuitively. My 'normal' tasks have not altered that much (same background programs running as has always been the case, but obviously they have been updated as well over time so it doesn't preclude any of *those* updates being a possible root cause) 
Has anyone got any ideas/suggestions/fixes ? What is the cause of the presentation of this statement?
I am running BOINC on an ASUS 64bit W10 machine
regards
ADB

**Comment by AenBleidd** [comment]
@gsd4me, thank you for your report.
Unfortunately, provided information is not enough to understand the issue.

Please go to the BOINC Data directory (by default it's 'C:\ProgramData\BOINC') and send us the next files:
- stderrdae.txt
- stdoutdae.txt

Thank you in advance

**Comment by gsd4me** [comment]
[stderrdae.txt](https://github.com/user-attachments/files/16644668/stderrdae.txt)
[stdoutdae.txt](https://github.com/user-attachments/files/16644669/stdoutdae.txt)

**Comment by RichardHaselgrove** [comment]
Project 'NumberFields' is uncontactable today because of an expired (non-auto-renewed) SSL certificate. That part can be ignored for now.

**Comment by AenBleidd** [comment]
Ok, I have looked at the logs, and I saw no problems there. BOINC client just connects to the projects when needed, and does some job.
I don't see any unexpected failures or something similar.
As far as I see, 'BOINC is not running' message could be seen from the screensaver only, so this might be just an issue with the screensaver, not the BOINC client itself.
Or, what is more possible: you have configured BOINC screensaver in your Windows, but you shutdown BOINC client for some reason, and when BOINC screensaver is turned on by Windows, it will show exactly this message.
@gsd4me, could you please clarify, what exactly you mean by saying
```
and I have to reconnect to the server to get positive work done
```
?

**Comment by AenBleidd** [comment]
Not enough information to understand if there is an issue or not.
Closing this for now.
