### ISSUE TITLE
Convert PHP code to use the new database abstraction layer.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#578]
**Reported by Didactylos on 9 Sep 38264715 04:53 UTC**
Convert PHP code to use the new [database abstraction layer](PhpDb).

Source: DevProjects

Migrated-From: http://boinc.berkeley.edu/trac/ticket/600

**Comment by ChristianBeer** [comment]
This is mostly done. The last remnants of old code are in the Ops section (which needs a complete overhaul) and some small admin scripts.
