### ISSUE TITLE
Add option to keep project files (prevent auto-removal) to avoid re-downloading identical files

### ISSUE THREAD

**Issue by sr1gh** [BOINC/boinc#5782]
I'm not sure if this is a project specific issue or not, but some projects will remove files from the project directory when the device has completed all assigned tasks. Then, when the device gets more tasks, the files are downloaded again. If the files have changed, then this would be necessary, but if the files have not changed (which appears to be the case for some projects), then this results in unnecessary network usage.

An example is World Community Grid (Mapping Cancer Markers), where each task downloads less than 1 KB of data. There is a "one time" download of about 45 MB, however, the file is removed whenever there are no tasks running, and needs to be downloaded again when there are more tasks. This can happen multiple times per day depending on how many projects the device has, the size of the work buffer, and how many CPU core are being used.

An option could be added (possibly in cc_config.xml) to prevent removal of files in the project directory if not absolutely necessary. (Files should still be updated if the project server has changed them)

**Comment by davidpanderson** [comment]
There is a server-side option to mark files as "sticky",
meaning they're kept around even when not in use.
WCG needs to use this for the large file.
