### ISSUE TITLE
Change default Q&A page to refer BOINC-specific questions to BOINC web site.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#581]
**Reported by Didactylos on 3 Apr 38264727 17:46 UTC**
Change default Q&A page to refer BOINC-specific questions to BOINC web site.

Source: DevProjects

Migrated-From: http://boinc.berkeley.edu/trac/ticket/603

**Comment by romw** [comment]
**Commented by jbk on 8 Sep 38997577 17:46 UTC**
Could we get a little bit more specific here;
- What default Q&A page? Is it forum_help_desk.php?
- What BOINC website should it point to? The main BOINC website? The BOINC wiki user manual? The BOINC-dev forums?

**Comment by ChristianBeer** [comment]
Not listed on DevProjects and still unspecific.
