### ISSUE TITLE
Android: battery draining

### ISSUE THREAD

**Issue by vladkasianenko** [BOINC/boinc#5815]
Hello.

I have BOINC 8.0.3 for Android.
Currently, I have setup for "at least 80% battery" and "only when charging".
Even when on the charger, it discharges slowly. So it reaches 80% and then stops computing. Once the level is above the threshold, it starts computing for a short period of time, because the battery drains again.

It would be nice if BOINC could wait up until 100% or something and then resume computing for the next discharge level. Let me know what do you think.

Hardware setup:
- Samsung S22 (Exynos 2200)
- 100W charger (but the Samsung itself might limit it to some lower values)

**Comment by AenBleidd** [comment]
Thank you for the report.
If your charger doesn't keep your battery at least on the same level while having heavy CPU load - then you definitely have some issues with the charger (probably need to replace it).
For now I'd suggest you to decrease the number of CPU cores used by BOINC: this will decrease the load, and should be able at least to keep your battery on the same level while charging.

The idea you suggested will increase complexity of the application itself without real benefits: as stated above, it's not ok if your charger can't charge your battery under load, and this is not the normal situation.

That is why I have to refuse your proposal and won't continue with it.

**Comment by vladkasianenko** [comment]
@AenBleidd, thank you for reply.

Probably it's not the problem with the charger, as I use it with many devices and only Samsung S22 is discharging over the time - I think it's because the power is limited under the load to prevent overheating or something, so it's more to how Samsung manages it.

I agree that it might increase complexity and we definitely don't want to make it too complex, so yeah, I agree with you that we should not do anything about it.
