### ISSUE TITLE
Android App threshold issue

### ISSUE THREAD

**Issue by vladkasianenko** [BOINC/boinc#5816]
**Describe the bug**
It states that computing should resume after 80% and now it's 82%, but no computing is performed. 

**Steps To Reproduce**
1. 
![SmartSelect_20240923_180027_BOINC](https://github.com/user-attachments/assets/d74ef83a-47db-49c8-89b2-e791721baf1a)

**Expected behavior**
Computing resumed. 

**System Information**
 - OS: Android 14, One UI 6.1, Samsung S22
 - BOINC Version: 8.0.3

**Comment by AenBleidd** [comment]
Closed as a duplicate of #5305
