### ISSUE TITLE
Einstein Home : Binary radio pulsar search (0,5 CPU + 1 Intel GPU) can't be processed

### ISSUE THREAD

**Issue by SIAMikeOne** [BOINC/boinc#5818]
**Describe the bug**
When computing any of the "Binary radio pulsar search (MeerKAT) 0,12 (BRP7-opencl-intel_gpu)" the system estimates 1 hour 14 minutes. It takes then usually about 4-5 hours to get to 90 %, and after another 12 hours it still have something about 99 % and never finishes.  If you postpone the task, the processed part is never stored, when re-activating the task the process starts again from zero. When closing and re-opening the BOINC the same situation, again starts from zero. The tasks are  running on 0,5 CPU + 1 Intel GPU. This situation is constant for more than a month.

**Steps To Reproduce**
1. Download any of the Binary radio pulsar search (MeerKAT) 0,12 (BRP7-opencl-intel_gpu) files
2. Start the computing...

**Expected behavior**
The computing should finish as usually.

**Screenshots**
Check the included file: two marked files to process, estimate is about 1:13:55, the file was running for more than hour.

**System Information**
 - OS: Windows 10 Home 22H2
 - BOINC Version: 8.0.2. x64

**Additional context**
![EinsteinHome](https://github.com/user-attachments/assets/ec32e1ad-7f2f-4226-bb09-1c306ac4cc58)

**Comment by brevilo** [comment]
Hi SIAMikeOne,

this is likely not a general BOINC issue. Would you mind joining us [here](https://einsteinathome.org/community/forum/22) and re-post your issue? Let's discuss it there. 

Thanks
