### ISSUE TITLE
Provide vboxwrapper 26208 for download

### ISSUE THREAD

**Issue by computezrmle** [BOINC/boinc#5826]
Since vboxwrapper 26207 had been published there were a couple of code changes that solve major issues and make it work with the most recent VirtualBox version.

Please upgrade the version number to 26208 and provide it for download (Apple/Linux/Windows) at
https://boinc.berkeley.edu/dl/

Hint:
The (linux) binary that is automatically generated contains lots of debug information.
To keep the final binary small those should be removed
`strip vboxwrapper_26208_x86_64-pc-linux-gnu`

**Comment by AenBleidd** [comment]
I'll work on that

**Comment by AenBleidd** [comment]
FYI: When we are building apps for release, we are already stripping all the symbols, so there is nothing to do here.

**Comment by computezrmle** [comment]
Can this be completed please.

**Comment by AenBleidd** [comment]
@computezrmle, yes, we are working on that, and it should be done soon.
Currently we have to switch to another signing solution for Windows, so unfortunately this takes a little bit more time that it was expected before.
Sorry for the delay.

**Comment by AenBleidd** [comment]
Done: https://github.com/BOINC/boinc/releases/tag/vboxwrapper%2F26208

**Comment by computezrmle** [comment]
@AenBleidd 
Thanks, but the Apple version is missing.

**Comment by AenBleidd** [comment]
MacOS Version is built manually, and will be uploaded here https://github.com/BOINC/boinc/wiki/Vboxwrapper-release-notes when ready
