### ISSUE TITLE
Add a mechanism where joining a team or group requires approval of an admin.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#583]
**Reported by Didactylos on 25 Apr 38264736 22:13 UTC**
Add a mechanism where joining a team or group requires approval of an admin.

Source: DevProjects

Migrated-From: http://boinc.berkeley.edu/trac/ticket/605

**Comment by romw** [comment]
**Commented by anilm on 22 Apr 42229737 15:15 UTC**
hi Didactylos can you provide more data regarding this function ,i mean do you want this functionality in all sites linked to BOINC or only to specific ones

**Comment by Ageless93** [comment]
Is this still something people want?

**Comment by AenBleidd** [comment]
There was no any response neither from the original topic starter not from any other.
Closing this as 'wontfix'
