### ISSUE TITLE
Ability to select which GPUs to suspend when computer is in use

### ISSUE THREAD

**Issue by sr1gh** [BOINC/boinc#5849]
When "Suspend GPU computing when computer is in use" is enabled, it suspends computing on all GPUs. In a system with multiple cards, where only one card is used for display output, this might not be ideal.

I would like to be able to suspend only the primary GPU that is used for display output, and allow the other GPUs to run based on the normal usage settings. A config option that can be added in cc_config.xml could allow users to specify which GPUs to suspend using "type" and "device_num".
It would be similar to the way the "exclude_gpu" option works.

**Comment by AenBleidd** [comment]
Closed as a duplicate of #2991
