### ISSUE TITLE
Unify preferences

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#585]
**Reported by Didactylos on 7 Dec 38264746 05:46 UTC**
Unify preferences (i.e., have the same prefs available on the web as in the Manager, and if possible make the interface look the same).

Source: DevProjects

''These changes need to be coordinated with changes to BOINC Manager.''

Migrated-From: http://boinc.berkeley.edu/trac/ticket/607

**Comment by ChristianBeer** [comment]
This was done for 7.4 or 7.6 so I consider it closed. The weekday schedule is still only configurable through the Manager but I would prioritize a remodel of the whole preference system over implementing this on the website.
