### ISSUE TITLE
app_testproject appears in 8.1.0

### ISSUE THREAD

**Issue by Dave-catcher** [BOINC/boinc#5859]
Did an update of 8.1.0 this morning and app_testproject appeared in my projects list in the manager. 1 task appears for this project but it says, Downloading suspended user request.
Under the activity tab network activity is shown as Always.

**Steps To Reproduce**
1. Follow steps from BOINC site to install nightly Linux build. (Instructions for Ubuntu 24.04 used as none for 24.10) Launch manager via GUI On removing the project, network activity is still not available. If I do systemctl stop boinc-client followed by systemctl start boinc-client the project has returned.
2.  This also happens on a clean install of 24.10 and boinc8.1.0 in a VM If I need to for dev work on CPDN will go back to 8.0.4 but happy to stay with this till that happens.

**Expected behavior**

**Screenshots**

**System Information**
 - OS: 
 - BOINC Version: 8.1.0

**Additional context**Ubuntu24.10 upgraded from 14.04 about a week ago.

**Comment by davidpanderson** [comment]
Oops!  I neglected to remove some debugging code.
Fixed in #5860

**Comment by Dave-catcher** [comment]
Thank you!
