### ISSUE TITLE
Add new profile features

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#587]
**Reported by Didactylos on 15 Jan 38264757 08:53 UTC**
Add new profile features:
    \* list of recent posts and threads this person created, on this and other projects.
    \* other features from social networking sites?
    \* Add "referral" mechanism: new user creates account, enters email of "referrer" (or goes to URL that has it embedded). Give referrer a fraction of credit (or a 1-time bonus). List referrals on user page (show only those still active). Add new referral table to DB. 

Source: DevProjects

Migrated-From: http://boinc.berkeley.edu/trac/ticket/609

**Comment by Ageless93** [comment]
Is this still something that users want?

**Comment by lfield** [comment]
An ordered list of posts is already visible on the profile for a project. Features from other social networking sites should be considered in the general context of support OAuth (#2163). Referral mechanism should be discussed in the context of credit (#2498).
