### ISSUE TITLE
Work done not updating

### ISSUE THREAD

**Issue by MDbrewdude** [BOINC/boinc#5874]
I am running rosetta@home on two separate windows 10 computers at my home.  Both are still running jobs for the project, but the "work done for the project" field is stuck on the same value for many days now.  I rebooted both computers, that was no help.  I removed boinc from both and re-installed it with the latest version, and the work done is still not updating.  I am logged into rosetta with the same username/password on both machines.  This is a bit disconcerting as I am now unsure that the work my computers are doing is being used by the project.

**Comment by AenBleidd** [comment]
It might be the project that doesn't send you the updated statistics.
Better to ask on their forum.
Please also keep in mind that you will receive points only when the task is done and validated.

**Comment by MDbrewdude** [comment]
Hi Vitalii,
 
Whatever you did last time (maybe just copying Boinc) did the trick, both my computers were showing updated work done.  This lasted for several weeks, but now the problem has returned.  I have tried rebooting, resetting the project, and re-installing boinc, none of that seems to help.  Not sure why this is happening, could use help again.
 
Thanks,
Jerry Davieau

**Comment by AenBleidd** [comment]
@MDbrewdude, I did nothing. Just let your PCs with BOINC run by themselves. They will update the statistics after some time.
And please keep in mind, that Rosetta@Home and other projects are managed separately by different teams from different universities and other organizations.
And BOINC maintainers are unrelated to these teams.
