### ISSUE TITLE
Team customisation features

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#588]
**Reported by Didactylos on 25 May 38264762 09:20 UTC**
Make it easy for teams to offer a client download that features their skin, and pre-register the user on that team for any projects he attaches to.

Source: DevProjects

Migrated-From: http://boinc.berkeley.edu/trac/ticket/610

**Comment by Ageless93** [comment]
Advanced view cannot be skinned, so that's something that needs to be tackled first then. I'd think that teams should be able to follow http://boinc.berkeley.edu/wiki/Creating_a_skin_for_the_BOINC_Manager for skinning Simple view.

**Comment by lfield** [comment]
It seems that skins for the Simple view are already supported. If this is wished for the Advanced view then a specific issue should be opened. In general people should be encouraged to obtain the client from a trusted source.
