### ISSUE TITLE
I can't install boinc-client-8.1.0-1274 on wsl1

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#5880]
**Describe the bug**
It fails during configuration stage while running
Executing: /lib/systemd/systemd-sysv-install enable boinc-client
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
**Steps To Reproduce**
1. Add nightly repository
2.  run "sudo apt install boinc"

**Expected behavior**

**Screenshots**

![Image](https://github.com/user-attachments/assets/f57d403b-498e-405f-85eb-1dc166c96a68)

**System Information**
 - OS: ubuntu 22.04
 - BOINC Version: 8.1.0-1274

**Additional context**

**Comment by AenBleidd** [comment]
This is a known limitation of WSL.
BOINC Linux package is not supposed to be installed on WSL.

**Comment by kotenok2000** [comment]
I want to be able to run boinc from user directory, using this command.
cd "/home/user/BOINC" && exec /usr/local/bin/boinc --gui_rpc_port 31417 $@

**Comment by AenBleidd** [comment]
Currently we don't support this type of installations in our Linux packages.
And there are no plans to add it.
