### ISSUE TITLE
Boinc doesn't use"When computer is not in use" settings

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#5885]
**Describe the bug**
Boinc doesn't use "When computer is not in use" settings
When i set desired cores usage for "in use" and for"not in use" there is no way to set "in use means mouse or keyboard input in the last x minutes" becauwse input field is deactivated.
You can activate it by checking "suspend when computer is in use", but it suspends computing completely.

**Steps To Reproduce**
1. Set desired cpus use in "computing preferences" for both cases.
2. Attempt to set mouse/keyboard activity timeout: input field isn't working.

**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/f9403303-0a84-4a3a-8d50-44d7a00c54ca)

**System Information**
 - OS: 10.0.22631.4391
 - BOINC Version: 8.0.4

**Additional context**

**Comment by AenBleidd** [comment]
@davidpanderson, could you please take a look? I think this is a proper scenario when user wants to not pause CPU and/OR GPU but instead use different settings for 'In use' and 'Not in use' cases.
