### ISSUE TITLE
Incorrect behviour of arrow buttons on simple interface

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#589]
**Reported by korpela on 8 Feb 38268759 21:46 UTC**
Clicking the arrow buttons for choosing tabs on the simple GUI causes all visible tabs to be replaced with hidden ones.  This is not typical behavior for tabbed interfaces.  The typical behavior is to move the selected page one tab to the left or right, scrolling the tabs by one tab as necessary.  This would be a better implementation.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/611

**Comment by romw** [comment]
**Commented by Nicolas on 22 Sep 38268785 03:06 UTC**
Clarified that it's talking of the simple GUI.

At first I thought you meant the advanced view, where arrows do move a single tab.

**Comment by ChristianBeer** [comment]
This issue is 9 years old, a lot has changed since then. If this is still an issue with the new simple GUI please open a new issue.
