### ISSUE TITLE
Correct a dl link at the BOINC wiki

### ISSUE THREAD

**Issue by computezrmle** [BOINC/boinc#5917]
At the wiki page (https://github.com/BOINC/boinc/wiki/Vboxwrapper-release-notes) please correct the link to the Windows version of vboxwrapper 26208.
It points to a zip file that does not exist.

Wrong:
https://boinc.berkeley.edu/dl/vboxwrapper_26208_windows_x86_64.exe.zip

Right:
https://boinc.berkeley.edu/dl/vboxwrapper_26208_windows_x86_64.exe

**Comment by davidpanderson** [comment]
Oops!  done
