### ISSUE TITLE
Improve the issue templates.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [BOINC/boinc#5940]
As an example, the FR template is currently the undermentioned:

<blockQuote>

~~~Markdown
**Describe the problem**
A clear and concise description of the problem you're looking to solve.

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Additional context**
Add any other context or screenshots about the feature request here.
~~~

</blockQuote>

This isn't convenient to use, because placeholders must be removed. Additionally, nor is it semantic, so it's inaccessible for screen readers.

Instead, it should be something like the undermentioned:

~~~Markdown
#### **Describe the problem**

<!-- A clear and concise description of the problem you're looking to solve. -->

#### **Describe the solution you'd like**

<!-- A clear and concise description of what you want to happen. -->

#### **Additional context**

<!-- Add any other context or screenshots about the feature request here. -->
~~~

**Comment by AenBleidd** [comment]
Issue templates should be fixed but in a completely different way (similar to this: https://github.com/microsoft/vcpkg/tree/master/.github/ISSUE_TEMPLATE)
Feel free to open PR with the improved template

**Comment by RokeJulianLockhart** [comment]
1. > Issue templates should be fixed
1. > Feel free to open PR with the improved template

Thanks. I've submitted https://github.com/BOINC/boinc/pull/5944#issue-2730243142.

> but in a completely different way (similar to this: https://github.com/microsoft/vcpkg/tree/master/.github/ISSUE_TEMPLATE)

@AenBleidd, I don't quite understand how those YAML files work, although I suppose the undermentioned would work?

~~~YAML
name: Request a feature or improvement
description: Suggest an improvement to vcpkg.
title: ''
labels: ["category:vcpkg-feature"]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: "<!-- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] -->"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      placeholder: "<!-- A clear and concise description of what you want to happen. -->"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      placeholder: "<!-- A clear and concise description of any alternative solutions or features you've considered. -->"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "<!-- Add any other context or screenshots about the feature request here. -->"
    validations:
      required: false
~~~

Why do you prefer a YAML file, over a Markdown file with a YAML preamble (which `/.github/ISSUE_TEMPLATE/feature_request.md` currently is)?

**Comment by AenBleidd** [comment]
Because templates created by YAML looks better and more informative.
Please provide a proper PR to review and test.
Thank you in advance.
