### ISSUE TITLE
Target AOSP API level ≥ 34 to remediate "Unsafe app blocked" prompt during installation.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [BOINC/boinc#5941]
#### **Describe the problem**

When `com.google.android.packageinstaller` installs https://f-droid.org/repo/edu.berkeley.boinc_80003.apk, `com.android.vending/com.google.android.finsky.protectdialogs.activity.PlayProtectDialogsActivity` appears, to warn the user:

![Image](https://github.com/user-attachments/assets/6b86454a-2759-4a82-9c5d-5f1e01ad8b09)

#### **Describe the solution you'd like**

Target an API level ≥ 34. Lower would also probably work, but merely temporarily, and why work on targeting an older API level?

#### **Additional context**

If it gets older, you might see https://github.com/cypherstack/stack_wallet/issues/1045#issue-2723082738 instead.

**Comment by AenBleidd** [comment]
We cannot increase API level, because then complete application will stop working. See detailed explanation here: #5344

**Comment by RokeJulianLockhart** [comment]
> https://github.com/BOINC/boinc/issues/5941#issuecomment-2531369630

@AenBleidd, doesn't that mean that this application's days are numbered...?

**Comment by AenBleidd** [comment]
> doesn't that mean that this application's days are numbered...?

Might be if we don't get a solution.
Any ideas from your side?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/BOINC/boinc/issues/5941#issuecomment-2531578744

@AenBleidd, [`stackoverflow.com/questions/78716684/executing-binary-files-on-android-targetsdkversion28-raise-permission-denied#comment138784482_78716684`](https://stackoverflow.com/questions/78716684/executing-binary-files-on-android-targetsdkversion28-raise-permission-denied#comment138784482_78716684:~:text=The%20updated%20discussion%20by%20the%20Termux%20team%20(follow%20links%20in%20thread)%20but%20found%20your%20prior%20post%20with%20similar%20references.) may be useful (note the *comment* that I have linked to).

**Comment by AenBleidd** [comment]
@RokeJulianLockhart, thank you for the link. It's a big discussion, and as far as I see, it's still open that means that there is no solution yet.
I'll check it later when we will decide how to proceed with that
