### ISSUE TITLE
Reimplement the AOSP GUI using M3.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [BOINC/boinc#5942]
#### **Describe the problem**

The current GUI is getting older. It appears to be an implementation of one of the first versions of M2, which differs significantly to the current standard – M3(+You).

#### **Describe the solution you'd like**

Replace it with a Material 3 GUI.

#### **Additional context**

Material You would also be nice, but who cares? This isn't the kind of app for which that matters.

**Comment by AenBleidd** [comment]
Current design is fine enough.
There are no plans to update to every new framework without significant reason.

**Comment by AenBleidd** [comment]
> would you accept a PR that does so?

Yes.
