### ISSUE TITLE
A bug about daily avg credit

### ISSUE THREAD

**Issue by takato3000** [BOINC/boinc#5955]
### Describe the bug

Daily avg credit calculation may not correct.
There may be some issues with the date calculation.
Maybe it's not an issue with the projects.(But it could be, if they use the same calc functions, etc.)
I observed the same issue in 2 projects.

### Steps to reproduce

1.Open "Projects" Tab in Boinc Manager
2.Find a Project and get the values of  Work done and Avg.work done
- for example: Asteroids@home It's 19661 credits in total, avg work done is 1729.35

3.Calculate the Result

### Expected behavior

avg work done should not be so small
Because I registered on 2024 Dec 10.(Date based on UTC, I got the first task at 10 Dec 2024, 16:47:00 UTC)
It's 2024 Dec 15 4:08am Here(+8UTC).
For a calculation by hand, I can get the answer of project asteroids@home is in range about 3922(5 days) - 4915.25(for 4 days)

appended at 4:27 am:
For me, The best calculation is using **total passed hours / 24** to calculate the result, maybe too slow to show a value for a new user, using **half an hour** or **a quarter** are both okay.

### Screenshots

![Image](https://github.com/user-attachments/assets/f44d3ce7-a5dd-4235-9ed2-6b09113fd7c1)
![Image](https://github.com/user-attachments/assets/1cc3c556-0495-4d52-9492-5a02e535cc4d)

### System information

- OS: Windows 11
- BOINC Manager Version: 8.02(x64) Windows

**Comment by davidpanderson** [comment]
'Recent average credit' is an exponentially weighted average.
It ramps up to the correct long-term average over a couple of weeks.
