### ISSUE TITLE
Manager should show location for selected host.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#6]
**Reported by romw on 14 Sep 37291386 02:13 UTC**
The boincmgr should have somewhere that the user can tell which profile (location) the client is using. This does show up in the Messages when the client first starts, but is gone after the logs rotate.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/6

**Comment by romw** [comment]
**Commented by Didactylos on 22 Oct 37504131 08:00 UTC**
I think this will require a GUI RPC. At the same time, can I request a GUI RPC to ''set'' the venue, also?

**Comment by Ageless93** [comment]
Already added to BOINC Manager's Project properties (in Advanced view)
