### ISSUE TITLE
Change OK button on Advanced Preferences to Save button

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#601]
**Reported by Ageless on 17 Apr 38309470 22:13 UTC**
When using the Simple View preferences, you go out by either clicking the Save or Cancel button. When using the Advanced View preferences, you go out by clicking either the OK or Cancel button.

People now just look into the Advanced Preferences and without knowing it make them work as they click OK to go out, then later they complain on forums that their preferences on the web site don't work when they change them and update BOINC. We increasingly find that these people are unknowingly using the override preferences, because they looked in once and went out by clicking OK.

So my idea is to standardize the buttons in Simple View and Advanced View, make them both Save and Cancel. Turning them around, so Cancel is first, would perhaps also make a difference. An extra pop-up window in which you have to confirm that you want to use the override preferences, may also do the trick. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/623

**Comment by romw** [comment]
**Commented by Nicolas on 20 Feb 38310441 20:00 UTC**
Agreed.

Make sure translators also write the button label in a way that makes clear it's doing changes.

**Comment by romw** [comment]
**Commented by Nicolas on 29 Oct 38310447 23:06 UTC**
Removed unneeded `[[BR]]` from description.

**Comment by romw** [comment]
**Commented by Pepo on 11 May 38315316 09:46 UTC**
Replying to [Ageless](ticket:623):
> So my idea is ''to standardize the buttons in Simple View and Advanced View, make them both Save and Cancel.'' Turning them around, so Cancel is first, would perhaps also make a difference.
Possibly to the extent that, if turned around, the user could inadvertently click the wrong one, because (s)he is used to the (somehow standardized) [ [[No](Yes]) ] order.

**Comment by romw** [comment]
**Commented by Ageless on 17 Jan 39897348 17:46 UTC**
May I re-request this option? It's still not clear to many people who peek in on the Advanced preferences that clicking OK saves those preferences and that BOINC will immediately start using them, overriding their web-preferences. They think they just exit the window by clicking OK. 

How difficult is it to use '''Save''' instead of '''OK'''? 

Or else, as interim solution add a good warning at the top. Something like "Clicking OK will save all preferences in this window to a local file, will override any of the same preferences set through the projects and BOINC will start using them immediately. If you do not want to use these local preferences, click Cancel."

**Comment by ChristianBeer** [comment]
The Dialog still uses OK/Cancel buttons with a tooltip that says the changes will be saved. There is also awarning at the top of the page that says which preferences are used (local or web). I still find this not clear enough. Relabeling the button from OK to Save would be much clearer.

**Comment by Ageless93** [comment]
Seeing how our developers are adding buttons to the manager's properties windows, can this issue be looked at now as well?

**Comment by AenBleidd** [comment]
Yes, I can do this

Best regards,
Vitalii Koshura

2017-08-15 0:15 GMT+03:00 Jord <notifications@github.com>:

**Comment by Ageless93** [comment]
Thanks, Vitalii. :-)



-- Jord van der Elst.

**Comment by AenBleidd** [comment]
Fixed in #2043

**Comment by davidpanderson** [comment]
Looks great - thanks.

**Comment by CharlieFenton** [comment]
Note that if this is ported to the 7.8 branch, it will require another update to the localization template BOINC_Manager.pot. It is important that any changes to localizable strings be done long enough before public release to give the translators for the various languages sufficient time to update their translations.

**Comment by CharlieFenton** [comment]
The label of this button now disagrees with the instructions at the top of the dialog in clientgui/DlgAdvPreferencesBase.cpp and clientgui/sg_DlgPreferences.cpp, which still say to "click OK" when there is no global_prefs_override.xml file:
    Using web-based preferences from <project URL>
    Set values and click OK to use local preferences instead

**Comment by AenBleidd** [comment]
@CharlieFenton, thank you. I'll fix this

Best regards,
Vitalii Koshura

2017-08-18 11:12 GMT+03:00 CharlieFenton <notifications@github.com>:

**Comment by AenBleidd** [comment]
Fixed in #2050

**Comment by truboxl** [comment]
So this is why when I upgraded from 7.8.3 to 7.9.3 and found that the `Enter` button exhibits the behaviour differently in Computing Preferences window. It's ok from a noob proof standpoint.
