### ISSUE TITLE
Core client config file locations

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#605]
**Reported by Eric Myers on 27 Jul 38315331 23:06 UTC**
The files cc_config.xml, global_prefs_override.xml, gui_rpc_auth.cfg, and remote_hosts.cfg are configuration files which the user can edit (even if most won't), so Debian requires that they be under /etc,
while the "usual" place for them is the working directory.   Right now the Debian package takes care of this with soft links.  A more robust solution would be to have the core client look for the files in a list of places, using the first it finds.   The files in the working directory would be checked first, and used if they exist.  The files in /etc/boinc would be checked and used if nothing is found in the working directory.  

See the discusion at  http://boinc.berkeley.edu/trac/wiki/UnixClientPackage

Migrated-From: http://boinc.berkeley.edu/trac/ticket/627

**Comment by romw** [comment]
**Commented by romw on 8 Feb 38315492 05:20 UTC**
Isn't /etc only supposed to be tweaked by administrators?

This would work well for package installs where BOINC is being installed as a daemon, but how is this supposed to work is BOINC has been installed by the user in their home directory?

It should probably be:
~/etc
/usr/etc
/etc

Or something to that effect.

**Comment by romw** [comment]
**Commented by Nicolas on 30 Apr 38348272 16:53 UTC**
Replying to [romw](comment:1):
> Isn't /etc only supposed to be tweaked by administrators?
> 
> This would work well for package installs where BOINC is being installed as a daemon, but how is this supposed to work is BOINC has been installed by the user in their home directory?

I don't know how to do it for official binaries, but if a user builds it from source, he would specify a different `--prefix` to get it on his home directory, and `/etc` would end up in `~/my_boinc_build/etc`. If he '''doesn't''' set a prefix, it would be in `/usr/local/etc` (just like binaries would be in `/usr/local/bin`).

It should be in /etc if the binaries are in /usr/bin, which only happens if BOINC is installed by the package manager.

**Comment by Ageless93** [comment]
Any Debian developers in the house who know if cc_config.xml, global_prefs_override.xml, gui_rpc_auth.cfg, and remote_hosts.cfg are required to be in /etc instead of /var/lib/boinc-client/ where they go to now?

**Comment by lfield** [comment]
It looks like this was done.

> # dpkg -L boinc-client | grep xml
> /etc/boinc-client/cc_config.xml
> /etc/boinc-client/global_prefs_override.xml

> # dpkg -L boinc-client | grep cfg
> /etc/boinc-client/gui_rpc_auth.cfg
> /etc/boinc-client/remote_hosts.cfg
