### ISSUE TITLE
Checkpoint and quit

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#62]
**Reported by KSMarksPsych on 3 Jun 37298144 02:40 UTC**
Date: 11:34 AM 01-17-2006

I think BOINC Manager should :
- Display next checkpoint time
- When exit BOINC Manager, display a alert box/confirm that show the next checkpoint time and ask the user wait or not

**Comment by romw** [comment]
**Commented by Didactylos on 13 May 37504041 22:13 UTC**
This is impossible.

**Comment by romw** [comment]
**Commented by Nicolas on 27 Jul 37760292 22:40 UTC**
Replying to [Didactylos](comment:2):
> This is impossible.
But one useful alternative feature is "wait for checkpoints and quit". Wait for the running applications to checkpoint, and stop them, removing them from RAM. As apps are removed from RAM, resume others still in RAM and do the same. Quit core client after they all quit.

**Comment by romw** [comment]
**Commented by MikeMarsUK on 1 Nov 37761315 08:53 UTC**

Sounds like a good idea Nicolas.  I currently do that manually when shutting down on my Quad (I run mostly CPDN-SAP which checkpoints every 50 minutes on my PC).  

When I suspend a SAP task I resume a task which has quicker checkpoints (so the last 30 minutes or so while I'm waiting for the final SAP task isn't idle).

**Comment by romw** [comment]
**Commented by John McLeod VII on 8 Sep 37761871 04:53 UTC**
Noting when the next checkpoint is actually going to occur is not possible.  The checkpoints are completely under the control of the science application, and not the BOINC core.  The BOINC core can request that a checkpoint not occur until a particular period has ellapsed since the last checkpoint, but it cannot be enforced.  The core client cannot force a checkpoint to occur.

The best that could be done is to indicate when the last checkpoint occurred.

**Comment by romw** [comment]
**Commented by Didactylos on 28 Feb 37879654 20:53 UTC**
The "wait and quit" feature has been suggested independently a few times now, so I suggest a GUI RPC is added so that add-ons can do this. I don't think there's enough need/demand to make it a standard Manager feature. Feature creep is evil!

**Comment by romw** [comment]
**Commented by Nicolas on 11 Apr 38165148 04:53 UTC**
Changed title to match the discussion on comments.

**Comment by romw** [comment]
**Commented by 512upload on 24 Oct 38176544 04:53 UTC**
I want a shutdown on next checkpoint feature too!

**Comment by romw** [comment]
**Commented by 512upload on 29 Jul 38176552 20:26 UTC**
*sorry, 'would like to have', that is.

**Comment by romw** [comment]
**Commented by 512upload on 23 Jan 40082029 05:20 UTC**
What if I just tell my computer to hibernate? Will I keep all the computation that was done up to this moment and when I start my PC back nothing will be lost including the information about the processing time I've contributed with to the project I'm using?

If yes, I think there is no need for this feature. Don't you agree?

**Comment by romw** [comment]
**Commented by davea on 13 Feb 40084579 02:40 UTC**
The client can't tell apps when to checkpoint.
They checkpoint when they want to.
Some checkpoint infrequently, some never.

If you hibernate and resume, computation continues with nothing lost.
If you turn off the computer, computation is lost back to the last checkpoint.

I don't think a new feature is called for.

**Comment by romw** [comment]
**Commented by Pepo on 15 Mar 40088914 14:13 UTC**
Replying to [davea](comment:14):
> The client can't tell apps when to checkpoint.
> They checkpoint when they want to.
>
> I don't think a new feature is called for.
It indeed is, described in [Nicolas](comment:3)' comment.

To summarize it, wait for all the currently running apps until they checkpoint: suspend them individually after having checkpointed and then stop the client if no more app is running.

(Each app suspended behind a checkpoint may be eventually removed from memory.)

(If some applications were suspended manually and the client can distinguish between these and such auto-suspended after a checkpoint, the manually suspended ones could be started once more to let them checkpoint prior to exit. Sure the user would have to keep in mind that some apps do not checkpoint at all and he could wait indefinitely... well, until the computation ends.)

**Comment by pataquets** [comment]
@romw: You might be interested in #544.
