### ISSUE TITLE
Remove -fomit-frame-pointer and -ffast-math gcc flags

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#625]
**Reported by mjakubicek on 5 Jul 38365301 19:06 UTC**
Is there any particular reason to have those flags set as default? They can make debugging much harder or impossible and should be avoided if possible.
I ask because they are currently prohibited for Fedora, so that I had to remove them anyway in the Fedora package.
(patch included)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/647

**Comment by romw** [comment]
**Commented by romw on 8 Sep 38365984 06:13 UTC**
This would cause a drop in benchmark scores.

See ticket #155 for further information.

David, should we re-visit this issue?

**Comment by romw** [comment]
**Commented by Nicolas on 22 Oct 38747861 21:20 UTC**
I think ONLY the benchmark .cpp files should be compiled with these flags.

**Comment by romw** [comment]
**Commented by mjakubicek on 20 Jul 38966144 03:33 UTC**
OK, what's the decision? Having this only for benchmark.cpp seems to be a good tradeoff...

**Comment by romw** [comment]
**Commented by mjakubicek on 7 May 39550046 11:06 UTC**
Half year past...ping again?

**Comment by romw** [comment]
**Commented by mjakubicek on 5 Jun 39554812 22:13 UTC**
Just switched to the 6.6a branch and those flags are *not* present there.

**Comment by ChristianBeer** [comment]
Those flags seem to have been removed. They are only present for Android builds right now.
