### ISSUE TITLE
[PATCH] Until <project_name> is known, Manager's Statistics tab displays an empty string

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#636]
**Reported by Pepo on 1 Aug 38375190 12:26 UTC**
''(This is posibly a duplicate of, an extension of or just another side-effect of events described in ticket:578, #417 and #633 and related changesets.)''

While attaching a new project to host, its scheduler is for any reason down and does not return project's name, e.g.:

``` xml
<scheduler_reply>
    <message priority="low">Server error: can't attach shared memory</message>
    <request_delay>3600</request_delay>
    <project_is_down/>
</scheduler_reply>
```

In Manager's Statistics tab, an empty string is displayed instead of the project's name in the project list at the right side (''"All projects"'' and ''"A. p. (sum)"'' Mode view), a higher minigraph without title is displayed in the graphs area (''"All projects"'').

Project URL should be displayed instead (as it is in the Projects, Messages and Disk tabs).

Migrated-From: http://boinc.berkeley.edu/trac/ticket/659

**Comment by romw** [comment]
**Commented by Pepo on 1 Jun 38559359 05:46 UTC**
I can't compile the BOINC Manager, but I believe [this patch](http://boinc.berkeley.edu/trac/attachment/ticket/659/empty_proj_name_in_stats_tab.patch) should solve it.

**Comment by romw** [comment]
**Commented by ChristianB on 13 Feb 40704708 09:20 UTC**
Line numbers differ but patch is still valid for latest Manager.

**Comment by ChristianBeer** [comment]
I couldn't reproduce now that I tested it. It seems that the introduction of the get_project_config.php RPC solved the particular problem originally reported.
