### ISSUE TITLE
[PATCH] Add custom filter to validate time fields in AdvPrefsDialog in BM

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#637]
**Reported by Simek on 27 Feb 38375354 21:20 UTC**
I purpose to use wxFILTER_INCLUDE_CHAR_LIST to validate time fields in Advanced Preferences Dialog in BOINC Manager. Now those fields are not filtered.

I create simple patch, but I'm not a wxWidgets programmer. It's based on code sample from wxForum. Please check it!  

Migrated-From: http://boinc.berkeley.edu/trac/ticket/660

**Comment by ChristianBeer** [comment]
This was fixed since the report. Last touched in 85810e14a464ca673feeeb9dd162cf38f1116bf1.
