### ISSUE TITLE
Cascading in CSS code missing

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#649]
**Reported by jbk on 23 Apr 38407745 21:20 UTC**
Currently the web CSS code is one big stylesheet (either black, white or the new one) making it hard for projects to make and maintain their own customizations.
[Proposal ==
Change the CSS code to be 3-level.[[BR]([BR]]
==)]
The base level::
 includes styles necessary for correct layouting and display but nothing fancy
The look-and-feel level::
 includes styles that add a certain look or feel to the base layout (this is stuff like white, black, etc)
The project level::
 This level includes customizations made by the project.
[[BR]]
The base level is always included in the HTML header. The look-and-feel is configured in the project configuration file and included based on the selection there. The project customization is originally an example file provided in the framework in /html/project.example/ allowing a project to override or expand the styles. It is included if present.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/672

**Comment by romw** [comment]
**Commented by davea on 1 Aug 38408525 07:33 UTC**
Good idea.  Please divide white.css (and/or style2.css)
into these 3 parts.

**Comment by ChristianBeer** [comment]
This got somehow superseded by bootstrap. The 3 way split is supported by defining `STYLESHEET` and `STYLESHEET2` in `project/project.inc` which can be used to override the selected bootstrap theme.
