### ISSUE TITLE
Remove decimal points from 'Statistics' graph

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#656]
**Reported by Peter Moss on 25 Feb 38440730 04:00 UTC**
It's only a small thing that I find annoying.
Your graphing functions are really very good with the multiple steps etc. depending on scale, but... Its final the labeling of the axes and the redundant decimal points that you insist in having.

i.e. My Seti graph can go from 363500.0  to 368000.0 depending if i show all or just one project. In fact ALL my graphs show the '.0' on each of the Y-Axis labels.

In our company we strip these non-essential decimalisation points as they crowd the screen! If each of the labels contains a '.' then we check to see if the legends all have the last char of '0' if all do, then strip them off. Repeat till you reach a non-zero in one or the '.', if the '.' then strip that too!

It looks neater and takes less space up!

Migrated-From: http://boinc.berkeley.edu/trac/ticket/679

**Comment by Ageless93** [comment]
I think this issue can be solved now as well. Vitalii, if you have a moment, can you check if this is a lot of work? I can assume that with the multiple trillions of credits in some of the projects, that the trailing .00 are a bit excessive.

**Comment by AenBleidd** [comment]
@Ageless93 Yeah, I'll check it.

**Comment by AenBleidd** [comment]
Fixed in #2081

**Comment by AenBleidd** [comment]
@TheAspens, could you please take a look at this ticket?
It is already fixed and ready for release.
Thanks

**Comment by AenBleidd** [comment]
Fixed via #2081

**Comment by TheAspens** [comment]
@AenBleidd - thanks for just proceeding to close.  Sorry for the slow response.
