### ISSUE TITLE
Relax URL validation in BOINC Manager to allow for unqualified domain names

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#660]
**Reported by omar on 17 Jun 38469257 17:46 UTC**
It would be nice if someone could relax the URL validation to allow for unqualified domain names. This will make it easier for internal, office grids to be set up.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/683

**Comment by Ageless93** [comment]
Are we validating URLs before trying to connect to them?

**Comment by lfield** [comment]
For security https and FQDN should be used, even in an internal setting.
