### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#666]
**Reported by elfring on 12 Mar 38492917 02:13 UTC**
I suggest to try the search pattern "\b_+[on the source files. You
will find a couple of places where names are used that
begin with an underscore and an uppercase letter.

Examples:[[BR](A-Z]+")]
- [_BOINC_API_](source:/trunk/boinc/api/boinc_api.h@14966#L20)[[source:/trunk/boinc/clientgui/AccountInfoPage.h@14551#L20 _WIZ_ACCOUNTINFOPAGE_H_]([BR]]
  -)[[source:/trunk/boinc/win_build/installerv2/redist/Windows/src/boinccas/terminate.cpp@13804#L36 _BOINC_PROCESS]([BR]]
  -)

This does not fit to the expected [naming conventions](http://en.wikipedia.org/wiki/Reserved_identifier) of the [C language standard](http://www.open-std.org/JTC1/SC22/WG14/www/docs/n1124.pdf).

Migrated-From: http://boinc.berkeley.edu/trac/ticket/689

**Comment by romw** [comment]
**Commented by Nicolas on 14 May 39156959 16:53 UTC**
This report is about many different parts of the code, not API only.

**Comment by romw** [comment]
**Commented by dandelot on 27 Sep 40952184 20:53 UTC**


C++, sec 17.4.3.1.3:
Each name having two consecutive underscores (2.11) is reserved to the
implementation for use as a name with both extern "C" and extern "C++" linkage.

So various names like 
```__cuInit``` 
defined-and-used in client/coproc_detect.cpp are not
standard-conforming.
AFAICT the identifiers used in coproc_detect.cpp are 
chosen by boinc, not cuda (my apologies for this note if those
specific identifiers with leading underbars are somehow required by the cuda library,
as in that case all is well).

Those seem to the only double-underscore names defined in boinc.

**Comment by romw** [comment]
**Commented by elfring on 2 Nov 40960217 15:33 UTC**
Replying to [dandelot](comment:4):

How do you think about a [corresponding clean-up](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+use+identifiers+that+are+reserved+for+the+implementation) for your [include guards](http://en.wikipedia.org/wiki/Include_guard#Difficulties)?

**Comment by romw** [comment]
**Commented by dandelot on 29 Jun 40982655 20:00 UTC**
The include-guards rules (using guards
that follow the C/C++ rules) suggested in the link make sense to me.

It's difficult to ensure that include-guards in boinc work without conflicting
with other non-boinc identifiers,
but adding to the referenced suggestions by preceeding (in boinc source)
the guards with BOINC_ would be effective for most (assuming headers guards
always had a trailing _H to avoid confusing them with capitalized class names
like BOINC_PROCESS).

For example, in ```ViewNotices.h```
```
ViewNotices.h:#ifndef _VIEWNOTIFICATIONS_H_
```

could be ```#ifndef BOINC_VIEWNOTIFICATIONS_H_```
(of course change all instances of ```_VIEWNOTIFICATIONS_H_``` so it all works.)

Having the header file named ```ViewNotices.h``` while the guard is renamed
```BOINC_VIEWNOTIFICATIONS_H_``` (inconsistent spelling, notices vs notifications)
is slightly jarring but otherwise harmless.

I hope these comments are responsive to elfring's question...

**Comment by elfring** [comment]
Would you like to [reconsider the usage of some underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") in affected identifiers once more?

**Comment by davidpanderson** [comment]
I implemented the multiple-inclusion guard name part of this.

**Comment by davidpanderson** [comment]
I fixed the __cuinit and _BOINC_PROCESS type of problems.  Are there others?

**Comment by Ageless93** [comment]
Closing for now then.

**Comment by elfring** [comment]
>Are there others?

A few update candidates were left over.

Examples:
* [screensaver.h](https://github.com/BOINC/boinc/blob/dd2be877f22f59ffba41eb6b0a379772dadc1842/clientscr/screensaver.h#L19)
* [win-config.h](https://github.com/BOINC/boinc/blob/5c36ce25daae8532f44d81e9f4c5527bde5e0e51/win_build/win-config.h#L19)
