### ISSUE TITLE
xpm icons cause lots of compiler warnings

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#669]
**Reported by Nicolas on 24 Jul 38504082 05:20 UTC**
The .xpm images used for the GUI cause '''lots''' of compiler warnings about "conversion from string literal to char_". They should be modified to use `const char_` instead.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/692

**Comment by romw** [comment]
**Commented by Nicolas on 29 Nov 38710764 11:06 UTC**
Fixing this apparently makes gimp fail to read the .xpm files :/

**Comment by romw** [comment]
**Commented by Nicolas on 6 Nov 38925551 14:13 UTC**
Update: it doesn't. gimp failed to read them because I had removed the /* XPM */ from the first line. Making the arrays const doesn't cause any problem.

**Comment by romw** [comment]
**Commented by Nicolas on 3 Oct 39380809 15:06 UTC**
Fixed in r18151

**Comment by romw** [comment]
**Commented by Nicolas on 3 Oct 40931054 10:13 UTC**
Actually, r18151 fixed like half the files. The rest still give warnings.

**Comment by Ageless93** [comment]
Is this still an issue?

**Comment by AenBleidd** [comment]
As far as I see this issue was already fixed. Closing fo now
