### ISSUE TITLE
auto switch to HTTP 1.0

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#670]
**Reported by Ageless on 19 Aug 38520494 19:06 UTC**
We see a lot of people lately on different forums who cannot up/download or report work. In about 70% of these cases having them switch to HTTP 1.0 through cc_config.xml fixes things for them.

My request is that BOINC tries this automatically. If after a set amount of no go's on upload or download or report that the client switches to using HTTP 1.0, telling the person through the messages that it does this and checks if communications will get through then. 

If not, revert back to HTTP 1.1 and leave a message that they report this on the forums. 
If it works that the client stays using HTTP 1.0, it's possible something at the ISP changed. 

Setting this to Major even though if it happens to people, it blocks them from up/downloading and reporting. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/693

**Comment by romw** [comment]
**Commented by Ageless on 19 Jun 38520500 10:13 UTC**
Addendum: Why not use cc_config.xml? Because most of the time you're talking to people who don't know how to use their computer or add anything to it. They run BOINC, are happy to help a project but have no clue what to do when it doesn't work. Even if walked through how to set up a cc_config.xml file and what should be in it, some consider it too difficult and uninstall BOINC.

**Comment by lfield** [comment]
This is so old I don't think it is an issue anymore.
