### ISSUE TITLE
UPDATED2: Alternative/New version of "white.CSS"

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#693]
**Reported by Simek on 28 Nov 38602351 10:13 UTC**
'''Work In Progress'''

Idea was taken from: http://boinc.berkeley.edu/trac/wiki/DevProjects
[CSS instead of HTML for formatting where possible; clean up white.css; improve the look; develop alternative looks (perhaps with the curiously popular rounded corners)."
[[BR]([BR]]
[[BR]]"Use)]
[progress after about 1,5h of work:'''[[BR]([BR]]'''Project)]

File is initially divide into parts. Project related website part look nice, I didn't notice any major visual bugs or glitches, but forum part it's still buggy and need improvements... I tried to fix or correct them, but I use Firebug plugin and it's hard to do it. However I think that CSS should be tested on real server.
[[BR]]
[[BR]]'''If some want to help in this project I attach actually version of my white.css file.''' 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/716

**Comment by romw** [comment]
**Commented by davea on 28 Jan 38603348 00:26 UTC**
(In [15771]) - web: improve white.css, and make corresponding PHP changes
    (mostly from Simek)
    fixes #716
- validator: tweak the way host error rate is computed,
    e.g. on error bump rate by .1 instead of .05

**Comment by romw** [comment]
**Commented by Simek on 30 Oct 38603393 23:33 UTC**
Awesome work davea, but you must add:
[[BR]]
-webkit-border-radius
[[BR]]
It add rounded corners to table when browse BOINC project site by Safaii.

**Comment by romw** [comment]
**Commented by davea on 30 Jan 38603414 19:33 UTC**
Done; I deployed this on BOINC Alpha, S@h and S@h beta.

**Comment by romw** [comment]
**Commented by Simek on 17 Nov 38603430 01:46 UTC**
I add little cleanup patch... Sorry for another reopen...

**Comment by romw** [comment]
**Commented by Ageless on 9 Jan 38603455 12:26 UTC**
Aha, is this why the Reply button in Seti Q&A now points to the Report post option? Both the red-x and the Reply button (that's right next to it) go off to Report post. And as said, in the Q&A section only, apparently it works on the main forums.

**Comment by romw** [comment]
**Commented by Nicolas on 7 Jun 38603457 03:33 UTC**
Replying to [Simek](ticket:716):
> Idea was taken from: http://boinc.berkeley.edu/trac/wiki/DevProjects
> [[[BR]([BR]]
>)]"Use CSS instead of HTML for formatting where possible; clean up white.css; improve the look; develop alternative looks (perhaps with the curiously popular rounded corners)."
> [[[BR]([BR]]
>)]'''Project progress after about 1,5h of work:'''
Most items in DevProjects were moved to tickets; see #595.

**Comment by romw** [comment]
**Commented by Nicolas on 15 Mar 38603461 11:06 UTC**
Replying to [Simek](comment:4):
> I add little cleanup patch... Sorry for another reopen...
Would be easier if you got commit access into a branch (letting David review and merge into trunk).

**Comment by romw** [comment]
**Commented by Simek on 11 May 38603542 16:00 UTC**
Nicolas - Good idea. It will be much easier...

Now I'm working on another patch to forum style...

**Comment by romw** [comment]
**Commented by Simek on 16 Oct 38603627 08:53 UTC**
Another patches included:[[BR]]
[[BR]]
user/white.css[[BR]]
inc/forum.inc[[BR]]
[[BR]]
Now forum look better... Now I'm going to sleep... It's about 1 a.m... Good night!

**Comment by romw** [comment]
**Commented by Simek on 7 Nov 38605681 20:26 UTC**
I up new version of white.css with FORUM fixes - some minor changes only in compare with previous version.

**Comment by romw** [comment]
**Commented by Simek on 9 Mar 38605708 21:46 UTC**
I add web screenshot of forum after latest patches...

**Comment by romw** [comment]
**Commented by Simek on 4 Jul 38611125 04:00 UTC**
'''Changelog:'''
[+ forum_index.php [based on rev.15801]([BR]]
[[BR]]
'''''white.css)'''''["white.css.and.forum_index.php.patch"''
[[BR]([BR]]
file:)]
 * new class "numbers" added for threads, posts and views counters cells
 * refreshed forum quote style
 * two unused classes deleted: cellwrap and sigdelim (I preform search in BOINC main catalog and subcatlogs)
 * Declimal RGB color code and web named colors converted to ex HTML color code
 * font size in post header and footer decreased
 * few classes moved to property parts of file
 * some duplicated style deleted 
 * new more pastel colors for sever status on the Server Status page

**Comment by romw** [comment]
**Commented by Simek on 6 Feb 38613448 08:26 UTC**
'''''/html/inc/prefs.inc [on rev.15802](based)'''''["prefs.inc.patch" [[BR]([BR]]
file:)]
[[BR]]
Another small patch included to fix style in account preferences on site.

**Comment by ChristianBeer** [comment]
Superseded by bootstrap implementation.
