### ISSUE TITLE
BOINC prevents MacOS X from resuming from standby

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#696]
**Reported by Koraktor on 9 Apr 38615302 13:46 UTC**
On my !MacBook Pro MacOS X repeatedly hangs when opening the lid (i.e. resuming from standby) when BOINC is running. It does not happen all the time, but I'm sure that BOINC is at least one reason for that problem.
If BOINC is not running, the problem doesn't occur.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/719

**Comment by romw** [comment]
**Commented by Nicolas on 13 Aug 38617218 03:06 UTC**
My dad has the same problem sometimes on his PowerBook, running OS X Tiger, that doesn't and has never had BOINC installed.

**Comment by romw** [comment]
**Commented by Koraktor on 24 Jul 38721318 16:00 UTC**
A small update after disabling BOINC for several weeks: Zero lockups.
I'm sure this is a BOINC problem.

**Comment by romw** [comment]
**Commented by charlief on 17 Nov 38722257 08:53 UTC**
Have you installed all the software and firmware updates for the MacBook Pro?  In particular, [Firmware Update 1.2](http://www.apple.com/support/downloads/macbookproefifirmwareupdate12.html) says:
  This EFI Firmware Update fixes several Boot Camp, start up, and wake-from-sleep issues on MacBook Pro computers.
and [About MacBook Pro Software Update 1.2](http://support.apple.com/kb/HT2058) says:
  This update improves graphics stability and is recommended for all MacBook Pro (Mid 2007, 2.4/2.2GHz) computers running Mac OS 10.4 Tiger.

There may be others as well.

**Comment by romw** [comment]
**Commented by Koraktor on 30 Jul 38764046 15:06 UTC**
Replying to [charlief](comment:4):
> Have you installed all the software and firmware updates for the MacBook Pro?  In particular, [Firmware Update 1.2](http://www.apple.com/support/downloads/macbookproefifirmwareupdate12.html) says:
>   This EFI Firmware Update fixes several Boot Camp, start up, and wake-from-sleep issues on MacBook Pro computers.
> and [About MacBook Pro Software Update 1.2](http://support.apple.com/kb/HT2058) says:
>   This update improves graphics stability and is recommended for all MacBook Pro (Mid 2007, 2.4/2.2GHz) computers running Mac OS 10.4 Tiger.
> 
> There may be others as well.

I should have mentioned that I'm running MacOS X 10.5.5 on a new MacBook Pro (May 2008).

**Comment by romw** [comment]
**Commented by charlief on 14 Aug 38765033 21:20 UTC**
Replying to [Koraktor](comment:5):
> I should have mentioned that I'm running MacOS X 10.5.5 on a new MacBook Pro (May 2008).

My experience is that new Macs often don't have the latest software and firmware updates.  I recommend you confirm the firmware version.  You should be able to do this using the System Profiler.

**Comment by romw** [comment]
**Commented by Koraktor on 15 Sep 38787082 18:40 UTC**
Replying to [charlief](comment:6):
> My experience is that new Macs often don't have the latest software and firmware updates.  I recommend you confirm the firmware version.  You should be able to do this using the System Profiler.
My firmware version is MBP41.00C1.B03. The last update is from April and only for MBP21 and MBP31 series.

**Comment by ChristianBeer** [comment]
The last update on this report was 8 years ago. If this still happens with current Hardware please open a new Issue.
