### ISSUE TITLE
Add summary of install choices to installer

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#707]
**Reported by Ageless on 7 Oct 38677062 10:40 UTC**
Can we please have a summary of the choices we made to install BOINC with on the screen where it says "Click Install to begin the installation." 
- Where it shows whether we chose to use the screen saver;[The installation paths;[[br]([br]]
  -)]
- Whether it is a service install or not;[When it says Protected Application Execution mode, tell that this means BOINC will be installed as a Windows service, with the graphics only working when the project has updated its applications. [[br]([br]]
  --)]
- Whether BOINC Manager can be controlled by all users or not. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/730

**Comment by romw** [comment]
**Commented by Didactylos on 2 Apr 38679348 09:20 UTC**
Due to an installer bug, BOINC can be controlled by any user, regardless of the setting. This makes all the added security utterly futile.

**Comment by romw** [comment]
**Commented by romw on 14 Dec 39159102 22:40 UTC**
Punting setup bugs to 6.10.

**Comment by romw** [comment]
**Commented by romw on 2 Oct 40859073 14:13 UTC**
Setup bugs are being punted to a future release.  This work item should be completed with the new open source installer.

**Comment by ChristianBeer** [comment]
Last time I did a Windows Install I saw such a page so I'm closing this old report.
