### ISSUE TITLE
Increase in CPU consumption of BOINC core client when network (or project) is unavailable

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#711]
**Reported by Raistmer on 26 May 38695851 20:26 UTC**
When whole network or single project down and many results waiting to be sent BOINC make retry to send for each result separately that leads to almost constant atempts to send one of results. This leads to increase in CPU consumption by core client.
BOINC could check once per some period defined by settings if network/particular project site available and only after success check retry all results sending for this project/all projects. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/734

**Comment by romw** [comment]
**Commented by Raistmer on 4 Feb 38695861 12:26 UTC**
[Example ](http://boinc.berkeley.edu/dev/forum_thread.php?id=3099&nowrap=true#20070)

**Comment by ChristianBeer** [comment]
This was fixed in 6.x or 7.x by multiple backoff counters.
