### ISSUE TITLE
[PATCH] BOINC Mgr does not display zero free space in disk tab

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#714]
**Reported by Pepo on 24 Jun 38731388 15:06 UTC**
The Changeset [15194] implemented displaying of the division of free space into available/unavailable to BOINC (because people asking for help were unable to figure out, why does BOINC not get free disk space assigned or how much space it has available).

Unfortunately if BOINC gets no available space, this information is skipped and not displayed at all. In such case BOINC should inform about this fact too.

(The attached patch is untested.)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/737

**Comment by romw** [comment]
**Commented by ChristianB on 16 Nov 40704665 03:33 UTC**
This bug is still in trunk and fixable.

**Comment by Ageless93** [comment]
Can this issue's pull request be looked at, please?
