### ISSUE TITLE
Limits apps within a project

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#724]
**Reported by MarkJ on 22 Sep 38764255 12:26 UTC**
Can we get a preference to limit application resources within a project please. At present we can setup project shares, but not limit apps within a project.

You would need to know what apps each project has and what the share is within that project. The current resource shares are stored in the account_xxx.xml. Under the project shares include values to limit applications (which should total to the project share). Another possible place to put it could be in app_info.xml.

Example: I have S@H set to 75% project share on a quad core but want to limit it to 1 Astropulse (AP) and 2 Seti Enhanced (MB) at a time. That is unless it doesn't have sufficent work to honour the preference.

'''account_setiathome.berkeley.edu.xml''' (some dummy xml to explain what I mean)
- <project_preferences>
  <resource_share>75</resource_share>
  <application_share>
  <app_name>astropulse</app_name>
  <app_percent>25</app_percent>
  <app_name>setiathome_enhanced</app_name>
  <app_percent>50</app_percent>
  </application_share>
  ...

Migrated-From: http://boinc.berkeley.edu/trac/ticket/747

**Comment by romw** [comment]
**Commented by MarkJ on 20 Sep 38991063 12:00 UTC**
Update: Einstein@home are also planning on releasing a 2nd app (PALFA search) for their project in 2009.

**Comment by ChristianBeer** [comment]
This can be done using an app_config.xml file
