### ISSUE TITLE
History of team's users

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#734]
**Reported by Pepo on 20 Aug 38794575 21:20 UTC**
During and after the recent team hijack affair, a few ideas were said about how this could be prevented (among others, [here](http://boinc.berkeley.edu/dev/forum_thread.php?id=2860&nowrap=true#18440), [here](http://boinc.berkeley.edu/dev/forum_thread.php?id=2860&nowrap=true#18451), [here](http://boinc.berkeley.edu/dev/forum_thread.php?id=2860&nowrap=true#18455), [here](http://boinc.berkeley.edu/dev/forum_thread.php?id=2860&nowrap=true#18461), [here](http://boinc.berkeley.edu/dev/forum_thread.php?id=2860&nowrap=true#18625) and elsewhere). One of them was to create some publicly visible place containing the history of team's users and founders and their names.

I've noticed that such ''Team history'' page actually already exists, although not publicly visible, just for team admins (and possibly project admins, in case of problems or accident). These tables could be made publicly visible, because the team user data are already exported to statistics sites and nearly the same lists can be built over time. (Nearly.)

This page stores the users' join/leave history and currently looks like:

== Team history for !MyOwnTeam ==
||'''When'''||'''User'''||'''Action'''||'''Total credit at time of action'''||
||18 Aug 2008 17:32:56 UTC||[[http://boinc.berkeley.edu/dev/show_user.php?userid=1452 Lduhl@berkeley.edu]([Image%28http://boinc.berkeley.edu/dev/img/head_20.png%29]]) (ID 1452)||joined||0||
||10 Oct 2008 15:11:01 UTC||[[http://boinc.berkeley.edu/dev/show_user.php?userid=1452 Lduhl@berkeley.edu]([Image%28http://boinc.berkeley.edu/dev/img/head_20.png%29]]) (ID 1452)||quit||0||
||14 Nov 2008 22:37:04 UTC||[Pepo](http://boinc.berkeley.edu/dev/show_user.php?userid=1063) (ID 1063)||quit||13 752.23||

---

My proposal is to modify Team history page as following: Add one additional column (also into the database) named '''Initiator''', which would hold the ID of person, responsible for someone quitting a team: if the user went on his own, there would be his ID, if the team founder kicked him off as ''inactive member'', the founder's ID would go there.

(There were social features' proposals for letting a newcomer ''credit'' someone for having him join a team - such user would have the opportunity to name the inviting user and his name would be logged in the table as ''Initiator'' as well.)

One of the most vocal requests were for storing the ID of users, who requested team ownership transfers and especially those, who took it over (or were assigned a founder).

== Team history for !MyOwnTeam ==
||'''When'''||'''User'''||'''Action'''||'''Initiator'''||'''Total credit at time of action'''||
||18 Aug 2008 17:32:56 UTC||[[http://boinc.berkeley.edu/dev/show_user.php?userid=1452 Lduhl@berkeley.edu]([Image%28http://boinc.berkeley.edu/dev/img/head_20.png%29]]) (ID 1452)||joined||||0||
||10 Oct 2008 15:11:01 UTC||[[http://boinc.berkeley.edu/dev/show_user.php?userid=1452 Lduhl@berkeley.edu]([Image%28http://boinc.berkeley.edu/dev/img/head_20.png%29]]) (ID 1452)||quit||[Pepo](http://boinc.berkeley.edu/dev/show_user.php?userid=1063) (ID 1063)||0||
||12 Oct 2008 13:15:22 UTC||[[http://boinc.berkeley.edu/dev/show_user.php?userid=8 Ageless]([Image%28http://boinc.berkeley.edu/dev/img/head_20.png%29]]) (ID 8)||joined||[Pepo](http://boinc.berkeley.edu/dev/show_user.php?userid=1063) (ID 1063)||8 433.56||
||13 Oct 2008 23:10:54 UTC||[[http://boinc.berkeley.edu/dev/show_user.php?userid=8 Ageless]([Image%28http://boinc.berkeley.edu/dev/img/head_20.png%29]]) (ID 8)||takeover requested||||8 653.96||
||12 Nov 2008 23:10:54 UTC||[[http://boinc.berkeley.edu/dev/show_user.php?userid=8 Ageless]([Image%28http://boinc.berkeley.edu/dev/img/head_20.png%29]]) (ID 8)||tookover||||8 986.32||
||14 Nov 2008 22:37:04 UTC||[Pepo](http://boinc.berkeley.edu/dev/show_user.php?userid=1063) (ID 1063)||quit||[Pepo](http://boinc.berkeley.edu/dev/show_user.php?userid=1063) (ID 1063)||13 752.23||

Last but not least, it would be nice to additionally store then-valid users' names as text strings, not just their IDs (this way an additional event of team being renamed could be logged here too), but this would possibly inflate the tables in database. Although not that much...

,,Displayed user names and events are (mostly) imaginary and do not necessarily mirror real users or events.,,

Migrated-From: http://boinc.berkeley.edu/trac/ticket/757

**Comment by romw** [comment]
**Commented by davea on 22 Oct 38794779 15:33 UTC**
This is a good idea, to use the team_delta table to store
all events related to the team, and to make it publicly visible.
I don't have time to do it right now,
but it should be fairly easy; can someone send me a patch?

**Comment by Ageless93** [comment]
Is this still an issue that people want added?

**Comment by AenBleidd** [comment]
Closing this as 'wontfix' since there was no additional requests last 5 years.
Could be reopened if this is smth that still desired
