### ISSUE TITLE
cannot install BOINC - ERROR 1714

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#743]
**Reported by Dr  C E T I  on 5 Aug 38842032 12:00 UTC**
cannot remove 3 lines in Registry

error 1714 has come up again & again - have removed everything from the Registry

safe the three lines which cannot be removed

> have uninstalled many versions and then re-installed - same ERROR every time

Microsoft / Hp / CA have all attempted a fix to the problem - nix

i have been told to speak to you @ Berkeley

Eric Korpela has the info referencing this situation -

> System is using Windows XP Professional (Media Center) w/ HP Pavillion dv9060us

< would appreciate ANY help - this 'problem' has been around since 2005 - many users just gave up and left the Project . . .

Thank You for your Consideration,

richard w lubrich jr

Migrated-From: http://boinc.berkeley.edu/trac/ticket/766

**Comment by romw** [comment]
**Commented by Nicolas on 4 Nov 38842070 09:46 UTC**
It's a known issue, but not a BOINC bug as far as I know. See http://boincfaq.mundayweb.com/index.php?language=1&view=119

**Comment by romw** [comment]
**Commented by Dr. C.E.T.I. on 15 Aug 38842115 13:46 UTC**

seen that (been to Jords pages) - these are the files that cannot be removed in the Registry:

HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\KmxFile\CreatedFilesTimestamp
C:\Program Files\BOINC\client_state.xml              REG_BINARY        86 cf 5a 60 c9 f1 c8 01 30 45 9f 87 00 00 00 00
C:\Program Files\BOINC\client_state_next.xml         REG_BINARY        78 a8 53 60 c9 f1 c8 01 30 45 9f 87 00 00 00 00
C:\Program Files\BOINC\client_state_prev.xml         REG_BINARY        78 a8 53 60 c9 f1 c8 01 30 45 9f 87 00 00 00 00

**Comment by romw** [comment]
**Commented by Ageless on 9 Feb 38850371 04:53 UTC**
Replying to [Dr. C.E.T.I.](comment:2):[[br]]
They can't be removed as they point to your firewall/AV/AS package's malware vault. Why you allowed any of BOINC's parts to be registered as malware is another question, but you should try to either fix it in the AV/AS/firewall package, or uninstall that package. Kmxfile is part of the CA Internet Security Suite.

**Comment by romw** [comment]
**Commented by romw on 23 Jan 39156073 10:13 UTC**
Please launch the installer using this commandline:
boinc_6.4.6_windows_intelx86.exe /v"/l*vx c:\boincsetup.log"

Email me the log file.

**Comment by romw** [comment]
**Commented by romw on 24 Apr 39159571 18:13 UTC**
I don't think you want your phone number posted on the Internet.

Go ahead and run the installer with those parameters.  The log file will tell me whihc component of the installation process is failing with error code 1714.  From there I might be able to tell you what is happening.

For the record error code 1714 is a Windows error code.  It isn't from anything I've written.  All I can go by is what is in the log file.

**Comment by romw** [comment]
**Commented by romw on 29 Jul 39159574 21:20 UTC**
Nevermind, I looked at Jord's FAQ...  It has a very specific meaning...

Did you try the Windows Installer Cleanup Utility?

**Comment by romw** [comment]
**Commented by Dr. C.E.T.I. on 27 Aug 39159609 09:20 UTC**
yes - have done just about everytning you can imagine

had CA, Microsoft & HP Escalation TeAm's [they linked directly to my system](and) attempt to figure this out - ALL they each came up with - was to see Berkeley regarding

i am presently about to make dinner - have to run - so, if anybody that is able to call - call - it's easier to answer ALL the questions this way

Thanks for the remarks / help - 'ello Ageless - hope u r well Sir

With Regards, richard

**Comment by romw** [comment]
**Commented by romw on 11 Aug 40859065 01:20 UTC**
Setup bugs are being punted to a future release.  This work item should be completed with the new open source installer.

**Comment by ChristianBeer** [comment]
This error crops up from time to time and is a Windows bug and BOINC can not fix it.
