### ISSUE TITLE
BOINC Manager lockup

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#750]
**Reported by Der Meister on 8 Dec 38874186 10:40 UTC**
When attaching to a project there is the dialog saying "Communicating with project Please wait...". When cancelling this operation before it completes or times out all menus, buttons, etc. in the manager are still set to disabled. In this state it can't be used anymore, even shutting down the manager isn't possible anymore, it has to be killed.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/773

**Comment by ChristianBeer** [comment]
Needs to be checked if this is still the case.

**Comment by Ageless93** [comment]
I've tested it earlier with my slow startup issue, I could exit the manager without problems (BOINC 7.8.1).

**Comment by Ageless93** [comment]
Tested again with 7.8.3, still cannot reproduce, so assume this is fixed.
