### ISSUE TITLE
Task window in Simple View GUI of manager has scale / placment / content issues

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#756]
**Reported by verduin on 21 Jan 38899053 19:06 UTC**
[[BR]]Placement and scale are perhaps the cause of missing border (see ticket #119) in the "Simple View" and also cause overwriting a portion of the task selection scroll above the window.  In addition placement of slide show images inside the window leaves void background below the images.

For the purposes of task selection, consider truncating task text to limit the length of the selector button above the window.  I submit this in the belief that a series of shorter buttons is more useful than a single long button in the display.  I believe the button text is essentially redundant with the text following "Application:" inside the window?

Further, there is no text inside the window to give specific identity to the task displayed.  In the "Advanced View" this is the "Name" field.  I find the tasks selected for simple view are limited to active tasks, but exclude finished and waiting to start tasks.  The selection is good but I admit confusion when finding more tasks in the Advanced View than were displayable in the Simple View.  You might consider this a defect in user training, but I request consideration for a window title?

This version is current today from Fedora 10 Preview repositories.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/779

**Comment by romw** [comment]
**Commented by Nicolas on 25 Feb 38899080 15:06 UTC**
If nobody disagrees, I'll close this as duplicate of #119, and update that one to mention everything that is broken on the simple GUI on Linux.

**Comment by romw** [comment]
**Commented by verduin on 1 Nov 38936919 08:26 UTC**
Replying to [Nicolas](comment:1):
> If nobody disagrees, I'll close this as duplicate of #119, and update that one to mention everything that is broken on the simple GUI on Linux.

As originator I agree combination with #119 is a reasonable approach.  One correction to my original post: the version was not 6.2, it *WAS* 5.10.28.  I see today that 6.2.15...fc10 corrects some of the issues, others remain for me to re-test...  I'm sorry for my organizational error.

**Comment by ChristianBeer** [comment]
Closing because Simple GUI was overhauled since this was reported.
