### ISSUE TITLE
Exit Manager for startup changes to stick (reopened)

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#767]
**Reported by Contact on 16 Apr 38937503 04:53 UTC**
I must exit the Manager before log off or reboot for Manager startup changes to stick.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/790

**Comment by romw** [comment]
**Commented by Ageless on 4 Apr 38937528 13:46 UTC**
Which Windows version? 
As it may not work on Vista with UAC on.

**Comment by romw** [comment]
**Commented by Contact on 16 Aug 38939942 06:40 UTC**
Replying to [Ageless](comment:1):
> Which Windows version? 
> As it may not work on Vista with UAC on. 
I've seen this since 6.4.0 on Win98 & XP.

**Comment by romw** [comment]
**Commented by romw on 2 Feb 39178587 03:06 UTC**
(In [17516])     - MGR: Saving and Restoring window diminisions is not a Mac only
        operation when starting up or shutting down the client. Increase
        the frequency of the auto-save state timer from 5 minutes to
        5 seconds.  Fixes #69, Fixes #735, Fixes #790, 
    - MGR: Lengthen the connected to client status field. Fixes #632
    - MGR: Properly update the connected to client status field
        even after a change to the simple view. Fixes #688
        
    clientgui/
        AdvancedFrame.cpp
        sg_BoincSimpleGUI.cpp, .h

**Comment by romw** [comment]
**Commented by romw on 15 Jun 39180816 09:20 UTC**
(In [17535])     - MGR: Saving and Restoring window diminisions is not a Mac only
        operation when starting up or shutting down the client. Increase
        the frequency of the auto-save state timer from 5 minutes to
        5 seconds.  Fixes #69, Fixes #735, Fixes #790, 
    - MGR: Lengthen the connected to client status field. Fixes #632
    - MGR: Properly update the connected to client status field
        even after a change to the simple view. Fixes #688
        
    clientgui/
        AdvancedFrame.cpp
        sg_BoincSimpleGUI.cpp, .h

**Comment by romw** [comment]
**Commented by Contact on 17 Dec 39270874 20:00 UTC**
I've reopened this ticket because I still see this problem with 6.6.20

**Comment by ChristianBeer** [comment]
If this is still a problem with current 7.6.33 please open a new issue.
