### ISSUE TITLE
wrapper does not detect first checkpoint_file of legacy application

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#768]
**Reported by yoyo on 29 May 38937584 20:00 UTC**
The wrapper does not detect the first creation of the checkpoint file of the legacy application, which is specified in job.xml. I removed all occurrences of variable stat_first to solve it.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/791

**Comment by Ageless93** [comment]
We have had quite a bit of wrappers built since this report. Is this still an issue or can this be closed?

**Comment by Ageless93** [comment]
Checked with yoyo, he hasn't had the problem off late and says this can be closed.
