### ISSUE TITLE
OS 10.5.5, Safari 3.1.2, BOINC 6.2.18.  BOINC computing and Safari open.  Closing laptop lid hangs machine

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#777]
**Reported by 39mars on 15 Dec 38964532 11:06 UTC**
Using OS 10.5.5, Safari 3.1.2, BOINC 6.2.18.  With Safari running, and BOINC computing, closing and then re-opening the lid of my laptop causes the machine to hang.  Screen is black and completely unresponsive.  This occurs every time I have tried it.  Shutting down by pushing button and then rebooting is the only fix I have found.  It looks as though no BOINC computation data is lost.  I have searched the OS, Safari and BOINC logs for some hints, and I do not find anything.

The scenario described above is the only one I have been able to find that hangs.  Permutations that _do_not_ hang the machine are as follows.  These are all with both BOINC and Safari running.  I have found no other applications which cause the issue:
1) Snooze BOINC.  Close and open lid.  Computer wakes.
2) BOINC running or snoozed.  Select sleep from the apple menu.  Close and open lid.  Computer wakes

Finally, of course, if I quit Safari with BOINC running and close/open, there is no hang.
One additional test was that I quit Safari and opened Firefox.  Closed/opened with no hang.

So, it seems to be a Safari/BOINC interaction problem.

This is not a huge issue as long as you remember to either quit Safari or snooze BOINC before closing the laptop, but failing that, the reboot and potentially lost data from other apps is something of an  issue.  Of course if you need logs, etc that you need to look over, please let me know.  Thank you for your time.

-Scott Doudrick

Migrated-From: http://boinc.berkeley.edu/trac/ticket/800

**Comment by ChristianBeer** [comment]
Closing because of age of used versions. If still still is a problem please open  a new issue.
