### ISSUE TITLE
Use special modified Tango Icons on BOINC Message Boards

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#784]
**Reported by Simek on 14 Nov 38980285 17:20 UTC**
I prepare few modified Tango Icon special for BOINC Message Board. I prepared also visualisation which is attached to this ticket. 

Single icons are attached too. I hoped there are nice and it's easy to identify what they mean.

No patches for the present. I prepare some if you will like my idea.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/807

**Comment by romw** [comment]
**Commented by davea on 8 Oct 38981483 20:53 UTC**
There are three independent attributes expressed in the current icons:

- read or unread
- sticky or not
- locked or not

**Comment by romw** [comment]
**Commented by Simek on 28 Aug 38984258 19:33 UTC**
Replying to [davea](comment:1):

Missing lock variations added

**Comment by romw** [comment]
**Commented by Eric Myers on 20 Jul 38989699 04:26 UTC**
The differences between these are so subtle that I'm not sure I get all the meanings they are intended to convey.

Yellow for "new posts" is already in use, so I suggest keeping that clue.

A padlock might be used for "locked" threads.

**Comment by ChristianBeer** [comment]
A lot has happened with icons and web technology since this report. I personally don't think we should use modified icons but if at all switch to a well known icon set. Please open a new issue to start a discussion or propose a well known iconset that works with current bootstrap themes.
