### ISSUE TITLE
BOINC Project Website - validation fixes and near-future plans

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#790]
**Reported by Simek on 17 Mar 38994092 18:13 UTC**
== Description ==

Ok... I reviewed many pages, but many more left to review. [prepared patch for those files. My changes should make more pages HTML 4.01 Valid.

'''I want to notice that my patch needs unfortunately testing, because I don't have my own BOINC test website.''' 

---

== Unsoved problem: ==
'''''edit_forum_preferences_form.php'''''[[BR]([BR]]

I)]

Originally <form> started in <table> but it's not valid. After move <form> outside <table> we have now whole <table> inside, but originally <form> close tag is inside <table> so it's invalid again. I move <form> close tag outside the <table>, but reset button need new special form. And here I have problem. Now <form>s are nested:

```
<form method=\"post\" action=\"edit_forum_preferences_action.php\" enctype=\"multipart/form-data\">
...
<form method=\"post\" action=\"edit_forum_preferences_action.php\">
...
</form>
...
</form> 
```

But they shouldn't. How to make this page valid? For now I don't have any idea, hope you will have some.

---

== Future plans ==
- complete validation check process
- redesign Certification code ( now those pages are totally messed up -  I want to create special page_head funcion and move all styles to CSS )
- split ''white.css'' into ''main.css'' (which include all attributes without colors and images ) and ''color.css'' (white, black... etc. - so we only need to edit color.css to create another colorset)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/813

**Comment by ChristianBeer** [comment]
Patch not applicable anymore.
