### ISSUE TITLE
BOINC runs for all users when installed for single-user

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#795]
**Reported by MarkJ on 15 Nov 39004822 17:46 UTC**
BOINC 6.4.5 and 6.5.0 under WinXP installed as single-user mode.

As per trak #751, startup client at logon is handled via registry entries. Previous versions (5.10.45) used to use the Startup folder. Under 6.4.5 and 6.5.0 the registry entries are for BoincMgr and BoincTray, whereas earlier (6.2.19) only included BoincTray.

This means logging on as different users they always have BOINC startup, regardless of if they should or should not run BOINC.

In my case BOINC was installed for user Seti but starts up for all users with access to its directories (ie those with admin access).

Migrated-From: http://boinc.berkeley.edu/trac/ticket/818

**Comment by romw** [comment]
**Commented by romw on 27 Mar 39159114 07:33 UTC**
Punting setup bugs to 6.10.

**Comment by romw** [comment]
**Commented by Pepo on 12 Mar 41181910 13:20 UTC**
As an additional ''goodie'', if both "HKLM\...\Run" and "Start Menu\Programs\Startup" entries exist for Manager, the 6.12.16 Manager is being started upon user's login with all empty Advanced View's tab panes, except that it is correctly connected to the client and Event log is live with all messages.

With the sequence View -> Open Simple View -> Open Advanced View it is possible to have one more Advanced View opened, with all tab panes correctly populated.

**Comment by ChristianBeer** [comment]
The Installer was revamped with 7.x and this is most likely fixed now, at least this was not mentioned recently.
