### ISSUE TITLE
Display history of data transfered

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#827]
**Reported by knreed on 5 Jul 39153071 03:06 UTC**
We have had requests to be able to see the history of how much data has been uploaded and downloaded from a given client.  It would be great if this information could be stored in the statitics_project_url.xml file and then made available for viewing on the statistics page.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/850

**Comment by romw** [comment]
**Commented by romw on 15 Sep 39155859 04:26 UTC**
This would need to be recorded by the CC

**Comment by ChristianBeer** [comment]
This is now available in the Client. There is a file `daily_xfer_history.xml` as well as an RPC `--get_daily_xfer_history` which does not distinguish by project.

**Comment by Ageless93** [comment]
daily_xfer_history.xml is used by the client to determine if the data transfer limits have been met or not. These limits are for the whole of BOINC and not per project.

**Comment by Ageless93** [comment]
Closing after conversation with its owner. The daily_xfer_history.xml file is doing what was requested.
