### ISSUE TITLE
Client doesn't ask for new work while having suspended tasks in a queue

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#839]
**Reported by Tamagoch on 30 Jun 39205656 06:40 UTC**
When putting some tasks or projects in a pause client seems to count them as working ones since no other jobs are requested. When trying to update active project manually scheduler requests 0 seconds of work which may leave system idle.

Sometimes increasing cache may help but I cannot see what else could make it request more tasks when there's nothing to process.

Found both in 32 and 64 bit Windows versions.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/862

**Comment by romw** [comment]
**Commented by Nicolas on 25 Jan 39205673 12:26 UTC**
If a project has any suspended task, there will be no work fetched from that project. This behavior is intentional.

**Comment by romw** [comment]
**Commented by sandro.tosi on 24 May 40623477 08:26 UTC**
Hello,
I can confirm this is happening with client version 6.10.58 on Debian.

While I can understand that if one project has jobs suspended than other jobs are not requested for *that* project only (even if I think it would be better to fetch additional WUs), I can see that WUs for *other* projects are not fetched as well.

It's like even if there are jobs suspended, they are counted as "valid" WUs, while there is actually nothing running on the machine (if all are suspended) and none are fetched: the machine is idle (indefinitely?).

I think it would be better to have the set of "running + waiting to run" to always match the additional work buffer or a minimum set of hours, and if there's nothing eligible for execution, fetch new WUs no matter what.

Regards,
Sandro

**Comment by ChristianBeer** [comment]
This should be fixed in current 7.6.33 and is intentional. If a project has suspended tasks no work for this project is requested. Other projects should request work as normal. If this is not working please open a new issue.
