### ISSUE TITLE
Many visual and style changes. Redesigned forum style and changes for other parts of website.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#849]
**Reported by Simek on 15 Jan 39290691 10:40 UTC**
A lot of changes in this patch, but i don't give 100% that this will be working, because I don't have any access to running project website, so I can't test it. I can only image what final effect will be.

List of changes:
- deleted forum table contains search and pm - now this two modules have own styled div
- trivial style fixes for components inside those boxes
- new function for first heading row in table - with rounded corners aka "row1_top" - test into "home.php"
- "white.css" forum post header Mozilla browsers fix and some other minor fixes

I have a lot of ideas, energy to work and correct any mistake and enough free time so expect in next few days more ticket like this. :)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/872

**Comment by romw** [comment]
**Commented by davea on 13 Feb 39291412 12:00 UTC**
The formatting is messed up.
Simek, do you have a project on which you can test?

**Comment by romw** [comment]
**Commented by Simek on 13 Aug 39291653 12:26 UTC**
Replying to [davea](comment:1):
> The formatting is messed up.
> Simek, do you have a project on which you can test?

Unfortunate David I don't have any one.

New, updated version of patch will be attached in a while. Thanks to Nicols for adding test patch to his project, so I can see what need to be corrected.

**Comment by romw** [comment]
**Commented by davea on 12 Oct 39291870 15:33 UTC**
BTW, the search and sort-order controls appeared in a new
rounded-corner rectangle;
I'd prefer that they not have this - just have them on the background.

**Comment by romw** [comment]
**Commented by Simek on 24 Jul 39292317 12:26 UTC**
Replying to [davea](comment:3):
> BTW, the search and sort-order controls appeared in a new
> rounded-corner rectangle;
> I'd prefer that they not have this - just have them on the background.

Let me finish working with forum style please and then tell me what you thing about all changes and decide to bring it in to trunk or not. =D

**Comment by romw** [comment]
**Commented by Nicolas on 17 Oct 39292846 03:06 UTC**
Don't apply this one yet; Simek and me are testing it and improving it.

**Comment by romw** [comment]
**Commented by Simek on 12 Jun 39294575 10:40 UTC**
Probably the latest version of patch. I would like to thanks Nicols for testing, bug reporting and support.

Changes are applied into Silly Pi project:
http://stuff.povaddict.com.ar:8080/boinctest/

Most changes in Message Boards styling.

**Comment by romw** [comment]
**Commented by Simek on 28 May 39302973 02:40 UTC**
Many changes since trunk - all of them are visible on Nicols Silly Pi Project - http://stuff.povaddict.com.ar:8080/boinctest/

Hoped someone still read this ticket.

**Comment by ChristianBeer** [comment]
Closing because changes got superseded by bootstrap introduction.
