### ISSUE TITLE
configure --enable-bitness=32 doesn't work

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#853]
**Reported by Nicolas on 4 Apr 39293706 04:00 UTC**
I tried to compile BOINC API for 32-bit Linux, being on a 64-bit Linux machine. Using `configure --enable-bitness=32` doesn't work; it compiles 64-bit code anyway (I didn't let `make` run to completion; I aborted it as soon as I saw a few files being compiled without any 32-bit flag).

I found the problem is the `SAH_OPTION_BITNESS` macro (defined in `m4/sah_select_bitness.m4`) adds `-m32` to `CFLAGS`, but not to `CXXFLAGS`, so C code would be compiled as 32-bit but C++ code wouldn't.

Another minor bug: if the macro detects `-m32` works, it prints "Selecting 32 bit model... -m32" but then prints "failed" on the next line anyway. The printing of "failed" is done always, instead of in the 'else' clause of checking if `-m32` works.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/876

**Comment by romw** [comment]
**Commented by Nicolas on 3 Sep 40500930 12:26 UTC**
A belated happy birthday for this bug report!

**Comment by ChristianBeer** [comment]
This is still an issue in https://github.com/BOINC/boinc/blob/master/m4/sah_select_bitness.m4

**Comment by truboxl** [comment]
Does this need a separate test for C++ compiler (unlikely to fail)? Or just include `$CXXFLAGS` enough?

The error part may need more digging into it. The test command looks fine to me but giving out false result.
