### ISSUE TITLE
Long term debt not counting

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#857]
**Reported by DoStuffZ on 6 Oct 39309560 21:46 UTC**
I'm experiencing an issue of long term debt not being counted for SETI project.

I'm currently running SETI + Milkyway + Einstein. Einstein is currently out of reach so thats on hold for the moment being. Milkyway is counting down just fine, as time is spent, SETI sits at 0.0 debt. I can't see what being counted up to balance out Milkyway. I previously saw 1 MW WU running + 1 AP + CUDA. Right now I got 1 AP, 1 SETI 6.03 + CUDA running. MilkyWay is balancing up, while SETI still shows 0.00s. Short term debt is not affected by this.
It's been an issue in both 6.6.20 and 6.6.23.

System:
Intel Duo Core E6850 @ 3ghz, 2gb RAM
Nvidia GTS 8800 (CUDA)
OS: Win XP
Using: BoincView 1.4.2

Migrated-From: http://boinc.berkeley.edu/trac/ticket/880

**Comment by ChristianBeer** [comment]
Debt was removed from the Client somewhere in 7.x
