### ISSUE TITLE
Prototype warnings in the BOINC API headers

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#861]
**Reported by gombasg on 24 Nov 39325552 20:26 UTC**
Hi,

When the BOINC API headers are included from C source code that gets compiled with "-Wstrict-prototypes", they generate a lot of "function declaration isnt a prototype" warnings. The attached patch fixes it by turning "foo()" to "foo(void)".

Gabor

Migrated-From: http://boinc.berkeley.edu/trac/ticket/884

**Comment by romw** [comment]
**Commented by Nicolas on 30 May 39325655 23:33 UTC**
But foo(void) is bad on C++.

**Comment by romw** [comment]
**Commented by gombasg on 10 Sep 39327659 14:13 UTC**
All the changes I posted are inside 'extern "C" { ... }', so the patch has no effect on C++.

**Comment by Ageless93** [comment]
Is this still an issue?

**Comment by AenBleidd** [comment]
Up
