### ISSUE TITLE
Task switch before 100[pct] reached

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#869]
**Reported by rebirther on 24 Mar 39375237 13:20 UTC**
This is a bad habit of BOINC 1sec before a WU could be finished, the task switched to another project.

Win32, Quad

Migrated-From: http://boinc.berkeley.edu/trac/ticket/892

**Comment by ChristianBeer** [comment]
Since BOINC can't know that the task will certainly finish within the next second this is correct behavior.
