### ISSUE TITLE
Debt Resetting on No Work Available

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#879]
**Reported by The Gas Giant on 21 Jan 39400924 20:26 UTC**
I am running Malaria Control, Milkyway, LHC, ABC, SETI and PrimeGrid.  My preferences are set up so that Malaria Control, Milkyway and LHC are my primary projects with ABC, SETI and PrimeGrid set up with small resource shares so that when the other projects have work they do not take over the computer.  However, Ive seen the change in BOINC where if a project asks for work and it receives none then BOINC resets the debt for that project.  I know the change was made to ensure massive debts were not built up, but this basically means that BOINC will never even try to honour the preferences I have set up.  Wouldnt it be better to build debt up to a maximum amount of debt (say a week of cpu time) so that once a project has work BOINC tries to crunch that project as much as it can?

This is specifically relevant to a project like Milkyway where a computer only sporadically receives work during the day, but once it gets it, it can sit there not crunching it until enough debt is built up to warrant spending some cpu time on it.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/902

**Comment by romw** [comment]
**Commented by davea on 16 Oct 39402904 22:13 UTC**
I don't understand this; are you talking about "CPU scheduling priority"
(formerly known as "short term debt")
or CPU work fetch priority?

**Comment by ChristianBeer** [comment]
Closing since request was unclear and may not apply anymore.
