### ISSUE TITLE
Drupal integration

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#884]
**Reported by davea on 16 Dec 39411012 16:26 UTC**
We're assessing the feasibility of integrating BOINC's
web features with Drupal
(an excellent and actively-developed framework for social web sites).
Wherever possible, BOINC features would be replaced by
their Drupal counterparts (forums, profiles, etc.).

The intended effects of this are:
- To make it easier for projects to have good-looking,
  distinctive web sites.
- To make it easier for projects to add content to their sites.
- To eliminate most of BOINC's web code
  (and thus not have to maintain it anymore,
  which is time-consuming and orthogonal to the purpose
  of doing distributed computing).

This is is at least 6 months off,
and we'll provide a migration path so projects don't have
to switch to Drupal right away.

More information on DrupalConversion.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/907

**Comment by brevilo** [comment]
FYI, we're expecting our first production release within the next two months...

**Comment by marius311** [comment]
Hi guys, I've started playing with getting this installed in [boinc-server-docker](https://github.com/marius311/boinc-server-docker) so its easy for anyone to get a Drupal based BOINC project going. I'm interested in taking Cosmology@Home to this in the future, but need to understand alot of things better.

* @romw's message certainly sounds like this the future of BOINC. Is that the case?
* I see that Drupal 6 (on which the docs suggest this is based) reached its end-of-life last week. Are there plans to upgrade?
* Speaking of which, to what extent is https://boinc.berkeley.edu/trac/wiki/InstallDrupal up-to-date? 
* Anything else I should know as I start playing with this? 

Thanks.

**Comment by marius311** [comment]
Followup question, where is the best place to ask specific questions about the setup process as I run into issues? (here, mailing lists, etc..?)

**Comment by davidpanderson** [comment]
The boinc_dev@ssl.berkeley.edu email list is the best place.
-- D

**Comment by brevilo** [comment]
@marius311 

* Yes, we do plan to upgrade to D8 *after* our production release (ASAP)
* The wiki docs are more or less up-to-date, just give it a try

**Comment by brevilo** [comment]
The BOINC Drupal integration was deployed at Einstein@Home in August 2016. We're currently finalizing the current release by fixing a few [pending issues](https://dev.gridrepublic.org/issues/?jql=fixVersion%20%3D%20%22Einstein%20release%22%20AND%20project%20%3D%20DBOINCP%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20priority%20DESC) concerning translations. The feature can already be considered mature nevertheless. Closing this issue.
