### ISSUE TITLE
[PATCH] server status page needs detail by CPU/GPU/app

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#890]
**Reported by zombie67 on 9 May 39447692 16:26 UTC**
The server status page _really_ needs to have the queue numbers split out to detail both CPU and GPU tasks, and by app (when there are more than one). Here are some examples from other projects:

http://boinc.umiacs.umd.edu/server_status.php

http://www.rechenkraft.net/yoyo/server_status.php

See "Results by Application" section for each. Very helpful! Also helps reduce posts like "Are we out of work? Or is there a problem with the server?"

Migrated-From: http://boinc.berkeley.edu/trac/ticket/913

**Comment by romw** [comment]
**Commented by ChristianB on 25 Apr 40708708 01:20 UTC**
Added a patch derived from rnaworld server_status.php. My VirtualPC is still on strike so I couldn't test this but it worked on rnaworld before.

**Comment by romw** [comment]
**Commented by davea on 14 Jul 40708997 15:06 UTC**
(In [22361]) - web: move server status page from ops/ to user/.
    Remove funky file-writing stuff - just use caching.
    fixes #913
- web: include link to server status page on sample front page

**Comment by romw** [comment]
**Commented by davea on 29 Dec 40708998 00:53 UTC**
Actually [22361] doesn't have the requested feature
(breakdown by app version)

**Comment by ChristianBeer** [comment]
The current server_status.php has this feature.
