### ISSUE TITLE
BOINC (All Versions) Intermittently Breaks DirectX (DX9.0c) Audio

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#892]
**Reported by Seldon2k on 29 Nov 39457130 19:06 UTC**
I have been running SETI@home since 1999.
Since the use of BOINC I have had an intermittent but persistant problem.

If BOINC has been running for more than a few hours, (8 hrs to 36 hrs), and I try to watch a video or play an mp3, I get a message that files are probably corrupt and it can't play them.
If I am attempting to watch streaming video I can but with NO sound.
e.g. YouTube lets me watch all movies silently, with no error messages.
Closing BOINC has no effect on this.
Only Rebooting the PC will fix it.

I have had this on two different PC's both running WinXP Pro with DX9.0c.

The first was an AMD 1.3GHz and the second an Intel 2.8GHz P4 (HT).
DirectX Diag reports no errors with drivers etc on both machines.

I can't remember what it reports during a fail condition as I have got into the habit of rebooting and not testing. I will try to remember to test again on the next fail.

Probably Unrelated but,
The first PC had an nVidia AGP graphics card running two monitors.
The second PC has two ATI Radeon Cards (AGP & PCI) running four monitors.
It also has two sound cards, the on-board Realtec for 5.1 Output and a SB PCI Card for Input.

Each time a new version of BOINC came out I was hopping this would be fixed.

I have now come to the conclussion that I am the only person experiencing this behaviour and decided to open a ticket on it.

My searches have revealed a DirectX VIDEO problem that was stopped by closing the BOINC manager, and fixed in a later version of 5.x of BOINC. It was therfore closed.

This seemed to be linked to the use of the BOINC screensaver, I run NO screensavers,
except that 'power-options.cpl' turns the screen off after 20 minutes.

One last thing I always run WinXP in Classic Mode with ALL 'Visual Enhancements' turned OFF. It looks just like Win98SE, and runs much smoother.

Hope someone can help with this AUDIO related problem that ONLY happens when BOINC is running.

It 'SEEMS' unrelated to the task running under BOINC, I am currently running version 6.6.28.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/915

**Comment by ChristianBeer** [comment]
Closing because of the age of the report.
