### ISSUE TITLE
Associate results with app version

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#894]
**Reported by davea on 19 Oct 39457939 14:40 UTC**
Add fields to result table:
- app_versionid (DB ID of app version, or 0 if anonymous platform)
- flops_estimate: what's returned by app_plan(), or p_fpops

This will accomplish at least 2 things:
- make it easier to analyze errors (i.e. what app versions are causing them)
- provide a generic way of computing claimed credit,
  namely elapsed time \* flops_estimate

Migrated-From: http://boinc.berkeley.edu/trac/ticket/917

**Comment by romw** [comment]
**Commented by davea on 14 Aug 39457942 16:53 UTC**
Also: (requested by Kevin):
add a field that stores the timestamp when the result reached its
'final' status.  I.e. this field would be set when the result reaches one
of the final statuses:

server_state = 5 and outcome = 1 and validate_state in (1,2)
or
server_state = 5 and outcome in (3,5)

**Comment by romw** [comment]
**Commented by Nicolas on 23 Jul 39457949 10:13 UTC**
Format description.

**Comment by romw** [comment]
**Commented by davea on 10 May 39459948 17:20 UTC**
Also: report and store CPU time and elapsed time separately.

**Comment by ChristianBeer** [comment]
Missing feature from the list above:

> add a field that stores the timestamp when the result reached its
> 'final' status. I.e. this field would be set when the result reaches one
> of the final statuses:
> 
> server_state = 5 and outcome = 1 and validate_state in (1,2)
> or
> server_state = 5 and outcome in (3,5)

**Comment by davidpanderson** [comment]
The result.mod_time field, added at some point, more or less serves this purpose.
The last update to a result is the change to file_delete_state, and that generally occurs shortly after the update to server state and outcome.
