### ISSUE TITLE
Comp on 96[pct], Boinc computing 100[pct], cannot complete project in time

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#897]
**Reported by lburden on 21 Jun 39463694 11:06 UTC**
I run Spinhenge 70% on my Win XP64 system (AMD 4000 processor) using the XP 64bit version of Boinc.  My computer used to polish off a project in 39 minutes until I got version 6.6.36.  Now I get a message that the Computer is on 96% with Boinc computing 100% of the time, therefore the project cannot be completed in time so it won't get a project.  Other projects still work.   My slower computers with older versions of Boinc still gets projects fine.  I went back to 6.4.7 and now projects are downloading again.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/920

**Comment by ChristianBeer** [comment]
Most likely fixed in a newer version.
