### ISSUE TITLE
Boinc GUI is mirrored

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#911]
**Reported by harley84 on 17 Nov 39527312 07:06 UTC**
Even though my Windows XP is an English version, my regional and Language options specify that I am using Hebrew preferences and located in Israel. Perhaps thats why all GUI looks mirrored to me. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/934

**Comment by ChristianBeer** [comment]
This is an old report and it needs to be verified if this is still happening with a current version.

**Comment by Ageless93** [comment]
Any users in Israel reading this who can check if this is still an issue with BOINC 7.6.33 or 7.8.1?

**Comment by AenBleidd** [comment]
Yes, it is still an issue, please see screenshot, BOINC version 7.12.1
![image](https://user-images.githubusercontent.com/3234209/45722959-a49d9480-bbb7-11e8-8cff-b29e622e64eb.png)

**Comment by lfield** [comment]
Closing as duplicate of  #988
