### ISSUE TITLE
Boinc doesn't build onopensolaris (with patch)

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#927]
**Reported by mich181189 on 11 Feb 39602579 12:53 UTC**
Boinc doesn't build on opensolaris because it fails on res_init not being declared. The key is to link against resolv.so. A patch is attached that adds this to the solaris line in autoconf.

(patched from 6.6.39 but should probably work on pretty much any release)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/950

**Comment by romw** [comment]
**Commented by korpela on 1 Feb 39602665 00:00 UTC**
I'll check to make sure the patch works on (non-open) Solaris 10 before committing.

**Comment by romw** [comment]
**Commented by mich181189 on 8 Jul 39602680 13:46 UTC**
jut noticed it doesn't quite work on opensolaris - looks like it needs to be added somewhere else. Exactly where I'm not sure as I'm not very familiar with the build system, but it needs to end up in client/Makefile on the BOINC_EXTRA_LIBS line. (I forgot to check it on a clean build initially)

**Comment by romw** [comment]
**Commented by mich181189 on 24 Sep 39602722 05:46 UTC**
resolv is mentioned in other parts of the configure.ac file so maybe something else is going on, either way, the result is that for whatever reason, it's not getting linked in.

**Comment by romw** [comment]
**Commented by mich181189 on 7 Aug 39602733 03:33 UTC**
further to my last comment, it's mentioned on line 409 where it is added to STATIC_LIB_LIST so this patch is somewhat irrelevant.

**Comment by romw** [comment]
**Commented by mich181189 on 9 Sep 39603209 00:53 UTC**
The more I use this, the more I realise it's going to take a lot more work to get this working out of the box. (for example, the client reports itself as i386-pc-solaris not the i686-pc-solaris the projects are configured for!) so it's probably a bit simplistic to expect this patch to do much.

**Comment by romw** [comment]
**Commented by korpela on 15 Jul 39603266 22:13 UTC**
Opensolaris must report itself much differently to config.guess to than earlier sun colaris revisions did.  When I run on Solaris 10 I get a BOINC_PLATFORM of i686-pc-solaris.  Are you sure you are looking at BOINC_PLATFORM and not host, build or target?

**Comment by romw** [comment]
**Commented by korpela on 10 Jan 39603268 21:46 UTC**
If so, please upload config.log and config.h.

**Comment by romw** [comment]
**Commented by mich181189 on 8 Jun 39606281 21:46 UTC**
Yes, it's definitely thinking that's the platform, I actually saw it report it to my boinc server as i386-pc-solaris - I think I've discovered a bit in config.guess that when tweaked, reads it correctly (for some  reason, there is no mention if i686-pc-solaris in there, only i386-pc-solaris) I've also now tracked down that for some reason, libresolv, although it was in the list of static libraries, wasn't actually checked for existance or added to the list to link in. What supprises me more is that this was presumably included in other builds (or it was not needed) either way, I'll attach a patch once I'm happy it runs stable enough so you can see what you think. I've put the config.log and config.h on as well (from unpatched version) .

**Comment by romw** [comment]
**Commented by Nicolas on 6 Dec 39740306 11:06 UTC**
Is this still being worked on?

**Comment by ChristianBeer** [comment]
If this is still an issue please file a new one.
