### ISSUE TITLE
Add Windows Explorer link to Data directory to Programs->BOINC

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#932]
**Reported by Ageless on 12 Mar 39708643 08:00 UTC**
Would it be possible that a future version of BOINC gets a path to the Data directory added in the Programs->BOINC folder? That way we (the helpers) can easily point someone to this mythical directory that no-one can find. 

At this moment when we ask someone to look at a certain file in their Data directory, the answer is usually that this directory doesn't exist, the file cannot be found etc. Usually due to the directory being hidden. 

Even on asking to restart BOINC and for them to look at the second or third line from the top which shows the path to the directory, people are unable to find it. 

If a path to the data directory was showing in the Start->Programs->BOINC folder, this would make it a lot easier for us to help people navigate to the directory. 

I do foresee problems with permissions, but this option is probably only necessary on the administrator account(s). 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/955

**Comment by romw** [comment]
**Commented by romw on 13 Jan 40859067 21:20 UTC**
Setup bugs are being punted to a future release.  This work item should be completed with the new open source installer.

**Comment by romw** [comment]
**Commented by davea on 7 Aug 41232376 09:46 UTC**
(In [23282]) - API: compile fixes for MinGW.  Fixes #955.  from Matt Arsenault

**Comment by romw** [comment]
**Commented by Pepo on 16 Feb 41239757 06:40 UTC**
Replying to [davea](comment:3):
> (In [- API: compile fixes for MinGW. Fixes #955. from Matt Arsenault

Is there __anything at all__ common between #955 and [23282](23282]))?? As for the mentioned reason to successfully close #955...

**Comment by romw** [comment]
**Commented by davea on 16 Jul 41241452 09:20 UTC**
I guess I closed the wrong ticket.

**Comment by Ageless93** [comment]
Retracting this issue. We have enough documentation in various places that people should be able to find out how to get there.
