### ISSUE TITLE
Use some of  modified led-icons in BOINC Manager

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#941]
**Reported by Simek on 6 Mar 39957818 07:33 UTC**
We can swap old icons with some icons for led-icons package. We can also add few icons into !MenuBar. Those icons are totally free:

http://led24.de/iconset/

There is my preposition:
http://i46.tinypic.com/19uhyr.jpg

Migrated-From: http://boinc.berkeley.edu/trac/ticket/964

**Comment by romw** [comment]
**Commented by Ageless on 15 Dec 39958966 15:33 UTC**
Escaping unlinkable word. (Add an exclamation point in front of the word).

**Comment by ChristianBeer** [comment]
The example proposition image is no longer available so it is unclear where to use the icons.
