### ISSUE TITLE
Use color to identify work for CPU/GPU

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#949]
**Reported by saldsl on 7 Sep 40007596 04:00 UTC**
In the advanced GUI, under Tasks tab, use different row background colors to identify WUs for CPU or GPU.
e.g. WU for CPU use blue, WU for GPU-nvidia use green, WU for GPU-ati use red

In this manner you could rapidly identify wich kind of work you have available in the queue.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/972

**Comment by ChristianBeer** [comment]
@AenBleidd I see you have worked on this in your personal fork already. Are you going to create a pull requets for this?

**Comment by AenBleidd** [comment]
@ChristianBeer Yes, the fix for this issue is not completed yet because it's happened to be a little bit more complicated as I expected before so it needs additional time but I'll finish it hopefully until end of spring.

**Comment by Ageless93** [comment]
@AenBleidd, Spring of 2018? ;-)

**Comment by AenBleidd** [comment]
@Ageless93, Seems you're right :-) I'll try to do it faster.

**Comment by Ageless93** [comment]
I hope I am not sending too much work in your direction. Just walking
through the issues list and see what can be closed, or what's small enough
that it can be done immediately (read: within the next test cycle of the
present BOINC 7.8)
If I should send some in Juha's direction as well, or if you want to share
with him, that's fine with me.


-- Jord van der Elst.

**Comment by AenBleidd** [comment]
@Ageless93 No, it's ok. I just have an unpredictable schedule so I can't tell for sure when I can do smth. Mostly it's related to my job :)

**Comment by AenBleidd** [comment]
While this looks like an interesting idea, however even now it's not so hard to identify GPU tasks just by looking at the 'Status' column.
Adding custom colors will just add a lot of visual noise.

Thus closing this as "won't fix"
