### ISSUE TITLE
No new GPU tasks and No new CPU tasks button

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#963]
**Reported by MarkJ on 25 Nov 40215995 04:00 UTC**
From the Seti Number Crunching forum. Requested by hiamps.

"Not that it would happen soon but it would be cool to have a couple extra buttons on the Projects tab page. We have "No new Tasks" but it would be helpful if there were also a "No CPU Tasks" and "No GPU Tasks". I assume both can be done by advanced users but I don't know how to stop boinc from downloading to CPU and still get GPU. A new button would be the easiest for the most. My CPU has plenty of work yet every now and then it still asks...."

Migrated-From: http://boinc.berkeley.edu/trac/ticket/986

**Comment by Ageless93** [comment]
There are no CPU tasks and GPU tasks. There are tasks and they're appointed to the correct hardware by the scheduler. The project preference pages have the settings for "Use CPU" and "Use AMD/Nvidia/Intel GPU", so when you do not want to receive work for a specific hardware resource, you can set it through there. Those restrictions will go in on the next contact with the project.
