### ISSUE TITLE
CPU Core access change 50[pct] to 100[pct], either BOINC or AQUA bug...

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#966]
**Reported by aspadistra on 25 Aug 40381052 21:46 UTC**
'''The BOINC started running the AQUA application with only one core initially!'''

'''BOINC fetched the 2 core work unit when it should not have.'''

''The AQUA application is a 2 core CPU application only, as far as I know.''

CPU Core access change 50% to 100% leading to application scheduling failure.

The AQUA 2 core application was permitted to start on 1 core.

The application continued to run on 1 core (to about 0.50%) until I restarted BOINC.

The application lost everything on restart (that is to say it was a total restart at 0.00%).

Either BOINC or AQUA @ Home bug ... both entities need to chat with each other to see who's error it is.

The offending application, that is either being mis-handled by BOINC or is just buggy...

"'''D-Wave's Iterative QUANtum Algorithms : Multi-Threaded'''"
-- It is heavily written in X86-32 assembler, with MMX and SSE.
-- Either it is an Assembler bug or a BOINC client scheduler bug.
-- However, there may be a subtle 'Multicore' BOINC bug at work here.

The loss in CPU time was not great, so far I would say under 30 minutes.

I am not pissed off about it, but miffed.
This kind of bug will annoy people.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/989

**Comment by romw** [comment]
**Commented by davea on 9 Mar 40381168 23:33 UTC**
Please set <cpu_sched_debug> and send message log

**Comment by romw** [comment]
**Commented by LiSrt on 13 Apr 40755554 22:40 UTC**
I think something similar is happening to me, a 4-core Aqua unit can be waiting to run, and it is as if the cores are "reserved", so that other projects can't use them, even though Aqua is not (for example, 1 core is running another project, and Aqua is waiting for all 4 cores to be free, but isn't doing anything).

The issue is also described here:
http://aqua.dwavesys.com/forum_thread.php?id=620

**Comment by ChristianBeer** [comment]
This looks like a common problem with multi threaded applications. Since the AQUA@home project is not around anymore I'm closing this. If there is a similar issue with a current project please open a new issue.
