### ISSUE TITLE
Tray icon menu won't stay open

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#970]
**Reported by Nicolas on 8 Oct 40399756 06:13 UTC**
When I right-click on the BOINC Manager tray icon, a context menu appears, but it immediately disappears when I release the right mouse button. The only way to activate an item in the menu is to hold the right mouse button and move to the menu item I want. I can't first open the menu, and then click on the menu item.

This is self-compiled BOINC Manager trunk r21618, on Linux, with wxWidgets 2.8.10.1 and GTK 2.20.1.

I'm running KDE 4.4, which may be quite relevant. There were changes in the handling of tray icons in Plasma between KDE 4.3 and KDE 4.4; although it's possible those changes didn't affect anything outside of native KDE apps (new KNotificationItem API).

Migrated-From: http://boinc.berkeley.edu/trac/ticket/993

**Comment by romw** [comment]
**Commented by mjakubicek on 29 Aug 42487581 02:57 UTC**
I can confirm this issue, and its even worse than that -- if you quite the manager from the tray icon menu, it keeps hanging in the background (if I close it from the main menu, this does not happen).

**Comment by romw** [comment]
**Commented by Nicolas on 21 Jul 42804033 02:05 UTC**
Still happening.

**Comment by romw** [comment]
**Commented by Nicolas on 11 Sep 45021493 03:40 UTC**
Wow, so many years passed; still happening.

**Comment by ChristianBeer** [comment]
Could not reproduce with 7.6.33 on Debian 9.
