### ISSUE TITLE
BOINC Benchmark

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#971]
**Reported by rebirther on 28 May 40404138 01:20 UTC**
It is not necessary to run the benchmark every 5 days in a running BOINC. Its better to run it every a five days count only if you restart BOINC or as now every new version.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/994

**Comment by romw** [comment]
**Commented by davea on 27 Jun 40709131 05:46 UTC**
(In [22365]) - client: if we successfully did CPU benchmarks,
    don't keep doing them every 5 days unless restart the client
    fixes #994

**Comment by romw** [comment]
**Commented by Pepo on 24 Nov 40749285 18:40 UTC**
Replying to [davea](comment:2):
> ...if we successfully did CPU benchmarks, don't keep doing them every 5 days unless restart the client...
[as [comment:0 rebirther]([BR]]
But) noted:
> ...only if you restart BOINC or as now every new version.

Today I've updated 6.11.7 -> 6.11.8 (Win7, compatibility install). In a few seconds after automatic post-install-start I've noticed, that the Mgr+client are running under admin's account, so I've stopped them (just during an unfinished benchmark). After new start (under the intended plain-user account), the new client did not do benchmarks at all.
[[[BR]([BR]])]
What about machines (like notebooks, etc), which speed (CPU frequency) does vary with time and temperature and else, while the client might be running uninterrupted for weeks?

**Comment by romw** [comment]
**Commented by Richard Haselgrove on 24 Jan 44172054 18:54 UTC**
The code in [22365] - now 2985faec - doesn't prevent an automatic benchmark being run under the following circumstances:

* Start BOINC and run benchmark
* Within 5 days, restart BOINC without changing version or configuration (no benchmark runs)
* Allow to run until 5 days after the initial benchmark.

Solution: When deciding not to run benchmarks at the intermediate restart (not needed: too recent), set did_benchmarks true anyway (on the grounds that it's a continuation of the previous session).

**Comment by ChristianBeer** [comment]
This was last changed in e2ffe54c735badd81679ae8bc0a0b09ec9a032e9 which I guess fixes the issue.
