### ISSUE TITLE
[PATCH] Build fixes under MinGW

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#972]
**Reported by MattArsenault on 15 Feb 40440173 02:13 UTC**
The BOINC libraries in the svn repository currently don't build under mingw on windows, with a few redefinition problems. I've worked around these issues, though I'm not entirely confident I didn't break anything else in the process.

The Makefile for mingw also has a few problems, such as installing the header files twice to different, nonstandard locations, and building for pentium-m. It also wasn't installing one of the headers.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/995

**Comment by romw** [comment]
**Commented by Nicolas on 15 Jan 40440239 04:00 UTC**
Is this patch for SVN trunk?

**Comment by romw** [comment]
**Commented by MattArsenault on 6 Jun 40440242 14:13 UTC**
Replying to [Nicolas](comment:1):
> Is this patch for SVN trunk?

Yes, from a few days ago.

**Comment by romw** [comment]
**Commented by MattArsenault on 25 Dec 41231259 18:13 UTC**
Here's an updated patch for current trunk which also fixes the build with MinGW64. It also gets rid of the extra copy of the mingw makefile which only serves to add confusion, and fixes some warnings.

**Comment by ChristianBeer** [comment]
Fixed in 4a4ee2a013bc4fd2f2a155260e57f61292403f6a but not closed because wrong ticket number was used in commit.
