### ISSUE TITLE
Additional work buffer not satisfied

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#982]
**Reported by sandro tosi on 7 Mar 40623446 21:20 UTC**
Hello,
I have around 20 WUs in the queue, all taking ~5 hours to complete; I have set additional work buffer to 10 days, but on my 4 cores pc those WUs will not take 10 days to run, but much more, so the additional buffer requested is not satisfied.

It seems to happen that that buffer is filled, then almost all the WUs are consumed and the it's filled again, while I think it has to be a continous process, keep filling the buffer as the WUs are completed.

Regards,
Sandro

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1005

**Comment by ChristianBeer** [comment]
A lot has happened to the Client scheduler since this report 7 years ago. Closing because of age.
