### ISSUE TITLE
Localization of right-to-left languages

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#988]
**Reported by mo v on 7 Nov 40709268 20:26 UTC**
Ido Schwartz, the Boinc Hebrew translator, has noticed problems in the Boinc manager Hebrew translation arising from the fact that this language is written right-to-left. He expects the same problems to arise with all RTL languages eg Arabic. 

In Boinc 6.11.6 and again in 6.11.7 he noticed that:
- the text in the Statistics and Disk tabs is inverted and unreadable
- the graphs are inverted from LTR to RTL 
- in the "Simple View" mode, the "Advanced View", "Preferences", "Pause" and "Messages" buttons do not translate. (I am not sure myself, however, whether this is related to the RTL problem)
- in the "Preferences" window the text is aligned to the left instead to the right

Ido has provided 3 screenshots from 6.11.6 showing the problem. In each case part of the BM is shown in its Hebrew and English versions.  

Statistics tab: ![](http://i15.photobucket.com/albums/a390/Dj_Leg0la5/Statistics.jpg)

Disk: ![](http://i15.photobucket.com/albums/a390/Dj_Leg0la5/Disk.jpg)

Simple View: ![](http://i15.photobucket.com/albums/a390/Dj_Leg0la5/simple.jpg)

A resolution of this problem would help our efforts to make Boinc more accessible world-wide. 

Thank you

Mo

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1011

**Comment by romw** [comment]
**Commented by mo.v on 12 Sep 40710417 08:00 UTC**
Ido also says:


As far as I can guess, the problem is the alignment of the entire UI to the right.
I think the alignment includes everything, even the statistics info pic.
As a result, it should be corrected if there will be a checking whether the UI Interface is RTL or not.
If it does, only the content of the Disk and Statistics Tabs - meaning the generated info pics section only - should be aligned back to the left, or another code that generates those info-pics will be needed, only for the RTL Languages.

**Comment by ChristianBeer** [comment]
Possibly related or duplicate of #911. Needs to be tested with current 7.6.33

**Comment by AenBleidd** [comment]
Still an issue. Please take a look at my comment in #911

**Comment by talregev** [comment]
The problem is more simple.
There is in the code mirror view.
Don't use it.
It not effect the text, and it only in this tab.

**Comment by AenBleidd** [comment]
@talregev, how about fixing it? You're among these rare people who use Hebrew and could really see the problem and verify it ;)

**Comment by talregev** [comment]
@AenBleidd I don't find the mirror in the code. If some one can point where there is the decision  of if is RTL or not. 
Also English speaker can verify this bug.
As I mention in my ticket:
https://github.com/BOINC/boinc/issues/3822#event-3804103560
You can see the Boinc word is mirror also. So when the boinc word will be ok, also the hebrew.

**Comment by talregev** [comment]
Can you add this to some milestone?
