### ISSUE TITLE
Web files and styles tweaks

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#989]
**Reported by Simek on 2 Sep 40711521 22:13 UTC**
Some tweaks for web files and styles. Changes including:
- "pointer" cursor for buttons
- most of non stylized "inputs" are now stylised
- minor tables visual tweaks

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1012

**Comment by romw** [comment]
**Commented by davea on 14 Nov 40722859 01:20 UTC**
(In [22394]) - web: appearance tweaks from Simek; fixes #1012

**Comment by ChristianBeer** [comment]
Path in original ticket was applied.
