### ISSUE TITLE
avoid N^2 algorithms in scheduler

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#994]
**Reported by davea on 22 Oct 40750082 14:13 UTC**
DB_SCHED_RESULT_ITEM_SET and associated code has a number of algorithms that are N^2^ in the # of results being reported.  Bad if N is, say, 10000.  Use std::map to avoid this

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1017

**Comment by ChristianBeer** [comment]
Needs to be checked if this still applies. Keep in mind that `std::map` is a sorted container while `std::unordered_map` is not and thus faster (but only available in C++11). There is a STL class `hash_map` that can be used instead of `std::unordered_map`.

**Comment by Ageless93** [comment]
Is this still an issue?

**Comment by lfield** [comment]
After 8 years, if this was an issue someone would have reported a performance issue.

**Comment by davidpanderson** [comment]
People have reported performance issues.  They affect clients with lots (1000s) of jobs

**Comment by RichardHaselgrove** [comment]
In a recent discussion at SETI (within the last week), it was asserted that:

> All BOINC versions past 7.0.2 have the 1000 task limit. Only the specially compiled 7.4.44 has the 3000 task limit.

I don't see any mention of that in the change log for 7.0.2 or immediately before, but I'll try to look through the code later today. If BOINC does currently have such a limit, that should cap any performance problems except for those who deliberately use the open-source nature of BOINC to bypass it.

**Comment by RichardHaselgrove** [comment]
The only reference to task limits I can find is 08d7dcd6d96ef0f993306fa2c697539a55e7c098, but that's denominated in time, not volume. The SETI reporting group is notoriously vague, so it may take some time to track this assertion down, unless anyone else can remember it?

**Comment by RichardHaselgrove** [comment]
D'oh. Lack of coffee error. b52d98b640342a559818e2677a7deefb21d6d82d - that was introduced in v7.2.2

**Comment by adamradocz** [comment]
[This thread ](https://stackoverflow.com/questions/2196995/is-there-any-advantage-of-using-map-over-unordered-map-in-case-of-trivial-keys)could be useful about the `std::map` vs `std::unordered_map`
