### ISSUE TITLE
crypt_prog output should be improved

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#996]
**Reported by teleyinex on 26 Mar 40759857 07:33 UTC**
When you type in the command line: crypt_prog you only get the following message:

"missing command"

The output doesn't help the user giving an option to obtain help from the command. On the other side, if you type: crypt_prog -help, you get the following message:

"unrecognized command"

After checking the source code, I realized that this command lacks this option. This command line argument should be included to help users understand what this command does, and more importantly all the options that can be managed. 

I have created a patch that addresses the described problems. If the patch is applied, when you run the command: crypt_prog you obtain the following message:

missing command

Try !`crypt_prog -help` for more information.

If then you run crypt_prog -help you obtain the following output:

Utility program for encryption.[n private_keyfile public_keyfile[[BR]([BR]]-genkey)] create a key pair with n bits (512 <= n <= 1024)[write it in hex notation[[BR]([BR]])]-sign file private_keyfile[create a signature for a given file[[BR]([BR]])] write it in hex notation[string private_keyfile[[BR]([BR]]-sign_string)] create a signature for a given string[write it in hex notation[[BR]([BR]])]-verify file signature_file public_keyfile[verify a signature[[BR]([BR]])]-test_crypt private_keyfile public_keyfile[test encrypt/decrypt[[BR]([BR]])]-convkey o2b/b2o priv/pub input_file output_file[convert keys between BOINC and OpenSSL format[[BR]([BR]])]-cert_verify file signature_file certificate_dir[[BR]] verify a signature using a directory of certificates

This information has been obtained from the beginning of the file crypt_prog.cpp. Adjoining is the patch.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1019

**Comment by ChristianBeer** [comment]
Fixed in 859253dba831657591e0d36ea1c6288181fcb450
