### ISSUE TITLE
Scheduler start less than cpu count task

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#998]
**Reported by Udo on 18 Mar 40775644 16:53 UTC**
I have a Core i7 Lenovo W510 notebook. The scheduler start between 3-8 WU for the 8 cores. I expect that alwasy 8 WU are running. AQUA@home runs always on 8 cores but for QMC, SIMAP, etc. I recognized that the WU load changes betwenn 3 - 8 WU without any changes to the config. An CPU benchmark determine always 8 CPUs.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1021

**Comment by romw** [comment]
**Commented by Ageless on 10 Jul 40775824 04:26 UTC**
Not a bug. Do know that Trac is for BOINC bugs, this isn't a bug. 

If you want to request help, please post at the [BOINC forums](http://boinc.berkeley.edu/dev/). 

AQUA is a multithreaded application, which uses all CPUs for one task. Other projects use the 1 task per CPU/core approach. Quite normal.

**Comment by romw** [comment]
**Commented by Udo on 7 Feb 40775855 04:00 UTC**
I think the scheduler is part of the BOINC software. I expect on an eight core cpu that always eight WUs (which uses only on core, like seti, simap, qmc) are running and not 3 or 5. I recognize that a WU ends and no new WU will be started.

**Comment by romw** [comment]
**Commented by ChristianB on 16 Mar 40776368 13:46 UTC**
Udo could you please enable the cpu_sched_debug, cpu_sched and work_fetch_debug  [logging flags](http://boinc.berkeley.edu/wiki/Client_configuration) and send the output to the boinc_dev Mailinglist? It would also be of interest what projects you are attached to and what are the resource shares.

**Comment by romw** [comment]
**Commented by Udo on 28 Dec 40787023 00:26 UTC**
Hello,

ChristianB asked me to send the debug information to the dev mailing list. The last few days I saw no problems
to run 8 WUs on my 8 Cores. But now there are only 4 WUs running. I hope this information could help to determine
the issue. This issue occurs also in the actual beta release of boinc.

Feel free to contact me if you need more information.

Regards,
Udo



10.10.2010 11:55:25        Starting BOINC client version 6.10.58 for windows_x86_64
10.10.2010 11:55:25        log flags: file_xfer, sched_ops, task, cpu_sched, cpu_sched_debug
10.10.2010 11:55:25        Libraries: libcurl/7.19.7 OpenSSL/0.9.8l zlib/1.2.3
10.10.2010 11:55:25        Data directory: C:\Daten\Boinc
10.10.2010 11:55:25        Running under account Udo
10.10.2010 11:55:25        Processor: 8 GenuineIntel Intel(R) Core(TM) i7 CPU       Q 720  @ 1.60GHz [6 Model 30 Stepping 5](Family)
10.10.2010 11:55:25        Processor: 256.00 KB cache
10.10.2010 11:55:25        Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss htt tm pni ssse3 cx16 sse4_1 sse4_2 syscall nx lm vmx smx tm2 popcnt pbe
10.10.2010 11:55:25        OS: Microsoft Windows 7: x64 Edition, (06.01.7600.00)
10.10.2010 11:55:25        Memory: 5.93 GB physical, 11.86 GB virtual
10.10.2010 11:55:25        Disk: 219.72 GB total, 157.36 GB free
10.10.2010 11:55:25        Local time is UTC +2 hours
10.10.2010 11:55:25        NVIDIA GPU 0: Quadro FX 880M (driver version 25738, CUDA version 3010, compute capability 1.2, 987MB, 116 GFLOPS peak)
10.10.2010 11:55:25        Version change (6.11.9 -> 6.10.58)



14.10.2010 07:46:47        [work fetch start
14.10.2010 07:46:47        [wfd](wfd]:) ------- start work fetch state -------
14.10.2010 07:46:47        [target work buffer: 86400.00 + 864000.00 sec
14.10.2010 07:46:47        [wfd](wfd]) CPU: shortfall 0.00 nidle 0.00 saturated 1051099.31 busy 0.00 RS fetchable 500.00 runnable 600.00
14.10.2010 07:46:47    AQUA@home    [CPU: fetch share 0.20 LTD -39337.65 backoff dt 0.00 int 0.00
14.10.2010 07:46:47    rosetta@home    [wfd](wfd]) CPU: fetch share 0.20 LTD -6863.17 backoff dt 0.00 int 0.00
14.10.2010 07:46:47    boincsimap    [CPU: fetch share 0.20 LTD -105321.82 backoff dt 0.00 int 0.00
14.10.2010 07:46:47    The Lattice Project    [wfd](wfd]) CPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 86400.00 (no new tasks)
14.10.2010 07:46:47    climateprediction.net    [CPU: fetch share 0.00 LTD -4625.67 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:46:47    lhcathome    [wfd](wfd]) CPU: fetch share 0.00 LTD -128.22 backoff dt 38631.15 int 86400.00
14.10.2010 07:46:47    Milkyway@home    [CPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:46:47    QMC@HOME    [wfd](wfd]) CPU: fetch share 0.20 LTD -136160.72 backoff dt 0.00 int 0.00
14.10.2010 07:46:47    SETI@home    [CPU: fetch share 0.20 LTD 0.00 backoff dt 0.00 int 0.00
14.10.2010 07:46:47    GPUGRID    [wfd](wfd]) CPU: fetch share 0.00 LTD 0.00 backoff dt 65562.13 int 86400.00
14.10.2010 07:46:47    PrimeGrid    [CPU: fetch share 0.00 LTD -24838.21 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:46:47        [wfd](wfd]) NVIDIA GPU: shortfall 0.00 nidle 0.00 saturated 1039811.34 busy 90866.21 RS fetchable 700.00 runnable 200.00
14.10.2010 07:46:47    AQUA@home    [NVIDIA GPU: fetch share 0.14 LTD 0.00 backoff dt 0.00 int 86400.00
14.10.2010 07:46:47    rosetta@home    [wfd](wfd]) NVIDIA GPU: fetch share 0.14 LTD 0.00 backoff dt 0.00 int 60.00
14.10.2010 07:46:47    boincsimap    [NVIDIA GPU: fetch share 0.14 LTD 0.00 backoff dt 0.00 int 15360.00
14.10.2010 07:46:47    The Lattice Project    [wfd](wfd]) NVIDIA GPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 86400.00 (no new tasks)
14.10.2010 07:46:47    climateprediction.net    [NVIDIA GPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:46:47    lhcathome    [wfd](wfd]) NVIDIA GPU: fetch share 0.14 LTD 0.00 backoff dt 0.00 int 86400.00
14.10.2010 07:46:47    Milkyway@home    [NVIDIA GPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:46:47    QMC@HOME    [wfd](wfd]) NVIDIA GPU: fetch share 0.14 LTD 0.00 backoff dt 0.00 int 0.00
14.10.2010 07:46:47    SETI@home    [NVIDIA GPU: fetch share 0.14 LTD -18793.26 backoff dt 0.00 int 0.00
14.10.2010 07:46:47    GPUGRID    [wfd](wfd]) NVIDIA GPU: fetch share 0.14 LTD -310567.91 backoff dt 0.00 int 0.00
14.10.2010 07:46:47    PrimeGrid    [NVIDIA GPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:46:47    AQUA@home    [wfd](wfd]) overall LTD -305800.00
14.10.2010 07:46:47    rosetta@home    [overall LTD -20322.29
14.10.2010 07:46:47    boincsimap    [wfd](wfd]) overall LTD -137924.04
14.10.2010 07:46:47    The Lattice Project    [overall LTD 0.00
14.10.2010 07:46:47    climateprediction.net    [wfd](wfd]) overall LTD -208987.12
14.10.2010 07:46:47    lhcathome    [overall LTD -726.99
14.10.2010 07:46:47    Milkyway@home    [wfd](wfd]) overall LTD 0.00
14.10.2010 07:46:47    QMC@HOME    [overall LTD -299045.95
14.10.2010 07:46:47    SETI@home    [wfd](wfd]) overall LTD -1713810.10
14.10.2010 07:46:47    GPUGRID    [overall LTD -737524.47
14.10.2010 07:46:47    PrimeGrid    [wfd](wfd]) overall LTD -24838.21
14.10.2010 07:46:47        [------- end work fetch state -------
14.10.2010 07:46:47        [wfd](wfd]) No project chosen for work fetch
14.10.2010 07:46:47        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:48        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:49        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:50        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:51        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:52        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:53        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:54        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:55        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:56        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:57    SETI@home    Started upload of 22jn10aa.23463.13155.16.10.202_0_0
14.10.2010 07:46:57    SETI@home    Started upload of 22jn10aa.23463.13155.16.10.224_0_0
14.10.2010 07:46:57        [CLIENT_STATE::poll_slow_events(): pers_file_xfers
14.10.2010 07:46:57        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 1 tasks active
14.10.2010 07:46:57        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:58        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:46:59        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:00    climateprediction.net    [cpu_sched_debug](poll_debug]) Request enforce CPU schedule: hadsm3dhet2_jp64_006595614_0 checkpointed
14.10.2010 07:47:00        Project communication failed: attempting access to reference site
14.10.2010 07:47:00        [CLIENT_STATE::poll_slow_events(): file_xfers
14.10.2010 07:47:00    SETI@home    Temporarily failed upload of 22jn10aa.23463.13155.16.10.202_0_0: connect() failed
14.10.2010 07:47:00    SETI@home    Backing off 1 hr 24 min 31 sec on upload of 22jn10aa.23463.13155.16.10.202_0_0
14.10.2010 07:47:00    SETI@home    Temporarily failed upload of 22jn10aa.23463.13155.16.10.224_0_0: connect() failed
14.10.2010 07:47:00    SETI@home    Backing off 3 hr 59 min 15 sec on upload of 22jn10aa.23463.13155.16.10.224_0_0
14.10.2010 07:47:00        [poll_debug](poll_debug]) CLIENT_STATE::poll_slow_events(): pers_file_xfers
14.10.2010 07:47:00        [enforce_schedule(): start
14.10.2010 07:47:00        [cpu_sched_debug](cpu_sched_debug]) preliminary job list:
14.10.2010 07:47:00    GPUGRID    [0: 63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0 (MD: yes; UTS: no)
14.10.2010 07:47:00    climateprediction.net    [cpu_sched_debug](cpu_sched_debug]) 1: hadsm3dhet2_jp64_006595614_0 (MD: no; UTS: yes)
14.10.2010 07:47:00    AQUA@home    [2: iq64A1_101006b_12_55_0 (MD: no; UTS: no)
14.10.2010 07:47:00        [cpu_sched_debug](cpu_sched_debug]) final job list:
14.10.2010 07:47:00    GPUGRID    [0: 63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0 (MD: yes; UTS: no)
14.10.2010 07:47:00    climateprediction.net    [cpu_sched_debug](cpu_sched_debug]) 1: hadsm3dhet2_jp64_006595614_0 (MD: no; UTS: yes)
14.10.2010 07:47:00    boincsimap    [2: 10100101.086134_0 (MD: no; UTS: yes)
14.10.2010 07:47:00    rosetta@home    [cpu_sched_debug](cpu_sched_debug]) 3: mem_widd_run03_centroid_B_1c3w_SAVE_ALL_OUT_IGNORE_THE_REST_22362_1760_0 (MD: no; UTS: yes)
14.10.2010 07:47:00    QMC@HOME    [4: qasino_p7c-c2h2_01_parasweep.91_0 (MD: no; UTS: yes)
14.10.2010 07:47:00    AQUA@home    [cpu_sched_debug](cpu_sched_debug]) 5: iq64A1_101006b_12_55_0 (MD: no; UTS: no)
14.10.2010 07:47:00    GPUGRID    [scheduling 63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0
14.10.2010 07:47:00    climateprediction.net    [cpu_sched_debug](cpu_sched_debug]) scheduling hadsm3dhet2_jp64_006595614_0
14.10.2010 07:47:00    boincsimap    [scheduling 10100101.086134_0
14.10.2010 07:47:00    rosetta@home    [cpu_sched_debug](cpu_sched_debug]) scheduling mem_widd_run03_centroid_B_1c3w_SAVE_ALL_OUT_IGNORE_THE_REST_22362_1760_0
14.10.2010 07:47:00    QMC@HOME    [scheduling qasino_p7c-c2h2_01_parasweep.91_0
14.10.2010 07:47:00    AQUA@home    [cpu_sched_debug](cpu_sched_debug]) not enough CPUs for multithread job, skipping iq64A1_101006b_12_55_0
14.10.2010 07:47:00        [using 4.14 out of 8 CPUs
14.10.2010 07:47:00        [wfd](cpu_sched_debug]) Request work fetch: CPUs idle
14.10.2010 07:47:00    boincsimap    [10100101.056612_1 sched state 1 next 1 task state 0
14.10.2010 07:47:00    climateprediction.net    [cpu_sched_debug](cpu_sched_debug]) hadsm3dhet2_jp64_006595614_0 sched state 2 next 2 task state 1
14.10.2010 07:47:00    boincsimap    [10100101.058028_1 sched state 1 next 1 task state 0
14.10.2010 07:47:00    boincsimap    [cpu_sched_debug](cpu_sched_debug]) 10100101.073070_1 sched state 1 next 1 task state 0
14.10.2010 07:47:00    QMC@HOME    [qasino_hftz-c2h2_mosweep.252_1 sched state 1 next 1 task state 0
14.10.2010 07:47:00    QMC@HOME    [cpu_sched_debug](cpu_sched_debug]) qasino_p7c-c2h2_01_parasweep.93_0 sched state 1 next 1 task state 0
14.10.2010 07:47:00    SETI@home    [08jn10ab.22964.9883.8.10.239_0 sched state 1 next 1 task state 0
14.10.2010 07:47:00    GPUGRID    [cpu_sched_debug](cpu_sched_debug]) 63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0 sched state 2 next 2 task state 1
14.10.2010 07:47:00    QMC@HOME    [qasino_p7c-c2h2_01_parasweep.91_0 sched state 2 next 2 task state 1
14.10.2010 07:47:00    rosetta@home    [cpu_sched_debug](cpu_sched_debug]) mem_widd_run03_centroid_B_1c3w_SAVE_ALL_OUT_IGNORE_THE_REST_22362_1760_0 sched state 2 next 2 task state 1
14.10.2010 07:47:00    boincsimap    [10100101.086134_0 sched state 2 next 2 task state 1
14.10.2010 07:47:00        [cpu_sched_debug](cpu_sched_debug]) enforce_schedule: end
14.10.2010 07:47:00        [CLIENT_STATE::do_something(): End poll: 2 tasks active
14.10.2010 07:47:00        [poll_debug](poll_debug]) CLIENT_STATE::poll_slow_events(): gui_http
14.10.2010 07:47:00        [CLIENT_STATE::do_something(): End poll: 1 tasks active
14.10.2010 07:47:00        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:01    QMC@HOME    [Request enforce CPU schedule: qasino_p7c-c2h2_01_parasweep.91_0 checkpointed
14.10.2010 07:47:01        Internet access OK - project servers may be temporarily down.
14.10.2010 07:47:01        [poll_debug](cpu_sched_debug]) CLIENT_STATE::poll_slow_events(): gui_http
14.10.2010 07:47:01        [enforce_schedule(): start
14.10.2010 07:47:01        [cpu_sched_debug](cpu_sched_debug]) preliminary job list:
14.10.2010 07:47:01    GPUGRID    [0: 63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0 (MD: yes; UTS: no)
14.10.2010 07:47:01    climateprediction.net    [cpu_sched_debug](cpu_sched_debug]) 1: hadsm3dhet2_jp64_006595614_0 (MD: no; UTS: yes)
14.10.2010 07:47:01    AQUA@home    [2: iq64A1_101006b_12_55_0 (MD: no; UTS: no)
14.10.2010 07:47:01        [cpu_sched_debug](cpu_sched_debug]) final job list:
14.10.2010 07:47:01    GPUGRID    [0: 63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0 (MD: yes; UTS: no)
14.10.2010 07:47:01    climateprediction.net    [cpu_sched_debug](cpu_sched_debug]) 1: hadsm3dhet2_jp64_006595614_0 (MD: no; UTS: yes)
14.10.2010 07:47:01    boincsimap    [2: 10100101.086134_0 (MD: no; UTS: yes)
14.10.2010 07:47:01    rosetta@home    [cpu_sched_debug](cpu_sched_debug]) 3: mem_widd_run03_centroid_B_1c3w_SAVE_ALL_OUT_IGNORE_THE_REST_22362_1760_0 (MD: no; UTS: yes)
14.10.2010 07:47:01    QMC@HOME    [4: qasino_p7c-c2h2_01_parasweep.91_0 (MD: no; UTS: yes)
14.10.2010 07:47:01    AQUA@home    [cpu_sched_debug](cpu_sched_debug]) 5: iq64A1_101006b_12_55_0 (MD: no; UTS: no)
14.10.2010 07:47:01    GPUGRID    [scheduling 63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0
14.10.2010 07:47:01    climateprediction.net    [cpu_sched_debug](cpu_sched_debug]) scheduling hadsm3dhet2_jp64_006595614_0
14.10.2010 07:47:01    boincsimap    [scheduling 10100101.086134_0
14.10.2010 07:47:01    rosetta@home    [cpu_sched_debug](cpu_sched_debug]) scheduling mem_widd_run03_centroid_B_1c3w_SAVE_ALL_OUT_IGNORE_THE_REST_22362_1760_0
14.10.2010 07:47:01    QMC@HOME    [scheduling qasino_p7c-c2h2_01_parasweep.91_0
14.10.2010 07:47:01    AQUA@home    [cpu_sched_debug](cpu_sched_debug]) not enough CPUs for multithread job, skipping iq64A1_101006b_12_55_0
14.10.2010 07:47:01        [using 4.14 out of 8 CPUs
14.10.2010 07:47:01        [wfd](cpu_sched_debug]) Request work fetch: CPUs idle
14.10.2010 07:47:01    boincsimap    [10100101.056612_1 sched state 1 next 1 task state 0
14.10.2010 07:47:01    climateprediction.net    [cpu_sched_debug](cpu_sched_debug]) hadsm3dhet2_jp64_006595614_0 sched state 2 next 2 task state 1
14.10.2010 07:47:01    boincsimap    [10100101.058028_1 sched state 1 next 1 task state 0
14.10.2010 07:47:01    boincsimap    [cpu_sched_debug](cpu_sched_debug]) 10100101.073070_1 sched state 1 next 1 task state 0
14.10.2010 07:47:01    QMC@HOME    [qasino_hftz-c2h2_mosweep.252_1 sched state 1 next 1 task state 0
14.10.2010 07:47:01    QMC@HOME    [cpu_sched_debug](cpu_sched_debug]) qasino_p7c-c2h2_01_parasweep.93_0 sched state 1 next 1 task state 0
14.10.2010 07:47:01    SETI@home    [08jn10ab.22964.9883.8.10.239_0 sched state 1 next 1 task state 0
14.10.2010 07:47:01    GPUGRID    [cpu_sched_debug](cpu_sched_debug]) 63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0 sched state 2 next 2 task state 1
14.10.2010 07:47:01    QMC@HOME    [qasino_p7c-c2h2_01_parasweep.91_0 sched state 2 next 2 task state 1
14.10.2010 07:47:01    rosetta@home    [cpu_sched_debug](cpu_sched_debug]) mem_widd_run03_centroid_B_1c3w_SAVE_ALL_OUT_IGNORE_THE_REST_22362_1760_0 sched state 2 next 2 task state 1
14.10.2010 07:47:01    boincsimap    [10100101.086134_0 sched state 2 next 2 task state 1
14.10.2010 07:47:01        [cpu_sched_debug](cpu_sched_debug]) enforce_schedule: end
14.10.2010 07:47:01        [CLIENT_STATE::do_something(): End poll: 1 tasks active
14.10.2010 07:47:01        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:02        [work fetch start
14.10.2010 07:47:02        [wfd](wfd]:) ------- start work fetch state -------
14.10.2010 07:47:02        [target work buffer: 86400.00 + 864000.00 sec
14.10.2010 07:47:02        [wfd](wfd]) CPU: shortfall 0.00 nidle 0.00 saturated 1051097.18 busy 0.00 RS fetchable 500.00 runnable 600.00
14.10.2010 07:47:02    AQUA@home    [CPU: fetch share 0.20 LTD -39337.65 backoff dt 0.00 int 0.00
14.10.2010 07:47:02    rosetta@home    [wfd](wfd]) CPU: fetch share 0.20 LTD -6865.07 backoff dt 0.00 int 0.00
14.10.2010 07:47:02    boincsimap    [CPU: fetch share 0.20 LTD -105323.72 backoff dt 0.00 int 0.00
14.10.2010 07:47:02    The Lattice Project    [wfd](wfd]) CPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 86400.00 (no new tasks)
14.10.2010 07:47:02    climateprediction.net    [CPU: fetch share 0.00 LTD -4627.57 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:47:02    lhcathome    [wfd](wfd]) CPU: fetch share 0.00 LTD -128.22 backoff dt 38615.94 int 86400.00
14.10.2010 07:47:02    Milkyway@home    [CPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:47:02    QMC@HOME    [wfd](wfd]) CPU: fetch share 0.20 LTD -136162.62 backoff dt 0.00 int 0.00
14.10.2010 07:47:02    SETI@home    [CPU: fetch share 0.20 LTD 0.00 backoff dt 0.00 int 0.00
14.10.2010 07:47:02    GPUGRID    [wfd](wfd]) CPU: fetch share 0.00 LTD 0.00 backoff dt 65546.91 int 86400.00
14.10.2010 07:47:02    PrimeGrid    [CPU: fetch share 0.00 LTD -24838.21 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:47:02        [wfd](wfd]) NVIDIA GPU: shortfall 0.00 nidle 0.00 saturated 1039806.83 busy 90863.61 RS fetchable 700.00 runnable 200.00
14.10.2010 07:47:02    AQUA@home    [NVIDIA GPU: fetch share 0.14 LTD 0.00 backoff dt 0.00 int 86400.00
14.10.2010 07:47:02    rosetta@home    [wfd](wfd]) NVIDIA GPU: fetch share 0.14 LTD 0.00 backoff dt 0.00 int 60.00
14.10.2010 07:47:02    boincsimap    [NVIDIA GPU: fetch share 0.14 LTD 0.00 backoff dt 0.00 int 15360.00
14.10.2010 07:47:02    The Lattice Project    [wfd](wfd]) NVIDIA GPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 86400.00 (no new tasks)
14.10.2010 07:47:02    climateprediction.net    [NVIDIA GPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:47:02    lhcathome    [wfd](wfd]) NVIDIA GPU: fetch share 0.14 LTD 0.00 backoff dt 0.00 int 86400.00
14.10.2010 07:47:02    Milkyway@home    [NVIDIA GPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:47:02    QMC@HOME    [wfd](wfd]) NVIDIA GPU: fetch share 0.14 LTD 0.00 backoff dt 0.00 int 0.00
14.10.2010 07:47:02    SETI@home    [NVIDIA GPU: fetch share 0.14 LTD -18793.26 backoff dt 0.00 int 0.00
14.10.2010 07:47:02    GPUGRID    [wfd](wfd]) NVIDIA GPU: fetch share 0.14 LTD -310583.12 backoff dt 0.00 int 0.00
14.10.2010 07:47:02    PrimeGrid    [NVIDIA GPU: fetch share 0.00 LTD 0.00 backoff dt 0.00 int 0.00 (no new tasks)
14.10.2010 07:47:02    AQUA@home    [wfd](wfd]) overall LTD -305800.00
14.10.2010 07:47:02    rosetta@home    [overall LTD -20320.77
14.10.2010 07:47:02    boincsimap    [wfd](wfd]) overall LTD -137921.64
14.10.2010 07:47:02    The Lattice Project    [overall LTD 0.00
14.10.2010 07:47:02    climateprediction.net    [wfd](wfd]) overall LTD -208984.01
14.10.2010 07:47:02    lhcathome    [overall LTD -726.99
14.10.2010 07:47:02    Milkyway@home    [wfd](wfd]) overall LTD 0.00
14.10.2010 07:47:02    QMC@HOME    [overall LTD -298964.37
14.10.2010 07:47:02    SETI@home    [wfd](wfd]) overall LTD -1713810.10
14.10.2010 07:47:02    GPUGRID    [overall LTD -737548.70
14.10.2010 07:47:02    PrimeGrid    [wfd](wfd]) overall LTD -24838.21
14.10.2010 07:47:02        [------- end work fetch state -------
14.10.2010 07:47:02        [wfd](wfd]) No project chosen for work fetch
14.10.2010 07:47:02        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:03        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:04        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:05        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:06        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:07        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:08        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:09        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:10        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:11        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:12        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:13        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:14        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:15        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:16        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:17        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:18    rosetta@home    [Request enforce CPU schedule: mem_widd_run03_centroid_B_1c3w_SAVE_ALL_OUT_IGNORE_THE_REST_22362_1760_0 checkpointed
14.10.2010 07:47:18        [cpu_sched_debug](cpu_sched_debug]) enforce_schedule(): start
14.10.2010 07:47:18        [preliminary job list:
14.10.2010 07:47:18    GPUGRID    [cpu_sched_debug](cpu_sched_debug]) 0: 63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0 (MD: yes; UTS: no)
14.10.2010 07:47:18    climateprediction.net    [1: hadsm3dhet2_jp64_006595614_0 (MD: no; UTS: yes)
14.10.2010 07:47:18    AQUA@home    [cpu_sched_debug](cpu_sched_debug]) 2: iq64A1_101006b_12_55_0 (MD: no; UTS: no)
14.10.2010 07:47:18        [final job list:
14.10.2010 07:47:18    GPUGRID    [cpu_sched_debug](cpu_sched_debug]) 0: 63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0 (MD: yes; UTS: no)
14.10.2010 07:47:18    climateprediction.net    [1: hadsm3dhet2_jp64_006595614_0 (MD: no; UTS: yes)
14.10.2010 07:47:18    boincsimap    [cpu_sched_debug](cpu_sched_debug]) 2: 10100101.086134_0 (MD: no; UTS: yes)
14.10.2010 07:47:18    rosetta@home    [3: mem_widd_run03_centroid_B_1c3w_SAVE_ALL_OUT_IGNORE_THE_REST_22362_1760_0 (MD: no; UTS: yes)
14.10.2010 07:47:18    QMC@HOME    [cpu_sched_debug](cpu_sched_debug]) 4: qasino_p7c-c2h2_01_parasweep.91_0 (MD: no; UTS: yes)
14.10.2010 07:47:18    AQUA@home    [5: iq64A1_101006b_12_55_0 (MD: no; UTS: no)
14.10.2010 07:47:18    GPUGRID    [cpu_sched_debug](cpu_sched_debug]) scheduling 63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0
14.10.2010 07:47:18    climateprediction.net    [scheduling hadsm3dhet2_jp64_006595614_0
14.10.2010 07:47:18    boincsimap    [cpu_sched_debug](cpu_sched_debug]) scheduling 10100101.086134_0
14.10.2010 07:47:18    rosetta@home    [scheduling mem_widd_run03_centroid_B_1c3w_SAVE_ALL_OUT_IGNORE_THE_REST_22362_1760_0
14.10.2010 07:47:18    QMC@HOME    [cpu_sched_debug](cpu_sched_debug]) scheduling qasino_p7c-c2h2_01_parasweep.91_0
14.10.2010 07:47:18    AQUA@home    [not enough CPUs for multithread job, skipping iq64A1_101006b_12_55_0
14.10.2010 07:47:18        [cpu_sched_debug](cpu_sched_debug]) using 4.14 out of 8 CPUs
14.10.2010 07:47:18        [Request work fetch: CPUs idle
14.10.2010 07:47:18    boincsimap    [cpu_sched_debug](wfd]) 10100101.056612_1 sched state 1 next 1 task state 0
14.10.2010 07:47:18    climateprediction.net    [hadsm3dhet2_jp64_006595614_0 sched state 2 next 2 task state 1
14.10.2010 07:47:18    boincsimap    [cpu_sched_debug](cpu_sched_debug]) 10100101.058028_1 sched state 1 next 1 task state 0
14.10.2010 07:47:18    boincsimap    [10100101.073070_1 sched state 1 next 1 task state 0
14.10.2010 07:47:18    QMC@HOME    [cpu_sched_debug](cpu_sched_debug]) qasino_hftz-c2h2_mosweep.252_1 sched state 1 next 1 task state 0
14.10.2010 07:47:18    QMC@HOME    [qasino_p7c-c2h2_01_parasweep.93_0 sched state 1 next 1 task state 0
14.10.2010 07:47:18    SETI@home    [cpu_sched_debug](cpu_sched_debug]) 08jn10ab.22964.9883.8.10.239_0 sched state 1 next 1 task state 0
14.10.2010 07:47:18    GPUGRID    [63-KASHIF_HIVPR_n1_bound_so_ba1-42-100-RND3495_0 sched state 2 next 2 task state 1
14.10.2010 07:47:18    QMC@HOME    [cpu_sched_debug](cpu_sched_debug]) qasino_p7c-c2h2_01_parasweep.91_0 sched state 2 next 2 task state 1
14.10.2010 07:47:18    rosetta@home    [mem_widd_run03_centroid_B_1c3w_SAVE_ALL_OUT_IGNORE_THE_REST_22362_1760_0 sched state 2 next 2 task state 1
14.10.2010 07:47:18    boincsimap    [cpu_sched_debug](cpu_sched_debug]) 10100101.086134_0 sched state 2 next 2 task state 1
14.10.2010 07:47:18        [enforce_schedule: end
14.10.2010 07:47:18        [poll_debug](cpu_sched_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:19        [CLIENT_STATE::do_something(): End poll: 0 tasks active
14.10.2010 07:47:20        [poll_debug](poll_debug]) CLIENT_STATE::do_something(): End poll: 0 tasks active

**Comment by romw** [comment]
**Commented by Udo on 25 Dec 40787341 20:26 UTC**
One way to solve the issue is do set in the local setting "on multiprocessor system, use at most" to 90 % and than back to 100 %. After this Boinc chrunching on all cores.

**Comment by ChristianBeer** [comment]
This is a report from 6 years ago. The issue was probably fixed in the meantime. If this is still observed please open a new issue.
